### ISSUE TITLE
Drukhari 

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-9e#1]
**File/Catalogue:** 
Aeldari - Drukhari v1

**BattleScribe version:** 2.01.02.89.

**Platform:** Windows

**Description:** There is an issue with the HTML formatting for the Combat Drugs and Power from Pain force rules. Line breaks are not rendered properly and instead _"\<br/>"_ is shown.

**Comment by amis92** [comment]
We'll wait for BattleScribe update - nothing we can do now.
