### ISSUE TITLE
Imperium - Dark Angels: Talonmaster points not updated

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10008]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I think talon masters are the wrong cost. Still showing 160. 

Thx

**Comment by Thairne** [comment]
Can you guys please decide? :P

https://github.com/BSData/wh40k/commit/4c585c087c729ad6f43b810802a7f51c910c6cc0

just for future reference:

![grafik](https://user-images.githubusercontent.com/8590840/122084167-de039d00-ce01-11eb-9293-f999e1c93918.png)
