### ISSUE TITLE
Blood Angels: Eliminator Las-fusil on Sergeant incorrect points 

### ISSUE THREAD

**Issue by bigjayme** [BSData/wh40k-9e#10003]
**File/Catalogue:** 
Blood Angels v227

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux
iOS
**Dropbox:** Yes/No
No
**Description:** Detailed issue description.
Eliminator Sergeant showing incorrect points, 10 instead of 5, as per Munitorum Field Manual 21

**Comment by acebaur** [comment]
Update your data

**Comment by bigjayme** [comment]
On iOS I have the latest data available. Blood Angels 227. Just rechecked.
Could be an issue that may resolve itself shortly then, if this is fixed in
the latest build.

**Comment by Technoblazed** [comment]
Blood angels is on 228, so you're definitely not on the latest data.

**Comment by bigjayme** [comment]
Yeah, I even deleted my 40k data and regrabbed it. It’s some sort of iOS
not updating issue. Will probably just resolve itself soon when I am able
to download the latest. Thanks!
