### ISSUE TITLE
Imperium - Dark Angels: Heavenfall Blade not available to Primaris Lt

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10014]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I am unable to equip the Heaven fall blade relic to the primaris lieutenant data sheet when it is equipped with the neo volkite, master crafted power sword and storm shield. I am able to do this on all platforms.

**Comment by Mad-Spy** [comment]
Additionally, master-crafted is misspelled in the weapon group name.

![image](https://user-images.githubusercontent.com/29306451/122186835-5ad85a80-ce86-11eb-8905-076e5ac3d536.png)

**Comment by Mad-Spy** [comment]
Checking the "and all child selections" box on all the conditions in the lib is sufficient to fix this.
