### ISSUE TITLE
Deathwatch - Plasma inceptors in Indomitor Killteam, price is less than actual one

### ISSUE THREAD

**Issue by yurahawk** [BSData/wh40k-9e#10012]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by cometeer** [comment]
this is incorrect. points for adding models to killteam are specified independently and haven't changed since release.

**Comment by Mad-Spy** [comment]
@cometeer, what is the reference for your assertion?

**Comment by cometeer** [comment]
> @cometeer, what is the reference for your assertion?

supplement deathwatch (gives specific points for adding to a kill team)
december faq supplement deathwatch (no mention)
munitorum field manual 2021 (no mention)

there are no other documents that apply to supplement deathwatch.

I agree it should have been updated and it's almost certainly intended to use the base costs of codex:sm but thats not how they implemented it.

**Comment by Technoblazed** [comment]
> supplement deathwatch (gives specific points for adding to a kill team)

Can you show me where it says the points for adding to a kill team please?

**Comment by cometeer** [comment]
currently at work, ill grab the books when i get home

**Comment by Technoblazed** [comment]
(I can save you the time, there are no points in the deathwatch book for kill team models, except for the DW specific models)
