### ISSUE TITLE
Adepta Sororitas: missing "Special Weapon" option for Battle Sisters squad

### ISSUE THREAD

**Issue by EBeureux** [BSData/wh40k-9e#10023]
**File/Catalogue:** Imperium - Adepta Sororitas (v160)

**BattleScribe version:** 2.03.21 (Windows) / 2.03.25 (Android)

**Platform:** Windows/Android

**Dropbox:** YNo

**Description:**
When selecting the Battle Sisters Squad Troop choice, there is a button to add "Battle Sister w/ Special or Heavy Weapon", but no button for "Battle Sister w/ Special Weapon". As a result, it is impossible to create a valid roster with the allowed "1 Sister with Special Weapon" and "1 Sister with Special or Heavy Weapon" for a 10-Sisters squad.

![image](https://user-images.githubusercontent.com/55287741/122450288-24463100-cfa7-11eb-8c20-92b5f379b5e0.png)

**Comment by Technoblazed** [comment]
Add more battle sisters to the unit.

**Comment by EBeureux** [comment]
Thanks! Sorry I missed this.
