### ISSUE TITLE
Imperium - Adeptus Astartes - Salamanders: Tome of Vel'cona is too lenient on mixing psychic powers

### ISSUE THREAD

**Issue by Citronnade** [BSData/wh40k-9e#10026]
**File/Catalogue:** Imperium - Adeptus Astartes - Salamanders v9.1.36

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** The Tome of Vel'cona allows a Librarian to know one power from the Promethean discipline in addition to any other powers it knows.  For a regular 2 power Librarian, this means it can either know 2 powers from Librarius/Obscuration by choosing that as their discipline and 1 power from Promethean from Tome, or 3 powers from Promethean by choosing Promethean as their discipline.  Chief Librarian makes it 3/1 or 4.

Currently, BS only requires that a positive number of powers are known from Promethean, allowing for mixes like 2 Librarius/2 Promethean or 1 Librarius/3 Promethean.

**Comment by Citronnade** [comment]
I replicated this using a standard Librarian and a Phobos Librarian to check both Librarius and Obscuration--same problem applies for both.

**Comment by Mad-Spy** [comment]
Salamanders are not properly validating psychic powers correctly in general as you can take powers from both the Codex and Supplement powers lists together without any errors.

The Librarius Discipline in the data is missing the modifiers to set it to max 0 if another discipline is selected.
