### ISSUE TITLE
Imperium - Imperial Fists: Expulsiaris relic not appearing for some models

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10046]
**File:** Imperium - Imperial Fists.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Hi! I would like to report the fact that the section of Exorcists' Relics lacks the relic Expulsiaris that would replace a Power Sword or Master-Crafted Power Sword. It's been a while now that the Exorcists' new rules came out, it would be great if you can add the missing information. Thank you!

**Comment by acebaur** [comment]
It's there but I looks like it isn't showing up on units with nested wargear like the indomitus captain

**Comment by Technoblazed** [comment]
Just another case of the relic only checking for the GST version of the MCPS and the Primaris Captain using the SM-lib MCPS.
