### ISSUE TITLE
Incorrect pts value of shield generator for ta'u XV8 crisis suits

### ISSUE THREAD

**Issue by MatteoCesari78** [BSData/wh40k-9e#10045]
**File/Catalogue:** T'au Empire.cat

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Shield generator for XV8 crisis battlesuits and XV8 crisis bodyguards is 5 pts, the correct value is 10 pts as per the last munitorum field manual

**Comment by AbonShell** [comment]
The newest one that came out with GT 2021 has Shield gen for XV8 and XV25 as 5 pts.

**Comment by MatteoCesari78** [comment]
i was watching the old faq of the old munitorum field of 04/02/2021, my bad, closing
