### ISSUE TITLE
T'au Empire

### ISSUE THREAD

**Issue by KarlosDLem** [BSData/wh40k-9e#10058]
**File/Catalogue:**  T'au Empire v93

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** Unable to enable Commander Shadowsun
in Detachment under the "Supreme Commander" rule.
Example: Second Commander in Farsight Enclaves Detachment

**Comment by Mad-Spy** [comment]
She appears in every Detachment type I try to add her to in the current release, regardless of the Sept Choice, as an HQ.

Is the issue that she is not visible, or that you get some kind of error?

**Comment by Technoblazed** [comment]
You can't use shadowsun as a second commander in a FSE detachment as she is not a FARSIGHT ENCLAVES COMMANDER.
