### ISSUE TITLE
Space Marines Plasma Inceptors Incorrect Cost & Sgt. Issue

### ISSUE THREAD

**Issue by SquaredSee** [BSData/wh40k-9e#10054]
**File/Catalogue:** Imperium - Space Marines.cat

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 
Plasma Exterminators for the Inceptor Squad are priced incorrectly. It should be 40pt base, +10 for Plasma Exterminators. Currently it is +20. I looked in the .cat file and it seems to be because it is priced at +10 and it repeats twice, when it should be priced at +5 and repeat twice.
Also, there is no option to give the Inceptor Sergeant the Plasma Exterminator upgrade.

**Comment by SquaredSee** [comment]
I created a pull request to fix the issue: #10055

**Comment by acebaur** [comment]
They are 10 points per exterminator and they have 2. Points are correct. The Sgts are included in the points calculation
