### ISSUE TITLE
Missing units from marines 

### ISSUE THREAD

**Issue by InquisitorJeff** [BSData/wh40k-9e#10076]
![2026D958-87C8-4AA8-905A-C1981346A4B4](https://user-images.githubusercontent.com/86895520/124367708-b01bb680-dc51-11eb-8891-61df64af70a1.png)
![11C556E8-C33B-46CB-A394-44EEE568E30F](https://user-images.githubusercontent.com/86895520/124367709-b14ce380-dc51-11eb-92be-e151e336f07b.png)
As far as I know the Primars Lieutenants are missing and the repulsor version are missing 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Valorcalls** [comment]
The repulsor isn't a dedicated transport at all, and All LTs are under the LT entry.
