### ISSUE TITLE
Adeptus Mechanicus - Onager Dunecrawler Neutron Laser+Cognis Stubber Points Wrong after change

### ISSUE THREAD

**Issue by Mr-xim** [BSData/wh40k-9e#10074]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** the combination of neutron laser and cognis stubber was increased to 5pts this is wrong heres the rule

 • This model’s eradication beamer can be replaced with one of the following: 1 daedalus missile launcher, 1 gatling rocket launcher and 1 twin icarus autocannon; **1 neutron laser and 1 cognis heavy stubber** this is a free upgrade
; 1 twin Onager heavy phosphor blaster.
 • This model can be equipped with 1 additional **cognis heavy stubber**. This is 5pts and pintle mounted
• This model can be equipped with one of the following: broad spectrum data-tether; smoke launcher

final loadout gives you 2 heavy stubbers for 5pts the pintle mount and the one one the laser under barrel for free

**Comment by AbonShell** [comment]
Because the cogni heavy stubber has points and is on the data sheet as a separate line item, 1 CHS, you pay for the upgrade.

**Comment by Mad-Spy** [comment]
As per @AbonShell's comment, if an item has a cost in the MFM then you must pay for it, regardless of how you get it. Nothing is free unless it has no point entry.

**Comment by Mr-xim** [comment]
this is not how it is in the GW app

**Comment by Technoblazed** [comment]
Then the GW app is wrong.
