### ISSUE TITLE
Space Marines - Veil of Time - Typo

### ISSUE THREAD

**Issue by SenshiKenpachi** [BSData/wh40k-9e#10089]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

nit instead of unit

incorrect:
Details: Blessing: Veil of Time has a warp charge value of 6. If manifested, select one friendly <Chapter> nit within 18" of this Psyker.

correct:
Details: Blessing: Veil of Time has a warp charge value of 6. If manifested, select one friendly <Chapter> **u**nit within 18" of this Psyker.

**Comment by Mad-Spy** [comment]
Fixed typos in report :)
