### ISSUE TITLE
Space Marine Sternguard Heavy Weapons

### ISSUE THREAD

**Issue by MiniJoe101** [BSData/wh40k-9e#10080]
**File/Catalogue:** Space Marines

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** YNo

**Description:** Space Marine Sternguard Veterans are missing heavy weapons including Heavy Bolter. Thanks.

**Comment by Technoblazed** [comment]
Add `Sternguard Veteran w/ Heavy Weapon` from the unit selection options.

**Comment by MiniJoe101** [comment]
Amazing thank you!!!

Joe Haddon- ***@***.***
GB-UK

On 5 Jul 2021, at 18:16, Anthony ***@***.***> wrote:

﻿

Closed #10080<https://github.com/BSData/wh40k/issues/10080>.
