### ISSUE TITLE
Admech: Skitarii Rangers Points Incorrect.

### ISSUE THREAD

**Issue by thehunter97** [BSData/wh40k-9e#10092]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
Admech Skitarii Rangers Alpha: Power Sword points should be 0pts, not 5pts

Admech Skitarii Rangers Special Equiptment: Plasma Caliver should be 10pts not 18, Transuranic Arquebus should be 15pts not 23.

**Comment by Mad-Spy** [comment]
1. Point cost is correct as per p20 of MFM 2021 MkII.
2. You're not just paying for the weapon, you're paying for the model holding it as well.
