### ISSUE TITLE
Imperium - Adeptus Mechanicus v164 - Omnispex + Enhanced Data-Tether

### ISSUE THREAD

**Issue by hagamemnon** [BSData/wh40k-9e#10100]
**File/Catalogue:** Imperium - Adeptus Mechanicus v164

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** Taking an Omnispex + Enhanced Data-Tether on a squad of 0-19 rangers or 0-19 vanguard should throw an error as this combination is only allowed on 20-strong units.

**Comment by Mad-Spy** [comment]
The data is currently allowing 2 selections at 10 models, but should only allow one.
