### ISSUE TITLE
Adepta Sororitas Castigator's bottom profile BS is (3+) should be (5+)

### ISSUE THREAD

**Issue by RamenSea** [BSData/wh40k-9e#10102]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by RamenSea** [comment]
Ok I just fixed it.
Heres a source for the stats https://wahapedia.ru/wh40k9ed/factions/adepta-sororitas/Castigator

**Comment by Thairne** [comment]
While I appreciate the trust, I think this is more an Alphalas issue :D
