### ISSUE TITLE
Imperium - Deathwatch - incorrect or missing power levels

### ISSUE THREAD

**Issue by beefwad13** [BSData/wh40k-9e#10107]
**File/Catalogue:** Imperium - Deathwatch

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 

- On the left side bar, under Troops -> Proteus Kill Team, it says they are 8 PL but when you add the unit it says its 7 PL. According to the codex, it should be 7 PL. can the sidebar value be fixed?

- For a Proteus Kill Team, you can add a "Black Shield" model for 1 PL but it currently has a value of 0PL. can this be fixed to 1 PL?

**Comment by Mad-Spy** [comment]
@Technoblazed, the first part can be fixed by removing the default selection on the Kill Team SEG. It's not needed anyway because you're setting a min on Vets.
