### ISSUE TITLE
Ta'unar missing VEHICLE keyword

### ISSUE THREAD

**Issue by Spacelord44** [BSData/wh40k-9e#10108]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Datasheet on Wahapedia says Ta'unar is a vehicle, but not in battle scribe.

**Comment by Mad-Spy** [comment]
The Tau'nar is a Lord of War and so will only appear in Detachments which can include that type of unit.

**Comment by Spacelord44** [comment]
Yes, but the data sheet in battle scribe doesn't include the vehicle tag.
Is this correct?

**Comment by DrTobogganMD** [comment]
No, it should have it.
