### ISSUE TITLE
Imperium - Incorrect wording on Adeptus Mechanicus Doctrina Imperative

### ISSUE THREAD

**Issue by QubitCrook** [BSData/wh40k-9e#10112]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:**
The AdMech *Selection Rules* currently lists the Doctrina _Bulwark Imperative_ as having the wording:

> +1 save/-3" Move

The codex wording for the part modifying saves is:
> Imrpove the Save characteristic of models in this unit by 1 (models in this unit cannot have a Save characteristic better than 2+)

"+1 save" is being taken in error by players to refer to all saving throws, including invulnerable saving throws. The codex wording to modify the save characteristic is entirely separate from save modifiers. I suggest the entry (along with the inverse wording on _Aggressor Imperative_) be updated to:
> +1 to Save characteristic (max of 2+)/-3" Move

**Comment by Mad-Spy** [comment]
Then those players should provide evidence from their copy of the Codex. The data set is not a replacement for owning the books.

**Comment by QubitCrook** [comment]
> Then those players should provide evidence from their copy of the Codex. The data set is not a replacement for owning the books.

I agree, they should. The wording is still incorrect though: +1 to saves (almost always refers to rolls) and +1 to save characteristic are two wholly different things.
