### ISSUE TITLE
Dark Angels -  Chaplain Ven Dread no option for litanies

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10119]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Chaplain ven dread does not have the options for litanies, i will check and report the space marine data file too, but since it has the priest tags it gets litanies

**Comment by Technoblazed** [comment]
This just needs the litanies adding to the chaplain dread link in the root entries of the DA cat.
