### ISSUE TITLE
GSC - Purestrain Genestealers incorrect points value

### ISSUE THREAD

**Issue by TheCowofEternalFlame** [BSData/wh40k-9e#10111]
**File/Catalogue:** Warhammer 40,000 v9.1.42

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Purestrain Genestealers in the Genestealer Cults roster are set to 15 points per model rather than the correct value of 17

**Comment by Mad-Spy** [comment]
The correct value _is_ 15 as per MFM 2021 MkII.

**Comment by TheCowofEternalFlame** [comment]
> 
> 
> The correct value _is_ 15 as per MFM 2021 MkII.

Oh! Sorry about that. The updated one isn't on Warhammer Community so I didn't see there _was_ an update to that. Thank you for your time and for bringing that to my attention.
