### ISSUE TITLE
No way to create detachments using keywords such as "tzeentch", "heretic astarts" or "adeptus astartes"

### ISSUE THREAD

**Issue by Emixam1** [BSData/wh40k-9e#10136]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Currently, there is no way to create detachments using faction keywords other than codex ones, such as the god keywords (eg, tzeentch, khorne) or other faction keywords (adeptus astartes, heretic astartes, etc)

**Comment by Mad-Spy** [comment]
Yes, there is. https://github.com/BSData/wh40k/wiki/Creating-Detachments-Using-Multiple-Factions

**Comment by acebaur** [comment]
Just as an FYI you won't be battleforged if you make an Adeptus Astartes detachment with multiple chapters. You'd also lose chapter tactics

**Comment by Emixam1** [comment]
Hey Alex, actually, you would be battleforged, though you're right about
losing chapter tactics, doctrines, and everything else
Thanks for getting back to me, it was mostly that I wanted to create a
tzeentch detachment for a new Bash Brothers + Be'lakor list

Best
Maxime
