### ISSUE TITLE
Ork Codex 2021

### ISSUE THREAD

**Issue by tag8833** [BSData/wh40k-9e#10142]
I'm just trying to keep track of my progress, and create a basis for testing and validation.

Initial Datasheets: tag8833
------------
- [x] Battlewagon
- [x] Beast Snagga Boyz
- [x] Nob w/ Banner
- [x] Big'ed BossBunka
- [x] Big Mek in MA
- [x] Big Mek w/ KFF
- [x] Big Mek w/ SAG
- [x] BoneBreaka
- [x] Beastboss on Squigosaur
- [x] Painboss
- [x] Burna-Bommer
- [x] Dakkajet
- [x] Blitza-Bommer
- [x] Deff Dreads
- [x] Deffkilla Wartrike
- [x] DeffKoptas
- [x] Flash Gitz
- [x] Ghazghkull Thraka
- [x] Makari
- [x] Gorkanaut
- [x] Gunwagon
- [x] Hunta Rig
- [x] Kaptin Badrukk
- [x] Killa Kans
- [x] Lootas
- [x] Kill Rig
- [x] Kommandos
- [x] Mad Dok Grotsnik
- [x] Meganobz
- [x] Megatrakk Scrapjets
- [x] Stormboyz
- [x] Mek
- [x] Mekboy Workshop
- [x] Mek Gunz
- [x] Morkanaut
- [x] Nob on Smasha Squig
- [x] RukkaTrukk Squigbuggies
- [x] Nobz
- [x] Painboy
- [x] Runtherd
- [x] Burna Boyz
- [x] Shokkjump Dragstas
- [x] Boomdakka Snazzwagon
- [x] Boss Snikrot
- [x] Boss Zagstruk
- [x] Squighog boyz
- [x] Tankbustas
- [x] Stompa
- [x] Trukk
- [x] Warbikers
- [x] Kustom Boosta-Blastas
- [x] Warboss
- [x] Warboss in MA
- [x] Weirdboy
- [x] Wazbom Blastajet
- [x] Wurpboy
- [x] Mozrog Skragbad
- [x] Zodgrod Wortsnagga
- [x] Beastboss

Initial non datasheet elements: tag8833
------------
- [x] Faction Rules
- [x] Clans
- [x] WL Traits
- [x] Relics
- [x] Psyckic powers.
- [x] Points
- [x] Specialist Rules
- [x] Strategem detachment Upgrades
- [x] Kustom Jobs
- [x] Strategem Unit Upgrades
- [x] Mekboy Workshop - `I'll Av Wot E's Avin!` validation
- [x] Detachment rules (waaagh/forced wlts/detachment locking)
- [x] Remove existing "Shared Rules" from models that shouldn't have them anymore (Dakka/Grots/Gunz for hire etc.)
- [x] Forced warlord traits for certain models

Not related but we should do this at the same time
------------
- [x] Legends unit filtering (reference tau/marine cats on how)

Testing and validation
------------
- [x] Forgeworld units need to be verified that they're using the correct versions of codex weapons

**Comment by tag8833** [comment]
Progress is on the https://github.com/BSData/wh40k/tree/OrkCodex branch.

Orks - 2021.cat file

**Comment by OgreBarberian** [comment]
- [x] big mek in mega armor 85, still has old options too
- [x] big mek with kustom force field 85, still has old options
- [x] big mek with shokk attack gun 110 now, still has da kleverest boss
- [x] boss snikrot 95
- [x] boss zagstruk 110
- [x] kaptin badruk 95
- [x] makari 55
- [x] deffkilla wartrike shows no relics available
- [x] runtherd 30 base
- [x] boyz dont have ard boyz strat anymore
hq, no slot, troops, ill get though the rest in the morning if you need me to. happy to hep techno!

**Comment by pawmiszczyk** [comment]
- [x] Deff dreads have old point value
- [x] squighog boys are missing

**Comment by Gullara** [comment]
- [x] Ghazghkull, when included in a non-Goffs detachment, gives an error: "Warlord cannot have any selections of Proper Killy". The warlord trait is mandatory despite being Goffs locked. 
- [x] Makari is counting against the HQ limit in a detachment while accompanying Ghazghkull, despite "Da Boss' Best Grot".

**Comment by GinFizzz** [comment]
- [x] Stratagem: Big Boss on Boss Snikrot should give him his locked Warlord Trait (Brutal but Kunnin') when selected, applies to other Named Characters as well.

**Comment by Calteezy** [comment]
- [x] Gorkanaut showing 340 points when it should be 365

**Comment by cpmcnally** [comment]
Burna Boyz and Lootas when created default to 5 Burnas / 5 Lootas, now illegal. Should default to 4 + Spanna w/ big shoota. Also the spanna weapon costs in these squads are the old values of +5 for big shoota, +10 for KM, +10 for RL. New costs are +0 / +5 / +5 respectively, for both units.

**Comment by Gulaghar** [comment]
- [ ] The Meganob does not allow picking two killsaws. 
- [ ] The Meganob's weapon choices are out of date, as the options are flexible now. I'll give the full rules below, but basically the divide between a power klaw meganob and a killsaw meganob no longer makes much sense.

WARGEAR OPTIONS
- Any model's power klaw can be replaced with one killsaw.
- Any model's kustom shoota can be replaced with one killsaw.
- Any model's kustom shoota can be replaced with one of the following: 1 kombi-skorcha; 1 kombi-rokkit.
