### ISSUE TITLE
Adeptas Sororitas - Dogmata has incorrect number of attacks on data sheet

### ISSUE THREAD

**Issue by OddestFuture** [BSData/wh40k-9e#10141]
**File/Catalogue:** 

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Dogmata has 2 attacks base in battlescribe instead of 3 as listed in the codex on her profile.

**Comment by Technoblazed** [comment]
Already fixed, pending release.
