### ISSUE TITLE
Aeldari - Drukhari: Blackstone Fortress Ur Ghul Unit missing from Data

### ISSUE THREAD

**Issue by Duriel201** [BSData/wh40k-9e#10144]
**File/Catalogue:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** The 16 points single model Ur Ghul unit from Blackstone Fortress is missing from the Drukhari data. You can currently only add Ur Ghuls through the court of the archon entry.

**Comment by Technoblazed** [comment]
Won't fix, the Drukhari codex is the newer publication with a model/unit of the same name.
