### ISSUE TITLE
Deathwatch Veterans missing Heavy Flamer

### ISSUE THREAD

**Issue by carlisle9** [BSData/wh40k-9e#10148]
**File/Catalogue:** 

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Deathwatch Veterans (and Proteus Killteam Deathwatch Veterans) are missing Heavy Flamer equipment option from their weapon list. Digging a little deeper it seems they're missing Deathwatch frag cannon, infernus heavy bolter, heavy bolter, and missile launchers as well. Additional points cost for 4 of these are missing as well.

**Comment by Technoblazed** [comment]
Add a Deathwatch Veteran w/ Heavy Weapon to the unit.
