### ISSUE TITLE
Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by HBMCalgar** [BSData/wh40k-9e#10155]
File: Imperium - Astra Militarum.catz

BattleScribe version: 2.03.21

Platform: Windows 

Dropbox: No

Description: Astra Militarum does not appear at all. I cannot select them from the list of available factions as they are simply not there. Everything else is.

**Comment by Technoblazed** [comment]
Delete all of your data files from your device and redownload, make sure that you don't have 8th edition and 9th edition installed at the same time as it's known to cause issues.

**Comment by HBMCalgar** [comment]
I'll give it a shot. :)

**Comment by HBMCalgar** [comment]
It worked! Thanks! :D
