### ISSUE TITLE
Tome Keepers Orator Sephax Cannot have any selections of benediction of fury (hidden)

### ISSUE THREAD

**Issue by demlimes** [BSData/wh40k-9e#10152]
File: Ultramarines

BattleScribe version: 2.03.21

Platform: Windows/iOS
Dropbox: Yes

Has an Error of "Orator Sephax cannot have any selections of benediction of fury (hidden)", his datasheet in the tome keepers index indicates otherwise.

**Comment by Technoblazed** [comment]
Can't replicate this at all, do you have an example list?

**Comment by demlimes** [comment]
Yeah here’s a list
