### ISSUE TITLE
Orks 2021 - Flyers have no Kustom Jobs

### ISSUE THREAD

**Issue by GinFizzz** [BSData/wh40k-9e#10169]
**File/Catalogue:** Orks 2021.cat

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:**
Ork Flyer Units are currently lacking any Kustom Jobs.
They should be able to take More Dakka, Shokka Hull, and Extra Kustom Weapon (On the Wazbomb).

**Comment by Technoblazed** [comment]
Fixed but the Wazbomb isn't eligible to take the extra kustom weapons because it has it's own versions of those weapons not the ones listed on the kustom job.
