### ISSUE TITLE
Ork Boyz data incorrect

### ISSUE THREAD

**Issue by Kai-Brereton** [BSData/wh40k-9e#10178]
**File/Catalogue: 40k - Orks** 

**BattleScribe version:** 2.03.21

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** In the Orks data, the Ork Boyz and the Boss Nob have been given the toughness 4 when in the Codex (page 93) the toughness of the Boyz and the Boss Nob is toughness 5
![20210730_221435](https://user-images.githubusercontent.com/52532348/127712230-b567a4ea-4287-499c-be4b-164d4c271286.jpg)

**Comment by Technoblazed** [comment]
Already updated in version 13.
