### ISSUE TITLE
Orks 2021 issues with Squighog boyz PL cost and Beastboss on Squigosaur Ramshackle

### ISSUE THREAD

**Issue by tildenat** [BSData/wh40k-9e#10177]
**File/Catalogue:** Orks - 2021

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Squighog boyz cost 8 pl for 3 if you have at least 6 models in the army.  If you only have one unit of 3 the cost is as it should be, which is 4 for 3. Also, the Beastboss on Squigosaur has Ramshackle, which it does not have in the codex.
![squighog pl](https://user-images.githubusercontent.com/88209834/127700674-6b9da092-a093-4deb-ae83-46d012df10a2.png)

**Comment by Technoblazed** [comment]
Update your data.

**Comment by tildenat** [comment]
I just did. the issue is still there.

**Comment by Technoblazed** [comment]
![Image](https://i.tech-no.me/2021/07/30/210730201233.png)

**Comment by tildenat** [comment]
yes, but if you add another unit, the cost on both will be 8 pl.

**Comment by tildenat** [comment]
![image](https://user-images.githubusercontent.com/88209834/127701117-b5816009-09d6-4433-99f8-3b3e9f86af96.png)

**Comment by Technoblazed** [comment]
It'll be fixed in next thursdays release.
