### ISSUE TITLE
Fix for issue #10107 caused incorrect data to Deathwatch catalogue

### ISSUE THREAD

**Issue by beefwad13** [BSData/wh40k-9e#10185]
**File/Catalogue:** Imperium - Deathwatch

**BattleScribe version:** 2.03.21.166

**Platform:** Windows/Android

**Dropbox:** No

**Description:** The "Proteus Kill Team" can add a "Black Shield" model for a cost of 1 Power Level, 25 Points. I asked for the Power Level change in Issue #10107 and it looks like the "Black Shield" cost was instead changed to 1 Point, instead which is incorrect.

**Comment by beefwad13** [comment]
@Technoblazed  thanks for the quick fix sir

**Comment by cometeer** [comment]
what publication is this based on?
original supplement does not even allow a blackshield to be added to a proteus KT
FAQ that allowed them to be added to proteus KT doesn't specifiy PL cost (while all the others do, so obvious mistake in the FAQ but it hasn't been addressed)  https://www.warhammer-community.com/wp-content/uploads/2020/12/nxnFmoeohIerS0xJ.pdf
Power rating update from 02/06/2021 doesn't mention DW at all

It would make sense for the guy to have a PL cost but as far as I can tell there is only a points cost via the DW vets datasheet.

**Comment by beefwad13** [comment]
@cometeer I just saw this in my email from months ago, sorry for the 3 month late reply. You make a valid point. I could have sworn this was in the FAQ/Errata or Chapter Approved 2021 but I do not see anything mentioned in either of the DW Supplement. So it does appear adding a Black Shield do a Proteus Team is 0 PL


@Technoblazed  is this something that can be reversed since we do not have any supporting documentation?
