### ISSUE TITLE
Imperium - Deathwatch: No units are marked as having Objective Secured

### ISSUE THREAD

**Issue by TrashPastor110** [BSData/wh40k-9e#10183]
**File/Catalogue:** Imperium - Deathwatch

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** When viewing the individual Deathwatch units, the Troops are not marked as having Objective Secured at the bottom of the list.

**Comment by acebaur** [comment]
Battlescribe is not a replacement for your codex, we do not include every single rule available to an army.
