### ISSUE TITLE
Orks 2021 Lootas validation incorrect

### ISSUE THREAD

**Issue by rufflabs** [BSData/wh40k-9e#10188]
**File/Catalogue:** Orks 2021

**BattleScribe version:** 2.03.21.166 data file 9.2.0

**Platform:** Mac

**Dropbox:** Yes

**Description:** Lootas rules from codex states "This unit must contain 1 spanner for every 4 Lootas it contains." However, the data file is not validating. With 4 Lootas, the validation says I can have 0 spanners. I have to add a 5th Loota before it lets me add a spanner.

**Comment by Technoblazed** [comment]
Fixed in the last release, should be available on appspot within the next few hours.
