### ISSUE TITLE
Bug Report - Ork Codex 2021

### ISSUE THREAD

**Issue by LahavBarak** [BSData/wh40k-9e#10181]
File: Orks - 2021.catz

BattleScribe version: 2.03.25.338

Platform: Android

Dropbox: No

Description: 
* Burna Boyz - minimum spanner amount (1 for every 4 burnas) not enforced
* Burna Boyz - no option to take Kustom Jobs (specifically zzapkrumpas and smoky gubbinz), the other eligible unit - lootas, works fine.
* Kill Rig - when selecting Big Boss strat - no warlord trait selection option opens.

**Comment by Technoblazed** [comment]
The Kill Rig has a forced warlord trait so is automatically applied whenever you make him your Warlord or use the Big Boss stratagem.
