### ISSUE TITLE
Orks - 2021: Nob on Smasha Squig has no statline

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10197]
**File:** Orks - 2021.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The Nob on Smasha Sguig for Orks 2021 is not providing a table for movement, skill, attacks etc.

**Comment by Technoblazed** [comment]
Fixed in the next release already.
