### ISSUE TITLE
Orks - 2021: Shokk Attack Gun Big Mek BS is incorrect

### ISSUE THREAD

**Issue by nicb1** [BSData/wh40k-9e#10194]
File: Orks - 2021.catz

BattleScribe version: 2.03.21

Platform: PC

Dropbox: No

Description: Big Mek w/ Shokk Attack Gun is showing a BS of 5+, should be BS 4+

**Comment by autowaaagh** [comment]
There's more than just the BS, he's also showing T4 instead of T5 and has no access to the mek kustom jobs
