### ISSUE TITLE
Death Guard Feotid Virion rule

### ISSUE THREAD

**Issue by sashman** [BSData/wh40k-9e#10202]
**File/Catalogue:** Chaos - Death Guard

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** When including 3 Feotid Virion units, the rule does not kick in. DG Codex page 40
![image](https://user-images.githubusercontent.com/905730/128080678-ed534634-f915-43ab-a412-42f544253c88.png)

**Comment by Technoblazed** [comment]
Add the models from no force org slot on the left side of your screen.
