### ISSUE TITLE
Ork 21: Shokk Attack gun BS skill incorrect

### ISSUE THREAD

**Issue by stowelly** [BSData/wh40k-9e#10207]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** /No

**Description:**  currently the Shokk Attack gun shows bs5+ but the new codex updated it to be 4+.

Also the selection rules still show the old versions of mob rule + dakka dakka dakka.

Thanks for all the hard work guys

**Comment by Technoblazed** [comment]
The SAG is fixed in the next release, but the mob rule and dakka dakka dakka were replaced/removed from the cat respectively, make sure you're using Orks 2021.
