### ISSUE TITLE
Bug report: Orks - 2021.catz 

### ISSUE THREAD

**Issue by GHGPII** [BSData/wh40k-9e#10218]
File: Orks - 2021.catz

BattleScribe version: 2.03.21

Platform: Windows

Dropbox: No

Description: Nob on Smasha Squig has no "Profiles" characteristics show when viewing selection or viewing the roster.
It should be the following: M:10" WS:3+ BS:5+ S:5 T:6 W:5 A:4 Ld:7 Sv:4+

**Comment by Technoblazed** [comment]
Already fixed in the next release.
