### ISSUE TITLE
Skitarii Vanguard Relics

### ISSUE THREAD

**Issue by thorgrim84** [BSData/wh40k-9e#10214]
BS will not let you apply more then one relic when using veteran cohort. Can't see anything in the rules that would prevent it.

**Comment by Thairne** [comment]
4 relics in a veteran cohort

![grafik](https://user-images.githubusercontent.com/8590840/128485193-8264fc27-5b31-4d09-b0b7-997dabd61462.png)

No error

Can you elaborate?

**Comment by thorgrim84** [comment]
I'm using the mobile version. I'll leave some pics.

**Comment by thorgrim84** [comment]
![image](https://user-images.githubusercontent.com/88498144/128527901-aeb93979-561c-4d1f-bd2b-1d06133622dc.png)

**Comment by thorgrim84** [comment]
![image](https://user-images.githubusercontent.com/88498144/128527973-f83fb621-1854-433e-856b-02862c0f1c59.png)

**Comment by thorgrim84** [comment]
![image](https://user-images.githubusercontent.com/88498144/128528131-a4b88341-ed95-453b-a8a8-abf62e108610.png)

**Comment by Technoblazed** [comment]
You've only taken 1x artefactorum, you need to take another one.

**Comment by Thairne** [comment]
Well thats that settled :)

**Comment by thorgrim84** [comment]
I had to take the archeotech specialist for the error to go away.
