### ISSUE TITLE
Primaris captain missing options

### ISSUE THREAD

**Issue by peaco86** [BSData/wh40k-9e#10222]
**File/Catalogue:** 40k, blood angels / space marines

**BattleScribe version:** 2.03.

**Platform:** Windows/

**Dropbox:** Yes/No

**Description:** when creating a roster for Blood angels, the primaris captain is missing options for:
-special issue bolt carbine and powerfist
-plasma pistol and powerfist
![Capture](https://user-images.githubusercontent.com/88575975/128593427-645fc1fa-d024-4a10-84e1-f08bd5979920.PNG)

**Comment by Mad-Spy** [comment]
1.  Read up one bullet, only Dark Angels (or their successors) can take a special issue bolt carbine.
2. This option is definitely there.
![image](https://user-images.githubusercontent.com/29306451/128593883-f0805d81-d25a-4664-adc9-09e4f35779f5.png)
