### ISSUE TITLE
Thousand sons Enlightened points 

### ISSUE THREAD

**Issue by Xenodraig** [BSData/wh40k-9e#10233]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description. The thousand sons enlightened do not have to pay for greatbows anymore so should not be 6 points to have them. At least there is no points listing in the 2021 field manual

**Comment by AbonShell** [comment]
Books not out yet so battlescribe hasn't released an update yet

**Comment by Mad-Spy** [comment]
@AbonShell Although it's not been made explicit, this report is based on the updated data on the TSons-2021 branch.
