### ISSUE TITLE
Aeldari - Drukhari: Blood Dancer WLT should be available with Cult of Strife (Restricted)

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10230]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** When selecting a Cult of Strife (Restricted) obsession, to use the Cult of Strife Codex Supplement options from Book of Rust, the Blood Dancer warlord trait isn't available for selection. 
Blood Dancer is the Cult of Strife unique warlord trait from the base book. From that book, when selecting an obsession, "If a Wych Cult model gains a warlord trait, they can have the relevant Wych Cult Warlord Trait instead of a Drukhari Warlord Trait." 
Then, from the Book of Rust Supplement: "If a Cult of Strife Character model gains a Warlord Trait, you CAN use the Cult of Strife Warlord Traits table below to determine what Warlord Trait they have instead of one from another source." 
Using a full detachment of Cult of Strife to unlock the supplement extra options doesn't negate any of the options from the base Cult of Strife obsession, including the Blood Dancer warlord trait.

**Comment by WindstormSCR** [comment]
hw the hell did this one break.... investigation required as the drukhari WLTs have been doing some strange things recently.
