### ISSUE TITLE
TSons QA Pass, Will Update Throughout Day

### ISSUE THREAD

**Issue by DrRuler** [BSData/wh40k-9e#10246]
**File/Catalogue:** TSons-2021 Thousand Sons

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** Yes/No

**Description:** 

Doing a quick QA pass, things I found from the cat I pulled 19 hours ago:

Bugs:
- [x] Cult of mutation relic not properly showing up on "SORCERER" models - Working fine for normal Sorcerers as long as you have a Mutation Warlord (as per the rules), but was broken for Thralls.
- [x] ~~Helbrute missing fist-gun options~~ Drill down into the fists
- [x] Inferno Bolts should be removed as an option (or I'm incredibly blind.)
- [x] Heldrake claws should be S User
- [x] Heldrake movement stats incorrect

Formatting/Spelling:
- [x] Capering Imps infernal pact "select oen"
- [x] Chorus Tutorum "you cna give"
- [x] Otherworldly Presience lacks word "invulnerable" (making it look EXTREMELY bad lol)
- [x] Tzaan Shaman has to manually select his disc but is default equipped with one and must take it.
- [x] Glimpse of Eternity "commnad"
- [x] Desecration of Worlds "normal moev"
- [x] ~~battle size has PLs wrong. It should be 0-25/26-50/51-100 etc. Strike Force games cap at 100PL~~ You are incorrect. 
![image](https://user-images.githubusercontent.com/29306451/129081891-511a6521-a988-4f51-a362-076e57adb910.png)

**Comment by Vailex** [comment]
Heldrake claws should be strength User and the degrading movement stats look off
