### ISSUE TITLE
Disciples of be'lakor errors

### ISSUE THREAD

**Issue by p5freak** [BSData/wh40k-9e#10244]
A tzeentch/slaanesh/nurgle daemon/csm psyker cannot choose from both psychic disciplines. Its either his own, or the noctic, not both. It says so in the noctic discipline.

_Before the battle, if every unit in your army has the DISCIPLES OF BE’LAKOR keyword (excluding UNALIGNED units), you can generate the psychic powers for any DISCIPLES OF BE’LAKOR PSYKER units from your army from the Noctic discipline using the table below, instead any other psychic discipline._ 

Also, you cannot mix csm and chaos daemons in a detachment in matched play. Units in a detachment must share at least one common faction keyword, which cant be chaos. When you mix csm and chaos daemons in a detachment, the common faction keyword is chaos. Disciples of belakor is not a faction keyword.

**Comment by Technoblazed** [comment]
You can still mix CSM and Chaos detachments on `NURGLE`, `SLANNESH`, `KHORNE` and `TZEENTCH`

**Comment by Mad-Spy** [comment]
1. This should be validated on every psyker. If there are any I've missed, raise a new issue with details.
2. There's no way to stop people doing this in Battlescribe, regardless of the fact that it it illegal.
