### ISSUE TITLE
Imperium - Adeptus Mechanicus: Rangers and Vanguards PL increment incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10252]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The PL for units of Skitarii Rangers and Vanguards are showing incorrectly. For example, a unit of 10 Skitarii Rangers is supposed to have 4 PL for a unit of 10 models, and if you use the Skitarii Veteran Cohort Army of Renown then that becomes 5 PL. When I add a unit it displays correctly. However, when I add a unit of Skitarii Vanguards made of 10 models, the PL on both becomes 6 for some reason even though both should display at 5 PL. It was displaying correctly a week ago and now it isn't.

**Comment by Mad-Spy** [comment]
@Thairne 

The yellow highlights should be like the blue one.

![image](https://user-images.githubusercontent.com/29306451/129319411-907d95b3-4918-4d8f-842f-18c41f6d97ca.png)
