### ISSUE TITLE
Bug hunting for new Grey Knights branch

### ISSUE THREAD

**Issue by MatteoCesari78** [BSData/wh40k-9e#10254]
**File/Catalogue:** new grey knights branch

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** 

idk if these are things that are still wip or the dev missed them, i just want to point them to help:

-gifts and vision should be bought by using points instead of granting you CPs
-grand master in dreadknight in 2nd bracket should have 5 attacks, he should have 13 wounds, he has the teleport strike ability
-kaldor draigo should have the reroll 1s to hit aura that works on grey knights core instead of brotherhood core
-psy out grenade are tags, not equipment anymore
-kaldor draigo has the tag supreme grand master, not grand master, so in the same detachment you should be able to take both him and another generic grand master on foot or in dreadknight
-brotherhood chaplain should have 4 attacks and BS 3+
-kaldor draigo knows 3 powers, he can correctly select 3, but the pop up shows wrongly that he can take only 2
-grand master on foot knows 2 powers, he can correctly select 2, but the pop up shows wrongly that he can take only 1
-grand master Voldus knows 3 powers, he can correctly select 3, but the pop up shows wrongly that he can take only 2
-paladins know 2 powers, they can correctly select 2, but the pop up shows wrongly that they can take only 1,
both the paragon and the paladins grunts have WS 2+, they should not have the brotherhood keyword
-purifiers dont have the brotherhood keyword, and they should not know the brotherhood psy power
-venerable dread should not have the brotherhood keyword and he should not know the brotherhood psy power, he should have the honoured knight keyword
-servitors should not have bolter discipline
-astral aim psy power is still the old version

**Comment by tekton** [comment]
still work in progress, thanks though
