### ISSUE TITLE
When selecting a Primaris Librarian Space Wolves Relics and special wargear isn't showing up to select. 

### ISSUE THREAD

**Issue by Muck1ng** [BSData/wh40k-9e#10250]
**File/Catalogue:** Space Wolves

**BattleScribe version:** 2.03.

**Platform:** Windows

Dropbox:** Yes

**Description:**  When selecting a Primaris Librarian Space Wolves Relics and special wargear isn't showing up to select.

**Comment by acebaur** [comment]
Working for me. Make sure you select a Warlord

**Comment by Muck1ng** [comment]
It’s happening if I select Ragnar black mane as my warlord then add the Primaris librarian. No space wolf relic items appear.

**Comment by acebaur** [comment]
Still not replicating.

**Comment by Technoblazed** [comment]
Unable to replicate, works fine on the latest release.

![Image](https://i.tech-no.me/2021/08/14/210814044120.png)
