### ISSUE TITLE
bug in Space wolves

### ISSUE THREAD

**Issue by karanha1** [BSData/wh40k-9e#10262]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
Saludos, he encontrado un par de fallos :
En el Fenrisian Great Axe (Cleave),el Damage es 3D+3 y no D6
En los Eradicators Squad el PL es 6 y no 7
Gracias

**Comment by karanha1** [comment]
Saludos, he encontrado un par de fallos :
En el Fenrisian Great Axe,el Damage es 3D+3 y no D6
En los Eradicators Squad el PL es 6 y no 7
Gracias

**Comment by Technoblazed** [comment]
Eradicators are 7 PL for the unit as of the latest PL update.

**Comment by karanha1** [comment]
Ok, thanks. 

Enviado desde Yahoo Mail con Android 
 
  El dom., ago. 15, 2021 a 12:42, ***@***.***> escribió:   


Eradicators are 7 PL for the unit as of the latest PL update.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
