### ISSUE TITLE
[Bug] Imperium - Grey Knights - Brotherhood Techmarine does not have access to Wisdom of the Prognosticars

### ISSUE THREAD

**Issue by raddue** [BSData/wh40k-9e#10272]
**File/Catalogue:** Imperium - Grey Knights 9.2.4.

**BattleScribe version:**  v2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** Brotherhood Techmarine is not counting as a character for access to the Wisdom of the Prognosticars.  Wisdom of the Prognosticars should be available to any non-named character.  Additionally, "Wisdom of the Prognosticars" is incorrectly titled "Wisdom of the Prognosticators".

**Comment by tekton** [comment]
Both the Librarian and the Techmarine have their access restored in the next release; thanks!
