### ISSUE TITLE
Grey Knight PL Issues

### ISSUE THREAD

**Issue by DrRuler** [BSData/wh40k-9e#10282]
**File/Catalogue:** Grey Knights.cat

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** Yes/No

**Description:** 

Grey Knights units missing their PL updates (Strikes should be 6PL, Termies 12PL, etc.)

PL per game size is also incorrect bracketing, Combat Patrol should be 0-25, Incursion 26-50, etc.

**Comment by SoSaltySalt** [comment]
#10246 Says the game size PL is correct
