### ISSUE TITLE
Orks - 2021: Grots have incorrect abilities

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10284]
**File:** Orks - 2021.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Grots have “dangerous in numbers” instead of their new abilites

**Comment by Technoblazed** [comment]
The grot abilities are correct, you're either using the wrong cat or using outdated datafiles.
