### ISSUE TITLE
Missing Unit

### ISSUE THREAD

**Issue by IronWulfen88** [BSData/wh40k-9e#10281]
**File/Catalogue:** Warhammer 40000 9th Edition v192

**BattleScribe version:** 2.03.25.338

**Platform:** Android

**Dropbox:** Yes

**Description:** Wolfguard battle leader on thunderwolf is missing from the hq choices

**Comment by AbonShell** [comment]
Under the lieutenants HQ selection.

**Comment by Technoblazed** [comment]
As above.
