### ISSUE TITLE
Craftworlds: Illic Nightspear not available

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10295]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 9.02.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** In the aeldari craftworlds faction the model “illic nightspear” doesn’t come up as hq, in fact I can’t find him at all, it should come up as an hq unit as indicated in the craftworlds codex and the version I’m on is v9.2.4 “all that glitters is dust” but I had to add the zeroes or else i wouldnt be able to submit

**Comment by Mad-Spy** [comment]
Appears correctly if Alaitoc is selected as your Craftworld. He is only available to that Craftworld
