### ISSUE TITLE
Ork Warboss in Mega Armour (Legends) not available

### ISSUE THREAD

**Issue by Rikerwota** [BSData/wh40k-9e#10294]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Technoblazed** [comment]
Already re-added in the next release.

**Comment by Rikerwota** [comment]
Cool, thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
