### ISSUE TITLE
Chaos Space Marines - Chaos Space Marines

### ISSUE THREAD

**Issue by Wyvern350** [BSData/wh40k-9e#103]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** One model may replace his boltgun with a special weapon or heavy weapon.  If the unit numbers 10 or more models. a second model may replace his boltgun with a special weapon or heavy weapon.  Currently, the program only allows one swap at 10 models.

**Comment by cartag** [comment]
Already done in previous commit.
