### ISSUE TITLE
Closed GK issues still happen for me(v9.2.5)

### ISSUE THREAD

**Issue by SoSaltySalt** [BSData/wh40k-9e#10314]
**File/Catalogue:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** #10278 and #10279 seem to still be broken for me. I've updated to 9.2.5, so I think I should be on latest

**Comment by tekton** [comment]
![image](https://user-images.githubusercontent.com/137810/129748901-2eff4a16-087f-4a94-b79c-35ca4eab1afb.png)

I tried both, they were working fine on a download from appspot; try looking at the GK version when you add a force it should be  92+

**Comment by SoSaltySalt** [comment]
Yea, now suddenly it works. Sorry for taking up your time
