### ISSUE TITLE
Chaos - Thousand Sons: Exalted Mutation and Smite issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10315]
**File:** Chaos - Thousand Sons.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Noticed two bugs with the new Thousand Sons data. I've selected Cult of Mutation and do not have access to the Exalted Mutation relic option for my HQ units. Other Cults seem to have their wargear so I believe it's an oversight of just this one Cult.

Second bug is that Thousand Sons seem to have abandoned the "Mini-Smite" entirely, with Aspiring Sorcerers and Scarab Occult Sorcerers using d3/d6 damage normal Smites. Battlescribe still shows these Psykers as using the weaker Smite however.

**Comment by Mad-Spy** [comment]
1. Exalted Mutation shows up fine if you have a Cult of Mutation Warlord and select a valid model (a SORCERER).  It wasn't working for Thralls, but that was fixed in the last release (TSons v102).
2. Fixed
