### ISSUE TITLE
[Bug] Imperium - Grey Knights some points value and Core keyword changes

### ISSUE THREAD

**Issue by raddue** [BSData/wh40k-9e#10317]
**File/Catalogue:** Imperium Grey Knights 

**BattleScribe version:** v2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:**

Points:
1. Stormhawk Interceptor is 195, should be 185.
2. Stormtalon Gunship is 185, should be 165.

~~Units missing CORE keyword:~~
~~1. Purgation Squad~~

**Comment by tekton** [comment]
Purgation squads got fixed when interceptors were fixed

**Comment by tekton** [comment]
Those are the cost with their default load outs, so the prices are right. Thanks for the heads up though :)

**Comment by tekton** [comment]
I see the points issue now- the default load outs changed! The joys of my codex finally arriving...
