### ISSUE TITLE
Grey Knights Rules Issues

### ISSUE THREAD

**Issue by newtothescene2021** [BSData/wh40k-9e#10325]
**File/Catalogue:** Warhammer 40,000 v9.2.5

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** 

- Castellan Crowe Attack Should Be 6 Instead of 5
- Brother Captain Stern is missing from the HQ list

**Comment by tekton** [comment]
Stern is locked to Ward, so you'll need to select the brotherhood to see him :)
