### ISSUE TITLE
TS's Skaeloch's Talon not showing up

### ISSUE THREAD

**Issue by SoSaltySalt** [BSData/wh40k-9e#10328]
**File/Catalogue:** Chaos - Thousand Sons v102

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** The relic staff Skaeloch's Talon that replaces a models force-staff is missing. The other staff replacement works correctly

**Comment by Mad-Spy** [comment]
Fixed in next release.
