### ISSUE TITLE
GK gate of infinity power is missing PSYKER keyword for eligible target units

### ISSUE THREAD

**Issue by Dusldorf** [BSData/wh40k-9e#10335]
**File/Catalogue:** warhammer 40k v9.2.5

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** gate can target a GK psyker unit but the power currently says any GK unit -- needs to also have psyker requirement

**Comment by BelisariusLawl** [comment]
Also worth noting that the range is wrong (and missing the ") and the warp charge is also incorrect.

In the new book, Gate is 18" range and WC 7. Battlescribe has it as 12 and 6 respectively.

**Comment by tekton** [comment]
To be fair, it's because it wasn't updated at all, botched, and lost in the transitions of things. So you missed all of that too...
