### ISSUE TITLE
Bad Venom Cost, it is actually 65 not 75

### ISSUE THREAD

**Issue by GustavoBastarrica** [BSData/wh40k-9e#10339]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Technoblazed** [comment]
65 base + 10 for the splinter cannon. The splinter cannon isn't free.
