### ISSUE TITLE
Grey Knight servitors missing servo arm

### ISSUE THREAD

**Issue by SSSlippy** [BSData/wh40k-9e#10332]
**File/Catalogue:**  9.2.5

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** Yes

**Description:** Servo Arm is missing from the servitor profile.  Has this weapon by default.

**Comment by tekton** [comment]
Someone forgot to add a min/max for that profile...huh...wonder who that was... >> << >>

thank you :)
