### ISSUE TITLE
Grey Knights Detachment Abilities

### ISSUE THREAD

**Issue by scuttstorm** [BSData/wh40k-9e#10337]
**File/Catalogue:*grey knights* 

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:** GK are missing some detachment abilities, such as Objective Secured for Troops.

**Comment by tekton** [comment]
That is part of the detachment itself as opposed to a named ability; the switch is there as a reminder for the extra rules, but battlescribe isn't meant to be a replacement for your codex. Thanks for the suggestion though :)
