### ISSUE TITLE
Tsons cultists PL error

### ISSUE THREAD

**Issue by darthrevan1234** [BSData/wh40k-9e#10347]
**File/Catalogue:** Thousand sons

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
Thousand Sons cultists are currently listed as 3PL rather than the 2PL in the new codex

**Comment by Technoblazed** [comment]
Dupe of https://github.com/BSData/wh40k/issues/10343
