### ISSUE TITLE
Bad Venom Cost

### ISSUE THREAD

**Issue by GustavoBastarrica** [BSData/wh40k-9e#10340]
**File/Catalogue: Warhammer 9th

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Venom Cost is 65 not 75

**Comment by Technoblazed** [comment]
65 base + 10 for the splinter cannon. The splinter cannon isn't free.

**Comment by GustavoBastarrica** [comment]
Sorry for duplicate did not see the other, thanks for clarification!
