### ISSUE TITLE
Adeptus Mechanicus

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#10344]
**File/Catalogue:** Adeptus Mechanicus v175

**BattleScribe version:** 2.03.15

**Platform:** iOS

**Dropbox:** Yes

**Description:** 
For the unit filter, instead of it being "Hide Legends Units" maybe it could be like Hide Forge World Units (like the Secutarii or X-101) because AdMech do not have an Legends units to hide so it is just a waste of code right now.

**Comment by Thairne** [comment]
AdMech also has basically zero Forge world beside the Terrax and the Hoplites. X101 is from Blackstone.
So its a total of 4 datasheets - I dont think an actual selector makes sense for it now. IF we get the 30k range - definately.
Hide Legends is mostly in there for future proofing - but I agree that it doesnt make sense (but also doesnt hurt - at all).
I'll hide it.
