### ISSUE TITLE
Aeldari - Drukhari: MASTER SUCCUBUS should be Max 1 in Force

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10350]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Codex Drukhari (pg 50) states you can only take one master succubus per cult. Battlescribe currently lets you take one upgraded (show stealer) master succubus AND Lelith Hesperax (has master succubus keyword) in same Cult of Strife detachment.

**Comment by elijahzucker** [comment]
A step further than just this, you can currently take 2 of any upgraded HQ of the same obsession as long as they are in separate detachments (eg: 2 master black heart archons each in they're own detachment)

**Comment by FarseerVeraenthis** [comment]
> A step further than just this, you can currently take 2 of any upgraded HQ of the same obsession as long as they are in separate detachments (eg: 2 master black heart archons each in they're own detachment)

I am unable to replicate this. It is possible to select them, but it throws an error, I am not certain if it would be possible to change this behaviour without a major overhaul for the CAT.
