### ISSUE TITLE
Imperium - "Operative Requisition Sanctioned" Stratagem invalid

### ISSUE THREAD

**Issue by PolecatEZ** [BSData/wh40k-9e#10351]
**File/Catalogue:** Warhammer 40,000 v9.2.6 

**Description:** Imperium - Operative Requisition Sanctioned (all Imperium lists)

The "Operative Requisition Sanctioned" Stratagem is invalid and superseded by the "Shadow Assignment" Stratagem.  It now should require an OFFICIO ASSASSINORUM unit to already exist in that detachment to validate.  Cost remains the same for CP, but the points cost is ZERO (the assassin unit is already paid for by existing on the list).  New official wording is as follows (reference War of the Spider):

Shadow Assignment - 2CP

"Use this Stratagem before the battle begins. If your
army includes exactly 1 OFFICIO ASSASSINORUM
unit, remove that unit from your army and then add
1 OFFICIO ASSASSINORUM unit of your choice to
your army. The unit that is removed does not count
as being destroyed for any rules purposes. Unlike
other units that are added to your army, this new
unit does not cost any reinforcement points, even in
a matched play game."

Currently it is possible to create an invalid list with multiple assassins or an assassin and Inquisition character in the same detachment.

Other than requiring the validation and updating text strings and updating the points cost to zero, no other coding changes should be necessary.

**Comment by Thairne** [comment]
aight. Someone's gotta do it some day.
