### ISSUE TITLE
Chaos - Thousand Sons: Warpflame pistol range incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10365]
**File:** Chaos - Thousand Sons.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Warpflame pistols are 12" now and not 6" in the new 2021 Codex

**Comment by ABMoW** [comment]
Submitted a Pull Request with Fix
