### ISSUE TITLE
Thousand Sons - Legends/Disk of Tzeentch Missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10385]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The data regarding Chaos - Thousand Sons dos not include Warhammer Legends rules. Nether the wargear options or the 'Sorcerer on Disk of Tzeentch'.

**Comment by Mad-Spy** [comment]
The combination of options is too much of a pain to leave implemented.
