### ISSUE TITLE
Drukhari  Raider Power level! 

### ISSUE THREAD

**Issue by Pitninja1** [BSData/wh40k-9e#10382]
**File/Catalogue:** warhammer 40,000 v9.2.2

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Raider power level shows as 6 - its 5 in the dex!

**Comment by synlic** [comment]
Check the FAQ:
https://www.warhammer-community.com/wp-content/uploads/2019/05/UsesnvPePAiqxPXL.pdf

It's been updated to 6.

**Comment by Mad-Spy** [comment]
Closing as per last comment.
