### ISSUE TITLE
Bug Thousand Sons & Cabal points display on mobile

### ISSUE THREAD

**Issue by ZiggyQubert** [BSData/wh40k-9e#10396]
**File/Catalogue:** 
Warhammer 40k 9.2.7

**BattleScribe version:** 2.03.
2.03.25.338

**Platform:** Windows/iOS/Android/Mac/Linux
Android

**Dropbox:** Yes/No
No

**Description:** Detailed issue description.
In the list header (where it displays the list name etc...) Cabal points in portrait mode cut off list points, any way to move cabal points to the end or abbreviate it 8n some way?
![Screenshot_20210829-115638](https://user-images.githubusercontent.com/3503895/131257017-1104ab0c-ba00-41cb-9061-1d0a3ccd5414.png)

**Comment by Mad-Spy** [comment]
No. The app displays them in alphabetical order.
