### ISSUE TITLE
Grey Knights - Psyk-out grenades

### ISSUE THREAD

**Issue by SoSaltySalt** [BSData/wh40k-9e#10395]
**File/Catalogue:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Is there a special reason psyk-out grenades are an automatic unit selection thing, instead of just another keyword? I'd guess so that it's easier to see. But wouldn't it be less stuff to load if it got moved into just a keyword.

**Comment by tekton** [comment]
I can, but every list is going to be very angry upon re-opening...

It is a keyword already for things that have it, but the profile was removed so it doesn't show up on print outs for the most part
