### ISSUE TITLE
Grey Knights - Unit Grenades

### ISSUE THREAD

**Issue by SoSaltySalt** [BSData/wh40k-9e#10394]
**File/Catalogue:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Not something that must be changed, but would be nice. Several units have Frag & Krak Grenades and Psyk-Out Grenades at the squad level, instead of per model.
#9580 says it has been fixed, but the update to the new codex might have reverted that?

**Comment by tekton** [comment]
it did, but functionally aside from different parsing it's the same
