### ISSUE TITLE
Chaos - Thousand Sons: Dilettante Relic error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10404]
**File:** Chaos - Thousand Sons.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Dilettante upgrade is giving an error when used on an Exslted sorceror. I am setting the point limit to 2k, buying sorcerous arcana twice and getting an error (maximum 1, though you can buy it twice in a strike game)

**Comment by Mad-Spy** [comment]
Unable to reproduce. Are you selecting your additional Relic from the Dilettante list, rather than the main list?

**Comment by Mad-Spy** [comment]
Also, you don't need to add Sorcerous Arcana twice; you add it once, then select how many extra Relics you want.
