### ISSUE TITLE
[Bug Report] CP total is wrong for Supreme Command Detachment + Battalion Detachment

### ISSUE THREAD

**Issue by Ratstail91** [BSData/wh40k-9e#10413]
**Describe the bug**
I currently have 2x HQs (in a battalion detachment) consuming 2x CP each, and the Silent King on supreme command detachment. The CP listed currently says 11/12 instead of 8/12.

**To Reproduce**
* Warhammer 40,000 9th Edition Rules version 192, Desktop
* Using this Roster: https://www.dropbox.com/s/5jbrz8sudafn2i1/Complete%20Necrons.rosz?dl=1
* The CP says 11/12

**Expected behavior**
Expected CP should say 8/12

**Screenshots**
* https://cdn.discordapp.com/attachments/797507115291246642/882505653988495360/unknown.png

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version 2.03.21

**Additional context**
The surpreme command detachment is producing 6 CP, whereas the battalion detachment is producing 5?

**Comment by Mad-Spy** [comment]
The Silent King gives you an additional 3CP for being your Warlord, as per his "The Silent King" rule.

**Comment by Ratstail91** [comment]
OMG my bad.
