### ISSUE TITLE
Chaos Knights, Rune of Nak'T'Graa relic not implemented well.

### ISSUE THREAD

**Issue by Sbrunch** [BSData/wh40k-9e#10415]
The text states correctly what the Rune of Nak'T'Graa (relic) does. The rune basically gives an inv. save and the chance for a dreadblade to choose an extra pact and an extra damnation. This means that a dreablade can have up to three pacts and/or damnations (2 basic +1 of the rune). However BattleScrive compiles an error if you select more than two despite the presence of the rune.. 

Also it is reported in the faq's that you can equip the rune on a dreadblade that does not have pacts and damnations (normally only one dreadblade can have pacts and damnations per detachment) this allows you to choose a pact and a damnation for the "extra" dreadblade allowing you to have two dreadblades with pacts and damnations. However if you try to give pacts and damnations to two dreadblades units in the same detachment it does return an error despite the presence of the rune.

Sorry for the bad english, it's not my native language.

**Comment by AbonShell** [comment]
![image](https://user-images.githubusercontent.com/20672472/131874936-dda85a32-dd4b-4d36-ac3d-8061f1b07a9f.png)
Seems to be working for me.

**Comment by Sbrunch** [comment]
> ![image](https://user-images.githubusercontent.com/20672472/131874936-dda85a32-dd4b-4d36-ac3d-8061f1b07a9f.png)
> Seems to be working for me.

It does print it out correctly but it still gives the alert, does it not to you?

![20210902_180115](https://user-images.githubusercontent.com/89992297/131877861-b8d273bb-31c9-4d47-86b7-e364d3b6fc9e.jpg)
![Screenshot_20210902-175917](https://user-images.githubusercontent.com/89992297/131877867-5ecde65a-e506-4131-8135-e8e3d842390d.jpg)

**Comment by AbonShell** [comment]
Three of each selected, no issues.
![image](https://user-images.githubusercontent.com/20672472/131881747-754fe276-04d6-46d4-aa00-de6ff33d1d7c.png)

![image](https://user-images.githubusercontent.com/20672472/131881843-d8ec90b9-b2f4-4fc4-b540-6d33f0e773cf.png)

**Comment by Sbrunch** [comment]
I didn't select the "rune pact and damnation" my bad!

**Comment by Sbrunch** [comment]
@abonshell I also noticed that the "rune pact and damnations" option is disabled for war dogs in case they are made a character via the lance rule and equipped with the rune, before reopening the issue could anyone verify this?

Edit: @Mad-Spy could you check?
