### ISSUE TITLE
Orks - 2021: Nobs missing MOB keyword

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10412]
**File:** Orks - 2021.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Hi,

I have noticed that the Nob unit also does not have the 'Mob' keyword, as the codex says they do.

I found this as they cannot take Madboyz Specialist Mob

Regards,

Jacob

**Comment by Technoblazed** [comment]
Fixed in next release.
