### ISSUE TITLE
Space Marines - Captain Weapon option Lightning Claw (Pair) Point Cost

### ISSUE THREAD

**Issue by TheBooray** [BSData/wh40k-9e#10423]
When selecting a weapon for Space Marines Captain the Lightning Claw (pair) option is listed as 5 pts and should be 10. If you select both lightning claws options to give the correct 10 pt cost an alert that there are too many options selected shows.

**Comment by acebaur** [comment]
The MFM, which is the most current points, has them at 5 for one or both, so you do not pay extra for the second one. It was this way in the codex too so not sure where you came up with this idea.
