### ISSUE TITLE
Imperium - Adepta Sororitas: Martyr's Vengeance should be available for Sacresant Superior

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10424]
**File:** Imperium - Adepta Sororitas.catz

**BattleScribe version:** 3.25.33

**Platform:** Android

**Dropbox:** No

**Description:** Relic not available for suitable model - BattleScribe v2.03.25.338

The relic: Martyr's Vengeance is a relic that replaces an inferno pistol for an order of our Martyred lady model.

It is not available to be selected for the celestian sacresant superior using the sacred burden stratagem while wielding an inferno pistol.

**Comment by Mad-Spy** [comment]
Sacred Burden does not allow a model to be given Martyr's Vengeance. There has been no change in the FAQ either to allow it.

![image](https://user-images.githubusercontent.com/29306451/132200397-c50ce07c-ac6b-45d8-912b-30346d200380.png)
