### ISSUE TITLE
Necrons Wrong points Catacomb Command Barge

### ISSUE THREAD

**Issue by WhiteSoule** [BSData/wh40k-9e#10432]
Hi when creating my Necrons roster I realized that the base point of the Catacomb Command Barge is wrong. In the codex of 9th edition that unit base point is 145pts plus 5 pts for the gauss cannon. In the BattleScribe app it is at 160 pts.
![image](https://user-images.githubusercontent.com/47774595/132469417-1f882ad3-1e0e-4358-b334-87fc075ccb67.png)

**Comment by Technoblazed** [comment]
The base points cost was changed to 155 in the MFM 2021 v2.
