### ISSUE TITLE
Chaos - Chaos Space Marines: FW units should not have Hateful Assault

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10438]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Chaos space marines forgeworld lords of war are incorrectly shown as having the hateful asaault special rule, deapite that extra attack being baked into the profile now.

**Comment by Mad-Spy** [comment]
There has been no update or errata to say that these units should not get Hateful Assault. 

FW datasheets are treated as if they are an addition to Codex: Chaos Space Marines, and all HERETIC ASTARTES units in the Codex gain the Hateful Assault rule, as per the latest Update for that Codex.
