### ISSUE TITLE
Imperium - Deathwatch: Changing melee options on HW terminators changes it for all of them.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10433]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.25

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** If you have more than one heavy weapon terminator in a Proteus Kill team, when you change one of their melee weapons it adds the change to all the heavy weapon terminators

**Comment by Technoblazed** [comment]
Unable to replicate. Please provide a roster file in a new bug report if you still have this issue.

![Image](https://i.tech-no.me/2021/09/10/210910105235.png)
