### ISSUE TITLE
[Grey Knights] Dreadnought Heavy Flamer Costs

### ISSUE THREAD

**Issue by SilverOtter** [BSData/wh40k-9e#10431]
When selecting a GK Dreadnought or Venerable Dreadnought and equipping it with a Dreadnought Combat Weapon, the price for the associated Heavy Flamer is incorrectly listed as 15 points. It should actually be 10 points.

**Comment by tekton** [comment]
you're right, it got messed up when the doomglaive fix got reapplied, thanks!
