### ISSUE TITLE
Grey Knights: Brother-Captains unable to take Sanctic powers

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10435]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Seems the grey knights sanctic discipline is missing when editing unit. When viewed there does seem to be a default selected. 

To reproduce. 
Create grey knight rooster. Add any unit capable of  at least 1 psychic power. For example HQ Brother Captain. You can select a power for the dominus discipline, but not for sanctic.

**Comment by Mad-Spy** [comment]
I suggest you re-read the datasheets for the Grey Knights units. Some of them cannot take Sanctic powers, including Brother-Captains.
