### ISSUE TITLE
Warhammer 40k - Thousand Sons cult of Mutation - Sorcerer in Terminator armor can't take Exalted Mutation relic

### ISSUE THREAD

**Issue by rag1n** [BSData/wh40k-9e#10430]
A Sorcerer in Terminator Armor is considered a SORCERER and should be able to take the Exalted Mutation Sorcerous Arcana

**To Reproduce**
1. Create a Thousand Sons Detachment
2. Select Cult of Mutation under Cults of the Legion
3. Add a Sorcerer in Terminator Armor. 
4. Refer to the Sorcerous Arcana and see that the relic Exalted Mutation is not visible

**Expected behavior**
Exaled Mutation should be available as it is for SORCERER models. Sorc in Terminator armor has the keyword Sorcerer

**Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version: 2.03.21
 - Release version [e.g. v192]

**Comment by rag1n** [comment]
I'm no expert in updating data but I believe the following change will fix it - change number from 0 to 1

![image](https://user-images.githubusercontent.com/31091773/132445978-6cd1ee4a-b152-41d8-972b-7b97a0de465e.png)

**Comment by Mad-Spy** [comment]
Working correctly in current release. You must have the relevant Cult Warlord in order to take Cult Relics. 

The code you have highlighted _hides_ the Relic if there is no such Warlord (or Magnus).

**Comment by rag1n** [comment]
As you can see my Sorc in Terminator Armor cannot see the Exalted Mutation relic despite being in the cult of mutation. I should be able to at least **see** it. I should then be able to select it without an error being thrown if I use the Sorcerous Arcana Stratagem

![image](https://user-images.githubusercontent.com/31091773/132453139-6f97e9ac-ec30-486d-b957-0e6894af9370.png)

**Comment by rag1n** [comment]
> Working correctly in current release. You must have the relevant Cult Warlord in order to take Cult Relics.
> 
> The code you have highlighted _hides_ the Relic if there is no such Warlord (or Magnus).

The relic is hidden if 0 of them are selected. Since I cannot even select 1 to begin with, the condition is true and therefore the relic is hidden.

Even my suggested solution isn't ideal, because you **should** be able to select multiple times and throw an error if selected more than once.  Having said that, I tested it and was able to select Exalted Mutation multiple times without any error being thrown (but at least I could select it)

![image](https://user-images.githubusercontent.com/31091773/132455236-b2164669-3365-4eb7-a8dd-3ae8b8711461.png)

**Comment by Mad-Spy** [comment]
Just being in the Cult is not enough. There _must_ be a Cult of Mutation Warlord or Magnus in your list as per the rules for Cult Relics. The example you have given does not appear to meet that criteria.

**Comment by rag1n** [comment]
Roger. Thanks for that.
