### ISSUE TITLE
Imperium - Dark Angels - Legends units missing keywords

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10451]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** In the Interrogator Chaplain on Bike and Chaplain on Bike Legends units, they are missing their [Priest] keyword and litanies selections. I've checked a few other places that still have them listed as having the Priest keyword, and therefore, Litanies of Battle.

**Comment by Thairne** [comment]
The official legends document lists no PRIEST keyword on either of them.
