### ISSUE TITLE
Wolfspear Codex Supplement

### ISSUE THREAD

**Issue by chronocobra** [BSData/wh40k-9e#10459]
Codex Supplement: Wolfspear

Chapter Tactic - Dark Terror:
- Add 1 to Advance rolls and charge rolls made for units with this tactic.
- Each time a ranged attack is made against a unit with this tactic by a model that is more than 18" away, the unit with this tactic is treated as having the benefits of light cover against that attack.

Relics:
Elemental Shroud:
- Each time an attack is made against the bearer, subtract 1 from that attack's hit roll.
- The bearer is not an eligible target for ranged attacks if it is more than 18" away from the firing model. If the bearer makes any kind of move, it loses the benefit of this Relic until the start of your next Movement phase.

Totem of Storms:
**Psyker** model only. Once per battle round, you can re-roll one Psychic test or Deny the Witch test taken for this model.

Blacktooth:
Model equipped with a combat knife or paired combat blade only. This relic replaces a combat knife or paired combat blade and has the following profile:
Melee S+1 AP0 D1
**Abilities:** Each time the bearer fights, it makes 2 additional attacks with this weapon. Each time an attack is made with this weapon, if a wound roll is successful, the target suffers 1 mortal wound and the attack sequence ends.

Warlord Traits:
1. Strike for the Throat:
Each time this **Warlord** makes a melee attack:
- You can re-roll the hit roll.
- Improve the Armour Penetration characteristic of that attack by 1.

2. Hunt from Afar:
Each time this **Warlord** makes a ranged attack against a non-**Vehicle**, non-**Monster** unit, an unmodified hit roll of 2+ is successful and an unmodified wound roll of 2+ is successful.

3. Howling Beast:
While this **Warlord** is within Engagement Range of any enemy models with a Leadership characteristic of 7 or less, add 2 to its Attacks characteristic.

**Comment by Mad-Spy** [comment]
Added for next release.
