### ISSUE TITLE
Inceptors point costs

### ISSUE THREAD

**Issue by davyboy85** [BSData/wh40k-9e#10456]
**Describe the bug**
Inceptors points need changing from 40pts to 45pts as per the Space Marine FAQ

![image](https://user-images.githubusercontent.com/29368586/133293817-9fce45a3-81c2-42ca-b5a5-7f6fdc0aaf53.png)

**Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version  v2.03.21.166
 - Release version Warhammer 40,000 v9.2.8

**Additional context**

**Comment by acebaur** [comment]
Points are correct as per MFM 2021
