### ISSUE TITLE
Chaos - Thousand Sons: Land Raider missing MACHINE SPIRIT

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10457]
**File:** Chaos - Thousand Sons.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Chaos Land Raider missing it's "MACHINE SPIRIT" keyword. Tzeentchs blessings upon ye

**Comment by Mad-Spy** [comment]
Fixed for next release
