### ISSUE TITLE
painboy on bike (Legend) Sawbonez: entry

### ISSUE THREAD

**Issue by whitewolfmxc** [BSData/wh40k-9e#10466]
Sawbonez: At the end of your Movement phase, this model can heal one friendly <CLAN> INFANTRY or <CLAN> BIKER model whose unit is within 3" of it. If you do so, roll one D6: on a 1, that model suffers 1 mortal wound. On a 2+, that model regains up to 2 lost wounds. Each model can only be healed once per turn.

painboy on bike (Legend) entry should update the above to be in line with painboy on foot

**Comment by Technoblazed** [comment]
The ork codex update does not affect legends unit rules, they remain the same.
