### ISSUE TITLE
Grey Knights: Typos and Wisdom of the Prognosticars validation issue

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#10469]
**Describe the bug**
- Precient Berthren is spelled wrong. That is how it is spelled currently and it should be spelled Prescient Brethren.
- Wisdom of the Prognosticators is spelled wrong. It should be spelled Wisdom of the Prognosticars
- You can take two or more of the same option for both Gifts of the Prescient and Visions of the Augurium upgrades. There should be an error when you select the same one more than once on different models.

**To Reproduce**
1. Go to a Grey Knights character adn select one Wisdom of the Prognosticars
2. Go to another GK character and select the same one
3. See that there is no error popping up

**Expected behavior**
For the third issue, I'd expect an error

**Screenshots**

**Device and data (please complete the following information):**
 - OS: iOS
 - BattleScribe version 2.0315
 - Release version 9.2.7

**Additional context**

**Comment by tekton** [comment]
It was only select things that could be duplicated; the limit was there was some of the child check was wrong for some- whoops

**Comment by Mad-Spy** [comment]
You fixed "Precient" but not "Berthren"
