### ISSUE TITLE
Space Marines: Chief Apothecary cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10462]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Chapter Command: Chief Apothecary upgrade - this is listed as 35 pts in all Apothecary profiles for the Dark Angels (Deathwing, Ravenwing, Apithecary, Primaris Apothecary). An FAQ updated this value to 15 pts in the 2nd June 2021 FAQ for Codex: Space Marines. I hope this helps!

**Comment by acebaur** [comment]
MFM 2021 MkII is the most up to date points costs so it's 35 points
