### ISSUE TITLE
 smashersquig missing rule for Battlefield Role slots

### ISSUE THREAD

**Issue by whitewolfmxc** [BSData/wh40k-9e#10465]
Squigboss | For each <CLAN> SQUIGHOG BOYZ unit included in a Detachment, up to two <CLAN> NOB ON SMASHA SQUIG units can be included in that Detachment without taking up any Battlefield Role slots.
-- | --

the programme doesn't recognise this when doing list for Nob on smashersquig

**Comment by Technoblazed** [comment]
Add the smasha squig from the no force org section.

**Comment by whitewolfmxc** [comment]
Mind telling me where it is ? 

![image](https://user-images.githubusercontent.com/65846291/134158452-bee3e4be-eea6-4996-abe9-5c82ccb400b9.png)

![image](https://user-images.githubusercontent.com/65846291/134158491-f1aacadd-c128-4fa7-9961-57c5964472cc.png)
