### ISSUE TITLE
Imperium - Grey Knights: Techmarine PL

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10467]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** GreyKnights Data v97 in Wh40k 9th Edition v192 -  The Brotherhood Techmarine has the wrong PL it is 4 PL in the new Codex, but the BS-Data stands with 5 PL.
Thanks for the great work!

**Comment by tekton** [comment]
This was fixed in another issue and will go out with the next release
