### ISSUE TITLE
DG chaoslord in terminator armor cant have deadly pathogens

### ISSUE THREAD

**Issue by p5freak** [BSData/wh40k-9e#10464]
DG v131

It is possible to select deadly pathogens for the chaoslord in terminator armor, but he doesnt have a plague weapon, and he cant get one. No plague weapon, no pathogens. BS doesnt give an error when you select a deadly pathogene.

**Comment by Mad-Spy** [comment]
You missed a couple. The Sorcerer in Terminator Armour also has no way of getting a plague weapon, and the Tallyman only has grenades (which don't count).

Regardless, you've now forced me to do it properly and it'll only appear for models which either always have a plague weapon, or, if they have an option, when they select one.
