### ISSUE TITLE
Grey Knights Grand Master Voldus shouldn't know projection of purity

### ISSUE THREAD

**Issue by MatteoCesari78** [BSData/wh40k-9e#10481]
Grand Master Voldus actually knows a weird psychic power, projection of purity, there is no reference of it in the new codex, i didnt know the 8th one, maybe is a remainder of the old codex?

**Comment by AbonShell** [comment]
It is the Wardmakers brotherhood power. Which because Grand Master Voldus is part of that brotherhood, has access to it. Page 48 of the grey knights codex.

**Comment by MatteoCesari78** [comment]
you are right i am dumb
