### ISSUE TITLE
40k Thousand Sons, Cult of Mutation, Sorcerous Arcana - Exalted Mutation Missing?

### ISSUE THREAD

**Issue by Tantilla217** [BSData/wh40k-9e#10482]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - BattleScribe version [e.g. 2.03.45]
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by AbonShell** [comment]
It's limited to a sorcerer model only. Note: Exalted sorcerers aren't SORCERER. They are EXALTED SORCERER. And that relic is only available on a SORCERER model. 
![SmartSelect_20210924-105051](https://user-images.githubusercontent.com/20672472/134695207-3b71ba07-8015-4cb1-95a3-732a4163a71e.jpg)

**Comment by Mad-Spy** [comment]
In addition to @AbonShell's comment, you MUST have a Mutation Warlord in your army; you do not get access to Cult Relics unless you have the relevant Warlord.

Also, we have a template for a reason, please use it properly when logging issues.
