### ISSUE TITLE
Aeldari - Craftworld - Remnants of Glory behaving strangely 

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10486]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Giving a remnant of glory to a non-warlord character in a separate detachment is creating a list invalid error. The rule for giving a relic is only that it goes to an ASURYANI character, with no restrictions on detachment or it needing to be your warlord.

**Comment by FarseerVeraenthis** [comment]
Hmmmmm... Seems a little odd, I'm away just now but I'll look into it 😄
