### ISSUE TITLE
[Craftworld Eldar] - Shadow Spectres incorrect squad size

### ISSUE THREAD

**Issue by McSheehy** [BSData/wh40k-9e#10497]
Shadow Spectres not allowing correct unit size.

Shadow Spectres allow for a unit size of 5-10 with an Exarch taking the place of one Spectre. 
Other aspect warriors allow a unit size of 4 + Exarch to have a legal min squad size. 

Shadow Spectres will only allow a unit size of 5 + Exarch to be selected in Battlescribe.

**Comment by Technoblazed** [comment]
What’s your source on an Exarch taking a slot instead? From the data sheet you get 5-10 Spectres, then you can optionally take an additional Exarch, there’s no replace options.

**Comment by Mad-Spy** [comment]
![image](https://user-images.githubusercontent.com/29306451/135295776-2273f322-b5c1-4daf-a912-f7e560c88d7f.png)

As @Technoblazed says, the datasheet says 5-10 Spectres and has nothing to say that you can replace a Spectre with an Exarch. Thus, you must always have at least 5 normal Spectres.

**Comment by McSheehy** [comment]
Hi,

Its 5-10 Spectres with the exarch 'replacing' one of those 5.
Its the same for all the other aspect warriors.

Shadow Spectres is the only one that doesn't allow this selection.

Cheers,

Crhris,

**Comment by McSheehy** [comment]
Ignore me,

Apologies, it seems Shadow Spectres is the only Aspect warrior without
'replace' in text.
I guess I got the data sheets mixed up.

Thanks,
