### ISSUE TITLE
Drukhari: Subfaction relics should only be available if there is a relevant Warlord.

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k-9e#10493]
**Describe the bug**
The Drukhari Codex states that subfaction Relics require a Subfaction WARLORD, unless the Detachment is a Realspace Raid.

**To Reproduce**
1. Create a Drukhari Roster with any detachment
2. Select a specific subfaction in the Obsession selector.
2. Add a model which is eligible for Relics.
3. Add the "Prizes from the Dark City" stratagem.
4. Subfaction-specific relics will be visible.

**Expected behavior**
Subfaction Relics shouldn't be available in standard Detachments unless the correct Warlord is selected.

**Comment by FarseerVeraenthis** [comment]
Yes, this is a planned development. I will get to it, possibly in time for next week's release.

**Comment by FarseerVeraenthis** [comment]
This is very odd... could you confirm the file version you were using at the time...?? I haven't changed anything to do with this recently and it is currently working as intended in v125
