### ISSUE TITLE
Chaos - Chaos Knights Ironstorm missile pod typo

### ISSUE THREAD

**Issue by Sbrunch** [BSData/wh40k-9e#10491]
The ironstorm missile pod is a blast weapon according to the codex, didn't know if it got faqqed but also wahapedia states it as a blast weapon however in BattleScribe (on chaos knights) it's listed as non-blast.

Imperial knights on BattleScribe do have it written as a blast weapon so I believe that rather than one of the two got it wrong.

**Comment by Mad-Spy** [comment]
Turns out there were two copies in the file, and I only fixed one of them when they added Blast.
