### ISSUE TITLE
Imperium - Space Marines: Reivers missing CORE keyword

### ISSUE THREAD

**Issue by GoglbMoglb** [BSData/wh40k-9e#10498]
**Describe the bug**

**To Reproduce**

**Expected behavior**
![image](https://user-images.githubusercontent.com/91622811/135306846-4591a9ed-81ff-4baa-8f5b-1fb43ec556f8.png)

**Screenshots**

**Device and data (please complete the following information):**
 - BattleScribe version [e.g. 2.03.45]
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by williamcaw** [comment]
What sub  Faction is it from?

**Comment by GoglbMoglb** [comment]
Imperial Fists

**Comment by acebaur** [comment]
> What sub Faction is it from?

It wouldn't matter, it's a Lib entry
