### ISSUE TITLE
Aeldari - Craftworlds: Relics are not unlocked in Detachments which don't contain the WARLORD

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10494]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** I opened my existing craftworlds roster, and I received an error telling me that the Autarch in my spearhead detachment was unable to take any remnants of glory. It had faolchus wing.

The warlord was a warlock skyrunner in a battalion detachment.

After removing the relic from the Autarch I was able to give the Autarch a relic only if the Autarch itself was the warlord.

I am talking about the Autarch on foot. I don't know if this also doesn't work for other Autarchs or relics.

**Comment by FarseerVeraenthis** [comment]
This should be fixed, please update your data. You may need to re-select your original warlord
![image](https://user-images.githubusercontent.com/23246922/135529399-02d01c4c-09e7-485d-b8ed-0de82661941d.png)
