### ISSUE TITLE
Orks: WAGONS should have access to Boom Boyz Specialist Mob

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10495]
**File:** Orks.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Under Specialist Mobs, p. 58, units with the WAGON keyword can gain the “Boom Boyz” ability.  Neither the Battlewagon, Gunwagon, Bonebreaka, nor Kannonwagon currently have an option listed for this Specialist Mob.

**Comment by Mad-Spy** [comment]
Kannonwagon does not have the WAGON keyword, so it is not eligible for this Specialist Mob. Also fixed so that WARBOSS models get this option as well.
