### ISSUE TITLE
Imperium - Imperial Knights: Unable to use Engine War traits with Exalted Court

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10490]
**File:** Imperium - Imperial Knights.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** I cannot select six warlord trait of "Psykic - engine war"'s by "Exalted court" stratagem.  It need to fix. thank you

**Comment by AbonShell** [comment]
So, the psychic awakening warlord traits are divided by which allegiance your night is from. Three are for Questor Mechanicus, and three are for Questor Imperialis. Them there's also the issue of, exalted court only allows you two extra warlord traits.

**Comment by Mad-Spy** [comment]
In order to take the Engine War traits, the model must _be_ a WARLORD. Thus, you cannot use Exalted Court to select them, as the model is only a WARLORD for the purpose of the trait itself, _not_ for determining which Traits it has access to.
