### ISSUE TITLE
Grey Knights Land Raider Crusader incorrectly priced

### ISSUE THREAD

**Issue by Saxonn** [BSData/wh40k-9e#105]
**File/Catalogue:** Grey Knights

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Hurricane bolters are priced at 34 points for two when it should be 8 for two and the twin assault cannons are priced at 50 points when they should be 35.

**Comment by tekton** [comment]
Set of copy paste fails from a night I was trying to go too quickly :(

**Comment by FarseerVeraenthis** [comment]
The points costs are correct in the latest released version (v2), this can be closed :smile:
