### ISSUE TITLE
Aeldari - Drukhari: Beastmaster cannot be set as WARLORD, despite having the Character keyword

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10500]
**File:** Aeldari - Ynnari.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Creating Ynnari army using Drukhari v124 data file

Beast master added in the no org and the elite category cannot be chosen as Warlord of a Ynnari army. It still has the option for Tolerated Ambition which is a stratagem that is Drukhari only and not available for Ynnari.

Since it cannot be chosen as a Warlord, it also can’t choose a Ynnari relic either.

**Comment by Mad-Spy** [comment]
Beastmaster has no Warlord link, nor a link to Relics of Ynnead.

**Comment by FarseerVeraenthis** [comment]
Looks like plenty of work to do on the elf cats... These are all largely related so hopefully I can crush all of them at the same time 😸
