### ISSUE TITLE
Servitor No Force Org Slot (Adeptus Astartes (Blood Angels))

### ISSUE THREAD

**Issue by SuperCaffeineDude** [BSData/wh40k-9e#10514]
When a techmarine (keyword) unit is present, a servitor squad can be taken without taking up the elite slot due to the Mindlock ability. I would presume the techmarine (primaris/non-primaris) should allow a +1 unit of servitors to be taken in the No Force Org Slot

**Comment by Mad-Spy** [comment]
Duplicate of #10473
