### ISSUE TITLE
Grot rules missing

### ISSUE THREAD

**Issue by whitewolfmxc** [BSData/wh40k-9e#10518]
Grot entry still missing the below rules :

1) Waaagh!

2) Cowardly: Unless a friendly <CLAN> RUNTHERD model is within 6" of this unit, each time a model in this unit makes a Combat Attrition test, subtract 1 from the result.

3) Diminutive: Each time a ranged attack is allocated to a model in this unit while it is receiving the benefits ofcover, add an additional 1 to any armour saving throwmade against that attack.
--

**Comment by Technoblazed** [comment]
It's fixed in the next release already.
