### ISSUE TITLE
Dark Angels missing Vanguard Veteran Squad

### ISSUE THREAD

**Issue by blipper** [BSData/wh40k-9e#10510]
**Describe the bug**
Dark Angels missing Vanguard Veteran Squad

**Expected behavior**
Should be available as in under Ultramarines et al.

**Comment by Technoblazed** [comment]
Dark Angels cannot take Sternguard or Vanguard veteran squads per the space marine codex.

**Comment by acebaur** [comment]
DA do not have access to Vanguard vets

**Comment by blipper** [comment]
Wow.  I had to dig to find that!  Sorry.
