### ISSUE TITLE
Drukhari Relic Bug - Cannot give second relic in a separate Detachment

### ISSUE THREAD

**Issue by GusHebblewhite** [BSData/wh40k-9e#10513]
A slightly fiddly bug. Basically it seems that you cannot give your second paid-for relic to a character that's not in the same detachment as your warlord.

Steps to recreate:
Create two patrol detachments
In one Patrol, add 2 archon. Make one of them your warlord and give them a relic. Use the "prizes..." strategem and give the other a relic.
In the other patrol, create an archon. In that detachment, even if you use the "prizes..." stratagem again, you cannot give this third archon a relic - the option does not appear within the unit option.

FYI this seems to have come from a recent change. I noticed because a bunch of my old valid lists are now throwing the error that certain characters cannot have relics.

App: 2.03.25
WH40K: v9.2.10

**Comment by FarseerVeraenthis** [comment]
This is fixed in file Drukhari v125, the released version is v124.
![image](https://user-images.githubusercontent.com/23246922/136094838-cdf52ba0-c267-44f4-ba49-b6944f9bb644.png)
