### ISSUE TITLE
Grey Knight land raider banisher

### ISSUE THREAD

**Issue by MatteoCesari78** [BSData/wh40k-9e#10520]
![image](https://user-images.githubusercontent.com/39375406/136181328-db9f3344-5507-479e-9863-fdbaa1b01384.png)

![image](https://user-images.githubusercontent.com/39375406/136181387-57d4940d-8601-4bf3-bb00-44c3e53475ba.png)

![image](https://user-images.githubusercontent.com/39375406/136181806-5c9eecc9-c193-4751-a96a-4498a541409e.png)

these are all the info i managed to find for this forge world variant that seems to be absent in the codex and the munitorum field manual mk2, if i am not mistaken then following the rules for the points the hunter killer missile and the storm bolter should be free, also i cannot find another datasheet or update on this datasheet other that the one of the IAC so if this one is the recent one then the Psyk-out Assault Launchers ability should be removed

**Comment by Technoblazed** [comment]
The data sheet you posted is out of date and the HKM/SB are 5 points each per the latest MFM 2021 v2 update. But the psykout grenades issue will need checking.

**Comment by MatteoCesari78** [comment]
can you point me to the new datasheet? i cannot find a new one in the faqs, is it only present in a new version of the material IAC book? also if there is not a section for the banisher in the field manual is it a guess that those pieces of equipment should cost the same as the other variants? (not that i am arguing, just curious)

**Comment by Technoblazed** [comment]
If you go to the latter third of the MFM you’ll find the Forgeworld unit points

**Comment by MatteoCesari78** [comment]
damn i am dumb, thousands of thx for pointing that out for me

edit: also in that section the banisher chassis is 20 points cheaper than the current roster one
