### ISSUE TITLE
Aeldari - Drukhari: Prizes from the Dark City Not Sufficiently Generous

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10538]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Multiple selections of Prizes from Dark City Strategem do not allow additional relics.

Start a new roster and set battle size to strike force (should allow teo uses of strategem). Create three detachments, each with an HQ. Give first HQ a relic. Select Prizes strat in other two detachments. Those HQs will not have the option to add a relic.

Note: with only one use of Prizes, the relic option is available. If chosen and a second Prizes is added, an error will show.

**Comment by FarseerVeraenthis** [comment]
A simple switch of one conditional from Force to Roster.
I also took the opportunity to upgrade slightly so that only having a Drukhari Warlord will unlock relics :-)
