### ISSUE TITLE
Multiple Signature systems and prototype systems in characters

### ISSUE THREAD

**Issue by Alex-40k** [BSData/wh40k-9e#10536]
**Describe the bug**
Currently T'au sept can chose both signature systems and prototype systems in the same character, example: vectored retro trusters and cross link stab jets in a coldstar commander 

**To Reproduce**
Select T'au sept, add coldstar commander, add vrt, add clsj 

**Expected behavior**
An error should pop as currently T'au characters can only take one relic 

**Screenshots**

**Device and data (please complete the following information):**
 - OS: [e.g. iOS] Android 
 - BattleScribe version [e.g. 2.03.45] latest 
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by Technoblazed** [comment]
Signature systems aren't the same as prototypes for the purposes of this rule. The only thing you can't do is take 2 signature or 2 prototypes on the unit.
