### ISSUE TITLE
Thousand Sons - The Change-Wrought Chalice relic modifier not increasing powers

### ISSUE THREAD

**Issue by Technoblazed** [BSData/wh40k-9e#10533]
**Describe the bug**
The Change-Wrought Chalice relics on a Tzanngor Shaman doesn't increase the amount of powers the model can know.

**Comment by Mad-Spy** [comment]
Fixed in next release.

**Comment by Mad-Spy** [comment]
I see why I got confused now when I checked it. They could already know too many powers!
