### ISSUE TITLE
Aeldari - Drukhari: Dancers Edge Relic is Missing

### ISSUE THREAD

**Issue by lgrant013** [BSData/wh40k-9e#10539]
**Describe the bug**
Recently updated data, went to create a Drukhari roster. Dancers Edge seems to be missing while Showstealers is selected.
Does not show up as a relic anymore. My first attempt was while creating a Realspace Raid. I checked to see if a cult detachment by itself would be different. Still missing.  Any other roster that had it selected before and is loaded back in is giving me an error telling me to remove it.

**Device and data (please complete the following information):**
 - OS: Windows/Android
 - BattleScribe version 2.03.21(PC) 2.03.25(Android)
 - Release version Warhammer 40k v9.2.11 Drukhari v128

![image_2021-10-08_204012](https://user-images.githubusercontent.com/92190814/136637620-eda6d999-bcd7-4050-8184-ff7c95d93c99.png)

**Comment by FarseerVeraenthis** [comment]
turns out I'd accidentally hidden it while working on the changes to the Cult specific relics...! It will be back on the next release, unless of course you want to download a copy of the datafiles from Master, in which case it is already updated :-)

**Comment by lgrant013** [comment]
All good, ill wait for the update to come out, in the mean time just editing a master roster I made that still has dancers edge selected.
