### ISSUE TITLE
Aeldari - Drukhari: Dark Lotus Toxin Missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10546]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 9.02.11

**Platform:** Android

**Dropbox:** No

**Description:** After update on the 7th dark lotus toxin is no longer an option. Seems to not exist now please fix. Thank you!!!

**Comment by FarseerVeraenthis** [comment]
Yeah, I missed the extra conditionals for the special relics when I updated the CAT. It is fixed now and will be in the next release.
