### ISSUE TITLE
Drukhari new issues 

### ISSUE THREAD

**Issue by shrykm** [BSData/wh40k-9e#10545]
Drukhari Succubus with showstealer upgrade doesn't get the option to take dancers edge after latest update,  vehicles also don't have the option to select "as detachment" faction. 
(Android)

**Comment by lgrant013** [comment]
I opened a ticket regarding the Dancers Edge relic the other day, that issue has been found and will be corrected in the next update will be released they mentioned.
The vehicle detachment thing is new though
