### ISSUE TITLE
Deduplicate output

### ISSUE THREAD

**Issue by xenoterracide** [BSData/wh40k-9e#10542]
So I have a tendency to configure my units the same. This way I don't forget which unit does which and what the rules are. However I've noticed that the output of battlescribe is extremely verbose. This may not be a 40k issue but I'm not really sure where to put it.

What I'd like to see is, For example if I have three Lord discordants with baleflamers, And none of them have any additional changes such as warlord or artifacts. That in the eye icon and other output it does something like 3 units of. Instead of repeating all of the same rules over and over again. 

By repeating them it simply makes scrolling through them to find what you're looking for a bit harder.

**Comment by Mad-Spy** [comment]
This is not possible as the app does not support it.

**Comment by xenoterracide** [comment]
Is it possible to migrate this issue somewhere more appropriate?
-- 
Caleb Cushing
https://xenoterracide.com

From: Iain Launchbury ***@***.***>
To: BSData/wh40k ***@***.***>
CC: Caleb Cushing ***@***.***>; Author 
***@***.***>
Date: Oct 9, 2021 2:29:24 PM
Subject: Re: [BSData/wh40k] Deduplicate output (#10542)

**Comment by Mad-Spy** [comment]
Even if you did, nothing would get done, because the app dev is no longer working on the app, at least at present.
