### ISSUE TITLE
Add repository versions for old editions

### ISSUE THREAD

**Issue by xenoterracide** [BSData/wh40k-9e#10543]
So recently I played And 8th edition game with a friend. He hadn't played in 4 or 5 years so he wasn't familiar with 9th. Unfortunately this meant going through and adding up all of the points individually. It would be nice to have a repository or whatever a final release of 8th edition. I believe this could simply be retrieved from a checkout from just before the release. I wouldn't really expect much maintenance unless there were inaccuracies.

**Comment by AbonShell** [comment]
8th edition is already available through the Archived Repositories
![image](https://user-images.githubusercontent.com/20672472/136666630-58af9ff3-6cc1-4014-a0f1-51a473fa69bb.png)
![image](https://user-images.githubusercontent.com/20672472/136666666-ff6a0b12-eb9b-461a-aa41-953a4aead6b2.png)

**Comment by xenoterracide** [comment]
Oh I see, I had no idea that option was there

**Comment by FarseerVeraenthis** [comment]
> Oh I see, I had no idea that option was there

don't worry dude, it is hardly very obvious :-)
Every day is a school day :-)
