### ISSUE TITLE
Chaos - Chaos Space Marines: Combat Elixirs not appropriately available

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10556]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** The Combat Elixirs stratagem is missing for Emperor's Children

**Comment by Mad-Spy** [comment]
Adding 4 conditional modifiers to almost every infantry unit in the catalogue is not something I want to do.
