### ISSUE TITLE
Drukhari - Too many troop choices (mobile)

### ISSUE THREAD

**Issue by Oshni** [BSData/wh40k-9e#10559]
Built a list on mobile, two patrols. First has 3 Kabalites, second has one wych. Battlescribe says 'Patrol detachment has 1 too many selections from troops (maximum 3). Updated my data immediately before list building.
![Screenshot_20211016-091501](https://user-images.githubusercontent.com/87262613/137595202-f97f318f-6479-48c3-b4a2-58f88bf625f1.jpg)
![Screenshot_20211016-091517](https://user-images.githubusercontent.com/87262613/137595204-2ac629e4-e8c9-4ce6-9b73-5a627165bad7.jpg)
![Screenshot_20211016-091530](https://user-images.githubusercontent.com/87262613/137595210-eb77e12c-39e5-4e0d-bbb8-5b77a4fcae49.jpg)
![Screenshot_20211016-091541](https://user-images.githubusercontent.com/87262613/137595218-2275a2b7-7f91-4cbe-871d-99fa5f864100.jpg)

**Comment by Technoblazed** [comment]
You’ve nested your detachments instead of creating 2 separate ones. When adding the 2nd detachment make sure to click add to the top level of the roster rather than an existing detachment.

**Comment by Oshni** [comment]
ahhhh, I see. Thank you.
