### ISSUE TITLE
Aeldari - Drukhari: Morvaine is being agonising

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10558]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Latest updated seems to have caused issue with Hekatrix of the Crucibale strategem. Morvaine's Agoniser is no longer selectable even if the strategem is taken on a Hekatrix in a unit of Bloodbrides. Previous valid roster is now showing error after update.

**Comment by FarseerVeraenthis** [comment]
Seems OK to me... note that you will need to jump through the correct hoops;
![image](https://user-images.githubusercontent.com/23246922/137601698-2baeadbd-d473-41ea-90b1-43889790b607.png)

**Comment by FarseerVeraenthis** [comment]
Further to add, this stratagem is only available on Cult of Strife Detachments, which means it will only show when "Cult of Strife (Restricted)" is chosen, additionally, you might need to check/uncheck the warlord option for your Cult of Strife warlord so they inherit the correct keywords (Cult of Strife Warlord) to unlock the relic in the first place... You might also want to check that the warlord has Cult of Strife selected as their obsession.

**Comment by ThePants999** [comment]
RAW, this does not require a Cult of Strife warlord. Unlocking the CoS relics for ordinary use absolutely does, but the Hekatrix of the Crucibael strat is unlocked simply by having a CoS detachment, even if it doesn't contain your Warlord, and explicitly says:

> That model can have one of the following Relics, even though they are not a CHARACTER: Morvaine’s Agoniser; Dark Lotus Toxin; Garland of Spite.

No requirement for it to be a relic you'd ordinarily have access to, just flat-out lets you give it to a Hekatrix.

Battlescribe is only allowing it with a CoS Warlord at the moment.

**Comment by FarseerVeraenthis** [comment]
You are correct, although I'm sure I fixed this already, because the other relics should be available for Hekatrix  and now they're not... Blasted Battlescribe!!

**Comment by FarseerVeraenthis** [comment]
> RAW, this does not require a Cult of Strife warlord. Unlocking the CoS relics for ordinary use absolutely does, but the Hekatrix of the Crucibael strat is unlocked simply by having a CoS detachment, even if it doesn't contain your Warlord, and explicitly says:
> 
> > That model can have one of the following Relics, even though they are not a CHARACTER: Morvaine’s Agoniser; Dark Lotus Toxin; Garland of Spite.
> 
> No requirement for it to be a relic you'd ordinarily have access to, just flat-out lets you give it to a Hekatrix.
> 
> Battlescribe is only allowing it with a CoS Warlord at the moment.

it is fixed in file v134, which is the latest release, please update your data 😸
