### ISSUE TITLE
HQ missing Wolf Guard Battle Leader on Thunderwolf option

### ISSUE THREAD

**Issue by sglasson-au** [BSData/wh40k-9e#10565]
Space Wolves missing Wolf Guard Battle Leader on Thunderwolf.

**To Reproduce**
1. New roster, space wolves, patrol
2. Expand HQ section 
3. Wolf Guard Battle Leader on Thunderwolf Is missing

**Expected behavior**
Expected to see the option available.

**Screenshots**

**Device and data (please complete the following information):**
 - OS: pC/windows
 - BattleScribe version [e.g. 2.03.45] sry don’t know. Did do a data update today 17 oct
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by AbonShell** [comment]
It's under lieutenants HQ choice
