### ISSUE TITLE
Custom Notes Dissapearing

### ISSUE THREAD

**Issue by Pitninja1** [BSData/wh40k-9e#10564]
**Describe the bug**
When I Put a custom note on a unit - it does not save (I press save on the PC version and I believe the APP version auto updates) 

NAMES for units stay and sync between PC/Phone - NOTES do not stay or sync

**To Reproduce**
click custom notes - add note click save

**Expected behavior**
notes should save to file - and appear on lists

**Device and data (please complete the following information):**
 - OS: IOS/Win10
 - BattleScribe version IOS 2.03.15 PC2.03.21 (both latest updates)
 - Release version [e.g. v1.2.3]

**Additional context**
its only the custom notes that wont sync - all other changes are fine

**Comment by AbonShell** [comment]
Not a data issue
