### ISSUE TITLE
Orks: Bad Moon Artifact Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10573]
**File:** Orks.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Badmoonz artifact da gobshot thunderbuss is not selectable by units using kustom shoota.

**Comment by Technoblazed** [comment]
Works as intended on characters with kustom shootas when badmoonz are selected.
