### ISSUE TITLE
Imperium - Black Templars: Second warlord trait with Heir of Sigismund stratagem gives an error

### ISSUE THREAD

**Issue by FarseerVeraenthis** [BSData/wh40k-9e#10575]
When selecting the second warlord trait with the Heir of Sigismund stratagem it gives an error of "Too many selections from warlord traits".

_Originally posted by @Kybelor in https://github.com/BSData/wh40k/issues/10571#issuecomment-945575244_

**Comment by acebaur** [comment]
Not replicating

**Comment by acebaur** [comment]
It did have an issue of not forcing you to take a BT one which is now fixed
