### ISSUE TITLE
Appspot and git hub crashing BS

### ISSUE THREAD

**Issue by Finnear** [BSData/wh40k-9e#10572]
**Describe the bug**
Attempting to add WH40K data into Bs Mobile crashes it from both appspot and github urls

**To Reproduce**
1. Go to add repository
2. Add either github or appspot

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - OS: [e.g. iOS] android
 - BattleScribe version [e.g. 2.03.45] current on Google play store 
 - Release version [e.g. v1.2.3] one google play store

**Additional context**

**Comment by Finnear** [comment]
Posted in discord I get to step 5 for gallery for Android before either Appspot and Github cause the crash

**Comment by Technoblazed** [comment]
Not a data issue, if you're having issues with the app crashing due to data issues, you'll just need to wait until the data repos are up as there is nothing we can do about it.
