### ISSUE TITLE
Imperium - Black Templars: Beastpyre Upgrade Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10571]
**File:** Imperium - Black Templars.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** For the Primaris Crusader Squads, I am unable to give them the Beastpyre upgrade as per the Relic Bearers rule despite giving one of the initiates the Pyreblaster. Upon further testing, I seem to be able to give it to other squads with Flamers, as well as give the Primaris Crusader Squad the Fist of Balphus if equipped with a Power Fist. As per the codex, the Beastpyre replaces either a Flamer or a Pyreblaster, so I'm unsure if this error is bases off of syntax or it was not included in the patch to begin with.

**Comment by Kybelor** [comment]
When selecting the second warlord trait with the Heir of Sigismund stratagem it gives an error of "Too many selections from warlord traits".

**Comment by acebaur** [comment]
> When selecting the second warlord trait with the Heir of Sigismund stratagem it gives an error of "Too many selections from warlord traits".

Please open a new issue for that

**Comment by acebaur** [comment]
The beastpyre issues has already been resolved

**Comment by DakVarad** [comment]
Found a similar issue on Windows version. Cannot give Fist of Balphus on Assault Intercessor with Power Fist.

**Comment by FarseerVeraenthis** [comment]
> The beastpyre issues has already been resolved
