### ISSUE TITLE
Imperium - Black Templars: Cannot give Fist of Balphus on Assault Intercessor with Power Fist.

### ISSUE THREAD

**Issue by FarseerVeraenthis** [BSData/wh40k-9e#10576]
Found a similar issue on Windows version. Cannot give Fist of Balphus on Assault Intercessor with Power Fist.

_Originally posted by @DakVarad in https://github.com/BSData/wh40k/issues/10571#issuecomment-946202475_

**Comment by acebaur** [comment]
This is fixed on master
