### ISSUE TITLE
Admonimortis unavail with Open The Vaults

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10580]
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Admonimortis does not appear ias an option when attempting to give a Terminator Shield Captain a relic via the OPEN THE VAULTS strategem. Making the Shield Captain the Warlord does not recreate the issue.

**Comment by Thairne** [comment]
![grafik](https://user-images.githubusercontent.com/8590840/138156766-8c855727-1916-4c00-a8e3-5a88038b27aa.png)
Cannot reproduce.
Admonimortis requires a Castellan Axe, not a Guardian Spear and appears if the former is selected.

**Comment by Technoblazed** [comment]
Can't reproduce and no further information given by reporter (anon posts zz)
