### ISSUE TITLE
Chaplain - Wise Orator

### ISSUE THREAD

**Issue by dice-viking** [BSData/wh40k-9e#10588]
**Describe the bug**
SW Chaplain can't have the Wise Orator Warlord Trait, even after upgrading to Master of Sancity - this seems to be a bug with the new update v.9.2.12. When opening an old roster where this WT could be selected, an error occurs:

![Screenshot from 2021-10-21 20-46-55](https://user-images.githubusercontent.com/92891352/138338800-530948d9-4358-4063-b17e-775a50c7867a.png)
[chaplain_error.txt](https://github.com/BSData/wh40k/files/7392174/chaplain_error.txt)

![Screenshot from 2021-10-21 20-48-30](https://user-images.githubusercontent.com/92891352/138338907-54b1749e-de4d-46d2-9adc-4a3fe637655b.png)

The validation error only disappears after deselecting the previously selected Wise Orator Trait .

**Comment by AbonShell** [comment]
You must still have a warlord traits to give them in order to take that warlord trait. Either with having them be your warlord, or having another character be your warlord and using the hero of the chapter strat.
