### ISSUE TITLE
relic supplement cult of strife drukhari glaive is missing

### ISSUE THREAD

**Issue by Pellexgrino** [BSData/wh40k-9e#10591]
drukhari relic supplement cult of strife glaive is missing.
cult of strife
HQ>succubus 
Glaive + relic supplement missing

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - BattleScribe version [e.g. 2.03.45]
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by AbonShell** [comment]
I believe this is use error, as I was able to equip the relic after making the correct selections

**Comment by FarseerVeraenthis** [comment]
> I believe this is use error, as I was able to equip the relic after making the correct selections

Agreed. Note that both your Warlord AND the Character trying to select the weapon must BOTH be Wych Cult of Strife. They need not be the same person.
