### ISSUE TITLE
Aeldari - Drukhari: Cult of Strife Relics not available when Heatrix of the Arena Stratagem is used w/o a Strife Warlord

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10598]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Hekatrix of the Crucibael strat should allow use of the Cult of Strife relics on a Hekatrix even withoit a Cult of Strife warlord. According to Book of Rust, Cult of Strife warlord is needed go assign the relics to a character, but the Hekatrix of the Crucibael names those relics specifically and onky requires a Cult of Strife detachment.

Currently, if Hekatrix of the Cruicbael start is selected without a Cult of Strife warlord, no relics are selectable.

**Comment by FarseerVeraenthis** [comment]
yup, this is an edge case, but the bug is valid... I'll see if I can fix it without getting a migraine with all the conditionals...!
