### ISSUE TITLE
FWAA: Sicaran punisher pintle stormbolter missing upgrade cost

### ISSUE THREAD

**Issue by Sicness** [BSData/wh40k-9e#10595]
**Describe the bug**

**To Reproduce**
1. Space Marines (maybe the same is true for chaos, I didn't check)
2. Choose Sany Sicaran unit.
3. Option Storm bolter is available without any cost because for some reason his 5 pts is already included in the base cost.

**Expected behavior**
Storm bolter should cost 5 pts and unit without options should cost 155 instead of 170. 

**Screenshots**
![2021-10-23_21-10-37](https://user-images.githubusercontent.com/349386/138565527-09d230f5-28ef-42f3-bf1c-e34d38a2e3bd.png)
![2021-10-23_21-11-00](https://user-images.githubusercontent.com/349386/138565535-f9d62eea-4a3f-4eae-a182-0de4103a04ec.png)
![2021-10-23_21-11-51](https://user-images.githubusercontent.com/349386/138565558-f20f6231-d6a1-4681-b3b0-3ac2c9ac34e7.png)

**Device and data (please complete the following information):**
 - data v9.2.13   2120 Oct 23

**Additional context**
I would make a PR with the fix, but in the previous time my PR was closed without any comment, so, I don't want to waste time again.

**Comment by CrumpetNinja** [comment]
You always have to pay an extra 15 pts for the Hull Heavy Bolter, which takes the base cost to 170.

**Comment by Sicness** [comment]
> You always have to pay an extra 15 pts for the Hull Heavy Bolter, which takes the base cost to 170.

Yes, I agree, but the issue regarding the 5 points for the bolter is actual.

**Comment by acebaur** [comment]
We typically don't accept PR from the community at large. While we use Github it is because it is convenient for bug reports and making changes to cats. Because of the way Battlescribe tends to make random changes it can cause nasty conflicts if two people are working on a cat at the same time.
