### ISSUE TITLE
Imperium - Legion of the Damned: Multi-Melta Points issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10609]
**File:** Imperium - Legion of the Damned.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** I have found that the multi-melta on the damned legionaires are actually 20points not 22 points for one

**Comment by Technoblazed** [comment]
Multi-meltas on LOTD are 22 points each - 
https://www.warhammer-community.com/wp-content/uploads/2019/12/36e76afc.pdf
