### ISSUE TITLE
[Anon] Bug report: Imperium - Black Templars (Old).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10606]
**File:** Imperium - Black Templars (Old).catz

**BattleScribe version:** 9.02.13

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Black Templars file: company champion has no chapter command upgrade options. Primaris crusader squad as described in supplement does not have restrictions on number of initiates or neophytes.  Current version restricts this.

**Comment by acebaur** [comment]
BT are not allowed to take a chapter champion as per codex SM

Primaris initiates are 5-11 and Primaris neophytes at 4-8 per the supplement
