### ISSUE TITLE
Incorrect calculation of number of Neophytes on Mobile

### ISSUE THREAD

**Issue by waldobuchner** [BSData/wh40k-9e#10607]
![image](https://user-images.githubusercontent.com/65628018/139213757-82980dfc-feae-4d9d-ae00-23283d0cb8df.png)

**Comment by Technoblazed** [comment]
Can't replicate on iOS which means this isn't a data issue. Unfortunately the app developer has been MIA for almost 2 years so there's close to no chance of getting whatever issue this is resolved. Try recreating the roster to see if that helps.

![Image](https://i.tech-no.me/2021/10/28/211028091315.png)
