### ISSUE TITLE
Deathwatch AoR Warlord Trait

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#10610]
**Describe the bug**
The Deathwatch Kill Team Strike Force warlord trait is available to characters when the AoR is not selected, butit shouldn't be available when the AoR is not selected

**To Reproduce**
1. Go to your warlord
2. Scroll down to the list of warlord traits
3.See Xenos Bane can be selected even though the Kill Team Strike Force AoR is not added in

**Expected behavior**
It should not be available unless the Kill Team Strike Force AoR is selected

**Screenshots**

**Device and data (please complete the following information):**
 - OS: iOS
 - BattleScribe version 2.03.15
 - Release version 9.2.13

**Additional context**

**Comment by Technoblazed** [comment]
Fixed in next release.
