### ISSUE TITLE
Chaos - Death Guard: Daemons Favour is currently too favourable

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10614]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The Daemons Favour (Wretched) artefact for Malignant Plaguecaster provides 1MW within 6" on roll <7, not within 12".

**Comment by raziel1013** [comment]
File: Chaos - Death Guard.catz

BattleScribe v2.03.21.166

Platform: PC & Android

Dropbox No

Description: When adding a second detachment for the Terminus Est force, the Harbinger of Death Trait is flagged as a validation error. I made sure that both detachments have the Harbinger as Plague Company and a Terminus Est force.
