### ISSUE TITLE
Can't remove weapons from T'au Coldstar Battlesuit

### ISSUE THREAD

**Issue by dark-alman** [BSData/wh40k-9e#10618]
Filename: Tau empire.catz

BattleScribe version: 2.03.21

Platform: Windows

**Describe the bug**
T'au codex references that the Coldstar Battlesuit can replace either it's High output burst cannon and/or missile pod with any item in the ranged weapon or Support Systems list.

But removing the missile launcher throws an error saying that it's 'minimum 1' when it isn't

**Comment by Technoblazed** [comment]
This was FAQ'd years ago, it's no longer `and/or`, it's `and` now. If you want the high output burst cannon, you have to take a missile launcher.

https://www.warhammer-community.com/wp-content/uploads/2019/10/12VoN8wWcwf0amfi.pdf

![Image](https://i.tech-no.me/2021/10/29/211029060946.png)
