### ISSUE TITLE
Tyranids synaptic links should be limited on number based on battle size

### ISSUE THREAD

**Issue by MatteoCesari78** [BSData/wh40k-9e#10620]
There is a limit of synaptic links you can use/purchase based on the battle size (1/2/3/4), so would be useful an alert when constructing tyranids lists

**Comment by GenWilhelm** [comment]
The limit is on the number that you can activate, rather than the number that you can purchase, so it's legal for an army to have more than the specified number.

Unfortunately, we can't do "soft" warnings, so it falls on the player to remember this limit exists.
