### ISSUE TITLE
 FW Sqauiggoth missing Waaagh rules 

### ISSUE THREAD

**Issue by whitewolfmxc** [BSData/wh40k-9e#10638]
Page 197 – Squiggoth, Abilities
Replace ‘’Ere we go, Dakka! Dakka! Dakka! (see Codex: Orks)’
with ‘’Ere we go, Ramshackle, Waaagh! (see Codex: Orks)’

FW Sqauiggoth missing Waaagh rules

**Comment by Technoblazed** [comment]
All `ORKS` units benefit from the Waaagghhhh rule, it's listed at the bottom of the roster output.
