### ISSUE TITLE
Both FW Ork Mega dread / Meka dread , missing Waagh rule 

### ISSUE THREAD

**Issue by whitewolfmxc** [BSData/wh40k-9e#10637]
Page 195, 196 – Mega Dread, Meka-dread, Abilities
Replace ‘’Ere we go, Dakka! Dakka! Dakka! (see Codex: Orks),
Ramshackle (see the Trukk datasheet in Codex: Orks)’ with ‘’Ere
we go, Ramshackle, Waaagh! (see Codex: Orks)

Both Mega dread / Meka dread , missing Waagh rule

**Comment by Technoblazed** [comment]
All `ORKS` units benefit from the Waaagghhhh rule, it's listed at the bottom of the roster output.
