### ISSUE TITLE
mIssing Waagh rules for both Grot tank and Grot mega tank

### ISSUE THREAD

**Issue by whitewolfmxc** [BSData/wh40k-9e#10636]
Page 194 – Grot Tanks, Grot Mega-Tank, Abilities
Replace ‘Dakka! Dakka! Dakka! (see Codex: Orks), Ramshackle
(see the Trukk datasheet in Codex: Orks)’ with ‘’Ere we go,
Ramshackle, Waaagh! (see Codex: Orks)’

mIssing Waagh rules for both Grot tank and Grot mega tank

**Comment by Technoblazed** [comment]
All `ORKS` units benefit from the Waaagghhhh rule, it's listed at the bottom of the roster output.
