### ISSUE TITLE
Aeldari - Craftworlds: Wraithseer should be able to choose the special detachment psychic power Twilight Gloom

### ISSUE THREAD

**Issue by marradius** [BSData/wh40k-9e#10640]
**Aeldari - Craftworlds**
When selecting the stratagem for Specialist Detachment: Wraith Host, a Wraithseer should be able to choose the specific psychic power "Twilight Gloom". This happens because it is not gaining the keyword "WRAITH HOST" when you choose the Specialist Detachment: Wraith Host.

**Expected behavior**
A Wraithseer is a "PSYKER" and should be a "WRAITH HOST" because it is a "WRAITH CONSTRUCT", so it is eligible to take "Twilight Gloom" as a Rune of Battle psychic power when you take the stratagem for Specialist Detachment: Wraith Host.

**Screenshots**
![Captura de pantalla 2021-11-04 064049](https://user-images.githubusercontent.com/93698120/140263760-78261cb4-7730-4d0e-bac9-ad955e46e36f.png)

**Device and data:**
OS: Windows 10 Home
BattleScribe version [2.03.21]
Release version [195]

**Comment by FarseerVeraenthis** [comment]
Seems ok to me...
![Screenshot_20211104-204833](https://user-images.githubusercontent.com/23246922/140417859-dda66086-5d32-4708-ab0b-f770a36c7716.png)

**Comment by FarseerVeraenthis** [comment]
#wrongissue
