### ISSUE TITLE
Dark Angels - Ravenwing Talonmaster cannot take Paragon of the Chapter

### ISSUE THREAD

**Issue by MidnightLlamaman** [BSData/wh40k-9e#10641]
Ravenwing Talonmaster cannot take Paragon of the Chapter, comes up as Ravenwing Talonmaster has 1 too many selections of Stratagem: Paragon of the Chapter (maximum 0)

**Comment by FarseerVeraenthis** [comment]
![Screenshot_20211104-204833](https://user-images.githubusercontent.com/23246922/140418358-74cf650e-bf2f-4c71-bcb7-c727f7a2eb81.png)
Seems ok to me, note that the model must be the warlord...
