### ISSUE TITLE
Super-Heavy Aux Detachments don’t allow Ork Clan Cultures to be selected

### ISSUE THREAD

**Issue by AdmiralAntz** [BSData/wh40k-9e#10642]
When adding a SHA detachment in an Orks list, one of 2 things happens. Either an option for clan cultures pops up with a message say “No clan cultures can be selected (hidden)” and no shared faction bonus appears in the configuration options, or the options for clan cultures is not present while the shared faction bonus is. Clan Cultures should be selectable, much like Houses can be for Imperial Knights.

Clan Cultures appear only when adding the detachment when you first create the list and are absent if you were to add the SHA detachment to an already existing list.

![A44450BE-B6CD-46F8-9E49-39B8AE29A3F9](https://user-images.githubusercontent.com/93706536/140288311-41558969-2972-4668-889b-715a66534db6.png)
![792D917B-378A-4751-A926-77831892028D](https://user-images.githubusercontent.com/93706536/140288312-0db11be0-e8cd-4d7b-93ae-67d10e9c28fc.png)
![969BBAF0-1D15-4294-A1DD-22BFD76D27A6](https://user-images.githubusercontent.com/93706536/140288315-8188379a-345b-4344-88dc-f66120932121.png)

 - OS: 14.8
 - BattleScribe version 2.03.15
 - Warhammer 40,000 v9.2.14

**Comment by Technoblazed** [comment]
Already fixed in the next release.
