### ISSUE TITLE
Orks - Remove Boom Boyz from Wazbomb Blasta Jet

### ISSUE THREAD

**Issue by GinFizzz** [BSData/wh40k-9e#10653]
**Describe the bug**
The Wazbomb Basta-Jet is not listed in the codex for the Boom Boyz specialist mob.

**To Reproduce**
1. Add a Wazbomb BlastaJet to a list
2. View the allowed Specialist Mob

**Expected behavior**
The Boom Boyz selection should not be possible for the Wazbomb Blastajet, or any of the Ork Flyers.

**Screenshots*
![javaw_5hnnVKjazJ](https://user-images.githubusercontent.com/47032978/140674798-432b9f1f-4d30-4e87-94c7-d44b11bc14cd.png)
*

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version v2.03.21.166 
 - Release version v196

**Comment by Technoblazed** [comment]
The blastajet has the MEK keyword so is eligible for it.
