### ISSUE TITLE
Space Marines — minimal output errors

### ISSUE THREAD

**Issue by Scope40k** [BSData/wh40k-9e#10654]
The following options are currently shown in the minimal output, though they only should appear in the full output:
- Incursor Squad, Incursor:  Bolt pistol, Frag & Krak grenades, Occulus bolt carbine, Paired combat blades 
- Intercessor Squad, Intercessor: Bolt pistol, Frag & Krak grenades
- Infiltrator Squad, Infiltrator: Bolt pistol, Frag & Krak grenades, Marksman bolt carbine
- Assault Intercessor Squad, Assault Intercessor: Astartes Chainsword, Frag & Krak grenades, Heavy Bolt Pistol
- Heavy Intercessor Squad, Heavy Intercessor: Bolt pistol, Frag & Krak grenades
- Reiver Squad, Reiver: Frag & Krak grenades, Special issue bolt pistol
- Veteran Intercessor Squad, Veteran Intercessor: Frag & Krak grenades
- Outrider Squad: Outrider: Astartes Chainsword, Frag & Krak grenades, Heavy Bolt Pistol, Twin Bolt rifle
- Suppressor Squad, Suppressor: Accelerator autocannon, Bolt pistol, Frag & Krak grenades
- Eliminator Squad, Eliminators: Bolt pistol, Camo cloak, Frag & Krak grenades
- Eradicator Squad, Eradicator: Bolt pistol
- Hellblaster Squad: Hellblaster: Bolt pistol, Frag & Krak grenades
All these selections are basic wargear, not options, and cannot be changed or replaced.

**Comment by alphalas** [comment]
One, you seem to misunderstand what minimal output does, and Two, it isn't a standardized system, so it's really up to the individual cat maintainer what appears on minimal and what doesn't.￼￼
