### ISSUE TITLE
Imperium - Black Templars: Missing ability should be missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10661]
**File:** Imperium - Black Templars.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** When list building with the newest version of the black templars list, infantry unit do not have the "defenders of humanity" ability. Intercessors incursors infiltrators etc. I built a list with blood Angel's and several other chapters to ensure they showed up elsewhere. Only black templars infantry are missing this ability.

**Comment by acebaur** [comment]
This ability no longer exists for space marines. It will be deleted from other catalogs as well.
