### ISSUE TITLE
Chaos Knighta: Magaera has incorrect Faction keyword

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10666]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The forgeworld chaos Magaera is missing the faction keyword chaos knights which can be found on the downloadable database on the forgeworld website

**Comment by Mad-Spy** [comment]
Fixed in next release
