### ISSUE TITLE
Chaos Forgeworld Dreads should not have Hateful Assault and Malicious Volleys

### ISSUE THREAD

**Issue by Whatshisface0170** [BSData/wh40k-9e#10663]
**Describe the bug**
Chaos Forgeworld dreadnoughts no longer have Hateful Assault and Malicious Volleys abilities as of Forgeworld Compendium.

**To Reproduce**
1. Add a force of any Chaos Space Marines armies (Death Guard, Thousand Sons, Chaos Space Marines)
2. Add Chaos Contemptor, Chaos Deredeo, and /or Chaos Leviathan 
3. See in rules that they have Hateful Assault and Malicious Volleys abilities

**Expected behavior**
The forgeworld chaos dreads should not have the above abilities 

**Screenshots**
![image](https://user-images.githubusercontent.com/93994209/140946073-1d72053b-abac-4a6a-ac61-d58f527f1d08.png)
![image](https://user-images.githubusercontent.com/93994209/140946138-b5843051-04bf-4375-bbb4-62e66aa5a64b.png)

**Device and data (please complete the following information):**
 - BattleScribe version 2.03.21

**Additional context**

**Comment by Mad-Spy** [comment]
These models get those rules in a CSM Detachment by virtue of being in that Detachment.

However, they were incorrectly being shown in TSons and Death Guard.
