### ISSUE TITLE
Space Marine HQ Wargear Selections

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#10664]
**Describe the bug**
The Captain should come with an Astartes chainsword by default but currently does not 
The Captain on Bike should come with a bolt pistol and Astartes chainsword by default but currently does not
The Captain in Terminator Armour should with a power sword and storm bolter by default but currently does not
The Chaplain should come a bolt pistol by default but currently does not
The Chaplain in Terminator Armour should come with a storm bolter by default but currently does not
The Librarian should come a bolt pistol by default but currently does not
The Librarian should have a force stave by default but currently has a force sword
The Lieutenant should have an Astartes chainsword and master crafted boltgun by default but currently does not
The Techmarine should come a bolt pistol by default but currently does not
This is for all the Space Marine chapters

**To Reproduce**

**Expected behavior**
A captain should have an astartes chainsword and master crafted boltgun by default when selected
A captain on bike should have an astartes chainsword and bolt pistol in addtion to the twin boltgun by default when selected
A captain in terminator armour should have a power sword and storm bolter by default when selected
A chaplain should have a bolt pistol by default when selected 
A chaplain in terminator armour should have a storm bolter by default when selected
A librarian should have a force stave and bolt pistol by default when selected
A lieutenant should have an astartes chainsword and master crafted boltgun by default when selected
A techmarine should have a bolt pistol and omnissian power axe by default when selected

**Screenshots**

**Device and data (please complete the following information):**
 - OS: iOS
 - BattleScribe version 2.03.15
 - Release version 9.2.15
**Additional context**

**Comment by acebaur** [comment]
All of these are because those weapons are also in a weapons group like "Pistols" or "Melee" weapons. Adding an additional one would be redundant since you can just select the option you want and get the same result.
