### ISSUE TITLE
Dark Angels Primaris Captain Error

### ISSUE THREAD

**Issue by fishking1702** [BSData/wh40k-9e#10660]
![F6876B17-AC2D-421A-8336-390007A0FC23](https://user-images.githubusercontent.com/93907161/140707843-664efde8-099d-41fe-82a1-926c98399eb9.png)
![18125F47-5F93-4EBA-A67A-B64065996E75](https://user-images.githubusercontent.com/93907161/140707847-dbb47cab-121e-471c-b5f9-36e42d0df954.png)
![488C484A-BAB4-4A5D-8DDE-5756226C9737](https://user-images.githubusercontent.com/93907161/140707848-6063982d-d52f-48a0-8888-ee1c0b82cae1.jpeg)
**Describe the bug**
So i don't know if i missed an FAQ or something but for some reason on battlescribe if you equip a primaris captain with a SI bolt carbine you can't equip a MC power sword when you should be able to.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - BattleScribe version [e.g. 2.03.45]
 - Release version [e.g. v1.2.3]

**Additional context**
The data sheet for a primaris captain it says “if this model is equipped with a SI Bolt Carbine and is not equipped with a MC power sword, it can equip a power fist” insinuating it can be given a MC power sword

**Comment by FarseerVeraenthis** [comment]
The current behaviour is correct.

- In order to be equipped with a MC Power Sword you must have an MC Auto Bolt Rifle.
- To gain an SI Bolt Carbine you must replace the MC Auto Bolt Rifle.
- Therefore, you cannot have an SI Bolt Carbine AND be equipped with an MC Auto Bolt Rifle.
- Since you do not have an MC Auto Bolt Rifle, you cannot equip a MC Power Sword.

The final point in this datasheet is not relevant to this discussion.

**Comment by fishking1702** [comment]
You are correct if we look at the order but that last part is very much relevant as it implies that a SIBC can carry a MC power sword. I also believe that the order is very much invalid seeing as these are at the bottom because of their exclusivity to the dark angels. Also if a MC power sword and a SIBC can't be equiped together why are they in the same kit without a "no melee" option, the kit comes with a MC power sword, a SIBC, and a Powerfist. Both this and the wording in the warhead implies that they can be run together order of war gear be damned.

**Comment by FarseerVeraenthis** [comment]
Yeah, you got me, I forgot about the order thing, it is now fixed on master and ready for the next release :-)

**Comment by fishking1702** [comment]
Thank you

**Comment by fishking1702** [comment]
Several updates have come out and nothing has changed with the DA primaris captain yet. When is it going to be fixed?

**Comment by FarseerVeraenthis** [comment]
Erm.... It should already be fixed... I'll check later 🙂

**Comment by FarseerVeraenthis** [comment]
right so, I did update the file nearly three weeks ago, but looks like I forgot to increment the revision.
I've just repeated the update, with a version increment, so it should be in the next release :-)
