### ISSUE TITLE
Drukhari relics headache

### ISSUE THREAD

**Issue by MatteoCesari78** [BSData/wh40k-9e#10676]
While it is allowed to choose for characters to pick different kabals/whyces cults/covens of the detachment they are in, it shouldn't be possible to pick the relic of the kabal/whyces cult/coven of the character if a detachment with the same keyword is not present in the army. 
It is still not 100% clear if we can use special kabals/whyces cults/covens relics if the warlord is not from those and we are not using the real space raid detachment, but it is pretty clear that we cannot use those relics if we dont have a detachment defined with those keywords.

**Comment by FarseerVeraenthis** [comment]
Looking at it, I think You're right.
The Warlord for the army needs to have the appropriate Obsession to unlock the Kabal/Cult/Coven specific relics.
Unless you're building a Realspace Raid of course...
TBH, this is pretty straightforward when you look at the codex:
![image](https://user-images.githubusercontent.com/23246922/141536538-6ba12087-e59b-4d34-8f8c-6813b3d116d7.png)


I'll see what I can do, but I'm currently trying to prepare my army for a tournament next weekend and I have - for me - A LOT of painting to do...!!

**Comment by FarseerVeraenthis** [comment]
closed
