### ISSUE TITLE
Imperium - Astra Militarum: Tank Commander and Knight Commander Pask saves still showing as 3+

### ISSUE THREAD

**Issue by MrRWJP** [BSData/wh40k-9e#10679]
File: Imperium - Astra Militarum.catz v307

BattleScribe version: 2.03.21

Platform: PC

Dropbox: Yes

Description: As per the new Balance Dataslate, ASTRA MILITARUM LEMAN RUSS models have had their save improved to 2+. This has been correctly updated on the regular Leman Russ datasheet, but has not been updated on the Tank Commander or Knight Commander Pask datasheets even though they both the ASTRA MILITARUM and LEMAN RUSS keywords.

**Comment by Technoblazed** [comment]
Already fixed int he next release.
