### ISSUE TITLE
Aeldari - Drukhari Show Stealer for Cult of Strife is missing

### ISSUE THREAD

**Issue by lgrant013** [BSData/wh40k-9e#10670]
Show Stealer is unselectable as Cult of Strife, is visible for Cursed Blade and Red Grief
Gives me an error saying this "cannot be selected (hidden)"

 - OS: Windows
 - BattleScribe version 2.03.21
 - Release version Warhammer 40k v9.2.15

**Comment by lgrant013** [comment]
Issue was happening after attempted to create a new roster, after a few attempts of closing and reoping the app, it seems to have stopped?

**Comment by lgrant013** [comment]
My appologies. I think I see when its happening. If you select the succubus and give her Show Stealer for Cult of Strife but add Lelith Hesperax, Show Stealer becomes unavailable to Succubus

**Comment by Valorcalls** [comment]
That would be working as intended, given you can't have 2 master succubuses from the same cult.

**Comment by FarseerVeraenthis** [comment]
@Valorcalls takes the win. 
Lelith has the Master Succubus keyword, and the Faction: Cult of Strife keyword, as such, you cannot have another Show Stealer for the Cult of Strife.

**Comment by lgrant013** [comment]
If thats the case then, no error is given if you do the same but with master haemonculus and urien rakarth in the same detachment

**Comment by FarseerVeraenthis** [comment]
> If thats the case then, no error is given if you do the same but with master haemonculus and urien rakarth in the same detachment

That is a different bug 👍
