### ISSUE TITLE
Imperium - Officio Assassinorum: Execution Force does not refund CP

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10672]
**File:** Imperium - Officio Assassinorum.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Creating an Imperial Knights army with an added Officio Assassinoruim Vanguard Detachment doesn't offer the CP discount for Execution force

EXECUTION FORCE
If your Warlord has the IMPERIUM keyword (excluding FALLEN), you can include this unit in your army as part of a Vanguard Detachment even if that Detachment contains no HQ units. If you do so, that Detachment’s Command Benefits are changed to ‘None’ and its Restrictions are changed to ‘This Detachment cannot include the same datasheet more than once.’

**Comment by Mad-Spy** [comment]
Nothing in the text for the Execution Force rule states that the CP cost is refunded. Command Benefits are not the same thing as Command Cost.
