### ISSUE TITLE
Necrons: Trazyn should discount 1st spend on extra relics

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10680]
**File:** Necrons.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Trazyn The Infinite is supposed to make your first use of the extra relic stratagem cost zero CP. He does not in battlescribe.

**Comment by DrTobogganMD** [comment]
He already does this. He adds 1CP if you have him and the stratagem.
