### ISSUE TITLE
Ultramarines - Assault Intercessor Sergeant is unable to take Teeth of Terra

### ISSUE THREAD

**Issue by Gimnae** [BSData/wh40k-9e#10681]
File/Catalogue: Imperium - Adeptus Astartes - Ultramarines v55

BattleScribe v2.03.21.166

Platform: Windows

Dropbox: No

Description: When using the Honoured Sergeant stratagem, the Teeth of Terra not show as an option for the Assault Intercessor Sergeant when he is equipped with an Astartes Chainsword.

**Comment by acebaur** [comment]
Correct, because that's not a relic he can have.

**Comment by Gimnae** [comment]
I am sorry, I read the thing all wrong. My mistake, thanks for correcting me :)
