### ISSUE TITLE
Astra Militarum — Leman Russ Sponsons

### ISSUE THREAD

**Issue by Scope40k** [BSData/wh40k-9e#10686]
Minor bug: Leman Russ units and Tank Commanders have their sponson options shown in preview (both html and text) separately, as a child unit, not as a regular wargear selection.

**Comment by Technoblazed** [comment]
The sponsons are in the wargear section of the datasheet, so they'll stay as a regular wargear selection, not a child unit.

**Comment by Scope40k** [comment]
Yes, it's done as an upgrade, but it looks the same way as a child unit in the roster output:
![Screenshot_1](https://user-images.githubusercontent.com/93893613/141714864-bce687a1-9505-4756-bf75-da858fddb2ae.png)

To avoid this each Selection Entry in Selection Entry Group "Sponson Weapons" should contain info links (Heavy Bolter (Shared), Plasma Cannon (Shared), etc.) instead of Entry Links. It will then look like this:
![Screenshot_2](https://user-images.githubusercontent.com/93893613/141716314-b9e60f60-ca13-488d-aaeb-7865358bbe39.png)

P.S.: there is no difference between upgrades with subselections and child units in the output html files, which is really wierd — I planned to apply custom styles to the page, and I cannot set different styles for these two completely different entities as they have the exact same output in the html.

**Comment by alphalas** [comment]
It's that way because there previously were bug reports about the sponsons not obviously visibly reflecting as being 2 weapons, so they were nested in wrappers to make it explicitly obvious without creating needless duplication. sorry.
