### ISSUE TITLE
Imperium - Black Templars: Revered Repositories validation error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10693]
**File:** Imperium - Black Templars.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** when using the revered repositories stratagem i am able to give a master crafted power sword plus one other relic to two sergeants without an error generating (other crusade relics do trigger an error)

**Comment by acebaur** [comment]
This is already fixed. Update your data
