### ISSUE TITLE
Orks New Narrative HQ Points cost

### ISSUE THREAD

**Issue by SoSaltySalt** [BSData/wh40k-9e#10698]
**Describe the bug**
The new Manik Gorg Defkopta character should be 70pts from the pics I saw. Also should be able to take a WLT(but not 100% on that)

(I know for sure that I'm on the latest version, since he was added right now)

**Comment by Technoblazed** [comment]
It has a forced warlord trait which is automatically added when you make him your warlord, I should probs add the strat though

**Comment by SoSaltySalt** [comment]
Couldn't make him my Warlord is what I meant
