### ISSUE TITLE
Outdated Points cost for Craftworlds Dark Reapers

### ISSUE THREAD

**Issue by NottanAjin** [BSData/wh40k-9e#10703]
As of Chapter Approved Munitorum Field Manual 2021, Dark Reapers cost 35ppm (total 105pts for MSU), but they are currently still listed by their 8th edition costs of 32ppm (total 96pts for MSU).

**Comment by Mad-Spy** [comment]
Cost is correct in the current release version (Craftworlds v139) as per MFM2021 MkII. Looks like your reference is out of date.

![image](https://user-images.githubusercontent.com/29306451/142841054-d6321bda-135d-4c9c-bd8c-39063469fd24.png)

![image](https://user-images.githubusercontent.com/29306451/142840900-ab7eab20-f205-4c15-b5b0-ed2367479023.png)
