### ISSUE TITLE
Ork crusade Looted vehicles not found ?

### ISSUE THREAD

**Issue by whitewolfmxc** [BSData/wh40k-9e#10700]
The 3 Ork looted vehicle units in  Octarius book 2 is not found anywhere ?

it should be in open play 

Looted wagon , Havy looted wagon , Battle fortress

**Comment by whitewolfmxc** [comment]
For some reason, these now only show up in a already-created list but not when you creating a new list (with open format)

**Comment by whitewolfmxc** [comment]
![Uploading 螢幕截圖 2021-11-30 11.05.23.png…](
![螢幕截圖 2021-11-30 11 05 28](https://user-images.githubusercontent.com/65846291/143978464-d46ab49a-e230-4b00-94a7-f8a319d2e12c.png)
)

**Comment by whitewolfmxc** [comment]
![螢幕截圖 2021-11-30 11 05 23](https://user-images.githubusercontent.com/65846291/143978483-8d314e9e-d00b-4f0f-8384-2ea734dc1a00.png)

**Comment by Technoblazed** [comment]
You have no meks in your list?
