### ISSUE TITLE
Chaos Rhino does not have normal combi-bolter as default weapon.

### ISSUE THREAD

**Issue by Hakoborino** [BSData/wh40k-9e#10710]
**Describe the bug**
A Chaos Rhino normally comes with a regular Combi-Bolter at stat line 24" | Rapid Fire 2 | 4 | 0 | 1. However, if you go on to a Chaos Rhino (for me in a Thousands Sons detachment) you will see that even though Inferno Combi-Bolter is NOT selected in the weapons, it will still show up when the model's sheet is preview in the app instead of the regular combi bolter. The inferno combi-bolter is a more expensive and more powerful version with a statline of 24" | Rapid Fire 2 | 4 | -2 | 1.

</body>
</html>

**To Reproduce**
Create Chaos Detachment (for me it was a Thousand Sons Patrol)
Add Chaos Rhino
Check to see Inferno Combi-Bolter is not checked
Preview the unit to see which weapon is there

**Expected behavior**
The unit should come with a combi-bolter stat-line, instead inferno combi-bolter always shows.

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version [e.g. 2.03.45]
 - Release version [e.g. v1.2.3]

**Comment by Mad-Spy** [comment]
A Thousand Sons Chaos Rhino _does_ come with an inferno combi-bolter as its default weapon, as per its datasheet.

![image](https://user-images.githubusercontent.com/29306451/143430204-098da017-f476-4d06-bb8f-6a116d8384e5.png)
