### ISSUE TITLE
Can't Eldrad Ulthran

### ISSUE THREAD

**Issue by coolivistos** [BSData/wh40k-9e#10715]
I can't fin Eldrad in HQ selection

![image](https://user-images.githubusercontent.com/95115465/143668149-34048b8e-4574-4c55-9485-166bc2e89451.png)

**Comment by AbonShell** [comment]
Must be either an Ulthwé or mixed detachment

**Comment by coolivistos** [comment]
![image](https://user-images.githubusercontent.com/95115465/143668349-4caad6c3-3df2-4dec-87f1-3d233485fbe8.png)


i still can't fin it

**Comment by AbonShell** [comment]
![SmartSelect_20211126-235304](https://user-images.githubusercontent.com/20672472/143668477-e2cc0628-b1a5-4e9f-8e6f-f8b6f54348e0.jpg)
