### ISSUE TITLE
Imperium - Space Wolves: Sky Claw Wolf Guard Pack Leader should have 2 wounds

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10714]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Space Wolves Wolf Guard Skyclaw Pack Leader has 1 wound in this dataset--that model should have 2 wounds like the rest of the Wolf Guard Pack Leaders. I looked at the other WG Pack Leaders for other Space Wolves units and those are all correct (i.e. they have 2 wounds). Thanks for your work!

**Comment by AbonShell** [comment]
Duplicate of #10713
