### ISSUE TITLE
More Drukhari cult/kabal/coven selection woes

### ISSUE THREAD

**Issue by ThePants999** [BSData/wh40k-9e#10718]
Thanks for making it possible to select the Kabal / Coven / Wych Cult for units individually. A couple of follow-on issues:

 - If you select "custom", you're unable to select _which_ custom one. A number of post-dataslate Drukhari lists include both a Dark Technomancers detachment and an Artists of the Flesh detachment, and also include one or more Coven units in a third, non-Coven detachment. It's important to be able to specify which of the custom Covens these units are from.

 - Currently, you're allowed to select "As Detachment" for a unit whose type doesn't match the detachment, e.g. Wyches in a Kabal detachment. It would be nice if this caused an error.

**Comment by FarseerVeraenthis** [comment]
Custom obsessions follow the same path for selection;
![image](https://user-images.githubusercontent.com/23246922/144111775-751727cd-f02b-45ba-be54-215eb6566203.png)

Regarding the 'As Detachment' situation, these units would then have no keyword at all, so they wouldn't be targettable by any stratagem/aura/effects from any other detachment. As such, this means the player should know they need to select a specific Obsession for that unit and make the selection. An error of the type you are suggesting would also be against one of our codes of practice in that when you add a unit it shouldn't flag an error by default - if it can be avoided. I'll see if it can be implemented cleanly, but the logic in the Drukhari cat is already pretty mind-bending so don't hold your breath!!

**Comment by ThePants999** [comment]
![image](https://user-images.githubusercontent.com/2923823/144115581-ec3839f0-3db8-429b-a735-4e379e20955e.png)

Your screenshot matches what I see for selecting the _detachment_ Obsession, but I don't see the same thing on a per-unit basis.

**Comment by FarseerVeraenthis** [comment]
That's not how obsessions work.
They are selected on a detachment basis and apply to the units within that detachment with the relevant keywords.
There is no way to select them on a per unit basis because there is no need to select them on a per unit basis...

**Comment by ThePants999** [comment]
That is not true. Well, it's partially true, but I'm not talking about Obsession here because a unit doesn't get an Obsession when it's in a mismatched detachment, I'm talking about which Kabal/Cult/Coven a unit is from in the first place. Quoting from the codex:

> Many datasheets in this section have either the \<KABAL>, \<WYCH CULT> or \<HAEMONCULUS COVEN> keyword. These are keywords that you can select for yourself, as described in the Warhammer 40,000 Core Book, with the guidance detailed below.
> 
> When you include a \<KABAL>, \<WYCH CULT> or \<HAEMONCULUS COVEN> unit in your army, you must nominate which Kabal, Wych Cult or Haemonculus Coven it is from and then replace the \<KABAL>, \<WYCH CULT> or \<HAEMONCULUS COVEN> keyword in every instance on its datasheet with the name of your chosen Kabal, Wych Cult or Haemonculus Coven.

In other words, when adding a unit of (say) Wyches to my army, I am REQUIRED to select which Wych Cult it is from so that I can replace <WYCH CULT> on its datasheet with, for example, CULT OF STRIFE - and that is necessary so that opponents know which Wyches are valid targets for Cult of Strife stratagems, or benefit from the Brides of Death aura from a Cult of Strife Succubus.

Going back to my original example. Let's say that I have a custom Coven which I name Alpha, for which I choose Artists of the Flesh as its Obsession, and another custom Coven which I name Beta, for which I choose Dark Technomancers. I then build a list like this:

Patrol 1: Coven (Custom: Artists of the Flesh)
 - Haemonculus 1 (As Detachment)
 - Wracks 1 (As Detachment)

Patrol 2: Coven (Custom: Dark Technomancers)
 - Haemonculus 2 (As Detachment)
 - Wracks 2 (As Detachment)
 
Patrol 3: Kabal (Black Heart)
 - Archon (As Detachment)
 - Wracks 3 (Custom Coven)

Wracks 3 does not gain an Obsession because it is not in a Coven detachment. However, its \<COVEN> keyword is still supposed to be replaced with an actual Coven, and whether it is replaced with ALPHA or BETA determines whether it benefits from the Master of Pain aura from Haemonculus 1 or Haemonculus 2. The current BSdata implementation does not allow me to specify.

**Comment by FarseerVeraenthis** [comment]
I appreciate this situation, but we're rapidly approaching the limits of possibility for BS.
As I said originally, I'll have a look and see what I can do, but I can't make any promises...!
