### ISSUE TITLE
FW Adeptus Astartes: Storm bolter on Sicaran Arcus should cost 5pts

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10712]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Dear developer. 
First of all a huge thank you for your work. 
One small mistake if I may. 
For the Sicaran Arcus Tank. Heavy support. FW Imperium. 
In my blood angels list. 
The Storm Bolter option should cost 5 points and be free as it is now. 
Thank you !

**Comment by Mad-Spy** [comment]
Duplicate of #10595
