### ISSUE TITLE
Forge-world specific warlord traits do not appear for marshal (other than charadon extras)

### ISSUE THREAD

**Issue by kpasko** [BSData/wh40k-9e#10716]
After selecting a forge world and specifying a marshal warlord, the associated warlord trait for that forge world does not appear in the options. The options appear correctly for tech priest warlords.

1. Choose forge world in 40K 9th, admech
2. Add a marshal and make warlord
3. Attempt to choose forge world warlord trait (eg luminescent blessing)
4. No special trait available (regardless of forge world)

**Expected behavior**
Marshal warlords should be able to get forge world warlord traits the same as tech priest warlords

**Screenshots**
![image](https://user-images.githubusercontent.com/167271/143701013-51f4902a-e842-4119-82ef-7f290443711a.jpeg)

![image](https://user-images.githubusercontent.com/167271/143701097-7e75101f-c145-4c3c-9872-94158d367092.jpeg)

**Device and data (please complete the following information):**
 - OS: iOS 
 - BattleScribe version 2.03.15

**Comment by Technoblazed** [comment]
> Each Forge World has an associated Forge World Warlord Trait. If an ADEPTUS MECHANICUS <FORGE WORLD> TECH-PRIEST CHARACTER model gains a Warlord Trait, they can have the relevant Forge World Warlord Trait instead of Adeptus Mechanicus Warlord Traits.

The Skitarii Marshall does not have the `TECH-PRIEST` keyword, so can't use the forge world specific warlord traits.
