### ISSUE TITLE
Lord Castellan Creed warlord trait vs tank ace

### ISSUE THREAD

**Issue by jmrbaptista** [BSData/wh40k-9e#10720]
**Issue**
When building a WARHAMMER 40K - ASTRA MILITARUM army list with the CADIAN REGIMENTAL DOCRINE, After:
1- including Lord Castellan Creed 
2- selecting Creed as the army warlord but NOT giving him the WARLORD TRAIT
3- including any TANK with the TANK ACE upgrade (LEMAN RUSS, MANTICORE, BASILISK or WYVERN).
4- selectinga TANK ACE ability for that TANK.

As per rules "If an ASTRA MILITARUM CHARACTER is your Warlord, rather than determining a Warlord Trait for that model, you can instead select one Tank Ace ability for an ASTRA MILITARUM VEHICLE model from your army.".

However When i select Lord Castellan Creed as the WARLORD, it always ask for the WARLOD TRAIT even if i selected a TANK ACE ability on any of those Vehicles.

**Expected behavior**
It should not point as error the fact that Lord Castellan Creed has no WARLORD TRAIT because of the fact that a TANK ACE is selected

**Comment by Technoblazed** [comment]
Under the Named Characters and Warlord Traits section:
> If a named character with a specific regiment keyword is your Warlord, they must be given the associated Warlord Trait. For example, Colonel ‘Iron Hand’ Straken must take the Catachan ‘Lead From the Front’ Warlord Trait as he has the CATACHAN keyword.

Under Tank Aces, it specifies `can instead`, as `must` is used in the NC&WT section, must takes preference over can, so they must take the Warlord Trait.

**Comment by alphalas** [comment]
Creed CANNOT not have a WLT if he's your warlord. Per the codex, named characters nominated to be warlord MUST HAVE the warlord trait appropriate to their regiment

**Comment by jmrbaptista** [comment]
Undestood, my bad! Thank you for the quick response.
