### ISSUE TITLE
Ork Characters missing options

### ISSUE THREAD

**Issue by whitewolfmxc** [BSData/wh40k-9e#10724]
all the Legend Ork characters are missing both options for 

Stratagem: Big Boss

Use this Stratagem before the battle, when you are mustering your army, if your WARLORD has the ORKS keyword. Select one ORKS CHARACTER from your army and determine one Warlord Trait for that model (this must be a Warlord Trait they could have); that model it is only regarded as your WARLORD for the purposes of that Warlord Trait. Each Warlord Trait in your army must be unique (if randomly generated, re-roll duplicate results), and you cannot use this Stratagem to give a model two Warlord Traits. You can only use this Stratagem once, unless you are playing a Strike Force battle (in which case you can use this Stratagem twice) or an Onslaught battle (in which case, you can use this Stratagem three times). | 

Codex: Orks 2021 p63

AND

Stratagem: Extra Gubbinz

Use this Stratagem before the battle, when you are mustering your army, if your WARLORD has the Orks keyword. Select one ORKS CHARACTER model in your army and give them one Shiny Gubbinz (this must be a Relic they could have). Each Relic in your army must be unique, and you cannot use this Stratagem to give a model two Relics. You can only use this Stratagem once, unless you are playing a Strike Force battle (in which case, you can use this Stratagem twice) or an Onslaught battle (in which case, you can use this Stratagem three times). |

 Codex: Orks 2021 p63

**Comment by GinFizzz** [comment]
This also affects Mek Boss Buzzgob.
All CHARACTER units should be able to take Big Boss.
All CHARACTER units that can take a Relic should be able to take Extra Gubbinz.
