### ISSUE TITLE
2x versions of heirlooms of the house / exalted court stratagems do not allow for selecting 2

### ISSUE THREAD

**Issue by kpasko** [BSData/wh40k-9e#10722]
**Describe the bug**
With imperial knights in a super-heavy auxiliary detachment, selecting the -3CP option for exalted court or heirlooms of the household does not show or slow for multiple selections

**To Reproduce**
1. Create super-heavy auxiliary detachment and add a knight 
2. Add either heirlooms of the household or exalted court
3. Click on that item and choose the 2x / -3CP option
4. Click on the knight and ensure the appropriate exalted court / heirloom of the house character option is selected
5. Click on warlord trait or heirlooms and try to select 2

**Expected behavior**
Either:
- 2x heirlooms or warlord traits should be selectable 
Or
- Choosing that stratagem should create an error if adding 2x of either is not allowed

**Device and data (please complete the following information):**
 - OS: iOS
 - BattleScribe version 2.03.15
 - Release version 

Imperium - Imperial Knights v83

**Comment by DrTobogganMD** [comment]
Why would you be able to put two relics or traits on a single model?

**Comment by kpasko** [comment]
If thats the case, the 2x stratagems should be removed

**Comment by DrTobogganMD** [comment]
Why would that option be removed?  Please consult both your codex and core rule book. No model can take more than one relic or warlord trait. The stratagem to take two extra allows multiple models to take a single relic or warlord trait.

**Comment by kpasko** [comment]
Apologies I was under the impression this was similar to Sentinel of terra,
exemplar of the chapter, chaos requisition, etc. rereading the stratagem
confirms you are correct. It still seems a bit strange to be allowed to
select the option for two with only one knight in the troop, but more a
nicety and certainly not a bug. Thank you for your time.
