### ISSUE TITLE
battlescribe says warlord creed must have a trait (but you can forgo one to get +1 tank ace)

### ISSUE THREAD

**Issue by Dusldorf** [BSData/wh40k-9e#10723]
**Describe the bug**
make creed warlord, but pick no trait (for extra tank ace), and battlescribe returns an error saying he must have a trait

**To Reproduce**
1. make creed warlord
2. dont select his trait

**Expected behavior**
not selecting a trait for creed should not return an error

**Device and data (please complete the following information):**
 - OS: windows 10
 - BattleScribe version [e.g. 2.03.21]
 - Release version [e.g. warhammer 40000 v9.2.18]

**Comment by acebaur** [comment]
Named characters MUST have their WLT. It can't be substituted

**Comment by SoSaltySalt** [comment]
I don't think the new Codexes say named characters MUST have their WLT's, BUT, the Guard Codex is from 8th, and does say MUST.
