### ISSUE TITLE
Orks: Warzone Octarius Book 2 Blood Axes Warlord Traits Should Not Require Warlord

### ISSUE THREAD

**Issue by GinFizzz** [BSData/wh40k-9e#10725]
**Describe the bug**
The 3 new Warzone Octarius Book 2 Blood Axe Warlord Traits are worded identically to the normal codex Warlord Traits and should not require the unit/model that has it to be your warlord.

Additionally, the way the Warlord Traits are currently implemented means they show as if they can have more than one selection, meaning instead of radio buttons, they are incremental counters.

**To Reproduce**
1. Create a force.
2. Set the Clan Kulture as Blood Axes.
3. Add a non-named HQ.
4. Make the HQ your warlord.
5. New Blood Axe Traits should appear.
6. Uncheck Warlord, add Big Boss.
7. New Blood Axe Traits will disappear.

**Expected behavior**
Blood Axes Warlord Traits should be available as long as your detachment is Blood Axes.
Warlord Traits should show as Radio buttons not incrementing counters.

**Screenshots**
Blood Axes Warboss on Warbike w/ Big Boss, Blood Axe Traits are missing.
![image](https://user-images.githubusercontent.com/47032978/144759860-1cc719da-f89c-4a7c-8252-c40e2e7f1ef6.png)

Blood Axes Warboss on Warbike w/ Warlord, Blood Axe Traits are available.
![image](https://user-images.githubusercontent.com/47032978/144759886-0e091faf-ba4e-46e8-b53e-b29305ae07f3.png)

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version v2.03.21.166
 - Release version v9.2.18

**Comment by GinFizzz** [comment]
Each of the Blood Axes traits should be adjusted to have Set Hidden to True if 0 Selections of Force in Blood Axes as per I've got a Plan Ladz. Additonally, set it to limit to 1 selection in roster to change selection to radio buttons.

![image](https://user-images.githubusercontent.com/47032978/144760447-bc511791-cb9c-45a0-8345-3ee8a6e185d2.png)

**Comment by Technoblazed** [comment]
Fixed in ab971cf57423bad0db7d202f1e2d64eac324dd80
