### ISSUE TITLE
 40k / Space Marines / Company Veterans missing Combat Sheilds

### ISSUE THREAD

**Issue by Warmastermorgan** [BSData/wh40k-9e#10739]
**Describe the bug**
In simple terms running the most up to date BS data file set for: BS  / 40k / Space Marines / Elites / Company Veterans:
1-Missing Combat Sheilds (@3pts, they have Storm Sheilds @ 4pts but not Combat Shields)
2-Missing Command Squad Rule I.e. if Captain present -1 Battlefield Role slot.
-
![Screenshot_20211212-225415](https://user-images.githubusercontent.com/96015776/145733810-2d00bf65-c5f9-4ca0-abc5-a44474126f1a.jpg)
![Screenshot_20211212-225354](https://user-images.githubusercontent.com/96015776/145733811-07a2b4c8-bf4a-45e6-b36e-e03c9a3006f0.jpg)
![20211212_225056](https://user-images.githubusercontent.com/96015776/145733812-f0b5a06f-a741-453e-b28d-1b011f9fc2eb.jpg)
![20211212_225029](https://user-images.githubusercontent.com/96015776/145733814-ae6d321c-a97d-42e6-ae1d-e19dc9ecede7.jpg)
![20211212_225006](https://user-images.githubusercontent.com/96015776/145733819-8a1659e1-8bb6-45db-b4fb-99988f16022c.jpg)
See attached supporting images of 9th edition space marine codex rules

**Comment by AbonShell** [comment]
Once you add a captain, you may them add a company veteran squad in the No Force Organization

In order for this unit to get the combat shield they must be from a dark Angels chapter or successor chapter.

**Comment by Warmastermorgan** [comment]
Thanks Abon,
Apologies for that.
Best, Morgan
________________________________
