### ISSUE TITLE
Imperium - Adeptus Astartes - Dark Angels: Heavenfall blade should not be available with Marked for Command

### ISSUE THREAD

**Issue by Citronnade** [BSData/wh40k-9e#10747]
**Describe the bug**
Heavenfall Blade is showing under "Special Issue - Dark Angels" for sergeants with a power sword when the Marked for Command Stratagem is added.  Heavenfall Blade is not one of the relics listed as available in Marked for Command.

**To Reproduce**
1. Create a new roster with DA, add any Warlord (reproed with Sammael), add  the Marked for Command stratagem, add a unit with a Sergeant with a power sword (reproed with intercessor squad).

**Expected behavior**
Heavenfall Blade should not be an option.

**Screenshots**
![image](https://user-images.githubusercontent.com/2671007/146446328-d97425d7-98a3-4414-b079-8be92d42deda.png)

**Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version: 2.03.21
 - Release version: v9.2.19

**Comment by Citronnade** [comment]
The only validation error provided is that I hadn't entered a Battle Size while reproing.

**Comment by FarseerVeraenthis** [comment]
I best fire up the cogitator and have a look then :-)
