### ISSUE TITLE
Terminus Est Error

### ISSUE THREAD

**Issue by raziel1013** [BSData/wh40k-9e#10742]
File: Chaos - Death Guard.catz

BattleScribe v2.03.21.166

Platform: PC & Android

Dropbox No

Description: When adding a second detachment for the Terminus Est force, the Harbinger of Death Warlord Trait on Typhus is flagged as a validation error. I made sure that both detachments have the Harbinger as Plague Company and a Terminus Est force.

**Comment by Mad-Spy** [comment]
You don't actually _need_ to add more than one instance of the "Terminus Est Assault Force" entry into your army. However, I've fixed it so the validation works right even if you have more than one.

**Comment by raziel1013** [comment]
Thank you! That was incredibly fast.
