### ISSUE TITLE
Master-crafted Condemnor Boltgun

### ISSUE THREAD

**Issue by h-2** [BSData/wh40k-9e#10750]
**Describe the bug**
BSData and Wahapedia have very different stats for Inquisitor Greyfax' gun. Since the datasheet for Wahapedia 8th edition is the same as BSData, I assume that BSData is outdated?

**To Reproduce**
1. Add Greyfax to detachment, look at data sheet
2. Go to https://wahapedia.ru/wh40k9ed/factions/inquisition/Inquisitor-Greyfax and compare

**Expected behavior**
You tell me

**Screenshots**

BSData and Wahapedia 8th edition:
![grafik](https://user-images.githubusercontent.com/2996863/146682681-801187d9-1e59-4547-91b3-047c4269f3b3.png)

Wahapedia 9th edition:
![grafik](https://user-images.githubusercontent.com/2996863/146682826-cb0f2618-c5df-47c7-a666-f96e6085c040.png)

**Device and data (please complete the following information):**
 - OS: Linux
 - BattleScribe version: 2.03.21
 - Release version: Warhammer 40k 9.2.17

**Comment by Mad-Spy** [comment]
The most recent datasheet for Greyfax is from PA:Pariah and that lists the damage of his weapon as 1.

Wahapedia is not an official rules source and should not be treated as such.

**Comment by h-2** [comment]
I thought that Warzone actarius updated the Inquisition rules?

https://spikeybits.com/2021/10/40k-inquisition-contents-revealed-for-war-zone-octarius.html

I am not implying that it has to be changed, just curious where the difference comes from.

Thanks for working on BSData!
