### ISSUE TITLE
Nobz on Bikes info way off from codex

### ISSUE THREAD

**Issue by MagnusD20XX** [BSData/wh40k-9e#10766]
**Describe the bug**
model price listed at 30 points- codex lists models at 38 point each before wargear.

also selecting nobz on bikes from the army list doesn't allow you to add wargear, while the codex rules include various choices such as big choppa, slugga, stikkbombs and more. Power levels also seem to be out of date.

**To Reproduce**
I mean, if you look at the codex and then look at the options inside battlescribe you'll see what i mean.

**Expected behavior**
i expected to option to show the correct points cost, power level, wargear options etc. am working on a tasty list, hehe

**Screenshots**
No need i think unless you don't have a codex? xD

**Device and data (please complete the following information):**
eh, no need

**Additional context**
problem seems to be shared with wahapedia but they have the correct wargear options. the rest of the info is also off from the codex.

ps: sorry if i just missed something and i'm the one who's wrong. it just seems to be a very commonly overlooked thing, apparently, and i'd love to see it fixed so i can get my army idea up on tts and whoop those mouthy savages from the competitive channel back to their little "big brain" meta copying boards, i mean drawing boards, ofc xD

**Comment by Technoblazed** [comment]
Nobz on bikes aren’t even in the codex anymore, they’re imperial armour compendium only.

**Comment by MagnusD20XX** [comment]
does that mean it's in legends only now? you don't support the crossover
from forgeworld models into 40k? that might be a mistake considering you're
running essentially the biggest tts thing for 40k right now and using
forgeworld models is a big part of how people play

**Comment by Technoblazed** [comment]
The options in battlescribe are the accurate legal options for the game.

**Comment by alphalas** [comment]
@MagnusD20XX you misunderstood what techno said. it's not that we're not supporting. we are supporting the models exactly as their rules exist in Legends and IA Compendium. Either way, they lost the vast majority of all their options in 8/9e.

**Comment by MagnusD20XX** [comment]
nobz on bikez aren't in legends, tho. and if the last known version of nobz
on bikez is from armour compendium they have wargear options. what legality
filter are you applying? like warhammer store grand tournament rules? i
don't get why "matched play" should take out options they clearly have.

**Comment by Technoblazed** [comment]
No one said they are legends. The available options from IA:C are available in battlescribe. Where is this datasheet you're viewing that has other options?

**Comment by alphalas** [comment]
<img width="805" alt="Screen Shot 2021-12-26 at 15 17 07" src="https://user-images.githubusercontent.com/15703066/147419124-88003806-19b6-4c02-887f-f7997d6a5b77.png">
this is the data sheet from IA:C

**Comment by MagnusD20XX** [comment]
IAC and then the errata from indomitus 1.2 has them losing double saw and
two kombi options but keeping the rest, which include single saw, stabba,
klaw

**Comment by Technoblazed** [comment]
Those options were for points at the back of the book that weren't valid options for the unit, which is why they were removed.

**Comment by alphalas** [comment]
^what techno said - those weapons are not on the data sheet as availible weapons so were removed by the latest FAQ to IA:C
![Screen Shot 2021-12-26 at 15 20 55](https://user-images.githubusercontent.com/15703066/147419198-42713054-953e-436f-86dc-8129c65dda1c.png)

**Comment by MagnusD20XX** [comment]
Look at what Jon posted. They clearly have more options than what's shown
in battlescribe. The errata is just to take a couple options out of what
Nobz normally have to specify for Biker nobz

**Comment by MagnusD20XX** [comment]
Battlescribe was showing zero war gear options for Nobz on Warbikes when I
sent this bug report originally. It's clear they have a few that I
mentioned in the report

**Comment by Technoblazed** [comment]
![Image](https://i.tech-no.me/2021/12/26/211226202344.png)

This is the available options.

**Comment by alphalas** [comment]
![Screen Shot 2021-12-26 at 15 24 59](https://user-images.githubusercontent.com/15703066/147419253-48d85a0e-345b-4f83-9609-9d2fea08930b.png)
confirmed

**Comment by alphalas** [comment]
so if you're not seeing these options, you need to update your data, making sure the check the delete all data before download checkbox.
![Screen Shot 2021-12-26 at 15 28 06](https://user-images.githubusercontent.com/15703066/147419307-55f35b9b-d640-4e31-8d6d-e3339541df8b.png)

**Comment by MagnusD20XX** [comment]
why'd you act like i was wrong, fix it then act like i was wrong for not
having the update you just did cuz of me? that's real unnecessary. but
thanks nonetheless, i guess...

**Comment by Technoblazed** [comment]
Whatever floats your boat bud.

![Image](https://i.tech-no.me/2021/12/26/211226203108.png)

**Comment by alphalas** [comment]
@MagnusD20XX the data hasn't been changed for 2 weeks like @Technoblazed just showed you. we haven't changed anything since you posted the bug report.
