### ISSUE TITLE
SM no "hero of the chapter" stratagem if HQ is in a different detachment from warlord

### ISSUE THREAD

**Issue by rfancher** [BSData/wh40k-9e#10769]
**Describe the bug**
SM no "hero of the chapter" stratagem if HQ is in a different detachment from warlord
Issue was reported in #7522 but with the wrong repro steps and it still occurs in v9.2.21 of 40K data

**To Reproduce**
1. Create a Space Marine army list
2. Add two detachments
3. Add an HQ as warlord to first detachment
4. Add HQ to second detachment
5. Attempt to assign “Hero of the Chapter” to HQ in second detachment

**Expected behavior**
I don’t see anything in the stratagem rules to disallow use in other detachments

“ Adeptus Astartes – Requisition Stratagem
Every Space Marine is a champion in their own right, a posthuman demigod who stands between Mankind and the darkness.
Use this Stratagem before the battle, when you are mustering your army, if your WARLORD has the ADEPTUS ASTARTES keyword. Select one ADEPTUS ASTARTES CHARACTER model from your army (excluding named characters) and determine one Warlord Trait for it (this must be a Warlord Trait it can have); that model it is only regarded as your WARLORD for the purposes of that Warlord Trait. Each Warlord Trait in your army must be unique (if randomly generated, re-roll duplicate results), and you cannot use this Stratagem to give a model two Warlord Traits. You can only use this Stratagem once, unless you are playing a Strike Force battle (in which case, you can use this Stratagem twice) or an Onslaught battle (in which case, you can use this Stratagem three times).”

**Device and data (please complete the following information):**
 - OS: iOS
 - BattleScribe version v2.03.15
 - Release version wh40k v9.2.21

**Additional context**
Specifically using ultramarines in my repro

**Comment by AbonShell** [comment]
Fixed in next release
