### ISSUE TITLE
Thousand Sons: cult of change relic missing

### ISSUE THREAD

**Issue by PsyQrow** [BSData/wh40k-9e#10788]
The cult of change sorcerous arcana "Capricious Crest" is missing. I am using the latest release for the thousand sons directory, have tried to find it on different characters and have tried remaking the list, but the capricious crest doesn't seem to be available on any characters.

**Comment by Mad-Spy** [comment]
It is definitely there. You **must** have a Cult of Change Warlord (or Magnus) in your army to use it, as with any of the Cult Relics. Using the relic stratagem with a different Cult Warlord is not sufficient.
