### ISSUE TITLE
Rogue Traders Missing 

### ISSUE THREAD

**Issue by toomanyprojects** [BSData/wh40k-9e#10785]
**Describe the bug**

**To Reproduce**
1. Go to 'Agents of the Imperium / Force list’
2. No Rogue Traders or Voidsman-at-arms available 

**Expected behavior**
All rogue traders and voidmsman at arms are missing from both their own army force and from the ‘agent of the imperium’ 

**Device and data (please complete the following information):**
 - OS: iOS
 - BattleScribe version 2.03.15
 - Release version 9.2.22

**Comment by AbonShell** [comment]
Added in next release
