### ISSUE TITLE
Lord Castellan Creed Warlord Trait

### ISSUE THREAD

**Issue by maverick2400** [BSData/wh40k-9e#10797]
**Describe the bug**
When you take Castellan Creed as your Warlord it requires you to take his Warlord Trait and gives you an error message when you don't. with the Psychic Awakening book, you can actually forego taking his Warlord Trait for a Tank Ace ability.

**To Reproduce**
1. Go to Lord Castellan Creed under HQ
2. Click on Warlord 2CP
3. Don't click the radial under Required Warlord Traits

**Expected behavior**
There should not be an error if you take Lord Castellan Creed as your Warlord but also take a Tank Ace.

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version 2.03.21
 - Release version v202

**Comment by acebaur** [comment]
Named characters *must* take their WLT they cannot trade it

**Comment by SoSaltySalt** [comment]
Not sure if the *must** part is true for all Codexes, but for Guard it is at least.
