### ISSUE TITLE
Adeptus mechanicus

### ISSUE THREAD

**Issue by BaronBlack** [BSData/wh40k-9e#108]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

Eradications ray for Tech priest dominus eradication ray abilities . At 8" becomes -4 ap not -1.

**Comment by Thairne** [comment]
was fixed with the latest release.
