### ISSUE TITLE
Adeptus custodes - wrong cost of shield captain with sword-n-board

### ISSUE THREAD

**Issue by TheKoD** [BSData/wh40k-9e#10824]
**Describe the bug**
In Codex: Adeptus Custodes, cost of praesidium shield for shield-captain is 10pts, not 20pts
**To Reproduce**
1. Go to adeptus custodes roster
2. Add shield-captain into it
3. Check out cost of 'sentinel blade and praesidium shield' wargear option, which is currently 20pts, but should be 10pts according to codex.

**Comment by Technoblazed** [comment]
Already fixed in next release.
