### ISSUE TITLE
Daemonic Disciples Characters have the wrong Locus

### ISSUE THREAD

**Issue by Luminoth** [BSData/wh40k-9e#10823]
**Describe the bug**

When adding a Daemonic Disciples Character to a Disciples of Be'lakore army they're currently showing their Daemonic Allegiance Locus instead of the Locus of Shadows. For example a Changecaster shows Locus of Tzeentch instead of Locus of Shadows. Similarly it looks as tho Legion Disciples are not showing the Disciples of Shadows ability.

**To Reproduce**

1. Create a new Chaos Daemons detachment and give it the Disciples of Be'lakor Army of Renown Configuration
2. Add a Changecaster to the detachment
3. Observe that the Changecaster has the wrong Locus
4. Additionally, a CSM detachment can be added to the army with the Disciples of Be'lakor Army of Renown Configuration and No Legion selected for the Legion Configuration
5. Add any valid CSM unit to the CSM detachment
6. Observe that the unit does not have the Disciples of Shadows ability

**Expected behavior**

I would expect Daemonic Disciples Characters to have the correct Locus and Legion Disciples to have the Disciples of Shadows ability.

**Device and data (please complete the following information):**
 - OS: all
 - BattleScribe version 2.0.3.21
 - Release version 9.2.24

**Comment by Mad-Spy** [comment]
Both rules are displayed at the top of the Roster in the same way that all army-wide rules of a similar type are displayed.

![image](https://user-images.githubusercontent.com/29306451/150155609-e0e27bcb-4e65-4cac-9689-231323e5d7bd.png)

![image](https://user-images.githubusercontent.com/29306451/150155643-5854904f-742f-4746-9a08-9cd491bc47c1.png)

**Comment by Mad-Spy** [comment]
You're right about it not hiding the other Loci though, so I've fixed that.
