### ISSUE TITLE
Disciples of Be'lakor doesn't validate the daemonic allegiance or cultist unit limit restrictions

### ISSUE THREAD

**Issue by Luminoth** [BSData/wh40k-9e#10825]
**Describe the bug**

I suspect this may be due to limitations with Battlescribe itself (or just the complexity of describing the rules), but I couldn't find anything saying for certain one way or the other so I figured I'd open an Issue just in case. The daemonic allegiance and chaos cultist unit limit restrictions aren't currently enforced.

**To Reproduce**

1. Create a new army with a Chaos Daemons detachment and a Chaos Space Marines detachment.
2. Add Be'lakor as the army warlord and Disciples of Be'lakor Army of Renown Configuration
3. Add 3 units of Daemonettes and 3 units of Chaos Cultists
4. Observe that no error is reported for exceeding either the daemonic allegiance or chaos cultists unit limit restrictions

**Expected behavior**

I would expect to see a validation error for both of the noted restrictions.

**Device and data (please complete the following information):**

 - OS: All
 - BattleScribe version 2.03.21
 - Release version 9.2.24

**Comment by Mad-Spy** [comment]
It's not possible to validate this so that's why it's not implemented.
