### ISSUE TITLE
Death guard demon prince, Lord of death Guard Aura 

### ISSUE THREAD

**Issue by peaco86** [BSData/wh40k-9e#10835]
**Describe the bug**
Death guard was updated in FAQ , 02/06/2021. demon prince, 'Lord of death guard' keyword is removed 

**To Reproduce**
n/a

**Expected behavior**
keyword and aura should no longer be used

**Comment by elodingens** [comment]
FAQ statet to remove the keyword which is already done. Aura should be unaffected by FAQ.

**Comment by Mad-Spy** [comment]
As per @elodingens message, the FAQ only removed the keyword, not the ability.
