### ISSUE TITLE
Ultramarines Honor Guard

### ISSUE THREAD

**Issue by SonOfGuilliman** [BSData/wh40k-9e#10842]
**Describe the bug**
The Honour Guard unit for Space Marines with Chapter Selector: Ultramarines shows Honour Guard as {Legends] with Weapon Options - probably a leftover from CA2017 or whenever they introduced a generic Honour Guard.  For Ultramarines there's still a unit in their Chapter Supplement(Pg 69), models on the webpage, references in the FAQ's -
UM FAQ:
Page 69 – Honour Guard, Abilities, Honour Guard
Change to read: 
‘While a friendly Ultramarines Character unit that has a 
Wounds characteristic of 9 or less is within 3" of this unit, enemy 
models cannot target that Character unit with ranged attacks.’
*Page 69 – Honour Guard, Keywords
Add the ‘Core’ keyword
Power Rating Update to 2. 

**To Reproduce**
1. Go to Ultramarine army creation
2. Go to Elites.
3. See Weapons options, the Legends tag (affects the Unit Filter option)

**Expected behavior**
Expected Results - a UM only unit without the Legends Tag or weapon option choices- probably separate and in addition to the Legends unit.

**Comment by acebaur** [comment]
Add the unit to the roster and it will remove the legends tag

**Comment by SonOfGuilliman** [comment]
I see that but there are still two things – it’s hidden if I hide Legends – and it still has weapon choices which the Ultramarines Specific Honor Guard do not.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
