### ISSUE TITLE
Imperium - Adeptus Custodes: Blade Champion PL incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10843]
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.21

**Platform:** Mac

**Dropbox:** Yes

**Description:** Blade Champion power level is incorrect (is 7, should be 6).

**Comment by Technoblazed** [comment]
Fixed in https://github.com/BSData/wh40k/commit/a24251d27903a4ca07fe6484623725e6d5ef487e
