### ISSUE TITLE
Chapter Command: Chief Apothecary cost

### ISSUE THREAD

**Issue by SonOfGuilliman** [BSData/wh40k-9e#10848]
Chapter Command: Chief Apothecary rings up at 35 points when the Codex:SM faq says: 

Page 202 – Points Values, Chapter Command.
Change these points values to read: 
‘Chapter Ancient……+20pts 
Champion……+15pts 
Chapter Master……+40ts 
Chief Apothecary……+15pts 
Chief Librarian……+25pts 
Master of Sanctity……+25pts 
Master of the Forge……+20pts’
Designer’s Note: These values match the ones found in the 
Chapter Command rules on page 98.

**Comment by acebaur** [comment]
Codex FAQ points are out of date, please refer to the most recent MFM for the current points.
