### ISSUE TITLE
Deathwing Ancient incorrect points on LC

### ISSUE THREAD

**Issue by FCowper** [BSData/wh40k-9e#10840]
**Describe the bug**
Lightning claws cost 5pts on a dark angels terminator ancient in battlescribe, but they cost nothing in MFM + codex

**To Reproduce**

1. Create a Dark Angels detachment
2. Add ancient in terminator armour/deathwing ancient
3. Add lightning claws as weapon upgrade

**Expected behavior**
Same as above but the claws cost nothing

**Device and data (please complete the following information):**
 - android and windows
 - BattleScribe version 2.03.25.338
 - Release version not sure

**Comment by FarseerVeraenthis** [comment]
This is fixed on master as of last night, so it will be in the next release :+1:

**Comment by FCowper** [comment]
Brilliant, cheers
