### ISSUE TITLE
Imperium - Adeptus Custodes: Witchseeker Squad PL incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10845]
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** The Power level for the Witchseeker Squad is incorrect (is 4, should be 3).

**Comment by Technoblazed** [comment]
Fixed in https://github.com/BSData/wh40k/commit/a24251d27903a4ca07fe6484623725e6d5ef487e
