### ISSUE TITLE
Imperium - Adeptus Custodes: Vigilator Squad PL cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10844]
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.21

**Platform:** Mac

**Dropbox:** Yes

**Description:** the vigilator squad should be power rating 3, not 4.

**Comment by Technoblazed** [comment]
Fixed in https://github.com/BSData/wh40k/commit/a24251d27903a4ca07fe6484623725e6d5ef487e
