### ISSUE TITLE
Dark Angels Black Knights cost not updated in unreleased data

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#10866]
On the master data, the ravenwing black knights are still 40 points a model but they should be 35 points just like the huntmaster 
![image](https://user-images.githubusercontent.com/72748875/151248569-986b8eb8-dcad-4057-8795-aa6c1f01462b.png)

**Comment by AbonShell** [comment]
Ravenwing black knights are 40 pts as of the current MFM.

**Comment by RespectableJack** [comment]
@AbonShell 
What about this?
![q8Yr0d7OAP6kuOgb](https://user-images.githubusercontent.com/72748875/151261818-add93b92-94a5-4223-935d-04cf1bedce92.jpg)

**Comment by Mad-Spy** [comment]
~~The new Munitorum Field Manual isn't released yet so the points haven't been updated in the released data.~~
 
I see you're using the unreleased data, so this does need fixing.

**Comment by RespectableJack** [comment]
Thats why I said the master, sorry if I was not clear enough

**Comment by AbonShell** [comment]
Putting data revision number in the post would normally clear up that confusion more directly.

**Comment by RespectableJack** [comment]
Okay wasn't too sure if the number would be needed since its unreleased but I'll remember that for the future.

**Comment by FarseerVeraenthis** [comment]
It's ok, that's my fault for being lazy :-)
