### ISSUE TITLE
Tyranids - Ravener Wargear missing costs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10878]
**File:** Tyranids.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Ravener wargear displays as no points cost. Rending claws and spinefists should be 2pts, devourer should be 4pts and deathspitter should be 6pts

**Comment by GenWilhelm** [comment]
Could you please provide a source for those numbers? My copy of the Munitorum Field Manual 2022 does not list any wargear costs for raveners.
