### ISSUE TITLE
Kill Rig - Warlord/Big Boss

### ISSUE THREAD

**Issue by trex3000** [BSData/wh40k-9e#10872]
**Describe the bug**
After selecting Warlord or Big Boss (with Warlord selected on another character) for the Kill Rig the Warlord trait defaults to 2. BeastGob (Aura) (Beast Snagga) and no selection options show on the right selection area. Tried re-making roster, restarting app, and adding/removing selections. 

**To Reproduce**
1. Create an Ork Battalion Detachment list with 1000pts
2. Set Battle Size to 2. Incursion
3. Add a Kill Rig to the roster.
4. Select the Kill Rig and check off the Warlord option.
5. Bug = No new sections will appear to select Warlord Traits.
6. Bug = Under Kill Rigs description, Warlord will be shown with 2. BeastGob Warlord Trait selected. 

**Expected behavior**
When selecting Warlord there should be a list of Warlord traits that appear under options (works for other HQs). This should allow you to select from several traits, including BeastGob.

**Screenshots**
![Options Only](https://user-images.githubusercontent.com/898931/151680710-f93616a8-f240-4d45-b797-0f3313aa6331.PNG)
![Unit Info Only](https://user-images.githubusercontent.com/898931/151680711-0b65c756-ca5b-469e-9036-0e784d1e3636.PNG)
![Big Picture](https://user-images.githubusercontent.com/898931/151680712-ad8a860e-d4de-460a-a967-f8063037ca62.PNG)

**Device and data (please complete the following information):**
 - BattleScribe version [e.g. 2.03.45]
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by Technoblazed** [comment]
Per the codex you should have read, the kill rig is forced to this warlord trait which is why you do not get to pick. ;)
