### ISSUE TITLE
Tyranids - Genestealer Cults: Neophyte Leader Shotgun

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10879]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Typo in the new gsc data
"Cult Cawls and Knife"

Neophyte Hybrid Leader can't seem to equip a shotgun

**Comment by GenWilhelm** [comment]
~~Where are you seeing the typo? When I search "cawl" in the file, I get 0 results.~~
Nvm, I found it.
