### ISSUE TITLE
Necrons Voltaic Staff does not replace Staff of light

### ISSUE THREAD

**Issue by Streyder** [BSData/wh40k-9e#10870]
**Describe the bug**
When a character uses the Voltaic Staff relic, the relic does not replace the Staff of light.

**To Reproduce**
1. Add a Technomancer to your list
2. Give it the Artefacts of the Aeons "Relic: Voltaic Staff"
3. Technomancer now has both weapon profiles instead of only the Voltaic Staff

**Expected behavior**
Technomancer should only have the Voltaic Staff

**Screenshots**
![image](https://user-images.githubusercontent.com/18559266/151530338-32086621-a38b-456d-9a1d-89a25d385f4e.png)

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version: v2.03.21.166
 - Release version: v 9.2.25

**Comment by Mad-Spy** [comment]
This is expected behaviour and as such will not be fixed. Replacing weapon profiles is (annoyingly) incredibly complex in the Battlescribe data structure, so we don't generally do it.
