### ISSUE TITLE
GSC no cult relics

### ISSUE THREAD

**Issue by EddieStant** [BSData/wh40k-9e#10887]
**Describe the bug**
Cult specific relics are not showing up as selectable options after selecting a given cult.
**To Reproduce**
1. Select a cult
2. create a character unit eg patriarch
3. Look at relic options
4. the cult one will be missing

**Expected behavior**
Cult relics should be selectable

**Device and data (please complete the following information):**
 - OS: Windows PC
 - BattleScribe version [2.03.21]
 - Release version [e.g. v9.2.26]

**Comment by Mad-Spy** [comment]
At least some of them appear to be working correctly. Please update this issue with the _specific_ issue you are experiencing.

**Comment by GenWilhelm** [comment]
The Nomad's Mantle was showing for Hivecult instead of Rusted Claw. If that wasn't the one you were looking for, please reopen this issue.
