### ISSUE TITLE
Imperium - Grey Knights: GK points not updating in app

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10884]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** While the tagged version on Github contains the new points for the Nemesis Dreadknight, the newly available data version in the app still shows the old points.

**Comment by Mad-Spy** [comment]
Looks like the data got released without a version bump.

**Comment by tekton** [comment]
I swear I did :(

**Comment by tekton** [comment]
bumped and pushed
