### ISSUE TITLE
Chaos - Death Guard: Plaguespurt gauntlet for Deathshroud Champion should be free

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10883]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 9.02.26

**Platform:** Android

**Dropbox:** No

**Description:** For deathshroud terminator champion, there should no longer an option to add plaguespurt gauntlets for 2.5 pts each. So should just be 55 pts flat for double gauntlets on champion.

**Comment by Mad-Spy** [comment]
You are slightly incorrect. The datasheet hasn't changed, so the Champion still has the option of whether to take 2 gauntlets or not; they just don't cost anything any more.
