### ISSUE TITLE
GSC - Issues List (reposted from GSC discord)

### ISSUE THREAD

**Issue by Eepid** [BSData/wh40k-9e#10895]
Heya - These are a summary of reported issues with GSC codex from the GSC discord. I've removed a couple that look to have been closed already. I didnt find these, but I wanted to post here to make sure they are reported - Not claiming any credit!

HQ:
Magus Ld 9 (Codex) not 8 (Battlescribe)

Troops:
Acolyte Hybrids Cult Claws and Knifes ap-2 (Codex) not -1 (Battlescribe) Also weapon Choise has a typo
Acolytes cult icon is a model without autopistol not just a bonus (does not complain in Battlescribe with handflamer, so you pay for them but should not have the one that would be on the icon carrier)

Neophytes Icon is just an upgrade and not as an own model, this should be taken into account for creating TTS armies.
Neophytes new shotgun is S4 and no ability (Codex) instead of S3 with ability (Battlescribe). Also called Cult Shotgun (Codex) not only Shotgun (Battlescribe)
Neophytes Webber is 18" (Codex) instead of 16" (Battlescribe)

Elites:
Hybrid Metamorphs have correct icon interaction (weird that Neophytes and Acolytes have it wrong)

Aberants Heavy Power Weapon is S+3 Ap-2 D3 (Codex) not Sx2 Ap-2 D3 (Battlescribe)

Biophagus cant be taken as no force org.
Biophagus Genomic Enhancment Table reads 3 times the same and is in the wrong order 2 and 3 need to be swapped
Aberants cant be targeted by biophagus alchemist supreme ability like others

Fast Attack:
Atalan Jackals miscounts when the second grenade launcher is allowed (4 jackals but it only allows one at 5 other jackals (including the grenade launcher jackal)
counts correct for the first wolf quad
Does not count the grenade Launcher Jackals towards the Jackal Limit at which the second Wolfquad is allowed
BUT will show an error if there are to many Jackals (including the Grenade Launcher models this time)
Atalan Leader has 3A not 2 (Battlescribe)

Psychic Powers:
Mind Control: 18" (Codex) not 12" (Battlescribe) the description even calls out the correct 18"

Proficient Planning:
Our Time is Nigh 10 points (Codex) not 15 (Battlescribe)

Meditations in the Shadow does not work as it still triggers an error if more than two Broodmind Disciplines are selected.

Relics:
once chosen, it can happen that the rusted claw relic can always be selected even if the cult creed is changed, without triggering an error, it can even occure that it isn't shown when it is changed to rusted claw again once it is gone.

**Comment by GenWilhelm** [comment]
Hey, thanks for putting this together, this is super helpful!
Are these all from v70? (I've already fixed some things in v71)

**Comment by Eepid** [comment]
Yeah v70 - There were a few more things that were on the closed list so I removed them. A couple more I just saw on the discord that arent marked as closed:

There is still 8th edition Stuff in it like the specialist detachments and the Stratagems for the Magus (The Cult's Psyche) and the Primus (The Heart of the Creed). Those should all be gone. 

Goliath Truck has a movement value of 4" in the lowest bracket (Codex) instead of 6" (Battlescribe)

All units seem to miss their own Unit Keyword which would be mentioned in Stratagems for example

**Comment by GenWilhelm** [comment]
Specialist detachments are still legal outside of GT play, as far as I know.
And I leave out keywords that exactly match the unit name (unless it's used by multiple units) just to reduce clutter - are there many people that want these in?

**Comment by Eepid** [comment]
Honestly, Im not sure - Just some people pointed it out - I guess its just to avoid rules lawyering dramas at some point.

One more I saw - The "Bladed Cog" specific Stratagem "Xenoform Bionics" which enhances a unit before the battle in the muster army step is missing as an option for the allowed units.

**Comment by GenWilhelm** [comment]
That's all fixed for v71 (sans keywords - I might put this in tomorrow if I'm feeling spicy). Thanks again for putting this together, and of course please do relay any more you come across (I might even jump in the discord to lurk).

Also it's probably worth mentioning there won't be a Thursday release this week because of the Tau codex, so these won't be live until Saturday.

**Comment by Eepid** [comment]
Awesome! Thank you so much

**Comment by mcam435** [comment]
Couple of things, I can't see how you select creeds for myriad cults? It's either missing or I'm being dumb.

Jackals should have demolition charges applied to models rather than units.

There's also some hang overs from the old codex such as splinter cults.

**Comment by GenWilhelm** [comment]
The myriad creeds are listed under the myriad cult selection.

Putting the demo charges under the jackal models would have very messy ui/ux, same with the power weapons.

Splinter cults are new with the current codex.
