### ISSUE TITLE
Death guard Contemptor Dreadnoughts Twin Volkite Culverin should be 15pts each not 5

### ISSUE THREAD

**Issue by Alfry10** [BSData/wh40k-9e#10894]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - BattleScribe version [e.g. 2.03.45]
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by Mad-Spy** [comment]
Duplicate of #10886

**Comment by Mad-Spy** [comment]
Please take a few seconds to check closed issues before opening new ones.
