### ISSUE TITLE
Tyranids - Genestealer Cults: Achilles Ridgerunner points not updated

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10897]
**File:** Tyranids - Genestealer Cults.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Hello. Achilles ridgerunners should be 80 points instead of 70 points. Thanks

**Comment by GenWilhelm** [comment]
Duplicate of #10881
