### ISSUE TITLE
Genestealer Cults: Nomad's Mantle not available to Rusted Claw characters

### ISSUE THREAD

**Issue by AndrewGreerGH** [BSData/wh40k-9e#10909]
**Describe the bug**

The Nomad's Mantle relic is not available to Rusted Claw characters.

**Device and data:**
 - OS: Windows 10
 - BattleScribe version 2.03.21
 - Release version 9.2.26

**Comment by GenWilhelm** [comment]
Fixed by 09637d1bff20a8b667eefc879ab9686210376cbe.
