### ISSUE TITLE
Tyranids - Genestealer Cults Issues

### ISSUE THREAD

**Issue by Instain** [BSData/wh40k-9e#10907]
**Describe the bug**
A clear and concise description of what the bug is:

- [ ] Primus should not contain Option: Stratagem: The Heart of the Creed as it no longer exists
- [ ] Our Time is Nigh should be 10 points per MFM 2022
- [ ] Achilles Ridgerunners should be 80 points per model per MFM 2022 and Codex
- [ ] Biophagus lacking appropriate categories (keywords). Only contains ELITES. Unable to select No Force org slot when HQ is present.
- [ ] Magus should not contain Option: Stratgem: The Cult's Psyche as it no longer exists.
- [ ] When a roster contains two Patriarch (in different detachments), and Leaders of the Cult is selected, there is no option to give the second non-warlord patriarch a warlord trait. Works for Primus and Magus in similar configuration.
- [ ] Meditations in Shadows does not allow for 3 broodmind discipline powers to be selected for Magus or Patriarch

**Device and data (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - BattleScribe version [e.g. 2.03.45] BattleScribe v2.03.21.166
 - Release version [e.g. v1.2.3] v9.2.26

**Additional context**

**Comment by Mad-Spy** [comment]
90% sure that all of these were reporting and fixed in #10895 and/or other reported issues. Please check the list of closed issues before creating new ones.
