### ISSUE TITLE
Tyranids - Genestealer Cults: Neophyte Hybrid leader should have option for shotgun

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10906]
**File:** Tyranids - Genestealer Cults.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Neophyte Hybrids

Neophyte hybrid leader should have option for shotgun

**Comment by GenWilhelm** [comment]
Duplicate of #10879
