### ISSUE TITLE
Adeptus Custodes Forgeworld units missing the <SHIELD HOST> Faction keyword

### ISSUE THREAD

**Issue by SSSlippy** [BSData/wh40k-9e#10913]
All the forgeworld units seem to be missing the shield host keyword.  The units have the shield host keyword in the imperial armor compendium.

**Comment by Technoblazed** [comment]
Already fixed in https://github.com/BSData/wh40k/commit/f3bd7e5e5d227197756e6732ba23c1981c4dd522
