### ISSUE TITLE
AM PL Adjustment

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10922]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.25

**Platform:** Windows

**Dropbox:** No

**Description:** Power Rating Update Updated 04/02/2022
---HQ
Lord Commissar from 3pl to 2pl
Knight Commander Pask from 14pl to 13pl
---ELITES
Crusaders 2 starting at 2 is 1pl per model added to a max of 10 pl and a unit of 10
Ogryn Bodyguard from 6pl to 3
---HEAVY SUPPORT
Deathstrike from 8pl to 7pl
Manticore from 8pl to 9pl
---FLYERS
Vendetta Gunship from 12pl to 11pl
---LORDS OF WAR
Baneblade from 30pl to 26pl
Banehammer from  29pl to 24pl
Banesword from   29pl to 24pl
Doomhammer from 29pl to 25pl
Hellhammer from 33pl to 28pl
Shadowsword  from 32pl to 27pl
Stormlord from 32pl to 27pl
Stormsword from 30pl to 26pl

**Comment by williamcaw** [comment]
fw death Korps of Krieg change
- ELITES
Combat Engineer Squad 6-10: 4
Death Rider Command Squadron 3 to 4
---FAST ATTACK
Death Rider Squadron 5: 3 to 5 , 6-10: 6 to 10
