### ISSUE TITLE
[Bug Report] Sagittarum Custodians with Misericordia

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-9e#10931]
**Describe the bug**
Since last FAQ Games Workshop, Misericordia are free so all units have been fixed but sagittarum not. Can you fix it please ? 

**To Reproduce**
1. Go to 'Manage Data'
2. Click on 'Warhammer 40,000 v9.3.0'
3. Scroll down to 'Sagittarum Custodians'

**Screenshots**
![sagcus](https://user-images.githubusercontent.com/99088564/152650230-9082d90d-d67f-42cd-9e16-76c590fcaae2.png)

**Device and data (please complete the following information):**
 - OS: Windows and Android
 - BattleScribe version [e.g. 2.03.21]

**Comment by Technoblazed** [comment]
They're not free for sagittarum in the MFM.

**Comment by ghost** [comment]
Misericordia are free for all units and models for adeptus custodes !!! even sagittarum models because of this => https://www.warhammer-community.com/wp-content/uploads/2022/01/XVjCdyR02Mwa08KD.jpg
It's official by Games Workshop 
link ===> https://www.warhammer-community.com/2022/01/21/spread-the-glory-of-the-emperor-with-these-free-adeptus-custodes-points-updates/

**Comment by Technoblazed** [comment]
If you read the actual text book, the GW non-FW models have free misericordias, the sagittarum have a price listed, so do not.

**Comment by ghost** [comment]
So, why all other units FW in the database batttlescribe have misericordia free ? 
For example, Venatari have misericordia free in your database. And all other FW models ... so why sagittarum have not ? 
I want to understand ...

**Comment by Technoblazed** [comment]
Because none of the other FW units have a points cost listed for the misericordia, but the sagittarum does, so they have a cost on battlescribe. If you believe it's an issue in the points book, you can email the GW FAQ email.

**Comment by ghost** [comment]
In my mind, I think it is an error or a mistake by GW ... Why just sagittarum should pay misericordia and not all ther others !!! It's just not normal because GW FAQ says that all misericordia are free to all !!!

**Comment by ghost** [comment]
In the webpage it's clearly says => 
![image](https://user-images.githubusercontent.com/99088564/152662400-c9cdc1bc-b6b1-41a8-b868-20eac892a881.png)
So GW says it !!!

**Comment by Valorcalls** [comment]
What the Warcom team says has absolutely nothing to do with what the actual rules say, and is at best considered inaccurate immediately.

**Comment by ghost** [comment]
What ?

**Comment by Technoblazed** [comment]
Email the GW FAQ email if you think there's an issue, we follow the RAW, and RAW they are not free.

**Comment by Valorcalls** [comment]
The warcom team (The Marketing Team) is not the rules team (the ones who make the books). The warcom team is not ever considered accurate for rules.

**Comment by alphalas** [comment]
@Constant1Valdor Warhammer community is notoriously known for putting out absolutely incorrect information that is proven correct by reading the Codex/rulebook . All Warhammer community is is a social media team that is fairly loosey-goosey with what they write.

**Comment by ghost** [comment]
can you explain me what is "RAW" ???!!! i don't know what it is ...

**Comment by alphalas** [comment]
RAW: Rules as written

**Comment by alphalas** [comment]
The saggitarum guard have a points cost for their misericordias in MFM, ERGO they must pay that cost. All other units that don’t have a cost listed don’t pay for it. That’s literally how it’s worked all of 9e

**Comment by ghost** [comment]
OK. ok. But if i write to GW i think my email will be deleted as quickly as it is arrived in mailbox GW ... So i am a silent voice in a million mail that GW receives

**Comment by ghost** [comment]
Can you translate for me ERGO and MFM (i'm french and i don't understand all words in english ...
Thanks

**Comment by Valorcalls** [comment]
that's not how the FAQ team works, it gets filtered properly.
MFM is the new points book that dropped recently, and is the source of all points for any book that isn't Tau (technically) as the newest source.
ERGO isn't an acronym, it effectively means "therefore"

**Comment by alphalas** [comment]
Ergo just means thus, so, etc
MFM is the Munitorum Field Manual, the part of Chapter Approved that updates points

**Comment by ghost** [comment]
Allright. I understand better now. So i'm convicted that it is a mistake by GW ... i will follow the next GW faq and updates about that !!!
Thanks for all and for your answers. 
See you & thanks for all your works on battlescribe !!!!

**Comment by alphalas** [comment]
It’s a mistake by the warhammer community team, not the rules team. Like I said, Warhammer community has been known for putting up blatantly incorrect information without correcting themselves later when it comes to rules in the prerelease news cycle.

**Comment by alphalas** [comment]
For example they have screwed up describing how storm shields work (saying they have rules they 100% absolutely didn’t have in the codex) and they flubbed badly on Be’lakor’s sword and how it works.
