### ISSUE TITLE
Tyranids: Crusher Stampede & Alpha Leader Beast Extra WT

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10930]
**File:** Tyranids.catz

**BattleScribe version:** 9.03.00

**Platform:** Android

**Dropbox:** No

**Description:** Tyranid units selected to be Warlords do not receive the extra warlord trait when the Crusher Stampede "Alpha Leader Beast" Strategem is selected.

**Comment by GenWilhelm** [comment]
Firstly, Alpha Leader-beast is a Leviathan stratagem, not a crusher stampede one. And, as far as I can tell, this is behaving correctly.

Please can you provide steps to reproduce the error?
