### ISSUE TITLE
Necrons: Dynastic advisors

### ISSUE THREAD

**Issue by lab-rat-kid** [BSData/wh40k-9e#10935]
**Describe the bug**
The dynastic advisors rule does not work.

**To Reproduce**
Create a battle-forged army which includes a Cryptek and a Nobel unit with no extra HQ slots. Try to add another Cryptek.

**Expected behavior**
An additional Cryptek should not take up an extra battlefield role slot.

**Device and data (please complete the following information):**
 - OS: android
 - BattleScribe version: v2.03.25.338
 - Release version: Necrons v98

**Comment by Technoblazed** [comment]
Add them from No Force Org Slot at the top.
