### ISSUE TITLE
Tau bodyguards limited to 1 per commander

### ISSUE THREAD

**Issue by Alex-40k** [BSData/wh40k-9e#10939]
**Describe the bug**
Bodyguards are currently limited to 1 per commander in all the detachment, nor just NFO slots 
**To Reproduce**
With 1 commander in the detachment add 1 bodyguard team to elites and 1 to nfo, the limit will pop up as one, remove the nfo and add it to elites and the limit will still be 1

**Expected behavior**
You should be able to bring up to 3 bodyguard units independently of how many commanders you bring, the difference being where you can put them 

Tau data V114

**Comment by Technoblazed** [comment]
Fixed in https://github.com/BSData/wh40k/commit/5b9d1be785405c551f5e1ce7fbdc3de20707bcaf
