### ISSUE TITLE
Orks: Incorrect validation on number of Nob on Smasha Squig

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10948]
**File:** Orks.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Hey I discovered that if you choose the squighogboys from the orks and then choose the two NoForceOrgSlot Nob on Smasha Squigs, battlescribe will give out an error message if you choose to regularly include a third Nob on Smasha Squig in your army.

**Comment by Mad-Spy** [comment]
Needs "Shared" unchecked on this constraint.

![image](https://user-images.githubusercontent.com/29306451/152981976-5690d094-f59e-42c5-9bfc-ee6bfbe58b01.png)
