### ISSUE TITLE
<HIVE FLEET> tag not properly being implemented in roster?

### ISSUE THREAD

**Issue by DaveNine** [BSData/wh40k-9e#10942]
I've noticed on Tyranivs v92 when selecting the Crusher Stampede Army of Renown with Leviathan hive fleet that I get a bunch of these <HIVE FLEET> tags all over the place even though I have a Hive fleet selected. I do not know if this is an error caused by data or BattleScribe. I did notice the same behavior even if I select other Hive Fleets so maybe it's intentional even if it's a little weird?

**Comment by Mad-Spy** [comment]
What "tags"? You haven't actually given any details of the problem

**Comment by DaveNine** [comment]
![issue](https://user-images.githubusercontent.com/19861039/152704126-c99ea077-f243-4507-927b-73bccdad6063.png)

This is the problem I am illustrating. It seems like even though having a Hive Fleet selected does not apply it to replacing the placeholder <HIVE FLEET> in the roster text.

**Comment by Mad-Spy** [comment]
That's just how it works. Battlescribe doesn't allow for replacing the generic keywords with specific ones without having to duplicate all the rules, so we don't bother.
