### ISSUE TITLE
Space Marines Power Level Update

### ISSUE THREAD

**Issue by synlic** [BSData/wh40k-9e#10952]
**Describe the bug**
Power Rating Update Updated 04/02/2022

---HQ
Primaris Chaplain on Bike - 6PL -> 7PL

---ELITES
Ancient in Terminator Armour - 5PL -> 6PL
Redemptor Dreadnought - 9PL -> 10PL

---FAST ATTACK
Storm Speeder Hailstrike - 9PL -> 7PL
Storm Speeder Hammerstrike - 9PL -> 8PL
Storm Speeder Thunderstrike - 9PL -> 8PL

---HEAVY SUPPORT
Centurion Devastator Squad - 14PL -> 11PL
Eliminator Squad - 5PL -> 4PL
Gladiator Lancer - 11PL -> 9PL
Gladiator Reaper- 12PL -> 10PL
Gladiator Valiant - 13PL -> 11PL
Land Raider - 15PL -> 14PL
Land Raider Crusader - 15PL -> 14PL
Land Raider Redeemer - 15PL ->14PL
Predator Destructor - 8PL -> 9PL
Repulsor Executioner - 19PL -> 18PL

---FLYERS
Stormraven Gunship - 17PL -> 16PL

---DEDICATED TRANSPORTS
Impulsor - 7PL ->  6PL

**Comment by williamcaw** [comment]
you got to go slow with this and do all synlic
fw/core sm  continued

---Fast Attack 
Deathstorm Drop Pod 6 to 7

---HEAVY SUPPORT
Centurion Devastator Squad 3 is what synlic said but when in 4-6 from 28 to 22

---Land Raider Achilles 18to  16
Sicaran Arcus 10 to  9
Sicaran Punisher 10 to  9
Vindicator Laser Destroyer 10 to   9
Whirlwind Scorpius 10 to 9


---FLYERS 
Xiphon Interceptor 11 to 12
Storm Eagle Gunship  19 to 18


---lord of war 
Astraeus 35 to 31
Fellblade & Falchion 31 to 32

**Comment by synlic** [comment]
Any news on this update?
