### ISSUE TITLE
Shas'O'Ralai missing in new tau lists

### ISSUE THREAD

**Issue by WingedOwl** [BSData/wh40k-9e#10965]
**Describe the bug**
Using the tau roster creater, Shas'O'Ralai is missing from the lidt of HQs, and he used to exist before the updated tau codex

**To Reproduce**
1. Go to new tau roster
2. Click on HQ
3. ShasO'Ralai no lo ger an option

**Expected behavior**
I would expect to see them there, for 100 points, as before.

**Screenshots**

**Device and data (please complete the following information):**
 - BattleScribe version [e.g. 2.03.45]
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by Technoblazed** [comment]
Change your sept to Ke'lshan.

**Comment by WingedOwl** [comment]
> Change your sept to Ke'lshan.

Thanks.
