### ISSUE TITLE
Tau/Imperial Armor DX-6 Remora Stealth Drones

### ISSUE THREAD

**Issue by KenPrintz** [BSData/wh40k-9e#10977]
**Describe the bug**
Remora Stealth Drones should be a single force organization slot for 1-4 Drones.  Currently, Roster builder will generate 
a roster validation error if you assign more stealth drones to the unit that your detachment has flyer slots.  (I.E. if you're using a brigade detachment with 2 flyer slots, and you assign 4 drones to the unit, it will tell you that there are 2 too many flyers assigned to the Brigade)

**To Reproduce**
1. Create Brigade detachment
2. add DX-6 Remora Stealth Drones
3. Use up arrow to increase to 3 or 4

**Expected behavior**
DX-6 Drones should occupy a single force organization slot regardless of number of drones in the unit

**Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version 2.03.21
 - Release version [Warhammer 40,000 9th Edition v205]

**Comment by AbonShell** [comment]
You are limited to 2 AIRCRAFT keyword models in a 2k game, as per the new data slate
