### ISSUE TITLE
Tau v116

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#10975]
Shadowsun currently can be taken in a detachment that is any sept, like Farsight Enclaves, but she has the T'au Sept keyword so she should only be able to be taken in a detachment that has the T'au Sept selected and not any of other septs selected
![image](https://user-images.githubusercontent.com/72748875/153698290-2c052fe4-d6d1-4b87-894e-28d7d57261b1.png)
![image](https://user-images.githubusercontent.com/72748875/153698304-6433032d-0a6e-4074-82b7-50eb19395ce1.jpeg)

**Comment by Technoblazed** [comment]
Shadowsun can be placed into other sept detachments as she's exempted due to the SUPREME COMMANDER keyword, mentioned in the sept text at the start of the rules section of the codex.

**Comment by RespectableJack** [comment]
On page 92, it says "if your army is battle-forged, you cannot include units from two different septs in the same detachment." 
The septs rule is for the whole army but on a detachment level she can't be included in a Farshights Enclave detachment
She can be in the same army but not the same detachment unless it's T'au sept
@Technoblazed

**Comment by Technoblazed** [comment]
@RespectableJack I've updated this now for shadowsun, but this also applies to Aun'va and Aun'shi too, regardless of the rules they have, due to the fact their rule just exempts them from the `Sept Detachment` declaration which is a different thing - so they will also need an FAQ.
