### ISSUE TITLE
Chaos spawn table of numbers 

### ISSUE THREAD

**Issue by Hels444** [BSData/wh40k-9e#10973]
File: Chaos - Daemons.catz

BattleScribe version: 2.03.25

Platform: Android

Dropbox: No

Description: could you add Chaos spawn to roster against the Lord of change as there is currently no way of seeing the WS, BS, D, A, S, T for the chaos spawn. Only possible to set aside reinforcement points for them with no detail. Would be the same approach as taken for the blue horrors and brimstone horrors. Thanks.

**Comment by Mad-Spy** [comment]
It's different in as much as the Blue and Brimstone Horrors are listed on the datasheet for the Horrors unit. However, I've added the Spawn in for Reinforcement detachments only.
