### ISSUE TITLE
Necrons: Wraith PL cost needs to be updated

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10980]
**File:** Necrons.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Canoptek Wraiths are 4 Power Level, should be 6 Power Level. Change Canoptek Wraiths from 4 Power Level to 6 Power Level.

**Comment by williamcaw** [comment]
power level update 2/4/22
Canoptek Wraiths 3: 4 to  6,  4-6: 8 to12
missed in the update in  #10941
