### ISSUE TITLE
T'au Empire - Aun'Va/Aun'Shi Sept Restrictions

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10989]
**File:** T'au Empire.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Aun'va Can joint detachement if any setp but he is hiden if the detachement isn't a tau detachemnt.

**Comment by Technoblazed** [comment]
Going to use this bug report as a reference for all future reports on this issue until it gets FAQ'd:

T'au Empire Codex - pg. 55, "Septs" paragraph 1
> If every <SEPT> unit in a T'AU EMPIRE Detachment is from the same sept, that Detachment is referred to as a Sept Detachment.

T'au Empire Codex - pg. 92, "The Sept Keyword", paragraph 5
> If your army is Battle-forged, you cannot include units from two different T'au septs in the same Detachment. 

T'au Empire Codex - pg. 105, "Aun'Va/Aun'Shi", Leadership Caste ability
> This unit can be included in any T'AU EMPIRE Detachment (excluding FARSIGHT ENCLAVES Detachments) **without preventing that Detachment from being a Sept Detachment** and without preventing other units in your army from benefiting from a Sept Tenet (pg 55), but this unit can only benefit from a Sept Tenet if every <SEPT> unit (excluding SUPREME COMMANDER units) in your army is from T'AU SEPT.

Rules as written, for both Aun'Va and Aun'Shi, you cannot include them in a detachment of a sept that is not T'au Sept or Vior'la Sept respectively, as while they do not break the Sept Detachment restriction, they do break the battle forged requirement currently.
