### ISSUE TITLE
Imperium - Imperial Knights : Exalted Court warlord traits for House Allegiance 

### ISSUE THREAD

**Issue by stephendonn** [BSData/wh40k-9e#10988]
**Describe the bug**
Household specific warlord traits are hidden when selected as an exalted court stratagem. These warlord traits are visible if "Warlord" is selected.

Steps to reproduce the behaviour:
1. Add "Household Choice",  Select "Questor Mechanicus" under "House Allegiance", and  "Raven"  under "Household" 
2. Add "Exalted Court" from "Stratagems"
3. Add "Knight Errant" from "Lord of War"
4. On the "Knight Errant", select "Character (Exalted Court)"
5. Under "Warlord Traits" For the "Knight Errant", Warlord traits with "(Mechanicus)" are hidden.

**Expected behaviour**
Under "Warlord Traits" For the "Knight Errant", Warlord traits with "(Mechanicus)" are visible.

**Device and data:**
 - OS: Windows 11
 - BattleScribe version: 2.03.21
 - Release version: [e.g. v1.2.3]

**Comment by Mad-Spy** [comment]
This is correct behaviour. Models granted a Warlord Trait via a Stratagem are do not count as a subfaction Warlord for the purposes of eligibility for WLTs, only for using the WLT they choose.
