### ISSUE TITLE
Grey Hunters Points and Option errors - v2.03.25.338

### ISSUE THREAD

**Issue by MechFace** [BSData/wh40k-9e#10995]
The Space wolves data (or at least the app interp of it) has gone really strange and is adding up grey hunter unit costs way higher than they should be e.g. 490 for a unit of 10 instead of 224. Also the summaries of the unit options selected are adding up differently and appearing in different unit options (i.e. wolf guard listing x5 chainswords). I've attached screenshot.

Try to create any Grey Hunters unit with any additional options than 5 marine default layout

![Screenshot_20220222-151354](https://user-images.githubusercontent.com/100224356/155177809-896fa961-3020-422f-980a-47ed68c3ed05.png)

 - mobile google Android
 - BattleScribe
v2.03.25.338 with latest update downloaded

**Comment by AbonShell** [comment]
Yeah if you look at all your selections, something really messed up. Close out the app, re-open it, delete that unit and remake it.
