### ISSUE TITLE
[RESUBMISSION] Bug/Rules error in Chaos Space Marine data

### ISSUE THREAD

**Issue by TheBigBadPanda** [BSData/wh40k-9e#11]
**File/Catalogue:** 

**BattleScribe version:** 2.01.02.

**Platform:** Android (probably all)

**Dropbox:** No

**Description:** When attempting to set up a unit of Chaos Space Marines i do not seem to have any options for wargear for the champion at all, and am not able to give the squad two Heavy Weapons or two Special Weapons, only one of each.

NOTE: This is a re-submission of a previous issue which was closed due to me not having altered the default "2.0" in the "BattleScribe version"-field.

**Comment by alphalas** [comment]
What version of the data are you running is the next question

**Comment by TheBigBadPanda** [comment]
v1.0.0 according to the android interface, just refreshed it and it did not change. Its the only one available so far, is it not?

**Comment by alphalas** [comment]
Correct- was just making sure you weren't still on 7e data
