### ISSUE TITLE
Imperium- adeptus custodies

### ISSUE THREAD

**Issue by thatguyis** [BSData/wh40k-9e#11006]
Looking at trajann Valoris he lets you pick up two two warlord traits in the book, but the most updated version of battle scribe only lets you pick master of the martial strategy and champion of the imperium. 

Also it appears that relics are missing for the shield hosts options and the relics for the army that can be picked if you dont want the shield host relics.

**Comment by Technoblazed** [comment]
1. Trajaan is forced to those 2 warlord traits per the codex, it's not an option.
2. The relics seem to be working just fine, make sure you have a <SHIELD HOST> character as your warlord.

**Comment by thatguyis** [comment]
Ok now I see the trait thing but that does explain why I can’t add the castellian mark to trajann

**Comment by thatguyis** [comment]
Oh wait never mind….
