### ISSUE TITLE
Error when taking additional Kroot Shapers with Kroot Carnivore's "Kroot Pack" special rule

### ISSUE THREAD

**Issue by jeffreyteters** [BSData/wh40k-9e#11001]
**Describe the bug**
Unable to include extra shapers with Kroot Pack rule (pg. 110)

**To Reproduce**
1. Start a new detachment for Tau
2. Choose 1 ethereal, 1 x Kroot Shaper (Warlord), 4 x Kroot Shapers, and 5 x Kroot Carnivore Squads.  
3. The following error is displayed: T'au Empire v114 (Battalion Detachment 0CP has 3 too many selections from HQ (Maximum 3).

**Expected behavior**
According to pg. 110 of the 9th edition codex, the Kroot Pack special rule should enable 1 non-HQ slot shaper.

**Screenshots**
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/89485014/155455455-04ebec68-4d14-46a3-8ee3-da8a1cd32d7c.png">

**Device and data (please complete the following information):**
 - OS: Mac
 - BattleScribe v2.03.21.166

**Comment by Technoblazed** [comment]
Add it from the no force org section.

**Comment by jeffreyteters** [comment]
Perfect!  Totally missed that.
