### ISSUE TITLE
ORKS - regular deathskull mek cannot choose da fixer upperz gubbin

### ISSUE THREAD

**Issue by ajulien42** [BSData/wh40k-9e#11008]
File: orks.catz

BattleScribe version: 2.03.21

Platform: Mac OS

Description: When choosing gubbinz for a regular mek, Da Fixer Upperz is not available except if the mek is a warlord, it should be available all the time.

**Comment by Technoblazed** [comment]
Seems to be working fine, make sure you actually have a deathskulls model as your warlord.

![Image](https://i.tech-no.me/2022/03/01/220301111228.png)

**Comment by ajulien42** [comment]
My bad.. my warlord was from a different kultur
