### ISSUE TITLE
Inquisitor Erasmus Cartavolnus data sheet

### ISSUE THREAD

**Issue by Muck1ng** [BSData/wh40k-9e#11017]
![image](https://user-images.githubusercontent.com/10154047/156894768-2ceb5d66-1b1e-429f-9660-ea2c5d36e505.jpg)

![image](https://user-images.githubusercontent.com/10154047/156894738-42ee320a-6563-41e4-af91-192f9b3c02b5.jpg)
![image](https://user-images.githubusercontent.com/10154047/156894751-3bbb6dab-c8f0-47d1-a9bb-c2d5f2ce707d.jpg)

**Comment by Technoblazed** [comment]
Added in https://github.com/BSData/wh40k/pull/11082
