### ISSUE TITLE
Ulthwe issue and seer council

### ISSUE THREAD

**Issue by lats1367** [BSData/wh40k-9e#11020]
Seer council Strat gives a CP instead of removing

When you give the ulthwe relic for a psyckwr to gain an additional psychic power, BS registers an error that the psycker has too many powers when it should be allowed to have an additional power from Fortune only.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - BattleScribe version [e.g. 2.03.45]
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by Mad-Spy** [comment]
Added to #11019
