### ISSUE TITLE
Codex Aeldari: Warlock Skyrunners - Seer Council Strat

### ISSUE THREAD

**Issue by SonOfGuilliman** [BSData/wh40k-9e#11024]
**Describe the bug**
Warlock Skyrunners don't have a box to complete the Seer Council Stratagem integrity check. 

**To Reproduce**
1. Go to Creating a Craftworld Aeldari Armor
2. Click on Stratagem: Seer Council 
3. Scroll down to: Your Farseer on Skyrunner and check the box for Seer Council (Farseer) - 
4. See error - The Seer Council (Warlocks Unit) cannot be found on either the Elite Slot version of Warloks on Skyrunners or the Slot Free Warlock Conclave Warlock Skyrunners. 

**Expected behavior**
Both of these units should have the expected box to check and close out the Battlescribe integrity check for Seer Council stratagem.

**Comment by FarseerVeraenthis** [comment]
Darn it, Warlocks are working correctly, but the Warlock Skyrunners are not.
I have moved this to #11019
