### ISSUE TITLE
Aeldari - Harlequins: Troupe load out issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11032]
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The harlequin troupe load outs don’t allow fusion pistol and harlequin caress to be selected

**Comment by FarseerVeraenthis** [comment]
This is already fixed on Master and will be updated with the next release.
