### ISSUE TITLE
Aeldari - Craftworlds: Ghosthelm of Alibaba is not magic enough

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11030]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 9.03.06

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Ghosthelm from Ulthwe does not give spell of rune of Fortune

**Comment by FarseerVeraenthis** [comment]
This is already fixed on Master and will be updated on the next release.
