### ISSUE TITLE
Yvraine doesn't get marked as Asuryani Warlord correctly.

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k-9e#11039]
![image](https://user-images.githubusercontent.com/29306451/157660463-151246de-1e76-40ca-8600-2ddf6ace1229.png)

The Shared checkbox is not checked on the modifier which should give Yvraine the "Asuryani Warlord" category.

For some reason, this stops the keyword from being applied.

**Comment by FarseerVeraenthis** [comment]
That wicked Copy/Paste fairy again... It was the same issue for all three of the Triumvirate - now fixed :smile: (on master at least!!)
