### ISSUE TITLE
Aeldari - Craftworlds: Striking Scorpions not suitably striking

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11033]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Striking Scorpions in the 9th Ed codex are A3 base. In BattleScribe there are showing A2 still.
Thanks 😊

**Comment by FarseerVeraenthis** [comment]
Updated on Master, will be in the next data release.
