### ISSUE TITLE
Aeldari - Craftworlds: Shrine Relics incorrectly cost a CP each

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11045]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 9.03.07

**Platform:** Android

**Dropbox:** No

**Description:** Relics of the shrine cost one CP each currently and option 1 CP. In fact if you take the option you can select two for free.

**Comment by FarseerVeraenthis** [comment]
It looks like the commit that sorted this out wasn't pushed to Master before the release went out.
It is fixed on master and will be included in the next release.

**Comment by FarseerVeraenthis** [comment]
this fix is released.
