### ISSUE TITLE
Ynnari in General

### ISSUE THREAD

**Issue by Ithyrrinaz** [BSData/wh40k-9e#11044]
Ynnari in general doesnt work with the extra strategems. You cant add relics, extra warlord traits or anything of the likes. (Yvraine was the OG warlord in my list and my Authark could not have a relic (No option for the extra relic strategem) nor use the "Extra WL-trait strategem"

"Relics of the shrines" (For autharks) Doesnt work either. No extra relic options appear when selected.

Striking scorpions exarch has a shrine relic as an option. It costs 1 CP.. But selecting it gives an error because you didnt use the "strategem" in the main list. Seems like the box in the exarch list is a leftover. (The strategem should be only one CP not two..And be (it seems) Enabled in the main list..Not in the exarchs weapon selection.) 

The harlequin/Drukhari child detachment doesnt work with the validation system. (And all of the above errors)

**Comment by FarseerVeraenthis** [comment]
Suggest you update your data and check/uncheck the Warlord box for Yvraine.
While it is possible there is a lingering -1CP for the scorpions, I just built the following list from scratch, and you can see the validation is correct.
Note that there are no shrine relics available for the Autarch, they are only accessible for Exarchs.
The full Ynnari implementation is still in development as there are some tricky vaidation issues that I'm still trying to resolve.
![image](https://user-images.githubusercontent.com/23246922/157833175-442bae7b-30aa-4991-8fa5-923302ad4fed.png)
