### ISSUE TITLE
Aeldari Craftworlds - Fire Dragons are hidden for Ynnari detachments 

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#11041]
**Describe the bug**
For Ynnari detachments, Fire Dragons are incorrectly hidden.

**To Reproduce**
1. Create a detachment where the Craftworld is set to Ynnari.
2. Go to Elites.
3. Fire Dragons aren't visible.

**Expected behavior**
Fire Dragons should be visible for Ynnari detachments

**Screenshots**
N/A

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version 2.03.21
 - Release version Aeldari - Craftworlds v151

**Additional context**
N/A

**Comment by FarseerVeraenthis** [comment]
Thanks, this happened as part of my work for Corsairs, that copy/paste fairy is a wicked mistress...!! (Fixed on Master, ready for release)
