### ISSUE TITLE
Aeldari - Harlequins: Troupe Master is missing options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11047]
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Harlequin Troupe Lead Player doesn’t have the ability to take a Caress or Embrace.

**Comment by FarseerVeraenthis** [comment]
this fix is included in the latest release
