### ISSUE TITLE
Tau - Multi tracker on Bodyguards

### ISSUE THREAD

**Issue by Settenano** [BSData/wh40k-9e#11052]
Multi tracker gives 2 additional hits on 6s if mounted on Bodyguards. It gives 1 additional hit if mounted on Crises or Commanders.

**Comment by Technoblazed** [comment]
Waiting for the FAQ before fixing this, as that datasheet is the only one for identically named wargear to have different ability text compared to all other units in the codex with the same wargear.

**Comment by Technoblazed** [comment]
No changes necessary as of
https://www.warhammer-community.com/wp-content/uploads/2019/10/zBkOtTfPzAqsQBnR.pdf
