### ISSUE TITLE
Aeldari - Harlequins: Solitare is not strong or tough enough

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11058]
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Solitaire in the new codex is S4 T4. In battlescribe they are still S3 T3

**Comment by FarseerVeraenthis** [comment]
this has been reported previously and is fixed on master
