### ISSUE TITLE
Aeldari - Craftworlds: Unit filter not working perfectly 

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11054]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The Unit Filter considers Vypers and War Walkers as Guardian units. They are not. The only units with the Guardian keyword are Guardian Defenders, Storm Guardians, Windriders, and Support Weapons. These are the only units that should be excluded by the Hide Guardian Units option.

**Comment by FarseerVeraenthis** [comment]
I mean, they're crewed by guardians, what's a few keywords between friends eh?!
(it's OK, I fixed it)
