### ISSUE TITLE
Aeldari - Craftworlds: shrine relics too expensive

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11050]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Aspect warrior relics are costing cp even when relics of the shrines stratagem is taken. This stratagem should allow two aspect relics for 1 cp. Thanks for the great work!

**Comment by FarseerVeraenthis** [comment]
Previously reported.
