### ISSUE TITLE
Aeldari - Harlequins: Unable to have multiple of the same Pivotal Role

### ISSUE THREAD

**Issue by AggressivelyMemeing** [BSData/wh40k-9e#11055]
**Describe the bug**
Harlequin Pivotal Roles are limited to one of each Pivotal Role per army. The codex allows for one of each Pivotal Role per subfaction (i.e. you can have a Light Death Jester, a Dark Death Jester, and a Twilight Death Jester all with the same Humbling Cruelty upgrade).

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a roster with either two or 3 Harlequin detachments that have an Elite or HQ slot. 
2. Set each detachment to have a different Saedath Characterisation
3. Add a Troupe Master, Shadowseer and Death Jester in each detachment.
4. Attempt to add the same Pivotal Role to each of the respective characters.  
5. Check for Roster Errors, and receive "has [1/2] too many selections of [Pivotal Role Name] (maximum 1)

**Expected behaviour**
So long as each of the Death Jesters, Troupe Masters and Shadowseers have different subfactions, they should be able to select the same Pivotal Role as another unit without issue. Solitaires do not have this problem since they are limited to 1 Solitaire per army and thus cannot have duplicates. 

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://cdn.discordapp.com/attachments/569676136028700699/952561642992959518/B22F6209-ED34-4E31-ABFF-0786D57E05E2.jpg)

**Device and data (please complete the following information):**
 - OS: iOS and Windows 10
 - BattleScribe version 2.03.21
 - Release version Warhammer 40,000 v9.3.6

**Additional context**
None

**Comment by FarseerVeraenthis** [comment]
I have updated the constraint to only look at the Force, not the Roster. The only problem with this is that if, for some reason, you have two Harlequin detachments with the same Characterisation in a roster, it would be possible to select the same Pivitol Role twice, without an error - even though this would be technically illegal. There is no way to validate this in BS at present without a major rework of how keywords are applied for Harlequins units with Pivitol Roles
