### ISSUE TITLE
Aeldari - Harlequins: Missing Troupe Leader options

### ISSUE THREAD

**Issue by AggressivelyMemeing** [BSData/wh40k-9e#11056]
**Describe the bug**
The Troupe Lead Player is unable to be equipped with a Caress or Embrace. 

**To Reproduce**
1. Create a roster containing at least 1 Harlequin Troupes units
2. Try to edit the Lead Player's melee weapon

**Expected behavior**
The option for a Harlequin's Embrace or Harlequin's Caress should exist.

**Screenshots**
None

**Device and data (please complete the following information):**
 - OS: iOS, Windows 10
 - BattleScribe version 2.03.21
 - Release version Warhammer 40,000 v9.3.6

**Additional context**
None

**Comment by FarseerVeraenthis** [comment]
this is fixed on Master and will be released shortly
