### ISSUE TITLE
Aeldari - Harlequins: Solitaire profile issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11053]
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Solitaire has S4 T4 as of the new codex, BS still lists it as S3 T3.

**Comment by FarseerVeraenthis** [comment]
This has already been resolved. Please update your data.
