### ISSUE TITLE
The Relics are not counted right

### ISSUE THREAD

**Issue by Ithyrrinaz** [BSData/wh40k-9e#11057]
The "Relics of the Shrine" Relics are for the Exarchs. 1 cp buys 2 of them.
"Treasures of the Aeldari" are for Characters..  The warlord (Or someone else when a warlord is selected) Get one free. 1 cp buys one more.

Right now it seems BS doesnt know the difference between them.

**Comment by FarseerVeraenthis** [comment]
this is fixed on Master and will be in the next release :smile:
