### ISSUE TITLE
Aeldari - Harlequins: Lead Player has lost his Kiss

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11068]
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Harlequin troops lead player is missing the harlequins kiss option after the last update, please fix. Thank you!

**Comment by FarseerVeraenthis** [comment]
I just updated my data nad the Kiss is present in file v69, maybe try updating again?
