### ISSUE TITLE
Aeldari - Craftworlds: Autarch Datasheet Update

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11067]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** GW released an updated Autarch datasheet with additional wargear options. Banshee blade, swooping hawk wings, and fusion pistol is no longer a locked option. Please update when you get a chance, and thanks for your great work!

**Comment by FarseerVeraenthis** [comment]
This will be included in the next release.
