### ISSUE TITLE
Aeldari - Harlequins: LEad Player selecitons missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11079]
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Lead Player for the Harlequin Troop appears to have lost the ability to take a Kiss.

Any models harlequin blade can be replaced with 1 harlequins kiss.

Data file checked: 9.3.8

**Comment by FarseerVeraenthis** [comment]
This is fixed on Master and will be in the next release.
