### ISSUE TITLE
Imperial Fists power level not correct

### ISSUE THREAD

**Issue by Veles343** [BSData/wh40k-9e#11072]
Noticed there are at least two units where the power level in the latest imperial fists data file is incorrect vs the latest power level published on WarCom, so I presume this effects the main space marines file as well.

The two I've spotted are:

Primaris Lieutenant - no longer costs an extra PL for taking power sword, relic shield and neo-volkite pistol
Eliminators - now only costs 4 PL not 5

**Comment by Veles343** [comment]
Comparing against:

https://www.warhammer-community.com/wp-content/uploads/2020/08/qLYBSYqMoHyXJ9yT.pdf

Found on here:

https://www.warhammer-community.com/faqs/

**Comment by Technoblazed** [comment]
Duplicate of https://github.com/BSData/wh40k/issues/10952
