### ISSUE TITLE
Aeldari - Harlequins: Troupe PL being difficult

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11076]
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 2.03.21

**Platform:** Android

**Dropbox:** No

**Description:** when you add more than one troupe units to the roster the powerlevel rises to 9
for all units
but that should only be happening of the models in a unit surpass 7
i think it counts all troupe models in the Roster instead of models in a unit

**Comment by FarseerVeraenthis** [comment]
This is fixed on Master and will be included in the next release.
