### ISSUE TITLE
Tau Codex Named Ethereals - Nachmund FAQ update

### ISSUE THREAD

**Issue by Trowis** [BSData/wh40k-9e#11078]
As RAW, you can't take either Aun'va or Aun'shi in a non-Tau/Viorla sept detachment without breaking battleforge. 

Nachmund FAQ gives us the following:

`
Q: Are named characters exempt from the rules that require 
every unit that has a selectable keyword to have the same 
selectable keyword?
A: Yes. Though named characters can have sub-faction keywords 
these are typically predetermined and not selected by the player 
(i.e. they are not typically presented within angular brackets). `

Is this enough to enable them to be taken in other sept detachments without breaking battleforge by RAW? Seems to be the intent and the read here.

**Comment by Technoblazed** [comment]
That FAQ is irrelevant as it only applies to the nachmund restriction, not the one in the codex. In terms of battlescribe, the intent doesn't really matter, the RAW says that they can't, which is what battlescribe uses.
