### ISSUE TITLE
Aeldari - Drukhari: Craftworld WLTS showing for Drukhari characters when Corsairs are in the roster.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11084]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** When building army lists where my warlord is a Drukhari character, and I have any Corsair Voidreaver or Corsair Voidscarred units in the same detatchment, the selection of Craftworld warlord traits is available. This is replicated across all 3 of the drukhari HQ units (Archon, Succubus, Haemonculus) and is not replicated when there are Corsair units in the same army, but a different detatchment.

**Comment by FarseerVeraenthis** [comment]
yeah, I know why that's happening :-) thanks for the report!!
