### ISSUE TITLE
Aeldari - Harlequins: Validation errors on Troupe

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11080]
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Data file 9.3.8

Issue when adding a second Fusion Pistol or a second Neuro Disruptor to a Troupe unit above 5.

Errors reported:
If 2 Fusion Pistol selected:
Troupe has 2 too many selections of Player w/ Fusion Pistol & Embrace (maximum -2)
Troupe has 2 too many selections of Player w/ Fusion Pistol & Caress (maximum -2)
If 2 Neuro Disruptor selected:
Troupe has 2 too many selections of Player w/ Neuro Disruptor & Embrace (maximum -2)
Troupe has 2 too many selections of Player w/ Neuro Disruptor & Caress (maximum -2)

To be clear, the Fusion Pistols and Neuro Disruptors are assigned to the Lead Player and a Player w/ Fusion Pistol & Kiss.

This may be related to Player w/ Fusion Pistol & Embrace, Player w/ Fusion Pistol & Caress being listed under "4-11 players" rather than "Fusion Pistols".  This also applies to Player w/ Neuro Disruptor & Embrace and Player w/ Neuro Disruptor & Caress.

**Comment by FarseerVeraenthis** [comment]
This is fixed in the latest release
