### ISSUE TITLE
Ynnari - Drukhari can't take Relics even if warlord in Ynnari detachment

### ISSUE THREAD

**Issue by OddestFuture** [BSData/wh40k-9e#11088]
**Describe the bug**
Title expalins

**To Reproduce**
Pick a drukhari character in a Ynnari detachment, no relics are available.

**Expected behavior**
Debatable, but after reading through the Relics of Cruelty and the Ynnari detachment rules I found literally no reason why a Drukhari Ynnari warlord could not take Drukhari relics (it only requires a Drukhari warlord, pg 74 Drukhari codex) Only WLT's are restricted by Kabal/Cult/Coven from what I could find, I know many people have said otherwise but I could find no reason for this on any page regarding detachment rules for Drukhari/Aeldari/Ynnari or their Relic pages. Also the TREASURES OF THE AELDARI RELICS (P84) a Drukhari character can take a relic if you have a Craftworld (WHICH YNNARI IS) warlord. This seemingly contradicts the later relic section in the book, but should over ride it as they are two separate rules and the other one does not directly say you CANT take a relic if the warlord is only craftworld and not also Asuryani/Harlequin.

This would however block you (if the warlord is drukhari) from taking any other Craftworld relics, as the strat would be unusable (same with the WLT Strat).

**Comment by FarseerVeraenthis** [comment]
Seems reasonable. Obviously, the Drukhari Warlord won't be able to take any of the sub-faction locked relics, but should be able to take the 'normal' ones.
I will work this up.
