### ISSUE TITLE
Aeldari - Harlequins: PL cost for Troupe increments incorrectly

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11081]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** When I create a Harlequin Troupe with 2 Fusion Pistols and each special weapon the Power Level changes to 9 despite not increasing the number of models, PL should just be 9 regardless of loadout

**Comment by FarseerVeraenthis** [comment]
Should be fixed in the latest release.
