### ISSUE TITLE
Aeldari - Craftworlds: Warlord traits playing silly beggars

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11087]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** In a Ynnari detachment, when you include a Harlequin character and elect an Asuryani character as your warlord or through the Champion of Asuryani stratagem battlescribe dictates that you can select a Harlequin warlord trait for them even though this should not be the case.

**Comment by FarseerVeraenthis** [comment]
this is fixed on master and will be included in the next release.
