### ISSUE TITLE
Imperium - Ultramarines: Is a tech marine on thunderfire even a Character to you?!

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11086]
**File:** Imperium - Ultramarines.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The tech marine gunner in a thunderfire cannon unit can't can't equip a relic or assign a warlord trait.

**Comment by acebaur** [comment]
Who even takes TFC anymore?!?

**Comment by Mad-Spy** [comment]
I don't think this is possible as relic and WLT SEGs are added in the faction catalogues, but you can't drill down to the Techmarine to apply them in the "correct" place.

**Comment by acebaur** [comment]
just looked at this, it's working correctly? can't replicate it
