### ISSUE TITLE
Ynnari Drukhari Wych cult/Kabal have access to upgrades they shouldnt

### ISSUE THREAD

**Issue by OddestFuture** [BSData/wh40k-9e#11098]
**Describe the bug**
Succubus and Archon have access to Lords of Commoragh upgrades in Ynnari which are specifically banned from the detachment. Also, Drukhari models can still pick "Alternate Kabal/Wych Cult" but they lose such key words and would not be able to switch.

**Expected behavior**
Lords of Commoragh and Cult/Kabal alternate selections should be inaccessible in Ynnari.

**Comment by FarseerVeraenthis** [comment]
I took care of the alternative selector last night, but I thought I'd already handled the other bit... I'll have a look and get it fixed 😊
