### ISSUE TITLE
Impossible to give Eldrad Ulthran a warlord trait with Champion of the Aeldari stratagem

### ISSUE THREAD

**Issue by just-jasper** [BSData/wh40k-9e#11099]
I think it should be possible to give Eldrad Ulthran a warlord trait with the Champion of the Aeldari stratagem, which states

> Use this Stratagem before the battle, when you are mustering your army, if your Warlord has the Asuryani or Harlequins keyword. Select one Asuryani Character or Harlequins Character and determine one Warlord Trait for that model; that model is only regarded as your Warlord for the purposes of that Warlord Trait. Each Warlord Trait in your army must be unique (if randomly generated, re-roll duplicate results), and you cannot use this stratagem to give a model two Warlord Traits. You can only use this Stratagem once, unless you are playing a Strike Force battle (in which case you can use this Stratagem twice), or an Onslaught battle (in which case you can use this Stratagem three times).

There's no exemption for named characters in the wording or elsewhere in the book, as far as I can see. On the Warlord Traits page, it states "If one of the following named characters gains a Warlord Trait, they must have the corresponding one shown on the right.", but doesn't mention anything about them being ineligible for the stratagem in the way that it does for relics ("Named characters cannot be given any Treasures of the Aeldari relics." — p84).

Hoping I haven't misunderstood something or missed a rule somewhere. 

Cheers,
Jasper

**Comment by FarseerVeraenthis** [comment]
Hmmmm... You're probably right, I'll have a look later.
