### ISSUE TITLE
Aeldari - Drukhari: Are Ynnari Drukhari still obsessive?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11094]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When I try to add an Ynnari detachment to my Drukhari list it pops up with an error that says you can’t use obsessions.  I can’t seem to find anything in the rules that says you would lose your obsessions for adding that style of detachment.  I get losing power from pain but not the obsessions.  Thank you.

**Comment by OddestFuture** [comment]
They lose their obsession. Their obsession (which is linked to <Kabal>/<Cult>) is replaced with <Craftworld> (P. 92, Aeldari codex).

**Comment by FarseerVeraenthis** [comment]
If you have a Drukhari Detachment, AND a Ynnari Detachment, the Drukhari in the Drukhari detachment can still have an obsession, but they do lose Power from Pain.

**Comment by FarseerVeraenthis** [comment]
the Drukhari IN the Ynnari detachment do not get an obsession
