### ISSUE TITLE
Craftworlds: Switch Support Weapons, Vypers, War Walker Weapons to quantity selector 

### ISSUE THREAD

**Issue by akakorlandril** [BSData/wh40k-9e#11097]
**Describe the bug**
Currently Support weapons & Vypers require to add a new model in the unit and change weapons individually when they only have one weapon option so would benefit from switching to quantity selector. War Walkers weapon options also have to be selected individually to change when they can be quantity the same way as Wraithlord heavy weapons are (precedent).

Similar issue but there are 3 combinations of Wraithlord non-heavy weapons, these are: 2 Flamers, 2 Shuriken catapults or one of each. Instead of having to select these individually add a single selector (**not** quantity selector) where you can pick between these 3 options.

**Additional context**
Talked with FarseerV regarding these very minor issues already :D

**Comment by FarseerVeraenthis** [comment]
Thanks, I'll get to it :+1:
