### ISSUE TITLE
Aeldari - Craftworlds: Warlock cost.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11091]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Aeldari Craftworlds army building lists a Warlock as 40 points per model. It should be 20 points per model

**Comment by FarseerVeraenthis** [comment]
they are 40 points for a single Warlock, 20 points if you take more than one - both are reflected in the current released version of the data.
