### ISSUE TITLE
Kurnos Bow and Farseers 

### ISSUE THREAD

**Issue by Savoronedge** [BSData/wh40k-9e#11095]
**Describe the bug**
Kurnos Bow creates an error "To many instances of Shuriken Pistol" when taken on a Farseer or Farseer Skyrunner. Removing the Shuriken Pistol then creates an error "Kurnos Bow may not be taken"

**To Reproduce**
1. Select a Farseer or Farseer Skyrunner
2. Add Relic, Kurnos Bow
3. See error

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - OS: both Windows 10 and Android
 - BattleScribe version  2.03.25
 - Release version 9.3.9

**Additional context**

**Comment by FarseerVeraenthis** [comment]
Please update your data, this is fixed 😸 
![Screenshot_20220323-064707](https://user-images.githubusercontent.com/23246922/159639681-0cc64d48-8a23-40d5-89c8-a3978ba62cec.png)

**Comment by Savoronedge** [comment]
Just refreshed this morning. Windows version still has the problem. Android
is correct.

**Comment by FarseerVeraenthis** [comment]
Both versions use the same data, so it would appear your desktop data has not updated itself properly... 
I'm glad to hear it is working on Android though :+1:
