### ISSUE TITLE
I don't get inline data for the preview 40k 8th

### ISSUE THREAD

**Issue by ernsm** [BSData/wh40k-9e#111]
**File/Catalogue:** 

**BattleScribe version:** 2.01.02 Newest

**Platform:** iOS

**Dropbox:** No

**Description:** I don't get the inline data into the preview. I deleted all data, re downloaded, tried other armies. Nothing. Meanwhile on my mac I have no problem

**Comment by Kohato** [comment]
Set "All Categories" to "No Categories" In list view. Known BS bug, not issue with data.
