### ISSUE TITLE
Aeldari - Harlequins: Pivotal roles pl missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11104]
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** When adding a pivotal role it increases the points but does not increase the PL by 1 as stipulated in the codex.

**Comment by FarseerVeraenthis** [comment]
Please update your data, this is fixed.
![Screenshot_20220329-191439](https://user-images.githubusercontent.com/23246922/160678192-4e198b72-ddb6-4aa8-99a6-4148cb974f55.png)
