### ISSUE TITLE
Prizes from the Dark City

### ISSUE THREAD

**Issue by shanethehat** [BSData/wh40k-9e#11107]
The Prizes from the Dark City stratagem does not allow selections for cult specific relics.

To recreate:

1. Create 2 Drukhari combat patrols, one with an archon and kabalites, the other with a succubus and wyches
2. With the first patrol, set the obsession to a kabal obsession, make the Archon the warlord
3. With the second patrol, set the obsession to a cult obsession
4. Observe that the Succubus does not get the cult specific relics appear

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/604650/160851853-be71e4c8-b9af-4623-9d60-cc0d68116baa.png">

In this image you can see that the Succubus can only select from the shared relics, and Traitors Embrace is hidden.

**Comment by AbonShell** [comment]
Working as intended. Your warlord must be of the specific subfaction in order to get access to those relics.  Page 53 of the codex

**Comment by shanethehat** [comment]
Ah, sorry you are right. You can only do what I'm wanting if its part of a realspace raid, and so the behaviour of the official 40k app is wrong!

**Comment by FarseerVeraenthis** [comment]
> ... and so the behaviour of the official 40k app is wrong!

Wouldn't be the first time, won't be the last 😸
