### ISSUE TITLE
Warlock Elite slot

### ISSUE THREAD

**Issue by skinless77** [BSData/wh40k-9e#11108]
**Describe the bug**
A warlock should not take an Elite slot if a Farseer is in the list thanks to the "Seer Council" rule

**To Reproduce**
Create an Aeldari Craftworlds list with a Patrol Detachment
Add a Farseer
Add a Warlock, plus 2 Elite unit

A validation error about the number of Elite units appear

**Expected behavior**
No validation error, the Warlock doesn't take an Elite slot

**Device and data (please complete the following information):**
 - OS: Windows 11
 - BattleScribe version 2.03.21

**Comment by AbonShell** [comment]
Once you add the farseer you will have a new catagory called No Force Org slot. You can find your free slot units there.
