### ISSUE TITLE
Tolerated Ambition

### ISSUE THREAD

**Issue by khalbrogo** [BSData/wh40k-9e#11103]
**Describe the bug**
Enabling Tolerated Ambition on Archon, Succubus, or Haemonculous does not give the full list of Warlord traits if they are in two different detachments. Only Inspiring Leader is available. If both HQ's are in the same detachement it works properly. 

**To Reproduce**
1. Create Two detachments
1. Add an HQ to each detachment (Archon, Succubus, or Haemonculous)
2. Give one of the above Warlord
3. Give the other Tolerated Ambition

**Expected behavior**
Tolerated Ambition should give the option for any Warlord trait that isn't already taken on another unit. 

**Screenshots**

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version [e.g. 2.03.45] v2.03.21.166
 - Release version [e.g. v1.2.3] 9.3.10

**Additional context**
![Capture](https://user-images.githubusercontent.com/102536303/160429268-4d7c8bc9-3e32-4334-a206-16c57a058d03.JPG)

**Comment by FarseerVeraenthis** [comment]
Looks like the show/hide has the wrong scope.
I'll try to fix it before the next release 😸

**Comment by FarseerVeraenthis** [comment]
This is now fixed on Master and will be included in the next release
