### ISSUE TITLE
Vanguard strike force errors - relics missing, outriders selectable

### ISSUE THREAD

**Issue by centurian99** [BSData/wh40k-9e#11105]
**Describe the bug**
The relics for the Vanguard strike force are missing and you can take outriders.

**Device and data (please complete the following information):**
 - OS: Android
 - BattleScribe version [BattleScribe v2.03.25.338
 - Release version 9.3.9

**Comment by acebaur** [comment]
Was fixed a while back

**Comment by centurian99** [comment]
Outriders is fixed but relics don't appear with a raven guard Vanguard strike force

Sent from Yahoo Mail on Android 
 
  On Wed, Apr 6, 2022 at 4:53 PM, Alex ***@***.***> wrote:   


Was fixed a while back
