### ISSUE TITLE
Space marine codex: Jump pack costs

### ISSUE THREAD

**Issue by mecdanna** [BSData/wh40k-9e#11114]
**Describe the bug**
For the space marine codex the jump pack cost is 2pts, according to the official app & the community update: https://www.warhammer-community.com/wp-content/uploads/2020/08/76UtmPgtSCGKJAnW.pdf
However it is 3 points in the app.

**To Reproduce**
1. Create a new Imperium detachment.
2. Create a space marine detachment (I use Deathwatch).
3. Add Veteran Vanguard marines or a Proteus killteam.
4. Add Veteran vanguards and give them jump packs, the cost is 3.

**Expected behavior**
Cost should be 2.

**Screenshots**
N/A

**Device and data (please complete the following information):**
 - OS: Android
 - BattleScribe version:  v2.03.25.338
 - Release version v9.3.10

**Additional context**
I tried to figure out how to fix it myself and submit a MR however I couldn't figure it out and I needed to get back to work. Sorry about that.

**Comment by Mad-Spy** [comment]
Cost is correct as per MFM2022. Your link is to the update to the 2021 MFM.

**Comment by mecdanna** [comment]
Sorry about that. My google-fu is weak.
