### ISSUE TITLE
Craftworlds Exarchs relics missing

### ISSUE THREAD

**Issue by LeButler** [BSData/wh40k-9e#11115]
Dire Avengers exarch, Fire Dragon Exarch, Howling Banshee Exarch, Warp Spider Exarch, Shining Spear Exarch and Dark Reaper Exarch not able to take their Aspect Shrine Relics.
Striking Scorpion exarch and Swooping Hawk Exarch do have relic option when selecting their loadouts.

Device and data
 - Windows App
 - BattleScribe version 2.03.21
 - Release version: Warhammer 40,000 v9.3.10 

Same issue seems to be with android phone App version 2.03.25. 

Further investigation shows that you need to have warlord selected to get the relic option open for Dire Avengers exarch, Fire Dragon Exarch, Howling Banshee Exarch, Warp Spider Exarch, Shining Spear Exarch and Dark Reaper exarch. If Warlord is not selected those relics stay hidden except for Striking Scorpion exarch and Swooping Hawk Exarch.  So Bug or not, or there was a fault in the user :-)

**Comment by FarseerVeraenthis** [comment]
They should all behave the same, so this is a valid bug since the different aspects behave differently...
