### ISSUE TITLE
Drukhari: Adding tolerated ambition does not show the correct traits

### ISSUE THREAD

**Issue by laiapc** [BSData/wh40k-9e#11125]
**Describe the bug**
When I create a list and make Drazhar warlord, I can't add warlord traits to Archon and Succubus even when paying the stratagem, it only shows "inspiring leader".

**To Reproduce**
1. Go to 'new roster
2. Click on adding forces, add 3 different patrols
3. Add battle size: "strike force 1001-2000 points"
4. Add obsessions to each patrol, 2 kabal of dark heart one cult of strife
5. Add to the first kabal patrol, Drazhar and select warlord and the warlord trait
6. Go to the second kabal patrol, add Archon, select "tolerated ambition -1cp" > it only shows traits brb, and inside "inspiring leader" instead of the list of correct traits.

**Expected behavior**
When selecting the stratagem, the list of traits should be shown to select one, not possible to repeat with other traits in the list

**Device and data (please complete the following information):**
 All devices after update from 26/03

**Additional context**
It was not happening in the previous release

**Comment by FarseerVeraenthis** [comment]
This is fixed on master and will be included in the next update.

**Comment by laiapc** [comment]
Great thanks 😊👏
