### ISSUE TITLE
(T'au) Prototype system that replaces weapon still adds the cost of the original weapon (Thermoneutronic Procector)

### ISSUE THREAD

**Issue by Marconius6** [BSData/wh40k-9e#11122]
**Describe the bug**
I'm not 100% clear on the rules here, but it's my understanding that if a Prototype System replaces a weapon, you shouldn't have to pay the cost of the original weapon. But currently the cost of both seems to be added.

**To Reproduce**
1. Add a Coldstar Battlesuit.
2. Give it a T'au Flamer (which is required), note that point costs goes up by +5pt
3. Give it a Thermoneutronic Projector, note that point cost goes up by an additional +20pt
4. So in total you are now +25pt in cost; but the Projector _replaces_ the Flamer, so it should really only be +20pt, I would think.

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version 2.03.21
 - Release version v9.3.10

**Comment by acebaur** [comment]
It works the same way as relics. You still have to pay the original cost of the weapon it replaces.
