### ISSUE TITLE
Aeldari - Drukhari: Warlord Traits misbehaving

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11121]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** When I have an Archon as my warlord and I also choose a Succubus for an HQ and use the Stratagem: Tolerated Ambition to give her a warlord trait all I see are (BRB) None & inspiring leader. Where did all the cult specific ones go? In particular, I'm using cult of strife. She is not my warlord but when I make her one, then they show up. Also missing are the Book of Rust Charadon rules.
I also use the strat to give my Haemonculus a warlord trait and that works fine.

**Comment by FarseerVeraenthis** [comment]
This is already fixed on master.
