### ISSUE TITLE
Aeldari - Drukhari: Tolerated Ambition is not sufficiently tolerant

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11132]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Selecting strategem "Tolerated Ambition" only gives "Inspiring Leader" as choice for Warlord Trait

**Comment by FarseerVeraenthis** [comment]
This is fixed on Master and will be in the next release
