### ISSUE TITLE
Craftworld Aeldari don't have Dedicated Transports

### ISSUE THREAD

**Issue by Morphius11** [BSData/wh40k-9e#11131]
**Describe the bug**

**To Reproduce**
1. Create a Craftworld Aeldari detachment.
2. Look on the left for Dedicated Transports.

**Expected behavior**
I expect to be able to add a Wave Serpent from Dedicated Transports

**Screenshots**

**Device and data (please complete the following information):**
Windows, 2.03.21, 9.3.10.

**Additional context**

**Comment by Mad-Spy** [comment]
Maximise your Battlescribe window. They hide off the bottom of the screen otherwise.
