### ISSUE TITLE
Aeldari - Craftworlds v156: Wraithseer BL/AML points incorrect

### ISSUE THREAD

**Issue by KalChoedan** [BSData/wh40k-9e#11139]
Aeldari - Craftworlds v156:

Bright Lance and AML on Wraithseer are currently listed as 10pts each. They should be 20pts each. Ref Nachmund p52. 

(Just for clarity, Wraithseer is an FW model, so it didn't get anything in the Codex.)

![image](https://user-images.githubusercontent.com/1786901/163554125-f3d75a8a-e9b3-4164-803b-bb6900fd0c4d.png)
![image](https://user-images.githubusercontent.com/1786901/163554188-2064ebde-904a-4e92-bde1-e608e1cb8c2a.png)

**Comment by williamcaw** [comment]
there was a release after that was issued on February 26
