### ISSUE TITLE
Brotherhood of the Cog issue

### ISSUE THREAD

**Issue by kixxurazz** [BSData/wh40k-9e#11134]
**Describe the bug**

**To Reproduce**
1. add 2 tech-priest dominus
2. add 2 tech-priest enginseer
3. for each tech-priest dominus you are able to add one tech-priest enginseer without taking up a role slot
4. you get an error saying that you have 1 too many HQ slots and its a maximum of 3 (this is not true as you are only using 2 slots)

**Device and data (please complete the following information):**
 windows 10 and also iphone 
 BattleScribe v2.03.21.166

**Comment by AbonShell** [comment]
Add them to the No Force Org selection that's above your HQ's, it'll be a selection called Brotherhood of the Cog, where you can select your tech priest.
