### ISSUE TITLE
Druhkari Stratgam: Tolerated Ambions -1CP on Warhammer 40k v9.3.10 - Dont work

### ISSUE THREAD

**Issue by Arpune** [BSData/wh40k-9e#11130]
Druhkari Stratgam: Tolerated Ambions -1CP
You can select on your HQ that you want to use it, but you cannot select the warlord trat of your Fraktion (Cult, Coven, Kabal).
You can add them, if you shortly make them to your warlord, select the trade and then remove them, but then the Rooster said:
"Succubus cannot have any selection of Warlord Trait (Wych Cult) (hidden)"

**To Reproduce**
1. Create a Druhkari List like (rosz added down below, just remove .txt behind, could not upload otherwise)
2. Click on try to remove and add the warlord trait on Succubus or Archon and see the error above.

**Expected behavior**
Druhkari Stratgam: Tolerated Ambions -1CP description:
Use this stratagem before the battle, when you are mustering your army, if your WARLORD has the DRUKHARI keyword. Select one DRUKHARI CHARACTER model from your army (excluding named characters) and determine one Warlord Trait for it (this must be a Warlord Trait it can have); that model is only regarded as your WARLORD for the purposes of that Warlord Trait. Each Warlord Trait in your army must be unique (if randomly generated, re-roll duplicate results), and you cannot use this Stratagem to give a model two Warlord Traits. You can use this Stratagem once, unless you are playing a Strike Force battle (in which case, you can use this Stratagem twice) or an Onslaught battle (in which case, you can use this Stratagem three times).
So I expect that with that configuration below the rooster should have no errors and the warlord trait should be selectable of your Fraktion (Cult, Coven, Kabal), when Tolerated Ambions is choosen on it.

**Device and data (please complete the following information):**
 - OS: Android and Windows 10
 - BattleScribe version [2.03.21]
 - Release version [v9.3.10]

**Additional context**
[drukhari2000PtsList.rosz.txt](https://github.com/BSData/wh40k/files/8467371/drukhari2000PtsList.rosz.txt)
(just remove .txt from this name to load it into your roster)

Just ask if you have further questions

**Comment by AbonShell** [comment]
Intended behavior. 
![SmartSelect_20220411-181314_Drive](https://user-images.githubusercontent.com/20672472/162842098-538d5433-b379-4518-b39e-db15535bf9d1.jpg)

Your warlord must be of the specific subfaction in order to get it.

**Comment by FarseerVeraenthis** [comment]
![image](https://user-images.githubusercontent.com/23246922/163119663-6c83d784-74d2-4375-8fd2-ecb4384f0171.png)
This is working as intended on the Master version. Suggest you update your data following the next release.
