### ISSUE TITLE
Astra Militarum Balance Dataslate Update

### ISSUE THREAD

**Issue by lewis0460** [BSData/wh40k-9e#11142]
Make changes to AM, DKK and ELY cats for the new "Hammer of the Emperor" and Infantry squad costs found in the new balance dataslate

https://www.warhammer-community.com/wp-content/uploads/2022/04/lBLlqvrttJVgyfhC.pdf

**Comment by Mad-Spy** [comment]
We're already aware of this. It doesn't need a report.
