### ISSUE TITLE
Astra Militarum - Dataslate update for Infantry not correct

### ISSUE THREAD

**Issue by Waz1973** [BSData/wh40k-9e#11148]
The base cost of a Astra Militarum Infantry Squad should now be 60 Points. This is inclusive of ALL wargear (as costs for all wargear for the unit have been reduced to 0) Therefore Vox Caster upgrade and costs of each Special and Heavy Weapon as well as wargear costs for all Sergeant Wargear should be reduced to zero for the unit.

**Expected behavior**

**Screenshots**

![Astra Militarum 1](https://user-images.githubusercontent.com/103832821/163677385-066ab826-a535-45a0-af90-5d65d5fcd771.PNG)

**Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version 2.03.11
 - Release version Warhammer 40K 9.3.11

**Additional context**

**Comment by Technoblazed** [comment]
This wasn't included in the update, it will be in next weeks release.

**Comment by Waz1973** [comment]
Awesome
