### ISSUE TITLE
Salamander Forged in Battle 2nd Tactic needs replacing,

### ISSUE THREAD

**Issue by Waz1973** [BSData/wh40k-9e#11149]
**Describe the bug**
Replace the 2nd part of the Salamander Battle Tactic (the bit about Ap -1 treated as 0) with the new section off the dataslate (Wound rolls cannot be re-rolled)

**Expected behavior**
As above when hovering over Salamander Chapter Tactic .

**Screenshots**

 **Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version 2.03.11
 - Release version Warhammer 40K 9.3.11

**Additional context**

**Comment by Mad-Spy** [comment]
The work hasn't been done yet.

**Comment by craigtubb57** [comment]
Maybe I'm going mad, but this doesn't look like it's done?
Still says AP1 --> AP0, but should be enemy cannot re-roll wounds.

https://github.com/BSData/wh40k/blob/7a04dc4d7236e2b6a7cfc0633b3864dc28bbc868/Imperium%20-%20Salamanders.cat#L1455
