### ISSUE TITLE
Tyranids: Hive Fleet/Stratagem/Hive Tyrant issues

### ISSUE THREAD

**Issue by Waz1973** [BSData/wh40k-9e#11146]
Create a new Tyranid Patrol.

Whatever Hive Fleet you choose it asks you to pick another hive fleet. Leviathan and Kronos for example.

Stratagem - Alpha Leader Beast is not working.

Hive Tyrants on Foot are allowed to swap out 2 different Melee Options for 2 ranged weapons now but this can only be 2 x Heavy Venom Cannons or 2 x Stranglethorn Cannons it cannot be one of each.

Windows 10 Machine
Latest Version of Battlescribe V 2.03.21
Warhammer 40,000 V9.3.11 released 16th April.
*

**Screenshots**
![Tyranids 1](https://user-images.githubusercontent.com/103832821/163675865-8094de3a-8aad-4c3b-a607-3d664473c9b0.PNG)

![Tyranids 2](https://user-images.githubusercontent.com/103832821/163675870-65a6dd31-95bf-43ae-b687-b1b6abfd2f18.PNG)
. 2.03.45]

**Additional context**

**Comment by Waz1973** [comment]
Also when you do choose a hive fleet it does not display the hive fleet specific warlord traits

**Comment by AbonShell** [comment]
With my testing the only thing that is not functioning correctly is weapon selection


Disregard. Alpha beast is also not working. It is not granting an additional WLT, unless you buy it with Hive Predator

**Comment by Waz1973** [comment]
Some monster (Scythed Heirodule) are showing as having the Swarming Masses ability when this ability should only show for units with the correct keyword (Termagants, Hormugants and Gargoyles)

**Comment by Waz1973** [comment]
There is an sumption currently that as GW have not said otherwise that the Leviathan specific abilities from Octarius Rising Tide and the Crusher Stampede Rules in WD471 are all still active as well.

**Comment by AbonShell** [comment]
@Waz1973 please make separate issues for each issue found.

**Comment by Waz1973** [comment]
Separate issue listed.
