### ISSUE TITLE
Tyranids v94 - Hive Tyrant problems

### ISSUE THREAD

**Issue by manuelvalera** [BSData/wh40k-9e#11156]
The Hive Tyrant can't:

- Take Hive Fleet Leviathan warlord trait or psychic power.
- Equip two Heavy Venom Cannons or two Stranglethorn Cannons (the codex permits this loadout).
-

**Comment by GenWilhelm** [comment]
Multiple cannons is duplicated in #11146 
Leviathan options are working correctly on my end. Could you provide a step-by-step on how to reproduce the error?
