### ISSUE TITLE
Tyranids - Parasite of Mortrex Missing Character Options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11150]
**File:** Tyranids.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Parasite of Mortrex doesn’t accept editing. 
Expected: warlord checkbox, warlord traits box, relic box

**Comment by p5freak** [comment]
Why isnt this listed under Issues ? I dont see it there. I wouldnt have opened issue #11151, if i would have seen it.
