### ISSUE TITLE
Tyranids v94 Detachment rules with Hive Tyrants (Rare Organisms rule)

### ISSUE THREAD

**Issue by aurorapar** [BSData/wh40k-9e#11162]
**Describe the bug**
According to the Rare Organisms rule on p. 51, you may take a single Hive Tyrant per detachment. Selecting two Patrol detachments and adding Swarmlord to the first, and either a Winged or default Hive Tyrant instructs the user that they have too many selections of Hive Tyrants.

**To Reproduce**
Create a new Tyranids list with two Patrol detachments.
Add a Swarmlord to the first detachment.
Add a Hive Tyrant to the second detachment.

**Expected behavior**
A single Hive Tyrant per detachment may be included without generating any errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/2294961/163772385-84ea63d0-6614-4ffc-bfe0-63736a47f255.png)

**Device and data (please complete the following information):**
Win10x64 BS Roster Edition 2.03.21 Tyranids data v94

**Comment by GenWilhelm** [comment]
You haven't selected two separate detachments in your screenshot; you've got a single patrol with a "child force" (used for creating multi-faction detachments).

To add a new detachment, you need to make sure the top level of the roster is selected when you click "Add Force", which should look like this:
![image](https://user-images.githubusercontent.com/22036809/163821994-21356a3a-740e-4092-877a-6b892b7353e2.png)
