### ISSUE TITLE
Aeldari  Craftworlds: Yriel and Anhrathe compulsory error

### ISSUE THREAD

**Issue by Kybelor** [BSData/wh40k-9e#11169]
Voidreavers and Voidscarred can only be used as compulsory units, if the entire detachment composes of nothing but Anhrathe units.

Selecting a Patrol or Vanguard with Prince Yriel as the single HQ and warlord, should enable Voidreavers and Voidscarred to fill up those slots, as long as they are the only units chosen.

The datafile doe snot support this.
![anhrathe_error](https://user-images.githubusercontent.com/89249139/164090311-457b2a4e-5088-4d62-a811-08d7566bdd1c.png)

**Comment by Technoblazed** [comment]
Change your Craftworld selection to Corsairs.
