### ISSUE TITLE
Space Marines - Captain melee weapon choice

### ISSUE THREAD

**Issue by shgreen1** [BSData/wh40k-9e#11177]
When choosing a melee weapon for the Captain, the quantity is always 2.  For example, I cannot choose 1 thunder hammer, it automatically chooses 2.

**To Reproduce**
1. Go to 'Captain'
2. Click on up arrow for quantity of thunder hammers
3. See quantity 2

**Expected behavior**
Should be able to choose a single melee weapon

**Screenshots**

**Device and data (please complete the following information):**
 - OS: iOS
 - BattleScribe version [e.g. 2.03.21]
 - Release version [e.g. v212]

**Additional context**

**Comment by acebaur** [comment]
Not a data issue, try restating Battlescribe or reinstalling.
