### ISSUE TITLE
Imperium - Deathwatch: Spectrus Kill Team Eliminator Executioner Round has incorrect profile

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11173]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Executioner Round in Spectrus Kill Teams says to add 2 to the hit roll rather than 1.

The Executioner round wording for the standard Eliminators unit is correct.

**Comment by Mad-Spy** [comment]
The collective and non-collective versions of the Eliminator bolt rifle should be using shared profiles for their profiles but are currently not, hence the divergence.
