### ISSUE TITLE
Furioso Dreadnought

### ISSUE THREAD

**Issue by SimonasBanys** [BSData/wh40k-9e#11178]
![image](https://user-images.githubusercontent.com/31985858/164947262-051c24d9-79f6-4342-871d-42139732fbfc.png)

BattleScribe version: 2.03.21.166

Platform: PC

Dropbox: No

Description: Furiosos dread with the frag cannon should be able to replace frag cannon with melta gun

**Comment by alphalas** [comment]
The data is correct as written; the Furioso standard has a heavy frag cannon and a Furioso fist w/ storm bolter; which it may then replace the heavy frag cannon with a second Furioso fist w/ melta gun, effectively giving it a pair of Furioso fists.

**Comment by SimonasBanys** [comment]
yeah, found how to do it, its just a bit counter intuitive
