### ISSUE TITLE
armour of contempt missing from several imperium datasheets

### ISSUE THREAD

**Issue by flowirin** [BSData/wh40k-9e#11175]
WH40k 9th ed version

for example, the Dark Angels file contains 22 references to "armour of contempt"

Space wolves contains none

same with iron hands.

I have not tested them all, but it is not consistently implemented across chapters.

**Comment by Mad-Spy** [comment]
It's not been implemented in most of the SM Factions yet.

**Comment by flowirin** [comment]
any idea on when it will be?

**Comment by alphalas** [comment]
No. We don't give ETAs.
