### ISSUE TITLE
Tyranids - Hydra Psychic Shriek psychic power does not count towards total psychic powers

### ISSUE THREAD

**Issue by asdok79** [BSData/wh40k-9e#11176]
I have found that the Tyranids - Hydra Psychic Shriek psychic power does not count towards total psychic powers. Other psychic powers display a warning if too many taken but if you add the hydra power no such warning is displayed.

**Comment by CrumpetNinja** [comment]
All Tyranids automatically know their Hive fleet power, and it doesn't count toward the number of powers they are allowed to know.

**Comment by asdok79** [comment]
Thanks for the explanation. Have closed issue.
