### ISSUE TITLE
Space Marines 

### ISSUE THREAD

**Issue by Waz1973** [BSData/wh40k-9e#11186]
List is allowing 4 HQ choices in a Battalion detachment when it should only allow 2-3 Choices.

Space Wolf Battalion
Allowing 
1 Lieutenant
1 Primaris Captain
1 Primaris Chaplain
1 Primaris Lieutenant

**Expected behavior**
Should report you have 2 many HQ choices only allowed 2-3 in a Battalion

**Screenshots**
![Capture](https://user-images.githubusercontent.com/103832821/165496616-940cfa37-faca-4cee-9bbe-8dc52bd94006.PNG)

**Device and data (please complete the following information):**
 Windows 10 Desktop Version
 Version 2.03.21
 Warhammer 40K Data v9,3,12 

**Additional context**

**Comment by Mad-Spy** [comment]
Lieutenants have the "Company Heroes" ability which allows you to have two in a single HQ slot.
