### ISSUE TITLE
Model/Unit/Upgrade flag not properly set in some catalogues

### ISSUE THREAD

**Issue by vflam** [BSData/wh40k-9e#11182]
Hello,

It looks like some catalogues do not properly flag Models and leave Upgrade even for stuff that should be models. I think all units are concerned for catalogues that fail to do it. I added a screenshot of an example of what I think should be type Model but is type Upgrade.

So far I noticed this in the following catalogues:
~~Imperium - Gray Knights~~
Imperium - Inquisition (Acolytes)
Imperium - Astra Militarum

There may be others, I found similar problems on some other catalogues but it may be because they are including Astra Militarum.

![upgrade](https://user-images.githubusercontent.com/17356677/164974599-b70dfe13-07d7-4a97-a3c9-75a3f4ce366a.png)

**Comment by tekton** [comment]
To what end are you wanting these changed? There's not really a substantial change in the battlescribe output itself...

**Comment by vflam** [comment]
I developed a new web application (https://www.newrecruit.eu/app) that works with Battlescribe Data.

I was asked to add a WTC format export for 40k and to respect this format I need this information (entry vs model).

**Comment by maybe-hello-world** [comment]
+1 to this issue :)

**Comment by maybe-hello-world** [comment]
List of Astra Militarum units and models with incorrect flags for @alphalas 

Imperium - FW Death Korps of Krieg.cat:
Death Rider Squadron Commander
Storm Chimera [Legends]
Combat Engineer Squad
Combat Engineers
Engineer Weapons Team
Death Rider Veterans

Imperium - Astra Militarum - Library.cat:
Officer of the Fleet
Hades Breaching Drill
Heavy Mortar Battery
Heavy Mortar
Rapier Laser Destroyer Battery
Rapier Laser Destroyer
Earthshaker Carriage
Medusa Carriage
Arvus Lighter
Veteran w/ Vox-caster
Veteran
Veteran w/ Medi-pack
Veteran w/ Regimental Standard
Veteran w/ Heavy Flamer
Veteran w/ Special Weapon
Veteran Weapon Team
Crassus
Heavy Weapon Team
Hydra Platform
Guardsman w/ Vox-caster
Guardsman
Guardsman W/ Special Weapon
Heavy Weapon Team
Manticore Platform
Marauder Destroyer
Servitors
Servitor (Heavy Bolter)
Servitor (Multi-melta)
Servitor (Plasma Cannon)
Servitor (Servo-arm)
Commissar Severina Raine
Guardsman
Guardsman W/ Special Weapon
Valdor Tank Hunter
Wyrdvane Psyker
Veteran Sergeant
Veteran w/ Lasgun
Veteran Weapon Team
Veteran w/ Shotgun
Veteran w/ Autogun
Tempestus Scion
Tempestus Scion w/ Vox-caster
Tempestus Scion w/ Medi-pack
Tempestus Scion w/ Platoon Standard

Imperium - Astra Militarum.cat:
Knight Commander Pask
Gotfret de Montbard

**Comment by maybe-hello-world** [comment]
List of Inquisition units and models with incorrect flags for @alphalas

Imperium - Inquisition.cat:
Acolyte
Daemonhost
Jokaero Weaponsmith
Lord Inquisitor Hector Rex
