### ISSUE TITLE
Aeldari - Craftworlds: Dark Reaper Exarch BS

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11188]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Dark Reaper Exarch has BS 2+, but should have BS 3+.

**Comment by FarseerVeraenthis** [comment]
Dark Reaper exarch gains improved BS when he has an Exarch Power.
The data is correct.
