### ISSUE TITLE
I do not see how I can make aCrusher stampede army in 9th edition

### ISSUE THREAD

**Issue by wfeijen** [BSData/wh40k-9e#11180]
I hope it is a user Error.
I am working on Android.

**Comment by AbonShell** [comment]
It's no longer a valid choice, and has been removed. https://www.warhammer-community.com/wp-content/uploads/2022/04/XTEpZheWFGC2pWI3.pdf for the source of that information.

**Comment by wfeijen** [comment]
Ah. I see. That didn't last long.
