### ISSUE TITLE
Aun Shi / Aun Va cannot be added to other Sept detachments

### ISSUE THREAD

**Issue by nodecourse2022** [BSData/wh40k-9e#11190]
**Describe the bug**
Aun Shi (Tau) and Aun Va, (Viorla) both units should be able to be added to any sept detachment as these characters are not sept locked.

Presently can only add if you select Tau / Viorla sept. 

Both models have the leadership caste ability that lets them go in any sept.

leadership caste: This model can be included in any Tau Empire detachment (excluding Farsight Enclaves detachments) without preventing that detachment from being a Sept detachment, and without preventing other units from your army from benefiting from a Sept Tenent (pg 55) but this model can only benefit from a Sept Tenet if every <Sept> unit (excluding Supreme Commander units) in your army is from - Tau  (Aun Va) / Viorla (Aun Shi)

**To Reproduce**
1. create a tau force
2. note that in the HQ options Aun Va / Aun Shi are not available
3. Change Sept Choice to Tau - Aun Va appears
4. change Sept Choice to Viorla - Aun Va disappears and AunShi appears.
5. Change Sept to Borkan neither show up

**Expected behavior**
These Character HQ's should be available to any Sept and were in earlier versions of the data file since the new code

**Screenshots**

**Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version [e.g. 2.03.45]: 2.03.21.166 
 - Release version [e.g. v1.2.3]: Warhammer 40,000 9th Edition v212 > Tau Empire v127

**Additional context**

**Comment by AbonShell** [comment]
Not a bug. Until it is FAQ'd it would break battle forged

**Comment by nodecourse2022** [comment]
It doesn't break battleforged.

Battleforged requires that units with a selectable keyword such as <chapter> or in this case <sept> must be drawn from the same <chapter> / <sept>. 

Aun'Va does not have a selectable keyword, Aun Shi does not have a selectable keyword. 

Both abilities state that they do not prevent a detachment from gaining a <sept> tenet - and a chapter that can gain a <sept> tenet is one that is battleforged. 

Nachmund prevents including multiple battleforged detachments with different subfaction keywords ie, partrol <Tau Sept> + Patrol <Borkan Sept>. 

Additionally Nachmund says that 'All unites must have at least 1 faction-keyword in common - and this cannot be 'CHAOS, IMPERIUM, ALEDARI, YNNARI OR TYRANIDS.

If AunVa is an Borkan detachment, he does not break the battleforged requirement of that detachment as per his data sheet, as Aun'va does not have <sept> selectable, its fixed at Tau Sept.
Additionally AunVa will not break the army construction rule - as he still shares the Faction - Tau Empire keyword with all units in the army. 

Pg55 in the tau codex explains that If a detachment is all from one sept it gains a sept tenet and is battleforged - it specifically excludes the Supreme Commander units - as there is only 1 in the whole codex, and only 1 unit can go in the supreme commander detachment. 

Aun'Va and Aun'Shi on their data sheets specifically state they do not break detachments being sept detachments and gaining benefits. 

And the core rules do not prohibit Tau Empire as the common keyword - indeed it cannot otherwise Kroot could never be in a battelforged sept as they do not share a sept keyword at all, and they are only 'Auxilary and not unaligned'. 

And the Nachmund tighter rules for battleforged only apply to models whose data sheets have selectable keywords - which neither Aun'Va and Aun'Shi have.

This will not be clarified by GW - as its fairly clearly from reading the rules. Even without referencing the different books, it is clear from the datasheet ability alone that it is expected as an exception to the normal rules no?

**Comment by AbonShell** [comment]
#10989 this goes into detail as to why it won't be changing.
