### ISSUE TITLE
Imperium - Black Templars: Primaris Sword Brethren should have Combat Squads ability

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11194]
**File:** Imperium - Black Templars.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Primaris Sword Brethren are missing the Combat Squads ability in the list export. Source for them having it: https://spikeybits.com/wp-content/uploads/2021/10/70d28b45-primaris-sword-brethren-datasheet.png

**Comment by Mad-Spy** [comment]
Despite the blurry non-GW source, OP is correct.
