### ISSUE TITLE
Ynnari Not Counting Yvraine Towards Asuryani Req.

### ISSUE THREAD

**Issue by StralisTV** [BSData/wh40k-9e#11197]
For the Ynnari army option under the Craftworlds, Yvraine is not filling the requirement of a Craftworld/Asuryani for the purposes of the new Ynnari rules. She does actually count, as her keywords are "Aeldari, Asuryani, Ynnari". Just a small thing, but figured I'd point it out for the two other people who are playing Ynnari.

![YnnariTestBad](https://user-images.githubusercontent.com/104891945/166642990-a8b9ef09-58d7-4dd2-b434-bce684ad161c.png)

**Comment by FarseerVeraenthis** [comment]
ooohhhh... she must be missing the code that adds the keyword... I'll aim to get it done before next release :+1:
