### ISSUE TITLE
Imperium - Space Wolves: Vanguard Spearhead AoR not available

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11208]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The option for the Vanguard Spearhead Army if Renown options are not displaying for certain chapters (non codex compliment space wolves, blood angl angels, dark angels) and wanted to make sure that this is a bug as they technically can use that Army of Renown rules set. This bug features on my Android Phone and the PC desktop version the same.

**Comment by Mad-Spy** [comment]
This was done.
