### ISSUE TITLE
Primaris Company Champion not showing up on a dark angels army

### ISSUE THREAD

**Issue by robiin1** [BSData/wh40k-9e#11209]
Hi there, when i go to Elites to add the primaris company champion to my Dark Angels force it just isnt there. I checked to see if it was on other space marine chapters and it was on the few that i checked ( like ultramarines). While i was checking i also noticed that there were other Legend models that didnt show up with the dark angels. I'd really appreciate if the primaris company champion could be added :)
Thanks a lot for any help,
Robin
 - OS: Android
 - BattleScribe version [v2.03.25.338]
-Imperium - Adeptus Astartes - Dark Angels v239 by BSData Developers

**Comment by Technoblazed** [comment]
Fixed in 9f03f357
