### ISSUE TITLE
Imperium - Grey Knights: "The Aegis" ability missing from datasheets

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11205]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Grey knight “the aegis” ability is not displaying despite the army been battle forged.

**Comment by tekton** [comment]
It's there as an option under Detachment Bonuses in Configuration
