### ISSUE TITLE
Chaos Knight/Super Heavy Detachment Cost Refund Error

### ISSUE THREAD

**Issue by keatoniousmaximonious** [BSData/wh40k-9e#11212]
I'm not sure if this is a bug with the detachment cost, the detachment refund for the new Chaos Knight list builder, or both, but I built a list with both 6 war dogs and 1 titan, and one with 3 abhorrent-class and the cost was still 3CP with no refund occurring. So, I think both the detachment cost increase to 6CP when a "titanic unit is present" and the new 3/6 CP refund mechanic for knights depending on the number of each class you bring isn't functioning.

**Comment by keatoniousmaximonious** [comment]
And this is with the 9th edition codex data imported

**Comment by Mad-Spy** [comment]
Did you also import the latest version of the GST file? If not, that functionality won't work.

**Comment by keatoniousmaximonious** [comment]
> 

I believe so? I went back an imported the warhammer40k.gst from the same zip folder the new chaos knight data was from and it didn't fix the issue

**Comment by Mad-Spy** [comment]
You're making sure to have a Warlord in the Detachments? You only get the refund once the Warlord is included.

It's all working as expected as long as you have both the updated CK catalogue and the updated GST.

**Comment by keatoniousmaximonious** [comment]
Yeah, warlord marked and everything. Went back to a Death Guard roster just to double check and that's broken for me too. Updated the app, updated the data, using an old non-Chaos Knight roster that worked before and it's still not refunding. 

Im pasting in a snip of my screen. It's Battlscribe 2.03.21, which is what it asks me to install when I use the in app update, and Warhammer 40K v9.3.14, which also doesn't change when I look for data updates.

![Capture](https://user-images.githubusercontent.com/99212387/168700400-9c8f2b72-f5fc-4c30-9a46-077bf55c3f2b.PNG)
P

**Comment by keatoniousmaximonious** [comment]
For reference, it was working on my system at least within the last week and a half, because I took this list made on Battlescribe to an RTT on the 7th with 8CP to start.

**Comment by Mad-Spy** [comment]
I can't find a problem with the actual refund for Knights (which shows on the Detachment Command Cost) but the naming of the detachment isn't changing properly at present.

I did however break it for some other detachment types. We'll get it sorted before release.
