### ISSUE TITLE
Imperium - Imperial Knights

### ISSUE THREAD

**Issue by AbonShell** [BSData/wh40k-9e#11218]
Imperial Knights V88, 9th Edition Codex release, Android app.

- [x] For all knights, has a minimum of 1 Exalted Court Selection when it should be an optional thing for knights
- [x] unable to select warlord after selecting a knight as a character. 
- [x] Stubbers and Meltas cost 20 pts on Armiger Hulls
- [x] No carapace weapon is set by default, throwing an error on adding the datasheet to the roster
- [x] Exalted Court upgrades are not limited to 1 instance per option across the roster
- [x] Defend the realm: "you lost 1 honor point"
- [x] Chivalric Oath: "Dirtuous ability""
- [x] Exalted Court upgrades should not be available on Armigers
- [x] Thunderstrike gauntlets should have a points cost of 0 now
- [x] DOMINUS-Class knights cannot take Sanctuary
- [x] DOMINUS-Class knights cannot take Armour of Saint Ion
- [x] Knight Baron is selectible as an entry on force level
- [x] Datasheets do not get their added wounds for Questor Mechanicus
- [x] Armiger Warglaives list the Armiger Autocannon profile
- [x] Thunderstrike Gauntlets now longer throw stuff at things
- [x] Code Chivalric: never have "les" than 0 Honour points
- [x] WLT Knight Senechal: "diferene"
- [x] Exalted Court: Master Tactician: "thjis"
- [x] CP refund requires 3 Questoris AND 6 Armigers to be present
- [x] Heirlooms is not tied to battle size (reports max 1 at 2k/Strike Force))

**Comment by RespectableJack** [comment]
Also, the Exalted Court upgrades should not be available on Armigers
Thunderstrike gauntlets should have a points cost of 0 now

**Comment by DrTobogganMD** [comment]
Closed via [be2be4f](https://github.com/BSData/wh40k/commit/be2be4f631a46dea0eb4703ea02370b5e0f0ff3b)
