### ISSUE TITLE
40k Chaos Knights 9th

### ISSUE THREAD

**Issue by sjwood13** [BSData/wh40k-9e#11215]
War-Dogs do not trigger changed points values for Chaos Favour of the Dark Gods upgrades.

Also, Helm of Dogs does not appear to be War Dog only

May be an issue with the War Dog ID

**Comment by sjwood13** [comment]
Also, Command cost does not appear to calc correctly

**Comment by Mad-Spy** [comment]
If you're using the unreleased data, you need both the CK file and the GST to ensure everything works.
