### ISSUE TITLE
Can't take Preceptic Node Relic on various characters. 

### ISSUE THREAD

**Issue by OneTrueCorvid** [BSData/wh40k-9e#11210]
Got a single Leviathan Battalion, and the Preceptic Node seems to only be able to be taken on certain characters, even though the rules say it can go on any character. 

Tyranid Prime, Neurothrope, Broodlord, Malanthrope, Tervigon, and Trygon Prime cannot be picked to have the Relic. But both forms of Hive Tyrant, and the Parasite of Mortrex can. The option simply does not exist.

**Comment by Mad-Spy** [comment]
Every model you mention has "Leviathan: Preceptic Node" as a Relic option in the current release data. If you're still not seeing it, then update.
