### ISSUE TITLE
Imperium - Imperial Knights: Not Able to Add Exalted Court Upgrades

### ISSUE THREAD

**Issue by atroiano** [BSData/wh40k-9e#11229]
There is no restriction in the codex around named characters buying exalted court upgrades if the army is a freeblade lance.   Canis Rex should be able to take the upgrades

**Comment by Mad-Spy** [comment]
~~He is a FREEBLADE, and they can't be EXALTED COURT.~~

No, you're right. GW didn't restrict it. Added to #11224

**Comment by atroiano** [comment]
He can if he is 100% can look at page 89 of the new codex.   If he is taken in a freeblade lance, there are no restrictions on him getting exhausted court upgrades.

**Comment by atroiano** [comment]
@Mad-Spy  looks like this issue is happening again after the latest update. do you want me to open a new one?
