### ISSUE TITLE
Imperial Knights v89 - Issue megathread

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#11224]
- [x] Imperial knights codex. All Questoris Knights with Reaper Chainswords should be +6 Strengh, not +4.
The Armigers have +4 and they are correct.
- [x] The stratagems "Heirlooms of the Household" and "Knight Baron" should not be selectable on the Warlord as neither can be used to double up on relics and warlord traits
- [x] The relic Mentor's Seal should allow a fourth teaching to be selected without an error but currently does not
- [x] The Crusader's Rapid-fire battle cannon cost 30 points but should be 0
- [x] Some Relics are available to DOMINUS models but shouldn't be.
- [x] Knight Baron army size constraints aren't working.
- [x] Cunning Commander is granting a free CP.
- [x] Order of the Companions army size constraints not working
- [x] Allegiance-specific heavy stubbers not displayed. #11237 
- [x] Endless Fury Relic needs its ability removing. 
- [x] "Heirlooms of the Household" and "Knight Baron" should not be selectable if your warlord is not IMPERIAL KNIGHTS
- [x] The Knight Preceptor still has the "Mentor" ability on its datasheet but it should not have that ability anymore
- [x] When taking Master of Lore on a Knight other than a Preceptor, it should allow them to take a Knightly Teaching but currently does not
- [ ] The Character (Knight Lance) selection should not appear on other knights once it's selected by the first knight since "Knight Baron" allows them to select a warlord trait (@Mad-Spy: It's not possible to hide a shared entry on only some models, so this can't be done.)
- [x] There's no way to easily de-select a Freeblade Tradition if you stop a model from being a Freeblade. Easiest way to do this is to set the SSEG to min0, then mod it back into min 1.
- [x] Master of Justice doesn't allow selection of Tradition
- [x] Armiger Freeblade Martial Tradition should be per unit, not per model.
- [x] Canis Rex should be able to use Legendary Knight to have an Exalted Court upgrade because GW are dumb.
- [x] Freeblade Lance missing WLT - Echoes from the past and Strat for 2nd Relic Favoured Knight
- [x] Master Tactician ~Exalted court upgrade should allow you to choose an additional Martial Tradition
- [x] Selecting the "Fealty to the Cog" Martial Tradition locks you in to House Krast
- [x] Freeblades should be able to pick a Questor Allegiance (for relic/strat purposes) separately to the rest of the detachment
- [x] Freeblades shouldn't be able to select Glorified History or Fealty to the Cog

**Comment by Technoblazed** [comment]
Just going to add this here too:

- "Heirlooms of the Household" and "Knight Baron" should not be selectable if your warlord if not IMPERIAL KNIGHTS

**Comment by Muck1ng** [comment]
To add to this.
* Endless Fury Relic needs its ability removing. 
* Freeblade Lance missing WLT - Echoes from the past and Strat for 2nd Relic Favoured Knight
* Master Tactician ~Exalted court upgrade should allow you to choose an additional Martial Tradition

**Comment by DrTobogganMD** [comment]
So many bugs! I love it! Working on them now :)

**Comment by ColonialAF** [comment]
"The Knight Preceptor still has the "Mentor" ability on its datasheet but it should not have that ability anymore"

What does this mean? The Preceptor definitely has the Mentor ability, it's what sets it apart.

**Comment by RespectableJack** [comment]
> "The Knight Preceptor still has the "Mentor" ability on its datasheet but it should not have that ability anymore"
> 
> What does this mean? The Preceptor definitely has the Mentor ability, it's what sets it apart.

The Mentor ability for reroll hit rolls of 1 for friendly Armigers is still on the Preceptor's datasheet in battlescribe, but "Mentor" is now a keyword for the Knightly Teachings so it should not have the aura of reroll of 1's to hit for Armigers

**Comment by crag79** [comment]
Blessed Arms- Questor Mechanicus Martial Tradition not showing 
BLESSED ARMS
-Add 6" to the Range characteristic of ranged weapons models with this Martial Tradition are equipped with.
-If a model has this Martial Tradition, the Type of every cognis heavy stubber it is equipped with is changed to Assault 6.
-If a model has this Martial Tradition, the Armour Penetration characteristic of every cognis heavy stubber it is equipped with is improved by 1.

**Comment by AbonShell** [comment]
Current status:

Working on getting freeblade lance exalted court working

Warlord trait for Lance,

Custom houses martial traits

Making sure exalted courts are working properly
