### ISSUE TITLE
Imperium - Imperial Knights: validation error when taking knight baron twice

### ISSUE THREAD

**Issue by ColonialAF** [BSData/wh40k-9e#11228]
**Describe the bug**
When selecting the Knight Baron stratagem for a second knight, there is a validation error that this is not allowed, but it is on Strike Force games or larger.

**To Reproduce**
1. Add two knights
2. Click on Knight Baron for both
3. See error

**Expected behavior**
There should not bea validation error

**Device and data (please complete the following information):**
 - OS: Android and PC
 - BattleScribe version: v2.03.25.338
 - Release version: 9.3.15

**Additional context**
The stratagem specifically states when it can be taken multiple times, and this functionality works for the dollar effect under relics.

**Comment by ColonialAF** [comment]
Also allowed to take it 3 times in Onslaught games. See page 82.

**Comment by Mad-Spy** [comment]
Added to #11224
