### ISSUE TITLE
Imperium - Imperial Knights: Relics should not be available to DOMINUS models

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11223]
**File:** Imperium - Imperial Knights.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** When adding dominus knight to superheavy attachment that has 2 armigers, the cost of the detachment should go to 6 cp as it is Titanic

In addition, Questoris Imperalis knight castellan should have 0 relic choices as most are locked to Questoris chassis and armiger chassis. I can see angels grace (Hawkshroud) and the heart of ion selectable for Knight Castellan

**Comment by Mad-Spy** [comment]
I can't replicate the CP cost issue, but the two Relics shouldn't be available to DOMINUS-CLASS models.

**Comment by Mad-Spy** [comment]
Added to #11224
