### ISSUE TITLE
Imperium - Imperial Knights: Cunning Commander trait gives 1CP

### ISSUE THREAD

**Issue by ColonialAF** [BSData/wh40k-9e#11230]
**Describe the bug**
Taking the Cunning Commander warlord trait grants a free CP automatically. The trait, as written, gives an extra CP in your command phase _only on a roll of _5+_, so it shouldn't be automatic.

**To Reproduce**
1. Go to a knight with warlord or Knight Baron
2. Click on "Cunning Commander" 
3. Look at the cost and the total CP count

**Expected behavior**
I expect to see the cost be "no cost" as the others are and it not grant a free CP immediately. See page 94.

**Device and data (please complete the following information):**
 - OS: Android and PC
 - BattleScribe version v2.03.25.338
 - Release version 9.3.15

**Comment by Mad-Spy** [comment]
Added to #11224
