### ISSUE TITLE
Aeldari - Legends Units: Legends not visible in Roster Builder

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11233]
**File:** Aeldari - Legends Units.catz

**BattleScribe version:** 0.00.00

**Platform:** Android

**Dropbox:** No

**Description:** Multiple units in legends appear to be missing, or are obfuscated to the point of not being findable to me.

Bonesinger is in HQ where instead it is Elite
All variants of legends Autarch are missing
Legends storm guardians are missing
Legends swooping hawks, warp spiders and striking scorpions are missing
Phoenix, Vampire Hunter and Vampire Raider are missing
Firestorm is missing

I would also suggest combining this dataset into the main one, as there are very few so it shouldn't cause any tangible performance issues.
Thanks.

**Comment by FarseerVeraenthis** [comment]
Bonesinger is HQ.
Legends Autarchs have all been replaced by the new one. You can only have one Autarch anyway, and all previous builds are covered by the latest datasheet, so there is no advatange of having more than one entry, expect more work to maintain.
Storm Guardians, Hawks, Spiders & Striking Scorpions never went to legends.
The FW models have all been brought into the main Library and should now be available natively in Craftworlds lists.
