### ISSUE TITLE
Imperium - Imperial knights v89: Questor allegiance shoulder stubbers not giving option to give their specific stubber to Questoris hulls. 

### ISSUE THREAD

**Issue by AbonShell** [BSData/wh40k-9e#11237]
**Describe the bug**
Questor allegiance shoulder stubbers still only just the old heavy stubbers for Questoris class

**To Reproduce**
1. Select either Questoris allegiance
2. Add any Codex Questoris hull
3. Try to select the specific stubber
4. Only heavy stubber

**Expected behavior**
A selection of iether heavy cognis stubber or ironhail stubber depending on allegiance.

**Device and data (please complete the following information):**
 - OS: Android
 - v216, v89

**Comment by Mad-Spy** [comment]
added to #11224
