### ISSUE TITLE
Imperial Knights - Canis Rex Should Be Able To Take Heirlooms of the Household 

### ISSUE THREAD

**Issue by atroiano** [BSData/wh40k-9e#11241]
There is no restriction in the codex for being able to take Heirlooms of the Household for Canis Rex.

**Comment by Mad-Spy** [comment]
If you've got a Github account, please add any new issues you find to #11224.

**Comment by Mad-Spy** [comment]
Also, although you can technically use that strat on him, you can't give him any Relics because named characters are banned from having them, as per the last sentence of the first paragraph on p90.
