### ISSUE TITLE
Imperium - Imperial Knights - Allegiance/Household/Martial Tradition Issues

### ISSUE THREAD

**Issue by CrusherJoe** [BSData/wh40k-9e#11246]
From discussion:
![image](https://user-images.githubusercontent.com/9998385/169562157-1de92a46-d643-4a3a-bffa-99a48ae52fa9.png)
![image](https://user-images.githubusercontent.com/9998385/169562539-d9ab94bd-83ce-44dd-8cf1-7de3174c3211.png)

**Comment by GreenHorde** [comment]
Last bugs for IK Updates
![image](https://user-images.githubusercontent.com/106485021/170880825-450170a0-2f23-4e92-83ab-ac83f02fc989.png)

**Comment by AbonShell** [comment]
I believe it's now fixed
