### ISSUE TITLE
Imperium - Ultramarines Chapter Tactic not being applied to units

### ISSUE THREAD

**Issue by DSdPR** [BSData/wh40k-9e#11243]
As you can see, although Codex Discipline is listed as chapter tactic under the Chapter Selection and the explanation is on the bottom part of the sheet, it would be nice if the Leadership bonus was automatically applied to the unit's numbers and the Codex Discipline ability added to the individual unit datasheets as well, similarly to how it is done for Blood Angles and The Red thirst for instance.
![image](https://user-images.githubusercontent.com/73946304/169518048-2ae984da-d5fc-45c6-a6a5-d0f1318e1b66.png)

![image](https://user-images.githubusercontent.com/73946304/169518283-8633e44e-0ab1-4811-a172-20fce81ce298.png)

**Comment by Mad-Spy** [comment]
To do this would mean adding a modifier to change the Leadership of every Marine unit, which is why it won't be done.

The data is not a replacement for knowing your rules.
