### ISSUE TITLE
Imperial Knights - 2 uses of Knight Baron for Strike Force battle size causes validation to fail

### ISSUE THREAD

**Issue by caseywittner** [BSData/wh40k-9e#11247]
**Describe the bug**
The Knight Baron requisition stratagem says "You can only use this Stratagem once, unless you are playing a Strike Force battle (in which case, you can use this Stratagem twice) or an Onslaught battle (in which case, you can use this Stratagem three times)." However, even when creating a list with a battle size of Strike Force, validation still fails and says "maximum 1."

**To Reproduce**
1. Create a Imperial Knights list
2. Under configuration, set Battle Size to Strike Force
3. Add multiple Questoris chassis models (ex: 1x Gallant and 1x Precptor)
4. Apply Knight Baron stratagem to both models
5. Validation fails with "<<List Name>> has 1 too many selections of Knight Baron (maximum 1)"

**Expected behavior**
This should not cause validation to fail a Strike Force sized games.

**Screenshots**
![IMG_2779](https://user-images.githubusercontent.com/9042187/169572207-91557fed-aee8-44fc-8f00-924ccccbd0cf.PNG)
![IMG_2780](https://user-images.githubusercontent.com/9042187/169572221-7be9286e-8c1d-467e-8c7f-baf6120d3f85.PNG)
![IMG_2781](https://user-images.githubusercontent.com/9042187/169572214-0370e807-b3cd-43a5-81d9-c4a8f245d8dc.PNG)
![IMG_2782](https://user-images.githubusercontent.com/9042187/169572213-d991321f-c825-4487-b804-1b21155a6100.PNG)

**Device and data (please complete the following information):**
 - iOS
 - BattleScribe version 2.03.15
 - Release version v9.3.15

**Comment by Mad-Spy** [comment]
Already reported and included in #11224
