### ISSUE TITLE
The Teeth That Hunger Swipe has no damage

### ISSUE THREAD

**Issue by gluck3d** [BSData/wh40k-9e#11245]
**Describe the bug**
The Teeth That Hunger relic has no damage in its Sweep profile (should be 2)

**To Reproduce**
Add a Knight Rampager  to the army, add The Teeth That Hunger as a relic, check the unit profile

**Expected behavior**
Sweep profile should have damage 2

**Device and data (please complete the following information):**
 - OS: Android
 - BattleScribe version 2.03.25
 - Release version 9.3.15

**Comment by Mad-Spy** [comment]
Fixed in next release.
