### ISSUE TITLE
Dominus class knights incorrect points cost

### ISSUE THREAD

**Issue by SimonasBanys** [BSData/wh40k-9e#11259]
**Screenshots**
![image](https://user-images.githubusercontent.com/31985858/169668180-a430a081-a9c0-4a41-9133-15afaa7845d1.png)

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version 2.03.21
 - Release version 9.3.15

Knight Castellan points cost should be 595+15 if using 2 twin siegebreaker cannons (for a total of 610) rather than 610+15
Knight Valiant should be 585+15 under the same conditions as above rather than 600+15

**Comment by AbonShell** [comment]
You pay for the weapon twice in the case of taking two siegebreaker cannons.
