### ISSUE TITLE
Imperium - Imperial Knights: Knight of the Cog 

### ISSUE THREAD

**Issue by crag79** [BSData/wh40k-9e#11253]
File: Imperium - Imperial Knights.catz

BattleScribe version: 2.03.21

Platform: Windows and Android

Description: For all of the knight classes there is no option to take Knight of the Cog when included in an army along side an Adeptus Mechanicus detachment allowing the Imperial Knight to be taken as any house not just as a Freeblade.

**Comment by williamcaw** [comment]
for Metallica

**Comment by crag79** [comment]
> for Metallica

Metalica/Raven is Knight of the Iron Cog which is now irrelevant from my understanding. Knight of the Cog is an Ad Mech wide strategum that allows you to keep Canticles and Doctrinas.

KNIGHT OF THE COG
For each [Detachment](https://wahapedia.ru/wh40k9ed/the-rules/core-rules/#Detachments) in your army with this ability, you can select one QUESTOR MECHANICUS [Super-heavy Auxiliary Detachment](https://wahapedia.ru/wh40k9ed/the-rules/core-rules/#Super-heavy-Auxiliary-Detachment) in your army. Models in that Detachment gain the KNIGHT OF THE COG keyword.

CANTICLES OF THE OMNISSIAH
If every unit from your army has the ADEPTUS MECHANICUS keyword (excluding AGENT OF THE IMPERIUM, UNALIGNED and [KNIGHT OF THE COG](https://wahapedia.ru/wh40k9ed/factions/adeptus-mechanicus/#Knight-of-the-Cog) units), this unit gains a bonus depending on which Canticle of the Omnissiah is active for your army.
DOCTRINA IMPERATIVES
If every unit from your army has the ADEPTUS MECHANICUS keyword (excluding AGENT OF THE IMPERIUM, UNALIGNED and [KNIGHT OF THE COG](https://wahapedia.ru/wh40k9ed/factions/adeptus-mechanicus/#Knight-of-the-Cog) units), this units characteristics are modified depending on which Doctrina Imperative is active for your army. Each Doctrina Imperative has two effects, an Optimisation effect that improves one of this unit’s characteristics, and a Deprecation effect that reduces one of this unit’s characteristics. When a Doctrina Imperative is active, both of these effects will apply to this unit.

**Comment by nikline** [comment]
> > for Metallica

> Metalica/Raven is Knight of the Iron Cog which is now irrelevant from my understanding. Knight of the Cog is an Ad Mech wide strategum that allows you to keep Canticles and Doctrinas.

He's talking about the iron cog stratagem in the charadon warzone act 1 (p70) :

Metalica - requisition stratagem

Use this stratagem before the battle, when you are mastering your army. Select one House RAVEN unit from your army. That unit gains the canticles of the omnissiah ability and is considered to have the ad mech keyword for the purposes of this ability  (the inclusion of this unit in your army does not prevent ad mech units in you army from using any rules that require every model in your army to have the ad mech keyword).

**Comment by crag79** [comment]
I was asking about the normal Knight of the Cog, because the way the IK codex is worded you can only take a Freelance Blade knight, but the Knight of the Cog is in the Ad Mech Codex.

**Comment by nikline** [comment]
ok, my bad.

**Comment by AbonShell** [comment]
Should be fixed in next release
