### ISSUE TITLE
Chaos Knights - issues

### ISSUE THREAD

**Issue by EvilDeCold** [BSData/wh40k-9e#11265]
File: Chaos - Chaos Knights.catz

BattleScribe version: 2.03.21

Platform: Windows and Android

Description:
1) Knight Despoiler point cost is 400 with default gear, however it is 375 in codex
2) Ironclast Abhorrent-Class Knights are unable to equip Veil of Medrengard artefact, but they should be able to.
3) There seems to be no way to include extra CPs from "Traintoris Lances" rule

**Comment by AbonShell** [comment]
If you look at the codex, it states that the defualt loadouts points is increased by 20 points. Then the 5 pts from the melta gun.

Issue is resolved in next release

Without more information, we can't know what you're talking about, and with that from our testing it's working.
