### ISSUE TITLE
You pay for the weapon twice in the case of taking two siegebreaker cannons.

### ISSUE THREAD

**Issue by SimonasBanys** [BSData/wh40k-9e#11260]
You pay for the weapon twice in the case of taking two siegebreaker cannons.

_Originally posted by @AbonShell in https://github.com/BSData/wh40k/issues/11259#issuecomment-1133765585_

![PXL_20220521_204328002](https://user-images.githubusercontent.com/31985858/169668468-8383a54f-12b8-417d-8050-1e7a7cee7dc1.jpg)
![PXL_20220521_204339795 MP](https://user-images.githubusercontent.com/31985858/169668469-b835ebcb-dd73-45a5-87d4-c7c5617e332f.jpg)

at no point does it say that you pay separate

**Comment by AbonShell** [comment]
You pay for default weapons.

**Comment by SimonasBanys** [comment]
where does it say that?

**Comment by SimonasBanys** [comment]
@AbonShell

**Comment by AbonShell** [comment]
If a weapon has a cost, you pay for it. Whether it's defualt or not.

**Comment by AbonShell** [comment]
Like it literally says it in the second screenshot you sent.

**Comment by AbonShell** [comment]
@SimonasBanys

**Comment by SimonasBanys** [comment]
cool ma bad
