### ISSUE TITLE
Drukhari: Coteries of the Haemonculi

### ISSUE THREAD

**Issue by dalamar666** [BSData/wh40k-9e#11270]
"Coteries of the Haemonculi" does not replace your Coven it just replaces your Obsession of your Coven.  You must still select a coven for your units.  You also still gain access to the Warlord Trait, Relic, and Strat of your Coven. Currently the only way to make this work is to select Obsession twice make one your coven and the other the AoR.  This will allow you to select the Relic and Warlord trait, but will throw the error that Detachment has 1 too many selections of Obsession.

**Device and data (please complete the following information):**
 - OS: [windows 11]
 - BattleScribe version [v2.03.21.166]
 - Release version [9th v216, Drukhari v148]

**Comment by FarseerVeraenthis** [comment]
This AoR is just plain broken atm, it has not been implemented properly.
I will fix it, but it requires quite a lot of work to get it working and sort out all the Relics and Stratagems and so on.
It will be done, just not right this minute :-)

**Comment by FarseerVeraenthis** [comment]
should be fully implemented in the next release :-)
(and is available on Master if you're savvy 😉 )
