### ISSUE TITLE
Court "master of justice" should grant a "martial tradition pick"

### ISSUE THREAD

**Issue by Ithyrrinaz** [BSData/wh40k-9e#11275]
The Exalted court power "Master of justice" do not promt you to pick another martial tradition.

**To Reproduce**
Pick a knight... Give it "Master of Justice" 

Expected: a bulletpoint choice to add a martial tradition. (Not Glorified history)

**Comment by AbonShell** [comment]
Yup, it's being worked on.

**Comment by Mad-Spy** [comment]
Already reported in #11224
