### ISSUE TITLE
House cadmus hunters of Foe

### ISSUE THREAD

**Issue by SimonasBanys** [BSData/wh40k-9e#11272]
**Expected behavior**
House Cadmus Hunters of Foe only applies to melee attacks, doesnt list that.

**Screenshots**
![image](https://user-images.githubusercontent.com/31985858/169871318-a0ad402e-187f-4596-b902-a33d2f807aa6.png)

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version 2.03.21
 - Release version 9.3.15

**Comment by AbonShell** [comment]
Resolved in the next release
