### ISSUE TITLE
Imperium - Imperial Knights v92 - Unable to access Heirlooms of the Noble Houses or Favoured Knight on Warlord

### ISSUE THREAD

**Issue by Viilipurkki** [BSData/wh40k-9e#11282]
Selecting Character (Knight Lance) and Warlord does not allow Heirlooms or the Favoured Knight stratagem to be used. Selecting the Heirlooms of the House stratagem is required to access them and also allows non-Freeblade Lance units to use Favoured Knight.

**Comment by AbonShell** [comment]
Can you give more information on what you mean by the first half. I've rectified the second half for the next release.

**Comment by Viilipurkki** [comment]
When I select both Character (Knight Lance) and Warlord on a knight, the Heirlooms menu doesn't appear and Favoured Knight doesn't appear either.

**Comment by AbonShell** [comment]
What knight are you using.

**Comment by Viilipurkki** [comment]
Knight Paladin.

**Comment by Viilipurkki** [comment]
Also happens with Errant and Gallant.

**Comment by AbonShell** [comment]
oop, I somehow missed putting those on that ones, Thanks! It'll be in the next release!

**Comment by ColonialAF** [comment]
Also doesn't show on Preceptor.

**Comment by Viilipurkki** [comment]
Seems this affects both Armiger types, Crusader, Warden, Valiant and Castellan as well. Also, it seems Valiant is also missing Traitor's Pyre from Questor Imperialis allegiance heirlooms.

**Comment by AbonShell** [comment]
All is fixed and will be uploaded to a branch for the next release.
