### ISSUE TITLE
Imperial Knights Relics

### ISSUE THREAD

**Issue by ATR3US** [BSData/wh40k-9e#11289]
When you select a unit(happened with a Paladin) to be your Warlord it does not show the option for relics, they only open up by selecting heirlooms of the household, and so paying the CP.

Happend using the freeblade lance army of reknown, neither does the favoured knight stratagem(wrong cost btw, should be 2cp) open the selection of relics

**Comment by AbonShell** [comment]
Should be fixed in next release
