### ISSUE TITLE
Imperial Knights - CP Refund Incorrect

### ISSUE THREAD

**Issue by ColonialAF** [BSData/wh40k-9e#11283]
When selecting a warlord in a warforged army where every Knight is in the same house, I only get 3CP refunded under Strike Force, when it should be 6CP.

**Comment by AbonShell** [comment]
Yeah, I noticed that too, but I didn't touch that at all. Waiting on input from other data devs

**Comment by AbonShell** [comment]
Is fixed and slated for next release
