### ISSUE TITLE
Imperium - Imperial Knights: Unable to select Traitor's Pyre

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11298]
**File:** Imperium - Imperial Knights.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Traitor's Pyre relic does not show up for Imperialis Valiant when taken as Warlord or with the stratagem Heirlooms of the Household.

**Comment by AbonShell** [comment]
Fixed in pending pull request
