### ISSUE TITLE
Imperium - Imperial Knights - Paladin has to select rapid fire battlecannon

### ISSUE THREAD

**Issue by dumdrak** [BSData/wh40k-9e#11295]
**Describe the bug**
Paladin has to select rapid fire battlecannon 

**To Reproduce**
create super-heavy detachment, 
add a knight paladin,
view list,
the paladin have not a rapid fire battlecannon
enter the paladin
select the rapid fire battlecannon

**Expected behavior**
The Paladin has a rapid fire battlecannon

**Device and data (please complete the following information):**
 - OS: Android 11
 - BattleScribe version 2.03.25.338
 - Release version 9.3.16

**Comment by AbonShell** [comment]
Read your codex, Rapid fire battle cannon has two options now if you're questor mechanicus or imperialis
