### ISSUE TITLE
Aeldari - Craftworlds: blah, blah, blah, something Phoenix

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11309]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** Building a craftworlds list with a patrol and vanguard detachments. Patrol has Prince Yriel and Corsair void-reavers. If any option other than corsairs is selected as craftworld in the patrol, validation error stating: Aeldari-Craftworlds V157 (Patrol Detachment 0CP) must have 1 more selections of troops (minimum 2). Patrol detachments only require 1 troops selection, and corsair void-reavers can fill that role provided all other units in the detachment are Anrathe, which Yriel (the only other unit in the detachment) is. Upon selecting corsairs as the craftworld (which isn't an option in the codex) the error goes away, however this makes the list invalid for matched play. On top of this the corsair void-reavers do not have the <Craftworld> keyword, so craftworld selection should not be an issue here.

Lastly another validation error which seems to be unique to V157 is: Flyer must have 1 more selections of Phoenix [Legends] (minimum 1). This error occurs two times, presumably due to the fact of there being two detachments present. This error was not present in V156.

**Comment by FarseerVeraenthis** [comment]
Select Corsairs for your Craftworld, the other bug is fixed.
