### ISSUE TITLE
Chaos Knights v69 - House Lucaris

### ISSUE THREAD

**Issue by TropicalRemixed** [BSData/wh40k-9e#11301]
House Lucaris Fell Bond isn't showing up when selected

**Comment by Mad-Spy** [comment]
Do you have at least 3 models in your Detachment? As per p56 of the Codex, you only get a Bond if this condition is met.

If you do have 3 models, please provide full details of your list.

**Comment by TropicalRemixed** [comment]
Ah yes, it shows up only after adding 3 units to the detachment (this doesn't seem to matter for the other subfactions though)

**Comment by Mad-Spy** [comment]
Looks like there are still some issues with the conditions. It'll be sorted in the next release.
