### ISSUE TITLE
Imperium - Imperial Knights: Some WLTs should not be available to Armigers

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11304]
**File:** Imperium - Imperial Knights.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Of the 6 generic warlord traits, the codex limits Armiger-class models to only have access to Cunning Commander, Blessed by the Sacristans or Ion Bulwark. Is it possible to make the other 3 warlord traits not be available to assign to an Armiger?

**Comment by AbonShell** [comment]
fixed in next release
