### ISSUE TITLE
Imperial Knights Issues

### ISSUE THREAD

**Issue by EternalWIP** [BSData/wh40k-9e#11300]
~~1) Warlords unable to select any Relic unless the Hierlooms of the House stratagem is spent.~~
2) Master of Lore working incorrectly on Preceptors, forces selection of Knightly Teaching as if it was any other  viable model
3) Favoured Knight appears on non Freeblade units, ~~Favoured Knight stratagem also incorrectly costed (-1CP should be -2CP)~~

Crossed out ones were fixed in a pending update.

**Comment by Muck1ng** [comment]
Adding to this issue rather than raise another. 

When selecting the Exalted court upgrade Master tactician you should be able to select an additional martial tradition if you are a freeblade.  At the moment you can only select 1.

**Comment by AbonShell** [comment]
Fixed in pending pull request
