### ISSUE TITLE
Bug Report: Imperial knights

### ISSUE THREAD

**Issue by SFCDaddio** [BSData/wh40k-9e#11310]
File: Imperium - Imperial Knights.catz

BattleScribe version: 2.03.15

Platform: Android

Dropbox: No

Latest update broke many things, recorded below:

detachment command cost calculation incorrect

Warlord cannot take any relics

Knight Baron cannot be used more than once

House specific relics missing

**Comment by AbonShell** [comment]
Fixed in next release
