### ISSUE TITLE
Aeldari Bug - Roster

### ISSUE THREAD

**Issue by Tango89er** [BSData/wh40k-9e#11314]
Aeldari (Ynnari) Combat Patrol states that "Flyers must have 1 more selection of Phoenix [Legends] (minimum 1)
![Screenshot_20220527-150106](https://user-images.githubusercontent.com/106371832/170648381-ee8458cf-d953-416c-a69d-72ca19000873.jpg)

**Comment by AbonShell** [comment]
Should be fixed in next release
