### ISSUE TITLE
Imp. Knight issues

### ISSUE THREAD

**Issue by Shoxaju** [BSData/wh40k-9e#11316]
It would seem these issues are unaddressed so here are some of the following issues I've spotted. If I fucked something up on options please tell me how to fix it
![Screenshot_20220527-122338](https://user-images.githubusercontent.com/48237957/170739732-e7bb479a-b42a-44b9-9452-f9158fa6af39.jpg)
![Screenshot_20220527-122329](https://user-images.githubusercontent.com/48237957/170739738-1ce28f33-3610-499e-a8d4-dd26ab5e38c4.jpg)

Chivalric code is required even if a knight is added to another imperial army (code is a mono-faction ability)

Some martial traditions are not able to be selected (pictures attached)

Making all your units freeblades (in my case just the one) should remove the requirement to pick a household (I assume this will get fixed when freeblade is a selectable household option)

Freeblades should be able to pick either an allegiance marital tradition or a freeblade tradition

![Screenshot_20220527-121221](https://user-images.githubusercontent.com/48237957/170739101-dd3fdd12-546c-48f3-b4a2-5c858e33d819.jpg)
![Screenshot_20220527-121026](https://user-images.githubusercontent.com/48237957/170739106-9947e6af-e873-4fb6-a185-318df3513d27.jpg)
![Screenshot_20220527-120736](https://user-images.githubusercontent.com/48237957/170739110-a850600a-063c-49af-a154-9faa23a9e478.jpg)
![Screenshot_20220527-120724](https://user-images.githubusercontent.com/48237957/170739113-005bb230-94e8-4073-a5c0-c1d2e06e46ab.jpg)

**Comment by Shoxaju** [comment]
Also adding as a comment, a check box to denote a freeblade unit acting as an agent of the imperium would help. It could eliminate chivalric code and household choice and automatically make the single unit a freeblade

**Comment by AbonShell** [comment]
You are two, soon to be three revisions out of date

**Comment by Shoxaju** [comment]
Oh that would make sense. I updated it a couple days ago, but I guess it didn't actually update
