### ISSUE TITLE
Imperial Knights: Relics unavailable without using a stratagem

### ISSUE THREAD

**Issue by nickdavies333** [BSData/wh40k-9e#11312]
OS: Android
Battlescribe: 2.03.25
Dataset: 9.3.16

When selecting a Warlord, the Warlord traits are made available but relics are not. When forcing relics to appear by using the 1CP heirlooms of the household stratagem the household specific relic does not appear for house Raven.

**Comment by AbonShell** [comment]
Fixed next release
