### ISSUE TITLE
Chaos Knights v69 - Dreadblade Fell Bond Not Showing when in a Detachment Alone

### ISSUE THREAD

**Issue by blueyedjay1** [BSData/wh40k-9e#11317]
When selecting a Fell Bond for a Dreadblade unit any kind, the Fell Bond will not show up unless another unit with a selected household is in the same detachment.  I tested this specifically with a super-heavy auxiliary detachment.  

According to my understanding of the rules, a single dreadblade in a super-heavy auxiliary detachment should still receive a Fell Bond, as on page 56 of the Chaos Knights Codex it says, "Note that dreadblade units always receive a Fell Bond, regardless of how many models are in their Detachment".

When unit is alone in detachment:
![image](https://user-images.githubusercontent.com/44881279/170740901-b5fd6f7e-4fb5-4def-aaac-7cbedcbd11a5.png)
When another unit is in the detachment:
![image](https://user-images.githubusercontent.com/44881279/170741119-9dde728e-7884-4c5b-b92c-ba036d951376.png)

Windows and Android
BattleScribe version: 2.03.21
Warhammer 40,000 v9.3.16

**Comment by Mad-Spy** [comment]
Will be fixed for next release.
