### ISSUE TITLE
Knights House Rework v95

### ISSUE THREAD

**Issue by AbonShell** [BSData/wh40k-9e#11325]
- [x] House Selection on a per force level
- [x] Being able to have freeblades be a different Questor selection from a force perspective
- [x] having available options change depending on above selections.
- [x] Custom houses being a per force thing as well. Currently they are not.
- [x] Exalted Courts working again.
- [x] heart of ion fixed
- [x] Taranis relic not working
- [x] echoes from the past functionality
- [x] better implementation of fealty of the Cog and glorified history
- [x] canis Rex agent of imperium keyword
- [x] traitor's pyre showing up on armigers

**Comment by williamcaw** [comment]
please also investigate the threshold of cp not being refunded with more then class knights not granting +6 refund

**Comment by Thairne** [comment]
SHA detachments require questor allegiance selections, yet offer none
Warglaives and Helverins have a Stubber selection available that is not for their chosen allegiance
"Alligence" is not a word :D

**Comment by kpasko** [comment]
[INVALID] The below issue should be ignored, this was due to `Army of Reknown` being selected, but `Freeblade Lance` not being selected. As discussed with dev, this can be avoided with a warning that one `Army of Reknown` selection must be made

--- Army of Reknown rules do not allow noble household selection, yet this is currently allowed ---

**Comment by kpasko** [comment]
`Army of Reknown` `Warlord` has no option for `ECHOES FROM THE PAST` warlord trait

**Comment by kpasko** [comment]
`Army of Reknown` list should error on `Lord of War` units that do not have `Freeblade` option selected

**Comment by kpasko** [comment]
`Knight Moirax` does not show options when `heirlooms of the household` is selected

**Comment by kpasko** [comment]
[INVALID] the issue below should be ignored, was due to a stray knight lance selection

--- `Questoris Knight Magaera` should be able to get `Character (Knight Lance)` but this option currently produces and error ---

**Comment by kpasko** [comment]
`Fealty to the Cog` and `Glorified History` are currently not available as martial traditions

**Comment by kpasko** [comment]
`Canis Rex` should have `Agent of the Imperium` keyword

**Comment by AbonShell** [comment]
Taranis relic not working

**Comment by kpasko** [comment]
Selecting `Fealty to the Cog` or `Glorified History` creates a second `Martial Tradition` selection set (as it should) - however, when deselected or another tradition is chosen this box still remains

**Comment by kpasko** [comment]
Canis Rex has no option to be warlord

**Comment by AbonShell** [comment]
All current items here are fixed
