### ISSUE TITLE
Imperial Moirax Knights detachment CP cost

### ISSUE THREAD

**Issue by nickdavies333** [BSData/wh40k-9e#11328]
OS: Android
BS version: 2.03.25
File version: 9.3.17

Taking Moirax Knights does not refund detachment CP in the same way taking Warglaives or Helverins does even though they have the same keyword "Armiger class"

**Comment by Mad-Spy** [comment]
Moiraxes have "ARMIGER CLASS", new Knights have "ARMIGER-CLASS". Notice the hyphen. Until GW make a change to the FW Knights, they don't count towards the CP refund.
