### ISSUE TITLE
Imperial Moirax Knight relics 

### ISSUE THREAD

**Issue by nickdavies333** [BSData/wh40k-9e#11327]
OS: Android
BS version: 2.03.25
File version: 9.3.17

When selecting the -1CP stratagem to give a Moirax Knight a relic the relics do not appear. They are there by default for Armiger Warglaives and Helverins

**Comment by Mad-Spy** [comment]
Moiraxes aren't eligible for the Relics, as they don't have the necessary keyword.

**Comment by AbonShell** [comment]
To add to that they are eligible for *some* relics. But yeah, they don't have the required keywords for a majority of them
