### ISSUE TITLE
Knight Moirax missing ARMIGER-CLASS keyword.

### ISSUE THREAD

**Issue by thenakedgypsy** [BSData/wh40k-9e#11337]
Knight Moirax are missing the ARMIGER CLASS keyword.

**Comment by AbonShell** [comment]
Correct, they don't have it.

**Comment by thenakedgypsy** [comment]
As-in they dont have it in the book? or correct they are missing it?

**Comment by Mad-Spy** [comment]
Well, you are correct that they have "ARMIGER CLASS". What they do not have is the new "ARMIGER-CLASS" keyword that was introduced in the new Codex.

The new one has a hyphen which makes them not the same.

**Comment by thenakedgypsy** [comment]
Thanks for clearing that up :)
