### ISSUE TITLE
Imperial Knights: Moirax missing Armiger Keyword

### ISSUE THREAD

**Issue by Gingalls** [BSData/wh40k-9e#11332]
Good Morning/Afternoon/Evening.

**BattleScribe version:** 2.03.21
**BattleScribe Data:** Warhammer 40,000 v9.3.17
**File:** Imperium - Imperial Knights.catz
**Platform:** PC

**Steps to Reproduce:**

1. Create a new roster selecting Imperium - Imperial Knights v93
2. Select Super-Heavy Detachment
3. Add Battle Size {I used Combat Patrol (0-50 Total PL / 0-500 Points)}
4. Add 2 SEPERATE Armiger Entries (each with ONE Armiger in it)
5. Make ONE Armiger a character (using the **Character (Knight Lance)** Option)
6. Make the SAME Armiger your Warlord (using the **Warlord** Option)
7. Add 1 Knight Moiraxes
8. See that the CP cost of the detachment hasn't been refunded
9. Remove Knight Moiraxes
10. Add 3rd Armiger Entry
11. See that the CP cost of the detachment HAS been refunded

**Description:**
It looks like the Knight Moirax (a Forgeworld Armiger knight) is missing the **Armiger-Class** keyword.  This means it is not counting towards the number of Armiger-Class knights needed to refund the CP when creating a detachment with a warlord in it (for the Imperial Knights army that is).

The Rule that I am referring to is the "Knight Lances" in the Imperial Knights Codex.  The datasheet for the Knight Moiraxes from Forge World does have the **Armiger-Class** Keyword on it.

Please continue the great work and thank you for all you do!

**Comment by Mad-Spy** [comment]
No. They have ARMIGER CLASS, with no hyphen. Until GW  change the FW Knights, they do not count towards the refund.

**Comment by SFCDaddio** [comment]
They have been updated in the app.

**Comment by williamcaw** [comment]
there is no action do do not having a faq posted but using some sleuthing of using official that was changed for keywords
