### ISSUE TITLE
IK Household and Questor oaths

### ISSUE THREAD

**Issue by SimonasBanys** [BSData/wh40k-9e#11343]
**Describe the bug**
Questor Allegiance for Imperial Knights is Detachment wide, rather than indivudual model to gain benefits, same for household

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version 2.03.21
 - Release version 9.3.17

**Additional context**
currently household choice must be made for each Imperial Knights model individually, which even if they are all different gives the household traditions to the knight model based on their household

**Comment by AbonShell** [comment]
Already being worked on, it was a concession that had to be made to have Freeblades work properly
