### ISSUE TITLE
Imperial Knights v95

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#11349]
I am using the master data.

When I select the Mechanicus Exalted Court upgrade Master Tactician, the Martial Traditions available to select are the Imperialis ones but it should be the Mechanicus ones (excluding Fealty to the Cog)

![image](https://user-images.githubusercontent.com/72748875/171902847-f5e09fc0-793b-4458-932c-ca7ed877d4b7.png)
![image](https://user-images.githubusercontent.com/72748875/171902874-9d77ee4f-41a9-49e4-b13c-ba3e9d3b4b56.png)

**Comment by AbonShell** [comment]
Fixed in next release
