### ISSUE TITLE
Tyranids - Maw-Claws of Thyrax requiring Rending claws

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11347]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 3.25.33

**Platform:** Android

**Dropbox:** No

**Description:** Hello, I'm posting on behalf of a friend that doesn't have discord. He pointed out a bug when selecting THE MAW-CLAWS OF THYRAX for his Tyranid Prime. Apparently it gives an error saying that it requires Rending Claws but the Codex doesn't have that stipulation.

**Comment by Mad-Spy** [comment]
Duplicate of #11335
