### ISSUE TITLE
Freeblade Lance bugs

### ISSUE THREAD

**Issue by ATR3US** [BSData/wh40k-9e#11356]
After updating for the new knight hauses rework, i found some issues with the Freeblade lance army of reknown:
-The Relic Bringer of Justice does not appear for any knight.
-Front line fighters Martial tradition does not appear for questor imperialis knights(neither for mechanicum).
-An error appears for repeating the same martial tradition on a unit of armigers.
-Favoured Knight stratagem cant be selected in any knight.

**Comment by AbonShell** [comment]
You cannot select the same martial tradition in your army. 

I will be adding the fact that armiger units gain the martial keyword, and not the model

Front line fighters is fixed next release

Others will be fixed shortly

**Comment by ATR3US** [comment]
For armigers makes it easier to select martial tradition and the freeblade selection on a unit level not on a model level.
Then waiting fir the next one for the rest! Thanks a lot
