### ISSUE TITLE
Imperial Knights

### ISSUE THREAD

**Issue by jesse8472** [BSData/wh40k-9e#11354]
Warlord Trait: Revered Knight not showing as a option once a Knight is upgraded with Knight Baron Strat.
No Martial Tradition when selecting Master Tactician for Exalted Court option.

**Comment by AbonShell** [comment]
What unit are you trying to take the WLT on, as well as what version are you on?

**Comment by AbonShell** [comment]
Not enough information, and unable to replicate. Second half fixed in next release.
