### ISSUE TITLE
Imperium - Imperial Knights freeblade warlord trait

### ISSUE THREAD

**Issue by SimonasBanys** [BSData/wh40k-9e#11365]
**Describe the bug**
IK Echoes from the past warlord trait isnt available to be taken for IK Freeblade characters, which would allow for IK to get either Fealty to the Cog or Glorified History martial traditions

**Screenshots**
![image](https://user-images.githubusercontent.com/31985858/172154231-e4c26aad-3270-49ba-941b-a2e5f877a08d.png)

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version 2.03.21
 - Release version 9.3.18

**Comment by AbonShell** [comment]
Fixed in next release. And just to make sure, you just select freeblade lance

**Comment by SimonasBanys** [comment]
@AbonShell but the freeblade can be a character too, which current config doesnt allow
![image](https://user-images.githubusercontent.com/31985858/172162168-059a8b9c-7ada-4886-9dfd-1bdd4ac3bb71.png)
