### ISSUE TITLE
Dark Angels: Company Veterans in NFO not hidden when "Hide Firstborn Units" is selected.

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#11364]
When "Hide Firstborn Units" is selected and I add a primaris captain of any variety, the firstborn company veterans show up in the No Force Org Slot even though they should be hidden and not appear 
![image](https://user-images.githubusercontent.com/72748875/172062630-9c39bc48-54fc-4446-869f-3f8659090652.png)
![image](https://user-images.githubusercontent.com/72748875/172062636-f18f2253-d080-4714-b55f-4bb25b57c05f.png)

**Comment by FarseerVeraenthis** [comment]
Damnit, someone noticed... OK, OK, I'll fix it... :+1:
