### ISSUE TITLE
freeblades in freeblade lances can be a characters, which current config doesnt allow

### ISSUE THREAD

**Issue by SimonasBanys** [BSData/wh40k-9e#11367]
@AbonShell but the freeblade can be a character too, which current config doesnt allow
![image](https://user-images.githubusercontent.com/31985858/172162168-059a8b9c-7ada-4886-9dfd-1bdd4ac3bb71.png)

_Originally posted by @SimonasBanys in https://github.com/BSData/wh40k/issues/11365#issuecomment-1147402691_

**Comment by AbonShell** [comment]
If you read the book, if it's a super heavy auxiliary detachment, you must be playing a combat patrol sized game for the ability to give a model in that detachment the character keyword.

**Comment by SimonasBanys** [comment]
but then its knight lance and the trait isnt appearing anyway
