### ISSUE TITLE
Aeldari - Drukhari: Coteries of the Haemonculi AoR issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11379]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Thank you for the Coteries of the Haemonculi Army of Renown update from Warzone Nachmund Rift War. May I point out a couple of two minor omissions.

First, the Army of Renown may still also be a member of one of the three standard codex Covens and although the army doesn’t gain the obsession from that Coven they can still access the specific warlord trait and relic associated with that Coven. So, for example an Army of Renown may still be a member of the Prophets of Flesh Coven and gain the Vexator Mask relic. Currently you can only select the Army of Renown or one of the Covens for a detachment. It would be helpful if you could select both the Army of Renown and one of the Covens and thereby be granted access to the specific warlord trait and relic from that Coven in the HQs section.

Second, it would be helpful if the three specific Army of Renown Requisition Stratagems (Rule through Fear, Art of Poisonry and Wealth & Power) could be included as an option with the applicable units, as for example Hekatrix of the Crucible requisition stratagem from the Cult of Strife supplement in the Book of Rust currently is for Wyche units.

Thank you for a fantastic app.

**Comment by FarseerVeraenthis** [comment]
closed, will be in the next release.
