### ISSUE TITLE
Add Kratos Heavy Tank for Marines

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k-9e#11373]
GW just released the 40k rules for it

https://www.warhammer-community.com/wp-content/uploads/2022/06/dgaIUEhxTojLsvsi.pdf

**Comment by Technoblazed** [comment]
Added in https://github.com/BSData/wh40k/commit/65ed4f09ccb9c1f255a914b1e71b6d6fdc2e28bd
