### ISSUE TITLE
Knight Valiant Missing Relic v96

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#11385]
The Knight Valiant can take the relic Traitor's Pyre but the relic is currently not showing up on the Valiant
Also noticed the Castellan is missing the option to take the relic Cawl's Wrath 
![image](https://user-images.githubusercontent.com/72748875/173159527-5fcb5d0c-aa50-491d-b601-00778bfca991.png)

**Comment by AbonShell** [comment]
![Screenshot_20220611-000528](https://user-images.githubusercontent.com/20672472/173171910-7cc95a51-2289-4fd7-aefb-e85953fa0f8d.jpg)
![Screenshot_20220611-000706](https://user-images.githubusercontent.com/20672472/173171943-af628208-b73b-4057-b0f1-26a0ccfbe292.jpg) seems to be working for me on master data.
