### ISSUE TITLE
Imperium - Imperial Knights - Detachment Command Cost

### ISSUE THREAD

**Issue by caseywittner** [BSData/wh40k-9e#11384]
**Describe the bug**
When adding a Detachment Command Cost to a Super-Heavy Detachment that contains a Titanic Unit, the cost is still listed as as -3CP instead of -6CP. Additionally, a Super-Heavy Detachment containing 6 or more Armiger-class models and 1 or more Titanic units should have it's Command Benefits changed to '+6 Command points if your Warlord is part of this Detachment.' However, no Command points are refunded.

**To Reproduce**
1. Go to configuration
2. Click on Detachment Command Cost
3. See inaccurate CP cost and no refund

**Expected behavior**
Adding the Detachment Command Cost to a Super-Heavy Detachment containing Titanic units should change the Detachment Command Cost from -3CP to -6CP. Additionally, An Imperial Knights Super-Heavy Detachment consisting of 6 or more Armiger-class models and 1 or more Titanic units should have it's Command Benefits changed to '+6 Command points if your Warlord is part of this Detachment.'

**Screenshots**
![image](https://user-images.githubusercontent.com/9042187/173111476-49e75305-2152-459e-9fb5-28390dfbc2a1.png)
![image](https://user-images.githubusercontent.com/9042187/173111509-58d1cd79-e115-4bc5-8cc1-814357f242f7.png)
![image](https://user-images.githubusercontent.com/9042187/173111533-586348ed-46a1-4984-b205-8e7218617d5f.png)

**Device and data (please complete the following information):**
 - OS: iOS
 - BattleScribe version 2.03.15
 - Release version v9.3.18

**Additional context**
My above screen shots should leave me with 9CP. I have 6 Armiger models, 2 Titanic Units, with one of those Titanic units, with one of those units being my Warlord. I start with 12CP, the detachment should be -6CP, the detachment bonus should be +6CP, and then I spent -3CP on warlord traits and relics.

**Comment by caseywittner** [comment]
Wondering if, for the Detachment bonuses, the Moiraxes aren't being counted as Armigers because their tags are "Armiger Class" instead of the "Armiger-Class" used by Warglaives and Helverins? In the WH App Moiraxes keywords is "Armiger-Class."

**Comment by AbonShell** [comment]
Yeah, moiraxes don't count for it, and we don't go by what the warhammer app says. We go by what the datasheets and the FAQ's to those datasheets say. As such, Moiraxes don't have the correct keyword to be considered for the detachment cost.

**Comment by williamcaw** [comment]
No action. missing intent. It hurts as secret information or being omitted and having missing intent from the faq on jun 1 2022 of the Armor Compendium. As intent is better then assumption of the change as battle scribe is not a codex replacement. if you want to express and ask if the intent was implied ask [40kFAQ@gwplc.com](mailto:40kFAQ@gwplc.com)

**Comment by caseywittner** [comment]
What about the Detachment Cost issue? Shouldn't a Super-Heavy Detachment with a Titanic unit cost 6CP instead of 3CP?

**Comment by AbonShell** [comment]
@caseywittner what version are you on, cause it's at least diced in v96, and should be fixed in v95

**Comment by caseywittner** [comment]
@AbonShell can this be reopened? After I emailed GW, they updated the IAC FAQ.

![unknown](https://user-images.githubusercontent.com/9042187/173640442-05abe32b-bc63-41b8-9c2a-2c4a86f5d92b.jpeg)

**Comment by AbonShell** [comment]
It's already fixed for the next release @caseywittner

**Comment by caseywittner** [comment]
Thanks!
