### ISSUE TITLE
Custodes v106- Unable to take Prosecutors in Adeptus Custodes list

### ISSUE THREAD

**Issue by DanielPat7** [BSData/wh40k-9e#11388]
As title says, I try and add a group of Sisters of Silence prosecutors to my Custodes list and it says I’m not allowed to take them in a list. i do not have the codex to check if i’m allowed to take these, only the Shadow Throne book from the box set. 
This is only for the patrol size afaik. you can take them in battalion detachments with no issue

**Comment by AbonShell** [comment]
What is the rest of your list

**Comment by AbonShell** [comment]
![SmartSelect_20220611-121431_Drive](https://user-images.githubusercontent.com/20672472/173195980-363e2113-e430-4c0e-af9d-662792d7c8d1.jpg)

**Comment by DanielPat7** [comment]
> ![SmartSelect_20220611-121431_Drive](https://user-images.githubusercontent.com/20672472/173195980-363e2113-e430-4c0e-af9d-662792d7c8d1.jpg)
> 
> 

Ah sorry, only had prosecutors as my troops, again i only had models and rules from the Shadowthrone box
