### ISSUE TITLE
Adeptus Mechanicus v185: "Slaved Systems" Forge World not available

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#11389]
The Adeptus Mechanicus are missing the option to take the custom forge world Slaved Systems Forge World 
![image](https://user-images.githubusercontent.com/72748875/173197309-92fb1234-f131-4782-8023-03532e1f1319.png)

**Comment by Thairne** [comment]
Slaved Forge Worlds are just the standard forgeworlds with a different key word.
They make functionally no different in list building compared to those, therefore it doesnt provide any benefit to give that option during list building.
Simply pick one of those during list building.
