### ISSUE TITLE
Imperium - Imperial Knights - Canis Rex should be selectable as warlord

### ISSUE THREAD

**Issue by ktbh4jc** [BSData/wh40k-9e#11391]
**Describe the bug**
After the last uplift, Canis Rex can not be set as your warlord. 

**To Reproduce**
1. Create an army list with an Imperial Knight SHD or SHAD
2. Add Canis Rex to the list
3. Click the Canis Rex entry
4. Look at the right panel

**Expected behavior**
There should be a checkbox to set Canis Rex as your warlord

**Screenshots**
![image](https://user-images.githubusercontent.com/37726886/173213949-254f0f9b-191a-47da-8a21-5a84fc9092a4.png)

**Device and data (please complete the following information):**
 - OS: Ubuntu
 - BattleScribe version [e.g. 2.03.21]

**Additional context**

Interestingly enough, the inbuilt "View" function does not show the "Categories" header, so I don't see Canis as a character. 
![image](https://user-images.githubusercontent.com/37726886/173213986-98358206-bd8e-46f4-965d-935d4bf7fdd7.png)

Although I do still see it when I export the roster as HTML and open it in the browser. This might be a red herring. 
![image](https://user-images.githubusercontent.com/37726886/173214016-f8cf8f15-7d7e-4e40-9382-2b69bff3000b.png)

(Bug report aside, we appreciate the work getting knights to be playable in Battlescribe. I feel like this has to be the most rule-breaky codex on a fundamental level of any I have seen so far, especially for KnightMech Soup lists)

**Comment by AbonShell** [comment]
Fixed in next release
