### ISSUE TITLE
Does Rhino can transport Wulfen?

### ISSUE THREAD

**Issue by hanliuxin5** [BSData/wh40k-9e#11396]
**Describe the bug**
Rhino now can transport Wulfen?!

**Expected behavior**
I've checked the official app which it shows Rhino can transport it, but I believe it is a bug.

**Device and data:**
 - Space Wolves: 216
 - BattleScribe version: 2.03.25

**Comment by Mad-Spy** [comment]
The Space Marine Codex defines the Transport rules for the Rhino. I suggest you check that.

If you think there's an error in the GW app, this is not the place to report it.
