### ISSUE TITLE
Imperium - Imperial Knights & Chaos - Chaos Knights SHAD should have the option for house traits when 3+ models

### ISSUE THREAD

**Issue by Sweetiebear** [BSData/wh40k-9e#11390]
With the new rules for knights, both imperial and chaos, say that any detachment with 3 or more knight models get access to their House allegiance. So a SHAD with 1 unit of 3 Armigers would qualify. 

Now this only matters for AdMech, where they can use Knight of the Cog (and Knight of the Iron Cog with House Raven) to have the knights without breaking abilities, but it should still probably be fixed. Unless I'm just missing how to make it work

**Comment by AbonShell** [comment]
Imperial knights one was just implemented, minus knight of the iron/cog

**Comment by Mad-Spy** [comment]
This is how it works in the current release.
