### ISSUE TITLE
Imperium - Imperial Knights: v97 bugs

### ISSUE THREAD

**Issue by AbonShell** [BSData/wh40k-9e#11398]
- [x] Freeblade small arms not working for questor imperialis
- [x] house Taranis relic is showing up when not a valid choice

**Comment by kpasko** [comment]
"If this model is included in your army, it must be your WARLORD. If more than one model in your army has a rule to this effect, then one of those models must be your army’s WARLORD."

This text is included in both princeps and high monarch. This seems to allow for both to be taken, so long as one of the knights is the warlord. However currently data requires both knights to be warlord, which is not possible.

**Comment by kpasko** [comment]
Having to add global questor allegiance with no allegiance and a "custom" noble house when running army of renown feels a bit awkward/confusing
