### ISSUE TITLE
Imperium - Imperial Knights: Character validation issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11409]
**File:** Imperium - Imperial Knights.catz

**BattleScribe version:** 2.03.03

**Platform:** Android

**Dropbox:** No

**Description:** In Imperial Knights rosters, the assignment of exalted court remains hidden even if a Questoris is a Character; also, the heirloom "Banner of Macharius Triumphant" remains hidden for the Questoris, even if I use the stratagem that allows me to use an additional relic.

**Comment by AbonShell** [comment]
Can't replicate with data on master.
