### ISSUE TITLE
Castellans of the Rift Ultramarines Successor Chapter is not available

### ISSUE THREAD

**Issue by WigaJiga** [BSData/wh40k-9e#11408]
**Description**
A new successor chapter was introduced for the Ultramarines in the book Warzone Nachmund: Rift War. It has its own chapter tactics, warlord traits, and relics

**Describe the solution you'd like**
The addition of the successor chapter to battlescribe

**Additional context**
details of the chapter can be found here https://www.youtube.com/watch?v=lwhlEEIv9XU

**Comment by michaelmulligan** [comment]
Rules for this chapter (WT, Relics, Stratagems) can be seen here - https://wahapedia.ru/wh40k9ed/factions/space-marines/castellans-of-the-rift#Codex-Supplement:-Castellans-of-the-Rift
