### ISSUE TITLE
Iron Hands and Salamanders not showing battle-forged army rules and armour of contempt

### ISSUE THREAD

**Issue by TheSadBeaver** [BSData/wh40k-9e#11405]
Iron Hands and Salamanders units are not showing the battle-forged army rules such as: 
- The Flesh Is Weak chapter tactic, 
- Calculated Fury super doctrine, 
- Armour of Contempt, 
- Objective Secure on troops slots
- Forged in Battle chapter tactic
- Promethean cult super doctrine.

**Comment by acebaur** [comment]
Several of these are already in the data. Also Battlescribe is not a requirement for your codex.

**Comment by TheSadBeaver** [comment]
I meant to say that it's not showing in the rules line for units in the output, when you print your army, as opposed to say, for example, Blood Angels like in the attached picture. 

![blood angels](https://user-images.githubusercontent.com/21087388/174503661-43281bc5-da8c-4ec5-8127-da5ba1088b11.png)

![iron hands](https://user-images.githubusercontent.com/21087388/174503712-c034e28b-09e2-4947-b475-7eb4a2010937.png)

**Comment by TheSadBeaver** [comment]
![iron hands rules](https://user-images.githubusercontent.com/21087388/174503772-de7cf254-f6e0-450a-ad67-6de482a3448b.png)

**Comment by AbonShell** [comment]
What he's saying is, battlescribe isn't a replacement for a codex.
