### ISSUE TITLE
Imperial Knights - Model can be given a relic when not a character. 

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11406]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** If a relic is not selected for the Warlord, another model can be given a relic without being a Character and without using the Heirlooms of the Household strategem.

**Comment by AbonShell** [comment]
You know, they shouldn't, you're right.

**Comment by AbonShell** [comment]
Fixed in next release
