### ISSUE TITLE
Imperial knights stuff

### ISSUE THREAD

**Issue by Weirwood369** [BSData/wh40k-9e#11412]
I should be able to select a knight as a warlord even if they are not a character. 

An imperial knight questoris class warlord  should get a +3 command point refund even in a super heavy auxiliary detachment

**Comment by Mad-Spy** [comment]
We don't implement non-character warlords, as only characters can take Warlord Traits and Relics.

**Comment by Weirwood369** [comment]
But the game does not require your warlord to be a character, just to get warlord traits and relics.  With the new rules there may be people who prefer to save their command points than spend them on the relics and warlord traits that are no longer free

I do not see a good reason for the app to not give the full set of choices that the game gives even if they are not the optimal choices to make

**Comment by Mad-Spy** [comment]
You will not be forced to spend the CP to take the WLT or Relic, even if you do make the model a Character. We will not be implementing non-Character warlords.
