### ISSUE TITLE
[Anon] Bug report: Imperium - Adepta Sororitas v197: Celestian Sacresants incorrect costs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11419]
**File:** Imperium - Adepta Sororitas

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Celestian Sacresants are at 15ppm, should be at 14ppm as per the Munitorum Field Manual 2022 Mk II

**Comment by CrusherJoe** [comment]
Got it, thank you for pointing it out!
