### ISSUE TITLE
Imperium - Grey Knights: Shield of Humanity not allowing WLT selection

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11425]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** When using the "shield of humanity" stratagem, the list for warlord traits does not appear to allow one to be selected.

**Comment by thatryan55** [comment]
I think this bug is still in effect.

**Comment by tekton** [comment]
> I think this bug is still in effect.

That's true with the released data, it will be fixed in the next release!
