### ISSUE TITLE
Aeldari - Craftworlds: Non-character unit points not updated

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11428]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 9.04.01

**Platform:** Android

**Dropbox:** No

**Description:** Hi,

Points aren't updated. Characters should be fine, rest is still old PTS.

**Comment by FarseerVeraenthis** [comment]
Yeah, seems my diff was duff 😆 
I'll get to it :+1:

**Comment by FarseerVeraenthis** [comment]
I should have closed this with my last commit.
The updated are done, just waiting for the next release :+1:
