### ISSUE TITLE
Warhammer 40,000 War zone Nephilim warlord trait and relic Command Point issue

### ISSUE THREAD

**Issue by wizard311** [BSData/wh40k-9e#11424]
**Describe the bug**
There are no longer free warlord traits or relics all cost 1 command point per.  Also characters with built in warlord traits need option to select/deselect said warlord trait to save Command points

**To Reproduce**
Necrons: Selecting Silent King with no ability to remove warlord trait forces -1 CP in tournament rules.
In the same list selecting Overlord then adding warlord trait cost 0cp for "first warlord trait" using rarefied nobility to produce the -1CP.

**Expected behavior**
Being able to use Silent King and other named characters and be able to not use built in warlord trait.

Selecting any warlord trait or relic cost -1 CP respectively regardless of how many have been selected

**Device and data (please complete the following information):**
 - OS: IOs, Android, Windows
 - BattleScribe version v2.03.25.338
 - Release version Necron v104

**Additional context**
Will be using battlescribe for 40K to enter tournaments and local games using ITC rules and need starting CP to be accurate.

**Comment by Technoblazed** [comment]
This isn't added for every army yet:

https://github.com/BSData/wh40k/issues/11397
