### ISSUE TITLE
Imperium - Space Marines: Points for Lasfusils in Eliminator Squad not updated

### ISSUE THREAD

**Issue by R0ot2U** [BSData/wh40k-9e#11436]
File: Imperium - Space Marines.cat

BattleScribe version: 3.25.38

Platform: Windows

Dropbox: No

Description: Primaris Eliminator Las fusils still cost 5 points for the Eliminator Squad per model (sergeant and regular models). They became free in the latest points update.

https://www.warhammer-community.com/wp-content/uploads/2022/06/mYZ4b5gZUiktj4GI.pdf

**Comment by acebaur** [comment]
Update your data.

**Comment by R0ot2U** [comment]
Oops yes! Thanks @acebaur I had updated but looks like still had the old file. Will wait for data service to be available and then purge and readd
