### ISSUE TITLE
Imperium - Ultramarines: Vet Intercessor Sgt should be able to take melee and pistol in rifle-armed squad

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11431]
**File:** Imperium - Ultramarines.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Veteran Intercessor Squad Sergeant is unable to take a pistol option and melee option as part of a rifle equipped squad.
1. Unit Weapon Options set for Bolt Rifle/Auto Bolt Rifle/Stalker Bolt Rifle
2. Select Sergeant Tab
3. Melee Weapons set for Astartes Chainsword/Power Sword/Thunder Hammer/Power Fist
4. Replace Rifle set for Bolt Pistol/Plasma Pistol/Hand Flamer

**Comment by Dunamis55** [comment]
Duplicate of the 2x pistols + 1x melee option of #11124
