### ISSUE TITLE
Aeldari - Drukhari: Relic Question 

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11434]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Drukhari HQ characters cannot be given obsession specific relics unless they are made the warlord of the entire force. 

For example: A Cult of Strife Succubus can not be given the Dark Lotus Toxin unless she is the warlord.
                      A Kabal of the Obsidian Rose Archon can not be given the Armour of Misery unless he is the warlord.

**Comment by AbonShell** [comment]
I *believe* that's indended with how the relic rules work. 
![Screenshot_20220625-064639_Drive](https://user-images.githubusercontent.com/20672472/175770280-161ab831-b60c-4d2a-bcfc-4de449ac6b3e.jpg)

**Comment by ghost** [comment]
Had to create an account sorry!

If you look specifically at the Cult of Strife Supplement though it states: 
'If your army is led by a CULT OF STRIFE WARLORD, you can, when mustering your army, give one of the following Artefacts of Cruelty Relics to a CULT OF STRIFE CHARACTER model from your army. Named characters cannot be given any of the following Relics.'

Which would suggest that those relics from the cult of stife supplement should be added into the artefacts of cruelty for all cult of strife characters within the specific detachment but limited to only being able to take one between all of them, it doesn't HAVE to be the warlord. I may be wrong please let me know if I am but that is how I interpret it.

**Comment by ghost** [comment]
Sorry to add on more but, your screenshot is specifically from the Real Space Raid section. If you don't take a Real Space Raid I don't believe there are the restrictions as when you take 2 detachments in a regular Drukhari army. The only rule placed on if you can give the Archon of the Obsidian Rose his unique chapter relic is 'KABAL OF THE OBSIDIAN ROSE ARCHON model only.' there is no mention about having to be a warlord to access the relic.

The regular relic wording in the book just quotes:
'If your army is led by a DRUKHARI WARLORD, you can, when mustering your army, give one of the following Artefacts of Cruelty to a DRUKHARI CHARACTER model in your army. Named characters cannot be given any of the following Relics.' Which again shows that the character you give the Artefact of Cruelty too doesn't need to be the warlord, only have the character keyword.

Again I may be wrong, please do let me know if I am!

**Comment by Valorcalls** [comment]
That section is not directly in reference to RSR, just in reference to cult/kabal/coven specific traits, rather then the more general ones for regular relics you links.

**Comment by Mad-Spy** [comment]
All 9th edition Codexes restrict subfaction relics to armies whose Warlord is from that subfaction.

**Comment by FarseerVeraenthis** [comment]
For the first part of the question, you can give an Archon the relic mentioned if they are not the Warlord, however, your warlord must be from the correct kabal to unlock the relics in the first place. You can test this by building a Patrol detachment with two Archon, one as the warlord, the other can then select faction specific relics as necessary.
For the second part of the question, page 53 of the codex, the very first paragraph of the text pasted earlier states that you must have the correct Warlord to have access to faction specific relics.
