### ISSUE TITLE
Imperium - Space Marines: <CHAPTER> tag used instead of specific Chapter in ability description

### ISSUE THREAD

**Issue by GinSoakedBoy** [BSData/wh40k-9e#11439]
**Describe the bug**
Many of the character and other unit abilities, psychic powers, litanies etc will list `<CHAPTER>` rather than the specific chapter e.g. ULTRAMARINES.

**To Reproduce**
A good example of this is Chief Librarian Tigurius. His abilities all list ULTRAMARINES as the chapter, but his Psychic abilities (which are not chapter specific to Ultramarines) all have `<CHAPTER>` instead.

![Chapter](https://user-images.githubusercontent.com/13789412/175789751-983e709e-6777-4945-b988-f5ce8412702e.jpg)

**Expected behaviour**
An example of expected/preferred behaviour for the Combat Restoratives ability be:

At the end of your Movement phase, this model can heal one friendly ULTRAMARINES INFANTRY or ULTRAMARINES BIKER model whose unit is within 3" of it. That model regains up to D3 lost wounds. Each model can only be healed once per turn.

It is currently:

At the end of your Movement phase, this model can heal one friendly `<CHAPTER>` INFANTRY or `<CHAPTER>` BIKER model whose unit is within 3" of it. That model regains up to D3 lost wounds. Each model can only be healed once per turn.

![Combat Restoratives](https://user-images.githubusercontent.com/13789412/175789792-0bc49d8a-68ee-4b32-a14c-e17c05eb1854.jpg)

**Device and data (please complete the following information):**
 - OS: MacOS, Windows 10
 - BattleScribe version 2.03.21
 - Release version 9.4.1

**Comment by acebaur** [comment]
Firstly this the is the wording in the codex. Battlescribe is not a replacement for your codex.
