### ISSUE TITLE
Stratagems unavailable for Tau Empire

### ISSUE THREAD

**Issue by DavidMidwinter** [BSData/wh40k-9e#11442]
**Describe the bug**
After updating data following the recent points changes, I have been unable to add stratagems to my Tau Empire lists; the category for Stratagems is not present. It is still present for other factions such as Space Marines, Aeldari, Necrons and Adeptus Mechanicus. See attached screenshots.

**To Reproduce**
1. Create a new roster
2. Select 'Warhammer 40,000 9th Edition v221'
3. Scroll down and select 'T'au Empire v131'
4. Select 'Unbound Army (Faction)'
5. Confirm roster creation (tick button, top right corner)
6. Observe

**Expected behavior**
Stratagems tab should be visible

**Screenshots**
1. Aeldari roster with Stratagems tab visible
![Screenshot_20220626-002815](https://user-images.githubusercontent.com/45365343/175793492-c2574b6b-9f24-4b4f-8340-27f903470d53.jpg)

2. T'au roster with no visible Stratagems tab
![Screenshot_20220626-002742](https://user-images.githubusercontent.com/45365343/175793496-22a3011d-700f-41d1-a980-c00388dc65e6.jpg)

**Device and data (please complete the following information):**
 - OS: Android 11
 - BattleScribe version 2.03.25
 - Release version v221

**Additional context**

**Comment by AbonShell** [comment]
The strats show up on a character.

**Comment by AbonShell** [comment]
![SmartSelect_20220625-201203](https://user-images.githubusercontent.com/20672472/175794325-514f3225-ce4f-4297-a2fd-cfbf18d4a4a3.jpg)

**Comment by DavidMidwinter** [comment]
Oh, that makes sense. Thank you
