### ISSUE TITLE
Bug report: Imperial Knights - Knight Baron

### ISSUE THREAD

**Issue by Rockwejd** [BSData/wh40k-9e#11441]
Description of error:
When selecting knight baron option roster error "Knight #### must have 1 more selections of warlord (minimum 1)" appears.  This error appears even if a warlord is already selected.

**To Reproduce**
1. Construct an Imperial super heave detachment.
2. Select 1 knight to be a character
3. Select said knight to be warlord
4. Select different knight to be a knight baron
5. roster error should indicate need for a warlord to be selected

**Expected behavior**
When selecting the knight baron option the only roster error should be the requirement to select warlord trait

**Device and data (please complete the following information):**
OS: android
Battle scribe Version: 2.03.25
Release version: Warhammer 40k 9th edition v221
Release version: Imperial Knights v98

**Comment by AbonShell** [comment]
![Screenshot_20220625-201637](https://user-images.githubusercontent.com/20672472/175794378-02eb0b62-212a-4b3d-979d-c76a93ab1a01.jpg)
![Screenshot_20220625-201630](https://user-images.githubusercontent.com/20672472/175794379-c90110fc-0694-4172-8ba0-8e46362708ee.jpg)

Unable to replicate

**Comment by AbonShell** [comment]
![Screenshot_20220625-201615](https://user-images.githubusercontent.com/20672472/175794395-70c6ca2a-d724-426a-b582-69eade225725.jpg)

**Comment by AbonShell** [comment]
Fixed in next release
