### ISSUE TITLE
Imperium - Astra Militarum: Sniper Rifle cost not updated for Infantry Squad

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11450]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** As far as I know, basic Infantry are supposed to pay 0 for the Sniper rifle.

**Comment by Mad-Spy** [comment]
Fixed in next release.
