### ISSUE TITLE
[Tyranids] Can't choose "Combat Patrol" in Battle Size with Patrol Detachment and Nephilim Gametype

### ISSUE THREAD

**Issue by Grouiiik** [BSData/wh40k-9e#11451]
**Describe the bug**
In a Patrol Detachment, when adding a Battle Size, Combat Patrol appeared, but with the error : "Battle Size cannot have any selections of 1. Combat Patrol (0-50 Total PL / 0-500 Points) (hidden)."
When choosing Incursion or Strike Force, Combat Patrol disappeared.

**To Reproduce**
1. Create a Tyranids Patrol Detachment roster
2. Set Nephilim Gametype
3. Add Battle Size

**Expected behavior**
I should be able to choose Combat Patrol in the Battle Size list.

**Screenshots**
![Sans titre](https://user-images.githubusercontent.com/12986220/175809487-0b6d5214-844a-4a9b-8249-9a136a180f80.png)

**Device and data (please complete the following information):**
 - OS: Windows and Android
 - BattleScribe version 2.03.21.166 (Windows) and 2.03.25 (Android)
 - Release version v9.4.1

**Comment by Technoblazed** [comment]
The nephilim pack only supports incision and strike force missions.
