### ISSUE TITLE
Chaos - Death Guard: Plagueburst Crawler entropy cannon cost not updated

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11455]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 9.04.01

**Platform:** Android

**Dropbox:** No

**Description:** Death Guard Plague Burst Crawler Entropy Cannon points are incorrect, showing 10 instead of 5
Warlord traits and relics are not being charged CP per new Nephilim rules

**Comment by Mad-Spy** [comment]
Each cannon is 5 points, and the model has two of them, so 10pts.

The other stuff isn't implemented yet, as per #11397
