### ISSUE TITLE
Aledari Craftworlds - re-add Amallyn Shadowguide

### ISSUE THREAD

**Issue by LoganBarnett** [BSData/wh40k-9e#11467]
## Description

Amallyn Shadowguide is (as far as I can tell) still a legal unit to take. It was removed in c694ca1dd3e07b62ed5673192c1f209b548bfd60 as part of the 9E Aeldari Codex changes. This manifests in v157 of the Aeldari Craftworlds catalogue, and a quick peek around tickets here doesn't indicate there are changes in progress.

## Reproduction
1. Create a `Aeldari - Craftworlds` roster.
2. In `Configuration` -> `Craftworld Selection`, select `Beil Tan: Swordwind`.
3. Go to the `Elites` section, and add a new unit (if on mobile) or just view the dropdown.
4. Observe that `Amallyn Shadowguide` is not selectable.

I'm guessing reproduction steps for the desktop version. BattleScribe no longer works for me, I think due to a bug in the ARM64 JVM that Apple ships with.

## Expected Behavior

`Amallyn Shadowguide` should be selectable in the `Elites` slot, when the `Craftworld Selection` is `Beil Tan: Swordwind`.

## Device and Data
- iOS 15.5
- BattleScribe v2.03.45 (latest)
- Warhammer 40,000 Data v9.4.1

**Comment by LoganBarnett** [comment]
I have committed some changes in https://github.com/LoganBarnett/bsdata-wh40k/tree/11467-re-add-amallyn-shadowguide but it is untested so far. I need a little time to verify my changes since I've both never done it before and don't have a functional desktop BattleScribe (new macOS/aarch64 JVM bug, I think).

If you'd rather make the changes yourself, I won't take offense :)

**Comment by FarseerVeraenthis** [comment]
There is no datasheet in the current codex for Amallyn Shadowguide, she is not in the Legends PDF, she is not Forgeworld, therefore, she is not a valid option.
Please run the logic that suggests she is a valid option and tell me where I can find her latest datasheet.

**Comment by LoganBarnett** [comment]
Btw, thanks for maintaining this data! I spend many hours squeezing points out of my Aeldari lists - and I owe that to your labors here :)

Amallyn Shadowguide appears in the [Warhammer Quest: Blackstone Fortress board game](https://www.games-workshop.com/en-US/Warhammer-Quest-Blackstone-Fortress-2018-eng). It's hard to link to a specific area, but the browser's search will show her listed in there. Additionally, the product description states the box includes "A 16-page booklet of datasheets for using the included miniatures in games of Warhammer 40,000.".

Attached is a screenshot of the datasheet. I cannot find a freely available PDF.
![amallyn-shadowguide-datasheet](https://user-images.githubusercontent.com/27005/176050203-8a7596b6-09da-4c80-be35-d000476d5072.jpg)

This would've been great material to have in [Psychic Awakening Faction Updates](https://www.warhammer-community.com/wp-content/uploads/2022/04/XTEpZheWFGC2pWI3.pdf) but material on the Blackstone Fortress is sadly absent.

I agree this isn't a slam dunk. I can't find official material that would say the datasheet is valid _other than the Blackstone Fortress description itself_. The 8E FAQ for Craftworlds did include a mention of Amallyn Shadowguide, but it also modified the datasheet.

My last, desperate defense of my position is taken from the [Catalog Guidelines of this project](https://github.com/BSData/catalogue-development/wiki/Catalogue-Guidelines), stating:

>  ...it's better to leave space for illegal builds than to throw errors on some legal ones.

I suggest that we honor the spirit of the guideline in that if we aren't certain if we can or cannot include the datasheet, we should allow it to be included and allow players and TOs to determine whether or not the datasheet is legal in absence of any additional information. This way players can still benefit from BattleScribe's wonderful compilation of rules, points calculations, etc. If it would be a helpful compromise, could we apply a similar filter that is used now for Legends? As such, we could have a `[Blackstone Fortress]` suffix like we do `[Legends]`, and that would at least make it clear to users that this isn't standard material from a codex?

**Comment by LoganBarnett** [comment]
I think this is the slam dunk I was looking for. The 40K mobile app has her datasheet available:

![399F1FA1-9FEE-4D83-8832-1FC93553B396](https://user-images.githubusercontent.com/27005/176059238-a59354d7-573a-47e4-ab73-270bf49b8555.png)

Points values here are current as of last week's Nephilim changes - so I hope we can consider this to be a good official source :)

**Comment by FarseerVeraenthis** [comment]
Grand. She is still an awful choice for an Elites slot, but I can add her in.
Since I don't have access to the full datasheet on the App, please can you take a shot of her keywords as listed on the WH40K app and I'll bung her in the data :+1: 😸

**Comment by LoganBarnett** [comment]
Thanks!

In addition to the screenshot above:

weapons:

![D31E3E04-9979-4722-B0C3-22BDA034F77E](https://user-images.githubusercontent.com/27005/176704998-d4c4c5bf-b020-47d0-8a89-1ea6cbacec27.png)

Abilities 1/2:
![5A827DD4-20B4-4AE8-A04D-E7DE53FEAE51](https://user-images.githubusercontent.com/27005/176705088-19a929e2-f2cf-4abf-b0d5-85308170d728.png)

Abilities 2/2 and keywords:
![E28DD68A-A7C3-4953-B059-4EA331F7D908](https://user-images.githubusercontent.com/27005/176705200-401d057d-bfc4-49a5-b718-2b1cfab36e7c.png)

I agree she doesn't seem like a stellar choice given all the awesome Elite choices we have. With the Nephilim changes, I want to see if she's good to use for the Aeldari scouting secondary. I imagine it's easy to hide a single model!!
