### ISSUE TITLE
Imperium: Adeptus Sororitas Celestian Sacreasants Points incorrect

### ISSUE THREAD

**Issue by rashius87** [BSData/wh40k-9e#11476]
Sisters of Battle Celestian Sacreasants points are at 15 instead of 14 Points per model.

![image](https://user-images.githubusercontent.com/76053253/175952770-6aed7bb1-7d2e-4876-8d92-1e2a95d03758.png)
![Sacreasants PTS Jun 2022](https://user-images.githubusercontent.com/76053253/175952956-2eb09eb9-0668-4f71-a496-593c2b2f67bc.PNG)

**Comment by Mad-Spy** [comment]
Fixed in next release as per #11444
