### ISSUE TITLE
Warhammer 40K Aedari Points are not updated

### ISSUE THREAD

**Issue by SaskOutrider** [BSData/wh40k-9e#11471]
This is what the points should be:

Maugan Ra | 160
Dire Avengers | 13
Fire Dragons | 23
Howling Banshees | 19
Striking Scorpions | 18
Swooping Hawks | 20
Warp Spiders | 22
Windriders with Scatter Laser | 30
Falcon Vectored Engines | 20
Fire Prism | 165
Fire Prism Vectored Engines | 20
Night Spinner Vectored Engines | 20
Wave Serpent | 145
Wave Serpent Vectored Engines | 20
Crimson Hunter | 175
Crimson Hunter Exarch | 175
Hemlock Wraithfighter | 215

**Comment by FarseerVeraenthis** [comment]
These are updated on the Master branch and will be in the next release.
