### ISSUE TITLE
Chaos Marines point update

### ISSUE THREAD

**Issue by Jhotaro25** [BSData/wh40k-9e#11483]
**Describe the bug**
Incorrect point totals and stat line on chaos marine units. Specifically khorne berserkers

**To Reproduce**
1. Go to Chaos Space Marines Roster
2. Click on Elites
3. Scroll down to Khorne Berserkers
4. See that they are 17pts per model in stead of 22 as well as not having updated statline with 2 wounds and 5 attacks 

**Expected behavior**
Update rosters with current point totals from Field Manual

**Screenshots**
![image](https://user-images.githubusercontent.com/108304170/176038670-55724281-ca41-4cbc-a70a-9b625e9ac1f7.png)
![image](https://user-images.githubusercontent.com/108304170/176039645-bb79e04a-f683-46ca-bb23-17f13ba91eb3.png)
![image](https://user-images.githubusercontent.com/108304170/176039812-4b91c0cc-8eda-4e00-96af-cd2f4518e0d6.jpeg)
![image](https://user-images.githubusercontent.com/108304170/176039881-7e490549-d1f1-4c06-96d1-1b1e68ae6288.png)
**Device and data (please complete the following information):**
 - OS: [iOS]
 - BattleScribe version [2.03.15]
 - Release version [v9.4.1]

**Comment by Mad-Spy** [comment]
I'm not updating the file twice. The points changes will be in with the new Codex release.

**Comment by Jhotaro25** [comment]
Ok thanks anyway
