### ISSUE TITLE
Imperial Knights v98: Ironhail Stubber not hidden when Knight is Mechanicus

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#11485]
When I select my Questor Allegiance as Questor Mechanicus, I can still select the Questor Ironhail Heavy Stubber, which is for Imperialis, on all Knignts even though they shouldn't have access to it when they are Questor Mechanicus 

![image](https://user-images.githubusercontent.com/72748875/176097576-b1458b2b-cc69-4f0c-8ca6-807bb8ceb116.png)
![image](https://user-images.githubusercontent.com/72748875/176097587-3ddb9fd3-1975-4ce7-b05b-84892471c93b.png)

**Comment by Mad-Spy** [comment]
@RespectableJack please take some time to include a meaningful title on issues you raise.
