### ISSUE TITLE
Astra Militarum: Executioner missing cost for cannon

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#115]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** Yes

**Description:** Astra Militarum Leman Russ Executioner Tank is missing and not accounting for the Executioner Cannon of all things. Which should be an added 20 pts in cost.

**Comment by alphalas** [comment]
duplicate of #116
