### ISSUE TITLE
[Bug Report]  Imperial Knights: Can not select any warlord traits.

### ISSUE THREAD

**Issue by Tritium-X** [BSData/wh40k-9e#11507]
It does not list any options to select a Imperial Knight as your Warlord or do house traditions/relics unless you go freeblade.

![IK Error](https://user-images.githubusercontent.com/45644700/176516805-84c4d7e3-b979-410d-a3e3-059557ef6eba.JPG)

**Comment by AbonShell** [comment]
First of all, you're a version behind. Second, unable to replicate.

**Comment by Tritium-X** [comment]
Are you sure it's a version behind? I updated the data and it still shows the same version as v221.

**Comment by AbonShell** [comment]
~~Current version is 98~~ oh my bad, I was looking at your PL, in any case I can't replicate your issue.

Oh, your issue is you're running an unbound army.
