### ISSUE TITLE
Imperium - Astra Militarum: Command Squad Veteran Weapons Teams' Lascannon should be 15 points

### ISSUE THREAD

**Issue by petersencw** [BSData/wh40k-9e#11508]
**Describe the bug**
Veteran Weapon Teams in Command Squads currently have free Lascannons. 

**Expected behavior**
According to the latest Munitorum Field Manual, Lascannons still cost +15 points for Command Squads.

**Device and data (please complete the following information):**
 - OS: iOS
 - BattleScribe version: 2.03.15
 - Release version: 9.4.1

**Comment by Technoblazed** [comment]
This is fixed in the next release.
