### ISSUE TITLE
Aeldari - Craftworlds Wrong PL

### ISSUE THREAD

**Issue by strakerc** [BSData/wh40k-9e#11501]
**Describe the bug**
Aeldari - Craftworlds still doesn't have the March 2022 PL update taken into account. This is separate from points updates. 

**To Reproduce**
Compare unit PL to the Power Rating update at https://www.warhammer-community.com/faqs/ for Aeldari - Craftworlds. Changes, such as with the Farseer, were not taken into account. 

**Expected behavior**
The PL in Battlescribe should match the Power Rating update. 

**Screenshots**
N/A

**Device and data (please complete the following information):**
 - OS: Android, Windows
 - BattleScribe version 2.03.25
 - Release version v9.4.1

**Additional context**
N/A

**Comment by DRC-TJensen** [comment]
The points are incorrect for the Aspect warriors as well

**Comment by Gryps2** [comment]
Please revert these changes. The PL adjustments in the March 2022 PL adjustment were for the 8th edition codex, not the 9th edition one. This can be seen by the fact that Dire Avengers are listed as being Troops despite being Elites in 9th edition, Wraithlords being listed as Heavy Support despite being moved to Elites, etc.

**Comment by straker-skulljack** [comment]
@Gryps2 , I used to think this as well, but that is incorrect. These *are* the correct PLs for 9th edition and the newest Craftworlds codex.

The first sentence even says it's craftworld and replaces all power level published before it came out and the new codex came out a week before it dropped. So it's correct as far as the power level even if they units are listed in wrong role slot.

Blame GW for their bad documentation, but they are still the newest PLs.

**Comment by strakerc** [comment]
I just updated to v.9.6.2 updated July 16th and despite this being closed the updated PLs still aren't taken into account. So there's nothing to revert 😢

**Comment by strakerc** [comment]
Is there a reason why this was reverted and closed? The PLs are still wrong and Gryps2's comment is wrong.

**Comment by FarseerVeraenthis** [comment]
The units listed and PL's given do not match the current book in many ways other than just units being in the wrong slots.
This thread is the entirety of discussion on the subject, which suggests the community is happy with the data as currently presented.

**Comment by strakerc** [comment]
To say the community is happy is nuts - are you in all of the FB Aeldari groups with thousands of members each? There are many complaints, and this is being litigated in the Discord right now: https://discord.com/channels/558412685981777922/569676136028700699/1028907490009698304

Technically, the codex came out before the PL update. RAW, the PL update is the true value for PL. Blame GW on being dumb (this wouldn't be the first time), but the current PL values are complained about by many members of the community - either way, folk will complain!

I empathize with this, but argue it's Battlescribe's job to follow GW, dumb or not.

**Comment by FarseerVeraenthis** [comment]
The Power Level update is clearly for the old codex.
If I were to attempt to include the details I would have to make a decision on how, for example, to implement the Warlock Conclave power level, since that datasheet no longer exists in the current codex.
Warlock Conclave <> Warlocks. 
Therefore, interpreting that they are equal is not RAW, and therefore not permissible.
Codex: Craftworlds <> Codex: Aeldari 
This update is not valid, it cannot be included without interpretation, so it will not be included.

**Comment by strakerc** [comment]
Yeah we had the conversation in Discord - thank you.
