### ISSUE TITLE
Imperium - Astra Militarum: Regimental Officers Matched Play validation question

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11513]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 9.04.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I dont think the imperial guard (AM) matched play rule for command squads requiring regimental officers is being checked. Pg132 of codex

**Comment by Technoblazed** [comment]
Looks fine during testing, you'll have to add some more specific details on what's not working for you.
