### ISSUE TITLE
Imperium - Deathwatch: Points not updated

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11514]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Deathwatch killteams not updated with the new points for instance if you take eliminators with las fusil in a spectrus killteam, they are still 30 points a model and they should only be 25 points since the las fusil  became free i  the last points balance.

**Comment by Mad-Spy** [comment]
Fixed in next release.
