### ISSUE TITLE
Space Marines - Chaplain Venerable Dreadnought is unable to use character stratagems

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#11518]
**Describe the bug**
Chaplain Venerable Dreadnought is unable to use the Hero of the Chapter stratagem to take a Warlord trait.

**To Reproduce**
1. Add a Chaplain Venerable Dreadnought and another HQ to your roster.
3. Make the secondary HQ your Warlord to enable things.
4. You are unable to take Hero of the Chapter on the Chaplain Dreadnought.

**Expected behavior**
You should be able to use the stratagem to select a Warlord trait for the unit, as it is a CHARACTER.

**Screenshots**
N/A

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version: [e.g. 2.03.21]
 - Release version: Tested on Blood Angels v249

**Additional context**
N/A

**Comment by Mad-Spy** [comment]
They also can't currently use the Nephilim Stratagems to unlock WLTs or Relics.
