### ISSUE TITLE
Tyranids armies gives double warning for missing warlord

### ISSUE THREAD

**Issue by reehn** [BSData/wh40k-9e#11517]
**Describe the bug**
Tyranids armies gives double warning for missing warlord, and only 1 disappears when you choose a warlord, there is also a wording difference:

- ... must have 1 more selections of Warlord (minimum 1) -> Does not disappear
- ... must have 1 more selections from Warlord (minimum 1) -> Does disappear

**To Reproduce**
1. Create a new Tyranids roster
2. See the error messages and you will have 2 warnings for not having a warlord
3. Choose a HQ and make it you warlord
4. See that the warning with "from Warlord" has disappeared but the one with "of Warlord" remains, which still blocks the CP count from being correct.

**Expected behavior**
To begin with only 1 warning for not have a Warlord, and for it to disappear when choosing a Warlord.

**Screenshots**
![image](https://user-images.githubusercontent.com/39645701/176780113-dc00b0bd-9114-4f01-8761-25e6b92a37c2.png)
![image](https://user-images.githubusercontent.com/39645701/176780255-5e9f610e-dec8-4fb9-94db-c1a09dd2c30a.png)

**Device and data (please complete the following information):**
 - OS: Windows and Android
 - BattleScribe version 2.03.21
 - Release version v9.4.1

**Additional context**

**Comment by AbonShell** [comment]
Fixed in next release
