### ISSUE TITLE
Bug report: Imperium - Adeptus Mechanicus.catz

### ISSUE THREAD

**Issue by Seano3** [BSData/wh40k-9e#11511]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe Version:** 2.03.21.166

**Platform:** Windows

**Description:** The Mechanicus Locum stratagem seems to not be working correctly. When ever I select it the warlord traits pop up but as soon as I select one a warning pops up saying that there is a maximum of 0.

**Comment by Mad-Spy** [comment]
Fixed in next release.
