### ISSUE TITLE
Aledari Craftworlds: Aspect warriors points are not updated

### ISSUE THREAD

**Issue by DRC-TJensen** [BSData/wh40k-9e#11516]
After balance state change:
Dire avengers should be 13
Hawks 20
Banshees 19

**Device and data (please complete the following information):**
 - BattleScribe version [e.g. 2.03.45]
 - Release version [e.g. v1.2.3]

**Additional context**

[💾 Cat: Aeldari - Craftworlds]

**Comment by Mad-Spy** [comment]
Fixed in next release
