### ISSUE TITLE
Warhammer 40,000 v9.4.1 24 jun 2022

### ISSUE THREAD

**Issue by JoeZan77** [BSData/wh40k-9e#11526]
New Roster --> Battaglion Detachment --> Tyranids
Error : New Roster (Warhammer 40,00 9th Edition v221) must have 1 more selections of Warlord (minimum 1 )
Although I have selected an HQ as a Warlord, I am notified that a Warlord has not been assigned in the list
![Schermata 2022-07-01 alle 00 16 18](https://user-images.githubusercontent.com/77099203/176893195-5f258e95-b4be-4836-939b-3981d42b953f.png)
[.]([url](url))

**Comment by AbonShell** [comment]
Fixed in next release
