### ISSUE TITLE
No required Legion is CSM Belakor detachments

### ISSUE THREAD

**Issue by Thor-axetheImpaler** [BSData/wh40k-9e#11537]
CSM detachments with Army of Renown - Disciples of Be'lakor is requiring a Legion trait even tho CSM doesn't get a Legion in DoB AoR.

**Comment by Mad-Spy** [comment]
They do choose a Legion. They just don't get a trait, instead swapping it for the DoB "trait" which is what gets displayed on the output, if you look closely.
