### ISSUE TITLE
Astra Militarum - weapons with improper cost values (should be 0) 

### ISSUE THREAD

**Issue by MackTheNoz** [BSData/wh40k-9e#11530]
**Describe the bug**
Upgrades listed below are not in the latest MFM and upgrades not in the MFM are free upgrades according to the section at the start of the MFM:

Infantry Squad / Special weapon / Sniper rifle -> is 2 should be 0
Veterans / Heavy Flamer -> is 10, should be 0
Veterans/  Special weapon / Sniper rifle -> is 2 should be 0
Platoon COmmander /  Chainsword / Power Maul -> is 4 should be 0
Platoon COmmander /  Chainsword / Power Axe -> is 5 should be 0
Special Weapon Squad /  Sniper rifle -> is 2 should be 0
Heavy Weapon Squad /  Missile launcher -> is 5 should be 0
Command Squad / Veteran with special weapon / Sniper rifle -> is 2 should be 0

**Steps to reproduce the behavior:**
Verify point values 

**Expected behavior**
Change values 

**Screenshots**
n/a

**Device and data (please complete the following information):**
 - Desktop and Android
 - BattleScribe version  v2.03.21.166
 - data Release version 9.4.1

**Comment by a-gorman** [comment]
I still see the Command Squad's sniper rifle costing 2 points in 9.6.2
