### ISSUE TITLE
Chapter approved War Zone Nephilim CP mistakes

### ISSUE THREAD

**Issue by Sbrunch** [BSData/wh40k-9e#11533]
Description:

Matched Category Grand Tournament War Zone Nephilim has a bug that doesn't correctly change the cost in CP of a few things.

Firstly as per nephilim you have access to a Super Heavy Auxiliary detachment as long as the Faction Keyword of units in it matches your Warlord's (exception for superfaction keywords such as imperium, chaos etc).

Secondly you are no longer granted for free the first relic or warlord trait and they both cost 1CP each as they use new generic stratagems.

To Reproduce:
1: create a new rooster
2: select matched play with chapter approved war zone nephilim
3: notice how you still have access to free WL traits and relics and still have to pay for the super heavy auxiliary detatchment

**Comment by Technoblazed** [comment]
1. Add the `Shared Faction Bonus` from `Configuration` if you meet the requirements as per the rulpes.
2. This isn't implemented for every faction, tracked here https://github.com/BSData/wh40k/issues/11397
