### ISSUE TITLE
Chaos knights dreadblade issue with faction specific WL stratagem

### ISSUE THREAD

**Issue by Sbrunch** [BSData/wh40k-9e#11534]
**Describe the bug**
after putting a dreadblade in a super heavy auxiliary detatchment in nephilim rules you can add a WL trait to a dreadblade AND a relic after only selecting the relic stratagem (corrupted heirlooms). In addition if you give it a WL trait this way and then select the stratagem for it (tyrannical court) you are given the error message that he can't have any more selections of traits. 
Just to clarify things if you only select the WL trait stratagem (Tyrannical court) you can't give him a WL trait as it wont let you select one.

**To Reproduce**
1. Create a Chaos Knights rooster
2. Open a Super heavy aux detatchment
3. Add a knight there (I did it with a desacrator)
4. make that knight a freeblade and now try to give him a WL trait via tyrannical court together with/or without a relic from corrupted heirlooms

**Comment by Sbrunch** [comment]
Note: this was with matched play nephilim settings

**Comment by AbonShell** [comment]
You technically shouldn't have access to the chaos knights specific strats, unless your warlord is a chaos knight.

**Comment by Mad-Spy** [comment]
I'm unable to replicate this in the current release.

The only legal way to get Tyrannical Court to appear on a model is to have a Knights Warlord, and adding Tyrannical Court correctly allows a Warlord Trait on the model it is added to.

If you're having a problem, please supply full details of your list.

**Comment by Sbrunch** [comment]
![Screenshot (17)](https://user-images.githubusercontent.com/89992297/177004143-38168630-1406-4563-97a7-5196933b4371.png)
[CK 1K 1T BDM.txt](https://github.com/BSData/wh40k/files/9033101/CK.1K.1T.BDM.txt)

Update, I think it's an android version problem as the same list from the same file (I share it as text as I cannot upload the army list file to github) if you open it on pc gives no errors but if you open it on android it gives one

**Comment by Sbrunch** [comment]
> You technically shouldn't have access to the chaos knights specific strats, unless your warlord is a chaos knight.

the list I am talking about has a warlord as a chaos knight

**Comment by Mad-Spy** [comment]
The data comes from the same source, so it can't be specific to your platform. The current released version of CK is v73. Update your data and try again.

**Comment by Mad-Spy** [comment]
Found the problem. Both strats give the model CHARACTER, and the conditions that show/hide the lists were triggering on a _single_ entry.
