### ISSUE TITLE
Astra Militarum - Not takin warlord trait gives Rooster Validation Error

### ISSUE THREAD

**Issue by MackTheNoz** [BSData/wh40k-9e#11531]
**Describe the bug**
_"Instead of choosing a Warlord Trait, you can select a Tank Ace ability to apply to one of your eligible Astra Militarum vehicles. Alternatively – or in addition if you want to include two Tank Aces – you can spend a single Command Point to use the Tank Ace Stratagem"_ 

It was there in previous versions, now is gone. 

Please note, that this does not require taking Warlord Trait, therefore geting Tank Ace by this method remains free. 

**To Reproduce**
1. Select character
2. Enable warlord 
3. In new menue there is no Tank Ace to select

**Expected behavior**
Additional option in warlord (named and unnamed) to allow him to take additional Tank Ace instead of Warlord Trait, that will cost OCP and increase Tank Ace limit. 

**Screenshots**
n/a

**Device and data (please complete the following information):**
Desktop and Android
BattleScribe version v2.03.21.166
data Release version 9.4.1

**Comment by Technoblazed** [comment]
You still need to pay for the strat to gain access to the tank ace, the prerequisite is "rather than determining a Warlord Trait", you still have to be eligible to determine one in the first place.
