### ISSUE TITLE
Chaos - Chaos Space Marines: Various profile issues

### ISSUE THREAD

**Issue by miguelgm** [BSData/wh40k-9e#11549]
**Describe the bug**
Some errors in dataslates:
- [x] Heretic Astartes Daemon Prince:
  - Hellforged sword: D2 should be D3
- [x] Fabius Bile:
  - Profile: BS 3+ should be BS 2+
- [x] Dark Comune:
  - Blessed Blade:
    - Profile: S3 should be S4
- [x] Havocs:
  - Havoc:
    - Profile: A4 should be A3
  - Havoc Champion:
    - Profile: A3 should be A4
- [x] Obliterators:
  - Profile: M4 should be M5

**To Reproduce**
Verify dataslates

**Expected behavior**
Change values

**Screenshots**
n/a

**Device and data (please complete the following information):**
 - OS: desktop
 - BattleScribe version: v2.03.21.166
 - Release version v9.5.0

**Additional context**
Thanks for your work :)

**Comment by Nvaughan2** [comment]
Noise marine champions should be able to take, and gift of chaos should be an option without needing to have a mark first
Otherwise its all good and I'm very happy with it!
