### ISSUE TITLE
Ork Waaagh! missing rules

### ISSUE THREAD

**Issue by whitewolfmxc** [BSData/wh40k-9e#11547]
Ork Waaagh! missing rules , updated rule below 

(current data is missing the +1 strength bonus on both stages)

Stage 1: Call Da Waaagh!
ORKS CORE and ORKS CHARACTER units from your army are eligible to declare a charge even if they Advanced this turn.
Add 1 to the Strength and Attacks characteristics of ORKS models from your army.
ORKS models from your army have a 5+ invulnerable save.

Stage 2: Get Stuck In!
Add 1 to the Strength and Attacks characteristics of ORKS models from your army.
ORKS models from your army have a 6+ invulnerable save.

**Comment by Technoblazed** [comment]
Update your data.

**Comment by whitewolfmxc** [comment]
excuse me ? where does it say +1 strength Bonus ?  see screen cap

![Capture 1](https://user-images.githubusercontent.com/65846291/177037654-72421885-f479-4367-9af3-60ed5a2c4839.JPG)

![Capture 2](https://user-images.githubusercontent.com/65846291/177037660-b964174a-aee0-4b5d-9a02-1206a99d5eb5.JPG)

**Comment by whitewolfmxc** [comment]
Hello , this has not been resolved yet
