### ISSUE TITLE
Chaos - Chaos Space Marines: Add Legends units back in

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11558]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Chaos space marine LEGENDS data appears to be missing from csm list. Specifically the HQ data. I.e. no chaos lord on bike or Zhufor the Impaler

**Comment by Akaoni** [comment]
**Note:** New Legends data has been released:
https://www.warhammer-community.com/legends/#warhammer-40000

**Comment by Mad-Spy** [comment]
Done as per the linked commit.

FW Legends have not been added back as they have not had updated rules.
