### ISSUE TITLE
Chaos 9.Ed bugs

### ISSUE THREAD

**Issue by h-2** [BSData/wh40k-9e#11565]
Thanks for the very swift data updates :)

Here are some things I noticed:
- Havoc Champion cannot have a boltgun
- Cultist (Mob) Champion cannot have Cultist firearm
- Let the galaxy burn is not listed under "Selection rules" 
- Legion trait is not lister under "Selection rules"

All of these were tested with World eaters, in case that makes a difference.

**Comment by Mad-Spy** [comment]
1. Fixed.
2. Fixed.
3. It was missing on Havocs. However the full text is not reproduced in the data, only a reference to the page in the Codex.
4. It's listed on the Legion selection.
