### ISSUE TITLE
Chaos - Chaos Space Marines: Points issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11564]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** 

- [x] ~~Gifts of Chaos broken. Should be available for unmarked characters to have a single relic~~ Already fixed.
- [ ] Forgefiend points incorrect. Base cost is 125 should be 110. 
- [ ] Ectoplasma cannons are 20 points should be 15. 
- [ ] Hades autocannon is 30 points should be 25. 
- [ ] Ectoplasma cannon head is 15 points should be a free upgrade

**Comment by Mad-Spy** [comment]
All the Forgefiend points are correct as per the Codex already.
