### ISSUE TITLE
Chaos Space Marines Legionaries Psychic Powers

### ISSUE THREAD

**Issue by ZiggyQubert** [BSData/wh40k-9e#11561]
**Describe the bug**
When selecting a power for a Legionary with the balefire tome, he should only have access to 3 powers

**To Reproduce**
Currently all 6 powers are available to select from

**Expected behavior**
Only 3 powers should be available

**Screenshots**
![image](https://user-images.githubusercontent.com/3503895/177155594-5fb9e0e6-9de2-49bb-a95f-3a32343a3cc9.png)

**Comment by Mad-Spy** [comment]
It is also incorrect for the Dark Commune's Mind Witch.
