### ISSUE TITLE
Blood Angels: Sanguinary models are missing the Nephilim Relic stratagem

### ISSUE THREAD

**Issue by ThePants999** [BSData/wh40k-9e#11568]
Since upgrading to v9.6.0, I cannot add any relics to characters in a Blood Angels detachment. No characters get an option for the "Relic" stratagem, regardless of who the warlord is, and adding the "Relic of the Chapter" stratagem has no effect: no relic options appear for any characters. Loading an existing data file with relics creates errors that those characters should not have any Relic selections.

**Comment by ThePants999** [comment]
Also, I know this is technically a separate issue, but I'll be lazy and add it here since it'll probably go to the same person: Dante is still being required to take his warlord trait if made the warlord.
![image](https://user-images.githubusercontent.com/2923823/177292478-cd0fb237-9e3b-4101-ba95-24e2170fbcb2.png)

**Comment by Mad-Spy** [comment]
The Relic and WLT Stratagems are appearing under the "Stratagems" group entry for me and then work as expected. It is a little confusing because "Angel Exemplar" is not in that group, but appears when you add the Warlord.

You might also want to try doing an update with "Delete existing data" checked to ensure that all files are correctly updated.

![image](https://user-images.githubusercontent.com/29306451/177294890-3964342f-e8cf-4a6a-a8a9-3570c6a99205.png)

**Comment by ThePants999** [comment]
@Mad-Spy Any chance you have some unreleased changes in there? I've just done another update with "Delete existing data" checked and that hasn't changed anything. There's definitely been a change since v9.5.0 because I previously didn't have the "Warlord Trait" stratagem, but for me there's still no Stratagems section on a character, and Relic of the Chapter remains under the "Stratagems" section of the detachment rather than on an individual unit.
![image](https://user-images.githubusercontent.com/2923823/177295768-a4994240-c7f4-4d51-aa07-799ece0e58fe.png)

**Comment by ThePants999** [comment]
@Mad-Spy I think there are BA-specific issues here. I just checked with the generic Captain and I am now seeing what your screenshot showed - but I _don't_ get that with a BA-specific character like the Sanguinary Priest.

**Comment by Mad-Spy** [comment]
Yes, it looks like the Sanguinary Priests are missing the Relic strat. Everything else does appear to be working correctly as far as I can tell. I've updated the title to reflect the problem.

**Comment by ThePants999** [comment]
Sanguinary Ancient is also bugged.
