### ISSUE TITLE
Necrons: Spyder Particle Beamer cost needs update

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11578]
**File:** Necrons.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Canoptek Spyder Particle Beamers cost 5pts now. Thank you for all the work you do!!

**Comment by TommyKnoxx** [comment]
Just wanted to comment it is 5p per. Particle Beamer and it has 2 of them. So total point cost is the same (10p)

**Comment by DrTobogganMD** [comment]
@TommyKnoxx is correct. 5 per x2 = 10 :)
