### ISSUE TITLE
Imperium - Dark Angels: DA specific characters are missing the Nephlim Relic stratagem

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11573]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Unable to add a relic to Interrogator-Chaplain. Issue is on pc as well as the app as of the most recent update.

**Comment by TheShutInProject** [comment]
Relic is also unavailable on Chaplain in Terminator Armor, Deathwing Strikemaster, Interrogator-Chaplain in Terminator Armor, Ravenwing Talonmaster, Deathwing Apothecary, Deathwing Champion, Ravenwing Ancient, Ravenwing Apothecary, and Ravenwing Champion.

**Comment by FarseerVeraenthis** [comment]
- [x] Chaplain in Terminator Armor, This is working fine.
- [x] Deathwing Strikemaster, 
- [x] Interrogator-Chaplain in Terminator Armor, 
- [x] Ravenwing Talonmaster, 
- [x] Deathwing Apothecary, 
- [x] Deathwing Champion, 
- [x] Ravenwing Ancient, 
- [x] Ravenwing Apothecary, and 
- [x] Ravenwing Champion
