### ISSUE TITLE
Imperium - Salamanders: Characters unable to select Relics

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11575]
**File:** Imperium - Salamanders.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** I apologize, I reported this incorrectly as Space Marine. I only found it under the Salamanders.

There is no list of relics to purchase after I click on the checkbox for either Strategem: Relic or Relic of the Chapter. This happens regardless of gametype (Open, Matched, or Narrative types). This is for characters only. When I do click on a Sergeant and check off the checkbox for Strategem: Master Artisans in Sgt Strategems, a new box of appropriate options does appear below it on the right hand side window panel.

I did have an old list after updating and a error/warning came up saying my warlord had a relic (hidden) that he was not allowed to have. I clicked the "None" option and the relic options disappeared. I saved it and the same error as above appeared and I was no longer able to see/access the relics (the checkboxes do not open a new set of options).

Thank you.

**Comment by acebaur** [comment]
I'll look into it

**Comment by MTG-Bob** [comment]
I see that this is closed as completed on 7/5/2022, this issue is still there. Relics are not listed even when Relic of the Chapter is selected
![1](https://user-images.githubusercontent.com/108858375/177707829-1bb4c166-9f78-4ddd-8c18-1b85153bd403.jpg)
.
