### ISSUE TITLE
Imperium - Astra Militarum: Command Squad lascannon should cost 15pts

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11581]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Under the Command Squad, the lascannon is listed at "no cost".  According to Munitorum Field Manual MkII 2022 (posted 06/2022) pg. 18, the cost of the lascannon should be 15 pts.

**Comment by Mad-Spy** [comment]
Fixed in next release
