### ISSUE TITLE
Aeldari - Drukhari: Bloodbrides are too expensive

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11583]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Drukhari bloodbrides are still listed at 15 points per model.  Wyches were lowered to 11ppm with the newest field manual, and upgrading to bloodbrides is listed as a 3pt upgrade.  Bloodbrides should be 14 points, not 15.

**Comment by FarseerVeraenthis** [comment]
dem bloodbrides eh...!!
