### ISSUE TITLE
Chaos - Chaos Space Marines: Lord of the Ezakarion missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11595]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** It looks like the Lord of the Ezekarion stratagem is missing for Black Legion. This is a stratagem that allows you to spend 1 CP to add a 2nd Warlord Trait to a Black Legion Warlord, as long as it comes from the Black Legion-only Warlord Traits. Thank you!

**Comment by Mad-Spy** [comment]
Appears to be working for me. Once you've selected a Warlord, and selected Black Legion as your Legion, the Stratagem appears on that Warlord.

![image](https://user-images.githubusercontent.com/29306451/177617676-febd3cd8-9e88-4147-a217-445b6b77a7b5.png)
