### ISSUE TITLE
Chaos - Chaos Space Marines: WLTs should be max 1 in Roster

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11597]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** I do *NOT* receive an error on the UI for adding 2 instances of the "Violent Urgency" WLT for Chaos Space Marines. 

Legion: World Eaters 
Detachment: Battalion 
Units the WLT was added to: Lord Discordant and Chaos Lord in Terminator Armor. 

Have not tested this lack of error on other detachments/HQs

**Comment by Mad-Spy** [comment]
Fixed in the referenced commit. Will be in next release.
