### ISSUE TITLE
Imperium-Space Marine wrong pts for Scout sniper rifle

### ISSUE THREAD

**Issue by Dzejra** [BSData/wh40k-9e#11599]
Imperium-Adeptus Astartes-Ultramarines v62
Scout sniper rifle cost is 0pts in app is still 2pts.

 - OS: iOS 15.5
 - BattleScribe version 2.03.15

**Comment by acebaur** [comment]
The app is not a rules source, the points are correct as per the points document

**Comment by Dzejra** [comment]
But in latest point document is Scout sniper rifle for free. https://www.warhammer-community.com/wp-content/uploads/2022/06/mYZ4b5gZUiktj4GI.pdf and so it is in the WH40k battle forge application.

**Comment by Dzejra** [comment]
But in latest point document is Scout sniper rifle for free. https://www.warhammer-community.com/wp-content/uploads/2022/06/mYZ4b5gZUiktj4GI.pdf and so it is in the WH40k battle forge application.
Best regards
Dzejra

Odesláno z iPhonu
