### ISSUE TITLE
T'au; R'varna and Y'vahra don't show all support systems

### ISSUE THREAD

**Issue by Uncle-Mel** [BSData/wh40k-9e#11590]
Shown in BS:
• Counterfire defence system
• Early warning override
• Multi-tracker
• Target lock
• Velocity tracker

Per latest (and previous) MFM for both:
• Advanced targeting system +20 pts
• Drone controller +5 pts
• Shield generator +40 pts

**Comment by Technoblazed** [comment]
MFM doesn't change the legal datasheet options.
