### ISSUE TITLE
Imperium - Blood Angels: Relic of the Chapter not working correctly

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11593]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** When selecting stratagem "Relic of the Chapter" unable to change ammount of CP cost.
When selecting a character, unable to provide them with a relic.

**Comment by acebaur** [comment]
Already Fixed
