### ISSUE TITLE
Imperium - Space Marines - Salamanders: Can't give Warlord Trait strategem to Adrax Agaton 

### ISSUE THREAD

**Issue by Egil31** [BSData/wh40k-9e#11608]
Can't give Warlord Trait strategem to Adrax Agaton

**Comment by acebaur** [comment]
Make sure you select him as your Warlord first and have Nephilim selected.

Unable to reproduce

**Comment by Egil31** [comment]
![Screenshot_2022-07-07-20-01-20-740_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/108886214/177819221-ded46dc2-bf66-4c79-a6c2-83629a889384.jpg)
