### ISSUE TITLE
Imperium - Salamanders: Forcing Nephilim WLT/Relic costs in Open Play

### ISSUE THREAD

**Issue by MTG-Bob** [BSData/wh40k-9e#11610]
**Describe the bug**
In Open Play
Forcing CP costs for Warlord Trait
Forcing CP costs for Relics
Forces to select Relic of the Chapter for both HQ units

**To Reproduce**
Start a new roster for Salamanders
Add 2 HQ units
Make one a Warlord

**Expected behavior**
Expected Menu options for both Traits and Relics.

OS: Windows 11
BattleScribe version: v2.03.21.166
Release version: 9.6.0
![3](https://user-images.githubusercontent.com/108858375/177934749-69daf281-615c-43b6-af1f-9bf888f20cf2.jpg)
![4](https://user-images.githubusercontent.com/108858375/177934779-ec414755-ae49-4216-8e9b-ed6de6e34594.jpg)

**Comment by acebaur** [comment]
Niether one of those strats are Nephilim specific and I'm not able to reproduce this.
