### ISSUE TITLE
Chaos Knights - Nephilim SHA CP refunds not working

### ISSUE THREAD

**Issue by tedhaha** [BSData/wh40k-9e#11616]
Nephilim p5 says

> If a player’s army includes one or more Super-heavy Auxiliary Detachments, they can change the Command Benefits of one of them to: ‘+3 Command points if the unit in this Detachment is not your WARLORD, but it is from the same Faction as your WARLORD’s Detachment, and that Faction is not CHAOS, IMPERIUM, AELDARI or TYRANIDS’.

but this doesn't work for Chaos Knight.

**Comment by AbonShell** [comment]
Add "shared faction bonus" to your roster in the configuration section
