### ISSUE TITLE
Astorath (BA) can't get his warlord trait

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#11615]
When Astorath is selected as warlord, the stratagem Warlord trait doesn't appear for him so he can't take his warlord trait

![image](https://user-images.githubusercontent.com/72748875/178090392-befc62f5-cc4f-45d2-8fd1-9295786cf5d1.png)

**Comment by RespectableJack** [comment]
Only Astorath can't get his warlord trait, I checked the other BA named characters and i was able to give them their traits

**Comment by Mad-Spy** [comment]
Duplicate of #11790
