### ISSUE TITLE
Necrons free Warlord Trait and Relic

### ISSUE THREAD

**Issue by TropicalRemixed** [BSData/wh40k-9e#11629]
I'm able to select a free Warlord trait and Relics with Necrons

Configuration:
Battle Size: Strike Force
Detachment Command Cost: -2CP
Dynasty Choice: <custom> Relentlessly Expansionist, Eternal Conquerors
Gametype: Nephilim

All units tried have free warlord traits and relics

**Comment by AbonShell** [comment]
Known issue, will be resolved soon
