### ISSUE TITLE
 T'au Empire.catz Error in Broadside Secondary Systems

### ISSUE THREAD

**Issue by donmcarthur** [BSData/wh40k-9e#11625]
File: T'au Empire.catz

BattleScribe version: 2.03.21

Platform: Windows

Dropbox: Yes

Description: File: Selecting Stabilized Optics and Twin Plasma Rifle on a Broadside Shas'vre  secondary systems, it produces an error "Broadside Shas'vre has 1 too many selections of Twin Plasma Rifle (maximum 0)

**Comment by Technoblazed** [comment]
> Note: No model can be equipped with more than one of the following: early warning override; stabilised optics; twin plasma rifle; velocity tracker.
