### ISSUE TITLE
Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by Arcuos** [BSData/wh40k-9e#11626]
Simple bug:
The aspiring sorcerer from Rubric Marines squads, should have every weapon replacement for free, warpflame pistola etc, as he has on the Thousand Sons Codex, but Now, they cost 5p.

**Comment by AbonShell** [comment]
Update your data. 
![SmartSelect_20220711-040245](https://user-images.githubusercontent.com/20672472/178217139-9033d0ca-9ad6-45e1-9293-109db234398f.jpg)
![SmartSelect_20220711-040235](https://user-images.githubusercontent.com/20672472/178217152-a20013e2-e3e2-4e75-a04f-e06242aaeb87.jpg)
