### ISSUE TITLE
Space Marines and all chapters - Stratagem section should be available for every HQ choice

### ISSUE THREAD

**Issue by smajchrz** [BSData/wh40k-9e#11630]
**Describe the bug**
The stratagem section should be available for every HQ choice, right now stratagem section shows only when a character is selected as Warlord. Such behaviour is against the wording of stratagems such as HERO OF THE CHAPTER and RELIC OF THE CHAPTER as such starts can be used to give trait/relic to ANY character, not only Warlord.

> RELIC OF THE CHAPTER
> Use this Stratagem before the battle, when you are mustering your army, if your WARLORD has the ADEPTUS ASTARTES keyword. **Select one ADEPTUS ASTARTES CHARACTER model from your army** and give them one Chapter Relic (this must be a Relic they could have). Each Relic in your army must be unique, and you cannot use this Stratagem to give a model two Relics. You can only use this Stratagem once, unless you are playing a Strike Force battle (in which case, you can use this Stratagem twice) or an Onslaught battle (in which case, you can use this Stratagem three times).

> HERO OF THE CHAPTER
> Use this Stratagem before the battle, when you are mustering your army, if your WARLORD has the ADEPTUS ASTARTES keyword. **Select one ADEPTUS ASTARTES CHARACTER model from your army** (excluding named characters) and determine one Warlord Trait for it (this must be a Warlord Trait it can have); that model it is only regarded as your WARLORD for the purposes of that Warlord Trait. Each Warlord Trait in your army must be unique (if randomly generated, re-roll duplicate results), and you cannot use this Stratagem to give a model two Warlord Traits. You can only use this Stratagem once, unless you are playing a Strike Force battle (in which case, you can use this Stratagem twice) or an Onslaught battle (in which case, you can use this Stratagem three times).

**To Reproduce**
Steps to reproduce the behaviour:
1. Just try to add a trait/relic to the non-warlord character of SM or one of its chapters.

**Expected behaviour**
The stratagem section is always visible next to character units or if it requires a smaller effort the two mentioned stratagems should be available from a top section on the character page - next to the warlord option.

**Screenshots**

**Device and data (please complete the following information):**
 - OS: iOS
 - BattleScribe version: 2.03.15
 - Release version: v9.6.1

**Additional context**
N/A

**Comment by Mad-Spy** [comment]
Work in progress.
