### ISSUE TITLE
Deathwing Terminator/Command Squad loadout points errors

### ISSUE THREAD

**Issue by RollToSaveVsDragons** [BSData/wh40k-9e#11631]
Deathwing Terminator Squad and Deathwing Command Squad normal squad members currently pay 5 points for Storm Bolter & Powerfist, and the sergeant doesn't have the option to change his Power Sword for a Power Fist for 5 points.

It should be the other way around. The normal squad members should get Storm Bolter & Powerfist by default and the sergeant should be able to change his Power Sword for a Power Fist for 5 points.

**Comment by FarseerVeraenthis** [comment]
This is in keeping with the codex and - as far as I can see - has not been changed via FAQ.
