### ISSUE TITLE
Adeptus Mechanicus: Archeotech Specialist is not correctly incrementing the number of relics available

### ISSUE THREAD

**Issue by Nothrazim** [BSData/wh40k-9e#11637]
Adding more Archeotech Specialists in the stratagem doesn't increase your permitted amount of relics. Each individual "Stratagem: Archeotech Specialist" gives you one more relic, but that gives an error that you cannot have more than one of these stratagems.

**Comment by Mad-Spy** [comment]
You only add the stratagem once, then drill down into it to select the number of relics.

**Comment by Nothrazim** [comment]
You are misunderstanding my bug report. It doesn't matter how many times you "drill down" to select additional relics within that **_one singular_** stratagem, it still only lets you bring one extra free. Try adding 3+ tech priests and giving them all relics by only adding one stratagem and incrementing it's value/CP cost, and it doesn't work. You'll need to try with 3+ characters since the first relic is a freebie, of course.

**Comment by Mad-Spy** [comment]
I see. I've updated the title to make it more obvious what the problem is.

It sounds like the increment is triggering off the wrong "Archeotech Specialist" entry.
