### ISSUE TITLE
Balefire Tome doesn't list all dark hereticus

### ISSUE THREAD

**Issue by xenoterracide** [BSData/wh40k-9e#11647]
**Describe the bug**
The Balefire Tome Marine, only has the option to select one of the first three dark hereticus is disciplines. However from the reading of the codex it seems like they could take one of all six

![Screenshot_20220715-110425.png](https://user-images.githubusercontent.com/5517/179251162-78c31098-95a3-45eb-999f-5008bb99b86f.png)![Screenshot_20220715-110412.png](https://user-images.githubusercontent.com/5517/179251183-3e0b970a-f7ae-4af4-a2f7-ef635f43e919.png)

**Comment by Mad-Spy** [comment]
I'm afraid you have misread the Codex (as did I, originally). LEGIONARIES (and CULTISTS) are only allowed to select from the first 3 powers.

![image](https://user-images.githubusercontent.com/29306451/179251462-01f8cb35-32b5-4ca1-b538-a28f9954b3dd.png)
