### ISSUE TITLE
Lucius dogma should be reverted to the old wording

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#11641]
Adeptus Mechanicus forge world Lucius dogma should be reverted to the way it is in the codex i believe, since in the FAQ for AdMech, it isn't listed in the Errata section and the app updated the other day to reflect that Errata for the codex

![image](https://user-images.githubusercontent.com/72748875/179040860-1cebd184-0373-4830-9994-1f9e191be845.png)

**Comment by Thairne** [comment]
![grafik](https://user-images.githubusercontent.com/8590840/179368843-726f4a75-80c0-4fd8-b595-3af95d45e7ca.png)
The balance dataslate still lists the changed dogma.
