### ISSUE TITLE
[Anon] Bug report: Imperium - Elucidian Starstriders not loading due to causing a Low Ram Mode error on all devices

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11642]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 3.25.33

**Platform:** Android

**Dropbox:** No

**Description:** Elucidian Starstriders are not loading, continuous Low Ram issue. Tried it on Tablet PC and Phone. I understand you guys are busy, with keep it updated. Keep up the great work.

**Comment by AbonShell** [comment]
Can confirm that v13 worked
