### ISSUE TITLE
Astra Militarum: Points Costs Errors

### ISSUE THREAD

**Issue by JPThunda** [BSData/wh40k-9e#11648]
Hello all.  First post here, found some points cost discrepancies.  Here's the list I found:

Infantry Squad
-Special Weapons
--Sniper Rifle should cost 0 points

Veterans Squad
-Sergeant
--Plasma Pistol should cost 0 points
--Boltgun should cost 0 points
--Bolt Pistol should cost 0 points
-Special Weapons
--Sniper Rifle should cost 0 points

Command Squad
-Special Weapons
--Sniper Rifle should cost 0 points

Special Weapons Squad
-Sniper Rifle should cost 0 points

**Comment by Technoblazed** [comment]
Already fixed in the next release.
