### ISSUE TITLE
Space Wolves warlord traits unselectable

### ISSUE THREAD

**Issue by nigelhasnomates** [BSData/wh40k-9e#11649]
**Describe the bug**
The warlord traits and relics on Space Marine characters are currently unselectable.

**To Reproduce**
1. Create Space Marine detachment
2. Click on a HQ
3. Scroll down to Click Warlord Trait, Nothing appears

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - BattleScribe version [e.g. 2.03.45]
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by acebaur** [comment]
Update your data, not reproducing ok the current version

**Comment by nigelhasnomates** [comment]
I've run it on a different computer and it's an issue Isolated to my specific computer.
