### ISSUE TITLE
Imperium - Astra Militarum: Tempestor Prime power fist cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11653]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** the Astra Militarum Tempestor Prime HQ needs +5 points on his Power Fist weapon option.  Point cost source:  Munitorum Field Manual 2022 mk2 - data version 9.6.2 Astra Militarum revision v312

**Comment by AbonShell** [comment]
Known issue
