### ISSUE TITLE
Armiger Helverins missing stratagems

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#11669]
I am on the master data. When a knight is selected as the warlord, Armiger Helverins are missing the Knight Baron and Heirlooms of the Household stratagems. 
Also, when a Helverin is made the warlord, they are missing the Warlord trait and relic stratagems
![image](https://user-images.githubusercontent.com/72748875/179645795-c81e18e2-e518-41e0-9fbe-f1fafde949fc.png)
![image](https://user-images.githubusercontent.com/72748875/179645806-31807a49-c0b6-4c9c-9f9b-f63e269a825f.png)

**Comment by AbonShell** [comment]
Fixed in latest commit
