### ISSUE TITLE
Gaunt's Ghosts should be regiment locked

### ISSUE THREAD

**Issue by Korvre** [BSData/wh40k-9e#11667]
Gaunt's Ghosts of the imperial guard can be taken in any regiment when they should they only be available in Tanith detachments

 - OS:Android
 - BattleScribe version 2.03.25
 - Release version 9.6.1

**Comment by Technoblazed** [comment]
1) Tanith isn't currently a thing,
2) They're OFFICIO PREFECTUS, they can be used in any ASTRA MILITARUM detachment without breaking the detachment, but they never gain a Regimental Doctrine anyway.
