### ISSUE TITLE
Imperial Knights, Armiger Helverin can't be given relics

### ISSUE THREAD

**Issue by zululim** [BSData/wh40k-9e#11689]
**Describe the bug**
Battlescribe is saying that Armiger Helverins cannot have a selection of Heirlooms of the relic

**To Reproduce**
My Helverin is in a freeblade lance, super heavy detachment

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/65802052/180016254-eef1fc8c-1556-4a0c-bba1-e4802f3517aa.png)

**Comment by AbonShell** [comment]
Fixed in next release
