### ISSUE TITLE
Aun'va - Leadership Caste

### ISSUE THREAD

**Issue by TylerJHuff** [BSData/wh40k-9e#11680]
**Describe the bug**

Aun'va's Leadership Caste is not properly being resolved when brought into other T'au detachments. Error code : HQ cannot have any selections of Aun'Va

**To Reproduce**

1. Go to T'au Detachments
2. Click on Sept Choice -> Bor'kan
3. Select Aun'va from HQ
4. See Error

**Expected behavior**

Aun'va is included without causing issues based on detachment or subfaction (excluding farsight enclaves)

**Screenshots**

**Device and data (please complete the following information):**

Warhammer 40,000 9.6.1

**Comment by AbonShell** [comment]
#10989 goes into detail as to why it's the way it is
