### ISSUE TITLE
Order of Companions always available

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#11681]
I am on the master data. The stratagem Order of Companions for House Raven is always selectable even when House Raven isn't the selected house
![image](https://user-images.githubusercontent.com/72748875/179866999-3dfda959-d622-45f4-9517-457eb10fbc7a.png)
![image](https://user-images.githubusercontent.com/72748875/179867010-6a06501d-d5ed-43e6-b9b3-b8100c50b90e.png)

**Comment by AbonShell** [comment]
Gdi, okay.
