### ISSUE TITLE
Black Templars Revered Repository allows you to take an extra relic plus the relic for the sergeant

### ISSUE THREAD

**Issue by Alex-40k** [BSData/wh40k-9e#11683]
**Describe the bug**
Revered Repository allows you an extra relic in your characters without using the chapter relic strat in said character, allowing you to take up to 4 character relics in a 2k game.

**Comment by Mad-Spy** [comment]
Are you saying that it should do this and it doesn't, or that it shouldn't do this and it does? It's really not clear from your report.

**Comment by acebaur** [comment]
This is correct and functioning properly
