### ISSUE TITLE
Legends units not available for Chaos Space Marines

### ISSUE THREAD

**Issue by Myrxenary** [BSData/wh40k-9e#11687]
Legends unit are available for other factions like space marines, but missing for chaos space marines. Missing units include Chaos Hellwright, Zhufor the Impaler, etc.

**Comment by Mad-Spy** [comment]
The models which got updated rules yesterday have been added back in for the next release. The FW models don't work with the new rules in the Codex, so I'm not planning to add them again unless they update them
