### ISSUE TITLE
Chaos Space Marines - Balefire Tome Powers

### ISSUE THREAD

**Issue by Squike** [BSData/wh40k-9e#11686]
The Chaos Legionaries with a Balefire Tome, with a specific Mark of Chaos cannot currently select the Mark Psychic Power

Nurgle - Putrid Miasma
Slaanesh - Delightful Agonies
Tzeentch - Skeins of Fate

**Comment by Mad-Spy** [comment]
No, because they get it automatically when you select the relevant Mark and it appears on their datasheet when you do so.

**Comment by Squike** [comment]
@Mad-Spy  so they get two powers? because it throws up an error saying you need to select a power? and what if I want the mark but not the  mark specific power?

**Comment by Mad-Spy** [comment]
Yes. As per the rules, any marked Psyker knows the power of its mark automatically in addition to any others. That's what it says on the Dark Hereticus powers page.
