### ISSUE TITLE
Chaos Contemptor Marks of Chaos

### ISSUE THREAD

**Issue by Squike** [BSData/wh40k-9e#11688]
Chaos Contemptor Dreadnaughts have the "CORE" keyword and should have access to chaos marks.

![image](https://user-images.githubusercontent.com/109665973/180008352-874a0d4d-9b90-49c7-b920-157e1906a8f0.png)

![image](https://user-images.githubusercontent.com/109665973/180007931-33a7619b-3658-48ae-a4f6-8a8d21785518.png)

**Comment by Mad-Spy** [comment]
This is incorrect. You must be CHAOS UNDIVIDED CORE in order to take a Mark. Contemptors do not have CHAOS UNDIVIDED.

**Comment by AbonShell** [comment]
![image](https://user-images.githubusercontent.com/20672472/180009605-3219a2c2-aaf4-4693-848a-b0ed080ae28f.png)
