### ISSUE TITLE
Missing space marine chapter

### ISSUE THREAD

**Issue by Weirwood369** [BSData/wh40k-9e#11695]
The Castellans of the Rift should be available in the list of Ultramarines Successors along with the Emperors Spears the Silver Templars and the Tome Keepers you have in there now. They are all strictly primaris, but in return for that they get their own set of warlord traits and relics they can use in addition to the Ultramarine stuff.

   Their complete rules were introduced in Rift War and will be valid until a new space marine codex comes out. The rules can be found here on Wahapedia

https://wahapedia.ru/wh40k9ed/factions/space-marines/castellans-of-the-rift

**Comment by acebaur** [comment]
Duplicate
