### ISSUE TITLE
flyers?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#117]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Ther Flyer unit entry is missing from several detachments.  So far I've only been able to add a flyer in the flyer aux. detachment.

**Comment by cartag** [comment]
Which ones specifically are the Flyers missing from and which army list are you using to find a flyer in?

**Comment by NecronLord3** [comment]
Specifically I was adding the Helldrake to death guard and regular Chaos marines.  However I pulled up several of the detachments such as the patrol and battalion and none have the flyer category at all.   Also tried the same detachments using Necrons as the faction the flyer option was also absent.

**Comment by Gnofry** [comment]
![image](https://user-images.githubusercontent.com/17345182/27255943-efa43e84-5376-11e7-8a9d-b5ef207e1605.png)

**Comment by Gnofry** [comment]
I am not seeing any issues with flyers. Can you purge your data and recheck? And provide which version of BS you are using and on what platform?

**Comment by skonk** [comment]
The Death Guard force only includes the units specifically listed as being able to have the Death Guard legion keyword.

If you want to add other units to the detachment (which is fine) then you need to use BattleScribes multi-force feature as described in some of the other issue posts.
