### ISSUE TITLE
Ynnari - Troupe Master should have access to Ynnari WL Trait

### ISSUE THREAD

**Issue by Muck1ng** [BSData/wh40k-9e#11702]
Data issue - When selected as part of a Ynnari detachment the Harlequin Troupe master should have access to the Ynnari Warlord trait: WARDEN OF SOULS.   

i can't see anything that would prevent this.

**Comment by Technoblazed** [comment]
> Note that, for the purposes of these craftworld rules, the Ynnari are treated as a craftworld and the YNNARI keyword is considered to be a replacement for the <CRAFTWORLD> keyword

> Each craftworld has an associated Craftworld Warlord Trait. If an **ASURYANI** <CRAFTWORLD> CHARACTER model gains a Warlord Trait, they can have the relevant Craftworld Warlord Trait instead of a Aeldari Warlord Trait
