### ISSUE TITLE
CSM - Word Bearers "Epistle of Lorgar"

### ISSUE THREAD

**Issue by Lotorio** [BSData/wh40k-9e#11700]
**Describe the bug**
The Relic "Epistle of Lorgar" isn't being allowed as an option if you have a supreme command detatchment with Abaddon as warlord.

**To Reproduce**
1. Select CSM "Battalion" & "Supreme command detatchment"
2. Add "Abaddon the Depoiler" to Supreme command detatchment, he is automatically your warlord. Add word bearers for your legion, battle size, CP cost etc.
3. Scroll to Battalion. Add word bearers for your legion, battle size, CP cost etc.
4. Scroll to HQ selections, Select Dark apostle.
5. add "Relic" or "Gift of Chaos". Epistle of Lorgar is not a valid selection.
6. See error

**Expected behavior**
Epistle of Lorgar should be a valid selection, the only stipulation is "Word Bearers Priest", the issue is the supreme command detatchment I think as it seems to work fine when Abaddon is included in the batalion (without the supreme command detatchment)

**Screenshots**

**Device and data (please complete the following information):**
 - BattleScribe version [e.g. 2.03.45]
![Screenshot 2022-07-21 131233](https://user-images.githubus
urcontent.com/109738017/180210889-434eed32-0ade-41fd-8bf8-5461faf412df.jpg)
![Screenshot 2022-07-21 131335](https://user-images.githubusercontent.com/109738017/180211194-6933aebc-315c-40b4-a952-016f428da436.jpg)

 - Release version [Warhammer 40k 9th edition v222]

**Additional context**
There seems to be a few others Word Bearer specific relics missing from the list.

**Comment by Mad-Spy** [comment]
Well, you shouldn't be able to because Abaddon is not a WORD BEARERS WARLORD. Your Warlord must be from the faction if you want to use subfaction relics.

See p77 of the Codex, in the Relics of Chaos paragraph.
