### ISSUE TITLE
Chaos - Death Guard: Poxwalker PL is incorrect at large unit size

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11712]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Poxwalker have the wrong PL when in a pack of 11+ they have 6PL in BS. But after the update only cost 5PL.

**Comment by Mad-Spy** [comment]
![image](https://user-images.githubusercontent.com/29306451/180758226-97e1010b-b52e-4c22-a338-713a3028045c.png)

This is the correct cost as per the latest Power Rating update.

https://www.warhammer-community.com/wp-content/uploads/2020/08/wRzHkacP0NPxYL3d.pdf
