### ISSUE TITLE
Imperial Knights Heirlooms of the Household not showing relics

### ISSUE THREAD

**Issue by SSSlippy** [BSData/wh40k-9e#11722]
When select Heirlooms of the Household no relics show.  See attached screenshot for example.  I am running the version from github master.

![image](https://user-images.githubusercontent.com/22452849/181134733-aec37073-3aa4-42df-b9ae-006e7fd717b0.png)

**Comment by AbonShell** [comment]
While vague, the only one that is actually incorrect is The Magaera, which I Just fixed for next release.
