### ISSUE TITLE
Imperium: Space Marines: Assault Marines shouldn't have access to hand flamer or inferno pistol

### ISSUE THREAD

**Issue by StokieRich** [BSData/wh40k-9e#11728]
Space Marine Assault Squad should not be able to take Hand Flamer or Inferno Pistol. Codex is clear that it is a choice from Pistols list for the Sergeant, but that the 2 normal Special Weapons are one of:
Plasma Pistol and Chainsword // Flamer // Meltagun // Plasma gun

Options for Inferno Pistol and Hand Flamer just need to be removed.

Thanks!

**Comment by acebaur** [comment]
Inferno and hand flamer are valid options from the Deathwatch and Blood Angels chapters

**Comment by StokieRich** [comment]
Hi,

They’re not options for Assault Squad, that’s incorrect, just for the sergeant.

The sergeant’s option is “one weapon from the Pistol list”

The squad itself is a list of options, not open to choose from the pistols list, which would open it to those pistols Death Watch or Blood Angels

**Comment by Mad-Spy** [comment]
@StokieRich seems to be correct. I can't find any reference which allows a standard Assault Marine to swap his weapons for a hand flamer or inferno pistol.

~~In addition, Blood Angels should be able to take 2 plasma or melta _in addition_ to the pistol/flamer swap that other Marines can do, as per the FAQ. Currently, they're limited to two swaps total.~~

**Comment by StokieRich** [comment]
Hmm I'm not sure I follow your second point actually @Mad-Spy 

From what I can see any faction can swap to a Flamer or Plasma Pistol.

Then Blood Angels and only Blood Angels can swap that Flamer for Melta Gun or Plasma Gun.

My understanding is that this would still only give you 2 special weapons in the unit, but that the Blood Angels can use these for Meltaguns and Plasma Guns, whereas non Blood Angels are only Flamers or the Plasma Pistol option.

**Comment by Mad-Spy** [comment]
Yeah, you're right. I misread it.

**Comment by acebaur** [comment]
I see, for some reason they are showing up in the squad as well. I'll look into it
