### ISSUE TITLE
Imperium - Imperial Knights - Heirlooms of the Household stratagem mistakenly no longer gives noncharacters relics

### ISSUE THREAD

**Issue by charlesamor** [BSData/wh40k-9e#11723]
**Describe the bug**
The Heirlooms of the Household stratagem in battlescribe no longer gives noncharacters the option to take relics.  You can work around it by giving a model character, giving them a relic, then taking away character, but that will still result in a warning in battlescribe.  

**Expected behavior**
Heirlooms of the Household should allow noncharacters to have a relic.  The stratagem specifically calls out non-character models.  

"Select one IMPERIAL KNIGHTS model from your army. That model can have one Heirloom Relic, even if they are not a CHARACTER model (this must be a Relic they could have)."

**Device and data (please complete the following information):**
 - Warhammer 40k Data v9.6.2
  Previously, in v9.6.1 this worked correctly

**Comment by AbonShell** [comment]
Fixed in next release.
