### ISSUE TITLE
Ork  FREEBOOTERZ  Klawn rules updated again by GW

### ISSUE THREAD

**Issue by whitewolfmxc** [BSData/wh40k-9e#11720]
https://www.warhammer-community.com/wp-content/uploads/2019/09/BGgBglAmbHKOYysD.pdf?fbclid=IwAR0XDDNDKqI-XM7pn9DhCZx8L-k6XHb_zA7-Cu8JRjKSMKNtLZSt9uZOU_0

now revert back to codex entry as last FAQ update was wrongly updated by GW

which is now +1 to hit (instead of the wrongly updated reroll 1's to hit)

**Comment by Technoblazed** [comment]
This was never changed, same with Kustom Jobs in the data, so no change required.
