### ISSUE TITLE
40k Ultra Marines units missing features.

### ISSUE THREAD

**Issue by Necrel** [BSData/wh40k-9e#11739]
**Describe the bug**

**To Reproduce**
1. Go to '...'make a list
2. Click on '....'add unit
3. Scroll down to '....'select heavy
Happens on Ultra Marines v63
Eradicators are missing in entirely.
Additionally both  lieutenant and Captain from the indominus box are missing the shield options. 

**Expected behavior**
Eradicators can be added and the equipment option are present in the primaris lieutenant and Captain from the indominus box have all their options.
**Screenshots**

**Device and data (please complete the following information):**
 - OS: [e.g. iOS] Google pixel build SQ3A.220705.003.A1
 - 
 - BattleScribe version [e.g. 2.03.45]
 - v2.03.25.338
 - 
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by Mad-Spy** [comment]
Current release version of the data is v64, however, these units haven't changed.

The **Primaris Captain** entry contains the "pistol, sword and Relic shield" loadout from Indomitus.
The **Primaris Lieutenant** entry contains the "neo-volkite pistol, MC power sword and storm shield" loadout.
Eradicators are a Heavy Support choice, and appear as such in the data.

**Comment by Necrel** [comment]
![Screenshot_20220801-034023](https://user-images.githubusercontent.com/110386766/182131143-3c2c7940-ecfd-4661-91ab-e65f8010630e.png)
Eradicators are not a choice for me.

**Comment by Necrel** [comment]
![Screenshot_20220801-034257](https://user-images.githubusercontent.com/110386766/182131474-195cd919-ed5b-4457-a4f3-a90cc7d9fe98.png)
Primaris lieutenant doesn't have an option for nor does it include a relic shield on my end.

**Comment by Mad-Spy** [comment]
1. If that is your only Heavy Support option, there is something wrong with your copy of the data. Marines have nearly 40 Heavy Support options. I suggest you do an update with "delete existing data" checked. Did you not think that mentioning that you can only see one of the many Heavy Support options available in the Codex was worth mentioning?

2. See where it says "Weapon option 1: Master-crafted auto bolt rifle"? Try tapping on the radio button next to it to get to the weapon options for the unit. Anywhere you see a radio button, that is a link to a group of options.

**Comment by Necrel** [comment]
1: deleted and updated data.
Still only have one option for heavy support.

2: I couldn't see it in the selection as all it had was volcan pistol and... But there it is.

**Comment by Necrel** [comment]
On issue 2 I deleted the roster and rebuilt it after the update I now see other options in heavy detachment.
