### ISSUE TITLE
HQ limit not bypassed for chapter command in 40k Black Templars

### ISSUE THREAD

**Issue by CalciferQuinn** [BSData/wh40k-9e#11740]
**Describe the bug**

Since Nephilim update, in Black Templars, when you upgrade a captain to chapter master, it no longer allows it to not count towards your HQ slot like before. 

**To Reproduce**
1. Set up a BT patrol detachment. Add a chaplain and captain. 
2. Upgrade captain to chapter master
3. Add a 3rd HQ captian which should be legal (since once you upgrade the first he doesn't count towards your slot)
4. See error of red exclamation point saying you canning exceed 2 HQ's

**Expected behavior**

This is just a simple fix, after all the massive nephilim changes - this is just a simple hiccup to change back to the way it was before!

**Screenshots**

![image](https://user-images.githubusercontent.com/110244917/181786640-6423b502-f752-4fd0-b25d-b1894d428b62.jpeg)

**Device and data (please complete the following information):**
 - OS: [e.g. iOS] I'm updated latest iPhone 
 - BattleScribe version [e.g. 2.03.45] up to date 
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by CalciferQuinn** [comment]
I wonder if this is all chapters; It's happening is space wolves as well

**Comment by AbonShell** [comment]
So, it counts towards the limit of how many units can be taken in that Force Organization, what it doesn't count is as a captain. ![image](https://user-images.githubusercontent.com/20672472/182253488-3b576374-88d0-40b8-8457-5c69145d61ae.png) ![image](https://user-images.githubusercontent.com/20672472/182253471-ea18ac6a-1d84-467c-b893-822fce05110b.png) 
![image](https://user-images.githubusercontent.com/20672472/182253553-7bbfd492-3562-470c-9383-a34658f1f0ad.png)
As a patrol, you can only have two HQ units.

**Comment by acebaur** [comment]
Make sure you have a battalion as your detachment because it and brigade are the only ones with 3 HQ slots
