### ISSUE TITLE
 Imperium - Adeptus Custodes: QoL request

### ISSUE THREAD

**Issue by chituchituchitu** [BSData/wh40k-9e#11744]
I would like to ask one request.

The Tarsus Buckler doesn't change the save characteristic to 2+ automatically.

Can someone program it for do it automatically?

Thank you guys, you are the best :).

**Comment by Thairne** [comment]
No. I considered doing it though.
It's listed as an explicit ability. There also can be mixed loadouts in the same squad which would make the readout confusing.

**Comment by chituchituchitu** [comment]
Ok, thanks for the answer :).
