### ISSUE TITLE
Warlord Trait stratagem missing for Drukhari characters

### ISSUE THREAD

**Issue by VeaZe** [BSData/wh40k-9e#11746]
**Describe the bug**
When selecting Drukhari characters, there is no option to spend a CP for the Warlord Trait stratagem. 

**To Reproduce**
1. Add a new roster for Drukhari
2. Select Game Type as '4. Chapter Approved: War Zone Nephilim'
3. Add any non-named character and select the 'Warlord' option
4. *No strat appears

**Expected behavior**
There should be an extra option for Warlord Traits. This is the correct behavior as taken from a Grey Knight Grandmaster:
 
![javaw_01c499iEvV](https://user-images.githubusercontent.com/110623613/182901160-cdf0bba8-43b9-4dd5-927f-3b3b7a1b7ac1.png)

**Screenshots**
![javaw_moYk26Rviq](https://user-images.githubusercontent.com/110623613/182901957-848fb4ab-f1a1-4be8-ba87-7b910cec158f.png)

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version: 2.03.21.166
 - Release version: 2.03.21.166

**Comment by AbonShell** [comment]
Already known and tracked via a tracker.
