### ISSUE TITLE
CSM Legionaire with Balefire tome

### ISSUE THREAD

**Issue by Chaosari** [BSData/wh40k-9e#11752]
When selecting their psychic power there are only three options:
Diabolic Strength
Infernal Gaze
Prescience. 

Should be three more?

Death Hex,
Gift of Chaos
Warptime

**Comment by AbonShell** [comment]
Looking at your codex, it says that legionnaires only get access to those three. The data is correct.

**Comment by Chaosari** [comment]
I should read better :)
Thanks
