### ISSUE TITLE
Ultramarines Chapter Champion and Ancient can't be given Relics

### ISSUE THREAD

**Issue by CaptainIdaho** [BSData/wh40k-9e#11759]
The Ultramarines Chapter Ancient and Chapter Champion unit choices cannot be given Relics despite being characters.

**Comment by Mad-Spy** [comment]
Duplicate of #11754

**Comment by CaptainIdaho** [comment]
This wasn't completed along with the other raised issue. Ultramarines Chapter Champion and Chapter Ancient still do not have access to Relics.
