### ISSUE TITLE
Blood Angels - Company Champion Jump Packs

### ISSUE THREAD

**Issue by jaeger527** [BSData/wh40k-9e#11760]
The current Blood Angels data file allows Company Champions to take a jump pack for 25 points. This is no longer an option in 9th Edition; it appears to be a Legends option but it is not marked as a Legends-only choice in the data file. I have not checked all of the other Space Marine chapters to see if this bug is reproduced elsewhere but confirmed it is not present in the Ultramarines file.

**Comment by Mad-Spy** [comment]
Unit is correctly marked as Legends when the Jump Pack is added. Closing.
