### ISSUE TITLE
Tyranid Warlord

### ISSUE THREAD

**Issue by NauFirefox** [BSData/wh40k-9e#11767]
Any Tyranids roster, continues to ask for a warlord even when one is selected if you have a Hive Tyrant as your warlord. 

This bug relates to the 'Hive Tyrant must be your warlord if you have one' rule, but causes a bug where it doesn't seem to count the 'required warlord' as the 'normal warlord'. So it recognizes if you pick a non-tyrant as a warlord and correctly errors, but if you do pick a tyrant, it doesn't see that you have a warlord, even with warlord selected. 

See screenshot for clarity.

![image](https://user-images.githubusercontent.com/15178582/184332677-c8aaeedb-a21c-4c25-ad6e-18713c436b74.png)

Reproduction, any Tyranid roster with a Hive Tyrant, Winged Hive Tyrant, or The Swarmlord.

**Comment by AbonShell** [comment]
Update your data

**Comment by Mad-Spy** [comment]
To clarify, the current released Tyranids data is v105; you have v103. It's best to update your data weekly.
