### ISSUE TITLE
CSM - Skeins of Fate

### ISSUE THREAD

**Issue by p3zd1sp3nx0r** [BSData/wh40k-9e#11766]
**Describe the bug**
Should be Warp Charge Value of 7, not 6

**To Reproduce**
1. Go to a Psyker
2. View Dark Hereticus Discipline
3. View Skeins of Fate at a Warp Power of 6.

**Expected behavior**
Skeins of Fate at a Warp Power of 7.

![image](https://user-images.githubusercontent.com/70374237/184282257-2288ff68-6d11-4edf-9143-f21d87e947b6.png)

**Comment by Mad-Spy** [comment]
Fixed in next release.
