### ISSUE TITLE
Imperium - Adepta Sororitas: Exemplar of the Order not available for Order of our Martyred Lady

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11770]
**File:** Imperium - Adepta Sororitas.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I am not able to select Exemplar of the Order on Canoness when the unit is selected as my HQ and I have Order of our Martyerd lady selected.

**Comment by Mad-Spy** [comment]
Unable to reproduce in current data. The option appears as expected in the "Character Stratagems" group.

![image](https://user-images.githubusercontent.com/29306451/184602037-23cf71de-1fff-4328-9c62-6f8365ebdfa9.png)
