### ISSUE TITLE
Harlequins Relic issues

### ISSUE THREAD

**Issue by Fenglorian** [BSData/wh40k-9e#11778]
Using a second relic on a Harlequins character gives an error that "UNIT cannot have any selections of Treasures of the Aeldari (Harlequins)" even when using the appropriate stratagem. This error goes away when using the Nephilim Relic stratagem a second time on that unit but then gives the error that you can only have one use of that stratagem. 

Harlequins characters are also listing "The Lost Shroud" Ynnari relic as a choice outside of a Ynnari detachment, and selecting this relic does not give any errors as long as the Treasures stratagem has been used to increase relic budget.

**Comment by FarseerVeraenthis** [comment]
The first part should be fixed on master and ready for release. The second part I'll have a look into :+1:
