### ISSUE TITLE
Treasures of the Aeldari not working correctly with Nephilim 

### ISSUE THREAD

**Issue by akakorlandril** [BSData/wh40k-9e#11777]
**Describe the bug**
1) When selecting Treasures of the Aeldari the relic option doesn't appear on characters

2) Can't have a regular CP relic and a treasures of the Aeldari relic without some kind of error

**Expected behaviour**
Not sure, maybe Treasures of the Aeldari should be an in character option like Champion of the Aeldari is?

**Comment by FarseerVeraenthis** [comment]
Argh.
I might know what is causing this but I'm not sure how to fix it... I'll have a look and see what I can do 🙂
