### ISSUE TITLE
Orks patrol detachment cannot take dedicated transport

### ISSUE THREAD

**Issue by Tynam** [BSData/wh40k-9e#11771]
The Orks Patrol Detachment does not seem to have the Dedicated Transport category - it is not possible to add a Trukk.

Found on
 - BattleScribe 2.03.21.166
 - 40k v9.6.3, Orks v54.

**To Reproduce**
1. Create Ork list.  Add Patrol Detachment.
2. Add any infantry Troops.
3. Attempt to add Trukk.

**Expected behavior**
Detachment should have Dedicated Transport section allowing Trukk.  One Transport selection should be legal for each Infantry unit in the detachment.

**Comment by AbonShell** [comment]
![SmartSelect_20220813-125830](https://user-images.githubusercontent.com/20672472/184503682-216ac3e2-e930-4707-9838-06e937773cd0.jpg)
 Unable to replicate

**Comment by Mad-Spy** [comment]
I suspect you're on desktop. Maximise your Battlescribe window. The app can't scroll down far enough to see the Dedicated Transports if you don't.
