### ISSUE TITLE
Imperium - Astra Militarum | Creed compels to take the warlord trait

### ISSUE THREAD

**Issue by Dragdord** [BSData/wh40k-9e#11776]
If Lord Castellan Creed is selected to be warlord, battlescribe requires user to give to him warlord trait, but trait is optional, not necessary.

**Comment by Technoblazed** [comment]
8th edition codex issues I'm afraid:

> If a named character with a specific regiment keyword is your Warlord, they must be given the associated Warlord Trait

Note the must, so if they are your warlord, you MUST use the strat and MUST take their trait.
