### ISSUE TITLE
Imperium - Space Marines: Ancient in terminator armour cannot select relics

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11787]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Warhammer 40k game system. Space marine white scars v47 battalion. Elites section. Ancient in terminator armor has no “relic” or “relic of the chapter” selection options, even if selected as warlord. Problem most likely in all current space marine rosters.

**Comment by acebaur** [comment]
Update your data.
