### ISSUE TITLE
Ultramarines Chapter Champion and Chapter Ancient unable to be given Relics when using Nephilim rules

### ISSUE THREAD

**Issue by CaptainIdaho** [BSData/wh40k-9e#11783]
The Ultramarines Chapter Ancient and Chapter Champion do not have the Relics of the Chapter option to enable them to receive Relics.

This issue was previously attached to another issue, regarded as a duplicate. However, when that issue was resolved, neither the Ultramarines Chapter Champion nor Chapter Ancient were fixed.

**Comment by Mad-Spy** [comment]
These models have no "Stratagem: Relic" entry which means they can't unlock relics when using Nephilim rules.

**Comment by CaptainIdaho** [comment]
I'm not very techy but you're totally right, I just tried it without the War Zone Nephilim rules and it still worked, so yes that is the problem. Well identified.
