### ISSUE TITLE
Imperium-Adeptus Astartes Scout Sergeant wrong pts value of Scout sniper rifle 

### ISSUE THREAD

**Issue by Dzejra** [BSData/wh40k-9e#11781]
Imperium-Adeptus astartes-Ultramarines v.64 Scout squad. Bad point value for wargear Scout sniper rifle. The points were adjusted for the unit, but the Scout sniper rifle was left with a bad value for the Scout sergeant. Correct is 0 pts. It is stated In MUNITORUM FIELD MANUAL 2022 MK II there is a sentence: “weapons and other wargear not listed in a unit’s entry cost no additional points to include in that unit”

Device and data:

OS: iOS 15.6
BattleScribe version 2.03.15

Screenshots
![IMG_8851](https://user-images.githubusercontent.com/58650466/185191317-49667046-7981-42ce-8b8a-12eb437a3bf2.PNG)

**Comment by AbonShell** [comment]
Update your data 
![image](https://user-images.githubusercontent.com/20672472/185193722-6ffb9369-2063-455b-8f19-b0a55480ab62.png)

**Comment by AbonShell** [comment]
Oh I see, my bad
