### ISSUE TITLE
Astra Militarum - Veteran Sergeant points values incorrect

### ISSUE THREAD

**Issue by noobzor99** [BSData/wh40k-9e#11789]
The Astra Militarum Veteran Sergeant in Veteran squads can take a number of upgrades, none of which have a points value in the latest munitorum field manual.  Battlescribe is still showing these options costing points.

The options in question are power axe, power maul, power fist, boltgun, bolt pistol, plasma pistol.

**Comment by Mad-Spy** [comment]
Fixed in next release.
