### ISSUE TITLE
Can't update data

### ISSUE THREAD

**Issue by Nyx1824** [BSData/wh40k-9e#11782]
I always get the same error when trying to update my data. Posted here months ago hoping for help and as of today have received none. Please fix the issue so that I can actually use the service. It tells me there's a corrupted file for some age of sigmar cat army even if I don't have age of sigmar in my rosters or data files.

**Comment by AbonShell** [comment]
Take a look at https://github.com/BSData/wh40k/issues/1706 It isn't anything that data contributors can do or change.

**Comment by alphalas** [comment]
@Nyx1824 make sure when you update your data, you check the box for delete data before updating
