### ISSUE TITLE
Crimson Slaughter Kranon(etc) missing

### ISSUE THREAD

**Issue by PastaboyLuc** [BSData/wh40k-9e#11797]
**Describe the bug**
as title say, after last update I can't insert any of the crimson slaughter option, i could do it until last month (last update was april 2022), anyway right now i can't find any choice in the battlescribe app,

meanwhile I checked the datafile here on github and there are some datas about Krnaon, Vrosh, Draznicht's etc, but it says "hidden: false or true depending on some different entry

I would really like to build back crimson slaughter in the roster, I'm sure someone else also has the same necessities/desire

I am not a developer so i don't have much knowledge about codes, hope the explanation is clear, and this is in the right place, 

thanks in advance everyone

**Comment by Mad-Spy** [comment]
None of those models have valid 9th edition rules since the new Codex came out. Hence, they are no longer in the data set.
