### ISSUE TITLE
Duplicate id in catalogue links in Space Wolves catalogue

### ISSUE THREAD

**Issue by EllieTellie** [BSData/wh40k-9e#11795]
**Describe the bug**
This is kind of a minor issue, but I noticed there is two catalogue links with the same id which is the only occurrence of a conflict that I could find in the whole 40k data. The id is: **162d-039c-7e19-1259**. It's two catalogue links one pointing to **Imperium - Space Marines** and the other to **Imperium - Officio Assassinorum** any chance of a fix?
I should add it's in Imperium Space Wolves catalogue.

**Screenshots**
![image](https://user-images.githubusercontent.com/38538076/186671079-aedf0ed6-121b-4092-a048-9fdbc239afc0.png)

**Comment by Mad-Spy** [comment]
It's actually a useless (and unused) link anyway because that catalogue is being pulled in via the Marines library anyway, but I've removed it.
