### ISSUE TITLE
Bug report: Imperium - Ultramarines.catz

### ISSUE THREAD

**Issue by GinSoakedBoy** [BSData/wh40k-9e#11796]
**Describe the bug**
Named Ultramarines characters that are selected as Warlords give an error when no Warlord trait is selected when gametype is set to Nephilim. 

**To Reproduce**
Create an Ultramarines roster and set and named Ultramarines character as the Warlord. 

**Expected behavior**
For Nephilim, a warlord trait is not required for named characters. 

**Screenshots**
![image](https://user-images.githubusercontent.com/13789412/186672186-27066afa-0c52-4e65-a2ca-ecc831ec932a.png)

**Comment by acebaur** [comment]
The wording on 8th SM supplements is such that you are required to give them their trait if they are Warlord. So if you are playing Nephilim then you have to pay a CP for it. Working as intended

**Comment by GinSoakedBoy** [comment]
The Codex states that if they use a warlord trait it has to be the one specified. In Nephilim, you don't have to pay the CP to give a warlord trait to a named character.

**Comment by GinSoakedBoy** [comment]
This is not "working as intended" but Nephilim lets you choose not to pay to take a warlord trait, even for 8th edition codexes.

**Comment by alphalas** [comment]
No, it does not override what the codex says. If you select a eighth edition character as warlord, you must take their warlord trait. There has been no FAQ or otherwise that says that is not still in effect.
