### ISSUE TITLE
Aeldari - Craftworld - Unable to add multiple Relics in nephalim without errors

### ISSUE THREAD

**Issue by fox5s** [BSData/wh40k-9e#11799]
**Describe the bug**
Adding the Stratagem: Treasure of the Aeldari does not unlock the Relic options.

**To Reproduce**
- Create an Aeldari - Craftworlds detachment
- Set game type to "Chapter Approved: War Zone Nephilim"
- Add Battle Size Configuration and set it to 2k points
- Add two HQ units that can receive relics (for example, an Autarch and Farseer)
- Add the "Stratagem: Treasure of the Aeldari" from the left list
- Click either HQ unit and see no option to add the Relic
- NOTE: "Strategem: Relic" is available and works correctly but using it twice (correctly) throws an error.

**Expected behavior**
There should be an option to add one Relic with "Stratagem: Relic" (which currently works) AND the option to add additional Relics via "Stratagem: Treasure of the Aeldari" depending on the battle size

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version 2.03.21
 - Release version not totally sure but I just updated it and the Manage Data screen says Warhammer 40,000 v9.6.4

**Additional context**
You can get the list to have multiple Relics with the correct CP costs by initially adding "Stratagem:Relic" multiple times and then unchecking it after selecting the relic. This throws errors but will result in what should be a legal list.

**Comment by Mad-Spy** [comment]
This would appear to be fixed as Treasures of the Aeldari is no longer a list level Stratagem, but is is selected on the model which is being assigned the Relic.
