### ISSUE TITLE
Imperium - Adeptus Astartes - Blood Angels: Astorath can't take Warlord Statagem under nephilim rules

### ISSUE THREAD

**Issue by Guy-Markman** [BSData/wh40k-9e#11790]
**Describe the bug**
If you choose the gametype as Nephilim and choose Astorath as your Warlord, you can't give Astorath the Stratagem: Warlord Trait -1CP.
You can choose it under every other gametype.

**To Reproduce**
1. Create Imperium - Adeptus Astartes - Blood Angels roaster (any detachment that can take HQ)
2. Change Gametype to 4. Chatper Approved: War Zone Nephilim.
3. Add Astorath to you roaster.
4. Under Options, choose Warlord 

**Expected behavior**
Under options you will be able to choose Stratagem: Warlord Trait -1CP, which when you choose will add option to choose Warlord Trait 3. Soulwarden

**Device and data (please complete the following information):**
 - OS: Check under both IOS and Linux BattleScribe
 - BattleScribe version Linux 2.03.21 and IOS 2.03.15
 - Release version Warhammer 40,000 v9.6.4

**Comment by Mad-Spy** [comment]
Fixed by https://github.com/BSData/wh40k/commit/edb058ced7e43b5b95392c507b2c329667c4926e
