### ISSUE TITLE
Space Wolves Entry for Every Model

### ISSUE THREAD

**Issue by GwenNealon** [BSData/wh40k-9e#118]
**File/Catalogue:** 

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** No

**Disclaimer:** I have never worked on making the data for the repositories before, so I don't know if there is some style guide that I'm suggesting against, but I thank you all for the work that you're doing and that you might hear me out.

**Description:** I don't know if this is supposed to be a bug, but for the Space Wolves, many units such as Wulfen, Long Fangs and Grey Hunters are formatted such that adding a new model to the unit adds a new branch underneath the unit. This is good for units such as Thunderwolf Cavalry or Wolf Guard where each individual model can be specially equipped, but for units such as Wulfen, Long Fangs and Grey Hunters where there is mostly just one choice to be made for each unit, I think it would be more streamlined to have a selection of X number of units with Y equipment instead of having a new branch for each model. I understand that you also can choose which models to have chainswords for Grey Hunters or which models to have autofrag launchers for Wulfen, but I think that also would be easier as a single value of 0 to max on the unit menu.

**Comment by penguin20000** [comment]
I'm aware of this and will work in making it more streamlined. 

The primary focus was getting everything in there and at least functional for the release :)

**Comment by Gnofry** [comment]
#125 would be essentially the same issue.
