### ISSUE TITLE
In Chaos Space Marines armies in 40k, Chosen units can include 1 powerfist for every 5 models

### ISSUE THREAD

**Issue by TarPalantir66** [BSData/wh40k-9e#11807]
When building Chaos Space Marines army lists, there is one option missing, according to the latest FAQ:

Page 161 – Chosen, Wargear Options
Add the following bullet point:
‘For every 5 models in this unit, 1 Chosen model equipped with a
boltgun can have its accursed weapon replaced with 1 power fist.
That model’s boltgun cannot be replaced.’

This wargear option is not available in the current version of the repository.

**To Reproduce**
1. Go to elite options
2. Click on the "plus" sign for chosen
3. Click on the tick mark to go back
4. Click now on the Chosen option that has appeared.
5. Click on a single chosen option right under "4x Chosen"
6. There should be the option to replace the "accursed weapon" with a "powerfist"

**Expected behavior**
Where it reads "Accursed weapon", there should be an option to replace it with a power fist.

**Screenshots**
I added a screenshot
![Screenshot](https://user-images.githubusercontent.com/112504421/187496469-9020c3e2-6f8a-401b-8177-95f9fecbcaeb.jpg)

**Device and data (please complete the following information):**
 - OS: Android 8.0.0
 - BattleScribe version 2.03.25.338

**Comment by Mad-Spy** [comment]
Already done. Will be in next release.

**Comment by TarPalantir66** [comment]
Ok. In that case, thanks a lot. 

    En martes, 30 de agosto de 2022, 19:07:55 CEST, Iain Launchbury ***@***.***> escribió:  
 
 


Already done. Will be in next release.
