### ISSUE TITLE
Imperium - Grey Knights: Ven Dread is missing "Charge of the Ancients" stratagem

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11809]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** The Dreadnaught & Venerable Dreadnaught do not have an option for the Combat Weapon + Heavy Flamer alternative equipment or the Preservers brotherhood Stratagem "Charge of the Ancients"

**Comment by Mad-Spy** [comment]
Dreadnought arm weapon options are available when drilling down into the arm.

Standard Dread does have the stratagem, but the Ven Dread is missing it.

**Comment by RespectableJack** [comment]
The Ven dreadnought can't take Charge of the Ancients as it is an Honored Knight and does not have the Brotherhood keyword

**Comment by tekton** [comment]
That is correct!
