### ISSUE TITLE
BA can take Relic of the Chapter strategem under Nephilim rules (on top of the 3xRelic strategem)

### ISSUE THREAD

**Issue by SimonasBanys** [BSData/wh40k-9e#11812]
**Describe the bug**
Blood Angels under Nephilim rules are able to take Relic strategem 3 times and then take multiple Relic of the chapter strategem (did it 5 times before I decided its enough)
**To Reproduce**
1. Start a Blood Angels Army
2. Select Warzone Nephilim rules
3. Add 3 Relic strategems to characters in the army
4. Add more characters and give them all Relic of the Chapter strategem

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/31985858/187793099-f1d22e65-59a0-4d7f-b010-8b37d0b556cd.png)
![image](https://user-images.githubusercontent.com/31985858/187793420-bfbafb52-bc80-4670-bd1d-6ce9de2d0e2e.png)

**Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version 2.03.21
 - Release version 9.6.4

**Comment by acebaur** [comment]
Yes and it throws an error telling you that you have too many so it's working correctly.

**Comment by SimonasBanys** [comment]
@acebaur if you want I can open a new army where I dont go over the org slot limit and it doesnt throw that error

**Comment by SimonasBanys** [comment]
![image](https://user-images.githubusercontent.com/31985858/187795752-fd77fef6-1605-4039-b4a9-9b315367af83.png)
so much relic of the chapter (way over limit and no errors)
