### ISSUE TITLE
Chaos - Daemons: Attacks incorrect for Be'lakor and Soul Grinder

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11835]
**File:** Chaos - Daemons.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** Be'lakor, Daemon v223 in a Patrol Detachment for Slaanesh or Khorne (only tested these two).

Be'lakor's Attacks in the Codex states bracketing 6 / 5 / 4.
BS Data says bracketing 8 / 6 / 4.

Soul Grinder, Daemon v223, again in Slaanesh and Khorne Detachments (Patrol).

Attacks in the Codex states Non-Bracketing drops, in 5 / 5 / 5 on his Attacks.
Attacks in BS states Non-Bracketing drops, in 7 / 7 / 7 on his Attacks.

**Comment by Mad-Spy** [comment]
Be'lakor already fixed for next release.
Soul Grinder Attacks are correct in current release. OP would appear to be looking at the Ld values.
