### ISSUE TITLE
Errors with lesser daemons unit size

### ISSUE THREAD

**Issue by maveb** [BSData/wh40k-9e#11839]
**Describe the bug**
- (Bloodletters/Blue Horrors/Daemonettes) unable to increase/decrease unit size

**To Reproduce Bloodletter bug**
1. Create an army list of Chaos Daemons - Battalion Detachment
2. Click on (Bloodletters/Blue Horrors/Daemonettes) under Troops
3. Click on (Bloodletters/Blue Horrors/Daemonettes) in the detachment
4. See missing unit size options in the right menu.

**Expected behavior**
A unit options to increase/decrease the amount of models in a unit

**Device and data (please complete the following information):**
 - Version V9.6.6
 - IOS/Windows/Linux

**Comment by Mad-Spy** [comment]
It would appear that you have misread the Codex, which you obviously have, of course. None of those units can go above 10 models.

**Comment by maveb** [comment]
In that case with Bloodletters the: "You can add 1 to hit rolls made for this unit whilst it contains 20 or more models." Has been forgotten to be removed.
