### ISSUE TITLE
Bloodletters numbers

### ISSUE THREAD

**Issue by Jhotaro25** [BSData/wh40k-9e#11831]
Blood letter unit cannot add more than 10models when they should be able to.

**To Reproduce**
1. Go to chaos demons
2. Click on troop
3. Scroll down to bloodletters
4. See that bloodletters can only take a max of 10 models

**Expected behavior**
Change it so bloodletters can take up to 20 models

**Screenshots**
![image](https://user-images.githubusercontent.com/108304170/188508279-0d4fe9c9-e5d2-4f93-aa37-256ab4c77d25.png)

**Device and data (please complete the following information):**
 - OS: [iOS]
 - BattleScribe version [e.g. 2.03.15]
 - Release version [e.g. v9.6.6]

**Additional context**

**Comment by acebaur** [comment]
They are 10 only in a squad now

**Comment by Jhotaro25** [comment]
It still says they get a bonus for have 20 in a squad in the app then.

**Comment by Mad-Spy** [comment]
> It still says they get a bonus for have 20 in a squad in the app then.

Fixed in next release.
