### ISSUE TITLE
Daemon Prince of Chaos can't take relics when using Nachmund gametype

### ISSUE THREAD

**Issue by siaoidiot** [BSData/wh40k-9e#11844]
The checkbox for "Relics of the Impossible Fortress" does not show on the options for a Daemon Prince of Chaos. I am using a Lord of Change as the warlord.
![image](https://user-images.githubusercontent.com/14965840/189331442-3e4eaab7-800e-475f-91c0-1987a1efcdca.png)

**Comment by Mad-Spy** [comment]
Fixed in next release.
