### ISSUE TITLE
Chaos Space Marines: Dark Apostle, Chosen, and World Eaters need updates to reflect rules changes in FAQ.

### ISSUE THREAD

**Issue by NottanAjin** [BSData/wh40k-9e#11846]
As of the most recent FAQ:

A Dark Apostle's Dark Disciples are now T4.

For every 5 models in the unit, Chosen may replace an accursed weapon with a power fist (non-Champion, costs 0 points until cost is properly established).

World Eaters cannot take any Psykers; while listbuilding currently properly forbids Masters of Possession and Sorcerers, Dark Communes also need to be forbidden and Legionaries cannot take Balefire Tomes.

**Comment by Mad-Spy** [comment]
Your first two points were fixed in release 9.6.5,, released on 31st August.

The psykers will be hidden in the next release.
