### ISSUE TITLE
Chaos Daemons - Relic assignment to Slaanesh vehicle bug

### ISSUE THREAD

**Issue by RemcoVanDerVeen** [BSData/wh40k-9e#11854]
**Describe the bug**
The codex describes limits on relics for vehicles of Khorne, Nurgle and Tzeentch, but not for Slaanesh. Therefore, they should be able to be given relics. See quote from the new Chaos Daemons codex below.

**To Reproduce**
1. Add a Tormentbringer on Hellflayer and a Tranceweaver
2. Make one the warlord and look for the relics strategem
3. The Tormentbringer can't have one, but the Tranceweaver can.

**Expected behavior**
Both models should be able to take relics.

**Device and data (please complete the following information):**
 - OS: Android, Windows 10
 - BattleScribe version [e.g. 2.03.25.338]
 - Chaos Daemons file v118

**Additional context**
Quote from the relics section for Nurgle:
"Named characters and Vehicle models cannot be given any of the following Relics." (page 94)

Quote from the relics section for Slaanesh:
"Named characters cannot be given any of the following Relics." (page 110)

**Comment by AbonShell** [comment]
Fixed in current release, update your data
