### ISSUE TITLE
Imperium - Adeptus Mechanicus: Relic allowance not incrementing correctly

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11857]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** On a Strikeforce (2000pt) list, using the standard, Eternal War gametype, the roster says there are 'too many relics selected' when the selections should be valid. x1 default for Warlord, x2 use of Archeotech Specialist Stratagem for a total of 3. Roster Error claims there is a limit of two.

**Comment by Mad-Spy** [comment]
@Thairne the repeat on the modifier is pointing to the strat itself, rather than the counter inside it.
