### ISSUE TITLE
Adeptus Mechanicus: The Purgation's Purity relic should replace Radium Serpenta

### ISSUE THREAD

**Issue by MLPaladin888** [BSData/wh40k-9e#11856]
**Describe the bug**
When a Skitarii Marshal takes the relic, The Purgation's Purity, it should replace the Radium Serpenta that they normally have.

**To Reproduce**
1. Add Skitarii Marshall to list
2. Take Strategem to allows a ADEPTUS MECHANICUS CHARACTER to take a relic (i.e. Nephilim Strategem: Relic, Archeotech Specialist)
3. Give Skitarii Marshall The Purgation's Purity
4. View Roster or hover over the Skitarii Marshall in the list
5. See that they still have their Radium Serpenta, as well as The Purgation's Purity that was taken.

**Expected behavior**
If a Skitarii Marshall takes the relic, The Purgation's Purity, it should no longer have a Radium Serpenta

**Device and data (please complete the following information):**
 - Windows 10
 - BattleScribe version 2.03.21
 - Release version 9.6.7

**Comment by Mad-Spy** [comment]
The data structure doesn't easily allow us to make this happen, so it generally doesn't. Most weapon replacement relics do not visually replace the weapon; you need to do it yourself.
