### ISSUE TITLE
Astra Militarum - Tank Ace options are not appearing correctly

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#11852]
**Describe the bug**

- Using the stratagem to grant a tank a Tank Ace ability doesn't work.
- Making a non-vehicle character your Warlord and not taking a Warlord trait does not allow a Tank Ace ability to be taken on any eligible unit.

**To Reproduce**
1. Add a non-vehicle character and an eligible Tank Ace unit to your roster
2. Make the non-vehicle character your Warlord, but don't take any traits
3. Add the Tank Ace stratagem to your roster
4. Tank Ace options do not appear on any units

**Expected behavior**
Tank Ace options should appear in either scenario

**Screenshots**
N/A

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version v2.03.21
 - Release version: Imperium - Astra Militarum v312 (checked both live and unreleased)

**Additional context**
This affects all modes of play, including Eternal War and Nephilim.

**Comment by Gingrel** [comment]
To add to this, even with a VEHICLE warlord (Tank Commander) I don't see any Support Aces options appear on the relevant units.

**Comment by ColonialAF** [comment]
Likely moot with the new codex release
