### ISSUE TITLE
Slaanesh vehicle characters cant get relics

### ISSUE THREAD

**Issue by p5freak** [BSData/wh40k-9e#11850]
Some slaanesh characters like the tormentbringer on exalted chariot, tormentbringer on seeker chariot, tormentbringer on hellflayer, etc. cant use the relic stratagem from the codex daemons. They are vehicles, but there is no restriction in the daemon codex that slaanesh vehicle characters cant take relics.

**Comment by Mad-Spy** [comment]
There is for every god except Slaanesh and I missed that they were allowed. However, it's fixed in the current release.
