### ISSUE TITLE
Red corsairs Lord discordant able to take black rune of damnation relic

### ISSUE THREAD

**Issue by xenoterracide** [BSData/wh40k-9e#11868]
**Describe the bug**
Red corsairs Lord discordant able to take black rune of damnation relic.

Unless I missed an FAQ, possible it says that this can be given to a cultist unit. Obviously a Lord discordant is not.

![Screenshot_20220918-173130.png](https://user-images.githubusercontent.com/5517/190928829-25907345-cbe2-4960-be9f-44443d92a801.png)

**Comment by Mad-Spy** [comment]
"Can", not "can only". Most CSM Relics can't be given to Cultists. Some have an explicit rule to say that they can. The Black Rune is one such Relic.
