### ISSUE TITLE
[Anon] Bug report: Aeldari - Aeldari Library.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11865]
**File:** Aeldari - Aeldari Library.catz

**BattleScribe version:** 9.06.07

**Platform:** Android

**Dropbox:** No

**Description:** When using Drukhari like a Succubus at Ynnari I can only give her a warlord Trait when Warlord. Also if I select her as Warlord others don't get treasures or champion of the aeldari to choose.

**Comment by Mad-Spy** [comment]
This sounds correct. Both of those Stratagems only work on ASURYANI or HARLEQUINS characters and require the Warlord to have one of those keywords. Including DRUKHARI characters in an Ynnari Detachment does not grant them either or those keywords.
