### ISSUE TITLE
Imperium - Imperial Knights characters forced to be warlords

### ISSUE THREAD

**Issue by SpencerMycek** [BSData/wh40k-9e#11863]
**Describe the bug**
Imperial knight models/units made to be characters (knight lance/knight baron strat), are forced to be warlord (Error indicates unit/model needs to make 1 more selection of warlord) when they are not required by either rule

quote: Knight Lances
“If this Detachment is a [Super-heavy Detachment](https://wahapedia.ru/wh40k9ed/the-rules/core-rules/#Super-heavy-Detachment), or if you are playing a Combat Patrol battle and this Detachment is a [Super-heavy Auxiliary Detachment](https://wahapedia.ru/wh40k9ed/the-rules/core-rules/#Super-heavy-Auxiliary-Detachment), select one ARMIGER-CLASS, QUESTORIS-CLASS or DOMINUS-CLASS model in this Detachment. That model gains the CHARACTER keyword.”

Knight Baron is similar in that the chosen model gains the warlord trait but does not count as a warlord otherwise

**To Reproduce**
1. Create and Imperial Knights Army
2. Super Heavy Detachment
3. Add Canis Rex (to avoid once per detachment restriction of Knight Lances) and make warlord
4. Add any other unit/model, and select either “Knight Lances” or “Knight Baron”5. 
5. Error indicates that unit must be chosen as warlord
6. This error also occurs if you have a second detachment, and try to make a knight a character there

**Expected behavior**
Knight Baron and Knight Lances just allow you to make a knight a character, and do not force you to choose them as warlord
Imperial Knight characters are not required to be warlords, unless I read the rules incorrectly.

**Device and data (please complete the following information):**
 - OS: IOS 15.6.1
 - BattleScribe version [e.g. 2.03.15]
 - Release version Imperial Knights v98

**Comment by AbonShell** [comment]
Update your data. Latest version is v104 and that bug was fixed in v99
