### ISSUE TITLE
Matched Play - Nephilim - Necrons - Secondary Objectives - Ancient Machineries/Purge the Vermin

### ISSUE THREAD

**Issue by Chris-B-Chicken** [BSData/wh40k-9e#11874]
Hey all. 
Saw an error with the Ancient Machineries Secondary in Battlescribe, if Nephilim is selected as Game Type.

Is it possible with an "if" clause, to change the text of the secondaries?

The Problem:
Ancient Machineries:
In Codex: You get 3 Points for the secondary after next CP with succesful action.
In Nephilim: You get 4 Points for the secondary at end of turn, if the unit performing the action has obsec. Otherwise, after next Command Phase.

Purge the Vermin:
In Codex: 2 Points for each table quarter, that does not have any enemy units (excluding AIRCRAFT units) wholly within it. Cannot be scored in first turn.
In Nephilim:
At the end of your turn:
- Score 1 victory point for each table quarter that has no enemy units (excluding AIRCRAFT units) wholly within it.
- Score 1 victory point if there are no enemy units (excluding AIRCRAFT units) wholly within your deployment zone.

I hope i explained it good enough. Thanks all :)

**Comment by Chris-B-Chicken** [comment]
[Select Necrons and Scroll down or use provided links below (Wahapedia.ru)](https://wahapedia.ru/wh40k9ed/the-rules/war-zone-nephilim-grand-tournament/#Nephilim-Secondary-Objectives)
[Wahapedia.ru Rule Ancient Machineries (Select Necrons before)](https://wahapedia.ru/wh40k9ed/the-rules/war-zone-nephilim-grand-tournament/#No-Mercy-No-Respite)
[Wahapedia.ru Rule Purge the Vermin (Select Necrons before)](https://wahapedia.ru/wh40k9ed/the-rules/war-zone-nephilim-grand-tournament/#Battlefield-Supremacy)

If I'm not allowed to link, please delete this post or tell me :)

**Comment by DrTobogganMD** [comment]
Side note: I hate nephilim. There's too many damn versions of the same game to account for now.

**Comment by Chris-B-Chicken** [comment]
Thanks guys! I can script a little, but not delevop software. If so, i would help you mate, lots of stuff i know... 
Leaving love behind <3
