### ISSUE TITLE
Imperium - Adeptus Astartes: Thunderfire Cannon's Techmarine Gunner cannot get WLTs or Relics

### ISSUE THREAD

**Issue by Citronnade** [BSData/wh40k-9e#11881]
**Describe the bug**
This is the same as the closed bug #11086, but I can replicate it.

**To Reproduce**
1. Create a new Patrol detachment of marines.  I chose IF.
2. Pick some arbitrary options to remove validation errors.  The bug appears on both Nachmund and Nephilim game types.
3. Add a Techmarine (HQ) and a Thunderfire Cannon (HS).  
4. Make someone a Warlord.  Play around with the various requisition stratagems--Hero of the Chapter, Relic of the Chapter, Relic, Warlord Trait, Sentinel of Terra, in all their combinations, on both the Techmarine and the Techmarine Gunner in the TFC.
5. The HQ Techmarine can choose options as expected.  The Techmarine Gunner properly validates the stratagems, but no options show up on him or in any of the subentries of the TFC to pick relics, WLTs, etc.

**Expected behavior**
The Techmarine Gunner should be able to take WLTs and relics like other characters.

**Screenshots**
![image](https://user-images.githubusercontent.com/2671007/192077504-35f6ad77-ab0f-480c-babb-b013d8bb92eb.png)

**Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version 2.03.21
 - Release version v9.6.7.  Catalogue v223, Imperial Fists v55.

**Comment by WindstormSCR** [comment]
Unfortunately this is a limitation of the battlescribe application and the way space marines have to be implemented to preserve any reasonable sanity.  So for this edge case unfortunately I would recommend using the stratagems to check CP then making a manual note of the selection.
