### ISSUE TITLE
Chaos Daemons - Khorne: Blootletters cannot increase squad size

### ISSUE THREAD

**Issue by JKFrost11** [BSData/wh40k-9e#11884]
When creating a Chaos Daemons army list, I cannot add more Bloodletters onto a unit; it is stuck at strictly 10 Bloodletters as there is no option to increase the number.

**To Reproduce**
1. Go to a Chaos Daemons army list that features Bloodletters
2. Click on a unit of Bloodletters
3. See error

**Expected behavior**
I would expect a field that allows for adding more models to the unit.

**Device and data (please complete the following information):**
 - OS: Windows 10 64-bit
 - BattleScribe version: 2.03.21
 - Release version v9.6.8

**Comment by Valorcalls** [comment]
Yes that would be how the new codex has the unit written. It's not a thing you can do anymore.
