### ISSUE TITLE
Imperium - Astra Militarum: Problems with Tank Commander Relics and Custom Regiments

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11883]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** I can't give relics to tank commanders and I can't select custom regiments without an error for Astra millitarum

**Comment by Mad-Spy** [comment]
Relics appear to be working fine in current release.

Choosing a custom regiment requires you to select "None" as your Regimental Doctrine.
