### ISSUE TITLE
Leagues of Votann - heavy weapons warriors do not gain the additional cost for ion blasters

### ISSUE THREAD

**Issue by crazytobuildmc** [BSData/wh40k-9e#11882]
The cost per model for heavy weapons Hearthkyn is 11pts for both autoch-pattern bolter and ion blaster squads in the data file, where it should be 11pts for a bolter squad and 12pts for an ion blaster squad.
Ruleswise you pay the initial +1pt per model for everyone to take blasters, then pay for the weapons on top of that.

EDIT: this also applies to melee weapons on an ion blaster squad's Theyn.

**Comment by acebaur** [comment]
That's not how points costs work. You only pay points for weapons you have. They don't have to pay 1 point for a gun they no longer have.
