### ISSUE TITLE
Chaos Thousand Sons Cult-specific Spells currently don't appear for psychic units that get them (not magnus, ahriman, tzaangor shaman).

### ISSUE THREAD

**Issue by josiahbones** [BSData/wh40k-9e#11890]
Thousand Sons Cult-specific Spells (of which there are 9) don't appear in the list for those that get them (not magnus or ahriman, as they don't actually belong to a specific cult). This should be an auto-addition based on cult selection at the detachment level. This is a subtle issue but could be fixed for completion sake (I note warlord traits and relics all appear correctly as options based on cult) and to complete the psychic implementation for TS, and improved whole integration with 40kroller. It would also help clearly demonstrate that the named characters + shaman indeed don't get access to cult spells (something I hadn't realised myself until recently). Given spells and their rules are fully articulated in the rest of the data, I think it makes sense that this feature be integrated.

**Comment by Mad-Spy** [comment]
The Cult spells already appear on the output after selecting a Cult, see the screenshot below of a Cult of Magic Sorcerer. You don't have to select them.

![Screenshot_20220927-063904](https://user-images.githubusercontent.com/29306451/192441418-cbefb1a3-341b-4ddc-9a31-84f439e0abb2.png)

**Comment by josiahbones** [comment]
Quite right. The issue I discovered is on the end of the app that integrates this data (40kroller). Apologies for the dud report.
