### ISSUE TITLE
Imperium - Inquisition: Acolyte needle pistol cost is incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11892]
**File:** Imperium - Inquisition.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Inquisition Acolytes’ Needle Pistol costs 2 points in the datafile. It should cost 0, since it’s changed in the MUNITORUM FIELD MANUAL 2022 MK II

**Comment by AbonShell** [comment]
fixed in [005d79e](https://github.com/BSData/wh40k/commit/005d79e5f8d9c26fc2662bb5790f5e0bc58b8860)
