### ISSUE TITLE
Leagues of Votann FAQ/Point increase

### ISSUE THREAD

**Issue by Gr3yhunt** [BSData/wh40k-9e#11894]
There just was a FAQ and point increase for LoV:

New points list https://www.warhammer-community.com/wp-content/uploads/2022/09/WtjTm0YG0DuZDq7L.pdf

HQ
Ûthar the Destined: 140>160 points base cost
Kâhl: 70>80 points  base cost
Einhyr Champion: 90>110 points  base cost
Grimnyr: 80>90 points  base cost
Brôkhyr Iron-master: 80>90 points  base cost

TROOPS
Hearthkyn Warriors: 11 pts/model>12 pts/model

ELITE
Einhyr Hearthguard: 35 pts/model>45 pts/model
Cthonian Beserks: 22 pts/model>30 pts/model

FAST ATTACK
Hernkyn Pioneers: 30 pts/model>35 pts/model
Sagitaur: 110pts/model>130 pts/model

HEAVY SUPPORT
Brôkhyr Thunderkyn: 35 pts/model>40 pts/model
Hekaton Land Fortress: 230>300 points  base cost

FAQ list https://www.warhammer-community.com/wp-content/uploads/2022/09/hLLv5bGIp5BaljHW.pdf

Page 86 – Eye of the Ancestors, 5th paragraph
Change to read:
‘Note, if an attack automatically wounds the target as the result
of this ability, then for the purposes of any other rules that
are triggered on a particular wound roll, that attack is never
considered to have been made with an unmodified wound
roll of 6.’

**Comment by Dunamis55** [comment]
Already being handled by the data author.

**Comment by Mad-Spy** [comment]
@Gr3yhunt, Do you honestly believe that we are not aware of new FAQs within minutes of them being released? You don't need to raise tickets to get this sort of thing done.

**Comment by Gr3yhunt** [comment]
just wanted to help, sorry.....

**Comment by Mad-Spy** [comment]
We appreciate the sentiment, but in cases of FAQs and other updates, we're (almost) always on top of it. Just let us know what's broken if you find anything after the data is released.
