### ISSUE TITLE
Fateskimmer missing access to relics stratagems

### ISSUE THREAD

**Issue by ben-ballot** [BSData/wh40k-9e#11900]
**Describe the bug**
The fateskimmer in daemon codex doesn't have the "Relic" stratagel or "Relics of the Impossible Fortress"'

**To Reproduce**
1. Create a daemon patrol with a warlord
2. Add a fateskimmer
3. See missing relics related options
4. Add a fluxmaster and compare (you will be able to see the relics startagem options)

**Expected behavior**
Fateskimmer should be able to take some relics from the codex.

**Device and data (please complete the following information):**
 - OS: [PC
 - BattleScribe version v2.03.21.166
 - Chaos Daemons v124

**Comment by Valorcalls** [comment]
Working as intended, Fateskimmer cannot take any relics as per the codex.

Tzeentch vehicles cannot take relics.
