### ISSUE TITLE
[Blood Angels] Death Company Marines shouldn't be allowed to take two melee weapons

### ISSUE THREAD

**Issue by ThePants999** [BSData/wh40k-9e#11908]
If you add a Death Company Marine and uncheck the default "Bolt pistol and chainsword" wargear option, you then gain a "Melee weapon" section and a "Ranged/Melee weapon" section, which allows you to pick two melee weapons, e.g. a power fist and a power sword. This isn't legal. The wargear options for the unit look like this:

>  • Any number of models can each have their bolt pistol and Astartes chainsword replaced with one of the following: 1 boltgun; 1 thunder hammer.
 • Any number of models can each have their bolt pistol replaced with one of the following: 1 hand flamer; 1 inferno pistol; 1 plasma pistol.
 • Any number of models can each have their Astartes chainsword replaced with one of the following: 1 power axe; 1 power fist; 1 power maul; 1 power sword.

You cannot therefore end up with two melee weapons; if you don't take a boltgun or thunder hammer, it's always one melee weapon and one pistol.

**Comment by Mad-Spy** [comment]
@alphalas I've written a change to how DCo work in order to fix this and make the layout better imo. It's on the 11908 branch. Please can you give it a look?
