### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Cartographica.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11914]
**File:** Imperium - Astra Cartographica.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Datasheets not updated. New stats, habilities and dynamics. Points are not acvurate to the latest updated darasheet published

**Comment by Mad-Spy** [comment]
Correct. It'll be done when it's done.
