### ISSUE TITLE
Leagues of Votann: Abiding Mantle has incorrect text

### ISSUE THREAD

**Issue by pantheonw** [BSData/wh40k-9e#11911]
Abiding Mantle (Relic) for Leagues of Votann Urani-Sutur Regulates incorrectly 
duplicates Thurian Greater League's relic (Kôrvyk's Curiass)
Abiding Mantle should say "Unless the bearer is the closest eligible target, enemy models cannot target it with ranged attacks."

Also I'm not sure if you're supposed to be able to select a faction relic without having a warlord selected but you cannot.

**Comment by Mad-Spy** [comment]
No, you can't select a Faction relic without a Faction Warlord. That has been a feature of every 9th edition Codex.
