### ISSUE TITLE
Orks - Big'ed Bossbunka points error

### ISSUE THREAD

**Issue by haroldl** [BSData/wh40k-9e#11928]
**Describe the bug**
The Big'ed Bossbunka is 75 points, including 1 Big Shoota (for 0 additional points). But this data set reports the cost as 80 points: 75 points base plus 5 points for the first Big Shoota.

**To Reproduce**
1. Create an Orks list and add a Fortification Network force.
2. Navigate to the Fortification section and add a Big'ed Bossbunka.
3. Notice that it has 1 Big Shoota automatically.
4. See that it is listed for 80 points when it should be 75 points.

**Expected behavior**
Base cost of Big'ed Bossbunka is 75 points. Big'ed Bossbunka with 4 Big Shootas and Shoutin' Pole should be 95 points total.

**Screenshots**
Let me know if you need this.

**Device and data (please complete the following information):**
 - OS: Linux
 - BattleScribe version 2.03.21
 - Release version v9.6.10

**Additional context**

**Comment by FarseerVeraenthis** [comment]
That's not right. 
You have to pay for all wargear that has a listed points cost, whether it is default equipment or not.
You get nothing for free unless there is no points cost listed, as such the data is correct already.
