### ISSUE TITLE
Imperium - White Scars: Khan on Bike is unable to take Relics or WLTs under Nephilim

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11931]
**File:** Imperium - White Scars.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** It doesn't appear that there is any way to give Khan on Bike any relics.  Neither Strategem: Relic, nor Strategem: Relic of the Chapter appear as options, even if you select Khan on Bike as a Warlord

**Comment by hammyhamm-bugs** [comment]
This bug has resurfaced with Arks of Omen
