### ISSUE TITLE
Wolf Guard Terminators weapons pt error

### ISSUE THREAD

**Issue by lats1367** [BSData/wh40k-9e#11939]
**Describe the bug**

Wolf Guard Terminators for Space Wolves show Combi-Meltas as 5 points for one unit, then charge 10 pts for any further units. No rule that makes that happen that I have been able to find

![WGT](https://user-images.githubusercontent.com/68863856/196544512-45930676-530c-4a9d-8af8-52817be0f420.PNG)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - BattleScribe version [e.g. 2.03.45]
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by AbonShell** [comment]
Unable to replicate. Probably an error of duplicated selection if you duplicate the unit. Advice is to create the unit from scratch

**Comment by lats1367** [comment]
When doing that you get errors that the models don't have weapons even though they do

Note that if it matters this is on PC

Stevan Latinovic sent on the go
________________________________
