### ISSUE TITLE
Honoured by the Rock not available to Dark Angels successor chapters warlords

### ISSUE THREAD

**Issue by FredSlawson** [BSData/wh40k-9e#11930]
When a Dark Angel Successor Chapter roster is being built the "Honoured by the Rock" Requisition Stratagem is not available for the Warlord to give them access to a Dark Angels Chapter Relic of The Rock.

**Comment by AbonShell** [comment]
The strat is Available in the stratagems selection, however it doesn't allow any model access to the relics.

**Comment by FarseerVeraenthis** [comment]
I am unable to replicate this error. Please provide more detail;
![image](https://user-images.githubusercontent.com/23246922/196004162-a7cc458d-f055-476c-9629-ac50c3b7bbda.png)

Note that the category 'Relics of the Rock' was previously called (wrongly) Relics of Caliban, I have now corrected this.
