### ISSUE TITLE
Grey Knight Terminator special weapons on justicar

### ISSUE THREAD

**Issue by SSSlippy** [BSData/wh40k-9e#11935]
Grey terminators can take special weapons on any unit in the squad unlike other units. Currently you cannot give the terminator justicar a special weapon. 

“ For every 5 models in this unit, 1 model’s storm bolter can be replaced with 1 weapon from the Special Weapons list.”

**Comment by starostin13** [comment]
Each "squad" unit contain that text

**Comment by tekton** [comment]
I get where people are coming from on this one, but no other unit (including the elite unit that is based on this one) operates that way
