### ISSUE TITLE
Leagues of Votann Stratagems

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#11945]
The LoV stratagems "Legend of the League" and "In the Right Hands" are available to be selected on the character that is your warlord, no matter which character it is, but they shouldn't be available to your warlord and only available to characters that aren't the warlord 

![image](https://user-images.githubusercontent.com/72748875/197445338-0b7f9a51-a128-410d-898c-8073447be32f.png)
![image](https://user-images.githubusercontent.com/72748875/197445344-63daaaf7-c2c8-4521-abdd-f372d0c5b6dd.png)

**Comment by Mad-Spy** [comment]
There's nothing to stop you giving your Relic stratagem/free Relic on another model, and using In The Right Hands on your Warlord.

If you actually select Legend of the League on a Warlord, you get a validation error.
