### ISSUE TITLE
Imperial Knight Helverin power level 

### ISSUE THREAD

**Issue by DCDoncaster** [BSData/wh40k-9e#11942]
**Describe the bug**
Power Level on Imperial Helverin is set to 7 and sghould be 8

**To Reproduce**
Attempt any roster with knights

**Comment by AbonShell** [comment]
Update your data. 
![SmartSelect_20221022_060516](https://user-images.githubusercontent.com/20672472/197333503-c166f724-93d0-4f1b-ae9f-c4337439d4a0.jpg)
