### ISSUE TITLE
Ork Crusade Looted Vehicles Aren’t Appearing Again

### ISSUE THREAD

**Issue by M4G4D4KK4** [BSData/wh40k-9e#11956]
Normally, when selecting an Orks Detachment with an Open game type you get three crusade only vehicle options; Looted Wagon [Dedicated Transport], Looted ‘Eavy Wagon [Heavy Support] and Battle Fortress [Lord of War].

All of these options just have power level values only, no points, alongside the crusade only currency of scrap points.

They aren’t appearing in any new Orks list I’m making, just the older ones made before a certain point (whatever that is). 

The only related item that is appearing is an 8th Edition version of the Looted Wagon called a Kart that only has a power level cost. The other two 8th Edition narrative looted vehicles are not appearing.

Looking through Orks bug history, it looks like this issue happened before but it’s happening again.

I’m using the current Battlescribe app and data for WH40K. And I’ve been using Orks v58 and not v117 (though I don’t know why an older version has been left in).

**Comment by Mad-Spy** [comment]
The dataset doesn't support any Crusade functionality. Anything there is a holdover from previous editions and possibly incorrect for 9th.

The units you mention above require a Mek or Big Mek in your army in their current implementation. Add one and they will appear.

If you're still seeing the option for Orks v117, you need to do a data update with "Delete existing data" checked to clear it out. That file was there as an interim while the Orks Codex was not on general release. The file is no longer in the data you download and there's no way to clear it from this end.

**Comment by M4G4D4KK4** [comment]
Thanks! I was so confused on why it stopped working!
