### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by starostin13** [BSData/wh40k-9e#11955]
### Your Discord

starostin13

### Additional information

I'm already implement one fix https://github.com/BSData/wh40k/pull/11944
And I want to proceed with https://github.com/BSData/wh40k/issues/11935

**Comment by Mad-Spy** [comment]
We're not currently looking for more contributors. Rather than submitting PRs unprompted, you would be better served to speak to the current GK maintainer via our Discord first.
