### ISSUE TITLE
Chaos - Gellerpox Infected units can't be added as Elites choices

### ISSUE THREAD

**Issue by bravetherainbow** [BSData/wh40k-9e#11953]
At the moment the only option for Gellerpox Infected in Battlescribe seems to be using the Disease Vectors ability and adding a single unit to a detachment without taking up a Force Organisation Slot.

Disease Vectors does not override the normal way of including them in an army. The actual rules still allow you to add them as Elites choices to an army and include more than one of them in a detachment (for example they could share a detachment with other NURGLE units to have the shared NURGLE faction keyword), but at the moment Battlescribe does not allow for this.

I guess they could have their own faction like the Servants of the Abyss faction?

 - OS: Android and Windows
 - BattleScribe version 2.03.21
 - Warhammer 40,000 9.6.10
 - Chaos Space Marines v198 and Death Guard v146

**Comment by Mad-Spy** [comment]
I guess you _could_ do what you're suggesting, but it would break all of your mono-faction army rules (Let the Galaxy Burn, Contagions of Nurgle). The possibility of someone wanting to do that seemed small, so I didn't bother allowing it (and I couldn't be bothered coding it to disable those rules when you do take Gellerpox).

You _can_ currently include them as Elites in Detachments which don't fall under Disease Vectors (i.e. not Patrol, Battalion or Brigade), as long as you don't have any non-Nurgle units in the Detachment. They are incorrectly limited to max 1 in those Detachments though, so I'll fix that.
