### ISSUE TITLE
Imperium-Adeptus Astartes-Ultramarine-Roboute Guilliman-Warlord Trait Stratagem

### ISSUE THREAD

**Issue by Lodestarrer** [BSData/wh40k-9e#11962]
While creating an Ultramarine list, Battlescribe insists the user using the Warlord Trait stratagem from GT 2022: Nephilim pack on Guilliman. If the user did not select it, it shows as a validation error in the list. The Warlord Trait Stratagem is not compulsive that users have the right of choosing not to spend the cp on Guilliman. In the Orks list building, the Warlord Trait on Thraka is not compulsory that if players don't spend the cp on him, there's no validation error. Thanks.

OS: Windows and IOS
BattleScribe version 2.03.21
Warhammer 40,000 9.6.11
Ultramarine v66

**Comment by acebaur** [comment]
The 8th edition SM books have wording that says if their named characters are your Warlord your MUST take their associated Warlord trait.
