### ISSUE TITLE
Necron AoR - AoR only selectable as Vanguard/Spearhead/Outrider

### ISSUE THREAD

**Issue by Rord64** [BSData/wh40k-9e#11961]
**Describe the bug**
The Necron AoR is only selectable when choosing a vanguard/spearhead/outrider detachment. There appears to be no restriction in the rules on which detachment can be taken, only that you receive a CP refund for using a vanguard.

**To Reproduce**
1. Load up Necron bscribe
2. Create a Patrol/Battalion
3. Try to add AoR

**Expected behavior**
AoR is there

**Screenshots**
![image](https://user-images.githubusercontent.com/73206970/198839306-9944b4b9-20d6-41e6-8f55-250eb9756348.png)

**Device and data (please complete the following information):**
 - OS: Windows 10 Pro
 - BattleScribe version 2.03.21
 - Release version v224

**Additional context**

**Comment by acebaur** [comment]
There are no troop options so you can't legally make the other detachments
