### ISSUE TITLE
T'au plasma rifle, wrong point cost.

### ISSUE THREAD

**Issue by Hulemann** [BSData/wh40k-9e#11977]
**Describe the bug**
Hi. When selection the loadout for all T'au commanders the post cost for plasma rifle is wrong.
curranty the cost is +10/+15/+20/+20

**To Reproduce**
Go select at least 3 plasma rifle on all 3 commanders.

**Expected behavior**
The calculation should be. 
+10/+15/+25/+24

**Screenshots**.

**Device and data (please complete the following information):**
Windows and IOS app.

**Comment by Mad-Spy** [comment]
Costs are correct as per Munitorum Field Manual 2022 MkII. 
https://www.warhammer-community.com/wp-content/uploads/2022/10/qXv15sMDPlghlq7K.pdf

**Comment by Hulemann** [comment]
What no. What you just linked to shows that the cost should be what i wrote. The cost should be Plasma rifle +10/+15/+25 pts

The currently calculation on battlescribe is +10/+15/+20

![image](https://user-images.githubusercontent.com/117545287/200143195-ad7ec80c-be4b-40f1-95ec-3723ed0294c6.png)
