### ISSUE TITLE
Missing AppSpot 40k data

### ISSUE THREAD

**Issue by doranakan** [BSData/wh40k-9e#11979]
**Describe the bug**
The 9th ed 40k data is not present anymore in [AppSpot](https://battlescribedata.appspot.com/#/repos)

**To Reproduce**
1. Navigate the following [link](https://battlescribedata.appspot.com/repos/wh40k)

**Expected behavior**
Data should be available.

**Screenshots**
404

**Device and data (please complete the following information):**
 - OS: any

**Additional context**

**Comment by acebaur** [comment]
This I'd a well known issue. We can't control it. I'd advise using Gallery instead or just being patient while it comes back to life

**Comment by Mad-Spy** [comment]
See #1706 for details of how to switch to Gallery.
