### ISSUE TITLE
Imperium - Elucidian Starstriders: Voidsmen-at-Arms are duplicated across two different catalogues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11972]
**File:** Imperium - Elucidian Starstriders.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Outdated Datasheets: current information as follows... 
10 pts/model (including voidmaster, canid and voidsmen with rotor canon) 
Canid Unit: M 8 / WS 3+ / BS - / S 4 / T 3 / W 1/ A 3 / Ld 6 / Sv 4+
FACTION KEYWORDS: Imperium, Navis Imperialis, Agents of the Imperium KEYWORDS: Infantry, Core, Concussion Grenades, Voidsmen-at-Arms
Masters of Close Confines: Each time a model in this unit makes a ranged attack that targets a unit within 12", an unmodified hit roll of 6 scores one additional hit. Shipborne Personnel: If your army is Battle-forged, this unit cannot be used as a compulsory selection in a Detachment (e.g. as the only Troops unit in a Patrol Detachment), unless that Detachment is a Navis Imperialis Detachment.

**Comment by Mad-Spy** [comment]
There are now two copies of the Voidsmen-at-Arms. If you remove whatever you have now and add the 50pt unit instead, you'll get the correct data.

**Comment by AbonShell** [comment]
Fixed in next release
