### ISSUE TITLE
Votann/CSM - Some multi-model characters is missing profiles

### ISSUE THREAD

**Issue by Dragdord** [BSData/wh40k-9e#11978]
CSM's Dark Apostle and Votann's Brokhyr and Grimnyr is missing their main character model characteristics.

For example, you if you expand Dark Apostle unit, you can see profile of Dark Disciples, but not of Dark Apostle. Same thing With Brokhyr and Grimnyr. Because of this yellowscribe cannot properly work with this units.
![Безымянный](https://user-images.githubusercontent.com/20326286/200153426-ed9ea8b1-d2b2-4437-bd69-41af42a0e6b7.png)

**Comment by Mad-Spy** [comment]
We don't code for Yellowscribe. The profiles for this units are visible in Battlescribe, so there is nothing to fix.
