### ISSUE TITLE
Leagues of Votann - Hearthguard use two different sheet types

### ISSUE THREAD

**Issue by DavidMidwinter** [BSData/wh40k-9e#11987]
For the Hearthguard data sheets, two different types of sheet are used. Hearthguard armed with either range weapon and Plasma Blade Gauntlet use individual model selection while those with Concussion Gauntlet use collectivised selection.
![Screenshot_20221110-223535](https://user-images.githubusercontent.com/45365343/201220626-087e781a-6831-43ba-a2a4-8b6168d28617.jpg)
![Screenshot_20221110-223519](https://user-images.githubusercontent.com/45365343/201220630-a5213e43-e3d0-49e1-b1dc-0cc29a143543.jpg)
It would make more sense if Concussion Gauntlet hearthguard used Collectivised model selection, as all non Hesyr Hearthguard share the same loadout.

**Comment by Mad-Spy** [comment]
Some idiot forgot to check a box. Fixed for next release.

**Comment by DavidMidwinter** [comment]
Reasonable! It's always something like that isn't it 🤣
