### ISSUE TITLE
AdMech missing WLT - multitasking cortex

### ISSUE THREAD

**Issue by TheGamingMed** [BSData/wh40k-9e#11985]
The warlord trait - Multitasking cortex is missing from the admech in 40k

MULTITASKING CORTEX

The warlord’s cogitative capacity is several orders of magnitude greater than a common Skitarius. Sharing a fraction of this processing power, the cogni-savant enables those under their command to focus upon several tasks at once.

In your Command phase, select one friendly <FORGE WORLD> SKITARII CORE unit within 9" of this WARLORD, or select one friendly <FORGE WORLD> CORE DATA-TETHER unit on the battlefield. Until the start of your next Command phase, if that unit is performing an action, it can make ranged attacks without that action failing.

**Comment by Mad-Spy** [comment]
The WLT appears correctly on a Skitarii Warlord, as expected, and I'm unable to make it not appear in the list via any other config. If it doesn't appear for you, please provide full details of your list.

![image](https://user-images.githubusercontent.com/29306451/201100475-46d58e8b-ac1b-4f2c-84a2-af39a71aba9d.png)
