### ISSUE TITLE
Imperium - Adepta Sororitas: Character Stratagems group is being incorrectly hidden on Warlords

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11994]
**File:** Imperium - Adepta Sororitas.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:**

 ~~Stratagem: Exemplar of the Order doesn’t work correctly.~~ 

When you pick the warlord the stratagems disappear. 

~~And it is supposed to be added to the warlord.~~

**Comment by Mad-Spy** [comment]
The logic is broken such that the group disappears if you select the model as the Warlord in a non-Nephilim game type.

**Comment by CrusherJoe** [comment]
Don't play non-Nephilim games?

**Comment by CrusherJoe** [comment]
Okay, seriously though.

Don't. Like what are you playing? Open War? Dirty card flipper style?

:) :) :) :) :) :) :) 

seeeeriously, though, I'll fix it after Guard book is done.
