### ISSUE TITLE
Noctilith Crown (CSM) need extra words (4+ invuln aura is RANGED ONLY)

### ISSUE THREAD

**Issue by Thor-axetheImpaler** [BSData/wh40k-9e#11998]
Need to add "against ranged attacks." at the end of the **Malevolent Locus (Aura)** invuln description on the Noctilith Crown CSM Foritification. Currently does not mention this restriction.

**Comment by Mad-Spy** [comment]
I'd also missed the non-CHAOS exemption on the -1 Ld effect.
