### ISSUE TITLE
6th/7th Edition Apocalypse

### ISSUE THREAD

**Issue by LachrimallusExterminator** [BSData/wh40k-9e#11991]
Hello. Going back to 6th and 7th so I can use OOP and ‘Legends’ vehicle models with rules the writer thought about for more than a minute before composing.

If you could add in these formations and datasheets to the Warhammer 40,000 7th Edition Necrons Apocalypse force selection, please. I’m mainly interested in the Infinite Phalanx and the 6th Edition Apocalypse version of the Transcendent C’tan (I might use the Void Dragon model as a proxy since it is “Gargantuan”. I prefer the original Necron lore.) Thanks.

![F9A05427-C9B7-4A8C-B6BD-D6F1FBB11432](https://user-images.githubusercontent.com/84422145/201883498-e8ca5e6d-fbf2-40d0-9eec-4a0a76f33741.jpeg)
![781ECC56-81F8-4FBD-BB0F-04E40F0EB368](https://user-images.githubusercontent.com/84422145/201883662-f3f44854-079e-44a1-96f0-98774cf992be.jpeg)
![4899FE7E-3EE4-4D5E-A710-656E726F21EE](https://user-images.githubusercontent.com/84422145/201883853-6ee7736d-420c-461d-aa9c-102aedf1923a.jpeg)
![9F15629C-0001-47A5-9A52-F8E1D7E65469](https://user-images.githubusercontent.com/84422145/201883980-54706fbd-f7e5-4684-9949-95b0ea1b7f7b.jpeg)
![96FC999A-62EC-4407-8B1A-BD6AB68A75A9](https://user-images.githubusercontent.com/84422145/201884122-f78561ef-0c20-48f8-bbbb-eefa753f6238.jpeg)
![F66A5349-A0EC-45E7-A671-825F5BD49B68](https://user-images.githubusercontent.com/84422145/201884218-7d6a83b8-28b6-49f4-b6ee-2e93dcc1d1a0.jpeg)
![2380A0E3-5428-4A78-85F8-A7945659D0DD](https://user-images.githubusercontent.com/84422145/201884372-e620c1e5-c34c-414d-b9c7-319759a521fc.jpeg)

**Comment by Mad-Spy** [comment]
This is the repository for 9th edition 40k. Please raise your request in the correct repository.

**Comment by LachrimallusExterminator** [comment]
Couldn’t find it.

**Comment by LachrimallusExterminator** [comment]
Thanks for sending me to a dead end. It’s archived and read-only. Could it be opened again, please?

**Comment by Mad-Spy** [comment]
The reason it's archived is because it's no longer being supported or updated by any volunteer authors.

Given that, the only way to get these added would be for you to do it yourself, which you can do in the files you have already downloaded using the Data Editor.

**Comment by LachrimallusExterminator** [comment]
I use iOS. Would I need a PC for that?

**Comment by Mad-Spy** [comment]
No, just a Mac desktop.
