### ISSUE TITLE
League of Votann - Sagitaur weapons

### ISSUE THREAD

**Issue by smajchrz** [BSData/wh40k-9e#12002]
**Describe the bug**
According to latest points updates and model building manual Sagitaur Missiles and L7 missiles are one weapon that cost 10 points.

**To Reproduce**
There is no possibility to select both weapons at once.

**Expected behavior**

Sagitaur missiles and L7 missiles should be merged into one selection from weapons list.

**Screenshots**

**Device and data (please complete the following information):**
 - OS: all
 - BattleScribe version [e.g. 2.03.45]
 - Release version v9.6.12

**Additional context**
Link to model manual:
https://www.reddit.com/r/WarhammerInstructions/comments/ysmxci/leagues_of_votann_sagitaur/

Link to points update:
https://www.warhammer-community.com/wp-content/uploads/2022/09/WtjTm0YG0DuZDq7L.pdf

**Comment by acebaur** [comment]
They are not one weapon per the data sheet.

**Comment by smajchrz** [comment]
![image](https://user-images.githubusercontent.com/66011779/203095845-4b33a0a4-e9b7-4d42-b52c-5649003e6ddf.png)

How do you explain that @acebaur  ? Points values from community updates taking precedence over entry in the codex.

Edit:
Shot from standalone codex:
![image](https://user-images.githubusercontent.com/66011779/203404367-92641fee-2b6e-43e1-9fcd-fbf06623fd02.jpeg)

**Comment by Mad-Spy** [comment]
The problem here is that we had only seen the launch box version of this datasheet, which has them as separate weapon options. They changed it between the two.

![image](https://user-images.githubusercontent.com/29306451/203941958-c1f8045b-8df9-4fc5-bb99-e32b99b18981.png)
