### ISSUE TITLE
Chaos Space Marines - Dark Apostle missing child "model" in selectionEntries 

### ISSUE THREAD

**Issue by sterling000** [BSData/wh40k-9e#12012]
Without a child selectionModel, many other community tools have issues with the Dark Apostle, i.e. yellowscribe for TTS. Every other multi-model unit that has a clear "leader" appears to have the parent unit, and then a clearly defined child model for it even if it has the same name (see The Silent King with Szarekh as a Child for reference) 

**Steps to Reproduce**
While the error is not exposed in Battlescribe, it is in other apps that use Battlescribe data that expect it to follow this convention like all the others do.

1. Create a Chaos Space Marine list.
2. Add a Dark Apostle to it.
3. Save the list.
4. Unzip the .rosz file somewhere on your machine.
5. Open the .ros file inside in a text editor.
6. Search for `<selectionEntry id="ec15-5c01-e987-c91f" name="Dark Apostle" hidden="false" collective="false" import="true" type="unit">`
7. Observe the type="unit".
8. Observe there is no "selectionEntry" in the nested selectionEntries for "Dark Apostle" with type="model", just "Dark Disciple" has one.

**Expected behavior**
The data should be present in the ros file.

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version: 2.03.21
 - Release version: Warhammer 40,000 v9.6.13

**Additional context**
If you upload any rosz file with a Dark Apostle in it to yellowscribe.net, you can see it doesn't assign the weapons to the Dark Apostle model because there isn't one, which then causes import tools for TableTop Simulator to not add the Dark Apostle as a model for scripting. These are the msot popular and most widely used mods for TTS right now which alot of people started using since the pandemic started, so while printed output of the roster looks fine on paper, this date being fixed would help alot, especially since this unit is basically an auto-include in any competitive CSM list in the meta.

**Comment by Mad-Spy** [comment]
We do not write for 3rd-party tools; we write for ease of use in the Battlescribe app.

**Comment by sterling000** [comment]
Literally from your own repo catalogue guidelines...

`First and most important rule is - try to keep in line with other catalogues for the given system.`

If you are consistent with your guidelines then 3rd party apps CAN at least consume your data whichever one you go with, if it's a matter of time, I was about to fork the repo and fix it myself, but I hope the principle you quoted before shutting my issue so quickly without discussion wasn't the only reason you denied it, because the if you read the entire thread, the battlescribe app experience would not be affected at all, in fact the change would be nearly invisible to an end user, AND it would actually be correct as far as the rules of pretty much every 40k tournament run to date.

Considering in it's current form without access to a codex, anyone submitting a list from the app without this fix is technically missing a model and their list would be considered void and could cost them a disqualification if the stakes were high enough.
