### ISSUE TITLE
Imperium, unable to deselect Trajann Valoris as Warlord

### ISSUE THREAD

**Issue by Imperialguard82** [BSData/wh40k-9e#12020]
**Describe the bug**
Unable to deselect Trajann Valoris as sole Warlord, I know he has a special rule where he has to be warlord, but that rule also applies to Guilliman,

**To Reproduce**
1. Create detachment including Trajann Valoris
2. Create another detachment including Roboute Guilliman
3. Get told army can only have 1 warlord

**Expected behavior**
I expect to be able to deselect Trajann Valoris as Warlord so Guilliman can be warlord, either that or remove the system telling me I have an error when I deselect Guilliman's Warlord

**Screenshots**

**Device and data (please complete the following information):**
 - OS: Android
 - BattleScribe version [e.g. 2.03.45]
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by Mad-Spy** [comment]
You just have to ignore the error, as they both have a rule which requires them to be a Warlord. Implementing an exemption across catalogues is problematic.
