### ISSUE TITLE
Imperium - Dark Angels: Talonmaster should allow a second LIEUTENANT choice

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12025]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Hello.
If I choose the Ravenwing Talon Master as an HQ choice, should it be possible to choose a second Talon Master in the No Force Org Slot due to his Company Heroes ability?
Best Regards Mario

**Comment by Mad-Spy** [comment]
You no longer need to add it via an NFO slot. We managed to get the validation to work so you can just add them as another HQ choice.
