### ISSUE TITLE
Orks: KIlla Kans should have Kustom Jobs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12034]
**File:** Orks.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Killa kans have no kustom jobs, despite being eligible for Nore Dakka and shock hull

**Comment by Mad-Spy** [comment]
KIlla Kans cannot have Kustom Jobs, because only single model units can have them, as per the rules.

![image](https://user-images.githubusercontent.com/29306451/207022405-89960c33-03d5-4d11-bf80-24520e132b03.png)
