### ISSUE TITLE
Leagues of Votann Sagitaur Wargear.

### ISSUE THREAD

**Issue by Oshni** [BSData/wh40k-9e#12032]
I believe the Sagitaur war gear is incorrect.
In the Collector's Edition of the codex, the one you probably used to write the BS Data for the Leagues, the Sagitaur Missile Launcher and the L7 Missile Launcher are listed as separate options. However, in the standard edition of the codex, they're listed as one wargear option. GW hasn't made any official FAQ on which one is correct, however the kit, the points cost PDF, and the GW app all list them as being taken together. In the Wahapedia discord we've been discussing it on and off for the last week and have settled on the fact they should probably be one selection, that costs a combined 10 points. 
I'd be happy to discuss this further if you'd like.

**Comment by Mad-Spy** [comment]
Fixed in next release, as per #12002

**Comment by Oshni** [comment]
Oh cool! Thank you for your hard work.
