### ISSUE TITLE
All Space Marines - CAPTAIN keyword needs to be consolidated

### ISSUE THREAD

**Issue by KalChoedan** [BSData/wh40k-9e#12035]
**Describe the bug**
There are currently 2 CAPTAIN keywords in Space Marines; one from FW and one from the Library. This is causing problems when validating some NFO slot options.

**To Reproduce**
1. Create a Roster
2. Add a model with the FW CAPTAIN keyword (e.g. Tyberos)
3. Add an NFO Company Vets squad
4. Validation error appears stating Roster has too many Company Vets

**Expected behavior**
Should validate to allow max 1 units of company veterans

**Screenshots**
![image](https://user-images.githubusercontent.com/1786901/207054891-51af27cd-e5fd-4c1f-8a2e-1391a0f9fd8e.png)

**Comment by Mad-Spy** [comment]
Best solution would be to move all Lib Captains to use the FW version and update all the conditions throughout all the catalogues.

Quickest solution is to remove the FW version and put the Lib version on all the RSEs in all the catalogues.

**Comment by WindstormSCR** [comment]
Fixed during FW Library merge
