### ISSUE TITLE
Orks: Painboy on Warbike PL incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12041]
**File:** Orks.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** On the app in the Orks data the Power level listed for the Painboy on Warbike is 6. According to the Warhammer Legends file for orks it is meant to be 5 power level.

**Comment by GinFizzz** [comment]
Can confirm that according the file at [this link](https://www.warhammer-community.com/wp-content/uploads/2019/12/7661dd41.pdf), power should be 5.

Screen capture is provided below.

![msedge_KItBE5fgmt](https://user-images.githubusercontent.com/47032978/208150703-7d673162-95a6-4a48-9248-99e6aef0c558.png)

**Comment by GinFizzz** [comment]
Should be resolved by pull request #12042.

**Comment by Mad-Spy** [comment]
Closed by #12042
