### ISSUE TITLE
Chaos - Chaos Space Marines: Sorceror profile not updated when selecting Liber Hereticus

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12046]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 3.21.16

**Platform:** Windows

**Dropbox:** No

**Description:** On the Chaos Space Marine Sorcerer there is the opton for gifts of chaos to select the Liber Hereticus. This besides other things adds one to the psychic powers that can be cast. That works on the sorcerer terminator version, but if you select it for the non terminator sorcerer, he gets the liber hereticus, but it doesn't add one to the castable powers.

**Comment by Mad-Spy** [comment]
Appears to be working as expected in current release. Selecting the Liber updates the Sorceror's psychic profile to show that it can cast 3 powers per psychic phase.

![image](https://user-images.githubusercontent.com/29306451/208401443-cd0a1168-48ad-4a45-91cd-f4b6085ad24c.png)
