### ISSUE TITLE
Imperium - White Scars: Statlines are not updated by Angel Artifice

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12045]
**File:** Imperium - White Scars.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** When selecting "Angel Artifice Relic" for a Chapter Master, the statline is not updated to include the improved attributes (+1 Wound, +1 Toughness, 2+ Armor Save). This probably affects all Space Marines, not online Scars, I guess.

**Comment by Mad-Spy** [comment]
Whether or not profiles are updated based on Relics is up to the individual data author. Profiles in the Marines catalogues are generally not updated.
