### ISSUE TITLE
Aeldari - Craftworlds: Striking Scorpion Exarch issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12052]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Striking Scorpion Exarch is listed as having 5 attacks but actually only has 4.

**Comment by FarseerVeraenthis** [comment]
Yes, when you give him an exarch power he gains an attack.
Standard he has four and this is how the data works at present.
