### ISSUE TITLE
Votann character units missing unit leader

### ISSUE THREAD

**Issue by blackraine** [BSData/wh40k-9e#12056]
**Describe the bug**
In battlescribe, each model needs separate representation. Currently the Grimnyr and Brokhyr are represented by the unit itself rather than having a separate unit entry in the unit like their Corgs and E-Cogs respectively. This is confusing for other programs, like Yellowscribe, that parse Battlescribe army lists to create outputs as it has no entry for the actual Grimnyr or Brokhyr model.

**To Reproduce**
1. Create a Leagues of Votann Roster
2. Select a Grimnyr or Brokhyr unit
3. Expand the unit selection
4. There will be no specific model entry for Grimnyr or Brokhyr

**Expected behavior**
Each model in the unit should be represented by a model entry rather than by the unit itself. Multiple identical models of the same type can be represented by a single entry. For example, when selecting Hearthkyn Warriors, there is one entry for the Theyn (unit leader) and one entry for 9x Warriors.

**Screenshots**
![image](https://user-images.githubusercontent.com/30580049/209849801-7eae4181-2f25-4343-a263-adaca7d0fe07.png)

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version v2.03.21.166
 - Release version v9.6.14

**Additional context**
This is mostly needed for compatibility with 3rd party software such as Yellowscribe, which imports Battlescribe army lists into Tabletop Simulator.

**Comment by Mad-Spy** [comment]
We don't build for compatibility with 3rd party programs. We write for ease of use in Battlescribe.
