### ISSUE TITLE
T'au Empire Breacher Team & Strike Team show inconsistent formatting.

### ISSUE THREAD

**Issue by Zurhydryh** [BSData/wh40k-9e#12058]
**Describe the issue**
When editing a roster, the Breacher Team and Strike Team units selections are in different orders, with the main models of the Breacher Team being listed under the main unit heading, and the Strike Team's models being listed under a Squad subheading below their Fire Warrior Drones.

Additionally in both editing and viewing UIs, the Breacher Fire Warrior Shas'ui is listed after the Breacher Fire Warriors, while the Strike Team's Fire Warrior Shas'ui is listed before the Fire Warriors.

Finally, the Guardian Drone does not show up in the first section of the unit's view UI unless another drone is also added to the unit, though it's ability and profile are listed.

**To Reproduce**
1. Add a Breacher Team and Strike Team, observe the different order of entries when editing the units.
2. Tick the box to add a Guardian Drone to a unit.
3. View the unit, observe that the Guardian Drone is not listed above Abilities.
4. Add any other drone to the unit.
5. View the unit again, observe that the Guardian Drone is now listed alongside the other drone above Abilities.

**Screenshots**
[Strike Team Example](https://user-images.githubusercontent.com/19255916/210024242-9dcaafc8-117f-4885-b59e-e4545b7c6b4c.png)

[Breacher Team Example](https://user-images.githubusercontent.com/19255916/210024273-6bc03a9d-47c7-4890-bfd6-5f5f4cf10148.png)

[Roster view with 1 Gun Drone added to Strike Team, and a Guardian Drone added both units](https://user-images.githubusercontent.com/19255916/210023805-980e613f-4986-4f56-8bab-3a160e0425ef.png)

**Device and data (please complete the following information):**
 - OS: Android
 - BattleScribe version 2.03.25
 - T'au Empire v139

**Comment by AbonShell** [comment]
Just a limitation of battlescribe. The data works as is, so there's not really a reason to change anything.
