### ISSUE TITLE
Adepta Sororitas Arco-Flagellants points calculations 

### ISSUE THREAD

**Issue by Hewitt40** [BSData/wh40k-9e#12066]
Maths error for unit.

Enduring implants are 5pts each but are calculated incorrectly, squad of 3 shows as 18pts per model (correct as base is 13 + 5 for implants) so squad should be 54pts, app logs as 57pts adding an additional 1pt per model incorrectly.

**Comment by AbonShell** [comment]
13x4=52
52+5=57
![image](https://user-images.githubusercontent.com/20672472/210287518-0518a145-43dd-4dd2-919a-80c238deefae.png)
