### ISSUE TITLE
Chapter Approved: Arks of Omen

### ISSUE THREAD

**Issue by WindstormSCR** [BSData/wh40k-9e#12068]
Need to update each faction with the relevant logic in the WLT and Relic stratagems to match Nephilim.

other faction specific details to be added on release

- [x] GST
- [x] Aeldari Craftworlds
- [x] Aeldari Harlequins
- [x] Drukhari
- [x] Aeldari FW
- [x] Chaos Knights
- [x] Chaos Space Marines
- [x] Chaos Daemons
- [x] Thousand Sons
- [x] Death Guard
- [x] Chaos FW
- [x] Inquisition
- [x] Officio Assassinorum
- [x] Imperial Knights
- [x] Custodes
- [x] Adepta Sororitas
- [x] Astra Militarum
- [x] Deathwatch
- [x] Raven Guard
- [x] Iron Hands
- [x] Ultramarines
- [x] Imperial Fists
- [x] Black Templars
- [x] Blood Angels
- [x] Salamanders
- [x] White Scars
- [x] Dark Angels
- [x] Leagues of Votann
- [x] Tau
- [x] Necrons
- [x] Orks
- [x] Genestealer Cults
- [x] Tyranids
- [x] Adeptus Mechanicus

**Comment by WindstormSCR** [comment]
Leaving open for other quirks that may need implementation

**Comment by jmtoniolo** [comment]
Do you guys put all points change updates under this task? Should all balance data slate update pull requests fall under this?
