### ISSUE TITLE
Some AdMech point changes that were missed

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#12076]
I am using the master data for Warhammer 40k

-Skitarii Rangers and Vanguard Alphas taser goad cost 5 pts, should be 0
-Fulgurite Electro-Priests cost 14 pts a model, should be 12
-The Serberys Raiders Enhanced Data-Tether is free, should be 5 pts
-Serberys Sulpherhounds currently cost 20 pts a model, should be 18 pts now (it wasnt highlighted in the MFM)
-The Sydonian Dragoon is 55 pts a model, should be 50 pts base

Also when I select Cawl as my warlord, he gives an error when I give him his warlord trait Masterwork Bionics and it says, he has 1 too many selections of it (maximum 0)

**Comment by rsigworth** [comment]
After this commit, it is no longer possible to select the taser goad on Vanguard Alpha or Ranger Alpha. The option is completely gone.
