### ISSUE TITLE
Leagues of Votann. Sagitaur weapon option error

### ISSUE THREAD

**Issue by natecross1990** [BSData/wh40k-9e#12078]
Sagitaur weapon options list 'L7 Missile launcher' and Sagitaur missile launcher' as two seperate options at 10pts each.
According to the codex and the 40k app the two weapons are a combined option of 'L7 missile launcher AND Sagitaur missile launcher' at 10 pts total.

Can you adjust this please :)

**Comment by Dunamis55** [comment]
Already fixed in next release.
