### ISSUE TITLE
Space Marines - 2023 MFM Mk I Points QA Pass

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#12088]
### SPACE MARINES
- [x] Captain in Terminator Armour’s chainfist costs 5 pts, but should cost 0 pts
- [x] Chaplain in Terminator Armour costs 95 pts, but should cost 85 pts
- [x] Librarian in Phobos Armour costs 100 pts, but should cost 90 pts
- [x] Techmarine’s plasma cutter costs 15 pts, but should cost 0 pts
- [x] Hand flamer costs 5 pts, but should cost 0 points for:
- Assault Intercessor Squad > Assault Intercessor Sergeant
- Intercessor Squad > Intercessor Sergeant
- Vanguard Veteran Squad models
- Veteran Intercessor Squad > Veteran Intercessor Sergeant
- [x] Intercessor Squad’s Astartes grenade launcher costs 5 pts, but should cost 0 pts
- [x] Bladeguard Veteran Squad > Bladeguard Veteran Sergeant’s neo-volkite pistol costs 5 pts, but should cost 0 pts
- [x] Plasma pistol costs 5 pts, but should cost 0 pts for:
- Bladeguard Veteran Squad > Bladeguard Veteran Sergeant
- Hellblaster Squad > Hellblaster Sergeant
- [x] Company Ancient’s thunder hammer costs 10 pts, but should cost 0 pts
- [x] Company Veterans > Company Veteran’s heavy flamer costs 0 pts, but should cost 10 pts
- [x] Sternguard Veterans > Sternguard Veteran w/Heavy Weapon’s heavy flamer costs 10 pts, but should cost 0 pts
- [x] Company Veterans’ power axe costs 0 pts, but should cost 3 pts
- [x] Company Veterans’ power sword costs 0 pts, but should cost 3 pts
- [x] Company Veterans’ power maul costs 0 pts, but should cost 3 pts
- [x] Company Veterans’ power fist costs 5 pts, but should cost 8 pts
- [x] Company Veterans’ thunder hammer costs 10 pts, but should cost 12 pts
- [x] Terminator Assault Squad > Assault Terminator Sergeant’s thunder hammer costs 10 pts, but should cost 0 pts
- [x] Terminator Assault Squad > Assault Terminator w/THSS’s thunder hammer costs 15 pts, but should cost 0 pts
- [x] Terminator Squad currently costs 38 pts per model, but should be 33 pts per model
- [x] Terminator Squad > Terminator w/ Heavy Weapon’s heavy flamer currently costs 5 pts, but should be 0 pts
- [x] Terminator Squad > Terminator w/ Heavy Weapon’s assault cannon currently costs 10 pts, but should be 0 pts
- [x] Terminator Squad > Terminator w/ Heavy Weapon’s cyclone missile launcher currently costs 25 pts, but should be 0 pts
- [x] Vanguard Veteran Squad currently costs 19 pts per model, but should be 20 pts per model
- [x] Vanguard Veteran Squad > Vanguard Veteran Sergeant’s relic blade currently costs 10 pts, but should be 0 pts
- [x] Multi-melta currently costs 10 pts, but should cost 0 pts for:
- Bike Squad > Attack Bike
- Eradicator Squad > Eradicator with MM
- [x] Invader ATV Squad’s multi-melta currently costs 5 pts, but should cost 0 pts
- [x] Devastator Squad’s armorium cherub currently costs 5 pts, but should cost 0 pts
- [x] Hunter’s storm bolter currently costs 5 pts, but should cost 0 pts
- [x] Repulsor Executioner’s icarus rocket pod currently costs 5 pts, but should cost 0 pts
- [x] Repulsor Executioner’s heavy laser destroyer currently costs 10 pts, but should cost 0 pts
- [x] Repulsor Executioner’s ironhail heavy stubber currently costs 5 pts, but should cost 0 pts
### BLACK TEMPLARS
- [x] Primaris Lieutenant’s auto-plasma currently costs 50 pts when taken with an Astartes chainsword, but should cost 0 pts
### BLOOD ANGELS
- [ ] Chief Librarian Mephiston (Primaris) currently costs 140 pts, but should cost 125 pts
- [x] Gabriel Seth currently costs 145 pts, but should cost 130 pts
- [ ] Librarian Dreadnaught’s heavy flamer costs 5 pts, but should cost 0 pts
- [ ] Librarian Dreadnaught’s meltagun costs 5 pts, but should cost 0 pts
- [ ] Death Company Intercessors currently costs 20 pts per model, but should be 18 pts per model
- [ ] Death Company Marines currently costs 18 pts per model, but should be 20 pts per model
- [ ] Death Company Marines > Death Company Marine’s power axe currently costs 5 pts, but should be 0 pts
- [ ] Power maul currently costs 5 pts, but should be 0 pts for:
- Death Company Marines > Death Company Marine
- Interrogator-Chaplain
- Ravenwing Black Knights > Ravenwing Huntmaster
- [ ] Power sword currently costs 5 pts, but should be 0 pts for:
- Death Company Marines > Death Company Marine
- Death Company Intercessors > Death Company Intercessor w/ Melee Weapon
- Interrogator-Chaplain
- Ravenwing Black Knights > Ravenwing Huntmaster
- [ ] Death Company Marines > Death Company Marine’s power fist currently costs 10 pts, but should be 5 pts
- [ ] Death Company Marines > Death Company Marine’s hand flamer currently costs 5 pts, but should be 0 pts
- [ ] Inferno pistol currently costs 5 pts, but should be 0 pts for:
- Death Company Marines > Death Company Marine
- Sanguinary Ancient
- Sanguinary Guard
- [ ] Death Company Marines > Death Company Marine w/ thunder hammer’s thunder hammer currently costs 15 pts, but should be 10 pts
- [ ] Blood talons (pair) currently costs 10 pts, but should cost 0 pts for:
- Death Company Dreadnought
- Furioso Dreadnought
- [ ] Heavy flamer currently costs 5 pts, but should cost 0 pts for:
- Death Company Dreadnought
- Furioso Dreadnought
- [ ] Death Company Dreadnought’s meltagun currently costs 5 pts, but should cost 0 pts
- [ ] Magna-grapple currently costs 5 pts, but should cost 0 pts for:
- Death Company Dreadnought
- Furioso Dreadnought
- [ ] Death Company Intercessors > Death Company Intercessor w/ Melee Weapon’s thunder hammer currently costs 20 pts, but should cost 0 pts
- [ ] Death Company Intercessors > Death Company Intercessor w/ Melee Weapon’s hand flamer currently costs 5 pts, but should cost 0 pts
- [ ] Sanguinary Guard’s power fist currently costs 5 pts, but should cost 0 pts
- [ ] Baal Predator’s twin assault cannon currently costs 10 pts, but should cost 0 pts
- [ ] Baal Predator’s heavy bolters currently cost 15 pts each, but should cost 0 pts
- [ ] Baal Predator’s heavy flamers currently cost 15 pts each, but should cost 0 pts
- [ ] Baal Predator’s hunter-killer missile currently costs 5 pts, but should cost 0 pts
- [ ] Baal Predator’s storm bolter currently costs 5 pts, but should cost 0 pts
- [ ] Death Company Intercessors’s Astartes grenade launcher costs 5 pts, but should cost 0 pts
- [ ] Plasma pistol costs 5 pts, but should cost 0 pts for:
- Death Company Marines > Death Company Marine
- Death Company Intercessors > Death Company Intercessor w/ Melee Weapon
- Sanguinary Ancient
- Sanguinary Guard
### DARK ANGELS
- [x] Asmodai currently costs 130 pts, but should cost 115 pts
- [ ] Azrael currently costs 160 pts, but should cost 140 pts
- [ ] Belial currently costs 140 pts, but should cost 125 pts
- [ ] Ezekiel currently costs 115 pts, but should cost 105 pts
- [ ] Combi-flamer currently costs 5 pts, but should cost 0 pts for:
- Interrogator-Chaplain
- Interrogator-Chaplain in Terminator Armour
- [ ] Combi-grav currently costs 5 pts, but should cost 0 pts for:
- Interrogator-Chaplain
- Interrogator-Chaplain in Terminator Armour
- [ ] Combi-melta currently costs 5 pts, but should cost 0 pts for:
- Interrogator-Chaplain
- Interrogator-Chaplain in Terminator Armour
- [ ] Combi-plasma currently costs 5 pts, but should cost 0 pts for:
- Interrogator-Chaplain
- Interrogator-Chaplain in Terminator Armour
- [ ] Interrogator-Chaplain’s lightning claw currently costs 5 pts, but should cost 0 pts
- [ ] Interrogator-Chaplain’s power axe currently costs 5 pts, but should cost 0 pts
- [ ] Interrogator-Chaplain’s power fist currently costs 10 pts, but should cost 0 pts
- [ ] Interrogator-Chaplain’s thunder hammer currently costs 20 pts, but should cost 0 pts
- [ ] Lazarus currently costs 110 pts, but should cost 100 pts
- [ ] Ravenwing Talonmaster currently costs 175 pts, but should cost 160 pts
- [ ] Sammael currently costs 150 pts, but should cost 135 pts
- [ ] Deathwing Strikemaster currently costs 95 pts, but should cost 85 pts
- [ ] Deathwing Strikemaster’s mace of absolution currently costs 10 pts, but should cost 0 pts
- [ ] Deathwing Strikemaster’s thunder hammer currently costs 10 pts, but should cost 0 pts
- [ ] Deathwing Strikemaster’s storm shield currently costs 5 pts, but should cost 0 pts
- [ ] Deathwing Apothecary currently costs 100 pts, but should cost 90 pts
- [ ] Deathwing Champion currently costs 80 pts, but should cost 70 pts
- [ ] Watcher in the Dark currently costs 5 pts, but should cost 0 pts for:
- Deathwing Command Squad
- Deathwing Knights
- Deathwing Terminator Squad
- [ ] Thunder hammer currently costs 10 pts, but should cost 0 pts for:
- Deathwing Command Squad
- Deathwing Terminator Squad
- [ ] Power fist currently costs 5 pts, but should cost 0 pts for:
- Deathwing Command Squad
- Deathwing Terminator Squad
- [ ] Assault cannon currently costs 10 pts, but should cost 0 pts for:
- Deathwing Command Squad
- Deathwing Terminator Squad
- [ ] Cyclone missile launcher currently costs 25 pts, but should cost 0 pts for:
- Deathwing Command Squad
- Deathwing Terminator Squad
- [ ] Heavy flamer currently costs 5 pts, but should cost 0 pts for:
- Deathwing Command Squad
- Deathwing Terminator Squad
- [ ] Plasma cannon currently costs 10 pts, but should cost 0 pts for:
- Deathwing Command Squad
- Deathwing Terminator Squad
- [ ] Ravenwing Ancient currently costs 100 pts, but should cost 90 pts
- [ ] Ravenwing Apothecary currently costs 100 pts, but should cost 90 pts
- [ ] Ravenwing Knights currently cost 35 pts per model, but should cost 30 pts per model
- [ ] Ravenwing Champion currently costs 70 pts, but should cost 60 pts
- [ ] Ravenwing Darkshroud currently costs 120 pts, but should cost 110 pts
- [ ] Ravenwing Darkshroud’s assault cannon currently costs 5 pts, but should cost 0 pts
- [ ] Ravenwing Land Speeder Vengeance currently costs 110 pts, but should cost 100 pts
- [ ] Ravenwing Land Speeder Vengeance’s assault cannon currently costs 5 pts, but should cost 0 pts
- [ ] Nephilim Jetfighter currently costs 175 pts, but should cost 155 pts
- [ ] Ravenwing Dark Talon currently costs 195 pts, but should cost 170 pts
- [ ] Chainfist costs 5 pts, but should cost 0 pts for:
- Deathwing Strikemaster
- Deathwing Command Squad
- Deathwing Terminator Squad
### DEATHWATCH
- [ ] Chaplain Cassius currently costs 95 pts, but should cost 85 pts
- [ ] Codicier Natorian currently costs 100 pts, but should cost 90 pts
- [ ] Watch Captain Artemis currently costs 105 pts, but should cost 95 pts
- [ ] Watch Master currently costs 130 pts, but should cost 115 pts
- [ ] Deathwatch Veterans currently cost 20 pts per model, but should cost 27 pts per model
- [ ] Deathwatch Veterans > Deathwatch Veteran w/ Heavy Thunder Hammer’s heavy thunder hammer currently costs 15 pts, but should cost 12 pts
- [ ] Deathwatch Veterans > Watch Sergeant’s xenophase blade currently costs 10 pts, but should cost 5 pts
- [ ] Deathwatch Veterans > Watch Sergeant’s combat shield currently costs 4 pts, but should cost 0 pts
- [ ] Deathwatch Veterans’ stalker-pattern boltgun currently costs 3 pts, but should cost 0 pts
- [ ] Grav-pistol currently costs 5 pts, but should cost 0 pts for:
- Deathwatch Veterans
- Veteran Bike Squad > Veteran Biker Sergeant
- [ ] Hand flamer currently costs 5 pts, but should cost 0 pts for:
- Deathwatch Veterans
- Veteran Bike Squad > Veteran Biker Sergeant
- [ ] Inferno pistol currently costs 5 pts, but should cost 0 pts for:
- Deathwatch Veterans
- Veteran Bike Squad > Veteran Biker Sergeant
- [ ] Deathwatch Veterans’ lightning claw currently costs 3 pts, but should cost 0 pts
- [ ] Plasma pistol currently costs 5 pts, but should cost 0 pts for:
- Deathwatch Veterans
- Veteran Bike Squad > Veteran Biker Sergeant
- [ ] Deathwatch Veterans’ power axe currently costs 3 pts, but should cost 0 pts
- [ ] Deathwatch Veterans’ power fist currently costs 8 pts, but should cost 0 pts
- [ ] Deathwatch Veterans’ power maul currently costs 3 pts, but should cost 0 pts
- [ ] Deathwatch Veterans’ power sword currently costs 3 pts, but should cost 0 pts
- [ ] Storm shield currently costs 5 pts, but should cost 0 pts for:
- Deathwatch Veterans
- Veteran Bike Squad > Veteran Biker Sergeant
- [ ] Deathwatch Veterans’ Deathwatch combi-flamer currently costs 5 pts, but should cost 0 pts
- [ ] Deathwatch Veterans’ Deathwatch combi-grav currently costs 10 pts, but should cost 0 pts
- [ ] Deathwatch Veterans’ Deathwatch combi-melta currently costs 10 pts, but should cost 0 pts
- [ ] Deathwatch Veterans’ Deathwatch combi-plasma currently costs 10 pts, but should cost 0 pts
- [ ] Flamer currently costs 5 pts, but should cost 0 pts for:
- Deathwatch Veterans
- Veteran Bike Squad > Veteran Biker Sergeant
- [ ] Deathwatch Veterans’ grav-gun currently costs 5 pts, but should cost 0 pts
- [ ] Deathwatch Veterans’ meltagun currently costs 5 pts, but should cost 0 pts
- [ ] Deathwatch Veterans’ plasma gun currently costs 5 pts, but should cost 0 pts
- [ ] Storm bolter currently costs 5 pts, but should cost 0 pts for:
- Deathwatch Veterans
- Veteran Bike Squad > Veteran Biker Sergeant
- [ ] Kill Team Cassius currently costs 240 pts, but should cost 220 pts
- [ ] Deathwatch Terminator Squad currently cost 33 pts per model, but should cost 35 pts per model
- [ ] Deathwatch Terminator Squad’s power fist currently costs 5 pts, but should cost 0 pts
- [ ] Deathwatch Terminator Squad’s chainfist currently costs 5 pts, but should cost 0 pts
- [ ] Thunder hammer currently costs 10 pts, but should cost 0 pts for:
- Deathwatch Terminator Squad
- Veteran Bike Squad > Veteran Biker Sergeant
- [ ] Deathwatch Terminator Squad’s teleport homer currently costs 5 pts, but should cost 0 pts
- [ ] Deathwatch Terminator Squad’s assault cannon currently costs 15 pts, but should cost 0 pts
- [ ] Deathwatch Terminator Squad’s cyclone missile launcher currently costs 20 pts, but should cost 10 pts
- [ ] Deathwatch Terminator Squad’s heavy flamer currently costs 10 pts, but should cost 0 pts
- [ ] Deathwatch Terminator Squad’s plasma cannon currently costs 15 pts, but should cost 0 pts
- [ ] Veteran Bike Squad currently cost 30 pts per model, but should cost 35 pts per model
- [ ] Veteran Bike Squad > Veteran Attack Bike’s heavy bolter currently costs 20 pts, but should cost 0 pts
- [ ] Veteran Bike Squad > Veteran Attack Bike’s multi-melta currently costs 30 pts, but should cost 0 pts
- [ ] Veteran Bike Squad’s power axe currently costs 3 pts, but should cost 0 pts
- [ ] Veteran Bike Squad’s power maul currently costs 3 pts, but should cost 0 pts
- [ ] Veteran Bike Squad’s power sword currently costs 3 pts, but should cost 0 pts
- [ ] Veteran Bike Squad > Veteran Biker Sergeant’s Deathwatch shotgun currently costs 5 pts, but should cost 0 pts
- [ ] Veteran Bike Squad > Veteran Biker Sergeant’s stalker-pattern boltgun currently costs 5 pts, but should cost 0 pts
- [ ] Veteran Bike Squad > Veteran Biker Sergeant’s lightning claw currently costs 5 pts, but should cost 0 pts
- [ ] Veteran Bike Squad > Veteran Biker Sergeant’s power fist currently costs 10 pts, but should cost 0 pts
- [ ] Veteran Bike Squad > Veteran Biker Sergeant’s xenophase blade currently costs 10 pts, but should cost 0 pts
- [ ] Veteran Bike Squad > Veteran Biker Sergeant’s Deathwatch boltgun currently costs 5 pts, but should cost 0 pts
- [ ] Veteran Bike Squad > Veteran Biker Sergeant’s Deathwatch combi-flamer currently costs 10 pts, but should cost 0 pts
- [ ] Veteran Bike Squad > Veteran Biker Sergeant’s Deathwatch combi-grav currently costs 15 pts, but should cost 0 pts
- [ ] Veteran Bike Squad > Veteran Biker Sergeant’s Deathwatch combi-melta currently costs 15 pts, but should cost 0 pts
- [ ] Veteran Bike Squad > Veteran Biker Sergeant’s Deathwatch combi-plasma currently costs 15 pts, but should cost 0 pts
- [ ] Veteran Bike Squad > Veteran Biker Sergeant’s grav-gun currently costs 10 pts, but should cost 0 pts
- [ ] Veteran Bike Squad > Veteran Biker Sergeant’s meltagun currently costs 10 pts, but should cost 0 pts
- [ ] Veteran Bike Squad > Veteran Biker Sergeant’s plasma gun currently costs 10 pts, but should cost 0 pts
- [ ] Corvus Blackstar currently costs 165 pts, but should cost 150 pts
- [ ] Corvus Blackstar’s hurricane bolter currently costs 15 pts, but should cost 0 pts
- [ ] Corvus Blackstar’s auspex array currently costs 5 pts, but should cost 0 pts
- [ ] Corvus Blackstar’s infernum halo-launcher currently costs 10 pts, but should cost 0 pts
- [ ] Aquila Kill Team Specialism currently costs 10 pts, but should cost 15 pts
- [ ] Dominatus Kill Team Specialism currently costs 15 pts, but should cost 20 pts
- [ ] Furor Kill Team Specialism currently costs 25 pts, but should cost 30 pts
- [ ] Malleus Kill Team Specialism currently costs 25 pts, but should cost 30 pts
- [ ] Purgatus Kill Team Specialism currently costs 15 pts, but should cost 20 pts
- [ ] Venator Kill Team Specialism currently costs 15 pts, but should cost 20 pts
### ULTRAMARINES
- [x] The non-Legends version of Honour Guard currently cost 25 pts per model, but should cost 45 pts for the entire unit
### SPACE WOLVES
- [x] Arjac Rockfist currently costs 110 pts, but should cost 100 pts
- [x] Bjorn the Fell-handed currently costs 175 pts, but should cost 155 pts
- [x] Canis Wolfborn currently costs 110 pts, but should cost 100 pts
- [x] Harald Deathwolf currently costs 130 pts, but should cost 120 pts
- [x] Krom Dragongaze currently costs 100 pts, but should cost 90 pts
- [x] Logan Grimnar currently costs 155 pts, but should cost 140 pts
- [x] Logan Grimnar on Stormrider currently costs 180 pts, but should cost 160 pts
- [x] Njal Stormcaller currently costs 140 pts, but should cost 120 pts
- [x] Ragnar Blackmane currently costs 120 pts, but should cost 110 pts
- [x] Ulrik the Slayer currently costs 110 pts, but should cost 100 pts
- [x] Wolf Guard Battle Leader in Terminator Armour currently costs 85 pts, but should cost 75 pts
- [x] Storm shield currently costs 5 pts, but should cost 0 pts for:
- Wolf Guard Battle Leader in Terminator Armour
- Blood Claws > Wolf Guard Pack Leader
- Blood Claws > Wolf Guard Terminator Pack Leader
- Grey Hunters > Wolf Guard Pack Leader
- Grey Hunters > Wolf Guard Terminator Pack Leader
- Thunderwolf Cavalry
- Long Fangs > Wolf Guard Pack Leader
- Long Fangs > Wolf Guard Terminator Pack Leader
- [x] Chainfist currently costs 5 pts, but should cost 0 pts for:
- Wolf Guard Battle Leader in Terminator Armour
- Blood Claws > Wolf Guard Terminator Pack Leader
- Grey Hunters > Wolf Guard Terminator Pack Leader
- Wolf Guard Terminators
- Long Fangs > Wolf Guard Terminator Pack Leader
- [x] Power fist currently costs 5 pts, but should cost 0 pts for:
- Wolf Guard Battle Leader in Terminator Armour
- Blood Claws > Wolf Guard Terminator Pack Leader
- Grey Hunters > Wolf Guard Terminator Pack Leader
- Wolf Guard Terminators
- Skyclaws > Skyclaw Pack Leader
- Long Fangs > Wolf Guard Terminator Pack Leader
- [x] Wolf Guard Battle Leader in Terminator Armour’s thunder hammer currently costs 15 pts, but should cost 5 pts
- [x] Combi-flamer currently costs 5 pts, but should cost 0 pts for:
- Wolf Guard Battle Leader in Terminator Armour
- Blood Claws > Wolf Guard Terminator Pack Leader
- Grey Hunters > Wolf Guard Terminator Pack Leader
- Wolf Guard Terminators
- Long Fangs > Wolf Guard Terminator Pack Leader
- [x] Combi-grav currently costs 5 pts, but should cost 0 pts for:
- Wolf Guard Battle Leader in Terminator Armour
- Blood Claws > Wolf Guard Terminator Pack Leader
- Grey Hunters > Wolf Guard Terminator Pack Leader
- Wolf Guard Terminators
- Long Fangs > Wolf Guard Terminator Pack Leader
- [x] Combi-melta currently costs 5 pts, but should cost 0 pts for:
- Wolf Guard Battle Leader in Terminator Armour
- Blood Claws > Wolf Guard Terminator Pack Leader
- Grey Hunters > Wolf Guard Terminator Pack Leader
- Wolf Guard Terminators
- Long Fangs > Wolf Guard Terminator Pack Leader
- [x] Combi-plasma currently costs 5 pts, but should cost 0 pts for:
- Wolf Guard Battle Leader in Terminator Armour
- Blood Claws > Wolf Guard Terminator Pack Leader
- Grey Hunters > Wolf Guard Terminator Pack Leader
- Wolf Guard Terminators
- Long Fangs > Wolf Guard Terminator Pack Leader
- [x] Plasma pistol currently costs 5 pts, but should cost 0 pts for:
- Wolf Guard Battle Leader on Thunderwolf
- Wolf Lord on Thunderwolf
- Blood Claws > Wolf Guard Pack Leader
- Blood Claws > Blood Claw with Plasma Pistol
- Grey Hunters > Grey Hunter w/Plasma Pistol
- Grey Hunters > Grey Hunter with Special Weapon
- Grey Hunters > Wolf Guard Pack Leader
- Wolf Guard
- Thunderwolf Cavalry
- Long Fangs > Long Fang Pack Leader
- Long Fangs > Wolf Guard Pack Leader
- [x] Combi-flamer currently costs 10 pts, but should cost 0 pts for:
- Wolf Guard Battle Leader on Thunderwolf
- Wolf Lord on Thunderwolf
- Blood Claws > Wolf Guard Pack Leader
- Grey Hunters > Wolf Guard Pack Leader
- Wolf Guard
- Long Fangs > Wolf Guard Pack Leader
- [x] Combi-grav currently costs 10 pts, but should cost 0 pts for:
- Wolf Guard Battle Leader on Thunderwolf
- Wolf Lord on Thunderwolf
- Blood Claws > Wolf Guard Pack Leader
- Grey Hunters > Wolf Guard Pack Leader
- Wolf Guard
- Long Fangs > Wolf Guard Pack Leader
- [x] Combi-melta currently costs 10 pts, but should cost 0 pts for:
- Wolf Guard Battle Leader on Thunderwolf
- Wolf Lord on Thunderwolf
- Blood Claws > Wolf Guard Pack Leader
- Grey Hunters > Wolf Guard Pack Leader
- Wolf Guard
- Long Fangs > Wolf Guard Pack Leader
- [x] Combi-plasma currently costs 10 pts, but should cost 0 pts for:
- Wolf Guard Battle Leader on Thunderwolf
- Wolf Lord on Thunderwolf
- Blood Claws > Wolf Guard Pack Leader
- Grey Hunters > Wolf Guard Pack Leader
- Wolf Guard
- Long Fangs > Wolf Guard Pack Leader
- [x] Storm bolter currently costs 5 pts, but should cost 0 pts for:
- Wolf Guard Battle Leader on Thunderwolf
- Wolf Lord on Thunderwolf
- Blood Claws > Wolf Guard Pack Leader
- Grey Hunters > Wolf Guard Pack Leader
- Wolf Guard
- Long Fangs > Wolf Guard Pack Leader
- [x] Lightning claw currently costs 5 pts, but should cost 0 pts for:
- Wolf Guard Battle Leader on Thunderwolf
- Wolf Lord on Thunderwolf
- Blood Claws > Wolf Guard Pack Leader
- Grey Hunters > Wolf Guard Pack Leader
- Thunderwolf Cavalry
- Long Fangs > Wolf Guard Pack Leader
- [x] Power axe currently costs 5 pts, but should cost 0 pts for:
- Wolf Guard Battle Leader on Thunderwolf
- Wolf Lord on Thunderwolf
- Blood Claws > Blood Claws Pack Leader
- Blood Claws > Wolf Guard Pack Leader
- Grey Hunters > Wolf Guard Pack Leader
- Thunderwolf Cavalry
- Long Fangs > Long Fang Pack Leader
- Long Fangs > Wolf Guard Pack Leader
- [x] Power fist currently costs 10 pts, but should cost 0 pts for:
- Wolf Guard Battle Leader on Thunderwolf
- Wolf Lord on Thunderwolf
- Blood Claws > Blood Claws Pack Leader
- Blood Claws > Wolf Guard Pack Leader
- Grey Hunters > Wolf Guard Pack Leader
- Long Fangs > Long Fang Pack Leader
- Long Fangs > Wolf Guard Pack Leader
- [x] Power maul currently costs 5 pts, but should cost 0 pts for:
- Wolf Guard Battle Leader on Thunderwolf
- Wolf Lord on Thunderwolf
- Blood Claws > Wolf Guard Pack Leader
- Grey Hunters > Wolf Guard Pack Leader
- Thunderwolf Cavalry
- Long Fangs > Wolf Guard Pack Leader
- [x] Power sword currently costs 5 pts, but should cost 0 pts for:
- Wolf Guard Battle Leader on Thunderwolf
- Wolf Lord on Thunderwolf
- Blood Claws > Blood Claws Pack Leader
- Blood Claws > Wolf Guard Pack Leader
- Grey Hunters > Wolf Guard Pack Leader
- Thunderwolf Cavalry
- Long Fangs > Long Fang Pack Leader
- Long Fangs > Wolf Guard Pack Leader
- [x] Thunder hammer currently costs 20 pts, but should cost 10 pts for:
- Wolf Guard Battle Leader on Thunderwolf
- Wolf Lord on Thunderwolf
- [x] Storm shield currently costs 10 pts, but should cost 0 pts for:
- Wolf Guard Battle Leader on Thunderwolf
- Wolf Lord on Thunderwolf
- [x] Blood Claws currently cost 18 pts per model, but should cost 17 pts per model
- [x] Blood Claws > Wolf Guard Terminator Pack Leader currently costs 33 pts, but should cost 34 pts
- [x] Thunder hammer currently cost 15 pts, but should cost 10 pts for:
- Blood Claws > Wolf Guard Pack Leader
- Grey Hunters > Wolf Guard Pack Leader
- Thunderwolf Cavalry
- [x] Thunder hammer currently costs 10 pts, but should cost 0 pts for:
- Blood Claws > Wolf Guard Terminator Pack Leader
- Grey Hunters > Wolf Guard Terminator Pack Leader
- Wolf Guard Terminators
- Long Fangs > Wolf Guard Terminator Pack Leader
- [x] Flamer currently costs 5 pts, but should cost 0 pts for:
- Blood Claws > Blood Claw with Special Weapon
- Grey Hunters > Grey Hunter with Special Weapon
- Long Fangs > Long Fang Pack Leader
- [x] Grav-gun currently costs 10 pts, but should cost 0 pts for:
- Blood Claws > Blood Claw with Special Weapon
- Grey Hunters > Grey Hunter with Special Weapon
- [x] Meltagun currently costs 10 pts, but should cost 0 pts for:
- Blood Claws > Blood Claw with Special Weapon
- Grey Hunters > Grey Hunter with Special Weapon
- Long Fangs > Long Fang Pack Leader
- [x] Plasma gun currently costs 10 pts, but should cost 0 pts for:
- Blood Claws > Blood Claw with Special Weapon
- Grey Hunters > Grey Hunter with Special Weapon
- Long Fangs > Long Fang Pack Leader
- [x] Grey Hunters’ Astartes chainsword currently costs 1 pts, but should cost 0 pts
- [x] Grey Hunters’ wolf standard currently costs 5 pts, but should cost 0 pts
- [x] Grey Hunters > Wolf Guard Terminator Pack Leader currently costs 33 pts, but should cost 34 pts
- [x] Hounds of Morkai currently cost 20 pts per model, but should cost 17 pts per model
- [x] Lukas the Trickster currently costs 80 pts, but should cost 70 pts
- [x] Murderfang currently costs 150 pts, but should cost 140 pts
- [x] Wolf Guard currently cost 19 pts per model, but should cost 20 pts per model
- [x] Wolf Guard’s jump pack currently costs 4 pts, but should cost 3 pts
- [x] Wolf Guard’s storm shield currently costs 4 pts, but should cost 5 pts
- [x] Wolf Guard’s power fist currently costs 8 pts, but should cost 5 pts
- [x] Wolf Guard’s thunder hammer currently costs 12 pts, but should cost 10 pts
- [x] Wolf Guard’s power axe currently costs 3 pts, but should cost 0 pts
- [x] Wolf Guard’s power maul currently costs 3 pts, but should cost 0 pts
- [x] Wolf Guard’s power sword currently costs 3 pts, but should cost 0 pts
- [x] Wolf Guard Terminators currently cost 33 pts per model, but should cost 34 pts per model
- [x] Cyclone missile launcher currently costs 25 pts, but should cost 0 pts for:
- Wolf Guard Terminators
- Long Fangs > Wolf Guard Terminator Pack Leader
- [x] Wolf Guard Terminators > Wolf Guard in Terminator with Heavy Weapon’s assault cannon currently costs 10 pts, but should cost 0 pts
- [x] Heavy flamer currently costs 5 pts, but should cost 0 pts for:
- Wolf Guard Terminators > Wolf Guard in Terminator with Heavy Weapon
- Long Fangs > Wolf Guard Terminator Pack Leader
- [x] Wulfen’s stormfrag auto launcher currently costs 3 pts, but should cost 0 pts
- [x] Wulfen Dreadnought’s heavy flamer currently costs 5 pts, but should cost 0 pts
- [x] Meltagun currently costs 5 pts, but should cost 0 pts for:
- Skyclaws > Skyclaw Pack Leader
- Skyclaws > Skyclaw with Special Weapon
- [x] Plasma gun currently costs 5 pts, but should cost 0 pts for:
- Skyclaws > Skyclaw Pack Leader
- Skyclaws > Skyclaw with Special Weapon
- [x] Thunderwolf Cavalry currently cost 40 pts per model, but should cost 35 pts per model
- [x] Thunderwolf Cavalry’s power fist currently costs 10 pts, but should cost 5 pts
- [x] Long Fangs currently cost 18 pts per model, but should cost 23 pts per model
- [x] Long Fangs’ armorium cherub currently costs 5 pts, but should cost 0 pts
- [x] Long Fangs’ heavy bolter currently costs 10 pts, but should cost 0 pts
- [x] Long Fangs’ lascannon currently costs 15 pts, but should cost 0 pts
- [x] Long Fangs’ missile launcher currently costs 15 pts, but should cost 0 pts
- [x] Long Fangs’ multi-melta currently costs 20 pts, but should cost 10 pts
- [x] Long Fangs’ plasma cannon currently costs 15 pts, but should cost 0 pts
- [x] Long Fangs > Long Fang Pack Leader’s grav-gun currently costs 5 pts, but should cost 0 pts
- [x] Long Fangs > Wolf Guard Terminator Pack Leader currently costs 33 pts, but should cost 34 pts
- [x] Long Fangs > Wolf Guard Pack Leader’s thunder hammer currently costs 15 pts, but should cost 0 pts
- [x] Long Fangs > Wolf Guard Terminator Pack Leader’s assault cannon currently costs 5 pts, but should cost 0 pts
- [x] Stormfang Gunship currently costs 250 pts, but should cost 225 pts
- [x] Stormfang Gunship’s lascannon currently costs 10 pts, but should cost 0 pts
- [x] Stormfang Gunship’s lascannon currently costs 10 pts, but should cost 0 pts
- [x] Melta array currently costs 25 pts, but should cost 0 pts for:
- Stormfang Gunship
- Stormwolf
- [x] Twin heavy bolter currently costs 20 pts, but should cost 0 pts for:
- Stormfang Gunship
- Stormwolf
- [x] Stormwolf currently costs 250 pts, but should cost 225 pts

**Comment by ThePants999** [comment]
Seeing that the SW stuff is all ticked, I'll highlight a couple of issues I spotted using the latest committed file:

- [x] Wolf Guard Terminators have been updated to 34 points, but the Wolf Guard Terminator Pack Leader in a Wolf Guard Terminators unit is still 33
- [x] Long Fangs' cherub is still 5pts despite being ticked above
- [x] Melee weapons have not been reduced to 0pts for Grey Hunter Pack Leader or Sky ~~Blood~~ Claw Pack Leader

Edit by @Mad-Spy: All fixed, plus Wolf Guard Sky Claw Pack Leader

**Comment by smajchrz** [comment]
In release version 9.7.0 

- [ ] Wolf Guard in Skyclaws unit (Space Wolves) should have all equipmeny for 0p. Currently Thunder Hammer cost 10p instead.
- [ ] Wolf Guard in Long Fangs unit (Space Wolves) should have all equipmeny for 0p. Currently Thunder Hammer cost 10p instead
- [ ] Wolf Guard Terminator in Long Fangs unit (Space Wolves) should have all equipmeny for 0p. Currently Thunder Hammer cost 10p instead
