### ISSUE TITLE
Validation Reports Error When Selecting First Free Artifact for Tyranid Force

### ISSUE THREAD

**Issue by joebobmiles** [BSData/wh40k-9e#12089]
**Describe the bug**
Tyranid forces do not allow you to select free bio-artifact, reporting a maxiumum of zero allowed.

**To Reproduce**
1. Create any kind of Tyranid force.
2. Add a Tyranid character to the roster.
3. Select a Bio-artifact for the character.
4. Check roster validation errors for "has 1 too many selections from Bio-artifacts (maximum 0).

**Expected behavior**
Expected the validation error "has 1 too many selections from Bio-artifacts (maximum 0)" to not appear when selecting the first Bio-artifact in a Tyranid force.

**Screenshots**
![Screen Cap](https://user-images.githubusercontent.com/19335924/211168732-cf6a8517-7905-4375-96ea-b7a05513573e.png)

**Device and data (please complete the following information):**
 - OS: Windows 11
 - BattleScribe version 2.03.21
 - Release version 9.6.14

**Comment by AbonShell** [comment]
Since nephilim, you no longer get a free relic or warlord trait.

**Comment by joebobmiles** [comment]
Only applicable to Nephilim or all games?

![image](https://user-images.githubusercontent.com/19335924/211177607-38f5ae32-18d0-4d26-8611-417c4ac69f0a.png)

![image](https://user-images.githubusercontent.com/19335924/211177623-dda6c850-c926-4f3d-8d20-290ea7dd66e1.png)

![image](https://user-images.githubusercontent.com/19335924/211177646-df61402f-ec99-42c1-baf8-53dc47925c91.png)
