### ISSUE TITLE
MFM Points update Jan 2023

### ISSUE THREAD

**Issue by AbonShell** [BSData/wh40k-9e#12087]
- [x] Aeldari
     - [x] Craftworlds
     - [x] Drukhari
     - [x] Harlequins 
     - [x] Ynnari
- [x] Chaos
     - [x] Chaos Knights
     - [x] Chaos Space Marines
     - [x] Daemons
     - [x] Death Guard
     - [x] Thousand Sons
     - [x] FW Heretic Astartes
     - [x] FW Renegade and Heretics
     - [x] Gellerpox Infected
     - [x] Servants of the Abyss
     - [x] Titanicus Traitoris
- [x] Imperium
     - [x] Adepta Sororitas
     - [x] Adeptus Astra Telepathica
     - [x] Adeptus Custodes
     - [x] Adeptus Mechanicus
     - [x] Astra Cartographcia
     - [x] Astra Militarum
     - [x] Black Templars
     - [x] Blood Angels
     - [x] Dark Angels
     - [x] Deathwatch
     - [x] Euclidian Starstriders
     - [x] FW Adeptus Astartes
     - [x] FW DKoK
     - [x] Grey Knights
     - [x] Imperial Fists
     - [x] Imperial Knights
     - [x] Inquisition
     - [x] Iron Hands
     - [x] LotD
     - [x] Officio Assassinorum
     - [x] Raven Guard
     - [x] Salamanders
     - [x] Space Marines
     - [x] Space Wolves
     - [x] Titan Legions
     - [x] Ultramarines
     - [x] White Scars
- [x] Xenos 
     - [x] Leagues of Votann
     - [x] Necrons
     - [x] Orks
     - [x] T'au Empire
     - [x] Tyranids
     - [x] Genestealer Cults

**Comment by byLemon12** [comment]
Hey, just noticed with Drukhari in the Master file shared on Discord that the Archons weapon upgrades (Huskblase and Blast Pistol) are still pointed at 5 each where they have been updated to be removed.

**Comment by FarseerVeraenthis** [comment]
> Hey, just noticed with Drukhari in the Master file shared on Discord that the Archons weapon upgrades (Huskblase and Blast Pistol) are still pointed at 5 each where they have been updated to be removed.

Thanks, I just updated this!

**Comment by MrCuba12** [comment]
Good Evening

Thanks for the updates however the for the Death Guard, the Plagueburst Crawler's Entropy Cannons should be 5pts rather than 10pts

**Comment by niurvindol** [comment]
Just noticed that Drukhari doesn’t have the option for Realspace Raid if using the arks detachment
