### ISSUE TITLE
Strategem: Warlord Trait -1CP option available and does nothing for Lucius the Eternal in Boarding Patrol Detachment

### ISSUE THREAD

**Issue by sterling000** [BSData/wh40k-9e#12095]
**Describe the bug**
In a CSM Boarding Patrol Detachment, Game Type Arks of Omen, Legion Emperor's Children, if Lucius the Eternal is your Warlord, the Strategem: Warlord Trait -1CP option is available to be selected and turning it on or off does nothing.

**To Reproduce**
1. Create a CSM Boarding Patrol Force
2. Set the Battle Size to Combat Patrol
3. Set the Game Type to 5. Chapter Approved: Arks of Omen
4. Set the Legion to Emperor's Children
5. Add Lucius the Eternal to the Boarding Patrol
6. Toggle "Warlord" to True for Lucius the Eternal
7. Observe "Strategem: Warlord Trait -1CP" shows in the options
8. Toggle "Strategem: Warlord Trait -1CP" On and Off, notice no new options are displayed, but the user's CP balance is affected.

**Expected behavior**
No Strategem Warlord Trait option should be listed if he can't take one.

**Screenshots**
Repro steps should be pretty clear

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version 2.03.21
 - Release version Directly pulled from git repo, currently at commit f0f8d4 on master.

**Additional context**
I'm aware there is an upcoming release and this is a minor issue, just thought I'd put in the report anyway and let you guys decide on priority.

**Comment by Mad-Spy** [comment]
Fixed in next release.
