### ISSUE TITLE
Orks: Weird behaviour with WLTs and Relics

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12098]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Won't let me choose a warlord trait or relic for the character selected as my warlord (orks: Warboss in Mega Armor and Weirdboy) but will then let me choose them for my other character instead. 

When warboss is selected as warlord, stratagem options appear for weird boy and after selecting them, they appear on my warboss as options and visa versa when weirdboy is selected as warlord.

**Comment by andresqevedo** [comment]
@Mad-Spy sorry I reported the same bug here https://github.com/BSData/wh40k/issues/12168 without checking first. I added more info in case it helps.
