### ISSUE TITLE
Astra Militarum - No Tanks?

### ISSUE THREAD

**Issue by BitterLies** [BSData/wh40k-9e#121]
**File/Catalogue:** 
Astra Militarum v2
**BattleScribe version:** 2.01.
2.01.02
**Platform:** Windows/iOS/Android/Mac/Linux
Windows
**Dropbox:** Yes/No
No
**Description:** Detailed issue description.
No vehicles of any kind available for selection.  Company Commander listed as Uncategoriezed, with numerous other squads/choices.  Commissars listed as HQ Choices (should be elites).  I've updated, deleted, then updated my install and files a few times.  Including screenshot
![capture](https://user-images.githubusercontent.com/25520602/27254236-54c48634-534a-11e7-8b77-0f0ebc02e27b.PNG)

**Comment by alphalas** [comment]
will be fixed with the next release
