### ISSUE TITLE
Chaos Space Marines Greater Brass Scorpion 

### ISSUE THREAD

**Issue by Tzardukar** [BSData/wh40k-9e#12100]
**Describe the bug**
demolisher cannon shows an incorrect rate of fire. 
It should be D3+3, but it says D6. 
![0F76D5F6-CB34-403D-A2A7-81018345C2BC](https://user-images.githubusercontent.com/122356541/211532827-a2916eb1-2c4f-4f02-be29-fd0fa65a6eea.jpeg)

**Screenshots**
See attached file

**Device and data (please complete the following information):**
 - OS: iOS
 - BattleScribe version 2.03.45
 - data file: 9.6.14

**Comment by Mad-Spy** [comment]
The model's datasheet states it is D6, and this has not been changed by errata as far as I can discover. If you have a GW source for this change, please provide it.
