### ISSUE TITLE
Grey Knights: Some wargear points values not updated

### ISSUE THREAD

**Issue by rap6tor** [BSData/wh40k-9e#12112]
**Describe the bug**
I've installed the latest version of the Grey Knights .cat and the wargear points values for several units has not been updated. For example, Brotherhood Terminator squads still must pay 5-10 points for their special weapons. A few other examples I've found so far:

Brotherhood Librarian Storm bolter hand options
Teleporter on Dreadknight and Grandmaster Dreadknight still costs 10 points.
Rhino and Razorback still must pay for Storm bolter and Razorback turret options.
All Land Raider Variants (Excluding Land Raider Banisher) must pay for upgrades
Purgation Squad Psycannon options still costs 5 points
Dreadnought Weapon Options still cost points
ETC.

Did not review all units so it would be recommended to double check all wargear points values.

**To Reproduce**
1. Go to one of the above listed units
2. Add wargear
3. Points cost incorrect as per Chaper Approved

**Expected behavior**
All of the above examples should have a points cost of 0.

**Screenshots**
![Screenshot 2023-01-11 162800](https://user-images.githubusercontent.com/72809917/211921537-128bd8ae-f08d-47fd-b167-d804a8fcfa95.png)

**Device and data (please complete the following information):**
 - OS: Android 13
 - BattleScribe version [e.g. 2.03.45] 2.03.25
 - Release version [e.g. v1.2.3] v115

**Additional context**
I updated the code on line 3508 (highlighted in above screenshot) to  <cost name="pts" typeId="points" value="0.0"/> and this fixed the Incinerator option for the Brotherhood Terminator Squad. Likely same fix for all the above examples.

Hope this helps, and apologies if this has been reported already.

**Comment by AbonShell** [comment]
Fixed in next release
