### ISSUE TITLE
Chaos - Chaos Knights: Unable to select Relic stratagem in AoO game type

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12117]
**File:** Chaos - Chaos Knights.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Unable to give a relic using Stratagem: Relic to a knights warlord or character. BS will allow to give a relic for free (which shouldn't be allowed) and to use WT stratagem, but not relic stratagem.

**Comment by Mad-Spy** [comment]
Fixed
