### ISSUE TITLE
Death Guard: Chimes of Contagion points values incorrect

### ISSUE THREAD

**Issue by Zeruke** [BSData/wh40k-9e#12115]
The following unit has incorrect point values for equipment.
Deathshroud Terminators: Chimes of Contagion is now free not 15 points. 
As per arks of omen balance dataslate.

![javaw_QSqVbVowMc](https://user-images.githubusercontent.com/52841409/211962493-16ea744b-9eb0-40f2-9544-60dd87c81d17.png)

**Comment by elodingens** [comment]
MFM 2023 Point Updates are not live yet, check https://github.com/BSData/wh40k/issues/12087

Is this still an issue then?

**Comment by Mad-Spy** [comment]
@elodingens lots of people have downloaded the pre-release data, even if they do fail to tell us that's what they're using! You don't need to comment every time. thanls.
