### ISSUE TITLE
Space Wolves: Logan Grimnar on Stormrider should be Chariot

### ISSUE THREAD

**Issue by SoSaltySalt** [BSData/wh40k-9e#12124]
**Describe the bug**
Logan Grimnar on Stormrider is marked as Vehicle and Cavalry, when he should be Chariot.

**Expected behavior**
Should just have Chariot, and as such be able to be taken in a Boarding Patrol.

**Comment by Mad-Spy** [comment]
Changed for now, as it's RAW, but I'm fully expecting that they'll close that loophole.
