### ISSUE TITLE
Astra Militarium - Super-heavy can no longer take Hunter Killer Missile

### ISSUE THREAD

**Issue by TommyKnoxx** [BSData/wh40k-9e#12125]
**Describe the bug**
Super-heavy can no longer take Hunter Killer. 
Baneblade
Banehammer
Banesword
Doomhammer
Hellhammer
Shadowsword
Stormlord
Stormsword

**To Reproduce**
Create any Astra Militarium detachement than can add a Lord of war/Super-Heavy then open that unit. There is a box to add a Hunter Killer Missile. That should be removed. 

**Expected behavior**
Not being able to add a Hunter Killer Missile 

**Screenshots**
![Screenshot_20230113-125027](https://user-images.githubusercontent.com/70916607/212314979-456d0a46-5c18-4208-93ef-f78204488156.png)

**Device and data (please complete the following information):**
 - OS: Android
 - BattleScribe version v2.03.25.338
 - Release version: Warhammer 40.000 v.9.6.14

**Additional context**

**Comment by AbonShell** [comment]
Fixed in next release
