### ISSUE TITLE
Imperium - Space Marines: Rapier Carrier should include a boltgun

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12123]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Rapier Carrier is missing the crew's boltgun profile:
24", Rapid fire 1, D4, AP0, D1

Source: Imperial Armour: Compendium. Warhammer 40K app with subscription.

**Comment by AbonShell** [comment]
No where on it's actual datasheet does it say that  the space marine crew is equipped with anything.

**Comment by AbonShell** [comment]
The profile does say it has a boltgun, but doesn't specify that it's the space marine crew's
