### ISSUE TITLE
The plague marines points is wrong

### ISSUE THREAD

**Issue by plaguemarine** [BSData/wh40k-9e#12126]
The plague marines points should be 19 per model even for the plague champions as per the new 2023 points data sheet update, but on battle script (I have made sure it’s all up to date) the points is still 21 per model. Btw I have uploaded some images to prove it and save you time. Thank you!

![0E711893-A129-43D6-AFB9-060A0FC5BFE9](https://user-images.githubusercontent.com/39224213/212324472-d9689f0c-3fc3-4988-802f-b05c81058dd4.png)
![4B13280B-CCAC-49BA-8657-B85074ADABD6](https://user-images.githubusercontent.com/39224213/212324473-f1c57475-c1d3-4b77-86e5-1bb5e9bbf87f.png)

![0967BDDA-5983-4532-96A5-6E672CE6D335](https://user-images.githubusercontent.com/39224213/212324465-f3203231-ba4a-4b62-8817-3135e47fa45b.png)
![C8430343-FD11-479F-8350-2751496B91CB](https://user-images.githubusercontent.com/39224213/212324470-3742fac8-1999-457c-a79b-e7a891e96858.png)

**Comment by Mad-Spy** [comment]
We haven't released the points update yet, as per #12087

**Comment by plaguemarine** [comment]
When do you think you will update the points

**Comment by Mad-Spy** [comment]
The previously mentioned ticket #12087 lists all the Factions and their current status. Once they're all done, it'll be ready for release. So, at some point after that issue gets closed.

**Comment by plaguemarine** [comment]
Thank you

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
