### ISSUE TITLE
Grey Knights; Cost for special weapon Troops models have not been updated

### ISSUE THREAD

**Issue by Apolom1994** [BSData/wh40k-9e#12129]
File: Imperium - Grey Knights.catz

BattleScribe version: 2.03.25

Platform: PC/Windows

Dropbox: No

Description: The troops for the grey knights can add a special weapon model for free, (35pts. nor 40pts)

**Comment by Mad-Spy** [comment]
Specifically, all three Terminator options haven't been reduced in cost for the model and the Psycannon options in both Terminator and Strike Squads are still paying for their psycannon.
