### ISSUE TITLE
Space Marines: WLT Trait is available for free in AoO rules

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12138]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 9.70.00

**Platform:** Windows

**Dropbox:** No

**Description:** First Warlord trait is bugged and doesn't cost CP. This is specifically for Guilliman, but unsure if everyone else is going through the same thing

**Comment by acebaur** [comment]
It's bugged for all the 8th codex chapters. It'll be fixed in the next release
