### ISSUE TITLE
Adeptus Mechanicus - Warlord Trait accessible without the stratagem [AoO]

### ISSUE THREAD

**Issue by MateuszWicherski** [BSData/wh40k-9e#12139]
**Describe the bug**
When Warlord is selected, he can take a Warlord Trait regardless of selecting the `Warlord Trait` stratagem.

**To Reproduce**
1. Create AdMech Arks of Omen detachment
2. Add Tech Priest Dominus to army, select him as Warlord
3. Select Warlord Trait without adding stratagem `Warlord Trait`
4. See no validation errors

**Expected behavior**
`Warlord Trait` stratagem should be required to select a Warlord Trait for character

**Screenshots**

**Device and data (please complete the following information):**
 - OS: Linux
 - BattleScribe version: 2.03.21
 - Release version 9.7.0

**Additional context**

**Comment by Valorcalls** [comment]
Did you also set your game type to CA Arks of Omen?

**Comment by CrusherJoe** [comment]
This happens with Sisters and Iron Hands as well. Yes, gametype is set to AoO.

**Comment by MateuszWicherski** [comment]
@Valorcalls yes
