### ISSUE TITLE
Orks: missing point adjustment for Flash Gitz Kaptin and Squiggoth

### ISSUE THREAD

**Issue by WeissRaben90** [BSData/wh40k-9e#12137]
**File:** Orks.cat

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Description:**
While the Munitorum Field Manual ~~clearly~~ appears to include the Kaptin within the models costing 20ppm in a Flash Gitz unit (as it does not differentiate between "4-9 Flash Gitz" and "1 Kaptin", but simply talks about "5-10 models"), the Kaptin is still priced at 25 points himself.

Also, in the most recent version of the MFM, the Squiggoth from FW went down 20 points, to 150 base. This is not reflected yet in the updated files.

**Comment by Mad-Spy** [comment]
Looks like all the FW Orks got missed.
