### ISSUE TITLE
Grey Knight - Librarian Upgrades 

### ISSUE THREAD

**Issue by Laeorin** [BSData/wh40k-9e#12157]
**Describe the bug**
Hey all! Great work, but just noting that the costing for Librarian guns (Bolter and the Combi-varients) is still in effect. According to the Munitorium, it's no longer at a cost to bring these guns.

**To Reproduce**
Load Librarian in HQ
Select "Storm Bolter Hand", select an option.

**Expected behavior**
The cost should be "No Cost"

**Screenshots**
N/A.

**Device and data (please complete the following information):**
 - OS: Android
 - BattleScribe version: 2.03.25
 - Release version: v9.7.0

**Additional context**
Thanks again for your hard work!

**Comment by Laeorin** [comment]
Oops, as title, I think this is specific to the Grey Knight Librarian

**Comment by AbonShell** [comment]
Fixed in next release
