### ISSUE TITLE
Boarding Patrol detachments have several issues.

### ISSUE THREAD

**Issue by coreyjdixon** [BSData/wh40k-9e#12153]
Starting CP should be 1.

Game size should always be Patrol @ 500pts

Each Boarding Patrol should **only** be able to take.
1HQ
3 Troops
3 Elites
+ Faction specific additions

**No faction should be able to have:**
FLY, 
MONSTER, 
VEHICLE
JUMP PACK
CAVALRY
BIKER
_~ unless specified in the faction specific rules (eg CW can take Dark Reapers HS unit)._

No faction should be able to take Relics or Warlord Traits.

Enhancements are missing for Warlords.

Link to faction specific additions and restrictions : https://www.warhammer-community.com/wp-content/uploads/2023/01/qPJwZxeX8lH4HarK.pdf

![image](https://user-images.githubusercontent.com/80826918/212502346-17c3bb36-99ea-4ae5-9e9e-5da9945a7ba4.png)

**Comment by Mad-Spy** [comment]
Some Factions haven't had it fully implemented.
