### ISSUE TITLE
Chaos Space Marines: Brass Scorpion cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12159]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Greater Brass Scorpion is listed as 475; it should be 430. Thanks for all you do!

**Comment by WindstormSCR** [comment]
Fixed in v210 (9.7.1 release)
