### ISSUE TITLE
Bug Report - T'au, Broadside weapons upgrade wrong cost.

### ISSUE THREAD

**Issue by Hulemann** [BSData/wh40k-9e#12167]
**Describe the bug**
T'au XV88 Broadside has the wrong cost for high yield missile pod. It's supposed to be +10 points, not the +20 points after the BS update.

**Additional context**
The upgrade is stated as +10 points, and you get two high yield missile pods for those 10 points.
Perhaps the author misunderstood this as +10 points pr weapon it gets.

The cost is +10 not +20.

**Comment by Valorcalls** [comment]
You buy two, nothing in the mfm says the points cost is for both of them.

**Comment by Hulemann** [comment]
![FF37936A-57CA-4515-9894-1C5203100FEC](https://user-images.githubusercontent.com/117545287/212504739-f87de683-658f-4048-8a50-a1af18b9ec1a.jpeg)

don’t have the book on my, but from wahapedia it states that you get two from the upgrade of +10 points.

**Comment by Valorcalls** [comment]
and the mfm says you get 1 for 10 points, of which you have to buy 2.
