### ISSUE TITLE
Tyranids: Tyrant Guard Crushing claws cost not updated

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12163]
**File:** Tyranids.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Tyrant Guard with Crushing Claw wargear should be 55points a mode in lieu of 65points.

**Comment by AbonShell** [comment]
You pay for each listed wargear. Crushing claws is listed at 10 points, you pay for two, hence 20 points for the Crushing Claw Pair.
