### ISSUE TITLE
Heroic Support stratagem missing from Death Guard detachment and arks of omen gametype.

### ISSUE THREAD

**Issue by Alaskaalien** [BSData/wh40k-9e#12161]
I am on android version 2.03.25, my friend is on PC version 2.03.21.

Both of us cannot see the Heroic Support stratagem underneath the configuration tab, this is in ~~Astra militarum~~, Death guard, ~~Harlequins~~, and ~~Custodes.~~ 

We double checked they are built as arks of omen detachments with game type set to arks of omen. We can choose the arks of omen compulsory type.

**Comment by FarseerVeraenthis** [comment]
Harelquins (and Aeldari and Drukhari) are done :-)

**Comment by AbonShell** [comment]
Custodes done

**Comment by Mad-Spy** [comment]
I fixed this a while back.
