### ISSUE TITLE
Bug Report: Orks warlord trait and relic strategems

### ISSUE THREAD

**Issue by andresqevedo** [BSData/wh40k-9e#12168]
**Describe the bug**
Warlord trait and relic stratagem are not available for selection to the warlord. Unless selected on a very roundabout way and once selected a validation error appears for non-named characters: i.e. `Beastboss cannot have any selections of Character Stratagems (hidden)`

**To Reproduce**
1. Add an non named character hq
2. Add another one
3. Select relic stratagem
4. Select second hq as a warlord
5. Select warlord trait stratagem
7. `Beastboss cannot have any selections of Character Stratagems (hidden)` error will appear

**Expected behavior**
Warlord trait and relic stratagems should be available for non-named characters.

**Screenshots**
![image](https://user-images.githubusercontent.com/47892973/212504653-e139ecf1-8cd2-4e4e-9c2f-19cbed6e12c1.png)

**Device and data (please complete the following information):**
 - OS: Windows and IOS
 - BattleScribe version  2.03.21

**Comment by AbonShell** [comment]
Fixed in next release
