### ISSUE TITLE
Necrons: FW units not updated to new points

### ISSUE THREAD

**Issue by Cryptothral** [BSData/wh40k-9e#12172]
Points changes to Necron units in FW Imperial Armour from Munitotium Manual not reflected.

Also still missing Cult Of The Cryptek army of renown from White Dwarf.

**Comment by AbonShell** [comment]
FW units completed

**Comment by Cryptothral** [comment]
Please read actual reference documents not reddit summaries for rules updates. Canoptek Acanthrites points cost were changed to incorrect value and still don’t match munitorum update released by GW.

Cult Of The Cryptek Army Of Renown still missing strat for additional cryptek arcana and not available to select outside of Arks detachment. Was released in Nov well before arks and guard codex.
