### ISSUE TITLE
Dark Angels Deathwing Ancient - Thunder Hammer Storm Shield Option still costing 20 points

### ISSUE THREAD

**Issue by Corbynx010** [BSData/wh40k-9e#12179]
**Describe the bug**

Dark Angels Deathwing Ancient Thunder Hammer Storm & Shield weapon option still costs 20 points

**To Reproduce**
1. Make a Dark Angels list
2. Add a Deathwing Ancient
3. Select the  Thunder Hammer & Storm Shield weapon option
4. Observe the cost is 20 points

**Expected behavior**
The Thunder Hammer & Storm Shield weapon option should be free

**Device and data (please complete the following information):**
 - OS iOS
 - BattleScribe version 2.03.15
 - Release version v9.7.0

**Comment by AbonShell** [comment]
Deathwing Ancient isn't a thing? If you're referring to the deathwing terminator squad, fixed in next release
