### ISSUE TITLE
Orks: Heroic Support Stratagem issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12170]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Orks do not have access to heroic hero stratagem. 

~~Beast boss on squiggosaur has issues when trying to load warlord trait and relic stratagem.~~ Fixed in latest update

**Comment by AbonShell** [comment]
Should be in 9.7.1
