### ISSUE TITLE
Deathwatch Vanguard Veterans equipment costs off

### ISSUE THREAD

**Issue by WTFChicken** [BSData/wh40k-9e#12181]
**Describe the bug**
The equipment points costs for Vanguard Veterans in a Deathwatch detachment are off for both in a Proteus Kill Team, and for Vanguard Veterans themselves (but in different ways). 

In a [Proteus Kill Team], if you add a [Vanguard Veteran] it currently lists in Melee Weapons free: Lightning Claws, Power Fists, and Thunder Hammers (these should be 3pts, 5pts, and 10pts respectively).

 If you get a [Vanguard Veteran Squad] in a Deathwatch detachment, the Melee Weapons are correct, but it costs 5pts for a [Hand Flamer] in Pistols when it should be free. (This doesn't effect many other chapters, since only Deathwatch and Blood Angels can equip hand flamers)

 - OS: Windows
 - BattleScribe version 2.03.21
 - Release version v9.7.0

**Comment by WTFChicken** [comment]
Just went and checked, The Hand Flamers also cost 5 pts on a Blood Angels [Vanguard Veteran Squad] when they should be free.

**Comment by AbonShell** [comment]
should be fixed in the next release
