### ISSUE TITLE
Adeptas Sororitas Warlord Trait  Strategem Hidden in AoO Detachment 

### ISSUE THREAD

**Issue by TDog117** [BSData/wh40k-9e#12184]
Adeptas Sororitas Warlord Trait  Strategem Hidden in AoO Detachment 

**To Reproduce**
1. Go to Game Type
2. Click on Matched
3. Scroll down to and select 5. Chaper Approved: Arks of Omen
4. Select any Character you have placed into the detachment 
5. Select "Warlord" 
6. Strategem sub-menu appears but only the Relic Strategem and Open the Reliquaries Strategem options are visible 

**Expected behavior**
Strategem sub-menu should appear with an option for Relic Strategem, Open Reliquaries Strategem and Warlord Trait Strategem 

**Screenshots**
Ss#1 Canoness using Chapter Approved: Nephilim option 
Ss#2 Canoness using Chapter Approved: Arks of Omen option

**Device and data:**
 - OS: Android (Kernel)
 - BattleScribe version v2.03.25.338
 - Warhammer 40,000 v9.7.0
 - Imperium - Adepta Sororitas v210

**Additional context**
Canoness in screenshots used as example, did replicate same problem with other characters in list.

![Screenshot_20230115_015429](https://user-images.githubusercontent.com/9887552/212527485-3f231f65-c8af-4bd4-9db4-9c3ed14a499b.jpg)
![Screenshot_20230115_015459](https://user-images.githubusercontent.com/9887552/212527496-64c8224f-6c91-4e96-bfe9-2a9f0c65de86.jpg)

**Comment by jimmywardmichael** [comment]
Still broken when selecting AOO has game type named characters like morvenn vahl and junith eruita the warlord traits doesnt appear. After selecting any game type other than AOO it works.
