### ISSUE TITLE
Overcosted weapons - Skitarii Ranger and Skitarii Vanguard (Adeptus Mechanicus)

### ISSUE THREAD

**Issue by ajnorton1** [BSData/wh40k-9e#12187]
Weapon "Arc Rifle" is 14 points, actual value is 5
Weapon "Plasma Caliver" is 14 points, actual value is 5
Weapon "Transuranic Arquebus" is 19 points, actual value is 10

**Comment by AbonShell** [comment]
You're paying for the body, 9, plus the weapon cost. 
For Arc Rifle, it's cost is 5. So 5+9 gets you 14.
