### ISSUE TITLE
CSM - Greater Brass Scorpion shows old points 

### ISSUE THREAD

**Issue by Tzardukar** [BSData/wh40k-9e#12190]
**Describe the bug**
The point costs for the Greater Brass Scorpion doesn’t show the updated cost of 430 

**To Reproduce**
1. Go to Add a CSM Lords of War detachment 
2. Add a GBS
3. Check the points

**Expected behavior**
It should be 430 as per the new update.
Page 47. https://www.warhammer-community.com/wp-content/uploads/2023/01/5iSs9obkISmPlK4t.pdf

**Screenshots**
See attachments. 

**Device and data (please complete the following information):**
 - OS: iOS
 - BattleScribe version 2.03.45
 - Release version 
![5F29769C-DFE8-4FD9-B57A-125E7AC0C251](https://user-images.githubusercontent.com/122356541/212529877-fac8f9e4-a188-496b-b643-0662986b3cdc.png)
![EBE96C81-F18A-46FE-A463-11D727C49194](https://user-images.githubusercontent.com/122356541/212529879-859ab3eb-7b75-4b22-8d6a-cc002fa25b63.jpeg)
 v9.7.0

**Additional context**
Add any other context about the

**Comment by Mad-Spy** [comment]
Update your data with "Delete existing data" checked.
