### ISSUE TITLE
Space Wolves - Wolf Guards in Skyclaws and Long Fangs units equipment cost

### ISSUE THREAD

**Issue by smajchrz** [BSData/wh40k-9e#12197]
In release version 9.7.0 

- [x] Wolf Guard in Skyclaws unit (Space Wolves) should have all equipmeny for 0p. Currently Thunder Hammer cost 10p instead.
- [x] Wolf Guard in Long Fangs unit (Space Wolves) should have all equipmeny for 0p. Currently Thunder Hammer cost 10p instead
- [x] Wolf Guard Terminator in Long Fangs unit (Space Wolves) should have all equipmeny for 0p. Currently Thunder Hammer cost 10p instead

**Comment by Exfrau** [comment]
Wulfen Stormfrag Auto–Launcher upgrade should be free as well.
