### ISSUE TITLE
CSM - Blood Slaughterer of Khorne wrong points

### ISSUE THREAD

**Issue by Serplant** [BSData/wh40k-9e#12193]
Blood slaughterer of Khorne PTS are wrong. Should be 125 not 140 per latest MFM. 
![Screenshot_2023-01-15-09-00-19-37_14914093de79514ef0a2e5abb22c6172](https://user-images.githubusercontent.com/52930062/212532180-8157d574-4ccb-4d8e-b555-c978c9424ee8.jpg)
![Screenshot_2023-01-15-08-59-08-58_f541918c7893c52dbd1ee5d319333948](https://user-images.githubusercontent.com/52930062/212532183-991eb2c6-d699-4373-ad67-028cf9bf4dbf.jpg)

**Comment by Mad-Spy** [comment]
Update your data with "Delete existing data" checked.
