### ISSUE TITLE
Genestealer Cults Boarding patrol characters

### ISSUE THREAD

**Issue by Harfish** [BSData/wh40k-9e#12194]
Genestealer Cults have a special rule which allows them to take up to three characters.

> You can include up to 3 Character models, but only one of these can have a Wounds characteristic of 5 or more. 

In the Codex, only two Character models have more than 5 wounds, the Patriarch and the Abominant. So GSC can take any three characters but not both of the Patriarch and the Abominant.

Also, the Jackal Alphus character should not be allowed at all due to having the BIKER keyword

**Comment by bbaker13** [comment]
One small correction: the Primus is also 5 wounds. So, those three characters are the ones you can’t take together.

**Comment by Mad-Spy** [comment]
Too much work to fix on old version
