### ISSUE TITLE
BA Term weapons collective

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#122]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** No

**Description:** Blood angels terminator squad. Selecting chainfist for any marine equips all marines in the squad with both chainfists and power fists

**Comment by raptor1770** [comment]
Confirmed that this is an issue. Working to correct it now.
