### ISSUE TITLE
Chief Librarian Mephiston points cost is incorrect

### ISSUE THREAD

**Issue by SimonasBanys** [BSData/wh40k-9e#12202]
**Describe the bug**
Chief Librarian Mephiston legends cost was updated, not the primaris one.

**Expected behavior**
Chief Librarian Mephiston points cost is 125pts
**Screenshots**
![image](https://user-images.githubusercontent.com/31985858/212538904-4df23e12-ab98-45d6-aed0-e7811cb11ed5.png)

**Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version 2.03.21
 - Release version 9.7.0

**Comment by AbonShell** [comment]
Fixed in next release
