### ISSUE TITLE
Imperium - Astra Militarum: Switch Kasrkin to have a "trooper with vox-caster" option, instead of the unit level option

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12200]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Kasrkin squads should have a "Kasrkin with vox caster" checkbox, rather then the current "give it to the entire unit checkbox"

**Comment by Mad-Spy** [comment]
Given that the model with the vox-caster is prevented from swapping its weapon, this does make sense.
