### ISSUE TITLE
No Warlord traits for Warbosses (Orks)

### ISSUE THREAD

**Issue by omnomnom1134** [BSData/wh40k-9e#12218]
**Describe the bug**
In the new Arks of Omen detachments, when selecting a Warboss in Mega Armour, a Beastboss on Squigasaur, or Warboss as the army's warlord, no prompt appears to give the unit a warlord trait. This includes a lack of prompt for using a stratagem to do so.

**To Reproduce**
1. Create an Arks of Omen detachment for the Orks faction
2. Add an HQ unit that has the "Warboss" keyword to your detachment list.
3. Select the unit as your warlord.

**Expected behavior**
There is no prompt to select a warlord trait or to use a stratagem to give the character a warlord trait/relic.

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version 2.03.21
 - Warhammer 40k version 9.7.0

**Comment by AbonShell** [comment]
Fixed in next release
