### ISSUE TITLE
CSM Blood Slaughterer and Kytan Ravager points issue, old abilities in FW datasheets, minor weapon updates.

### ISSUE THREAD

**Issue by billthechicken** [BSData/wh40k-9e#12214]
The Blood Slaughter and Kytan Ravager both dropped points in the last points update.
Blood Slaughterer went down to 125.
Kytan Ravager went down to 400.
The Forgeworld datasheets still show the daemonic and infernal regeneration abilities even though these has been removed and replaced by the daemon engine rule.
Greater Blight Drone still has disgustingly resilient instead of sickly resistance.
Hell Talon still has autocannon instead of havoc autocannon.
Chaos Fellblade still has demolisher cannon instead of demolisher siege cannon.
All these changes are from the IA Compendium FAQ.

**Comment by Mad-Spy** [comment]
Do an update with "delete existing data" checked.
