### ISSUE TITLE
Orks: Incorrect points costs

### ISSUE THREAD

**Issue by JJDeeds** [BSData/wh40k-9e#12217]
**Describe the bug**
Nob for flash gits is still 25 points instead of the the new points cost of 20

Squiggoth is still 170 points not the new points cost of 150.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Device and data (please complete the following information):**
 - OS: [Android]
 - BattleScribe version [2.03.25]
 - Release version [v9.7.0, orks]

**Comment by AbonShell** [comment]
Fixed in next release
