### ISSUE TITLE
Tyranids - Genestealer Cults: Relic strat missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12216]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Arks of Omen;
- Genestealer Cult
. No option to use the Relic 1CP strat (presumably should be in Stratagems section).
~~. Neophyte Hybrids ; Neophyte Leader ; Melee Weapons - all options should be free (0pts). Specifically, the Power Maul and Power Pick have not been updated to 0pts and still show as 5pts.~~

**Comment by AbonShell** [comment]
Duplicate of #12143
