### ISSUE TITLE
Genestealer Cults - Atalan Leader's grenade launcher should be free

### ISSUE THREAD

**Issue by bbaker13** [BSData/wh40k-9e#12224]
**Describe the bug**
Atalan Jackal Leaders still pay 5 points for grenade launchers. They are free for the troops, but the leader is still paying 5 points for them.

**To Reproduce**
1. Go to Genestealer Cults Atalan Jackals.
2. Click on the Leader.
3. See the option for Grenade Launcher is 5 pts.

**Expected behavior**
Grenade launchers should be free for all Atalan Jackals and leader.

**Screenshots**
![image](https://user-images.githubusercontent.com/6002694/212557205-148259d1-bf70-4167-9c71-f9539f63a20a.png)

**Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version 2.03.21
 - Release version 9.7.0

**Comment by AbonShell** [comment]
Fixed in https://github.com/BSData/wh40k/commit/bc7390fc3f34c89df87a03476c4829abe6ceb8c7
