### ISSUE TITLE
Incursion games AoO 

### ISSUE THREAD

**Issue by RareSide** [BSData/wh40k-9e#12228]
**Describe the bug**
Incursion games also start with 6CP in GT:AoO Like Strike force Games. AoO doesn't make a difference there.

**Screenshots**
Adding one of GT:AoO and one of BS

![IMG_20230115_190110](https://user-images.githubusercontent.com/122745266/212558597-259fd7c1-8e62-4af0-9694-c7dbb21517f8.jpg)
![Screenshot_2023-01-15-19-01-45-692_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/122745266/212558637-0a41b1af-10a3-4061-8f4c-f7d3e4acb524.jpg)

**Device and data (please complete the following information):**
Warhammer 40.000 V9.7.0

**Comment by AbonShell** [comment]
Fixed in next release
