### ISSUE TITLE
Ark of Omens Auxiliary Support Detachment Currently Costs -2 CP when It should be Free

### ISSUE THREAD

**Issue by WACoggins1** [BSData/wh40k-9e#12222]
**Describe the bug**
When adding an auxiliary support detachment as a second detachment for an assassin, it currently costs 2 CP when it should be free. 

**To Reproduce**
1. Go to BS
2. Click on 'Edit Forces'
3. Add Auxiliary Support in addition to the Ark of Omens detachment
4. Costs 2 CP instead of being free.

**Expected behavior**
The additional detachment should be free.

**Device and data (please complete the following information):**
 - BattleScribe version [e.g. 2.03.21] PC

**Comment by AbonShell** [comment]
Fixed in next release
