### ISSUE TITLE
Imperium - Astra Militarum: Cadian Command Squad Power Fist points

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12223]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Power fist for veteran in cadian command squad listed as free

Should be 5 points

**Comment by AbonShell** [comment]
Fixed in https://github.com/BSData/wh40k/commit/bc7390fc3f34c89df87a03476c4829abe6ceb8c7
