### ISSUE TITLE
Leagues of Votann: Boarding Patrol HQ issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12237]
**File:** Leagues of Votann.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Under boarding patrols it says too many characters when selecting only a brokyr as the HQ

**Comment by Mad-Spy** [comment]
Error is correct. Both the Brokhyr and his Ironkin Assistant have the CHARACTER keyword, so you can't take that unit as Boarding Patrols are restricted to a single CHARACTER model. 

I suggest you email GW to ask why they forgot about this, despite implying that you can take a Brokhyr.

**Comment by Shortandgrudgy** [comment]
As stated on the mustering rules it only says the unit cannot be upgraded to a forge master. Not that you cannot use him. 
![Screenshot_20230117_150916_Acrobat for Samsung](https://user-images.githubusercontent.com/122846134/212794786-66c22194-7b55-4e38-a12c-66f6a882561f.jpg)

**Comment by Mad-Spy** [comment]
Yes, but as I said the rules for Boarding Patrols state that you may only take one CHARACTER _model_.

There are two CHARACTER models in that unit, hence RAW you cannot include it.

GW will need to errata the rules to allow you to take the unit.

**Comment by Shortandgrudgy** [comment]
I have just emailed Games workshop and will screen shot their response.
