### ISSUE TITLE
Bug Report - Roboute Guilliman

### ISSUE THREAD

**Issue by FbinKo** [BSData/wh40k-9e#12230]
**Describe the bug**
Roboute Guilliman gets his Nobility Made Manifest warlord trait for free in the Arks of Omen Detachment.
If Roboute Guilliman is included in any list it shows an error (Arks of Omen and Nephilim), unless he has his warlord trait added.

**To Reproduce**
Part 1 -----
1. Create an Arks of Omen Detachment for Ultramarines
2. Add Roboute Guilliman
3. Select him to be the Warlord
Part 2 -----
1. Create any Detachment for Ultramarines
2. Add Roboute Guilliman
3. Select him to be the Warlord

**Expected behavior**
As expected, Guilliman is required to be the Warlord, but he should not be forced to take his warlord trait. And you should only be able to selecte his warlord trait if you paid 1CP.

**Comment by acebaur** [comment]
Fixed in the next release
