### ISSUE TITLE
Imperium - Legion of the Damned: missing WLT & Relic Strats. AoO heroic support missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12249]
**File:** Imperium - Legion of the Damned.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** When picking the Warlord after filling the HQ slot. Once the Warlord box has been checked, the stratagems for the Warlord trait and relics don't come up. Also there is no way of adding the Second HQ  option as per the arks of omen stratagem

**Comment by Mad-Spy** [comment]
Legion of the Damned have no HQ choices, so it's not clear what model you're expecting to add WLTs to.

I think you've added this under the wrong catalogue, so raise it again for the correct one and we'll look at it.
