### ISSUE TITLE
Necrons: HQ Slot issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12241]
**File:** Necrons.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** When taking a Noble and a cryptek in an detachment, a second cryptek should be possible to add without taking up an HQ slot. 

At the moment, the second cryptek counts as an HQ resulting in 3 HQ instead of 2.

**Comment by AbonShell** [comment]
Add a Dynastic Advisor in the No Force Org slot
