### ISSUE TITLE
Aeldari/Ynnari/Drukhari

### ISSUE THREAD

**Issue by Roxfall** [BSData/wh40k-9e#12240]
**Describe the bug**
Venom costs 75 points. It should cost 65 points in Arks of Omen.

**To Reproduce**
1. Make an Aeldari list, select Ynnari as the Craftworld.
2. Add a Venom as a dedicated transport.
3. Observe the cost.
4. Notice how the base splinter cannon adds +10 points with no way to deselect it.

**Expected behavior**
A Venom comes equipped with a splinter cannon and a twin splinter rifle. The twin splinter rifle can be upgraded to a second splinter cannon for 10 points. But the first splinter cannon should cost nothing, and the base cost should be 65 in Arks of Omen, without any upgrades.

**Device and data (please complete the following information):**
 - OS: Android
 - BattleScribe version 2.03.25
 - Release version Warhammer 40,000 v 9.7.0

**Comment by AbonShell** [comment]
Misunderstood your question in the discord. You always pay costs, regardless if they're default or not
