### ISSUE TITLE
Orks: Points incorrect for Flash Gitz Kaptin model

### ISSUE THREAD

**Issue by haroldl** [BSData/wh40k-9e#12245]
**Describe the bug**
All of the Flash Gitz models cost were reduced from 25 to 20, including the Kaptin of the unit but the cost is still showing up as 25 points in Battlescribe.

**To Reproduce**
1. Create an Orks Arks of Omen detachment
2. From Heavy Support, add a unit of Flash Gitz
3. Expand the unit and observe that the Kaptin is listed at 25 points of cost instead of 20.

**Expected behavior**
All Flash Gitz, including the Kaptin, should be 20 points each based on the latest PDF.

**Screenshots**

**Device and data (please complete the following information):**
 - OS: Linux
 - BattleScribe version v2.03.21
 - Release version v9.7.0

**Comment by AbonShell** [comment]
Fixed in latest release
