### ISSUE TITLE
Orks: WLT & Relic Strat missing, AoO Heroic Support missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12250]
**File:** Orks.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** When choosimg a Warlord, there is no option to pick the Warlord traitor Stratagem or the relic stratagem. There is also no Stratagem option to add the second HQ for the arks of omen rules

**Comment by AbonShell** [comment]
Fixed in 9.7.1
