### ISSUE TITLE
Tyranids - Genestealer Cults: AoO Relic strat missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12257]
**File:** Tyranids - Genestealer Cults.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Unable to use relic stratagem under AoO rules. Stratagem is present under nephilim, disappears when switching to AoO.

**Comment by AbonShell** [comment]
duplicate of #12216
