### ISSUE TITLE
Imperial Knights: Unable to clear error when not selecting Questor Allegiance Oath for Freeblade in SHA

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12258]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** I get an error for not selecting a Questor Allegiance Oath for a Freeblade Imperial Knight in a super heavy auxiliary detachment. Their is an option to select "none" but the error is still there.

**Comment by AbonShell** [comment]
Fixed in https://github.com/BSData/wh40k/commit/bc7390fc3f34c89df87a03476c4829abe6ceb8c7
