### ISSUE TITLE
Imperium - Astra Militarum: Ataches and bodyguards missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12256]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Maybe I'm missing it but I cannot find a way to add regimental ataches or bodyguards.

**Comment by AbonShell** [comment]
You add them via the selection on any infantry officer.
