### ISSUE TITLE
Imperium - Dark Angels: Missing Ravenwing Keywords

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12252]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Not really a bud, but certain units are missing Ravenwing keyword such as primaris chaplain on bike, talonmaster, Ravenwing apothecary, etc.

**Comment by Skywrath0135** [comment]
Bumping this for visibility.

**Comment by FarseerVeraenthis** [comment]
I think I got them all... let me know if I missed any once the next release is live :-)
