### ISSUE TITLE
Imperium - Space Wolves: WG Pack Leader Storm Shield Points

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12253]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Wolf Guard ~~Battle~~ Pack Leader in the wolf guard squad has the incorrect points value for Storm Shield. Listed as 0, should be 5

**Comment by Mad-Spy** [comment]
That is not correct. Wolf Guard Pack Leaders still have to pay.

![image](https://user-images.githubusercontent.com/29306451/212761533-25887f5b-7a4d-4d95-b8f1-663ea66ceb9d.png)

**Comment by Mad-Spy** [comment]
Already fixed.
