### ISSUE TITLE
Imperium - Adeptus Mechanicus: AoR not available in AoO Detachment

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12261]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When completing an Adeptus Mechanicus army list the Army of Renown is not an option once you select arks of omen as the battlefield type. Army of renown works on other factions so just seems to be an error with ad mech

**Comment by AbonShell** [comment]
Technically, armies of renown aren't valid as of January.

**Comment by Thairne** [comment]
Armies of renown are now only valid in narrative play and older GT versions.
AoO is the new current way to play GT/Matched, therefore they are no longer valid in matched play using Arks of Omen.
