### ISSUE TITLE
Combat Engineers Missing 

### ISSUE THREAD

**Issue by Spacelord44** [BSData/wh40k-9e#12271]
Combat Engineers are missing from the Elite choices for Astra Militarum in the new update.

**Comment by alphalas** [comment]
Yes, but actually no. They're specifically DKoK units, Which the entire Dkok subfaction doesn't ACTUALLY work because they haven't FAQ'd it to work with the new codex. So yes, the unit TECHNICALLY has rules; but it's practically nonfunctional in all but casual house-ruled games.

**Comment by philipri** [comment]
Hi - can we reopen this issue, given the FAQ issued to Imperial Armour on Jan 25th?

**Comment by Spacelord44** [comment]
Yes please, seems like combat Engineers are just an elite choice now.
