### ISSUE TITLE
Imperium - Dark Angels: Techmarine on Bike should be available in Ravenwing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12275]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The Techmarine on bike from Warhammer Legends is not available for a Ravenwing Outrider Detachment. But he should, just like the Libarian on Bike and the Chaplain on Bike

**Comment by FarseerVeraenthis** [comment]
In a strong case of 'be careful what you wish for' - none of the Legends Bike Units have the Ravenwing Keyword, so none are eligible for selection in the Ravenwing Outrider Detachment... Sorry!
