### ISSUE TITLE
SW: Wolf Guard Jump packs cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12270]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** When putting in jump packs on Wolf guard, the points aren't added.

**Comment by Mad-Spy** [comment]
Unable to reproduce in current release.

5 Wolf Guard - Jump Pack cost shown as 15pts

![image](https://user-images.githubusercontent.com/29306451/212850950-f15afd39-16b0-47ec-baff-a90d0e8e08a8.png)

6 Wolf Guard - Jump Pack cost shown as 18pts, 2PL.

![image](https://user-images.githubusercontent.com/29306451/212851045-e2ea15fa-11b2-4e0f-ada7-0929565ca561.png)
