### ISSUE TITLE
Necron - Can't add Overlord to a boarding patrol

### ISSUE THREAD

**Issue by drwasho** [BSData/wh40k-9e#12276]
**Describe the bug**
Attempting to add an Overlord produces the following error:

```
"... has 1 too many selections from Character (maximum 1)"
```

**To Reproduce**
This is the army I'm attempting to construct:

```

+++ Necron Boarding Action (Warhammer 40,000 9th Edition) [22 PL, 400pts, 3CP] +++

++ Boarding Patrol (Necrons) [22 PL, 400pts, 3CP] ++

+ Configuration [3CP] +

Battle Size [3CP]: 1. Combat Patrol (0-50 Total PL / 0-500 Points)  [3CP]

Detachment Command Cost

Dynasty Choice: Dynasty: Szarekhan

Game Type: 5. Chapter Approved: Arks of Omen

+ HQ [6 PL, 90pts] +

Overlord [6 PL, 90pts]: Warlord
. Tachyon Arrow and Hyperphase Glaive

+ Troops [6 PL, 110pts] +

Necron Warriors [6 PL, 110pts]
. 10x Necron Warrior (Gauss Flayer) [110pts]: 10x Gauss Flayer

+ Elites [8 PL, 155pts] +

Hexmark Destroyer [4 PL, 65pts]

Skorpekh Destroyers [4 PL, 90pts]: Skorpekh Destroyer (Reap-Blade) [30pts]
. 2x Skorpekh Destroyer (Thresher) [60pts]: 2x Hyperphase Threshers

+ Fast Attack [2 PL, 45pts] +

Canoptek Scarab Swarms [2 PL, 45pts]
. 3x Canoptek Scarab Swarm [45pts]: 3x Feeder Mandibles

Created with BattleScribe (https://battlescribe.net)

```

**Device and data (please complete the following information):**
 - OS: iOS
 - BattleScribe version [e.g. 2.03.45]
 - Release version v9.7.1

**Comment by Mad-Spy** [comment]
The Hexmark Destroyer is also a CHARACTER and you can only have one CHARACTER in a Boarding Patrol, as per p64 of the rules.

Neither the Overlord nor the Hexmark are CRYPTEKS, so you don't get the increment to allow 2 CHARACTERS.

**Comment by drwasho** [comment]
Thanks mate, sorry missed that.

**Comment by drwasho** [comment]
![image](https://user-images.githubusercontent.com/3887694/213154861-3f5e7797-6cbb-4297-88d7-6fa51d070f74.jpeg)

According to the mustering rules, you can include 2 characters as long as one of them is a Cryptek unit... so if I swap the Overlord with a Plasmancer, BS is returning an error saying I have more than 1 max character. 

Similarly if I remove the Hexmark and have the Overlord + Plasmancer, I have an error for too many HQs and too many characters.

Am I missing something?

**Comment by Mad-Spy** [comment]
Sounds like the validation isn't working properly then. Raise a new issue for that.
