### ISSUE TITLE
Imperium - Adeptus Mechanicus: Artefactotum on Alpha/Princeps has odd behaviour

### ISSUE THREAD

**Issue by KeetGithub** [BSData/wh40k-9e#12287]
**Describe the bug**
When selecting the Alpha of a Skitarii squad or Princeps of a Sicarian squad for example, available options for relics do not initially appear when the Artefactotum strategy is checked for the unit. 

It is necessary to further select a Warlord before the list of Relics will appear.

It might be better to either hide or validate that Artefactotum cannot be used without a Warlord selected to avoid confusion.

**Device and data:**
 - OS: Windows
 - BattleScribe version 2.03.21
 - Release version 9.7.1

**Comment by Thairne** [comment]
Artefactotum says they can get " a relic they could have".
Without a AdMech Warlord, you do not have access to relics, therefore it is working as intended and not bug.
It is suboptimal though.
