### ISSUE TITLE
Space wolf wargear costs incorrect. 

### ISSUE THREAD

**Issue by Foambrick** [BSData/wh40k-9e#12288]
I was making my Arks of Omen space wolves list when I noticed multiple wargear costs are incorrect. 

Wolf guard: displays lightning claw, power fist and thunder hammer as being free, but are 3,5,10 points respectively 

Wolf guard skyclaw pack leader: shows the thunder hammer as 10 points, but all wargear is free for pack leaders. 

These are all the issues I’ve seen, there may be more but this is all I’m aware of. 

Im using 9th edition v.238 and version 2.03.15 on an iPhone 12

**Comment by Mad-Spy** [comment]
Fixed in next release.
