### ISSUE TITLE
Black Templar missing AoO WLT and Relic strat

### ISSUE THREAD

**Issue by Tetsuo91** [BSData/wh40k-9e#12284]
**Describe the bug**
Black Templars are missing the matched play WLT and Relic strats from the new AoO book. It also is showing Helbrecht and Grimaldus WLTs are mandatory.

**To Reproduce**
Create new BT army
Add Grimaldus or Helbrecht

**Expected behavior**

Have New strats and not require WLT

**Screenshots**
https://i.imgur.com/PWCVtWT.png

**Device and data (please complete the following information):**
 - Win11
 - BattleScribe version BattleScribe v2.03.21.166
 - Release version v9.7.0

**Comment by acebaur** [comment]
This is already fixed. Either your data is out of date or you need to create a new list (this fixed it for someone else having this issue)
