### ISSUE TITLE
Allied detachments giving an error

### ISSUE THREAD

**Issue by JANXOL** [BSData/wh40k-9e#12289]
**Describe the bug**
One of the recent edits broke allied detachments for AoO.
Yesterday it was working fine, now its yelling at me i cant have a freeblade super-heavy aux. tested on a file i saved earlier and which was fine, as well as new files.

**To Reproduce**
Create an imperium AoO detachment. 
Add a knights super heavy auxiliary, add a freeblade.
It will show an error you can have maximum of 0 super-heavy auxiliary detachments.

**Comment by Mad-Spy** [comment]
~~When you say "Imperium" which Faction specifically?~~

I see it now. Needed to select AoO game type.

**Comment by JANXOL** [comment]
Bear in mind imperium + freeblade is not the only combo affected. Also seeing it with csm + dreadblade, gsc + BB super-heavy aux. 
Wierdly enough it seems the super-heavy auxiliary battle brothers detachment is affected, but patrol battle brothers detachments are not giving an error.
