### ISSUE TITLE
Chaos Knights: Corrupted Heirlooms Req Strat giving a WLT choice when it shouldn't

### ISSUE THREAD

**Issue by sterling000** [BSData/wh40k-9e#12286]
**Describe the bug**
It appears that selecting Corrupted Heirlooms on a Knight Abominant opens up Warlord Traits selection for the unit. This strategem should function just like the usual Relic Strategem and grant access to a relic. The only difference is, that in CK usually you have to make them a character before you can make them a WL or give them relics or WLTs, but Corrupted Heirlooms says specifically "That model can have one [Relic of Tyranny], even if they are not a CHARACTER model" but it does NOT make them an actual character.

So there may be something happening in the data where it's thinking that this strategem has made them a character but they actually have not been. It could be confused with the Tyrannical Court strategem that DOES allow the unit to select a WLT and make them a character.

**To Reproduce**
1. Create an Arks Of Omen Detachment
2. Add a Knight Rampager and make it your warlord
3. Add a Knight Abominant and select Corrupted Heirlooms option
4. Scroll down and see Knight Abominant can select Warlord Traits when it shouldn't be able to without other selections

**Expected behavior**
Only your Warlord and a unit with the "Tyrannical Court" strategem should be able to select Warlord Traits.

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version 2.03.21
 - Release version 9.7.1

**Additional context**
Probably not specific to adding a Rampager or Abominant and order probably doesn't matter, just have to have one that is a warlord for Corrupted Heirlooms to even show up first since it's dependent in the rules.

**Comment by Mad-Spy** [comment]
Fixed in next release
