### ISSUE TITLE
 Necrons: Cult of the Cryptek should allow Named CRYPTEKS

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12293]
**File:** Necrons.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** The Cult of Cryptek army list should be allowed any model that’s a cryptek. So that includes Illuminor Szeras or Orikan the Diviner. We’ve had this confirmed by a member of the GW faq team.

**Comment by Valorcalls** [comment]
Neither of those characters are eligible to be in that army of renown since they both lack the ability to be from the same dynasty, as required by the army.

**Comment by Niels-H** [comment]
Please reopen this Issue

Quote @Valorcalls 
> Neither of those characters are eligible to be in that army of renown since they both lack the ability to be from the same dynasty, as required by the army.

@Valorcalls : Dynastic Agents are excluded from this rule. The fact, that named characters didn't have the <Dynasty> Keyword does not count. There are other appearences of the "Same Dynasty" rule which do include named characters. See rules for detachments or choice of Dynastic Code.

Quote @BSDataAnon 
> **Description:** The Cult of Cryptek army list should be allowed any model that’s a cryptek. So that includes Illuminor Szeras or Orikan the Diviner. We’ve had this confirmed by a member of the GW faq team.

@Valorcalls : @BSDataAnon also mentioned, that a GW FAQ-Team-member confirmed that named characters are allowed.

**Comment by alphalas** [comment]
We don't take "trust me, bro I talked to a GW guy he totally says I'm right" as a source. Rules as written, the way the data is right now is correct. Until it is officially FAQ'd, it will not change. This always has been, and always will be the rule that battlescribe uses.
