### ISSUE TITLE
Missing: Astra Militarum - Armageddon Basilisk/Medusa

### ISSUE THREAD

**Issue by ARC-Mavout** [BSData/wh40k-9e#12299]
Is there a Reason why Astra militarum can't take Armageddon Pattern Basilisks and Medusas?
They're listed in the recent Pointbalance 

![Armageddon Pattern](https://user-images.githubusercontent.com/123033622/213318094-2e16db5f-e217-4a38-a728-fb202693841f.png)

**Comment by alphalas** [comment]
Due to the fact they don't actually work with the new codex. All FW units need to be FAQ'd to be usable right now legally.

**Comment by Trowis** [comment]
It looks like the Armageddon Basilisk/Medusa and the Malcador have been given new datasheets and FAQ in the book. Not sure if updates for 9e will happen so close to 10e.
