### ISSUE TITLE
Imperium - Adepta Sororitas: Morvenn Vahl Warlord validation has not been updated for AoO

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12295]
**File:** Imperium - Adepta Sororitas.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** I had Morvenn Vahl selected in my army with the Warlord Trait Righteous Fury. However, after it got updated to the version 9.7.1, it says I cannot have it selected. Then when I uncheck the box, it says I must have, and can't select it again.

**Comment by Mad-Spy** [comment]
Morvenn does not have access to the Character Stratagems SSEG in the AoO game type and is also being validated on a choice of WLT she is unable to select.

![image](https://user-images.githubusercontent.com/29306451/213286308-50262cf9-275e-4831-9b42-cfe43b42d984.png)

**Comment by KalChoedan** [comment]
Nor do the other Sisters named characters:
![image](https://user-images.githubusercontent.com/1786901/213404338-58d2a7ba-2d10-49f9-90f2-caf28e0f55f5.png)
![image](https://user-images.githubusercontent.com/1786901/213404409-742ec615-5ae6-4187-8229-98f7468bc167.png)
