### ISSUE TITLE
Imperium - Adeptus Custodes: Allarus Custodians should have ObSec

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12309]
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Allarus Custodians are still not showing obsec rule.

**Comment by Thairne** [comment]
https://github.com/BSData/wh40k/issues/12247
