### ISSUE TITLE
Imperium - Adeptus Mechanicus: Army of Renown Choice missing in Arks of Omen Detachment if choosing Gametype: Chapter Approved Arks of Omen

### ISSUE THREAD

**Issue by Marlemops** [BSData/wh40k-9e#12308]
Hi, 

if you open an Adeptus Mechanicus Arks of Omen Detachment the option to choose the Armys of Renown dissapears if you select 

the Game Type Chapter Approved Arks of Omen. 

If you select the Army of Renown before choosing the Game Type, it complains that the Army of Renown is not allowed, but still calculates the points for it on the corresponding models. 

Windows 10 

BattleScribe v2.03.21.166

Release version 9.7.1

**Comment by Thairne** [comment]
https://github.com/BSData/wh40k/issues/12261
