### ISSUE TITLE
 Necron - Elite CHARACTER and C'tan errors

### ISSUE THREAD

**Issue by ikerortiluzu** [BSData/wh40k-9e#12306]
When creating a roster with the new detatchment added in the Arks of Omen chapter, I found that there is an error when adding the second C'tan since they shoud fill the slots reserved for the elite character role. Instead they spend a regular Elite slot. This leads to an error when creating a roster, for example, with 2 elite units and 2 C'tan units (with heroic support stratagem) and in which we take as compulsory role any that is not elite.

To reproduce the error is as simple as when creating a roster with the Arks of omen detatchment, add 2 non-character elite units and 2 C'tan units, and put as compulsory slot any that is not elite.

I attached 3 screenshots to show the error.
![WhatsApp Image 2023-01-19 at 15 29 32](https://user-images.githubusercontent.com/123089999/213468740-2c095ac9-dbce-45ed-ad0f-90eee2458e6b.jpeg)
![WhatsApp Image 2023-01-19 at 15 29 33](https://user-images.githubusercontent.com/123089999/213468800-0764fa95-92b5-46b2-ab1c-bcdd083d011a.jpeg)
![WhatsApp Image 2023-01-19 at 15 29 32 (1)](https://user-images.githubusercontent.com/123089999/213468822-87e89ff3-8edd-4c13-8732-9227d74c0c7b.jpeg)

The second error I want to report is that when selecting the C'tan powers the app is not giving an error when we repeat a Ctan power for different units. C'tan powers can not be repeated.

**Comment by Mad-Spy** [comment]
Transcendant C'tan issue is already reported in #12291 

Please log the other issue as a separate ticket.
