### ISSUE TITLE
Necrons - Validation issue with HQs and characters in Boarding Patrol

### ISSUE THREAD

**Issue by drwasho** [BSData/wh40k-9e#12301]
![image](https://user-images.githubusercontent.com/3887694/213154861-3f5e7797-6cbb-4297-88d7-6fa51d070f74.jpeg)

**Background/context**
- According to the mustering rules above, you can include 2 characters as long as one of them is a Cryptek unit. 

**Bug**
- If I have an Overlord + Plasmancer, BS is returning an error saying I have `...1 too many selections from HQ (maximum 1)`
- If I have Hexmark + a Plasmancer, BS is returning an error saying I  have `...1 too many selections from Character (maximum 1)`

**Comment by Mad-Spy** [comment]
@DrTobogganMD, I missed this in the doc so I never gave Necrons the option to take 2 CHARACTERS/HQ in the GST Force Entry.
I've sorted that now, so you should be good to just limit any HQ/CHARACTER that's not a CRYPTEK to max 1 in Force, and CRYPTEK to max 2.

**Comment by fallingbear** [comment]
![image](https://user-images.githubusercontent.com/611341/214750076-487cafa7-bbc4-4c79-a292-27781ad5bbc9.png)


After downloading the update, I'm getting an error "has too many selections of Skorpekh Lord" when there is a Skorpekh Lord and Plasmancer as HQs. Based on the mustering orders, shouldn't that be valid?

**Comment by DrTobogganMD** [comment]
Hmm I may have missed the logic on sorkepkh lord - I'll look.

**Comment by drwasho** [comment]
Also getting this error from the latest update:

![image](https://user-images.githubusercontent.com/3887694/215295645-67bc02a3-23d2-49e0-a0d5-c31f40357f4f.jpeg)

![image](https://user-images.githubusercontent.com/3887694/215295640-65c33589-9934-4a73-a897-fb842ebf425c.jpeg)

**Comment by drwasho** [comment]
Also getting an error when combining Imotekh and an Plasmancer: 

![image](https://user-images.githubusercontent.com/3887694/218287605-6c57ade6-70a0-4c64-9182-55caadb153ee.png)

**Comment by fallingbear** [comment]
![image](https://user-images.githubusercontent.com/611341/222012621-cb779d23-c55f-47a1-88a5-b1d00a0289c0.png)
The error is still present after the newest update.
