### ISSUE TITLE
Necron named characters WLT issues

### ISSUE THREAD

**Issue by JANXOL** [BSData/wh40k-9e#12310]
**Describe the bug**
Named characters for the necron have two issues with WLT - one is that when made warlod, it demands to have a warlord trait giving an error if you choose not to give it. The other is that you can give the character a WLT without using the WLT stratagem, which shouldn't be possible. Similar issues are present with named characters accross multiple factions, though didnt quite narrow down which ones exactly.

**To Reproduce**
Create AoO necron detachment, Sautekh dynasty
Pick Imotekh and make him warlord

**Comment by Mad-Spy** [comment]
Fixed in next version,
