### ISSUE TITLE
Orks: Power Klaw costs are inconsistent on Nob in Boyz unit

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12313]
**File:** Orks.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** When equipping the Nob on a boys unit a power klaw costs 20 points if on Arm 1 but 5 points if on arm 2

**Comment by 40korkboy** [comment]
I also believe the Big Choppa to be mis-cost, it should be 5pts for the Nob to take the Big Choppa.
