### ISSUE TITLE
QoL: AoO compulsory slots

### ISSUE THREAD

**Issue by JANXOL** [BSData/wh40k-9e#12326]
If mechanically possible, it would be good if after adding an AoO detachment, it would start with the item "Arks of Omen compulsory type" in configuration already added. It's an item you need to add every single time to every single AoO for every single faction. While a minor thing, it would save some clicks, especially on mobile when you need to go through submenus to add it and then set the desired compulsory type.

**Comment by Mad-Spy** [comment]
It's not possible to do this due to limitations in Battlescribe. Sorry.
