### ISSUE TITLE
Space Marines: Kayvaan Shrike breaks CAPTAIN logic because he is a CHAPTER MASTER, but not a CAPTAIN

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12323]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** As we know, Heroic support stratagem exist for doubling captain or hive tyrant.
And this means there should be a warning sign when users muster thier army
with 2 captains without stratagem option or setting one of them as a CM.

The problem is, it seems broken with named chapter master character.
Shrike in my case.

Example:
2 captains and shrike without stratagem option
should generate warning but it isn't.

I guess this happens for a bug in checking algorythm such as
1.Checking CM flag in army→true→2captains is legal
2.Shrike is not a captain(for some reason?)→shrike and 2captains legal

**Comment by Mad-Spy** [comment]
Shrike doesn't have the CAPTAIN keyword on his datasheet, but the logic which increments the number of allowed CAPTAIN models doesn't take this into account so it is possible to take 2 Captains, plus Shrike, which should not be permitted without using Heroic Support.

**Comment by JANXOL** [comment]
Are you sure it shouldn't? Chapter masters are excluded From Company Command
You can take a chapter master and a captain without using heroic support. So heroic support would then allow you to take a second captain as well, unless i misunderstand.

**Comment by Mad-Spy** [comment]
You're right, but that's what I said. Your error report correctly states the problem which is that you can do it without Heroic Support which should not be possible.
