### ISSUE TITLE
NECRONS points still incorrect and AoR still missing

### ISSUE THREAD

**Issue by Cryptothral** [BSData/wh40k-9e#12325]
Please read actual reference documents not reddit summaries for rules updates. Canoptek Acanthrites points cost were changed to incorrect value and still don’t match munitorum update released by GW.

https://www.warhammer-community.com/wp-content/uploads/2023/01/AyrCVZHP6abRKmR0.pdf

Cult Of The Cryptek Army Of Renown still missing features. Including strat for additional cryptek arcana, and not being available for regular detachments outside of Arks detachment. 

Was released in Nov well before arks and guard codex.

Come on guys been three updates now and still not done thoroughly enough to be correct.

**Comment by Mad-Spy** [comment]
This sort of bug report will get you banned for further offences. This is a warning.

The work here is done for free in people's spare time. No one here is obliged to do this and denigrating the work that is done is not constructive.

Just report the bug; additional commentary on your dissatisfaction is not required.

**Comment by Cryptothral** [comment]
Sorry, I’ve posted three times for these small updates and they’ve been repeatedly marked COMPLETED when they’re still incorrect. Not sure how else I’m supposed to report the issue that whoever is doing it isn’t reading the red highlighted numbers correctly. Or that they are assuming competitive players using AoO are the only folks interested/important enough to use an AoR released two months ago in WD.

I know people make mistakes. But if I can get banned for stating an obviously incorrect factual error which I do know for a fact originated when Chef from Tabletop Tactics (whom I like and support) posted the typo to a reddit conversation I’m not the one overreacting emotionally.

**Comment by DrTobogganMD** [comment]
My friend, that is not the reason the ban was brought up. I am the necrons cat maintainer. I will take your issue into consideration and review points.

The reason the ban was brought up was the attitude disparaging a team bringing you something for free on an application whose programmer has ghosted everyone. It's just bad form. Further, quoting TT of all people ... My man, they get rules wrong CONSTANTLY on Batreps. I love them, they're fun to watch but you can definitely choose a better "source".

**Comment by Cryptothral** [comment]
This is hilarious. You both keep doubling down on the error and trying to burn me but revealing that clearly neither of you are reading my posts/responses. My source from the beginning is the GW article as I stated.

I also clearly stated the incorrect points values that were put into BS by the last update are who’s ultimately referencing Tabletop Tactics’s typo, or the reddit post from them summarizing points changes which also had the typo.

Literally you’re last message trying to scold me refers to yourself because the points values that you put in the last update are ultimately derived from TT. If you reread my message from last night you will see that I already was pointing out that TT was the origination of the mistake and my correct source was the gw pdf.

Do you understand what I’ve been pointing out yet? I have been referencing the official document from gw the whole time and every time I post in the correct manner you folks dictate - every response I get is someone insecurely taking it personally and trying to insult me, but instead further revealing that they are not actually reading my posts / the updates from the beginning.

I rest my case.

**Comment by WindstormSCR** [comment]
> points values that you put in the last update are ultimately derived from TT.

uh, no, no they aren't, and you're acting like a spoiled child. We're not taking it personally, we just think you're a bit of a cunt.

**Comment by Cryptothral** [comment]
Lol, you’re the person who wrote the wrong number into the update. If you were referencing the correct source, as you try to claim, instead of war comp reddit then the number would be 35 not 36 from the beginning.

You’re both idiots trying to insult me over your own obvious mistakes.

I would never have taken this tone or been laughing at you if you two hadn’t started acting like reactionary incels.

You two are the perfect example of the people who drive new players away and get the whole hobby made fun of.

**Comment by KalChoedan** [comment]
You "took this tone" in literally your first post, before anyone had replied to you. 

> Come on guys been three updates now and still not done thoroughly enough to be correct.

That's just entitled and insulting, and it stands in stark contrast to the reaction we get from other members of the community to these sorts of errors when they, for example, visit the Discord server and ask if there's anything they can do to help - unlike your response which has essentially been just to complain repeatedly that the volunteers giving up their free time to provide something you clearly value aren't doing it to a sufficiently high standard for you.

It doesn't matter whether you're right or not, or whether or not your corrections are accurate. It doesn't even matter if you're right about the source of the error. What matters here is this absurdly arrogant, entitled attitude. These are people giving up their free time to do this. They don't get paid for it. They barely get thanks. And if they get something wrong people like you who seem to have decided that they deserve these updates come out of the woodwork to berate them.

Unbelievable.

**Comment by Cryptothral** [comment]
No, that was my third post trying to get something fixed that had been marked "COMPLETE" each time even though it was done incorrectly. And it does matter that I was correct about the origination of the error because that's one of the things I'm supposed to be in trouble and feel bad for - even though all the responses try to claim that wasn't the source of the typo and attempt to insult me about it.

I only created this github account to go through the process you folks specify to correct things but those people clearly don't read past the first sentence or the official points while doing it. Not sure what else I'm supposed to do when every response is more concerned about throwing shade for the mistake than just correcting a typo. Everyone of you justifies your own direct insulting of me why hypocritically telling me I'm getting a warning for expressing my frustration that three times it has been erroneously marked complete.

Enjoy your cognitive dissonance.

------- Original Message -------

**Comment by DrTobogganMD** [comment]
We do not go off of "Reddit posts from TT". You need a period of time to cool down. Take care friend, your issue will be investigated and addressed.

**Comment by amis92** [comment]
If you're claiming previous reports, linking to them would increase your credibility. If it has been a couple of times already, your frustration is understandable.

Getting our attention is definitely one of your achievements here. Taking a bit less offensive tone would help, though. Right now we're either letting you have a win here by fixing (if there's indeed an issue), or doing nothing just in spite of you, but the latter would also hurt others, which is in direct opposition to our mission.

So we want to make sure that anyone else who stumbles in here won't take your stance, and thus you should expect a ban for offending us, as has been quoted already.
