### ISSUE TITLE
Imperium - Dark Angels: Servitors mis-behaving

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12324]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** When running a techmarine alongside more than one unit of servitors, this flags as an error, even if the servitors are included filling an Elites slot in the force org. There should only be a restriction on the number of Servitors included under no force org, not under elites.

**Comment by Mad-Spy** [comment]
~~Unable to replicate issue in currently released data. If you're seeing a problem, please provide full details of your list.~~

Assumed this was generic to all Marines, but it looks like it's DA-specific.

**Comment by FarseerVeraenthis** [comment]
I just checked this on mobile, I'll update my data, I experienced the same issue as the OP
