### ISSUE TITLE
Add Rowboat Guilliman to other chapters

### ISSUE THREAD

**Issue by JANXOL** [BSData/wh40k-9e#12328]
According to AoO errata, 

> You can include an Adeptus Astartes Primarch unit in
> a Chapter Detachment even if it does not share the
> Chapter keyword of other units in that Detachment.
> Doing so does not prevent any other units from gaining their
> Detachment Rules. Note that the Adeptus Astartes Primarch
> unit will only gain a Chapter Tactic if every Chapter unit
> shares the same Chapter keyword.

There were other changes to supreme command as well and while I'm sure you guys have seen it, I'l reference it [here](https://www.warhammer-community.com/wp-content/uploads/2023/01/0VLDQWlhsHWcnXWx.pdf)

**Comment by Mad-Spy** [comment]
Fixed in next release. If there hasn't been a release since an update came out, you don't need to raise issues to get the changes done.

**Comment by JANXOL** [comment]
Oh apologies. I am using the data from master, not the release and I do not have an option to take Rowboat into a different chapter. (Updated 2 hours ago, which mean I should have latest master at this point.

**Comment by Mad-Spy** [comment]
It will be fixed, before the next release.
