### ISSUE TITLE
Imperium - Blood Angels: Hammer of Baal is missing its profile?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12337]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Hammer of Baal not showing up in roster view, only the standard thunder hammer but it is selectable on roster builder.

**Comment by AbonShell** [comment]
Unable to replicate, If possible, please post what unit it is missing on.
