### ISSUE TITLE
Adeptus Custodes <Core> + <Infantry> Objective secured missing from units

### ISSUE THREAD

**Issue by Komrad33** [BSData/wh40k-9e#12332]
**Describe the bug**
With the latest balance dataslate All Core+Infantry Adeptus Custodes and SoS units get Obsec according to the wording of the update.

This includes Custode Wardens (elite), Both flavor of terminators (both elite), as well as Ventari Custodes (the wingy fly bois) (fast attack). 

This also applies to SoS Vigilators (elite) and witchseekers (Fast Attack)

I may be wrong but they meet the new definition listed out in the[ 2023 Balance dataslate](https://www.warhammer-community.com/wp-content/uploads/2023/01/3L0GNWfXu9HzCaH0.pdf). If I am incorrect please let me know why! always trying to learn. 

**To Reproduce**
1. Select any of the non Troops Core+Infantry and none of them have Objective Secured: Example Custode wardens elite choice that possesses both the Core and Infantry key words

**Expected behavior**
Core + Infantry units outside of the troops Keyword having Objective Secured 

**Screenshots**
![image](https://user-images.githubusercontent.com/123283918/213900369-5eaedb13-a34c-4b63-89d5-7d1b960fc1a9.png)
![image](https://user-images.githubusercontent.com/123283918/213900476-5e981da9-0f17-403a-922e-8c57859470d8.png)

**Device and data (please complete the following information):**
 - OS: Windows and IOS
 - BattleScribe version: Windows: 2.03.21, IOS 2.03.15
 - Release version: 9.7.1 (im assuming this is the datafile version?)

**Additional context**
Thank you all so much for doing the data files. I love how well they work and wish I could help more. Been an avid user for years!

**Comment by Thairne** [comment]
https://github.com/BSData/wh40k/issues/12247
