### ISSUE TITLE
Spacewolves points/rules issues

### ISSUE THREAD

**Issue by Mackha1** [BSData/wh40k-9e#12346]
Wolf guard terminators thunder hammers should be 0 points as per new field manual, thunderwolf cavalry should also have CORE keyword.

**Comment by Mad-Spy** [comment]
1. Fixed in next release, as per the multiple issues already logged that you could have searched for.
2. They already do.
![image](https://user-images.githubusercontent.com/29306451/214146325-69fbfc6c-70b6-4e7d-8708-24ab99794509.png)
