### ISSUE TITLE
Imperium - Adeptus Custodes: Various Crusade issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12364]
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Crusade specific bugs.
All non-Character units are missing battlescars.
Vexilus Praetor and Vexilus Praetor in Allarus Terminator Armor both have double battle honours.
Artefacts of the Vaults should be Custodes only, Sisters of Silence units shouldn't be able to select them.
Atonement in Battle Battlescar should be Shield Captain / Shield Captain in Allarus / Shield Captain on Dawneagle only.
Study the Martial Ka'tah's Battlescar should be Infantry only.

**Comment by Mad-Spy** [comment]
Too much work to fix on old version
