### ISSUE TITLE
Necrons: Can't take more than one Plasmacyte despite taking multiple DESTROYER CULT units

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12379]
**File:** Necrons.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Can't add more then 1 Canoptek Plasmacyte. Rule called "Viral Construct" - for each DESTROYER CULT unit in a detachment, one Canoptek Plasmacyte can be included in that detachment without taking up a Battlefield Role slot. When i take two units of Skorpekh Destroyers, i cant unclude more then 1 plasmacyte.

**Comment by Mad-Spy** [comment]
I believe these two modifiers are conflicting. The Set is taking precedence over the increment and preventing more than one Plasmacyte from being taken.

![image](https://user-images.githubusercontent.com/29306451/215076868-88b3e000-8b11-4d13-93f2-2d45e889636b.png)

![image](https://user-images.githubusercontent.com/29306451/215076933-84c028ab-9ff1-4dcc-b612-2976ae73d445.png)
