### ISSUE TITLE
Imperium - Dark Angels: Land Speeder Vengeance assault cannon should be free

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12375]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** ~~Azrael's character trait is not costing any CP~~ Reported as #12368 

Also I believe the Land Speeder Vengeances assault cannon upgrade is free now.

**Comment by FarseerVeraenthis** [comment]
ref #12362
