### ISSUE TITLE
Astra Militarum - Kasrkin's "Warrior Elites" and "Veteran Commandeer" Tank Ace shouldn't have Born Soldiers

### ISSUE THREAD

**Issue by Enzarel** [BSData/wh40k-9e#12389]
Both abilities let you, direct quote from the codex, "[...] select one doctrine from pages 60-61 that no other unit from your army has. This [unit/model] has that doctrine in addition to any others it has.", with Veteran Comandeer further specifying "[...] from the Regimental Doctrines section (pg 60-61) [...]"; this is specifically the section that contains the Guard's equivalent of successor tactics, and does not contain Born Soldiers (which is located in its own separate section a page before).

However, in Battlescribe, both abilities let you choose from amongst _all_ of the available doctrines, including Born Soldiers. BS should be removed from the list in both instances.

**Comment by AbonShell** [comment]
It has validation where it will error when selected, and is hidden when deselected.
