### ISSUE TITLE
Imperium - Space Wolves - wolf guard terminator - thunder hammer cost 

### ISSUE THREAD

**Issue by anonsw** [BSData/wh40k-9e#12384]
In the wolf guard terminator datasheet cost for thunder hammer for the pack leader is 0, for the rest of the model in the unit shown as 10 per model. Should be 0 for all the model in the unit as for mfm

**Comment by Mad-Spy** [comment]
Update your data

**Comment by Mad-Spy** [comment]
Update your data. It was fixed in the last release.
