### ISSUE TITLE
Renegades & Heretics: Valkyrie missing from flier options.

### ISSUE THREAD

**Issue by Randicore** [BSData/wh40k-9e#12385]
Options to add fliers to the renegades & heretics force missing.

**To Reproduce**
Create a roster using the 9.7.2 dataset
Select "add force" and choose Chaos - Renegades & Heretics [Legends] from the top drop box.
Choose any detachment capable of selecting a flier for the lower drop box, arks of omen recommended. 
add force and create roster. Scroll down to "fliers" under the heavy support options on the left side of the screen.
Only flier option listed is the Arvus Lighter, you can see that the Valkyrie option is missing.

**Expected behavior**
The ability to select and add the Valkyrie as an option under fliers with the imperial guard 9th edition rules and corresponding data. 

**Screenshots**
attached of both missing valk and relevant rules.

**Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version BattleScribe v2.03.21.166
 - Release version Warhammer 40,000 v9.7.29.7.2 dataset

**Additional context**
![renegades valk rule](https://user-images.githubusercontent.com/51863727/215049517-a4ddf189-5309-47d1-b4fc-361d6571a10c.png)
![Valkyrie missing](https://user-images.githubusercontent.com/51863727/215049523-101765b9-b193-4cd2-8c9b-62ad063dac32.png)

**Comment by Mad-Spy** [comment]
Technically, the datasheets referred to in that document don't exist any longer. However, I'm happy to go with the intent in this case, especially given that this is a Legends faction.
