### ISSUE TITLE
 Astra Militarum Feedback

### ISSUE THREAD

**Issue by quindraco** [BSData/wh40k-9e#124]
**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:**

The following units do not have a force org slot, so they cannot satisfy roster validation:
Kell (should be Elites)
Company Commander (should be HQ)
Heavy Weapons Squad (should be Heavy)
Infantry Squad (should be Troops)
Master of Ordnance (should be Elites)
Platoon Commander (should be Elites)
Special Weapons Squad (should be Elites)

**Comment by quindraco** [comment]
Also, Command Squads are incorrectly listed as HQs.  They should be Elites.

**Comment by alphalas** [comment]
will all be fixed with the next release.
