### ISSUE TITLE
Dkok Marshall and bodyguard. 

### ISSUE THREAD

**Issue by Foxen1** [BSData/wh40k-9e#12405]
**Describe the bug**
Bodyguards are allowed on all non named infantry characters according to codex. 
BattleScribe lack the option of assigning a bodyguard to a Dkok Marshall

**Comment by Mad-Spy** [comment]
Is this in the master data which has the DKoK integrated or in the release data?

**Comment by Foxen1** [comment]
> 

Released data

**Comment by AbonShell** [comment]
Yeah, I forgot to throw on attachés and bodyguards on anything but codex. I'll fix it for next release
