### ISSUE TITLE
Dkok and Arks detachment 

### ISSUE THREAD

**Issue by Foxen1** [BSData/wh40k-9e#12404]
**Describe the bug**
The app won't let you add a Dkok detachment to a regular Astra arks of omen detach. So that you can incorporate regular dkok units alongside with regular Astra units. 

It's possible to add dkok to a Astra patrol detachment but not omen. 

**Screenshots**
![Screenshot_20230130_103409](https://user-images.githubusercontent.com/7782482/215441172-01e8fc04-1fb9-4786-bf1b-885060ea028a.jpg)

**Device and data (please complete the following information):**
 - OS: Android

**Comment by Mad-Spy** [comment]
Fixed in next release.
