### ISSUE TITLE
Guilliman [Ultramarines]  is being hidden under Primaris filter

### ISSUE THREAD

**Issue by CaptainIdaho** [BSData/wh40k-9e#12416]
~~Adding Guilliman into an Ultramarines list comes up with notification of error, that he must have a Warlord Trait (i.e. spend 1 Command Point).~~

In addition, if using the unit filter and select Primaris (i.e. filter out Primaris) then Guilliman is included within that as if Primaris.

**Comment by acebaur** [comment]
He does indeed have to buy his Warlord trait per the UM supplement. I will look into the unit filter though
