### ISSUE TITLE
Imperium - Deathwatch: Heavy thunder hammer cost is incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12410]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Heavy thunder hammer cost has changed to 10 points

**Comment by FarseerVeraenthis** [comment]
They are showing as 12 on the MFM I just downloaded, which is what they are set to in the data.
Please provide a source.
