### ISSUE TITLE
Bugs and typos found for Chaos Space Marines repository

### ISSUE THREAD

**Issue by S0ulBreak** [BSData/wh40k-9e#12430]
Bugs:
1st typo that I found is under the "Daemon Weapons" ability, which reads "Until that fight is resolved, the bearer _cannon_ make any attacks with any daemon weapons it is equipped with. ()" I'm pretty sure that "cannon" is meant to be "cannot" instead.

2nd typo that I found was under the Helbrute ability "Frenzy" which reads: "Each time this model makes an attack, if it has 7 or fewer wounds remaining, re-roll a _wou nd_ roll of 1." Which incorrectly reads "wou nd roll" instead of "wound roll.”

Additional notes:
Thank you, guys, for your hard work designing this data for players to access their army's list, abilities, and wargear conveniently and to help people make organized army lists. You guys do such a wonderful job trying to keep up with rules updates and stuff as well. So keep up the good work guys👍.

Edit: I was wrong on the points for the Soulreaper, that was a typo, I thought that it was for the gun itself, not just the model, went to type five, fat fingered 1 on my way to 5, and then hit 6 instead. I am retarded

**Comment by Mad-Spy** [comment]
Rubric w/ soulreaper cost is correct.

**Comment by S0ulBreak** [comment]
> 

> 

I’m sorry, read the edit for context, I am retarded.

**Comment by S0ulBreak** [comment]
> Rubric w/ soulreaper cost is correct.

I’m sorry, read the edit for context, I am retarded.
