### ISSUE TITLE
Bug Report: Death Rider Units not showing

### ISSUE THREAD

**Issue by Deecee29** [BSData/wh40k-9e#12447]
Death Rider units not showing in list choices.

**Expected behavior**
Without the Hide Forge World tab chosen in the unit filters all the Death Rider units should be visible

 - Windows
 - 2.03.21
 - iOS
 - 2.03.15

**Additional context**
These unit show on the Android platform under the same circumstances

**Comment by AbonShell** [comment]
Delete and redownload your data
