### ISSUE TITLE
Assault Marine wargear error

### ISSUE THREAD

**Issue by JANXOL** [BSData/wh40k-9e#12453]
**Describe the bug**
At the present, plasma pistol equipped by the sarge is counted into the two pistol limit of the squad, which i believe shouldn't be the case.
As worded:

> The Assault Marine Sergeant's bolt pistol can be replaced with one of the following: 1 weapon from the Pistols list; 1 weapon from the Melee Weapons list.

(Pistols list does include the plasma pistol)

And

> Up to 2 Assault Marines can each have their bolt pistol and Astartes chainsword replaced with one of the following:
>   - 1 plasma pistol and 1 Astartes chainsword.
>   - 1 flamer.

(The chainsword can then be further replaced by an eviscerator)
Note that it explicitly mentioned 2 Assault Marines and not 2 models in this unit. Which would exclude the Sergeant from this limit.

For contrast:

> For every 5 models in this unit, 1 model’s Astartes chainsword can be replaced with 1 eviscerator.

That's per model and does include the sergeant.

Thus it seems to me one should be able to take plasma pistol on sergeant in addition to two plasma pistols on normal marines.

**Comment by acebaur** [comment]
This is already fixed. Add the eviscerator guy, select him and choose your pistol.

**Comment by JANXOL** [comment]
@acebaur You misunderstand. 

Give plasma pistol to sergeant, give plasma pistol to two marines -> it gives error. It shouldnt. You can have 3 plasma pistols in the unit.
