### ISSUE TITLE
Imperium - Astra Militarum: Heavy lascannon profile is incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12459]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The "Heavy Lascannon" of the Astra Militarum's "Field Ordnance Battery" should be "Heavy 2" instead of "Heavy D6".

**Comment by Dunamis55** [comment]
Confirmed as bugged.
Codex:
![image](https://user-images.githubusercontent.com/36267768/217309655-a3fdd8d6-d451-45f8-8852-f7cea819e490.png)

BattleScribe
![image](https://user-images.githubusercontent.com/36267768/217309706-fb4b493b-38b3-4ed2-aafd-eac40d0f23b8.png)
