### ISSUE TITLE
Warhammer 40,000: All Elite choices should be unique in a Boarding Patrol

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12452]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** For Boarding Patrols, all Elites choices should be limited to only one of each data sheet: “Each Elites unit in this Detachment must be different.” The only exception is Orks, who can take two units of Meganobz.

**Comment by Mad-Spy** [comment]
Agreed that implementation is up to the catalogue author.
