### ISSUE TITLE
Arks of Omen Detachment Elite Character slots are missing

### ISSUE THREAD

**Issue by Morhgoz** [BSData/wh40k-9e#12460]
As title say, Elite choice character slots are missing, at least for Codex: Orks.

**Comment by Dunamis55** [comment]
Elite characters are showing up to me ok. Please delete and update your data.
![image](https://user-images.githubusercontent.com/36267768/217306451-daab888f-e5e7-45f1-8750-4dae3d94e554.png)

**Comment by Dunamis55** [comment]
Apologies, I misread character slots as character choices. Does appear to be bugged at the moment.
