### ISSUE TITLE
Duplicating Long Fang unit changes wargear points cost

### ISSUE THREAD

**Issue by ProgrammingKiddo** [BSData/wh40k-9e#12469]
**Describe the bug**
When creating a Long Fangs unit with a Wolf Guard Terminator Pack Leader equipped with (Storm Shield, Thunder Hammer, Cyclone Missile Launcher), the cost of the unit should be 149pts (since all their wargear but multi-meltas is free).
However, when duplicating that unit, the Thunder Hammer's cost suddenly becomes 10pts, and so the unit cost goes up to 159pts.

**To Reproduce**
1. Create a Space Marine detachment
2. Select 'Space Wolves' as chapter
3. Add a unit of Long Fangs to the roster
4. Add a Wolf Guard Terminator Pack Leader to the unit
5. Select the following loadout for him: Storm Shield, Thunder hammer, Cyclone Missile Launcher
6. Right-click the Long Fangs unit and select 'Duplicate'

**Expected behavior**
When duplicating the Long Fangs unit, the newly created unit should have the same loadout costed at the same points.

**Screenshots**
[Screenshot.](https://imgur.com/a/5f172Ds)

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version v2.03.21.166
 - Release version v9.7.3

**Comment by Mad-Spy** [comment]
It's a known app bug so it won't get fixed due to the app being abandoned.. There's nothing we can do on the data side to fix it. All you can do is remove the model and add it again. Closing and reloading the list would also resolve it.
