### ISSUE TITLE
Imperium - Astra Militarum: Militarum Tempestus Command Squad counts as 2 CHARACTERS in Boarding Patrols

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12474]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** In a Boarding Patrol Detachment, a Militarum Tempestus Command Squad is counting as more than one character toward the character limit of 3, similar problem that the Cadian Command Squad had in issue #12439

**Comment by AbonShell** [comment]
Fixed in latest release

**Comment by Moxieman00** [comment]
Are you certain? I am on version 9.7.5, 40K v246, Astra Militarum v319. The Militarum Tempestus Command Squad could not even be selected as an HQ option before this release, so I couldn’t see the character limit issue before this release for this unit.

**Comment by AbonShell** [comment]
U rite
