### ISSUE TITLE
Aeldari - Drukhari: make Grotesque output less grotesque 

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12480]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Would it be possible to fix the Grotesques so that entries are not replicated for no reason? Instead of seeing many entries, just 6x Grotesque w/ Monstrous Cleaver (for example).

**Comment by FarseerVeraenthis** [comment]
Yeah, I can take a look 😺
