### ISSUE TITLE
Craftworlds warlock skyrunner character not counting towards character elite slots in Arks detachment

### ISSUE THREAD

**Issue by TheresasAccount** [BSData/wh40k-9e#12487]
**Describe the bug**
Craftworlds solo warlock does not count towards character elite slots

**To Reproduce**
1. Make craftworlds detachment for Craftworlds
2. Fill up elite slots
3. Add character warlock

**Expected behavior**
Character warlock should not count towards elite, should count against elite character

**Screenshots**
![image](https://user-images.githubusercontent.com/50762188/218292319-613cfe51-a620-44e1-a586-d999c594539a.png)

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version 2.03.21
 - Release version v9.7.4

**Additional context**

**Comment by FarseerVeraenthis** [comment]
Yeah, that's gonna be a fun one to sort out...
