### ISSUE TITLE
Guilliman must spend CP to get warlord trait in Deathwatch

### ISSUE THREAD

**Issue by brianlaw033** [BSData/wh40k-9e#12498]
**Describe the bug**
Deathwatch’s Guilliman is getting error if not spending cp to get warlord trait

**To Reproduce**
1. Create AoO Deathwatch list
2. Add Guilliman to the list
3. See Error

**Expected behavior**
Not having “must have 1 more selection of warlord trait” error

**Device and data (please complete the following information):**
 - all os
 - v9.7.6

**Comment by acebaur** [comment]
8th edition SM supplement named characters are required to pay for their WLT due to the wording in their book. Working as intended
