### ISSUE TITLE
World Eaters - Exalted Eightbound error

### ISSUE THREAD

**Issue by JANXOL** [BSData/wh40k-9e#12499]
**Describe the bug**
One of the gear options for exalted eightbound champion is "Two eviscerator chainfists" - whatever that is supposed to mean - and it appears to give him two eviscerators, which is not correct. The weapon option should be "two chainfists" and give him two chainfists, there is no option for him to take two eviscerators.

**Comment by Mad-Spy** [comment]
Look like I made a mistake; thanks for your condescending report.

**Comment by JANXOL** [comment]
Apologies if you take it as condescending, it was not the intent.
