### ISSUE TITLE
Disciples of the Red Angel unit inclusion/exclusion errors

### ISSUE THREAD

**Issue by Multitallented** [BSData/wh40k-9e#12494]
For the Disciples of the Red Angel subfaction of the new World Eaters catalogue, the following units are available when they shouldn't be:

- Chaos Spawn
- Hellbrute
- Defiler

The entire selection of Khorne Daemons from the Daemons catalogue should be available within the Arks of Omen detachment.

**Comment by Dunamis55** [comment]
- Chaos Spawn is BEAST, so shouldn't be available. - Actual bug.
- Helbrute doesn't have DAEMON, so shouldn't be available. - Actual bug.
- Defiler meets the criteria, so should be able to be taken. - Working correctly.
- Any units from any other codex (such as Codex: Chaos Space Marines, Codex: Daemons, or the Imperial Armour Compendium) do not have the WORLD EATERS keyword, so don't bypass the World Eater Battle-Forged Rules that the Disciples of the Red Angel sub-faction uses. - Working correctly.

**Comment by Multitallented** [comment]
Actual quote from the book reads "Your army can only include **KHORNE DAEMON** units and **WORLD EATERS CHAOS LAND RAIDER** units." From this quote you can see that Khorne Daemons from Codex: Daemons can be included within the Arks of Omen detachment.

You are correct that the Defiler does have the **KHORNE DAEMON** keywords. My mistake.

As a side note, you can include Be'lakor in a Disciples of the Red Angel army, but you would lose the Blood Tithe mechanic since he is not an Agent of Chaos.

**Comment by Dunamis55** [comment]
The actual relevant quote from the book reads:

> When mustering your army, if it includes one or more **WORLD EATERS** Detachments, you must select one of the following sets of Sub-faction rules for your army to use for the duration fo the battle (make a note of any Sub-faction rules your army is using on army roster):
> - World Eaters (pg 46-47).
> - Disciples of the Red Angel (pg 48-49). Note that these rules include additional restrictions that apply when mustering your army.

You cannot bypass faction rules with the additional restrictions that apply to the subfaction. If you don't have **WORLD EATERS** as a faction keyword, you can't be in the Disciples of the Red Angel subfaction Detachment either, **KHORNE DAEMON** or not.

**Comment by Multitallented** [comment]
Had a conversation about this on the World Eaters discord. You are correct. I'm getting leaks mixed up with rules as written
