### ISSUE TITLE
Agents of the Imperium Dataslate

### ISSUE THREAD

**Issue by MechMK1** [BSData/wh40k-9e#12490]
A new dataslate [**Agents of the Imperium**](https://www.warhammer-community.com/2023/02/13/imperial-agents-datasheet-inquisitors-and-assassins-join-the-battle-against-the-arks-of-omen/) was released today.

This affects the following units:

- Callidus Assassin
- Culexus Assassin
- Eversor Assassin
- Vindicare Assassin
- Lord Inquisitor Draxus
- Inquisitor Coteaz
- Inquisitor Greyfax
- Inquisitor Karamazov
- Inquisitor
- Inquisitor Eisenhorn
- Jokaero Weaponsmith
- Acolytes
- Daemonhost
- Imperial Navy Breachers
- Cartographica Rogue Trader
- Voidsmen-at-arms

Furthermore, the dataslate includes the Telethesia Discipline for psykers, which includes the following powers:

- Terrify
- Psychic Fortitude
- Dominate
- Mental Interrogation
- Psychic Pursuit
- Castigation
- Ordo Hereticus: Scourging
- Ordo Xenos: Psychix Veil
- Ordo Malleus: Waring Incantation

These units and abilities should be added/updated in whichever catalogue they belong.

**Comment by Dunamis55** [comment]
Is already being worked on.

**Comment by MechMK1** [comment]
Is there an issue to track progress on? I couldn't find one

**Comment by Dunamis55** [comment]
Not at the moment. The data devs are exploring the best way to consolidate everything into a workable catalogue.
There's not a lot of new changes though, so there is a possibility that there won't be a progress tracker.
