### ISSUE TITLE
World Eaters - Exalted Eightbound - Wargear Options - Champion Dual Eightbound Chainfist

### ISSUE THREAD

**Issue by tarkingt0n** [BSData/wh40k-9e#12502]
**Is your feature request related to a problem? Please describe.**
In release 9.7.6, when adding a unit of Exalted Eightbound, the Champion has the option to replace an Eightbound Eviscerator with an Eightbound chainfist.  When selecting this, the resulting output indicates "Two eviscerator chainfists" but the selection indicates "2x Eightbound eviscerator".  

The weapon 'tooltip' displayed when mousing over the "Two eviscerator chainfists" option when customizing wargear for the champion model also presents the weapon profile for Eightbound eviscerator.

**Describe the solution you'd like**
I'd like to request the output be changed to "Two Eightbound chainfist" and the Selections: indicate "2x Eightbound chainfist".  I'd also like to request the corresponding weapon profile in the Weapons preview be changed to reflect.

**Additional context**
See page 58 in Codex: World Eaters for reference.

**Comment by AbonShell** [comment]
fixed in next release
