### ISSUE TITLE
Imperium - Agents of the Imperium v85 - units hidden for battalion detachments

### ISSUE THREAD

**Issue by KalChoedan** [BSData/wh40k-9e#12504]
AoI units are being hidden for battalion detachments, for all Imperium factions.

To Reproduce:

Create a roster containing a battalion detachment of any Imperium faction and gametype. No AoI units are visible.
For even more weirdness, add a second detachment of AoI - you only see fortifications. Removing the battalion doesn't clear this, only recreating the roster.

**Comment by OneBluewolf** [comment]
This still appears to be an issue. I am not seeing the AoI listed as an option for battalion detachments.

**Comment by KalChoedan** [comment]
@OneBluewolf 

> This still appears to be an issue. I am not seeing the AoI listed as an option for battalion detachments.

Unless you're using the bleeding edge data manually downloaded from github, that's expected behaviour. This fix has been implemented, but not pushed out to the released data yet. Compare the date of the fix to the date of the most recent release to confirm.

![image](https://user-images.githubusercontent.com/1786901/220375843-80dd90f4-fcbb-46d8-8d74-32d313d560e9.png)
