### ISSUE TITLE
Aeldari - Shuriken Catapult missing from Wraithlord / Aeldari Flamers & Shuriken Catapult option

### ISSUE THREAD

**Issue by neonsamurai** [BSData/wh40k-9e#12510]
**Describe the bug**
When adding 'Aeldari Flamer & Shuriken Catapult' to the Wraithlord, the Shuriken Catapult is missing from the Wraithlord's profile.

**To Reproduce**
1. Create a new Aeldari Roster.
2. Add a Warithlord to the Roster
3. Add the option 'Aeldari Flamer & Shuriken Catapult' to the Wraithlord
4. Open Roster by clicking on 'View roster' button
5. The Wraithlord does not have the Shuriken Catapult in its profile

**Expected behavior**
The Wraithlord should have profiles for the flamer and the Shuriken catapult in its profile.

**Comment by Mad-Spy** [comment]
You need to drill down into the fists to add the relevant weapon, then they will appear.

**Comment by neonsamurai** [comment]
@Mad-Spy I don't think that's correct.

The configuration of the Wraithlord looks like this:
![Bildschirm­foto 2023-02-19 um 23 05 55](https://user-images.githubusercontent.com/1582455/219977941-09ac6a4d-7d7c-415a-9f17-87389db2d10f.png)

When looking at the Roster preview it does not show shuriken catapults:
![Bildschirm­foto 2023-02-19 um 23 07 27](https://user-images.githubusercontent.com/1582455/219977980-ea98274a-88a1-4d29-887f-fed43791c46e.png)

However I noticed in the data editor, that the shuriken catapult is missing from the wraithlord's corresponding Support Weapon Configuration:
![Bildschirm­foto 2023-02-19 um 23 08 39](https://user-images.githubusercontent.com/1582455/219978032-819597dc-4eb4-426a-b223-ad8e1c12f905.png)

And when I added the shuriken catapult to the profile in the data editor, it would show up correctly on the roster. I think I could provide a pull request with the fix, if that helps.

**Comment by Mad-Spy** [comment]
Sorry, I thought it was set up like other "dreadnoughts". It's a bug so it'll get looked at in due course.

**Comment by FarseerVeraenthis** [comment]
@neonsamurai you can submit a PR if you like. Please use a link to the shuriken catapult profile (in the same way the flamer has been linked) and remember to bump the revision number :smile:
I'll review the PR and merge it if it's ok :+1:
