### ISSUE TITLE
Imperium - Space Wolves: Guilliman not available

### ISSUE THREAD

**Issue by Egil31** [BSData/wh40k-9e#12514]
No option to add Roboute Guilliman in Arks of Omen detachment in base v.9.7.6

**Comment by Mad-Spy** [comment]
You need to select that you are using the "Arks of Omen" game type first.

**Comment by Egil31** [comment]
Sure
I select Detachment Arcs of Omen, game type Arks of Omrn
![Screenshot_2023-02-20-15-08-54-193_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/108886214/220088759-02d338a9-c44a-4dab-88f9-1b23186e00cd.jpg)

**Comment by Mad-Spy** [comment]
Ok, then he will be there under Lords of War.

![Screenshot_20230220-123904](https://user-images.githubusercontent.com/29306451/220110463-4d91aa4e-684c-41f9-bcf5-e6dff95293f9.png)

**Comment by Egil31** [comment]
In space wolves v232 Guilliman is not in Lord of War.

> Ok, then he will be there under Lords of War.
> 
> ![Screenshot_20230220-123904](https://user-images.githubusercontent.com/29306451/220110463-4d91aa4e-684c-41f9-bcf5-e6dff95293f9.png)

![Screenshot_2023-02-21-20-56-10-423_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/108886214/220410123-e006a3f7-6beb-497a-947d-3c83a9794170.jpg)
