### ISSUE TITLE
Aeldari - Craftworlds: Shrine Relic validation is not working correctly

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12523]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** In an Arks of Omen matched played list, when selecting a shrine relic for an exarch model it doesnt require you to use the stratagem relic of the shrines. In matched play you have to spend a command point for two shrines, and in a ynaari detatchment, you can use the stratagem, relic of the shrines twice but ONLY if your warlord has the asuryani keyword, when i select my Warlord to be my Death Jester in my unbound army it should not allow me to select Relic of the Shrines twice

**Comment by Mad-Spy** [comment]
Not sure why OP is referring to an Unbound Detachment above, as that is not permitted in Arks Matched Play?

I think there are actually two problems here based on their description though.

1. Users are able to select Shrine Relics by _only_ selecting a Warlord in Arks rules.
2. Harlequin Warlords are unlocking Shrine Relics, but they are not ASURYANI so they shouldn't.
