### ISSUE TITLE
Blood Angels - Roboute Guilliman not visible

### ISSUE THREAD

**Issue by Tixbert** [BSData/wh40k-9e#12533]
I tryed to create an Arks of Omen Blood Angels Detatchment with Roboute Guilliman but I cannot find him in the Lord of War categorie.
Just before I tried with Imperial Fists and Black Templar. And there he is in the Lord of War categorie. 

I already downloaded the newest data 9.7.6 (delete old first). 
I use an Android Phone.

**Comment by acebaur** [comment]
Update your data and check the delete all data. Box when you do

**Comment by KalChoedan** [comment]
I'm pretty sure this one is actually broken in the current data:

![image](https://user-images.githubusercontent.com/1786901/220933536-376e4740-e08e-432c-89a4-a0081e6f171a.png)

**Comment by Tixbert** [comment]
I deleted and reloaded my data again. Same result. He is missing
