### ISSUE TITLE
World Eaters Exalted Eightbound Champion Chainfists Issue

### ISSUE THREAD

**Issue by Bababyka** [BSData/wh40k-9e#12541]
For the Exalted Eightbound, He has the option for "Two Eviscerator Chainfists" which have the profile of a normal eviscerator which isn't possible on the Exalted Champion, I'm assuming its meant to be the profile for the 2 chainfists with the Damage increase to 3 but is a current issue
![exalted](https://user-images.githubusercontent.com/126386411/221403797-76067f22-81b9-4867-8d1c-f0ee8fb507cb.PNG)

**Comment by AbonShell** [comment]
Fixed in next release
