### ISSUE TITLE
Open the Vaults stratagem missing on Knight-Centura

### ISSUE THREAD

**Issue by HemlockNight** [BSData/wh40k-9e#12544]
Thisis  the stratagem to give a character a relic. The relics of the vigil section shows up by default if game type isn't selected, but disappears when game type is selected, nowhere is the tickbox to use Open the Vaults.

**Comment by Mad-Spy** [comment]
Please include the affected Faction on any issue reports.

**Comment by Mad-Spy** [comment]
However, Open the Vaults is selected at the Roster level, not on an individual model, and you need an ADEPTUS CUSTODES WARLORD in order to select it in the first place.

![image](https://user-images.githubusercontent.com/29306451/221821214-ea1cd9eb-0ba4-4d23-9224-5db173ff3509.png)
