### ISSUE TITLE
Necrons - +2CP added when making Imotekh your Warlord in AoO Detachment

### ISSUE THREAD

**Issue by Thorrgrym** [BSData/wh40k-9e#12542]
**Describe the bug**
When using Arks of Omen detachment, adding and selecting Imotekh as Warlord adds 2 CP to the CP total.

**To Reproduce**

Create a Necrons Arks of Omen Detachment and select Imotekh to be added.  Add him and make him Warlord.  Your CP will jump from 6 to 8.  No other character models are doing this.

**Expected behavior**
I expected that when Imotekh was added as Warlord it would not add any CP as that is not a thing in Arks of Omen.

**Screenshots**
![image](https://user-images.githubusercontent.com/126421960/221437844-ae84666a-34ff-4dee-88ae-398a01506653.png)

**Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version 2.03.21.166
 - Release version 9.7.6

**Additional context**

**Comment by AbonShell** [comment]
Working as intended. Please read the datasheet of the model

**Comment by Thorrgrym** [comment]
Apologies. My son was sure it worked a different way.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
