### ISSUE TITLE
Boarding Patrol - Imperial forces - Validation error for needing to select "Ordo"

### ISSUE THREAD

**Issue by fuzzypat** [BSData/wh40k-9e#12556]
When you choose the "Boarding Patrol" detachment under the "Add Force" button while creating a new roster, the resulting roster will show a validation error for the new roster, that it "must have 1 more selections of Ordo Selection (minimum 1)".  

It seems to happen for multiple "Imperial" factions.  It does not happen when choosing non-Imperial factions (*e.g.* Chaos Knights, Aeldari Harlequins).  It does not happen when you chose a detachment that is not the "Boarding Patrol" detachment.  

<img width="519" alt="Ordo Selection" src="https://user-images.githubusercontent.com/126894991/222760080-cb3dd72b-3b68-4a1e-8855-f869ab5588f0.png">

**Comment by AbonShell** [comment]
Oops, forgot to set a hide if the primary catalog isn't agents.

**Comment by fuzzypat** [comment]
Thank you!
