### ISSUE TITLE
Orphaned links (target no longer exists)

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-9e#12550]
**Describe the bug**

Thanks to Project Phalanx, I've found a couple of links for which the targets have been removed and no longer exist.

These references (`targetId`s) are unresolvable and a simple text search reveals that there are no entries that have these IDs anywhere in this repository - they're only used as target IDs (references) and therefore are broken:
- 11x `5518-d0f5-a880-d71c` (Battle Honours)
- 1x `96e4-0a16-0d00-c15d` (Wyrdvane Psykers)
- 1x `8774-e003-4a50-56c7` (Custom Character Selections)
- 1x `43c4-8968-c599-ad5f` (Is a Custom Character)

**Expected behavior**

There are no orphaned/broken references/links.

**Screenshots**

![image](https://user-images.githubusercontent.com/2671396/222212888-8279d592-88b6-4f4f-9501-04b3e8c106f6.png)

**Comment by AbonShell** [comment]
Can you give what files they're in?

**Comment by amis92** [comment]
I think it's easier to just do a full-text search in the repo, in like notepad/vscode?

**Comment by amis92** [comment]
Thanks! 🚀
