### ISSUE TITLE
Adding Canis Rex as AGENT OF THE IMPERIUM

### ISSUE THREAD

**Issue by p5freak** [BSData/wh40k-9e#12560]
Canis Rex is missing in the AGENT OF THE IMPERIUM list. Any IMPERIUM army can add Canis Rex because he has the AGENT OF THE IMPERIUM faction keyword.

AGENT OF THE IMPERIUM
If your army is Battle-forged, you can include one Agent of
the Imperium unit in each Imperium (excluding Fallen units)
Patrol, Boarding Patrol, Battalion, Brigade and Arks of Omen
Detachment in your army without those units taking up
Battlefield Role slots in those Detachments. The inclusion of
an Agent of the Imperium unit does not prevent other units
from their Detachment benefiting from Detachment abilities
(e.g. Chapter Tactics), and it does not prevent other units from
your army benefiting from abilities that require every model
in your army to have that ability (e.g. Combat Doctrines).
An Agent of the Imperium unit included in a Patrol, Boarding
Patrol, Battalion, Brigade or Arks of Omen Detachment in this
manner is ignored for any rules that state all units from that
Detachment must have at least one Faction keyword in common
(e.g. in a matched play game), and when determining your
Army Faction.

**Comment by AbonShell** [comment]
While he has the agent of the Imperium keyword, he does not have the agent of the imperium ability.
