### ISSUE TITLE
Paragon of the Chapter not validating properly - should require a DA WLT

### ISSUE THREAD

**Issue by corrinavatan** [BSData/wh40k-9e#12570]
**Describe the bug**
The above mentioned stratagems, which grant a second WLT for the DA, BA, and SW codices, do not validate Warlord Traits properly.  Each of the stratagems require that the second WLT given must be a DA, BA, or SW warlord trait; however, the Battlescribe error validation will say the list has no errors, even if the character is given two non-chapter warlord traits.  Confirmed myself that BA/DA/SW traits do not validate properly, have not checked personally if Ultramarine, Black Templar, White Scar, or other chapter traits are also not validating.

Issue is the same as closed issue #12564, which was just for Deathwatch

**To Reproduce**
1.  Create a Blood Angels, Space Wolves, or Dark Angels list, Arks of Omen detachment
2. Make any Character a Warlord.
3. Select the "Warlord Trait" and appropriate "Second Warlord trait" stratagem for that chapter
4. Select two Warlord traits, with neither of them being a chapter-specific warlord trait (aka use Space Marines Codex or Vanguard warlord traits.
5. Validation will not detect an error.

**Expected behavior**
That validation for the use of Paragon of the Chapter (DA) Warrior of Legend (SW) and Angel Exemplar (BA) checks to confirm that at least one Chapter-specific WLT is on the character to meet the wordings of each stratagem.

**Screenshots**
N/A

**Device and data (please complete the following information):**
 - 
 - BattleScribe version [e.g. 2.03.24
 - Release version [e.g. v1.2.3]

**Additional context**
As stated, this is an "extension" of the issue reported in issue 12564, which was jsut for Deathwatch.  I have not checked the Ultramarines, Black Templar, White Scars, Imp Fists, or other chapters but I assume that they are also not validating properly

**Comment by Mad-Spy** [comment]
Warrior of Legend appears to be working as expected?

![image](https://user-images.githubusercontent.com/29306451/223218866-25834a8a-cb80-447e-be8c-0a6665ef4143.png)

**Comment by Mad-Spy** [comment]
As is Angel Exemplar
![image](https://user-images.githubusercontent.com/29306451/223219184-9189c932-b6b3-46a3-ac56-99712510141a.png)

**Comment by Mad-Spy** [comment]
Please provide a specific example of when this is not working.

**Comment by Mad-Spy** [comment]
Looks like it's only Paragon of the Chapter that is not working correctly.
