### ISSUE TITLE
Imperium - Space Marines: Primaris Lieutenant not updated to match latest datasheet

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12577]
**File:** Imperium - Space Marine library.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Primaris lieutenant missing a few weapon options, namely power fist and plasma. And sorry if that has been reported already

**Comment by MaxPowers1337** [comment]
Seems to me that the lieutenants options from the agastus box set is completely missing. Isn't it?
