### ISSUE TITLE
Desolation Squad errors

### ISSUE THREAD

**Issue by JANXOL** [BSData/wh40k-9e#12578]
There are a few errors with desolation squad. First and most important - the sergeant is missing.
It is available as a selection in BS, but its not actually considered a model - when put through yellowscribe, the unit only contains 4 models. The entry for the sergeant, who should have extra attack and leadership, doesnt show up in unit sheet, both in BS and YS.

Additionally all models are called "desolation marines". Plural. Expected names would be "desolation marine" (singular). And "desolation marine sergeant". 

Additionally, for the weapon entries: the strength of castellan launcher is listed as "S4", while it should be just "4". Similarly, AP of superkrak is listed as "AP -3" instead of "-3"

**Comment by Mad-Spy** [comment]
Summary of issues:

1. Marines and Sgt have a type of "Upgrade" instead of "Model"
2. Sgt is missing his model profile.
3. Desolation Marine Selection Entry and profile are incorrectly pluralised.
4. Castellan launcher S value should be "4", not "S4".
5. Superkrak AP value should be "-3", not "AP -3".
6. PL doesn't increment until the 7th model is added, rather than the 6th.

**Comment by Xanetaaz** [comment]
The unit is missing it’s castellan launchers.
Stats are:
Castellan launcher 36" Heavy D3 S4 AP-1 D1 (Blast. This weapon can target units that are not visible to the bearer.)

Can't get to show, so don't know where the op has seen it.

**Comment by JANXOL** [comment]
![castellan](https://user-images.githubusercontent.com/20998469/224540647-c583dbc5-feab-4b81-acc2-99a20045b998.png)
I have seen it right there. Update your files.

**Comment by Xanetaaz** [comment]
> I have seen it right there. Update your files.

Did that yesterday and just now again, they don't show up.
![Udklip1](https://user-images.githubusercontent.com/79477613/224549489-5706a250-faff-4355-8f80-2c8524215cb3.JPG)

**Comment by nc623XH** [comment]
Same thing here, latest release and on iOS. Castellan Launcher is completely missing.

**Comment by acebaur** [comment]
The Launcher is on the master, so if you are pulling from that you will see it. If you are waiting for appspot then you won't see it
