### ISSUE TITLE
[Admech] No CP cost for additional Relic when picking Relic via Stratagem

### ISSUE THREAD

**Issue by Cephel** [BSData/wh40k-9e#12581]
**Describe the bug**
The Technoarchaelogist can take a relic without the respective character strategem, effectively bypassing the CP cost for taking it. It seems this can apply to a number of unit combinations, I'm listing the one I reproduced below, but I believe this is an issue with the Stratagem: Archeotech Specialist, rather than the unit(s) themselves.

**To Reproduce**
1. Make a new roster, Adeptus Mechanicus with an Arks of Omen Detachment
2. Change game type to Arks of Omen, Set Forge World to Mars, add AoO compulsory type, set it to Troops
4. Add 3x Skitarii Rangers (they don't matter, we just need them to get rid of validation errors)
5. Add 1x Skitarii Marshal, make him the Warlord, give him Stratagem: Archeotech Specialis, select Relic: Exemplar's Eternity
6. Add 1x Technoarchelogist, observe that the Relic selection is already opened and one can be selected freely. No validation error is produced as a result of this. This should not happen, as the Relic was already taken by the Marshal.

Additionally: You can verify that the 2 relics are linked, by unselecting Archeotech Specialist from the Marshal, there is now a validation error for BOTH the Marshal and the Technoarcheologist.

**Expected behavior**
The way I understand it, 1x selection of Archeotech Specialist should entitle you to pick 1 and only 1 relic. If you want to pick another relic via the same stratagem, you must include the stratagem multiple times. The relevant rule quote is:

> Select one ADEPTUS MECHANICUS CHARACTER model in your army and give them one Relic (this must be a Relic they can have). Each Relic in your army must be unique, and you cannot use this Stratagem to give a model two Relics. You can only use this Stratagem once, unless you are playing a Strike Force battle (in which case you can use this Stratagem twice), or an Onslaught battle (in which case you can use this Stratagem three times).

**Screenshots**
\-

**Device and data (please complete the following information):**
 - OS: Windows 11
 - BattleScribe version v2.03.21.166
 - Release version v9.7.8

**Additional context**
I am relatively new to the game, I tried making sure that this isn't some obscure rule that I was missing, but it is entirely possible I oversaw something, if that's the case I apologize for filing this report in error.

**Comment by Mad-Spy** [comment]
In addition, it is possible to give a model two Relics by selecting both the Relic strat and Archeotech Specialists, which shouldn't be possible.
