### ISSUE TITLE
Tau Broadsides cant take any 2 Secondary Systems

### ISSUE THREAD

**Issue by CassWindred** [BSData/wh40k-9e#12584]
Broadside Battlesuit units have the following rules:

• Any number of BATTLESUIT models can each have their heavy rail rifle replaced with 2 high-yield missile pods.
 • Any number of BATTLESUIT models can each be equipped with up to two of the following (duplicates on the same model are not allowed):
  ○ 1 advanced targeting system
  ○ 1 early warning override
  ○ 1 multi-tracker
  ○ 1 seeker missile
  ○ 1 stabilised optics
  ○ 1 twin plasma rifle
  ○ 1 twin smart missile system (cannot be equipped alongside twin plasma rifle)
  ○ 1 velocity tracker
Note: No model can be equipped with more than one of the following: early warning override; stabilised optics; twin plasma rifle; velocity tracker.

However, certain combinations of 2 Secondary System provide the error "Broadside Shas'ui has 1 too many selections of [thing] (maximum 0)"

**To Reproduce**
1. Add a Broadside Battlesuits unit to a Tau roster
2. Select a Battlesuit and tick the Secondary Systems "Early Warning Override" and "Stabilised Optics" (several other pairings also produce the error)
3. Observe error

**Expected behavior**
Valid battlegear selections such as "Early Warning Override" and "Stabilised Optics" should not produce an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/12970693/223872257-aee886f6-8de9-48a5-802d-f91bfb8910f0.png)

**Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version 2.03.21
 - Release version 248

**Comment by AbonShell** [comment]
"Note: No model can be equipped with more than one of the following: early warning override; stabilised optics; twin plasma rifle; velocity tracker."

You are equipping two from that list, thus giving an error. There is no bug.
