### ISSUE TITLE
Orphaned conditions (target/child no longer exists)

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-9e#12587]
**Describe the bug**

There are some conditions for which `childId` target no longer exists in any of repo's catalogues.

Thanks to Project Phalanx, I've found a couple of conditions for which the targets have been removed and no longer exist.

**Expected behavior**

All referenced elements exist.

**Additional context**

Below is the phalanx compilation output. I'd suggest to use a raw text editor or xml processor to find and fix/remove the apperances.
```
Compiled in 00:00:00.0041686
Diagnosed in 00:00:07.5457073
85x error WHAM0006: No candidates for binding this reference were found (ref='e536-b475-827e-e3cf' in Condition). No node with such id was found.
1x error WHAM0006: No candidates for binding this reference were found (ref='2633-9684-dace-c39c' in Condition). No node with such id was found.
1x error WHAM0006: No candidates for binding this reference were found (ref='6e6d-3f5b-3aac-ac75' in Condition). No node with such id was found.
3x error WHAM0006: No candidates for binding this reference were found (ref='95a3-3a66-87cd-9ae1' in Condition). No node with such id was found.
2x error WHAM0006: No candidates for binding this reference were found (ref='4092-2eb4-6372-5b4c' in Condition). No node with such id was found.
3x error WHAM0006: No candidates for binding this reference were found (ref='877b-8e8b-9af1-c91e' in Condition). No node with such id was found.
Diagnostic count: 95
```

**Comment by AbonShell** [comment]
e536-b475-827e-e3cf = World Eaters in the Modify group that sets ``Faction: <Legion>``
2633-9684-dace-c39c = Lord Arkos Inspiring Leader hide Logic


~~6e6d-3f5b-3aac-ac75 = Astra Militarum Mukaali Raiders
95a3-3a66-87cd-9ae1 = Ordo Malleus Inquisitor Logic
4092-2eb4-6372-5b4c = Orks Warboss on Bike Logic?
877b-8e8b-9af1-c91e = Big Mek Logic?~~
