### ISSUE TITLE
Warhammer 40K    BlackTemplar Primaris Crusader Squad   Not assigning Neophytes weapons other than Grenades

### ISSUE THREAD

**Issue by shane1492** [BSData/wh40k-9e#12590]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - BattleScribe version [e.g. 2.03.45]
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by acebaur** [comment]
They must all that the same weapon so it'd a single weapon selection outside of the models themselves. It is working as intended

**Comment by shane1492** [comment]
HI

Thank you for the reply Sorry to keep bugging you .... I am still confused .... in the attached screen shot I have 5 Primaris Initates with Chainsword and Heavy Bolt Pistol ...... the 4 Neophytes I have selected with Chainsword and Bolt pistol ......... Battlescribe is not assigning the Chain sword and bolt pistol to the neophytes, in fact it is not assigning any weapon the the neophytes at all. What am I doing wrong? I would like my whole squad Initate and Neophytes to have chains words.

Thanks     On Sunday, March 12, 2023, 08:39:26 AM MDT, Alex Baur ***@***.***> wrote:  
 
 


They must all that the same weapon so it'd a single weapon selection outside of the models themselves. It is working as intended
