### ISSUE TITLE
Drukhari Update

### ISSUE THREAD

**Issue by Carimnor** [BSData/wh40k-9e#12593]
Not all strategems are available for the Drukhari. In fact, only one is. Also cannot add "Favoured Retinues" upgrade to Kabalite Warriors. The Warhammer app also allows two Wyches to be equipped with Razorflails without a penalty. I'm not sure if this is actually allowed in game or not. Would someone please update the repository?

**Comment by Dunamis55** [comment]
1. Stratagems are only added to the roster editor if they're relevant to list building. If they're in-game stratagems, they generally aren't available in the data. If you have specific examples that you feel should be available during list building, please re-open the issue and let us know which ones are missing.
2. Kabalite Trueborn are considered a separate Troops selection to Kabalite Warriors. To be able to see and take them, you'll first need to upgrade an Archon to a Master Archon via the Splintered Genius upgrade. This is working correctly.
3. Wyches can only take 1 Razorflail if they have 10-19 models, or 2 Razorflails if the unit has 20 models. This is working correctly.
