### ISSUE TITLE
Necrons: Unable to select an Army of Renown in a Patrol Detachment

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12599]
**File:** Necrons.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Cult of the Cryptek are longer able to take a patrol detachment which they should be able to take.
Most likely because they now fall under the army of renown configuration item which did not allow it for the annihilation cult.

**Comment by acebaur** [comment]
If you are playing Arks of Omen that's correct, you cannot take a patrol detachment in that game format

**Comment by Mad-Spy** [comment]
More explicitly, the option to select an Army of Renown (of any kind) is not available in a Patrol Detachment, but should be. Cult of the Cryptek is not limited to any particular game type.
