### ISSUE TITLE
ARMY OF RENOWN: COGS OF VASHTORR

### ISSUE THREAD

**Issue by ThePhoenix676** [BSData/wh40k-9e#12592]
Description
A new army of renown was introduced. (COGS OF VASHTORR)

Describe the solution you'd like
The addition of the army of renown to battlescribe and add VASHTORR THE ARKIFANE datasheet.

Additional context
details of the this army of renown can be found on WAHAPEDIA:

https://wahapedia.ru/wh40k9ed/factions/chaos-space-marines/Vashtorr-the-Arkifane
https://wahapedia.ru/wh40k9ed/factions/chaos-space-marines/#Army-of-Renown:-Cogs-of-Vashtorr

**Comment by Mad-Spy** [comment]
There is no need to raise issues for newly released content.

Also, Wahapedia is not a primary rules source and should not be presented as one.
