### ISSUE TITLE
Blood Angels: Primaris Chaplain on Bike doesnt have the Litany of Hate (Aura)

### ISSUE THREAD

**Issue by ASauceDude** [BSData/wh40k-9e#12596]
Imperium - Blood Angels

BattleScribe version: 2.03.15

Platform: iPad iOS

Dropbox: Yes

Description: Primaris Chaplain on Bike dont show the Litany of Hate. In Categories is the Keyword PRIEST that says that this model knows the Litany of Hate.

Keyword: PRIEST | This model knows the Litany of Hate and one other litany from the Litanies of Battle. In your Command phase, if this model is on the battlefield, it can recite one litany it knows that has not already been recited by a friendly model this turn. Roll one D6: on a 3+, the recited litany is inspiring and takes effect until the start of your next Command phase.

**Expected behavior**
Litany of Hate should already show up in list of Litanies.

**Device and data (please complete the following information):**
iPad iOS
BattleScribe version: 2.03.15

**Comment by AbonShell** [comment]
Fixed in next release
