### ISSUE TITLE
Tau Boarding Action Wrong Units and validation

### ISSUE THREAD

**Issue by fallingbear** [BSData/wh40k-9e#12608]
Based on the boarding action and mustering rules 1.1, the following units are not allowed in boarding actions but are available.

- HQ
	- Commander in Enforcer Battlesuit (Has fly and is not a Crisis unit)
	- Commander in Coldstar Battlesuit (Has fly and is not a Crisis unit)
	- Longstrike (Is a vehicle)
- Elites
	- Ghostkeel Battlesuit(Is a vehicle)
- Fast Attack
	- Only pathfinders and tactical drones
- Heavy Support is not allowed

Either one stealth battlesuit or a Crisis unit is allow in the list. Currently, you can include both.

Mustering rules:

https://wahapedia.ru/wh40k9ed/the-rules/boarding-action-rules/#Mustering-a-Boarding-Patrol

![image](https://user-images.githubusercontent.com/611341/226142245-869ffbc9-f927-43d9-812b-80df6ee9eefd.png)

**Comment by amis92** [comment]
@AbonShell I think. I haven't touched catalogue in a long time.

**Comment by Mad-Spy** [comment]
Too much work to fix on old version
