### ISSUE TITLE
Chaos Knight's Lancer Tyrannical Court / Crown of Jedathra issue

### ISSUE THREAD

**Issue by gunandgod** [BSData/wh40k-9e#12605]
**Describe the bug**

when selecting Tyrannical court artifacts of tyranny are available which I don't believe should be the case. also, Crown of Jeathra should not be selectable as the lancer is not the required type.
**To Reproduce**

**Expected behavior**

relics should be available 
Crown should never be available to Lancers
**Screenshots**
![image](https://user-images.githubusercontent.com/128179218/225986221-bbc72e48-8bf6-4c45-9e8c-aa23e74392d0.png)
![image](https://user-images.githubusercontent.com/128179218/225986261-ed5a8253-7af6-4434-b878-d90cb6764f6e.png)
![image](https://user-images.githubusercontent.com/128179218/225986281-78614639-28d4-4172-87e9-51001a7c8d93.png)
![image](https://user-images.githubusercontent.com/128179218/225986291-4cf184ff-fad5-4262-b1ae-ba92e4420855.png)

**Device and data (please complete the following information):**
 - OS: PC
 - BattleScribe version 2.03.21.166

**Additional context**

**Comment by Mad-Spy** [comment]
Tyrannical Court grants CHARACTER, at which point the model becomes eligible to have Relics. That is not an error, however, I'm not sure how you've managed to get the Relic selector and the Relic stratagem option visible at the same time. If you can provide more details of your full list, please do.

The Crown appearing for incorrect unit types is a bug.
