### ISSUE TITLE
Orks - Too many Attacks for beastboss on squigasaur

### ISSUE THREAD

**Issue by zululim** [BSData/wh40k-9e#12619]
datasheet in battlescribe says he has an Attack characteristic of 6, Wahapedia says he has Attack characteristic of 5

**Comment by AbonShell** [comment]
![image](https://user-images.githubusercontent.com/20672472/227003467-f7fab84c-dd3c-4c5a-9962-8abd81dc7d9f.png)
It only changes to six when you select The Proper Killy WLT.

Also, don't use Wahapedia as a primary source. Because it isn't.
