### ISSUE TITLE
Aeldari - Drukhari: You should be able to give a Lord of Commorragh upgrade to a model, regardless of Cult/Kabal/Coven

### ISSUE THREAD

**Issue by AbonShell** [BSData/wh40k-9e#12613]
**Describe the bug**
The upgrade should be available regardless of what your subfaction selection for the detachment should be.

**To Reproduce**
1. Create a Drukhari detachment
2. Select any of the obsessions
3. Add a model that doesn't belong to obsession
4. Try to add a Lord of Commorragh upgrade to said model
5. See error

**Expected behavior**
Be able to upgrade regardless of selected obsession

**Comment by FarseerVeraenthis** [comment]
As discussed, there are cross-detachment validation issues which require user selection of obsession for each unit to be enabled so that 'everything' validates correctly...
