### ISSUE TITLE
CSM: Legion specific relics and WLTs not hidden for either belakor or vashtorr AoRs

### ISSUE THREAD

**Issue by WindstormSCR** [BSData/wh40k-9e#12626]
Both AoRs do not allow any legion-specific enhancements to be taken, however current behavior is that enhancements are still shown for whichever legion is selected, and a selection is required to create a roster without errors.

**Comment by Mad-Spy** [comment]
Legion WLTs are now hidden for Cogs (they were already hidden for DoB)
Legion Relics are now hidden for both AoRs.
