### ISSUE TITLE
Space Marines - Hero of the Chapter strat hidden for Iron Hands Dreadnoughts

### ISSUE THREAD

**Issue by gluck3d** [BSData/wh40k-9e#12622]
**Describe the bug**
A revision or two ago, Hero of The Chapter stratagem became unavailable for Iron Hands Dreadnoughts and I don;t see any reason for this. If the dreadnought has March of The Ancients

**To Reproduce**
1. create an empty Iron Hands detachment
2. Add Redemptor Dreadnought
3. Select Stratagem: March of the Ancients for it

**Expected behavior**
A strat Hero of the Chapter should appear, which would allow to add Warlord Trait to this dreadnought

**Actual behavior**
A strat Hero of the Chapter does not appear. Old lists  which have dreadnoughts with traits show an error that a unit can't have it.

**Device and data (please complete the following information):**
 - OS: Android
 - BattleScribe version  2.03.25
 - Release version v9.7.10

**Comment by acebaur** [comment]
Update your data

**Comment by gluck3d** [comment]
@acebaur 
? Sorry, may be I miss something, may you advise?
9.7.10 seem to be the latest data, isnt it?
