### ISSUE TITLE
Imperium - Deathwatch: Missing Xenophase blade selections

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12637]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Hi, veteran bikers and captains in Deathwatch can no longer choose to pick a Xenophase Blade

**Comment by FarseerVeraenthis** [comment]
seems to work fine for me 🤷
