### ISSUE TITLE
Imperium - Adepta Sororitas: Canoness Points Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12645]
**File:** Imperium - Adepta Sororitas.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Adepta Sororitas v214.  Canoness with organic equipment (Plasma Pistol, Power Sword and Rod of Office) is listed at 65 points (5 points per equipment). Should be no cost with the cost of the unit being 50 points.

**Comment by Valorcalls** [comment]
Those pieces of wargear have costs you have to pay. This has been this way the entire edition.
