### ISSUE TITLE
Adeptus Astartes: Space Wolf Point Inaccuracies

### ISSUE THREAD

**Issue by JPD444** [BSData/wh40k-9e#12646]
**Describe the bug**
When creating my list, I noticed some values were out of place. For the Elite Unite "Wolf Guard" there should be a 3-point cost for lightning claws and a 5=point cost for a Power Fist. Additionally, for the Primaris Lieutenant HQ unit, the option "If this model is not equipped with either a master-crafted power sword or a power fist, it can be equipped with one of the following: 1 master-crafted power sword; 1 power fist" is not present and I am unable to add a Master-Crafted Power Sword or Power Fist to my Primaris Lieutenant if they do not have one equipped. 

**Screenshots**
![Wolf Guard](https://user-images.githubusercontent.com/101355464/230735374-abcb9162-d514-4afb-917e-218e9db47a67.JPG)
![Primaris_Lieutenant](https://user-images.githubusercontent.com/101355464/230735375-06d2b236-ca0b-4ef2-ac80-ceaca6558cdc.JPG)

**Comment by Mad-Spy** [comment]
It looks like your data is out of date. Please update it.

The current version of the Wolves data is v236.
