### ISSUE TITLE
Armigers gaining agent of the imperium in a super heavy auxiliary detachment as a Freeblade, but normal knights not. 

### ISSUE THREAD

**Issue by Scout1032** [BSData/wh40k-9e#12656]
Currently it seems that only Armigers gain the agent of the imperium keyword when placed in a super heavy auxiliary detachment as a Freeblade, yet the actual knights don’t seem to. Which I find strange as Wandering hero should apply to all Freeblade knight units and not Armigers. 
![IMG_3198](https://user-images.githubusercontent.com/131710700/234098107-e62f87cd-c395-4ae8-9039-9d19bad643e5.jpeg)
![IMG_3199](https://user-images.githubusercontent.com/131710700/234098111-8f727919-3545-412d-ba65-79d32e9f2e8d.jpeg)

**Comment by AbonShell** [comment]
Already fixed in next release

**Comment by Scout1032** [comment]
Noted, thank you Abon
