### ISSUE TITLE
Leagues of Votann wargear as unit types

### ISSUE THREAD

**Issue by Uncle-Mel** [BSData/wh40k-9e#12653]
**Describe the bug**
The main infantry units (Hearthkyn, Beserks, Hearthguard and Brôkhy Thunderkyn) have separate datasheets for their main loadout. This is not consistent with other data files and creates unnecesary unit entries.

**Expected behavior**
A radiobutton for default loadout.

**Comment by Mad-Spy** [comment]
The current implementation better reflects the actual loadout of the models and avoids unit level selection of weapons which is problematic. No change will be made.
