### ISSUE TITLE
GULLIMAN has error when I select it to be the warlord.. It is forcing me with an error that I have to use the stratagem warlord traits for it. 

### ISSUE THREAD

**Issue by balannear** [BSData/wh40k-9e#12655]
**GULLIMAN has error when I select it to be the warlord.. It is forcing me with an error that I have to use the stratagem warlord traits for it. **

**To Reproduce**
1. Go to 'Ultramarine'
2. Click on 'gulliman' 
3. Scroll down to 'error 
![Screenshot_20230419_101503](https://user-images.githubusercontent.com/22398797/232950848-dc39386e-206e-4694-b55e-cd23ee0da905.jpg)
![16818712822134772707895292793653](https://user-images.githubusercontent.com/22398797/232950892-08f0b0c4-2e05-4161-9865-b5af7c1b9698.jpg)
'

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - BattleScribe version [e.g. 2.03.45]
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by acebaur** [comment]
The 8th edition supplements have wording that requires their named characters to take their WLT if they are Warlord.
Working as intended
