### ISSUE TITLE
Old balance dataslate points changes not present in latest dataslate are still used

### ISSUE THREAD

**Issue by jblasz** [BSData/wh40k-9e#12686]
Units use points values from old balance dataslates that are no longer present in dataslate 2023 q2 (and in-betweens) are still used in v9.7.14. Noticed:
Dataslate 2022 Q2 versus latest: 
harlequinn voidweaver cost change to 130pts no longer applicable, should cost the base 90pts.
harlequinn starveawer cost change to 95pts no longer applicable, should cost the base 80pts.

Rule changes are applied correctly (ie inv save worsened to 5++), so the 2023 q2 dataslate overall is applied.

drukhari kabalite trueborn cost increase by 3pts (to 11pts) no longer applicable, should cost the base increase by 2pts (to 10pts) (base unit of 5 should cost 50pts, and costs 55pts). This one I'm not sure which dataslate the change came from, but the increase is not present in latest dataslate or drukhari faq.

Dataslate 2022Q2: https://www.warhammer-community.com/wp-content/uploads/2022/04/lBLlqvrttJVgyfhC.pdf
Dataslate 2023Q2: https://www.warhammer-community.com/wp-content/uploads/2023/04/UgkX20O5FRSztM0r.pdf

**Comment by AbonShell** [comment]
Points are accurate per the latest MFM. 
https://www.warhammer-community.com/wp-content/uploads/2023/01/GQO2sMiMAgmdzDng.pdf
