### ISSUE TITLE
Space Wolf Rune Priest (no bike)

### ISSUE THREAD

**Issue by Hutchyweb** [BSData/wh40k-9e#12690]
I can only seem to find a Space Wolf Rune Priest on bike, not without a bike in the BattleScribe data set for Space Wolves.

Here's the GW model
https://www.games-workshop.com/en-GB/Space-Wolves-Rune-Priest

Here's a datasheet but its a Sword not Rune Axe and i'm not sure how old it is?
https://files.gitter.im/BSData/wh40k/Rdro/primaris-rune-priese.PNG

Could a rune priest be added pls?

**Comment by AbonShell** [comment]
The reason you're only seeing the one on bike is, it's the only valid option. The image of the data sheet you're showing is from the 8th edition book, of which is no longer valid. As of right now, there isn't a datasheet to represent that model.

**Comment by Hutchyweb** [comment]
OK, thanks. Same if i'd have known i'd have spend my money on another miniature. Fingers crossed for 10th edition. Thanks

**Comment by AbonShell** [comment]
Hate to break it to you but they're also not in 10th. They already released all sw units for 10th. They might get sheets in the legends update.

**Comment by Hutchyweb** [comment]
Doh!
