### ISSUE TITLE
Watch Master reference issue

### ISSUE THREAD

**Issue by skeletor100** [BSData/wh40k-9e#12694]
**Describe the bug**
Watch Master category is defined in the Deathwatch catalogue, but referenced in the Osseus Key in the Space Marines catalogue without importing the Deathwatch catalogue. It doesn't really cause any issues directly, as the Osseus Key can only be accessed if the Black Spear Task Force detachment is selected which is only made available through the Deathwatch catalogue, but it has the potential to cause issues if Osseus Key becomes accessible from a different catalogue.

**Comment by Mad-Spy** [comment]
Not sure why an Enhancement tied to a specific Detachment would become available to any catalogue that cannot take that Detachment? Roster builders handle it as expected, so nothing needs to be fixed at this time.

Also, you've reported a 10th edition issue in the 9th edition repository by accident.
