### ISSUE TITLE
Astra Militarum Tank Commander Pintle

### ISSUE THREAD

**Issue by DoctorAbyss** [BSData/wh40k-9e#12695]
Pointless Mount Option listed as
"Storm Bolter or Heavy Stubber" gives option of Heavy Bolter and shows Heavy Bolter stats instead of Heavy Stubber in selectable options.
![Screenshot_20230728_121636](https://github.com/BSData/wh40k/assets/55283356/221a91c8-ac9d-4750-ad9f-dc4e62c477d4)
![Screenshot_20230728_121624](https://github.com/BSData/wh40k/assets/55283356/6303dc9a-bb6c-4a54-856c-39a34ca181e6)
![Screenshot_20230728_121619](https://github.com/BSData/wh40k/assets/55283356/90279151-2236-4edb-a41d-7bac62fbb6ca)

**Comment by Mad-Spy** [comment]
Unable to replicate in current data
