### ISSUE TITLE
Heldrake missing attack values

### ISSUE THREAD

**Issue by smaughanster** [BSData/wh40k-9e#127]
**File/Catalogue:** 
Chaos Marines V3
**BattleScribe version:** 2.01.
2.01.02
**Platform:** Windows/iOS/Android/Mac/Linux
Android
**Dropbox:** Yes/No
No
**Description:** Detailed issue description.
Heldrake attack values not listed in the damage table

**Comment by cartag** [comment]
what the hell, I fixed that a while ago...

**Comment by smaughanster** [comment]
Thanks 😁
