### ISSUE TITLE
Missing VENDETTA GUNSHIP (legend) from battlescribe for 10th edition for Astra Militarum

### ISSUE THREAD

**Issue by Kimo2u** [BSData/wh40k-9e#12705]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - App being used to create lists [e.g. New Recruit, Bluescribe, Battlescribe]
 - App version
 - Data release version [e.g. v1.2.3]

**Additional context**

**Comment by AbonShell** [comment]
This is 9th edition repo.

**Comment by Kimo2u** [comment]
This is also 10th edition under legends from the warhammer community: 

https://www.warhammer-community.com/wp-content/uploads/2023/07/jNHY4B0QD6wZidaL.pdf
on page 38 

and also in the 10the edition LEGENDS FIELD MANUAL on the same site download page

https://www.warhammer-community.com/wp-content/uploads/2023/07/IS6VWf6eufvfcMiM.pdf
on page 9 with a 255 point cost for 10th edition



thanks to whomever updates this
    On Saturday, September 2, 2023 at 12:42:46 PM EDT, AbonShell ***@***.***> wrote:  
 
 


This is 9th edition repo.

**Comment by Kimo2u** [comment]
This needs to be reopen and have the vendatta gunship added based on Warhammer communtiy sources listed for Legend units with the 10th edition daraslate and points.
