### ISSUE TITLE
 not answered clearly Missing VENDETTA GUNSHIP (legend) from battlescribe for 10th edition for Astra Militarum legend

### ISSUE THREAD

**Issue by Kimo2u** [BSData/wh40k-9e#12707]
I sent a earlier issue  (Issue #12705) on this and received not a very clear answer why this would not be added. I presented the following

This is also 10th edition under legends from the warhammer community:

https://www.warhammer-community.com/wp-content/uploads/2023/07/jNHY4B0QD6wZidaL.pdf

on page 38

and also in the 10the edition LEGENDS FIELD MANUAL on the same site download page

https://www.warhammer-community.com/wp-content/uploads/2023/07/IS6VWf6eufvfcMiM.pdf

on page 9 with a 255 point cost for 10th edition

I respectfully request an answer why this would not be added to w40k legends in battlescribe in a more clearer manner and the above information from the warhammer community is being ignored,

thank you

**Comment by Mad-Spy** [comment]
You've once again raised your issue in the 9th edition repository, instead of the 10th edition repository. Please choose the correct version of Warhammer 40,000 when raising your issue.
