### ISSUE TITLE
Imperium - Astra Militarum: Ministorum units missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#128]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** Mac

**Dropbox:** No

**Description:** File - Imperium - Asta Militarum v6
Unit selection does not include units from Adeptus Ministorum, with Astra Millitaurm key words, i.e
HQ - Uriah Jacobs
Elite - Ministorum Priest

**Comment by alphalas** [comment]
#77 the cat is set up as the index is.
