### ISSUE TITLE
Imperium - Astra Militarum: Telepathica units missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#131]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** Mac

**Dropbox:** No

**Description:** File - Imperium - Asta Militarum v6
Unit selection does not include units from Adeptus Astra Telepathica, with Astra Millitaurm key words, i.e
HQ - Primaris Psyker
Elite - Wardvane Psykers
Elite - Astropath

**Comment by alphalas** [comment]
#77 the cat is set up as the index is.
