### ISSUE TITLE
Imperium - Astra Militarum: Issue with v2

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#133]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** No

**Description:** The Astra Militarum roster got completely nuked in v2. It had some errors in v1 so I updated everything and now it's missing half, or more, of the units it should have.

**Comment by alphalas** [comment]
v5 will be released shortly - it has everything corrected.
