### ISSUE TITLE
Imperium - Astra Militarum: units in wrong category

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#135]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** Yes

**Description:** When making a new list using the Astra Militarum or adding an Astra Militarum force to another force, the data either loads incorrectly or data is in wrong locations or missing. For example: I can't select any Heavy Support choices, Infantry Squad is under Uncategorised, The only Fast Attack choice is Rough Riders, Loads of units are missing. This happens on Windows as well as on Android with units being in the same location on both Windows and Android.

**Comment by BitterLies** [comment]
I reported the same thing.  It will be fixed on next release, according to the team.

**Comment by alphalas** [comment]
yup v5 will resolve the issue.
