### ISSUE TITLE
WH40K 8th ed Orks Missing HQs

### ISSUE THREAD

**Issue by Eoinmc97** [BSData/wh40k-9e#136]
**File/Catalogue:** 8th Ed WH40K Orks

**BattleScribe version:** 2.01.02

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Some special characters for Orks are missing from the HQ section, such as Ghazkghull and Zagstrukk.

**Comment by Gnofry** [comment]
![image](https://user-images.githubusercontent.com/17345182/27256004-ec5fdb06-5377-11e7-898e-dda5a3655439.png)



I am experiencing no issues with characters. Please purge your data and try again.

**Comment by tag8833** [comment]
Zhardsnark is gone because all FW chars a re gone pending the release of rules.  Ghazzy just moved to hq
