### ISSUE TITLE
Imperium - Dark Angels

### ISSUE THREAD

**Issue by MaverickIV** [BSData/wh40k-9e#139]
**File/Catalogue:** 

**BattleScribe version:** 2.01.00

**Platform:** Windows

**Dropbox:** No

**Description:** (Sorry for my possible bad English)

 - Ravenwing Bike squad: Ravenwing Sergeant from the Ravenwing Bike squad is charged 2pts where it should be 34 pts (missing the 32pts cost from regular Ravenwing Bikes).

 - Ravenwing Attack Bike: Ravenwing Attack Bikes don't have their twin boltgun listed nor charged (in either the Ravenwing Attack Bike Squad or the Ravenwing Bike Squad)

 - Deathwing Knights: The Knight Master misses his Storm Shield entry and cost. Also, Storm Shield entry for the Knights is marked 20pts where it should be 5pts (not a character). Save for the Knight Master’s Shield, the total cost of the unit is correct however.

 - Deathwind Terminators Squad: Selecting a heavy wepon don’t replace the storm bolter of the selected Terminator. The issue probably comes from the writing in the index that says they “can take a plasma canon or a weapon from the Terminator Heavy Weapons list” without replacing the storm bolter. Probably a writing error since all other Terminator Squads replace their Strom Bolter

 - Chaplain in terminator armor: not a HQ choice for the Unforgiven. We have Interrogator-Chaplain in terminator armor instead 😉

 - Librarian on Bike: Twin Boltgun listed twice and charged twice

 - Librarians Psychic Powers: When selecting the 3 psychic powers (where they should only know 2), no error is marked. (Not a big issue, but just in case)

 - Techmarines: The points marked in the selection list are the ones without wargear. The ones after selection are correct

 - Company Masters (Normal and in Terminator Armor): Storm Shield are listed and charged at 30pts. Should be 15pts since they are character.

 - Interrogator-Chaplain in Terminator Armor: Storm Shield entry doesn’t have a price (and is not charged when selected). Should be 15pts since it’s a character

 - Company Veterans: Veterans Sergeant should have acces to a Storm Shield for 5pts, not a combat shield for 4pts (the actual choice for the squad sergeant)

 - There are no options for taking a Deathwing Champion in the Elite choice list.

**Comment by Shurf** [comment]
To clarify: not replacing terminator storm bolter when taking a heavy weapon results in incorrectly priced terminator (it costs a stormbolter more)

**Comment by Thairne** [comment]
No, it does not. You do not replace the Storm bolter to take a heavy as you did in earlier editions.

**Comment by Dyrnil** [comment]
More bugs:

**Tactical space marine squad:**
- Not showing in the roster profile/summary. - 
- There should be a limitation when editing the squad's models number (you could have potentially 12 SM due to the selection of heavy and special weapon is set).

**Assault squad** - There's no limit to the squad size

**Deathwing knight roster profile** - The Ld and Save stats are switch

**Comment by Shurf** [comment]
I am sorry, I do not have the index with me at the moment, so I cannot look at exact wording. But not replacing the stormbolter results in some weird situations like a terminator having a cyclone missile launcher, power fist and two stormbolters it does not have enough hands for. While RAW this may be the case (can't look it up right now), this is very likely to be FAQed.

**Comment by Thairne** [comment]
I agree with the FAQ.
Still, currently RAW is RAW.

**Comment by Thairne** [comment]
I cannot reproduce the other bugs. Tacs are showing. If they're not, its a bug with BS since the data cannot influence that.
Also, you do get an validation error saying 7 marines are max when selecting special and heavy.

**Comment by Dyrnil** [comment]
I just tried again, both PC and android version, if you just use a tac squad, in the roster view (printer version) it is shown the sargeant, but not the normal marine.
