### ISSUE TITLE
8th, Adeptus Mechanicus: Various bugs

### ISSUE THREAD

**Issue by robinlindberg** [BSData/wh40k-9e#141]
**File/Catalogue:** Adeptus Mechanicus

**BattleScribe version:** 2.01.02.89

**Platform:** Windows

**Dropbox:** No

**Description:** 
**Kataphron Breachers:** No cap on amount of models. Should be maximum 12.
**Kataphron Destroyers:** No cap on amount of models. Should be maximum 12.
**Kastelan Robots:** No cap on amount of models. Should be maximum 6.
**Skitarii Vanguard:** Should have power level 8 for 6-10 models. Now has power level 4 for 6-9 models and power level 8 for 10 models.

**Sicarian Infiltrators:** No cap on amount of models. Should be maximum 10.
**Sicarian Infiltrators:** Should have power level 12 for 6-10 models. Now has power level 6 for 6-9 models and power level 12 for 10 models.

**Sicarian Ruststalkers:** Each model should be armed with transonic razor **and** chordclaw. Everyone but the Princeps currently only have the razor.

**Ironstrider Ballistarii:**  No cap on amount of models. Should be maximum 6.
**Sydonian Dragoons:**  No cap on amount of models. Should be maximum 6.

**Comment by raptor1770** [comment]
I am almost done fixing these bugs if someone can assign me to this issue. Thanks.

**Comment by DedusJovus** [comment]
Also, if i can add to this list, since it's also Admech, Vanguards seem to be limited to 2 special weapon choices, even if they have a full unit of 10 models. In that case it should be 3 special weapons allowed.

**Comment by Thairne** [comment]
@raptor1770 put in a pull request. I'll review and merge it.

**Comment by Thairne** [comment]
Most of these reports are actually NOT TRUE or made on old data.
Pull request caused several major errors.
Models that are not collective do not validate on the mask, but per error msg when a constraint is hurt.
Lesson learned.

**Comment by robinmtb** [comment]
Now neither Rangers, nor Vanguards can have special weapons in 5 model squads :(
