### ISSUE TITLE
Necrons Reanimation Protocols ability not displayed 

### ISSUE THREAD

**Issue by RAPJThompson** [BSData/wh40k-9e#147]
**File/Catalogue:** Necrons.catz

**BattleScribe version:** 2.01.02.89

**Platform:** Windows/Android

**Dropbox:** No

**Description:** Reanimation Protocols ability not displayed on units of Necron Warriors when viewing the Roster printout.
![reanimation protocols](https://user-images.githubusercontent.com/5531993/27256887-e96d9f42-5380-11e7-876e-a925885aef95.png)

**Comment by Kohato** [comment]
O.o Did you read the entire list printout?

**Comment by Kohato** [comment]
So, it's definately a bug. but not a data bug. It's a BS issue for some reason. The gauss flayer is causing the rule to hide.
