### ISSUE TITLE
Nothing working on ipad 

### ISSUE THREAD

**Issue by suldog** [BSData/wh40k-9e#148]
**File/Catalogue:** 

**BattleScribe version:** 2.01.02

**Platform:** iOS (ipad air 2)

**Dropbox:** No

**Description:** Detailed issue description: every time i add a unit or character from any army to any list it displays the name of the unit or character and the points and power cost and that is it no profile no weapons nothing

**Comment by GenWilhelm** [comment]
Its a bug in the iOS app. When viewing the roster go into options, then advanced options, and change "All Categories" to "No Categories".
