### ISSUE TITLE
Imperium - Astra Militarum: Missing choices, incorrect categories

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#149]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** No

**Description:** i know its still being worked on but you are missing transports super heavies the company commander should be hq guard squads should be troops veterans should be elites and there are a few others just figured i would chime in unless someone else hasn't yet or you didn't notice

**Comment by RaptorInMotion** [comment]
Already on it :)

**Comment by alphalas** [comment]
Yup it's all fixed - hopefully the release that fixes it will come out tomorrow
