### ISSUE TITLE
Blood Angels Captain in Gravis Armor Points Incorrect

### ISSUE THREAD

**Issue by jasonstanden** [BSData/wh40k-9e#151]
**File/Catalogue:** Warhammer 8th edition / Blood Angels

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** Yes/No

**Description:** The Master Crafted Power Sword listed on the Captain in Gravis Armour should cost 10 points, but is currently listed on the model for free (0 points).

**Comment by flakpanda** [comment]
Currently it is displaying the correct amount:
<img width="1497" alt="screen shot 2017-06-17 at 10 21 36 pm" src="https://user-images.githubusercontent.com/19719565/27257820-77d81e2c-53ab-11e7-91e9-8692a9f56b79.png">
