### ISSUE TITLE
Blood Angels Captain Storm Shield Bug

### ISSUE THREAD

**Issue by fedratsailor** [BSData/wh40k-9e#154]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** Yes/No

**Description:** Detailed issue description.
Was making a list of my HQ captain models. I had 3 of them in the list, and went to give one of them a Storm shield.  it gave all 3 of them the storm shield when I only needed it on that one model.  some sort of bug. This was all done in the Blood Angels section, Don't know if it apply's to other Space marine armies (codex, DA)

**Comment by flakpanda** [comment]
This is not a bug in the Space Marines catalog, but it is happening in the Blood angels one.

**Comment by Gnofry** [comment]
It seems that the storm shield the captain is linking to is Collective. Just need to create a non-collective version.
