### ISSUE TITLE
Drukhari, Cronos lacks Power Point value

### ISSUE THREAD

**Issue by Dragonoid1976** [BSData/wh40k-9e#157]
**File/Catalogue:** Aeldari-Drukhari v1

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** No

**Description:** While perusing the Drukhari catalogue, I noticed that the Cronos is lacking a Power Points value on its entry, and I cannot add more Cronos to a single unit like I can with the Talos entry.

**Comment by Dragonoid1976** [comment]
While the Cronos now has a points value and can have more Cronos added to it, the PL for them is incorrect. They should cost 5 PL per model rather than the 7 they currently cost. Unless I'm missing something, of course.

**Comment by Toreador13** [comment]
Fixed in v4
