### ISSUE TITLE
Deathwatch Terminator Equipment Issue

### ISSUE THREAD

**Issue by NZStarlord** [BSData/wh40k-9e#159]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Death Watch Terminators don't get a Storm Bolter with their Power Fist and Meltagun, this is causing an issue of my armies going over cost due to paying for a Storm Bolter I don't have on the models, nor do I have to have it. You can have a Power Fist & Meltagun without taking a Storm Bolter.

**Comment by tag8833** [comment]
You cannot have a PF & Meltaguns wihout either a storm bolter or a heavy weapon.  
![image](https://user-images.githubusercontent.com/17749311/27261427-549faf26-5408-11e7-8bd6-caac37230be7.png)

![image](https://user-images.githubusercontent.com/17749311/27261428-61e4646a-5408-11e7-957e-69bc54f33215.png)

As you can see, the pf + meltagun only replaces the PF.  It doesn't replace the Stormbotler, so the Termie gets to keep it.  

I understand that this is weird, and might not make sense from a modeling point of view, but it is how the rules have been written.  If you disagree with it, I recommend you ask GW to change it.

**Comment by NZStarlord** [comment]
While this is the case It does not replace the power fist With a Power fist
and meltagun AND storm bolter. sure I can keep the storm bolter, but in
your thing I am FORCED to keep the storm bolter if I want a power fist and
Melta gun

**Comment by francoisbeaulieu** [comment]
The storm bolter is in the standard wargear. You do have to have it if you didn't take an option that replaces it.
![img_0571](https://user-images.githubusercontent.com/12718495/27263765-22c8ee28-543e-11e7-9ce4-d0038db1a72e.PNG)

**Comment by NZStarlord** [comment]
Except that when I use your list my choices force me to take a Storm bolter
WITH the power fist and melta gun​
 20170619_075412.jpg
<https://drive.google.com/file/d/0BwVYtcIVEV8mOVA0QmFwM2dQMDA/view?usp=drive_web>
​

On Mon, Jun 19, 2017 at 7:52 AM, François Beaulieu <notifications@github.com

**Comment by francoisbeaulieu** [comment]
It's not my list, I'm just a fellow user trying to help you understand why the rules are applied correctly here, if read as written. (Which is the only thing these guys can do for this project to remain sane.)

So, you are equipped with a storm bolter and powerfist by default. You want the "powerfist + meltagun" which is on the melee weapon list. Thus, you can only replace the powerfist with the pf+mg. You end up with a stormbolter on one arm and a powerfist/meltagun combo on the other. Until GW publishes a FAQ that says otherwise, you are correctly FORCED to pay for the stormbolter.

**Comment by francoisbeaulieu** [comment]
There is a bug when doing it for a terminator with heavy weapon. Is that what you mean?

**Comment by NZStarlord** [comment]
yes that is what I mean, in that I replace the Power FIst with a Power
Fist, a Meltagun AND a Stormbolter, because for some reason a Storm Bolter
is lumped in with the Power Fist and Meltagun option, even though I'm
replacing it with a Heavy Weapon, in this case a Heavy Flamer​​

On Mon, Jun 19, 2017 at 8:36 AM, François Beaulieu <notifications@github.com

**Comment by francoisbeaulieu** [comment]
Ok, that wasn't clear; you never mentioned the heavy weapon. See #162 looks like it's already been fixed.
