### ISSUE TITLE
Grey Knights Librarian

### ISSUE THREAD

**Issue by new-neon** [BSData/wh40k-9e#163]
**File/Catalogue:**  Grey Knights v1

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Description:** Grey Knight Librarian in Terminator Armor has a wrong psyker rule. He must has next rule: "This model can attempt to manifest two psychic powers in each friendly Psychic phase, and sttempt to deny one psychic power in each enemy Psychic phase. It knows the Smite power and two psychic powers from the Sanctic disipline." And he mast can choose 2 powers from Sanctic.

**Comment by tekton** [comment]
That's an easy one to fix; thanks for the heads up!

**Comment by tekton** [comment]
Grand Master had a similar issue it would seem. Getting both fixed.
