### ISSUE TITLE
No possible to create complex detachments

### ISSUE THREAD

**Issue by new-neon** [BSData/wh40k-9e#164]
**File/Catalogue:** Warhammer 40k 8ed v3

**BattleScribe version:** 2.01.02

**Platform:** Windows/Android

**Dropbox:** Yes

**Description:** I did not find possibilities create complex detachments, for example: Imperium detachment or Tyranid detachment witch consists from units with only this Faction Keyword.

**Comment by Owlsbane** [comment]
Have a look here (#77), it explains how to make complex detachments.

**Comment by Kohato** [comment]
What owl said. It is quite possible.

**Comment by new-neon** [comment]
Ou, thank you, sorry for stupid issue.
