### ISSUE TITLE
Imperium - Adeptus Mechanicus

### ISSUE THREAD

**Issue by new-neon** [BSData/wh40k-9e#165]
**File/Catalogue:** Imperium - Adeptus Mechanicus v3

**BattleScribe version:** 2.01.02

**Description:** 
1) Skitarii Rangers and Skitarii Vanguards have incorrect counting for maximum specials (when you add or remove specials you have incorrect messages).
2) Minimal count of Skitarii Rangers and Skitarii Vanguards with standard weapon must depend on how many models with special weapons.

Note: For avoid this problems you can look how it implemented in GreyKnights or Drukhari catalog for example.

**Comment by Thairne** [comment]
I know how to fix that, thank you ;)
