### ISSUE TITLE
Imperium - Space Marines: Tac squad size issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#168]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** when adding marines with heavy or special weapons to tactical squads, there's an error message that says there are too many of the option in question (maximum 0).

**Comment by Kohato** [comment]
Update data. This is fixed.
