### ISSUE TITLE
Astra Militarum - Company commander has no Power Level

### ISSUE THREAD

**Issue by edward3h** [BSData/wh40k-9e#17]
**File/Catalogue:** ./Warhammer 40,000 8th Edition/Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02.89

**Platform:** Mac

**Dropbox:** No

**Description:** Company commander has no Power Level

**Comment by FarseerVeraenthis** [comment]
referring to #6 @alphalas is working through the problems with this CAT.

**Comment by alphalas** [comment]
Rolled into #6
