### ISSUE TITLE
Broken line breaks in Power from Pain and Combat Drugs special rules description

### ISSUE THREAD

**Issue by voroneril** [BSData/wh40k-9e#171]
File/Catalogue: Aeldari - Drukhari.cat

BattleScribe version: 2.01.

Platform: Windows

Dropbox: No

Description:  Broken line breaks in Power from Pain and Combat Drugs special rules description
Screenshot:
![view roster_ coven roster warhammer 40 000 8th edition v3 2017-06-18 15 11 51](https://user-images.githubusercontent.com/15366201/27260584-900fe780-5438-11e7-8e14-1731868d1f6d.png)

**Comment by Kohato** [comment]
Known.  Bs bug, not a data bug. Pending fix from Jon.
