### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by wfeijen** [BSData/wh40k-9e#172]
**File/Catalogue:**  

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** Yes

**Description:** I play Necron, Tyranid and Tau. Building a Chaos army. I have proper understanding to make small changes and the sense to leave bigger changes to the more advanced contributers. So I would like to help.

Additional question: small changes like adding a proper header or changing a weapon cost - do they need a Issue or can I repair them on the fly with proper comment on check in?

**Comment by amis92** [comment]
Hi, in the new 40k repository we do not give write access to anyone except Core Team - if you want to contribute, communicate with us on gitter and through issues and push changes as Pull Requests from your own fork. See [Getting Started 3rd bullet](https://github.com/BSData/bsdata/wiki#getting-started).
