### ISSUE TITLE
Chaos Space Marines: Unable to select Berzerkers as Troops

### ISSUE THREAD

**Issue by daoc2k** [BSData/wh40k-9e#173]
File: Chaos - Chaos Space Marines.catz
BattleScribe version: 2.01.02
Platform: Android
Dropbox: Yes
Description: World Eaters option to take Khorne Bezerkers as Troops not available

**Comment by cartag** [comment]
Add "Legion" under No Force Org slot, then check World Eaters. Same routine as 7th edition, not much different here.
