### ISSUE TITLE
Chaos - Chaos Space Marines: Maulerfiend has too many lasher tendrils

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#174]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** Yes

**Description:** I believe the maulerfiend replaces the magna cutters with lasher tendrils. It doesnt say 2 lasher tendrils it seems intended to be replacing both cutters. So you would pay 12 pts for the lasher tendrils for a total Maulerfiend cost of 161. Having 2 sets of lasher tendrils would give a maulerfiend a ridiculous amount of attacks in combat his base +2d6 which i dont think its the intent.

**Comment by cartag** [comment]
This has already been updated. It may be in the file I just uploaded, or one previously, but it's been updated.
