### ISSUE TITLE
Drukhari point cost issues

### ISSUE THREAD

**Issue by voroneril** [BSData/wh40k-9e#178]
**File/Catalogue**: Aeldari - Drukhari.cat
**BattleScribe version**: 2.01.02
**Platform**: Windows/iOS/Android/Mac/Linux
**Dropbox**: No

**Description**:
Point Cost of Haemonculus Tools for Haemonculus is "0" should be - "1"
Point Cost of Macro-Scalpel for Talos is "8" should be - "4"
Pull request with fix - https://github.com/BSData/wh40k/pull/170

**Comment by Toreador13** [comment]
Fixed.
