### ISSUE TITLE
Aeldari Ynnari Force Orgs have no unit options - show only HQ choices

### ISSUE THREAD

**Issue by Miyth** [BSData/wh40k-9e#18]
**File/Catalogue:** Aeldari - Ynnari v1

**BattleScribe version:** 2.00.

**Platform:** iOS

**Dropbox:** No

**Description:** 
Right now, when making a new Ynnari force, detachments can be selected normally, but those detachments only have the 3 native HQ choices (Yvraine, the Visarch, the Yncarne). There is no flow to create mixed detachments of Aeldari / Druhkari / Harlequins using the Ynnari heroes.

**Comment by FarseerVeraenthis** [comment]
The Ynnari CAT is not ready yet. It should be available either later today or early tomorrow.

NOTE: if you actually want Aeldari Soup rather than a Ynnari Army you can add multiple factions to a detachment

**Comment by Miyth** [comment]
Noted- thanks for the update!
I appreciate the tip about Aeldari soup- the flow for that is strange, but it makes sense in hindsight.

(Note for others trying to puzzle through this flow: Create a Ynnari detachment, then create another Aeldari detachment in that force.  When it asks for a parent force, select the Ynnari detachment instead of the force. This creates a detachment nested under the primary that counts towards the requirements of the parent detachment.)

**Comment by FarseerVeraenthis** [comment]
This should be good to go, the full ynnarii cat was released yesterday.
