### ISSUE TITLE
Imperium - Astra Militarum: Validation error in Vanguard detachment

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#186]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** No

**Description:** The Vanguard detachment incorrectly validates the number of HQ choices.  The validation message states that the maximum is 2, but the message appears starting with simply any HQ selection (i.e. 1 or more).  Once I add the first HQ choice it lists the validation error, "Imperium - Astra Militarum v8 (Vanguard Detachment +1CP) has 1 too many selections from HQ (maximum 2)".

**Comment by alphalas** [comment]
make sure you're running latest BS, delete and redownload data
