### ISSUE TITLE
Incorrect Points on Necron Immortals

### ISSUE THREAD

**Issue by Salynne** [BSData/wh40k-9e#187]
**File/Catalogue:** 
Necrons.cat

**BattleScribe version:** Latest as of this post.

**Platform:** Windows

**Dropbox:** No

**Description:** The Necron Immortals entry is charging for an extra gun to start with for some reason. It lists 5 models but selecting either Gauss Blaster or Tesla Carbine starts at 54 points. 9 times 5 is 45. A maxed out squad of 10 ends up being 9 points more than it really is, showing 99 points for 10 weapons.

**Comment by raptor1770** [comment]
Close #202 
Same as issue #194

**Comment by raptor1770** [comment]
Same as issue #194
