### ISSUE TITLE
Admech: Non-functional special weapon choices

### ISSUE THREAD

**Issue by robinlindberg** [BSData/wh40k-9e#188]
**File/Catalogue:** Adeptus Mechanicus

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** No

**Description:** 

The index states that Skitarii vanguard and ranger units start at 5 models and that at that size up to 2 models may switch to special weapons. I.e. you could have 1 alpha, 2 regular rangers and 2 rangers with Arc Rifles.

This is impossible to at this time. The setting for amount of rangers has a minimum of 4, so if one adds a special weapon ranger, the unit size becomes 6. It is at that point not possible to lower the amount of normal rangers since the minimum value of that control seems to be 4.

If one removes a model from the roster view you get a warning that you have too few rangers in the squad, although you have 5 if you count them in the rooster view.

Adding special weapons works great for servitors for example, but with rangers and vanguard the cost of the model itself is not included. It is also not counted as a model in the unit, Since I can add infinite amount of special weapons without hitting the max limit for the unit.

Another good thing with the servitor example is that it is much easier to remove models, once added. With the current solution for rangers with just a button, you have to go to the roster view, mark and remove for each model. With the servitors you can remove several at once by just entering 0.

**Comment by Thairne** [comment]
Already fixed.
