### ISSUE TITLE
Imperium - Space Marines: Tac squad size error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#197]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** No

**Description:** The Tactical Squad entry is giving an "Invalid" error.  
When trying to put in a full 10-man squad, I clicked on the option for a Heavy and a Special Weapon.
So my overall unit count is 7 Marines, 1 Sgt, 1 Heavy, 1 Special - 10 Marines.  But I get the error saying I have "1 too many selections ..." of both the heavy and special weapon marines.
If I up the basic Marine count to 8 marines (11 marines total) those errors go away, but then I get a "Tactical Squad has 1 too many selections of Space Marines ...).
I'm guessing the Sgt isn't being counted against the 10 Marine total properly?

**Comment by raptor1770** [comment]
This looks like a legit issue. Working now.
