### ISSUE TITLE
Assumed Amendments

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-9e#2]
_From @GenWilhelm on June 5, 2017 23:11_

Whilst working on the data files, the authors have noticed some peculiar things thing that we assume are going to be amended with the official release of 8th edition.

| Location | Assumed Amendment |
| --- | --- |
| Imperium 1  | Twin Icarus Lascannon should be Heavy **2** |
| Imperium 2 (p78)  | ~~First row of damage table should be **6**-11+~~  |
| Imperium 2 (p94) | ~~Celestine should be maximum 1 per army~~ |
| Imperium 1 (p203) | ~~Terminus Ultra not specifying if it's points include wargear (assumed resolution - it doesn't * )~~ |
| Imperium 1 (unknown) | Space Wolf Skyclaws don't have Jump Packs listed in their wargear. I'm assuming this is a mistake given the content of the rest of the datasheet|
| Xenos 1 (p21 & p22) | ~~What happens when a Warlock Conclave that numbers between 4 and 6 models casts Smite? 1-3 = one mortal wound, 7-10 = D6 mortal wounds, nothing noted for 4-6. Should be D3?~~ |
| Xenos 2 (pg132) | ~~Unit size of Runtherd (1-3) differs from datasheet (1). Side with the Dataslate (1)~~ |
| Xenos 2 (pg132) | ~~Unit size of Deffkopta (1-3) differs from datasheet (1-5). Side with the Dataslate (1-5)~~ |
| Xenos 2 (pg 28) | Deffkopta's Kustom Mega-Blasta has a slightly different wording than other instances of that weapon, and the profile on pg134. I assumed it was the same as other instances of that wargear. |
| Xenos 1 (pg No. Unknown) | ~~Hellions do not have a keyword preventing them boarding transports (they are Drukhari Infantry). I assume this is an error and they will be given the "Jet Pack" special rule or something similar. Either that or the Venom / Raider Transport text will be updated to disallow keyword FLY or similar.~~ |
| Imperium 1 (pg 220) | ~~The unit size of Deathwatch Bikers in the points list (1-5) differs from the unit size in the dataslate (3-6).  I went with the dataslate (3-6).~~  |
| Imperium 1 (pg 220) | ~~The unit size of Deathwatch Vanguard Vets in the points list (1-5) differs from the unit size in the dataslate (5-10).  I went with the dataslate (5-10).~~  |
| Imperium 1 (pg 220) | ~~The unit size of Deathwatch Terminators in the points list (1-5) differs from the unit size in the dataslate (5-10).  I went with the dataslate (5-10).~~  |
| Imperium 1 (pg unknown, Dark Angels section) | ~~The Nephalim Jetfighter datasheet lists the "Blacksword Missile Launcher" as being Heavy 1, but the ranged weapons wargear list lists it as Heavy 10. Assumed to be Heavy 1.~~ |
| Imperium 1| ~~Deathwing terminators can replace all weapons with a selection of options, e.g. twin lighting claws. They then can take an item from the heavy weapons list. You end up with a lightning clawed terminator that also wields an assault cannon. In earlier versions you had to replace your storm bolter, however this restriction just is not there anymore.~~ |
| Index Imperium 1 pg 40 (and various other locations) | ~~Lightning Claws - combi-bolter may be swapped for 1 lightning claw, then power fist may be swapped for another. Single lightning claws are 9pts but a pair is only 13pts. Even though these are equipped individually, once finished the model is equipped with a pair of LCs so 13pts seems the most likely cost.~~ |
| Index Xenos 1 | Lelith Hesperax has a weapon option in her profile. Her points cost is listed as including wargear. Would she add 5 points for taking an Impaler? My assumption is no as the impaler and penetrating blades seem about equal. |
| Index Xenos 1 | ~~The Ravager's Night Shield does not have the restriction to Ranged Weapons only. Given that every other instance of Night Shield does, this is probably a typo. The Drukhari cat includes the restriction.~~  |
| Index Xenos 1 | ~~RAW, the Acothyst in a unit of Wracks can take Tools of Torment. However, Tools of Torment states you must replace a ranged weapon, which the Acothyst does not have. Assume that he must replace his Haemonculus tools instead?~~ |
| FW Chaos Index Pg 54 | ~~Spined Chaos Beast lists different powers for Khorne and Tzeentch keywords than are listed in datasheet. Assumed Khorne gets Unstoppable Ferocity instead of BftBG and Tzeentch gets Ephemeral Form instead of Architects of Fate, neither of which are listed in the book.~~ |

---

Template for posting others:

```
| Location | Assumed Amendment |
| --- | --- |
| BOOK-AND-PAGE | DESCRIBE-HOW-TO-FIX |
```
---

* Updated 26/06/2017 to collect updates into one table.
* Updated 02/07/2017 for 2nd July Errata.

_Copied from original issue: BSData/wh40k-7th-edition#3748_

**Comment by amis92** [comment]
@flakpanda reported

| Location | Assumed Amendment |
| --- | --- |
| Imperium 1 (p203) | Terminus Ultra not specifying if it's points include wargear (assumed resolution - it does**n't** * ) |

\* bold edit per @flakpanda 's [comment below](https://github.com/BSData/wh40k/issues/3748#issuecomment-307000012)

**Comment by amis92** [comment]
Possibly http://natfka.blogspot.com/2017/06/new-community-40k-rules-and-questions.html#comment-3341615009

>The Infantry Squad has 9 guardsmen and a sergeant. Two of the guardsmen form a Heavy Weapon Team. Now, the heavy weapons teams in the heavy weapons squads have 1 lasgun and 1 heavy weapon... but there's no mention in the Infantry Squad of the loadout on the Heavy Weapon Team. This leads to two RAW arguments, one that they have 2 lasguns, one that they have 0, and one RAI argument that they have 1 lasgun. In need of Errata.

**Comment by amis92** [comment]
_From @FarseerVeraenthis on June 6, 2017 21:25_

| Location | Assumed Amendment |
| --- | --- |
| Xenos 1 (p21 & p22) | What happens when a Warlock Conclave that numbers between 4 and 6 models casts Smite? 1-3 = one mortal wound, 7-10 = D6 mortal wounds, nothing noted for 4-6. Should be D3? |

**Comment by amis92** [comment]
@FarseerVeraenthis `Assumed Amendment` should suggest the *amendment* to be made, so I guess in this case D3 ?

**Comment by amis92** [comment]
_From @tag8833 on June 7, 2017 16:9_

| Location | Assumed Amendment |
| --- | --- |
| Xenos 2 (pg132) | Unit size of Runtherd (1-3) differs from datasheet (1).  Side with the Dataslate (1) |
| Xenos 2 (pg132) | Unit size of Deffkopta (1-3) differs from datasheet (1-5).  Side with the Dataslate (1-5)  |
| Xenos 2 (pg 28) | Deffkopta's Kustom Mega-Blasta has a slightly different wording than other instances of that weapon, and the profile on pg134.  I assumed it was the same as other instances of that wargear. |

**Comment by amis92** [comment]
@tag8833 I'll disagree as to the assumed amendment.

Runtherd is clearly a single model unit. It says so on dataslate (in every instance the reference is "this model", description says "Runtherd is a single model [...]") and additionally he has the **Character** keyword (which only single model units have). I'd actually go with datasheet. Same with Deffkoptas (go with datasheet), but here we agree.

**Comment by amis92** [comment]
_From @tag8833 on June 7, 2017 21:31_

@amis92 Fair enough.  I'll make the Runtherd change.  I'm out voted.

**Comment by amis92** [comment]
_From @flakpanda on June 8, 2017 5:9_

I am assuming that Terminus Ultra **does not** include wargear costs based on other Lord of War entries.

**Comment by amis92** [comment]
_From @FarseerVeraenthis on June 8, 2017 9:27_

| Location | Assumed Amendment |
| --- | --- |
| Xenos 1 (pg No. Unknown) | Hellions do not have a keyword preventing them boarding transports (they are Drukhari Infantry). I assume this is an error and they will be given the "Jet Pack" special rule or something similar. Either that or the Venom / Raider Transport text will be updated to disallow keyword FLY or similar. |

**Comment by amis92** [comment]
_From @tag8833 on June 8, 2017 20:32_

| Location | Assumed Amendment |
| --- | --- |
| Imperium 1 (pg 177) | The Corvus Blackstar has an ability "Blackstar Cluster Launcher" that describes equipment that isn't listed  |
| Imperium 1 (pg 220) | The unit size of Deathwatch Bikers in the points list (1-5) differs from the unit size in the dataslate (3-6).  I went with the dataslate (3-6).  |
| Imperium 1 (pg 220) | The unit size of Deathwatch Vanguard Vets in the points list (1-5) differs from the unit size in the dataslate (5-10).  I went with the dataslate (5-10).  |
| Imperium 1 (pg 220) | The unit size of Deathwatch Terminators in the points list (1-5) differs from the unit size in the dataslate (5-10).  I went with the dataslate (5-10).  |

**Comment by amis92** [comment]
_From @DirtDiglett on June 9, 2017 1:26_

@tag8833 The Blackstar Cluster Launcher is not equipment, it is a self-contained ability. It includes how it is activated, the damage it does, etc. When it references the Blackstar Cluster Launcher in its description it is referring to itself.


| Location | Assumed Amendment |
| --- | --- |
| Imperium 1 (pg unknown, Dark Angels section) | The Nephalim Jetfighter datasheet lists the "Blacksword Missile Launcher" as being Heavy 1, but the ranged weapons wargear list lists it as Heavy 10. Assumed to be Heavy 1. |

**Comment by amis92** [comment]
_From @tag8833 on June 9, 2017 4:1_

@DirtDiglett It is listed as "Other Wargear" in the points list:
![image](https://user-images.githubusercontent.com/17749311/26960508-8b68f656-4c9d-11e7-99e5-71e7262f91d2.png)

The ability:  
![image](https://user-images.githubusercontent.com/17749311/26960598-1bb4c42e-4c9e-11e7-8768-04481e09f6cd.png)

It referenced wargear by the same name as the ability.  For contrast, consider the Auspex ability right below it.  That has defined wargear, and rules for taking it.  I think the best assumption is that the Blackstar does indeed come with exactly 1 Blackstar Cluster Launcher and has no ability to take more.

**Comment by amis92** [comment]
_From @Thairne on June 11, 2017 12:22_

| Deathwing Terminators| Heavy weapon selection |
| --- | --- |
| Imperium 1| Deathwing terminators can replace all weapons with a selection of options, e.g. twin lighting claws. They then can take an item from the heavy weapons list. You end up with a lightning clawed terminator that also wields an assault cannon. In earlier versions you had to replace your storm bolter, however this restriction just is not there anymore. |

**Comment by amis92** [comment]
_From @GitArdnutz on June 12, 2017 11:7_

| Location | Assumed Amendment |
| --- | --- |
| Index Imperium 1 pg 40 (and various other locations) | Lightning Claws - combi-bolter may be swapped for 1 lightning claw, then power fist may be swapped for another. Single lightning claws are 9pts but a pair is only 13pts. Even though these are equipped individually, once finished the model is equipped with a pair of LCs so 13pts seems the most likely cost. |

**Comment by amis92** [comment]
_From @Toreador13 on June 15, 2017 17:19_

| Location | Assumed Amendment |
| --- | --- |
| Index Xenos 1 | Lelith Hesperax has a weapon option in her profile. Her points cost is listed as including wargear. Would she add 5 points for taking an Impaler? My assumption is no as the impaler and penetrating blades seem about equal. |

**Comment by ilaunchbury** [comment]
| Location | Assumed Amendment |
| --- | --- |
| Index Xenos 1 | The Ravager's Night Shield does not have the restriction to Ranged Weapons only. Given that every other instance of Night Shield does, this is probably a typo. The Drukhari cat includes the restriction.  |

**Comment by CorruptedValor** [comment]
On Ynnari, Drukhari Raiders and Venoms are not listed as transport options. I assume they should be as they do not have to have the humonculous coven keyword, it's just an option.

**Comment by GenWilhelm** [comment]
@CorruptedValor this is not the appropriate place to report such an issue, this is a list of issues in the indexes that we assume are going to be amended by GW.

The bug you are reporting has already been noted, and can be followed in issue #113.

**Comment by CorruptedValor** [comment]
My apologies, I misunderstood the section head, and only checked that it
wasn't already reported in that section. I will make sure to report in the
correct section in future.

**Comment by cartag** [comment]
| Location | Assumed Amendment |
| --- | --- |
| FW Chaos Index Pg 54 | Spined Chaos Beast lists different powers for Khorne and Tzeentch keywords than are listed in datasheet. Assumed Khorne gets Unstoppable Ferocity instead of BftBG and Tzeentch gets Ephemeral Form instead of Architects of Fate, neither of which are listed in the book. |

**Comment by amis92** [comment]
See #418 for a list of bugs for T'au Empire in Forge World's Imperial Armour Index: Xenos.

**Comment by ilaunchbury** [comment]
| Location | Assumed Amendment |
| --- | --- |
| Death Guard | Sorceror on Palanquin of Nurgle technically still uses Dark Hereticus powers as it wasn't updated in the Codex. However, it can reasonably be assumed it should use Contagion like all the other Death Guard psykers.|

**Comment by amis92** [comment]
There's a new obvious typo in SM Codex:

| Location | Assumed Amendment |
| --- | --- |
| Codex: Space Marines p172 | Devastator Squad Sergeant has an option that reads: `The Space Marine Sergeant may replace his boltgun with *items* from the Sergeant Equipment list.` It's an obvious typo which should be corrected to `an item`, in line with all other models that replace single weapon for item from Sergeant Equipment. |
