### ISSUE TITLE
Battle Sisters PL doesn't increase when I add squad members

### ISSUE THREAD

**Issue by edward3h** [BSData/wh40k-9e#205]
**File/Catalogue:** Imperium - Adeptus Ministorum

**BattleScribe version:** 2.01.02.89

**Platform:** Seen on Android & Mac

**Dropbox:** Yes

**Description:** I add a Battle Sisters squad - it has PL 4. I add more Battle Sisters to the squad - the PL should increase to 8 for up to 10 models (12 for up to 15 models) but it stays as 4.

**Comment by raptor1770** [comment]
This looks like a legit issue. Working now.
