### ISSUE TITLE
Imperium - Astra Militarum: Ministorum and Admech units missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#207]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Astra Telepathica and Adeptus Mechanicus units do not appear in the Astra Militarum list even though they have the Astra Militarum keyword.

**Comment by raptor1770** [comment]
I believe #77 solves this issue.

**Comment by alphalas** [comment]
@raptor1770  is correct - the cats are set up like the index.
