### ISSUE TITLE
[Implementation] SM Crusader Squad; Collective Chainswords

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-9e#209]
**File/Catalogue:** Imperium - Space Marines CAT / Warhammer 40K GST

**BattleScribe version:** 2.01.

**Platform:** Windows/Android

**Dropbox:** No

**Description:**
Chainsword entry in units should be collective. Currently, in Crusader Squad and Assault Squad, models with chainsword are listed individually while models with boltguns are listed collectively. 

Models with chainsword in these units have no other options, so they should be presented collectively (I think that's what the implementation
guidelines say) via a +/- spinner instead of a +Add button.

**Comment by GitArdnutz** [comment]
There are a few other units that would benefit from similar treatment - particularly Assault Terminators (only 2 types of model, so a couple of +/- spinners are a lot easier than individually adding & equipping up to 10 models).
