### ISSUE TITLE
Astra Militarum: Special Weapon Scion also has volley gun

### ISSUE THREAD

**Issue by blackrabbit84** [BSData/wh40k-9e#218]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

Militarum Tempestus Scions. When trying to equip troops with a special weapon such as a melta, the hot shot volley gun is not automatically removed, resulting in an error of the troop being equipped with 2 special weapons

**Comment by fejjn** [comment]
+1 on this.

**Comment by BitterLies** [comment]
Are you unable to 'uncheck' the Volly gun?  I was able to, and there is no more validation error.

**Comment by alphalas** [comment]
just uncheck the volley gun

**Comment by blackrabbit84** [comment]
Yeah they fixed it niw
