### ISSUE TITLE
Imperium/Chaos

### ISSUE THREAD

**Issue by KealL** [BSData/wh40k-9e#220]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
Is there a plan to make a linked cat for like all the imperium, and another for all of Chaos?

**Comment by Thairne** [comment]
Nope.
You can do that via multi-faction detachments.
