### ISSUE TITLE
Astra Militarum: Special weapon Scion also has volley gun 

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#222]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** No

**Description:** Mititarum tempestus scions - no selections for hot-shot lasgun, unselectable hot-shot volley gun in scions with special weapon

**Comment by alphalas** [comment]
duplicate #218
