### ISSUE TITLE
Bug Report: Thousand Sons

### ISSUE THREAD

**Issue by IngemarSkelander** [BSData/wh40k-9e#225]
File: Thousand Sons.catz

BattleScribe version: 2.01.02

Platform: Windows

Dropbox: No

Description: If I'm not mistaken, this whole catalogue is invalid in 8th, it should be merged with Chaos Space Marines

**Comment by cartag** [comment]
Nevermind the fact that it was created new for 8th edition. Thousand Songs and Death Guard both have their own army list in the index, life loyalist chapters do that also stand alone. 

Basically, you're mistaken.
