### ISSUE TITLE
Imperium - Adeptus Mecanicus Errors

### ISSUE THREAD

**Issue by AbsoluteManiac** [BSData/wh40k-9e#227]
Bug Report - Adeptus Mechanicus 

BattleScribe version: 2.01.

Platform: Android

Dropbox: No

Skitarii are still bugged, special weapons are being added as squad members at the cost of only the weapon. Additionally will not allow 3 special weapons in squads of 10

**Comment by Thairne** [comment]
![grafik](https://user-images.githubusercontent.com/8590840/27279348-a52c33ce-54e4-11e7-97c2-434ac9660490.png)

STILL fixed with v5.
