### ISSUE TITLE
Bug Report - Warhammer 40000 8th Edition - Space Marines

### ISSUE THREAD

**Issue by darkhoras** [BSData/wh40k-9e#229]
**File/Catalogue:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** No

**Description:** Detailed issue description.
When I select 10 Marines and add Heavy and Special, I receive information that "too many space marines"
![photo5927183159609370822](https://user-images.githubusercontent.com/19798370/27281113-26aba426-54f3-11e7-99aa-9192914cb032.jpg)

When I decrease number to 7, I receive information that I cannot select Heavy and Special marines:
![photo5927183159609370823](https://user-images.githubusercontent.com/19798370/27281146-40066b04-54f3-11e7-956a-f93bb5624c7e.jpg)

**Comment by Kohato** [comment]
This has been fixed. Update data.
