### ISSUE TITLE
Dark Angels - Ravenwing Land Speeders - MM

### ISSUE THREAD

**Issue by Randobar** [BSData/wh40k-9e#230]
Dark Angels v1

Both Multi-Melta Options are added to all Speeders in the squad, not just the one it is selected for.

**Comment by Randobar** [comment]
guess my update failed then.

**Comment by Thairne** [comment]
Yes and nope, this issue is legit ;)

**Comment by Randobar** [comment]
yeah, just updated correct and still get the problem :)
