### ISSUE TITLE
Astra Militarum v12- Consolidated list of errors

### ISSUE THREAD

**Issue by bowgs** [BSData/wh40k-9e#231]
**File/Catalogue:** Imperium - Astra Militarum v12

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** 

### Knight Commander Pask
- [x] Can select multiple battlecannons and the price is wrong (30 instead of 22)- take this away and make the command battle tank default option cost 22 pts
Interestingly the tank commander looks to be set up correctly, so maybe copy that.

### Infantry Squad
- [x] Heavy bolter should be 8pts (currently 10)
- [x] Sniper rifle should be 2pts ( currently 4)

### Special Weapons Squad
- [x] Sniper rifle should be 2 pts (currently 4)
- [x] Demo charge should not be default for the 3 guys with special weapons

### Conscripts 
- [x] Conscripts need to be grouped (people tend to run these in 30-50 man squads, and they don't have any options) and you can give them multiple lasguns - take away the selection box and just give them 1 lasgun by default

### Bullgryns 
- [x] if you swap the grenadier gauntlet for a bullgryn maul it gives an error saying needs one more selection of grenadier gauntlet

### Militarum Tempestus Scions  
- [x] gives an error when you give a special weapon guy a special weapon because it doesn't take away the volley gun - take away the default volley gun and add it to the list of special weapon options
- [x] group up the regular guys with hotshot lasguns
- [x] regular scions should be 10 pts, not 9 (1pt for hotshot lasgun)
- [x] why is there a frag and krak grenade option?

### Militarum Tempestus Scions Command Squad
- [x] Each scion has the option to take multiple hotshot lasguns, rather than there being one box for the whole squad, or a checkbox for each man
- [x] Scion with medi pack should be 20 pts (9 base, 10 medi pack, 1 hotshot laspistol)
- [x] Scion with voxcaster should be 15 pts (9 base, 5 vox caster, 1 hotshot lastpistol)

### Taurox Prime
- [x] Defaults to none as the hull mounted option - this isn't valid.  The option disapears once you select something else, but it shouldn't be there in the first place.  The default should be two hotshot volleyguns
- [x] Defaults to none as the turrent weapon - this isn't valid. The option disapears once you select something else, but it shouldn't be there in the first place. The default should be taurox battle cannon
- [x] Two hotshot volley guns should cost 18pts, rather than 9
- [x] Two autocannons should cost 30pts, not 15

### Heavy Weapons Squad 
- [x] Heavy bolter should be 8pts not 10

### Rough Riders
- [x] Regular rough riders have options for chainswords and laspistol.  The boxes don't work properly, (they actual multiply by the number of men, so adding 4 chainswords to 4 rough riders results in 16 chainswords) and don't need to be there as this is default equipment that can't be changed.

### Command Squad
- [x] Command squads are being included as HQ slot even though in Elites section.  It also counts as an elite, so it takes up an elite choice and an HQ choice.
- [x] Command squad heavy weapon counts as 1 person where it should count as 2.  You cannot validate your squad with a heavy weapon team included - it either says you have too many veterans or not enough.  This same bug has been fixed on the Infantry Squad.
- [x] Heavy Bolter should be 8pts

### Veterans
- [x] Heavy Bolter should be 8pts
- [x] Sniper Rifle should be 2pts

### Armoured sentinal  
- [x] Explodes rule incorrect. It is not the same as the general explodes. It should be units within 3" take 1 mortal wound.

### Commissar 
- [x] Bolt pistol needs to be default, bringing total cost to 31

### Lord Castellan Creed 
- [x] His points cost is supposed to be 70pts including wargear. hes currently listed as 80points.

### Nork Deddog 
- [x] His points cost is supposed to be 80pts including wargear. hes currently listed as 85points

### Valkyrie 
- [x] hull weapon - lascannon listed at 25 pts should be 20 points

**Comment by fejjn** [comment]
Isnt the price wrong for Taurox Prime Autocannons too? 2x15 (because 2 autocannons?)

**Comment by bowgs** [comment]
> Isnt the price wrong for Taurox Prime Autocannons too? 2x15 (because 2 autocannons?)

Yes, the price of the 2 volleyguns is wrong as well, I've added these to the list, and taken off the ones that were fixed in v12, and renamed the issue to reflect that these are still issues in v12.

**Comment by wismeril** [comment]
On windows, add more than 20 conscripts did not change the point cost.
Still stay at 60pts.

**Comment by Coomakazie** [comment]
Command squad heavy weapon counts as 1 person where it should count as 2.

Command squads are being included as HQ slot even though in Elites section.

**Comment by bowgs** [comment]
> On windows, add more than 20 conscripts did not change the point cost.
Still stay at 60pts.
I can't recreate this on version 12, it behaves as expected so I'm not going to add this to the list

> Command squads are being included as HQ slot (ie they count towards your HQ allowance) even though in Elites section.
Good spot, added to the list
> Command squad heavy weapon counts as 1 person where it should count as 2.
This same bug has been fixed in the infantry squad so hopefully it's a quick fix.  I've added it to the list with a bit more detail

**Comment by wismeril** [comment]
> I can't recreate this on version 12, it behaves as expected so I'm not going to add this to the list
I've create au new roaster, it work's correctly.

With many upgrades, may be old roasters are bugged

**Comment by Coomakazie** [comment]
Also command squad heavy Bolter at 10 points instead of 8

**Comment by bowgs** [comment]
> Also command squad heavy Bolter at 10 points instead of 8

I've updated the original post with this and a couple of other cost issues (mainly with veterans)

**Comment by alphalas** [comment]
@bowgs is everything from #189 here?

**Comment by bowgs** [comment]
@alphalas  They are now, I've just added them, the ones that are still issues at least.  A few of them seem to have been resolved already, I can't recreate them in V12.

**Comment by alphalas** [comment]
Bueno - thanks.

**Comment by bowgs** [comment]
@alphalas Forget that, I tried to add them but couldn't because you were editing it.  I'll add them in a comment and you can do what you want with them

**Comment by alphalas** [comment]
jut add them now.
i swear i won't edit till you're done lol

**Comment by alphalas** [comment]
Everything currently on the list has been fixed - just waiting for your additions then i'll push and release.

**Comment by bowgs** [comment]
Done

**Comment by bowgs** [comment]
One more thing, Valkyrie needs an option to take 1 or 2 heavy bolters
