### ISSUE TITLE
Issues with making allied armies that share faction keyword(s)

### ISSUE THREAD

**Issue by Quiltar** [BSData/wh40k-9e#238]
**File/Catalogue:** 
All of them? (more or less)

**BattleScribe version:** 
2.01.02 (also tried the stable version. not change)

**Platform:** 
Windows (10, 64bit)

**Dropbox:** : 
Have it, but not using it for Bscribe (for now)

**References.**:
8th edition, Rulebook page 240, factions info box (with the red\black marine on it)

**Description:** 
This is maybe more a missing feature, but it affects lists building, so I'll call it a bug.
(please read to the end).

When making a detachment (any of the ones found in the rule book) for matched play, it is possible and legal to make a detachment with say, 1 hq : space marine captain, and 2 troops : Astra militarum conscripts, and 1 elite : vindicare assassin.
Because they all share the < imperium > faction keyword. 

This is as of now not possible in battlescribe, since there is (as of yet) no combined imperium catalog, if I want to use battlescribe +8th catalogues to build my AM army with vindicare assassins, I'm forced to pick the auxillary (elite) detachment for each assassin. This is not as intended by the rules of 8th.

NOTE: This goes for any army that shares keywords. You'll find the same problem with say eldar. or tyranids and cults, or chaos marines \ daemons etc..

So unless I'm missing something* grand here, then as the catalogues are organized, allied armies are not possible to build properly.

* I hope I'm missing something. 
Also, I posted as a bug because I can't find a suggestion box anywhere, and your facebook page is automated, thus no replies and so on.

Cheers, and keep up the emperors work 👍

**Comment by Quiltar** [comment]
Holy crap... not five minutes after I post this I figure out my issue.. Did not realize that I could add "child" lists. Since each force I added wanted its own detachment I assumed it was broken. Terribly sorry. Closing this now.

**Comment by amis92** [comment]
Just for reference, #77 has a how to for this - in case anyone wanders there in future.
