### ISSUE TITLE
Grey knights - Interceptor Pl not increased

### ISSUE THREAD

**Issue by wismeril** [BSData/wh40k-9e#242]
**File/Catalogue:** Grey knights

**BattleScribe version:** 2.01.

**Platform:** Windows/

**Dropbox:** No

**Description:** 
Interceptor Pl not increased when when add more than 4 interceptor

Description of Psyker (Santic 1 squad) had `<br/><br/>`  in the middle of the text

**Comment by tekton** [comment]
Including this fix in my other PR; going to fix other squads I missed, too.

**Comment by amis92** [comment]
`<br/>` is a BS bug
