### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by Penallegion** [BSData/wh40k-9e#243]
#**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows
 
**Dropbox:** Yes

**Description:** Detailed issue description.
Hi i would like to help making The data files work optimal. 
I have used the data editor before.

**Comment by amis92** [comment]
Hi, in the new 40k repository we do not give write access to anyone except Core Team - if you want to contribute, communicate with us on gitter and through issues and push changes as Pull Requests from your own fork.
