### ISSUE TITLE
Dark Angels - missing Deathwing champion

### ISSUE THREAD

**Issue by Dyrnil** [BSData/wh40k-9e#248]
**File/Catalogue:** imperium - Dark Angels v4.catz

**BattleScribe version:** 2.01.

**Platform:** Windows/Android

**Dropbox:** No

**Description:** 

Missing **Deathwing champion** selection choice in the elites section

**Comment by Lobokai** [comment]
Sry, new to github. Does this mean this issue is solved next update?

**Comment by Thairne** [comment]
Yep, it should be with the most current version after appspot updates.

**Comment by Lobokai** [comment]
Thank you good sir
