### ISSUE TITLE
Imperium - Astra Militarum: Veteran squad issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#258]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** Yes

**Description:** Veteren sargent cannot select shotgun as a weapon option. Also veterans keep saying too many selections from lasgun when im using shotguns

**Comment by alphalas** [comment]
update data - Sgt can't take a shotgun because he does not have a lasgun to replace with a shotgun.
