### ISSUE TITLE
Imperium - Militarum Tempestus Points Error

### ISSUE THREAD

**Issue by AbsoluteManiac** [BSData/wh40k-9e#262]
File/Catalogue: Imperium - Astra Militarum 

BattleScribe version: 2.01.

Platform: Android 

Dropbox: No

Description:
Tempestus scion points cost is incorrect, hot shot lasgun is not included in cost 
Scion: 9pts 
Frag/krak grenades: 0pts 
Hot shot lasgun: 1pt 
Additionally frag/krak grenades are added as additional scions

**Comment by alphalas** [comment]
Duplicate of #231
