### ISSUE TITLE
Imperium - Astra Militarum: Tempestus Scions weapon validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#268]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** No

**Description:** When configuring a squad of Tempestus Scions if you add a special weapon Scion the Hot-shot Volley Gun is listed as an independent checkbox rather than in the list of radio buttons for the other special weapons.  This allows you to incorrectly select 2 special weapons for the model simultaneously.

**Comment by alphalas** [comment]
Duplicate of #231
