### ISSUE TITLE
Drukhari - Court of the archon incorrectly flagged as invalid

### ISSUE THREAD

**Issue by smacktoid** [BSData/wh40k-9e#269]
**File/Catalogue:** 
Drukhari, 40k 8th edition v3

**BattleScribe version:** 2.01.

**Platform:** iOS

**Dropbox:** Yes

**Description:**

The Court of the Archon unit in the Drukhari faction is supposed to be available whenever an Archon is used in a battle forged army. In this scenario the unit does take up a force org slot.

When this unit is added to a battle forged drukhari list an error is incorrectly flagged, reading something along the lines of
"Too many selections from elites..."

It looks like the court of the Archon is being treated as at least 1 elites choice, which is making the list invalid in the app.

**Comment by scottmmmm** [comment]
Example list to help illustrate:


[b]++ Patrol Detachment (Aeldari - Drukhari) [20 PL, 280pts] ++[/b]

[b]+ No Force Org Slot +[/b]

[b]Court of the Archon [10 PL, 146pts]:[/b] Medusae, Sslyth, Sslyth, Ur-Ghul

[b]+ HQ +[/b]

[b]Archon [4 PL, 64pts]:[/b] Huskblade, Splinter pistol

[b]+ Troops +[/b]

[b]Kabalite Warriors [3 PL, 35pts][/b]
. 4x Kabalite Warrior
. Sybarite: Splinter Rifle

[b]Kabalite Warriors [3 PL, 35pts][/b]
. 4x Kabalite Warrior
. Sybarite: Splinter Rifle

[b]++ Total: [20 PL, 280pts] ++[/b]

Created with [url=https://battlescribe.net]BattleScribe[/url]

**Comment by Toreador13** [comment]
Fixed in v4
