### ISSUE TITLE
Imperium - Astra Militarum: Missing telepathica units

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#281]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** No

**Description:** Telepathica units, Techpriest Enginseers and Ministorum Priests are not available in Militarum detachments despite having the Militarum faction keyword.

**Comment by penguin20000** [comment]
You need to add the required Child Force, see #77 on how to do it.
