### ISSUE TITLE
Chaos - Chaos Space Marines - Havoc Points Cost Issue

### ISSUE THREAD

**Issue by ViscousVortex** [BSData/wh40k-9e#285]
**File/Catalogue:** Chaos Space Marines v4

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** No

**Description::** Issue with Havoc points cost. Only first selection of any weapon adds to the points total of the unit.
Example I add a heavy bolter to the unit and it correctly adds 10 points to the unit cost. If I add a second Heavy bolter the cost doesn't increase like it should. This happens for each of the weapon choices.

**Comment by cartag** [comment]
I'm unable to duplicate this, it's working fine for me

**Comment by ViscousVortex** [comment]
After testing again with Chaos Space Marines v6, I also cannot replicate the issue.
