### ISSUE TITLE
Bug Report: Orks Wazbom Blastajets kustom force field

### ISSUE THREAD

**Issue by Horus-3-Echo** [BSData/wh40k-9e#286]
**File/Catalogue:**  Orks.cat

**BattleScribe version:** 2.01.02.89

**Platform:** Windows

**Dropbox:** No

**Description:** Wazbom Blastajets kustom force field should be like there https://www.games-workshop.com/resources/PDF/StormcloudAttack/40k-rules-wazbom-blastajet-en.pdf

**Comment by GenWilhelm** [comment]
It is there - it's an optional replacement for the Stikkbomb flinga.

**Comment by Horus-3-Echo** [comment]
I should specify more, now it says: 
All friendly ORK units that are entirely within 9" have a 5+ invul save against ranged weapons. If the Big Mek is embarked, the vehicle transporting it has a 5+ invul against ranged weapons instead.   

But in these rules it says:
Kustom Force Field: Roll a dice every time a Wazbom
Blastajet with a kustom force field loses a structure
point. On a roll of 5 or 6 the damage is absorbed by
the force field and the Blastajet suffers no damage.

**Comment by GenWilhelm** [comment]
Those rules are for Stormcloud Attack, not Warhammer 40k. The 40k index says:
"If this model is armed with a kustom force field, and friendly ORK units that are entirely within 9" have a 5+ invulnerable save against ranged weapons."

**Comment by Horus-3-Echo** [comment]
Ahhhhh, thx :-)
