### ISSUE TITLE
Drukhari - Mixed Grotesques Weapons

### ISSUE THREAD

**Issue by githubuser-riddip** [BSData/wh40k-9e#287]
**File/Catalogue:** Aeldari Drukhari v3

**BattleScribe version:** 2.01.03

**Platform:** iOS

**Dropbox:** No

**Description:** 

I added a unit with 4 Grotesques and tried to give two of them Liquifier Guns (LG) and the other two a Monstrous cleaver (MC) instead.
Now this happens: Either Battlescribe complains that I am missing a weapons selection because all Grots are without a MC, or I add the missing MC to a single Grot and suddenly all Grots get it, even the ones who already have a LG, giving them 2 weapons instead of 1.
It is not possible to give two Grots only a LG or only a MC.

![with mc](https://user-images.githubusercontent.com/29569586/27328414-65c8115c-55b2-11e7-9ca8-44ce3999f207.jpg)
![without mc](https://user-images.githubusercontent.com/29569586/27328443-72f640e2-55b2-11e7-86b2-5cc9361362ff.jpg)

**Comment by Toreador13** [comment]
Fixed in v5
