### ISSUE TITLE
Chaos - Chaos Space Marines - LOW crash

### ISSUE THREAD

**Issue by MountyChris** [BSData/wh40k-9e#288]
**File/Catalogue:** 
Chaos Space Marine v4

**BattleScribe version:** 2.01.02
Android

Hi Guys,

I'm getting a crash any time I try to add a LOW choice or Non Force Org slot to a chaos Super heavy detachment/Superheavy Auxiliary detachments.   Supreme Command Detachment allows selection of LOW fine . 

Works fine for other catalogues. 

Any ideas?

**Comment by cartag** [comment]
I can't duplicate this

**Comment by MountyChris** [comment]
No longer happening in new chaos index.
