### ISSUE TITLE
Astra Militarum v13 remaining issues

### ISSUE THREAD

**Issue by bowgs** [BSData/wh40k-9e#290]
**File/Catalogue:** Astra Militarum v13

**BattleScribe version:** 2.01.

**Platform:** Windows/Android

**Dropbox:** No

**Description:** 

Excellent progress in the last update, just a few issues remain (including a couple I hadn't spotted before, apologies).

### Scions
- [x] The number of Scions doesn't seem to add up correctly, I think it's including the Tempestor.  For instance 4 Special Weapons, 1 Vox caster and 4 hotshot lasguns is reported as 10 guys.  This means you can't take a full-strength squad (1 Tempestor and 9 Scions) without getting an error.
- [x] Because of the above you can't take 4 special weapons without getting an error (you need a full 10 man squad to get 4 special weapons, but a full 10 man squad reports as 11 so you either get an error for too many men or too many weapons).

### Special weapons
- [x] The sniper rifle is still the wrong price across the board - (infantry squad, veterans, command squad, special weapon squads, scions etc).  Should be 2pts, currently 4

### Special Weapons Squads
- [x] The non special weapons guys have laspistols instead of lasgun in their profile. Low priority as didn't affect costs or validation.

### Militarum Tempestus Command Squad
- [x] Hotshot lasgun should be 1pt, so Scions with a hotshot lasgun should be 10pts
- [x] Scion with standard should be 15 pts (9, + 1 for hotshot pistol, +5 for standard)

### Rough Riders
- [x] Shouldn't be allowed to take a sniper rifle.  This means they'll probably need their own list of special weapons, seeing as the standard AM one includes the sniper rifle.  Not a high priority issue.

### Command Squad
- [x] The veterans default to no weapon (should be lasgun) and once you select an option it says "4x veteran has 3 too many selections from lasgun (maximum 1).   I think the fix is to make the lasgun the default and put the option to swap for a laspistol and chainsword on each individual veteran, rather than the group.

### Chimera variants
- [x] Should not have the option for a hull mounted multi melta. 
- [x] None is not a valid option for hull mounted weapon in most cases, default should be heavy bolter. 

### Leman Russ Vanquisher
- [x] No sponson, pintle or turret options.

### Taurox
- [x] limited to one Taurox

### Baneblade and Hellhammer
- [x] Demolisher Cannon option has no cost.

**Comment by Coomakazie** [comment]
Still on v12 on iOS. I have updated the data but no v13 yet.

Do I have to delete previous existing data first?

**Comment by bowgs** [comment]
> Still on v12 on iOS. I have updated the data but no v13 yet.
Do I have to delete previous existing data first?

V13 is in github, but it's not on the main webpage.  You need to download from github and export it into the appropriate directory, overwriting the existing files, but I'm not on iOS so I can't help you with that.  I'm just trying to help with the testing hence why I went to the effort of manually installing it.

**Comment by Thairne** [comment]
Or you could just wait until we push a release. Then it takes a few hours to reach the public.

**Comment by Coomakazie** [comment]
I will have to wait unfortunately. I'm away from home all week and only have an iPhone to mess around with list building

**Comment by bowgs** [comment]
You could, and in most cases should, but there's been a lot of issues with this catalogue and I'm just trying to help with identifying them.

**Comment by Eerieuk** [comment]
Ill add this here make it easier to track .
Militarum Tempestous Scion minimum squad number wrong. When u add a unit as a troop choice it generates the tempestor and tells u in the bottom window " Militarum Tempestous Scions must have 3 more selections from Scions (minimum 4) . 3 scions plus 1 tempstor is only 4 models unit need to be min of 5 models

**Comment by Coomakazie** [comment]
Got v13.

issue for command squads - 'must have same selections from veterans'
I have two snipers and a mortar team as a unit.

I'm not sure what it's telling me, not enough people in squad? I think it's just a false error message.

**Comment by bowgs** [comment]
> issue for command squads - 'must have same selections from veterans'
I have two snipers and a mortar team as a unit

I can't recreate this on android, I just set up a command squad with two snipers and a mortar team and got no error - are you sure you don't have any extra veterans in there?

**Comment by Coomakazie** [comment]
Tried to recreate it in a new list and error did not come up, possibly due to moving the list from v12 to v13.

Disregard last message

**Comment by HanYoL0** [comment]
I may be misunderstanding the codex but I think there's a problem with the infantry squad, specifically the heavy bolter for the HwT.  Should it be costed at 8 points instead of 10?

**Comment by bowgs** [comment]
> I may be misunderstanding the codex but I think there's a problem with the infantry squad, specifically the heavy bolter for the HwT. Should it be costed at 8 points instead of 10?

Yes, but that issue is already fixed in v13.  V12 is the version that is currently live which is why you are still seeing this issue.

**Comment by HanYoL0** [comment]
Oh man my apologies. I updated last night, didn't realize how fast these are moving. Thanks for all the hard work!

**Comment by bowgs** [comment]
@alphalas is doing all the development, I'm just helping with the testing and co-ordinating the issues.

**Comment by alphalas** [comment]
And I really appreciate it- with all the mess the first 4 vers were, it's a huge help

**Comment by ExLibrisMortis** [comment]
When adding dedicated transports to any detachment level, there is a validation error stating that you have too many transports.

In the rules it states that you may have 1 dedicated transport per other choice in the detachment. I have attached a file showing that I have 3 veterans units selected, and 3 Taurox's, but its still showing the validation error.
[New Roster.zip](https://github.com/BSData/wh40k/files/1088803/New.Roster.zip)

**Comment by alphalas** [comment]
Make sure your data is updated and try making a new list -that sounds like a bug I fixed already

**Comment by ExLibrisMortis** [comment]
I have updated the data and its still showing.

**Comment by HanYoL0** [comment]
Ok I just updated again to be sure I was current:

The hellhammer baneblade is showing the demolisher cannon free. I think it should be 40 pts.

**Comment by bowgs** [comment]
> When adding dedicated transports to any detachment level, there is a validation error stating that you have too many transports.

I think this is specific to Taurox - I think it's limited to 1, I can take the correct amount of Chimeras.  I've added it to the list

**Comment by Coomakazie** [comment]
Ok recreated my issue of 'command squad must have same number of selections from Vetrans'

This error comes up if you have 2 command squads with different lodeouts.

I have 1 team consisting of 2 snipers and 1 heavy weapon team.
The other consisting of 1 veteran, 1 with medi pack, 1 with regimental standard, and 1 with vox caster.

I think the error is to do with having 1 command squad with options from the top block and another with options from the second block.

**Comment by ExLibrisMortis** [comment]
When you add wyverns they don't automatically choose a hull weapon. The default should be a heavy bolter like almost every other chimera chasis vehicle.

**Comment by bowgs** [comment]
I already have that as an issue under Chimera Variants

**Comment by ExLibrisMortis** [comment]
Yup, looked over that, thanks!
