### ISSUE TITLE
Ynnari "Combat Drugs" Force Rule?

### ISSUE THREAD

**Issue by KalChoedan** [BSData/wh40k-9e#291]
**File/Catalogue:** Aeldari Ynnari v5

**BattleScribe version:** 2.01.

**Platform:** Windows/

**Dropbox:** No

**Description:** 
All selections from the Ynnari list are erroneously showing as having "Combat Drugs" as a Force Rule. Example, an empty Patrol Detachment:
![image](https://user-images.githubusercontent.com/1786901/27331788-d76f87a0-55b6-11e7-91ec-5cfb6a967bae.png)

**Comment by FarseerVeraenthis** [comment]
closed with #308
