### ISSUE TITLE
Bug - Imperium - Astra Militarium - Hellhound Variants error

### ISSUE THREAD

**Issue by Eerieuk** [BSData/wh40k-9e#307]
**File/Catalogue:** Astra Miltarum v17

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** no

**Description:** Hellhound variants

**Bane wolf, Devil Dog and Hellhound**  - All 3 variants have the option to select a multimelta as hull weapon. Should only be Heavy Bolter or flamer as an option

**Comment by alphalas** [comment]
![img_1302](https://user-images.githubusercontent.com/15703066/27353187-25d705fc-55d1-11e7-9bab-5a13c8e11e09.PNG)
Read better.

**Comment by Eerieuk** [comment]
my bad.. must have missed that one sry. Great job on the fast fixes

**Comment by alphalas** [comment]
It's been that way for two codices – not really something you could miss.

**Comment by Eerieuk** [comment]
Again sry.. Never a unit ive used.
