### ISSUE TITLE
Chaos - Death Guard - HTML & BS disagreement

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#309]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** No

**Description:** Chaos Spawn description, Mutated Beyond Reason table.
Entry showing HTML format coding.

**Comment by cartag** [comment]
The problem is that BS isn't rendering the output properly.

**Comment by GenWilhelm** [comment]
The latest build intentionally escapes HTML code - it's a feature, not a bug.
https://github.com/BattleScribe/Desktop-Alphas/issues/133#issuecomment-307643637
