### ISSUE TITLE
Imperium - Astra Militarum: Command squad size validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#310]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** No

**Description:** When building a Command Squad, replacing 2 Veterans with a Veteran Weapons Team only counts the Weapons Team as a single veteran, causing the program to prompt you to add another Veteran to the squad.

**Comment by alphalas** [comment]
was updated - next release will fix.
