### ISSUE TITLE
Tau Empire - Stealth Suits selecting support system upgrades for Shas'ui cumbersome

### ISSUE THREAD

**Issue by StealthKnightSteg** [BSData/wh40k-9e#313]
**File/Catalogue:** Tau Empire v2

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** No

**Description:** Detailed issue description.
Any Shas'ui may take a single item from the support system, now you have to swap out a "non" upgraded for another shas'ui. This can be easier.

**Comment by amis92** [comment]
@StealthKnightSteg 
I've added this option because it makes roster output shorter if you do not select any support system. It might be however preferred to make the non-collapsible version the default. Do you think this is the case?

**Comment by StealthKnightSteg** [comment]
I'm not sure, of course it is preferred to have a shorter output, but it took me a while to figure out how to get the support systems on there for the shas'ui while the shas'vre was easy to pick out. Also I'm not sure if it would be better the other way now as every shas'ui can pick a different support system. But as the rest is the same output can also just show how many shas'ui you have and how many of the different support systems are linked (if that is possible... been a while since I dived in to the manipulation of the catalogue's)
Anyway if I find it confusing to get shas'ui with a support system I'm probably not the only one.

**Comment by amis92** [comment]
Yeah I think I've overdone that. I'll revert it.

Or... just a very silly idea:

Create an entry of Shas'ui for each support system:

* Shas'ui
* Shas'ui with Advanced ...
* Shas'ui with Drone Controller
* etc.

but that's quite possibly even worse? Although saves clicks and screen switches on mobile.

**Comment by StealthKnightSteg** [comment]
I would say try it out and see if you are happy with it

**Comment by amis92** [comment]
![zrzut ekranu 2017-06-22 o 17 15 29](https://user-images.githubusercontent.com/2671396/27441559-2df10b54-576e-11e7-9d44-e33e489cf695.png)

Not sure if happy about that.

That's how it looks now:


![zrzut ekranu 2017-06-22 o 17 19 11](https://user-images.githubusercontent.com/2671396/27441718-ae0941d0-576e-11e7-8ac6-b19ad8a49d8b.png)

**Comment by amis92** [comment]
Another example:

![zrzut ekranu 2017-06-22 o 17 51 48](https://user-images.githubusercontent.com/2671396/27443416-3a74ac96-5773-11e7-9c4a-5a6201c11dba.png)


vs (what is now):

![zrzut ekranu 2017-06-22 o 17 50 45](https://user-images.githubusercontent.com/2671396/27443372-1b4af514-5773-11e7-8242-90d7b478ef22.png)

**Comment by GitArdnutz** [comment]
Definitely an improvement from my perspective as a user on desktop and mobile

**Comment by StealthKnightSteg** [comment]
How does that hold up when you select a shas'ui / shas'vre with a fusion blaster? And does the shas'vre show f it can take the fusion blaster?
The examples you put up look a lot better that way! nice job

**Comment by amis92** [comment]
They've stayed the same (ui w/ FB is separate with nested support system choice, 'vre also has nested choices - too many possibilities to flat it out)
