### ISSUE TITLE
Drukhari - Wyches categories missing

### ISSUE THREAD

**Issue by USSX-Hares** [BSData/wh40k-9e#314]
**File/Catalogue:** Drukhari.cat

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** Wyches have all keywords but Troops missing. That's why they've did not gain Strength from Death rule in the Ynnari catalog (Infantry or Biker category required). Please, add links to their Categories to match other units' implementation.

@Toreador13 please, take a look
@FarseerVeraenthis, FYI

**Comment by Toreador13** [comment]
Fixed in V5
