### ISSUE TITLE
Chaos Icons

### ISSUE THREAD

**Issue by thefbgnome** [BSData/wh40k-9e#319]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description. Adding an Icon to most units should cost 10 pts ( ie an icon of wrath <khorne> on a unit of Raptors... or CSM)

**Comment by cartag** [comment]
I don't see the problem, the icons do cost 10 pts. If you're not able to find it, you'll see a listing for what mark is chosen, the icon is under there.

**Comment by thefbgnome** [comment]
NVM I see now it is two steps... not sure why?

**Comment by cartag** [comment]
Easiest implementation. I'd rather have it done and messy than have people waiting on my dumb ass. It will likely be changed when the codex comes out anyway.
