### ISSUE TITLE
Astra Militarum: Unable to select more than 2 special weapons for Scions

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#32]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** No

**Description:** Create a Brigade Detachment of Astra Militarum.  Create a tempestus scion squad.  Put in 6 regular scions, and try to add 4 hotshot volley guns.  It only allows for up to 2 of any type of special weapon, instead of 4.  I tried deleting the tempestor and it still didn't work.

**Comment by alphalas** [comment]
It's a known error in #6
