### ISSUE TITLE
Aeldari - Ynnari - Shuriken cannons have incorrect cost on Ynnari Starweavers and Voidweavers

### ISSUE THREAD

**Issue by jpazdera** [BSData/wh40k-9e#323]
**File/Catalogue:** 

**BattleScribe version:** 2.01

**Platform:** Windows/Android/Mac

**Dropbox:** No

**Description:** The cost of the shuriken cannons on Ynnari Starweavers and Voidweavers (12 pts each) is incorrect and does not match the cost of those on the Harlequin versions of the vehicles (10 pts each).

**Comment by FarseerVeraenthis** [comment]
Well that's a nice one GW!! Craftworld Shuriken Cannons cost 12pts, but you're right, Harlequin ones only cost 10pts.
I suspect this has happened because of the way the three Aeldari CAT's were merged, so the heavy weapons list needs a modifier to take into account the cost difference.

**Comment by USSX-Hares** [comment]
I'll take a look why it is happening.
