### ISSUE TITLE
Astra Militarum error 

### ISSUE THREAD

**Issue by Ciarangj** [BSData/wh40k-9e#326]
the base points cost of commissar is wrong and veterans don't have the option to take their heavy flamer

**Comment by Coomakazie** [comment]
Commissar is base 30 and must take a bolt pistol so is therefore 31 - points are not incorrect.

Vetrans have the option to take heavy flameer per v18.

Please update your data.

**Comment by FarseerVeraenthis** [comment]
Correct in file version 18.
