### ISSUE TITLE
Alphabetize Catalogs in Add Force Dialog

### ISSUE THREAD

**Issue by mugginns-zz** [BSData/wh40k-9e#33]
**File/Catalogue:** 

**BattleScribe version:** 2.01.02

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes

**Description:** Hi, can you alphabetize the dropdown for the different catalogs in the add force catalog? Would make using it 100% easier.

**Comment by penguin20000** [comment]
This is a Battlescribe bug rather than a Data bug. I think @Jonskichov is aware

**Comment by FarseerVeraenthis** [comment]
They are in alphabetical order for me...

**Comment by penguin20000** [comment]
Strange on Android they are but Windows they're not

**Comment by mugginns** [comment]
Hi, sorry - on Android they are, on Windows they are not.

**Comment by Owlsbane** [comment]
Just to confirm some more, Windows 10 here, no alphabetical order.

**Comment by skonk** [comment]
MacOS here and they are out of order.
