### ISSUE TITLE
Orks - Bug report

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#338]
**File:** Orks.catz

**BattleScribe version:** 2.01.03

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Wrong pts values: big mek in mega armor, all warboss builds, manz, nob w banner, painboy builds, tankbustas, deff koptas, all buggies and wartrakks, big and mek gunz, deff dread, gorkanauat and morkanaut, killa kans, all flyers, trukks

I cross referenced the points listed in BS to the index: xenos 2 book

**Comment by Penallegion** [comment]
Are you sure you have the current data file ? i am crossreferencing now and all points seem legit.
have you tried substracting wargear from model cost ?

**Comment by tag8833** [comment]
I'm pretty sure this is the same source as #321 and #256  

I think he doesn't understand that you've got to pay for wargear even if it comes standard.  Not sure how to communicate with him since he submits as Anon.

**Comment by tyler30000** [comment]
I beleive issue with defkoptas they can take killsaws in addition to the spinning blades already equipped. 

Thus in combat attacks can be split between this weapons
