### ISSUE TITLE
Space Marines: Dark Angels Deathwing Terminators - Incorrect points/selection for heavy weapons

### ISSUE THREAD

**Issue by Luxey012** [BSData/wh40k-9e#340]
**File/Catalogue:** Warhammer 40,000 8th Edition v1.0.9/Warhammer 40,000 8th Edition v4

**BattleScribe version:** 2.01.02

**Platform:** Windows/iOS

**Dropbox:** No

**Description:**
When going to select the heavy weapons for the Deathwing Terminators, it selects both a "Heavy Weapon" and the default "Storm Bolter/Power Fist". This is incorrect, as the rules do not allow for this selection. The Storm Bolter is replaced by the Heavy Weapon.

Also, this causes the unit to be charged points for both the heavy weapon choice and the default weapon set.

![bug](https://user-images.githubusercontent.com/29606050/27390631-60d29f5e-5667-11e7-95d0-0eca93ad8b13.JPG)

**Comment by alphalas** [comment]
No, it's actually not replaced with how the entry is worded.
