### ISSUE TITLE
Imperium - Astra Militarum: Veteran squads are counting as a Troops choice

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#344]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.01

**Platform:** Windows

**Dropbox:** No

**Description:** When filling out a Battalion Detachment with 6 Infantry Squads in the Troop selection, adding a Veteran Squad to your Elite selection causes Battlescribe to return the validation error "Battalion Detachment has 1 too many selections from Troops"

The program displays Veterans as Elites, but still tracks them on the roster as Troop choices when counting your force org slots.

**Comment by alphalas** [comment]
Will be fixed in the next release
