### ISSUE TITLE
Drukhari - Khymerae should not take up force org slot with beastmaster

### ISSUE THREAD

**Issue by smacktoid** [BSData/wh40k-9e#352]
**File/Catalogue:** Drukhari.cat

**BattleScribe version:** 2.01.

**Platform:** iOS

**Dropbox:** Yes

**Description:**

When a beastmaster is added to a drukhari force it should be possible to add a unit of khymerae without taking up a force org slot.

As it stands Khymerae can be added to the 'no force org' section, but they are still counting towards the number of fast attack choices, even when there is a beastmaster in the list.

**Comment by Toreador13** [comment]
Fixed in Drukhari v7 (release tonight)
