### ISSUE TITLE
Bug Report- Astra Militarum.catz

### ISSUE THREAD

**Issue by blackrabbit84** [BSData/wh40k-9e#357]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

Error: "dedicated transport has 1 too many selections of Taurox (maximum 1"

Won't allow you to take more than 1 Taurox in a list.

**Comment by blackrabbit84** [comment]
Another issue: Brigade detachment without the minimum amount of troops shows as a legal list. Intermittent issue only encountered occasionally when adding and removing units.

**Comment by alphalas** [comment]
Update data - all previously resolved bugs. Also make sure you are running latest BS.
