### ISSUE TITLE
Astra Militarum: No Sponsons for Pask

### ISSUE THREAD

**Issue by H3BREWH4MMER** [BSData/wh40k-9e#36]
**File/Catalogue:** 

**BattleScribe version:** 2.00.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by bowgs** [comment]
This has already been reported in https://github.com/BSData/wh40k/issues/6, lets try to keep the AM issues together.

**Comment by H3BREWH4MMER** [comment]
Sorry, I'll close this one out.
