### ISSUE TITLE
Imperium - Astra Militarum - Tempestus Scions unable to de-select Hot-Shot Volley Gun

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#362]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** No

**Description:** When selecting Tempestus Scions special weapons, the special weapons automatically has chosen the 9 point hot shot volley gun. You can't remove the weapon and adds those points on top of the special weapon you want, giving an error

**Comment by alphalas** [comment]
Update your data and BS
