### ISSUE TITLE
Imperium - Space Marines: Sarge weapon validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#364]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** No

**Description:** Space Marine Sergeants are required to take two types of wargear for the roster to be declared valid, but that means if you only equip a sergeant with a bolter, you must also choose either a chainsword or a bolt pistol for the roster to validate. If you try to pick all three, you get another validation error. It should be bolter OR BP/CS

**Comment by GenWilhelm** [comment]
On their datasheet, tactical sergeants are equipped with a boltgun and a bolt pistol, either of which they can replace with an item from the Sergeant Equipment list. In effect, you can have any combination of 2 items on the list.
