### ISSUE TITLE
Imperium - Dark Angels Hellblaster Squad wrong Power Level

### ISSUE THREAD

**Issue by MaverickIV** [BSData/wh40k-9e#366]
**File/Catalogue:** Imperium – Dark Angels V8

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** No

**Description:** The Heavy Support **Hellblaster Squad** has a wrong Power Level cost. It should be 12PL, and not 6PL as of now

**Comment by GenWilhelm** [comment]
Fixed in 4385bec71d65d5f677d50fbc16674ef410dbbb91.

**Comment by MaverickIV** [comment]
That fixe was for Dark Angels V7, as it refers to #333 (my priviest post on that matter)

Was I just 1 version late and the fixe will come with Dark Angels V9 ? (just to be sure)

**Comment by GenWilhelm** [comment]
Yes, the fix is in v9. It has been released already, so it should be there if you update your data.

**Comment by MaverickIV** [comment]
Okay. Thanks. I have got the right cost now.
