### ISSUE TITLE
Astra Militarum: Incorrect cost for flamer

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#37]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Astra Militarum Flamer in Infantry Squad entry should be 11 points (4 for model 7 for the weapon) not 14points.

**Comment by alphalas** [comment]
rolled into #6
