### ISSUE TITLE
Harlequins Shuriken Cannons have different point values than other Eldar

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-9e#375]
**File/Catalogue:** Ynnari - Aeldari.cat

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** No

**Description:**

**Comment by FarseerVeraenthis** [comment]
The problem is? 
In the index harlequin shuriken cannons are 10, Eldar ones are 12.

**Comment by AzhekAhriman** [comment]
Hi, sorry about the lack of info originally.... Got caught by a title change that wiped the whole post.

The issue is that in Ynnari detachments a Shuriken Cannon costs 12 points even when it is mounted on a Harlequin vehicle.

**Comment by GenWilhelm** [comment]
This was fixed today in f10b54d75adf730632e56dfbee7868ef582797b4.

**Comment by FarseerVeraenthis** [comment]
and hence this can be closed :smile:
