### ISSUE TITLE
Incorrect cost for HB on Valkyrie

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#38]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Valkyrie Heavy Bolters are 24 points for a pair. They should cost 16 points per pair (HB at 8 points each)

**Comment by alphalas** [comment]
Rolled into #6
