### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Aref-Naa** [BSData/wh40k-9e#385]
**File/Catalogue:** Astra Militarum

**Description:** @cartag told me to post this here- looking to help out with the Astra Militarum and/or Inquisition file if it's needed.

**Comment by amis92** [comment]
Hi, in the new 40k repository we do not give write access to anyone except Core Team - if you want to contribute, communicate with us on gitter and through issues and push changes as Pull Requests from your own fork. See [Getting Started 3rd bullet](https://github.com/BSData/bsdata/wiki#getting-started).

And as AM and Inq is @alphalas's, he'll manage it.

**Comment by alphalas** [comment]
Yeah join us on gitter (https://gitter.im/BSData/wh40k), I know another dev said he might have a job for you
