### ISSUE TITLE
Chaos Daemons replication

### ISSUE THREAD

**Issue by Joshua137** [BSData/wh40k-9e#387]
**File/Catalogue:** 
Chaos Daemons
**BattleScribe version:** 2.01.
2.01.03
**Platform:** Windows/iOS/Android/Mac/Linux
iOS
**Dropbox:** Yes/No
No
**Description:** Detailed issue description.
I have 2 units of Flesh Hounds in one detachement. Changing size of one also changes size of the other. Happens with all fast attack options. Also occurs with elites choices as well. Troop choices are NOT affected.

**Comment by cartag** [comment]
More specifically, only affects PL of the unit.

**Comment by qurgh** [comment]
This is happening for me with Plague Drones too. Adding Drones to one unit also adds drones to all other Drone units, which then increases the points and Power.

**Comment by amis92** [comment]
Possibly another example of BattleScribe/Desktop-Alphas#166 ?

**Comment by cartag** [comment]
No, this is different amis. This is me being a dumbass when writing a file.

**Comment by cartag** [comment]
Fixed in v6.
