### ISSUE TITLE
Space Wolf Grey Hunter problems

### ISSUE THREAD

**Issue by hype261** [BSData/wh40k-9e#388]
File: Imperium - Space Wolves.catz

BattleScribe version: 2.01.03

Platform: Windows

Dropbox: No

**Description:** Clicking to add a Grey Hunter in one unit adds it to another unit.  With a 10 man squad gives an error when trying to have 2 special weapons.  Should be 1 special weapon per 5 models.

**Comment by penguin20000** [comment]
Should be fixed once the new release lands on app spot
