### ISSUE TITLE
Imperium - Astra Militarum: Unable to take more than 2 special weapons on Scions

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#39]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** No

**Description:** Ten man Scion squads are being limited to 2 special weapons when they are entitled to 4

**Comment by bowgs** [comment]
This has been reported in #6 - please add AM issues to the existing report
