### ISSUE TITLE
Chaos - Chaos Space Marines - Special Weapon Selection Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#391]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.03

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Not sure if this is a bug or not but I can't figure it out. The rule book states that up to 4 Chosen can replace there bolt guns with with items from the specialist list. When I try to outfit them with 4 plasma guns I'm getting an error that the list isn't valid. I can't figure this out.

**Comment by skonk** [comment]
Yeh this is an error.

The Special Weapons within the "Weapon Replacement (up to 4)" section are currently limited to 1 per unit, but should be part of the up to 4 rule.
