### ISSUE TITLE
CAT - Aeldari - Corsairs <-- I'll get to it

### ISSUE THREAD

**Issue by FarseerVeraenthis** [BSData/wh40k-9e#394]
I'll build a CAT for the Corsairs, even though it is only 3 datasheets at present, because they don't have the "Asuryani" keyword and hence aren't aligned to a Craftworld in the same way as the units in the Craftworld CAT.

**Comment by Viper666-Qc** [comment]
Corsairs??? You mean the Anhrathe?

**Comment by FarseerVeraenthis** [comment]
Yup, but since the name of the craftworld CAT is not Asuryani I think Corsairs is a better option, also doesn't sound like a sneeze...
