### ISSUE TITLE
Ynnari Supreme Command error

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k-9e#395]
**File/Catalogue:** Aeldari - Ynnari v9

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** No

**Description:** The Ynnari Supreme Command detachment allows the selection of unit types other than HQ, Elite or Dedicated Transport. These options should not be available.

**Comment by ilaunchbury** [comment]
Ignore me. Don't know what I did here.
