### ISSUE TITLE
Add FW Units to Aeldari - Craftworlds CAT.

### ISSUE THREAD

**Issue by FarseerVeraenthis** [BSData/wh40k-9e#396]
- [x] Shadow Spectres
- [x] Wasp Assault Walker
- [x] Wraithseer
- [x] Hornet
- [x] Warp Hunter
- [x] Lynx
- [x] Scorpion
- [x] Cobra
- [x] Nightwing
- [x] Phoenix
- [x] Vampire Raider
- [x] Vampire Hunter
- [x] Skathach Wraithknight
- [x] Revenant Titan
- [x] Irillyth
- [x] Phantom Titan

Don't expect them done in a rush :wink:

**Comment by Jbat360** [comment]
And also the corsair units if possible since they're the same faction.

**Comment by Jbat360** [comment]
Actually disregard me. Just seen your other post for corsairs lol. Sorry. 
Thanks!

**Comment by Sepherato** [comment]
Revenant Titan:
Move/ws/bs Missing.
Phantom Titan has it, only missing for the revenant.

**Comment by ilaunchbury** [comment]
[ ] The table for the Vampire's Distort Fields isn't working in the HTML output on Windows.
[ ] Crystal Targeting Matrix has "targetting" in its Description.
[ ] Skathach Wraithknight has "set yp" in the Description for Webway Rupture.
[ ] Skathach Wraithknight missing ) in "Deathshroud Cannon (Dispersed" name.
[ ] Skathach Wraithknight "Deathshroud Cannon (Focussed)" should only have a single s in Focused.
[ ] Are the profiles for the Deathshroud Cannon the correct way round (I don't have the index, sorry)? Most weapons with a dispersed profile are lower strength, more shots on that profile, but the Deathshroud isn't.
[ ] Revenant Titan - Should be "**reduced** to 0 wounds" in the Catastrophic Collapse description.
[ ] Revenant Titan - same table in Description issue as with the Vampire.
[ ] Phantom Titan - Same issue in Catastrophic Collapse as Revenant.
[ ] Phantom Titan - same table in Description issue as with the Vampire.
