### ISSUE TITLE
Imperium - Astra Militarum: Brigade validation error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#397]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** No

**Description:** When building a brigade detachment, there is a warning saying 12 only troop choices when there are 10 or more troop choices. The 8th edition 40k rules allow 12 troop choices. Right now the tool only allows 9 before it errors.

**Comment by alphalas** [comment]
How many Vet squads did you take? There was a bug fixed where vets were counting as troops and Elites
