### ISSUE TITLE
Feature request: Picking psychic powers

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-9e#4]
_From @BerkshireKnight on June 9, 2017 20:54_

The new rules allow all psykers to choose the power or powers they know instead of rolling randomly. Might it be a good idea to add psychic powers as a new type of 'wargear,' and allow psychic units to select their power(s) from within the list?

_Copied from original issue: BSData/wh40k-7th-edition#3810_

**Comment by amis92** [comment]
_From @tekton on June 9, 2017 23:20_

I did that for Grey Knights the other night- it's not too hard to add, but does look a little weird, imo. There's already some built in support to the Alpha Builds for "Psychic Ability" when filling out profiles, too.

**Comment by amis92** [comment]
_From @flakpanda on June 10, 2017 16:34_

This should be handled on a cat by cat basis. Implementing this is easy. Create a new entry within the psyker with selectable powers. I have this for SM Libbies.

**Comment by Penallegion** [comment]
also did it in R&H

**Comment by FarseerVeraenthis** [comment]
This has been included in the Guidelines on the Wiki, so I think this issue can be closed.
Ref: https://github.com/BSData/wh40k/wiki/CAT-Creation-Guidlines
