### ISSUE TITLE
Imperium - Astra Militarum: Unable to give Veterans a heavy flamer

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#40]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** There is no heavy flamer option for Veterans. Should be a 17 (+6 for the model) point upgrade in addition to the 3 special weapons slots. Thanks!

**Comment by bowgs** [comment]
This has been reported in https://github.com/BSData/wh40k/issues/6 - please add AM issues to the existing report
