### ISSUE TITLE
Tyranids - Hive Tyrant's wings do not take weapon slot

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#401]
**File:** Tyranids.cat

**BattleScribe version:** 2.01.03

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Hive Tyrant's Wings should take up a weapon slot. It doesn't. With or without Wings it still requires 2 weapon slots to be filled.

**Comment by GenWilhelm** [comment]
On the Hive Tyrant's datasheet it simply states that it "may have wings", not that it replaces one of its weapons with them. I understand that on the model the wings go in the arm sockets, thus blocking you from having a second set of arm weapons, but from a rules perspective a Hive Tyrant must have two sets of weapons, regardless of its wings.

If you don't want to spend extra points, then the rending claws cost 0; or if you want to be strictly WYSWYG, then just don't select a second set of weapons and ignore the error message.

Datasheet for reference:

![tyrant](https://user-images.githubusercontent.com/22036809/27490278-9410bd72-5835-11e7-83a4-e4034356a866.png)
