### ISSUE TITLE
Astra Militarum - Invalid unit size when using Heavy Weapons squad

### ISSUE THREAD

**Issue by Celibarin** [BSData/wh40k-9e#411]
File: Imperium - Astra Militarum.cat

BattleScribe version: 2.01.02

Platform: Android

Dropbox: No

Description: When using a Heavy weapon squad in the Infantry unit and Veteran squad the unit only counts as 1 Guardsman/Veteran. This in turn makes it an invalid unit as when taking away 2 guardsman, to make 7, with Lasguns the unit is invalid in the roster errors stating "Veterans/Infantry Squad must have 1 more selections of Veterans/Guardsman (minimum 9). If you increase Veterans/Guardsman with Lasgun you get the error: "Maximum 8".

**Comment by alphalas** [comment]
Update data
