### ISSUE TITLE
Aeldari - Drukhari - Voidraven base cost

### ISSUE THREAD

**Issue by Lokust** [BSData/wh40k-9e#416]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** data file is listing cost of 160.  Index shows 169.  Probably just a typo.

**Comment by GenWilhelm** [comment]
What file version are you looking at? This should have been fixed in v6.

**Comment by Lokust** [comment]
Ah sorry I thought I'd updated it, maybe it didn't update correctly before.
 please mark issue as resolved and bug reporter as idiot
