### ISSUE TITLE
Acastus Porphyrion has fusil - incorrect 

### ISSUE THREAD

**Issue by Xabre1342** [BSData/wh40k-9e#419]
Extra weapon, can't remove it.

**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Thairne** [comment]
What catalogue is that thing in?

**Comment by francoisbeaulieu** [comment]
I beleive it's from the ForgeWold indexes for both Chaos and Astra Militarum.

**Comment by cartag** [comment]
Corrected from Chaos, if loyalist copied from Renegade it will have same problem.

**Comment by Thairne** [comment]
Loyalist doesnt exist yet.
Fulltext search reveals that 

Chaos - Dark mechanicum
Chaos - Questor Traitoris

have that thing in it.

It also belongs into Astra Militarum, so its our Prime Boy that is responsible :P

**Comment by cartag** [comment]
It belongs in the Questor Imperialis file because that's the faction it's part of.

**Comment by Thairne** [comment]
Since its fixed in chaos and not yet existant in loyalist, closing.
I'm going to work the thingies in via https://github.com/BSData/wh40k/issues/382 once I find the time.
