### ISSUE TITLE
Chaos Space Marines - nearly all

### ISSUE THREAD

**Issue by Olsen370** [BSData/wh40k-9e#421]
**Description:** Replacing a standard weapon with an optional weapon: the standard weapon won`t vanish. Seen at Cultists, CSM, Chosen and others: changed weargear is listed and all standard wepaons too. So a unit of nine Chosen has nine Bolt guns plus all special weapons.

**Comment by cartag** [comment]
I would assume you are competent enough to realize when it says "Replace one X with Y" you can know to not count the default one when figuring out attacks. The only work around is a WAY more complicated setup, which would then lead to people bitching that they have to do even more work.
