### ISSUE TITLE
Imperium - Space Marines: War gear / weapons not collective, not correct model type, categories missing

### ISSUE THREAD

**Issue by Takao-7** [BSData/wh40k-9e#426]
**File/Catalogue:** Imperium Space Marines V6

**Description:** Many weapons and war gear in units are not collective. Most weapons have two versions: collective and non-collective. If there are more than one model in the unit that uses that weapon, the collective one should be taken, so that you have, for example, 5x Space Marine und not Space Marine, Space Marine, Space Marine, Space Marine, Space Marine.
For example for the Space Marine in the Tactical Squad, all three weapons (Bolt pistol, Boltgun and Frag & Krak grenades) are links to war gear which is collective (see the _(select)_ drop down menu).

The weapons and war gear for several other units, including the Assault squad, is NOT a link to a collective war gear.
One should go through every unit in the Space Marine codex and see if their war gear is collective or not and change it to collective if not.

Also, there are several units which don't have the "unit" type and models which are not "models", but are instead "upgrades".

Lastly several units don't have any categories checked. (Is this even necessary?)

**Comment by flakpanda** [comment]
Ill get to it when i get to it.

**Comment by flakpanda** [comment]
Im closing this, as I've decided that that catalog is working fine and how it needs to be until further improvement. Please do not raise this as an issue again.
