### ISSUE TITLE
[Bug Report] Astra Militarum.cat - Shadowsword 

### ISSUE THREAD

**Issue by ctdavids** [BSData/wh40k-9e#448]
File/Catalogue: Imperium - Astra Militarum.cat (Version 25)

BattleScribe version: 2.01.02

Platform: Windows

Dropbox: No

Description:

Issues not fixed in https://github.com/BSData/wh40k/issues/424

Shadowsword

    17 points for default twin heavy bolter when it should be 14 (the bolters in the sponsons are properly 14, but the one on the hull is 17)
    Still doesn't show degraded stats (M/BS/A) (as in the profile shows a *, but nowhere does it show what that value is at what wound values)

**Comment by alphalas** [comment]
I cannot duplicate either

**Comment by ctdavids** [comment]
I'm not sure why not.  I just did a fresh install (on Mac to check that).  I then updated from the repository.  Then I updated the warhammer core file and the astra militarum files from the latest on this site.  Then I added a shadowsword model.  See the attached image.

Note: Twin heavy bolter [17 pts]
Note: no values for degrading wounds and stat line

<img width="1280" alt="screen shot 2017-06-25 at 11 19 15 am" src="https://user-images.githubusercontent.com/5614387/27518585-449cd1a4-5998-11e7-9567-880128d53260.png">

**Comment by alphalas** [comment]
Are you pulling from app spot or github ?

**Comment by alphalas** [comment]
If appspot you're gunna have to wait for the next release to fix

**Comment by ctdavids** [comment]
I get the initial data pull from the one listed in BattleScribe (which I think is AppSpot), but I then manually downloaded the core file and the AM file from github and loaded them using the import data file option.

**Comment by alphalas** [comment]
I'll look again when I get home - I know I fixed it

**Comment by ctdavids** [comment]
I can confirm this works for me now.  Thanks for all the hard work!
