### ISSUE TITLE
Chaos Havocs weapon upgrades

### ISSUE THREAD

**Issue by blueraven84** [BSData/wh40k-9e#449]
**File/Catalogue:**  Warhammer 40,000 8th edition 1.0.13

**BattleScribe version:** 2.01.

**Platform:** Windows 10

**Dropbox:** No

**Description:** Chaos Havocs weapon cost wrong when taking Havocs in added detachments 

Example: Daemon Battalion + Chaos Space Marine Battalion.

Counts correctly for the first weapon but doesn't add points when you add more than one weapon upgrade.

**Comment by cartag** [comment]
I think this is less an issue with the Chaos file and more with how BS calculates points. Researching more.

**Comment by cartag** [comment]
https://github.com/BattleScribe/Desktop-Alphas/issues/166
