### ISSUE TITLE
No profile data when in View on iOS

### ISSUE THREAD

**Issue by Dalthoraz** [BSData/wh40k-9e#45]
**File/Catalogue:** 
Warhammer 40000 8th Edition

**BattleScribe version:** 2.01.02

**Platform:** iOS

**Dropbox:** No

**Description:** Detailed issue description.
When I do to view on a roster I can't see profiles for models.  See attached images.  The title and points are all there but not the unit profiles.

![image1](https://user-images.githubusercontent.com/29486746/27234806-548ac390-528c-11e7-980e-aeddc9fb127f.PNG)
![image2](https://user-images.githubusercontent.com/29486746/27234807-548ed5de-528c-11e7-9825-e3ee53cda445.PNG)

**Comment by Dalthoraz** [comment]
Is there an issue open that I can follow for updates?

**Comment by GenWilhelm** [comment]
Not that I can find, but the developer is aware of it. We'll keep this issue open for now, until the bug has been fixed.

**Comment by Dalthoraz** [comment]
Great thanks

**Comment by GenWilhelm** [comment]
Just heard about a workaround. If you go into advanced options on the roster view and disable categories does that change anything?

**Comment by Dalthoraz** [comment]
Yes it look correct now.  Thanks for that.  Seems like categories is interfering in an unexpected way.  Thanks again

**Comment by francoisbeaulieu** [comment]
This is solved in version 2.01.3
