### ISSUE TITLE
Aeldari - Craftworlds: Autarch Forceshield ability has no cost - it should

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#451]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.01.04

**Platform:** Android

**Dropbox:** No

**Description:** the autarch force shield is listed as 0 points and should be 8. the hemlock wraithfighter has a sperit stone for free when it should be 10 points. per warhammer 40k facebook if an item has a points cost listed for it it must pay the points for the item. inharent abilitys are only free if their is no points cost listed for them.

**Comment by FarseerVeraenthis** [comment]
Please link the Facebook comment

**Comment by FarseerVeraenthis** [comment]
https://m.facebook.com/story.php?story_fbid=1851315258522438&id=1575682476085719

**Comment by FarseerVeraenthis** [comment]
Jesus, bloody phone... 
I'll get that updated shortly, this was actually how it was built originally...

**Comment by amis92** [comment]
For future reference, the post and answer is attached as an image below:

![image](https://user-images.githubusercontent.com/2671396/40647459-32c75a3c-632c-11e8-8b29-6efa1b425ad7.png)
