### ISSUE TITLE
Chaos - Chaos Space Marines - Special Weapon Validation Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#454]
**File:** ~~Chaos - Daemons.catz~~ Chaos - Heretic Astartes

**BattleScribe version:** 2.01.04

**Platform:** Android

**Dropbox:** No

**Description:** Up to 4 Chosen may replace their boltgun with a combi-weapon, special weapon, or melee weapon. The current file says that i have to many if i select more than 1.

Its completely valid to have a squad of 5 Chaos Chosen with 4 Plasma Guns.

**Comment by cartag** [comment]
Duplicate of #391
