### ISSUE TITLE
Imperium - Astra Militarum - Twin Heavy Bolter Points Cost Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#461]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** The points for twin heavy bolters are 14 points in the imperium index 2 which is completely different from imperium index 1 which is 17 pts and is meant for space marines.

**Comment by alphalas** [comment]
Update your data - was fixed in new release
