### ISSUE TITLE
Bug Report: Rosters not listed in Alphabetical Order

### ISSUE THREAD

**Issue by BaconCatBug** [BSData/wh40k-9e#463]
**File/Catalogue:** Warhammer 40k 8th Edition v1.0.9

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** N/A

**Description:** Why are none of the catalogue options in alphabetical order? Please make them so as it is beyond infuriating to try and find what you want especially if you are taking units from multiple sources.

**Comment by flakpanda** [comment]
This is a Battlescribe bug that we have no control over. We have raised the issue with the dev.

**Comment by FarseerVeraenthis** [comment]
should have been fixed with the latest release of Battlescribe...
