### ISSUE TITLE
Chaos - Chaos Space Marines - Fallen Not Costed Properly?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#464]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** Yes

**Description:** The Fallen aren't costed properly. All weapons seem to be free in current data file. Fallen with plasma pistol = 14 pts...that's a free plasma pistol.

**Comment by Penallegion** [comment]
Doesn't decrement Bolt pistol if you replace weapon
![plasma](https://user-images.githubusercontent.com/25779557/27594531-4f7d15d4-5b5a-11e7-821e-c02d51128522.png)

**Comment by flakpanda** [comment]
@Penallegion Im confused, is this issue about Fallen, or Chosen?

**Comment by Penallegion** [comment]
@flakpanda oh my bad it was the only ticket open for Chaos at the time thought i would keep them collected for easy acces but let me just remedy that so it fits the size 4 around here
