### ISSUE TITLE
Tau troops duplicating

### ISSUE THREAD

**Issue by Lance845** [BSData/wh40k-9e#465]
**File/Catalogue:** 
Warhammer 40,000 8th edition 1.0.0
Tau Empire v2

**BattleScribe version:** 2.01.02

**Platform:** Windows/iOS/Android/Mac/Linux
Window 10

**Dropbox:** Yes/No
No

**Description:** Detailed issue description.
If you add multiple units of Tau infantry to a detachment and then increase or decrease the number of models it duplicates through all similar units.

For example. If I create 3 units of Fire Warrior Breachers and then increase one unit from 5 models to 8 all 3 units will increase to 8 models.

I have had the same thing happens to pathfinder units in the Fast Attack section.

Unsure how wide spread the issue is.

**Comment by amis92** [comment]
BattleScribe/Desktop-Alphas#166

@Lance845 Please just confirm if it's happening only if that Tau force is a child force (not a root one) - if so, that's out of our reach. Wait for BS update.

**Comment by GenWilhelm** [comment]
The Fire Warriors in a Breacher Team are marked as collective, so any Breacher Teams with the same parent (ie. in the same Force) will automatically adjust so they all have the same number of Fire Warriors.

**Comment by amis92** [comment]
Okay it looks as though there were a couple more Collectives as well:

* Breacher Team Fire Warriors
* Vespid Stingwings both normal and Leader
* Kroot Carnivores
* Kroot Hounds
* Krootox Riders
* Kroot Shaper's weapon

**Comment by amis92** [comment]
But still not happening with Pathfinders. That might've been BS bug mentioned.
