### ISSUE TITLE
Tyranids - Carnifex Weapon Selection Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#467]
**File:** Tyranids.catz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** No

**Description:** Carnifex is alowed to trade both it's monstrous scything talons for 2 choices from the Bio-Cannons upgrade "any model may replace both it's monstrous scything talons with two choices from the Monstrous Bio Cannons list"  
So instead of only being able too choose 1 bio cannon we should be able too select 2, obviously forcing us to deselect it's schything talons, or other arms etc.
Thank you so much for all your hard work and dedication, me and all my friends use Battle Scribe!
Hope this helps.

**Comment by GenWilhelm** [comment]
Works fine on my end. Admittedly, it does look a little odd being "2x 2x ...", so I'll change that so it reads "2x Two ..." instead.

![bio-cannon](https://user-images.githubusercontent.com/22036809/27534023-80bf9624-5a5d-11e7-9094-a0bdfb28e8a7.png)

**Comment by 7Louis** [comment]
Aah I see, sorry I thought that you could have 2x Strangelthorn cannons or 2x Heavy venom Cannons. But orait.
Thank you

**Comment by GenWilhelm** [comment]
Ah yeah, the wargear list specifically forbids taking two of the big cannons on the same model.
Never mind, improvements were made regardless :)
