### ISSUE TITLE
Corsairs - Bugs and Enhancements

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-9e#468]
**File/Catalogue:** Aeldari - FW Corsairs v2

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** Yes

**Bugs:**
- [x] Reavers (and Heavy) should be 9 points per model.
- [x] Reavers and Skyreavers (and Heavies) are missing T and A from their profiles.
- [x] Reavers and Skyreavers don't correctly decrement min and max depending on the number of Heavies.
- [x] Cloud Dancer Felarch should be 30 points.
- [x] Brace of Pistols is missing D from its profile.

**Enhancements:**
- [x] All unit profiles are missing book and page references.
- [x] Reavers, Skyreavers, and Cloud Dancers could be collective.

**Comment by FarseerVeraenthis** [comment]
Unfortunately they cannot be collective because every model is customisable to a significant degree
I'll look at the rest although I did think I'd got the increment/decrement right :smile: the joy of battlescribe!
