### ISSUE TITLE
Aeldari - Ynnarri - New FW Corsair File has duplicate Unique Id.

### ISSUE THREAD

**Issue by Whiteraven15** [BSData/wh40k-9e#469]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Currently, the Aeldari - FW Corsair.cat file has the same UniqueID as the Ynnarri one. This causes the Ynnari file to get deleted by the Roster Editor once it loads the data files.

**Comment by FarseerVeraenthis** [comment]
This has been corrected by regenerating the CAT ID of the Corsair CAT.
As of commit bae223e

https://github.com/BSData/wh40k/commit/bae223e5e9c1fb334c7ad9f0429416a76e607916#diff-e966d1065eb0fd774ea9f22634be162d
