### ISSUE TITLE
Imperium - Adeptus Ministorum - Canoness weapon selections linked & SoB PL Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#472]
**File:** Imperium - Adeptus Ministorum.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** 1.   Have 2 Canoness as HQ. When I go to modify the weapons for the one of them it is modify the weapons for other one as well and vice versa. As they have different weapon profiles (1 has an inferno pistol and chainsword / 1 has bolt pistol and power sword) i am not able to choice different weapon profiles.
2.   When increasing the number of sisters in a battle sister squad the power level stays at 4 instead of increasing to 8 for 1-5 models after the initial amount or power level to 12 for 6-10 extra models

**Comment by alphalas** [comment]
What version of the cat are you running?

**Comment by GenWilhelm** [comment]
It's probably v3 or earlier if the Battle Sisters' PL isn't updating.
That said, there are still some issues with collective weapons in shared entry groups - specifically the power sword, bolt pistol, and boltgun.
