### ISSUE TITLE
Chaos - Chaos Space Marines - Warpsmith

### ISSUE THREAD

**Issue by Blastershoot** [BSData/wh40k-9e#473]
**File/Catalogue:** Chaos - Chaos Space Marines.catz 

**BattleScribe version:** 2.01.03.90

**Platform:** Windows

**Dropbox:** Yes

**Description:** Warpsmith doesn't have the Mark of Chaos selection possibility like ie Sorceror.

**Comment by cartag** [comment]
Right now marks don't actually do anything, and warpsmiths can't take icons, so it is a purely cosmetic selection at this point.

**Comment by Blastershoot** [comment]
Sure. It was just to tell you. I see sorcerors that have the selection possibility and at the end is the same as the Warpsmith.
