### ISSUE TITLE
Chaos - Chaos Space Marines - Chosen

### ISSUE THREAD

**Issue by Narkjin** [BSData/wh40k-9e#479]
**File/Catalogue:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.03.90

**Platform:** Windows

**Dropbox:** No

**Description:** Up to four Chosen may replace their bolter. But if I take a combi-, special or heavy weapon, the bolter is still there (in the description).

Btw. Chosen has strength 44 in their roster/profile ;)

**Comment by cartag** [comment]
Duplicate of #391

**Comment by Narkjin** [comment]
They've still the bolter, if I take a special weapon. And if I remove the bolter manually, I am getting an error.
