### ISSUE TITLE
Aeldari - Drukhari - Venom & Reaper Profile Bugs

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-9e#481]
**File/Catalogue:** Aeldari - Ynnari.cat and Aeldari Drukhari.cat

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** No

**Description:** Venoms are Toughness 6 in the profile entry in both Ynnari detachments and Drukhari ones. They are Toughness 5 in the index (Xenos 1, Pg 57). Reaper Storm Vortex Projector in blast mode has an AP of 6 instead of 0 (FW Xenos, Pg 37)

**Comment by FarseerVeraenthis** [comment]
The Drukhari and Ynnari CAT's effectively share data, so this will be fixed in the Drukhari CAT and then merged into the Ynnari CAT alongside any other updates.

**Comment by Toreador13** [comment]
Fixed in v9 which I will release tonight.
