### ISSUE TITLE
Aeldari - Drukhari - Razorwing Flock Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#486]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.01.02

**Platform:** Mac

**Dropbox:** No

**Description:** Razorwing flocks appear to be 3+ for the minimum dimension of the unit. They should be 1-3 instead, 1-12 considering further upgrades.

**Comment by Toreador13** [comment]
Fixed in v9 which will be released tonight.
