### ISSUE TITLE
Bug Report: Castellan Creed Error

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-9e#49]
**File/Catalogue:** Astra Militarium v1

**BattleScribe version:** 2.01.02

**Platform:** PC

**Dropbox:** No

**Description:** Lord Castellan Creed is having multiple errors reported:  "Lord Castellan Creed has 1 too many selections of Hot-shot Laspistol (maximum 1)"  when value is changed to 1 error is report "must have 1 more selections of Hot-shot Laspistol (minimum 2) when two are selected."

**Comment by alphalas** [comment]
rolled into #6
