### ISSUE TITLE
Chaos - Daemons - Burning Chariots have two battlefield roles

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#492]
**File:** Chaos - Daemons.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** In a brigade, burning chariots appear to count as both HS and Elites.

**Comment by cartag** [comment]
~~Looks fine to me, there's nothing in the CAT that links it to an Elite choice.~~

It was the linked Exalted Flamer that did it. Resolving.

**Comment by Glospey** [comment]
Not sure why this is closed.  The cost issue was resolved so I just updated my repositories again but the dual roles problem still persists . . .
![burning chariot - dual roles](https://user-images.githubusercontent.com/30353892/28476894-c4afa934-6e1f-11e7-9d6c-976789eb69ff.png)

**Comment by ilaunchbury** [comment]
I think I re-broke this when I did the refactor. I've changed the Exalted Flamer entry back to a unit-specific one and it's now working correctly.
