### ISSUE TITLE
Aeldari - Ynnari - Wraithknight not available. Avatar should be removed.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#496]
**File:** Ynnari

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** Wraithknights don't show up as a selectable unit for Ynnari.
Avatar of Khaine isn't allowed to be used in an Ynnari army.

**Comment by FarseerVeraenthis** [comment]
Since the Wraithknight is a Lord of War, please ensure you're using a detachment that has a LoW slot.

The Avatar should be removed, for now, just don't select him :wink:
