### ISSUE TITLE
Imperium - Astra Militarum - Infantry Squad heavy weapon model count issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#497]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** Yes

**Description:** Astra militarum infantry squads count heavy weapons teams as 1 guardsman but cost the correct points as 2 guardsmen. This causes a list error that you dont have enough guardsmen in the squad

**Comment by alphalas** [comment]
update your data.
