### ISSUE TITLE
Drukhari issues - copied from #3908

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k-9e#5]
**File/Catalogue:** Drukhari v1

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** No

**Description:**

Copied from  BSData/wh40k-7th-edition#3908

- [x] Archon: Members is misspelled as Memebers in Court of the Archon. 36e8e80e356bea24364bb252f2b1e7b503aaae72
- [x] Succubus: Needs Splinter pistol set as default ranged weapon. 36e8e80e356bea24364bb252f2b1e7b503aaae72
- [x] Succubus: Missing "Lightning Dodge" and "No Escape" abilities. 36e8e80e356bea24364bb252f2b1e7b503aaae72
- [x] Kabalite Warriors: PL increments are incorrect. As I understand it, PL should increase once minimum is exceeded, not when maximum is reached. i.e. 1 Sybarite + 4 Warriors is 3 PL, 1 Sybarite + 5 Warriors should be 5 PL. 36e8e80e356bea24364bb252f2b1e7b503aaae72
- [x] Kabalite Warriors: Heavy Weapon naming looks bad on roster. Add a modifier to fix the name when it is selected? 36e8e80e356bea24364bb252f2b1e7b503aaae72
- [x] Wracks: Should Acothyst's Haemonculus tools be 0-1 as he has to swap them for his Weapons of Torture option as per RAW?  As the Acothyst has no ranged weapon, how can he swap it for Tools of Torment which is required RAW? I suggest RAI is that he swaps Haemonculus tools for one of the other options. Would need adding to #3748.
- [x] Wyches: Unit size should be 5-20, not 5-15. 36e8e80e356bea24364bb252f2b1e7b503aaae72
- [x] Beastmaster: Adding Khymerae pairs does not increment PL. 36e8e80e356bea24364bb252f2b1e7b503aaae72
- [x] Beastmaster: The Khymerae have a 5+ inv save, but the Beastmaster does not gain it, The way this is currently implemented makes it look as if he does when you add them as his free unit. Not sure how/whether this can be fixed.
- [x] Grotesques: Grotesque with Weapons of Torture needn't have weapon options other than Weapons of Torture. He can't replace his Monstrous Cleaver with both a Liquifier Gun and a Weapon of Torture at the same time.
- [x] Hekatrix Bloodbrides: Same PL increment issue as with Kabalite Warriors. 36e8e80e356bea24364bb252f2b1e7b503aaae72
- [x] Incubi: Klaivex should have Klaive as default weapon. 36e8e80e356bea24364bb252f2b1e7b503aaae72
- [x] Incubi: Incubi Model entry should be Max 9 Selections in Parent (currently 10 which causes a validation error). 36e8e80e356bea24364bb252f2b1e7b503aaae72
- [x] Kabalite Trueborn: Kabalite Trueborn should be max 19. 36e8e80e356bea24364bb252f2b1e7b503aaae72
- [x] Mandrakes: Should be 9 PL at 6+ models, not 10. 36e8e80e356bea24364bb252f2b1e7b503aaae72
- [x] Mandrakes: Should be "any of **your** Movement Phases" in From Out of the Shadows description. Also a missing whitespace in "at least **9"away** from". 36e8e80e356bea24364bb252f2b1e7b503aaae72
- [x] Sslyth: Shardcarbine should be one word. 36e8e80e356bea24364bb252f2b1e7b503aaae72
- [x] Sslyth: Sslyth who are included in the Court of the Archon have the same problem as with Khymerae for the Beastmaster, in that the way rules are grouped implies that the Archon (and any other models in the "unit") get a 5+ save.
- [x] Reaver: Individual Reaver upgrades should be max 1 per parent. Also, conceivably any Reaver can take them, so they should be included on the Special Weapons Reavers as well.
- [x] Scourge: Solarite Melee weapons should only be available if the model selects a pistol.
- [x] Cronos: Selection has no unit size, should be 1-3. 36e8e80e356bea24364bb252f2b1e7b503aaae72
- [x] Cronos: Spirit Syphon should be "hit **its** target" in the Description. 36e8e80e356bea24364bb252f2b1e7b503aaae72
- [x] Ravager: All weapon options should default to Dark Lance. 36e8e80e356bea24364bb252f2b1e7b503aaae72
- [ ] Ravager: Night Shield description should not have restriction to ranged weapons only according to RAW. However, other instances of this equipment *do* have the restriction, so it's possibly a typo.
- [x] Talos: PL does not scale as unit size increases. 36e8e80e356bea24364bb252f2b1e7b503aaae72
- [x] Talos: Only 1 macro-scalpel should be replaced by an alternative weapon, not both.
- [x] Talos: Twin liquifier gun should be "determine **its** AP" and "hits **its** target" in the description. 36e8e80e356bea24364bb252f2b1e7b503aaae72
- [x] Voidraven: Missing whitespace in Void Mine description "maximum of **10D6**" 36e8e80e356bea24364bb252f2b1e7b503aaae72
- [x] Raider: Weapon should default to Dark Lance. 36e8e80e356bea24364bb252f2b1e7b503aaae72
- [x] Raider; **Open-topped** description should be "apply to **its** passengers". 36e8e80e356bea24364bb252f2b1e7b503aaae72

- [ ] Dark Lance: It would seem neater to use a modifier to change the weapon type if it's equipped on a relevant vehicle rather than relying solely on the ability text to remind the player.
![image](https://user-images.githubusercontent.com/29306451/27202479-b721b0cc-5219-11e7-9888-b6878335817c.png)

**Comment by ilaunchbury** [comment]
@amis92, if you can make me an admin, I can tidy some of these up.

**Comment by Toreador13** [comment]
The Sslyth and Beastmaster issue is an issue with mixed units and using profiles for abilities. Wish it would actually list those like rules on the profiles. Only real way I can see to get around that is to make entries for each, and or a blank rule to reference that.....  not great.

**Comment by Toreador13** [comment]
Nevermind, seemed to be an issue with my battlescribe install. I am going to make court and beastmaster beast unit a no force org slot item.

**Comment by Toreador13** [comment]
All checked will be fixed on release of v3. 
Probably won't change the Dark Lance bit for now unless one of you do it. Leaving it like the rulebook is better IMO for now.
