### ISSUE TITLE
Bug Report: Issues adding second detachment. 

### ISSUE THREAD

**Issue by Sychophant** [BSData/wh40k-9e#50]
**File/Catalogue:** Warhammer 40,000 8th edition v1

**BattleScribe version:** 2.01.00.87

**Platform:** Windows 10

**Dropbox:** No

**Description:** After adding a first battalion detachment, any other detachment I add is only able to select battalion.  Here is a screenshot: https://www.dropbox.com/s/hbnnnc6ezsyna87/Detatchment%20Bug.png?dl=0

**Comment by cartag** [comment]
Click on Roster before clicking add. If you add with a detachment highlighted it will add a sub detachment.

**Comment by Sychophant** [comment]
Thanks
