### ISSUE TITLE
Imperium - Dark Angels - Deathwing Terminator wargear cost issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#502]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** Dark Angels Deathwing Terminators wargear.
When selecting any heavy weapon the initial storm bolter is never removed for points.
Indeed, the CML and Storm Bolter actually adds the cost of ANOTHER storm bolter.

**Comment by Thairne** [comment]
As is RAW. Again.

**Comment by Thairne** [comment]
This is as the rules tell us.
