### ISSUE TITLE
Imperium - Blood Angels - Lemartes MIA

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#507]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 1.03.90

**Platform:** Windows

**Dropbox:** No

**Description:** Lemartes is not available under HQ or anywhere else. 

BattleScribe v2.01.03.90

**Comment by IronWulfen88** [comment]
Did you put chapter blood Angels. Sometimes the specific BA hq don't show up if you dont

**Comment by jheifner89** [comment]
I am using the Blood angels v5 chapter.
![untitled-2](https://user-images.githubusercontent.com/29756358/27643782-9fb79244-5be7-11e7-932b-c45457ccb715.jpg)

**Comment by Crowbar90** [comment]
Lemartes is available. You have to select Blood Angels chapter (it's in No Force Org), as stated in Battles error message and he will appear. The same applies for all other Blood Angels specific characters and for Gabriel Seth.
