### ISSUE TITLE
T'au Empire Hammerhead ion cannon missing overcharged profile

### ISSUE THREAD

**Issue by nottsknight** [BSData/wh40k-9e#513]
**File/Catalogue:** T'au Empire.cat

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** Yes

**Description:** See issue title.

**Comment by amis92** [comment]
Yeah, my bad. I hid it 'cause it was late and I thought "oh but Tiger Shark may not use Nova profile, lets hide it" and then I've done that to cannon instead of accelerator's Nova profile. -.-

Aaand also obiously noone except Riptide has access to Accelerator, so it was all rather moot point.
