### ISSUE TITLE
Chaos - FW Renegade and Heretics - Typo

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#518]
**File:** Chaos - FW Renegade and Heretics.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** In renegade & heretics disciples is misspelled. Should be spelled "Disciple". Current is spelled Diciple. (no "S").

**Comment by Penallegion** [comment]
Corrected where i could find
