### ISSUE TITLE
Chaos - FW Renegade and Heretics - Earthshaker Carriage Battery

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#519]
**File:** Chaos - FW Renegade and Heretics.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** There is no entry for Earthshaker Carriage Battery.

**Comment by Penallegion** [comment]
it's not in there since the choice is not listed RAW, will have a look at it.

**Comment by jimbojoneshost** [comment]
FAQ adds it as a legal choice for Renegades and Heretics, along with the following other units:

Page 81
 – Renegades and Heretics Army List
Add the following units to the list of those that can have 
the
 Renegades and Heretics 
keywords:
 •   Armageddon Pattern Medusa
Imperial Armour – Index: Forces of the Astra Militarum
  •   Earthshaker Carriage Battery
Imperial Armour – Index: Forces of the Astra Militarum
  •   Medusa Carriage Battery
Imperial Armour – Index: Forces of the Astra Militarum
  •   Macharius Heavy Tank
Imperial Armour – Index: Forces of the Astra Militarum
  •   Macharius Omega
Imperial Armour – Index: Forces of the Astra Militarum
  •   Macharius Vanquisher
Imperial Armour – Index: Forces of the Astra Militarum
  •   Macharius Vulcan
Imperial Armour – Index: Forces of the Astra Militarum

Source: https://17890-presscdn-0-51-pagely.netdna-ssl.com/wp-content/uploads/2017/07/40K_8th_ed_Update_Imperial_Armour_Index_Forces_of_the_Astra_Militarum_ver_1.0.pdf

**Comment by Penallegion** [comment]
will be implemented via #815
