### ISSUE TITLE
Tyranids - Wargear Issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#524]
**File:** Tyranids.catz

**BattleScribe version:** 2.01.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** In the wargear options for the Tyranid Warrior and Tyranid Prime its states that either of these selections may trade in its devouer for and item from the basic bio weapons list. Scything talons IS a selection from the basic bio weapons list. Doing this means the model now has two sets of scything talons. Further. The wargear options allow these models to replace their ORGINAL set of scything talons for an item from the melee bio weapons list which includes rending claws. Thus, the weapon combonation of scything talons and rending claws is allowed despite your builder claiming otherwise. Further, your builder states that these models MUST have a ranged weapon selection and are not allowed two melee weapon selections which is clearly not the case when simply trading in the devourer alone for another set of scything talons gets you to melee weapons. Best to you and thanks for you hard work. I hope to see these addressed in the next version for the nids. Rj Harris.

**Comment by GenWilhelm** [comment]
>the weapon combonation of scything talons and rending claws is allowed despite your builder claiming otherwise.

Using your process (ie. replace the devourer with scything talons, then replace the original talons with rending claws), it is possible to have both scything talons and rending claws. However, it does throw errors if you instead select the other, original set of scything talons, so I'll update the logic to stop it from doing that.

The other part, about having two selections from the Melee Bio-weapons list, I have reservations about, as the wording on the datasheet implies that it may only take one weapon from the list.
