### ISSUE TITLE
Aeldari Craftworlds - Adding/Subtracting Models from Units does not update wargear point costs

### ISSUE THREAD

**Issue by Miyth** [BSData/wh40k-9e#53]
**File/Catalogue:** Aeldari Craftworlds

**BattleScribe version:** 2.00.

**Platform:** iOS

**Dropbox:** No

**Description:** 

Currently confirmed with Dark Reapers and Dire Avengers, adding/subtracting basic models from the unit is not factoring in wargear.

A dire avenger should consist of its base cost (10) plus its avenger shuriken catapult (7). Subtracting a Dire Avenger from the unit results in a drop of 10 points (from 85 to 75). Dropping to one Dire Avenger leaves 45 points. (The cost of 1 DA + 5 catapults).

Conversely, adding Dire Avengers beyond the first increments the unit cost by 10.

The first Dire Avenger model added back to a completely empty Dire Avenger unit properly costs 17 points.

**Comment by FarseerVeraenthis** [comment]
If this is with Craftworld as a parent it's bad news, if it is as a child it is a battlescribe bug. 
Is Craftworld your only CAT?

**Comment by Miyth** [comment]
Ahh, this is with Craftworld as a child of a Ynnari detachment- so it sounds like it's Battlescribe's bug.

**Comment by FarseerVeraenthis** [comment]
The Ynnarii CAT just got posted to github so once it is picked up by appspot you can do a Ynnarii army from one CAT :+1:
