### ISSUE TITLE
Deathwatch - Land Raider Redeemer Sponsons

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-9e#531]
**File/Catalogue:** Imperium - Deathwatch

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** Yes

**Description:** Land Raider Redeemer should have Flamestorm Cannons, instead of Twin Lascannons.

**Comment by FarseerVeraenthis** [comment]
Duplicate of #477
