### ISSUE TITLE
Tyranids - Tervigon Points Incorrect?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#543]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** No

**Description:** Tervigon Massive Scything Talons point value is incorrect. It should be 22 points.

**Comment by GenWilhelm** [comment]
They are 22pts.

![terv](https://user-images.githubusercontent.com/22036809/27682461-8404bc10-5cba-11e7-81c9-ecc0c5280387.png)
