### ISSUE TITLE
Imperium - FW Elysians - Twin lascannon wrong cost; Company Commanders boltgun option missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#544]
**File:** Imperium - FW Elysians.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** Point values for twin lascannons are incorrect. Currently they are priced at 50 points, they should be 40 points(Imperial Armour Index: Forces of the Astra Militarum Pg 111) . Also Company commanders do not have the option for a bolt gun though it is listed in the ranged weapons available to Elysians (Imperial Armour Index: Forces of the Astra Militarum Pg 119).

**Comment by alphalas** [comment]
where do you see this? it clearly has no restrictions; may exchange laspistol for one item on the raged list.
