### ISSUE TITLE
Imperium - Space Marines: Primaris lieutenant issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#546]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** Primaris lieutenants carry the following
Bolt pistol range 12 type pistol 1 S 4 AP 0 D1
Frag grenade range 6 type grenade D6 S3 AP 0 D1
Krak grenade range 6 type grenade 1 S6 AP -1 D D3

none of that is listed

Also the Lieutenants are listed as having master crafted auto bolt rifles that cost 4 points, they only have "auto bolt rifle" for 0 points. The power sword variation is correct and does cost 4 points. Also the base model is 60 points, it is currently listed at 74

**Comment by flakpanda** [comment]
While I did forget to add the bolt pistol and grenades, you are still wrong about the rest.
<img width="514" alt="screen shot 2017-06-29 at 12 00 13 am" src="https://user-images.githubusercontent.com/19719565/27672075-0a6f589e-5c5e-11e7-9c41-4a7af5812d94.png">
<img width="255" alt="screen shot 2017-06-29 at 12 00 39 am" src="https://user-images.githubusercontent.com/19719565/27672074-0a6cc9e4-5c5e-11e7-98ec-a61b8f5c5327.png">
