### ISSUE TITLE
CSM - Cypher Plasma pistol strength

### ISSUE THREAD

**Issue by likwid-dzign** [BSData/wh40k-9e#551]
**File/Catalogue:** Chaos - Chaos Space Marines

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** Yes

**Description:** Currently Cypher's plasma pistol profile incorrectly shows strength as "38" instead of "8".

**Comment by FarseerVeraenthis** [comment]
but, but, but, it is a really special pistol...!
