### ISSUE TITLE
Imperium - Space Marines - Thunderfire Cannon Cost Question

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#553]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** Thunderfire cannon costs to much. The techmarines has a servoharness, wich helt should till have and THE techmarine Also cost to much

**Comment by ilaunchbury** [comment]
Cost appears to be correct. 

Techmarine is 36pts + 40pts of wargear (9 for Flamer, 7 for plasma cutter, 2 X 12 for servoarms). This is effectively a servo-harness, so is displayed as such.
Thunderfire Cannon is 28pts plus 30pts for the cannon itself.

Total points: 134
