### ISSUE TITLE
Astra Militarum Output Errors?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#554]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** Tempestus Scion stat lines for Hot-shot Lasguns and Hot-shot Volley Guns do not appear in the html rendering of my army list.

**Comment by flakpanda** [comment]
Please make sure you are not running in Low Memory Mode.

**Comment by jppatterson28** [comment]
Low memory mode box is unchecked.

**Comment by jppatterson28** [comment]
And all of my settings are set to display as much info as possible.
