### ISSUE TITLE
Request: Alphabetisation manipulation for detachments

### ISSUE THREAD

**Issue by BaconCatBug** [BSData/wh40k-9e#563]
As of v2.01.03 of Battlescribe, dropdown menus are now sorted alphabetically. Yay. 

However, Detachments are not optimally sorted alphabetically, rather they should (imho) sorted as they appear in the rulebook (Patrol, Battalion, Brigade, Vanguard, Spearhead, Outrider, Supreme Command, Super-Heavy, Air Wing, Super Heavy Aux, Fortification Network, Aux Support, Unbound).

While I fully expect this to not be possible to do in a clean way, I felt I might as well ask as you guys seem to be awesome technomaguses of the highest order.

**Comment by GenWilhelm** [comment]
Nothing to do with us, I'm afraid. The order you mention (from the book) is the order we had them in before the update, and is still their order in the game system. There's pros and cons to each way of doing it, so each person may differ on their preference.

Feel free to voice your opinions on the BattleScribe uservoice page: https://battlescribe.uservoice.com/forums/55066-general

**Comment by BaconCatBug** [comment]
Might there not be a work around by prefixing each detachment with a different chess symbol?

**Comment by alphalas** [comment]
No

**Comment by amis92** [comment]
@BaconCatBug the longer answer is that such a workaround *is possible* but then we are on a path of personal preference which order exactly is *the most appropriate*. Right now it's quite clear it's the rulebook one, but soon we'll get grips on actual codexes which will introduce new detachment types.

Any order is arbitrary, but alphanumerical one is the most neutral. I hope that answer gives you good enough reasoning. :)
