### ISSUE TITLE
Space Wolves Wolf Guard Terminator Options incorrect?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#564]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** Wolf Guard in terminator armor should have access to the "terminator heavy weapons list". In the war gear options last bullet point allows one wolf guard for every five models to either take a cyclone missile launcher or replace their storm bolter with an item from the terminator heavy weapons list.

**Comment by penguin20000** [comment]
There's a separate option to add a Wolf Guard with Heavy Weapon.
