### ISSUE TITLE
Blood Angels Assault Squad Sgt Choices

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#565]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** No

**Description:** Sergeants in a regular Assault Squad are currently limited to either bolt pistol and chainsword or an eviscerator.  According to Imperium Index 1 the sergeant may replace his bolt pistol with items from the Melee Weapons or Pistol list (which for Blood Angels includes Inferno Pistol and Hand Flamer), and may also replace his chainsword with items from the Melee Weapons list.

**Comment by Crowbar90** [comment]
Just select Regular Wargear under Space Marine Sergeant. All weapon options are there.
