### ISSUE TITLE
Aeldari - Ynnari - Windriders Wrong Cost

### ISSUE THREAD

**Issue by KalChoedan** [BSData/wh40k-9e#574]
**File/Catalogue:** Aeldari Ynnari v11

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** Windriders are being costed at only the points value of the model and not including the weapons cost. So a scatter laser windrider is 20pts, a shuriken cannon windrider is 20 pts etc. Whereas they should be 20 pts per model + 10 for twin shuriken catapult, 12 for shuriken cannon, 15 for scatter laser.

**Comment by FarseerVeraenthis** [comment]
Is this in a child force?

**Comment by KalChoedan** [comment]
In an Outrider detachment (top level).

![image](https://user-images.githubusercontent.com/1786901/27744292-d8ef387a-5db6-11e7-876d-3b57a1be7eb3.png)

**Comment by GenWilhelm** [comment]
The Windrider being in bold suggests they have weapon options that aren't being enforced.

**Comment by KalChoedan** [comment]
Right - I don't entirely understand how it's structured, but from a user perspective it seems as though the weapon choice has additionally been placed into a submenu that isn't enforced or automatically selected. You can toggle this option to 1 which results in correct costings:
![image](https://user-images.githubusercontent.com/1786901/27746444-268e3506-5dbf-11e7-8466-a2ec98f9b157.png)

**Comment by GenWilhelm** [comment]
Yeah, having the weapon selection be anything other than 1 would create an illegal list. This behaviour is pretty typical of when a weapon is linked to a unit, but minimum and maximum restriction aren't put in place, it's a simple fix.

**Comment by USSX-Hares** [comment]
@GenWilhelm @FarseerVeraenthis @KalChoedan is it reproduced in Craftworlds?

**Comment by USSX-Hares** [comment]
Reproduced. Investigated. Fixed.

**Comment by USSX-Hares** [comment]
There was a problem in merging two implementations of shared / collective items. One does have min/max set up inside, and one does have min/max set up beside the entry link.

**Comment by USSX-Hares** [comment]
Forget to create a Merge Request
@FarseerVeraenthis, please, accept

**Comment by FarseerVeraenthis** [comment]
Merged :smile:
