### ISSUE TITLE
Blood Angels Named Characters missing from App

### ISSUE THREAD

**Issue by ln1000000** [BSData/wh40k-9e#576]
**File/Catalogue:** Blood Angels

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** Blood Angels named Characters (ex. Commander Dante) are not showing in BattleScribe roster editor despite being included in the CATZ data file.

**Comment by GenWilhelm** [comment]
You need to select which chapter you are, under "No Force Org Slot".

@Crowbar90, perhaps you could assume people are playing regular Blood Angels unless they select Flesh Tearers. It's best not to have a lot of stuff hidden by default.

**Comment by Crowbar90** [comment]
Hmm, that's probably right. I'll make the change as soon as I can find some time.

**Comment by amis92** [comment]
From #585:

Would inverting the condition help?

So that you see Lemartes (and others) immediately, but get a warning that they require Faction: Blood Angels taken?

It leads to better discoverability. Unless that's not working in BS which it well may be.

**Comment by Crowbar90** [comment]
I was thinking of removing the distinction altogether - after all, nothing says you can't take some Flesh Tearers in a Blood Angels detachment. This would lead to a situation where all generic marine abilities refence <CHAPTER> units, all BA abilities reference BLOOD ANGELS and Gabriel Seth references FLESH TEARERS. It's not optimal, but maybe it's the easiest solution.

**Comment by alphalas** [comment]
*TECHNICALLY*, Seth should be in both the SM and BA cat -  there is nothing that says you have to take flesh tears as Blood Angel second foundings. Most people would because well that's the way it's intended to be, however, you don't have to. I'm actually considering running a detachment of flesh tearers with storm talons and other things that blood angels can't take to keep my color schemes similar

**Comment by amis92** [comment]
I thought there was some constraint that a single detachment must contain only one chapter. In generic Astartes at least.

Sent from my Windows 10 phone

**Comment by alphalas** [comment]
There is - you can't have Seth and Lem in one detachment

**Comment by Crowbar90** [comment]
Why not? If I build my detachment using the Adeptus Astartes keyword, I can have as many different <CHAPTER> keywords as I want.

**Comment by alphalas** [comment]
Because GW is dumb: 
![img_1370](https://user-images.githubusercontent.com/15703066/27794449-3b39ace8-5fd0-11e7-9529-b804e4fb58d1.PNG)

**Comment by alphalas** [comment]
So, if detachment = FT using BA rules; no Dante allowed. If FT =/= BA, Seth and Dante in 1 detachment Bueno

**Comment by Crowbar90** [comment]
Pushing a fix for this now. Every special character will be visible without validation errors unless Select Chapter is in the roster; in that case, only the selected chapter's characters will be shown.
