### ISSUE TITLE
Imperium - Space Wolves - Can leaders take multiple wolf claws?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#578]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Under Space wolves melee options there needs to be an option for a pair of wolf claws that costs 13 points. This specifically doesn't show up under sky claws for the pack leader or the wolf Guard sky leader. You have the option for a single wolf Claw at 9 points which is correct, but there is also the option for a pair of wolf claws under the space wolves melee weapon in the I dew imperium I book.

**Comment by penguin20000** [comment]
The models in question can only swap one weapon for a melee weapon so they can't take two.
