### ISSUE TITLE
Chaos - Death Guard - Plague Champion should have access to combi-weapons

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#579]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** Plague Marines Plague Champion should have access to combi-type weapons when replacing bolt pistol and boltgun (according to champion equipment he might select 2 normal weapons, or 1 combi-type)

**Comment by cartag** [comment]
Duplicate of #533
