### ISSUE TITLE
Imperium - Adeptus Custodes Shield Captain Storm Shield points value should be 5

### ISSUE THREAD

**Issue by MJMahoneyCodes** [BSData/wh40k-9e#58]
File/Catalogue: Imperium - Adeptus Custodes.cat 

BattleScribe version: 2.01.02

Platform:N/A

Dropbox:N/A

Description: 
The points value for  "`<selectionEntry id="cd6d-3b32-3e8f-7be5" name="Storm Shield" hidden="false" collective="false" type="upgrade">`" is 10. This is a Shield Captain's Storm Shield option. It should be 5 points and not 10 points. 

The Storm Shield points value for a Custodian's Storm Shield is 5 points as expected, and does not need to be changed.

**Comment by GenWilhelm** [comment]
Edited the OP to fix formatting.

**Comment by ziggurattt** [comment]
Whoops, the specific item is id cd6d-3b32-3e8f-7be5.
