### ISSUE TITLE
[Space Marine] Scouts have incorrect points for multiple scouts with sniper rifles if used in a combined detachment.

### ISSUE THREAD

**Issue by athelred** [BSData/wh40k-9e#581]
**File/Catalogue:** Imperium - Space Marines v9

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** 

Steps to reproduce.

1. Add a Patrol detachment of Imperium - Inquisition (this works with any detachment I have tested)
2. Add Space marines to the inquisition detachment.
3. Add a Scout Squad to the detachment.
5. Add 2 Scout w\ Sniper Rifle.

The first Scout with sniper rifle has the correct points, 15.  The second and (subsequent) only adds the base cost of the scout, 11.  It does not add the weapon costs for the additional scouts.  It lists it as 4x sniper rilfle (4pts).  It works correctly if the Space marine detachment is a separate detachment, regardless of other detachments.

I think this will also show up anywhere you have multiple model entries with weapons already included.  A similar issue occurs with the fallen w/ Lightning claws, if you add the fallen, select their Lightning claws options, and then modify the number of models.

**Comment by GenWilhelm** [comment]
It's a known bug for nested forces. If you save and reload the roster, it should update the cost of the unit.

https://github.com/BattleScribe/Desktop-Alphas/issues/166
