### ISSUE TITLE
Chaos - Chaos Space Marines: problem swapping weapons on Noise Marines

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#582]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** when adding equipment to noise marines its only letting me swap one boltgun to a sonic blaster when you should be able to swap all boltguns with sonic blasters.

**Comment by cartag** [comment]
Working fine for me.
