### ISSUE TITLE
Orks - Chinork has wrong battlefield role

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#583]
**File:** Orks.catz

**BattleScribe version:** 2.01.03

**Platform:** Android

**Dropbox:** Yes

**Description:** The Chinork Warkopta is at the moment in the Fast Attack listed, but the Index Xenos from forgeworld lists it as a dedicated transport unit.

Thank you for your help.

**Comment by tag8833** [comment]
Whoops.  I'll get it fixed on Monday.
