### ISSUE TITLE
Blood Angels - Lemartes does not appear

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#585]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** Lemartes is missing from the HQ Entries for Blood Angels

**Comment by flakpanda** [comment]
Please make sure from under No Forge Org you are selecting a faction.

**Comment by amis92** [comment]
Would inverting the condition help?

So that you see Lemartes (and others) immediately, but get a warning that they require Faction: Blood Angels taken?

It leads to better discoverability. Unless that's not working in BS which it well may be.

**Comment by amis92** [comment]
Oh, I've missed #576. I'll merge it with that one, I think it's the same problem.
