### ISSUE TITLE
Imperium - Space Wolves - Njal Stormcaller weapon

### ISSUE THREAD

**Issue by LokiTarrishar** [BSData/wh40k-9e#586]
**File/Catalogue:** Space Wolves

**BattleScribe version:** 2.01.04

**Platform:**iOS

**Dropbox:** 

**Description:** 
Njal's unique melee weapon, Staff of the Stormcaller stat profile missing from summary for both normal and terminator entries.

**Comment by flakpanda** [comment]
Also to add on to this. It allows me to add more than one Njal (either/both versions) without validating that i cannot.
