### ISSUE TITLE
Aeldari - Craftworlds - Dark Reaper points cost not incrementing correctly in child detachment

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#589]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.01.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** In the craftworld aeldari list, the cost of Dark Reapers is wrong. It only adds 5 points for the additional model, but not the cost of the gun, which makes each model cost 36 points. The initial cost for the minimum squad appears to be correct, and only adding additional models seem to be incorrect.

**Comment by FarseerVeraenthis** [comment]
Is this in a child detachment?

**Comment by edward3h** [comment]
I'm seeing the same issue, and yes it was in a child detachment.

**Comment by FarseerVeraenthis** [comment]
Child detachments are bugged, but I'll see if there's anything I can do...

**Comment by amis92** [comment]
I'd say it's https://github.com/BattleScribe/Desktop-Alphas/issues/166
