### ISSUE TITLE
Points costs off for questor traitoris and fellblade

### ISSUE THREAD

**Issue by cerosoul** [BSData/wh40k-9e#590]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
![img_0138](https://user-images.githubusercontent.com/29809122/27758937-628b6562-5dd6-11e7-8570-fcb6b4975bad.PNG)
![img_0139](https://user-images.githubusercontent.com/29809122/27758954-d37e3682-5dd6-11e7-8f99-68e5afc45e14.PNG)

**Comment by cartag** [comment]
Forgot weapons I'm guessing?
