### ISSUE TITLE
Aeldari - Craftworlds.cat Points Cost Bug

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-9e#597]
**File/Catalogue:**  Aeldari - Craftworlds.cat

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** There seems to be a broad issue in Craftworlds detachments where changing the composition of a squad results in models incrementing at incorrect points costs. I've specifically encountered this in Shining Spear and Windrider squads so far. Upon further examination what appears to be happening is that when a craftworld detachment is used as a child adding or subtracting a shining spear doesn't add or subtract the cost of those weapons, instead always remaining at 3 laser lances and Twin shuriken catapults

 Edit: This seems like it might be related to #589 as it is in a situation where the Craftworld detachment is a child of another Aeldari one.

**Comment by GenWilhelm** [comment]
It's a known bug for nested forces. If you save and reload the roster, it should update the cost of the unit.

https://github.com/BattleScribe/Desktop-Alphas/issues/166
