### ISSUE TITLE
Astra Militarum Feedback

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-9e#6]
- [ ] Hot Shot Las Pistol should cost 1 point.
- [ ] I would love an option to inculde the list of Orders with the roster.
- [x] Commisar Yarrik missing "Hero of Hades Hive" ability. 
- [x] Lord Commisar, Tempestor Prime, Commisar:  Chainsword has no profile.  In fact no items on the Melee weapons list has a profile.
- [x] Hot Shot Lasgun and Hot Shot Las Pistol profile incomplete.  S3  Ap-2  D1
- [ ] Taurox Prime has the wrong BS in it's damage table.  It should be 1 better.  Starts at 3+.
- [x] Nork Deddog is missing his "Huge Knife"
- [ ] Deathstrike is missing a damage chart.
- [ ] Armoured sentinal should default to multi-laser
- [ ] No profiles for Sentinal weapons
- [x] Rough Riders should be grouped.  The min unit size is 5.  2 of them can have special weapons.
- [x] Conscripts have no wargear.  Should have Lasgun and Frag Grenade.
- [x] Platoon and Company Commander should have frag grenades.
- [x] Company commander has no Power Level
- [ ] Says that the maximum number of transports is 1 (Taurox/Chimera both)
- [ ] Valkyrie Heavy Bolters are 24 points for a pair. They should cost 16 points per pair (HB at 8 points each)
- [x] Lord Castellan Creed is having multiple errors reported: "Lord Castellan Creed has 1 too many selections of Hot-shot Laspistol (maximum 1)" when value is changed to 1 error is report "must have 1 more selections of Hot-shot Laspistol (minimum 2) when two are selected."
- [x] Elite choice Commissar has no power point. Should be 2.
- [x] Astra Militarum Infantry Squad not labeled as troops and not correctly costed at 40pts base.
- [x] Heavy Weapon Team doesn't charge for crew (eg lascannon should be 28 points (20+4+4) because you have to remove 2 guardsman from the guardsmen section for it to validate)
- [ ] Grenade Launcher is 1 pt too expensive at 10 points (should be 4+5 = 9)
- [ ] Astra Militarum Flamer in Infantry Squad entry should be 11 points (4 for model 7 for the weapon) not 14points.
- [ ] Tempestor with hotshot laspistol should be 10pts (9 + 1 for hotshot laspistol)
- [ ] Special weapons are soft limited to 2 total in a 10 man squad (should be 4) - allows it but lists it as an error.
- [ ] Special weapons are hard limited to 2 of each type, even in a 10 man squad (should be 4 of each, but also 4 total)
- [ ] MT Scions -  They can take 2 special weapons for every 5 models in the unit.
- [ ] Scion with vox-caster should be 15pts (9+5+1)
- [ ] Scion with medi pack should be 20 pts (9 +1 for HS laspistol + 10 for medi pack)
- [ ]  Scion w/vox-caster should be 15pts (9+1 for HS laspistol +5 for vox-caster)
- [ ]  Hotshot Laspistol needs to cost 1pt
- [x] If you have two veteran squads and make changes to the special weapons it makes the same change to both squads.
- [x] Need the option to take a heavy flamer in addtion to their special weapon choices.
- [ ] Heavy weapons don't include the cost of the veterans - they should because you have to decrease the veteran count by 2 if you add a heavy weapon
- [ ] Veteran w/ Medi-pack is only 6 points, should be 16
- [ ] Veteran w/ Meltagun is only 6 points, should be 18
- [ ] Veteran w/ Plasma Gun is only 6 points, should be 13
- [ ] Veteran w/ Sniper Rifle is only 6 points, should be 5
- [x] Veteran Heavy Weapons team only has access to a Mortar
- [x] Veterans can take a vet with a heavy flamer.
- [ ] Pask should default to a Battle Tank.  
- [ ] Too expensive - The 167 point starting cost should include a Leman Russ .  You should only have to pay for the weapon options.  Currently it makes you pay for a whole tank.  A TC with a standard Russ (Battlecannon, lascannon, 2 x heavy bolters) should cost 225pts  - presently he costs 392pts
- [ ] Cost is all wrong - should start out as 177 plus weapons.  Currently starts at 185 plus the cost of a whole tank.  
- [ ] No option for sponson weapons
- Pask with a Battlecannon and Lascannon (currently there's no options for Heavy Bolters) should cost 219 pts - presently he costs 386pts
- [ ] Tank Orders text is incorrect - Pask is able to give orders to a Character (although the Knight Commander rules text is correct)
- [x] Bullgryns are missing some options.  They should be able to take a Grenadier Gauntlet & Bruteshield  or a Power Maul and Slabshield.  Also, it's not an ordianry Power Maul.  It is a bullgryn maul.
- [x] Ratlings should be grouped.  They have no options.  Make their sniper rifle collective.
- [x] Master of Ordnance had no power point cost. Should be 2.

**Comment by amis92** [comment]
_From @bowgs on June 15, 2017 10:23_

# **Bugs**

**Infantry Squad**

- [ ] Heavy Weapon Team doesn't charge for crew (eg lascannon should be 28 points (20+4+4) because you have to remove 2 guardsman from the guardsmen section for it to validate)
- [ ] Grenade Launcher is 1 pt too expensive at 10 points (should be 4+5 = 9)

**Scions**

- [ ] Tempestor with hotshot laspistol should be 10pts (9 + 1 for hotshot laspistol)
- [ ] Special weapons are soft limited to 2 total in a 10 man squad (should be 4) - allows it but lists it as an error.
- [ ] Special weapons are hard limited to 2 of each type, even in a 10 man squad (should be 4 of each, but also 4 total)
- [ ] Scion with vox-caster should be 15pts (9+5+1)

**Scion Command Squad**
- [ ] Scion with medi pack should be 20 pts (9 +1 for HS laspistol + 10 for medi pack)
- [ ]  Scion w/vox-caster should be 15pts (9+1 for HS laspistol +5 for vox-caster)


**Tempestor Prime**
- [ ]  Hotshot Laspistol needs to cost 1pt

**Veterans**
- [ ] If you have two veteran squads and make changes to the special weapons it makes the same change to both squads.
- [ ] Need the option to take a heavy flamer in addtion to their special weapon choices.
- [ ] Heavy weapons don't include the cost of the veterans - they should because you have to decrease the veteran count by 2 if you add a heavy weapon

**Tank Commander**
- [ ] Too expensive - The 167 point starting cost should include a Leman Russ .  You should only have to pay for the weapon options.  Currently it makes you pay for a whole tank.  A TC with a standard Russ (Battlecannon, lascannon, 2 x heavy bolters) should cost 225pts  - presently he costs 392pts

**Knight Commander Pask**
- [ ] Cost is all wrong - should start out as 177 plus weapons.  Currently starts at 185 plus the cost of a whole tank.  
- [ ] No option for sponson weapons
- Pask with a Battlecannon and Lascannon (currently there's no options for Heavy Bolters) should cost 219 pts - presently he costs 386pts

**Bullgryns**
- [ ]  It shouldn't be a choice between "Grenadier Gauntlet & Slabshield" and "Power Maul & Bruteshield".  It should be a choice of shield ("Bruteshield" or "Slabshield") and a choice of weapon ("Grenadier Gauntlet" or **"Bullgryn** Maul")

# **Style/Consistency issues**

**Ratlings**
- [ ]  Do we need a seperate entry for each Ratling? eg (Ratling, Ratling, Ratling).  Couldn't they be treated like the other infantry squads - eg 10 x Ratling.  It's not like they have any options

**Comment by Kharn009** [comment]
HQ Options
Unable to take Primaris Psyker

Elite Options
Unable to take Astropath or Wyrdvane Psykers

Company Command Squad
Veteran w/ Medi-pack is only 6 points, should be 16
Veteran w/ Meltagun is only 6 points, should be 18
Veteran w/ Plasma Gun is only 6 points, should be 13
Veteran w/ Sniper Rifle is only 6 points, should be 5
Veteran Heavy Weapons team only has access to a Mortar

**Comment by bowgs** [comment]
> @Kharn009 
Primaris Psyker, Astropaths and Wyrdvanes are part of Astra Telepathica, which can be added as a sub-faction so this isn't a bug.
The Veteran Heavy weapons team does have access to other heavy weapons, it's just the mobile interface is a bit clunky for selecting them.

**Comment by Kharn009** [comment]
@bowgs - Thanks for the tips for the Psykers and the Veteran HWS

Vanguard Transport Option
Says that the maximum number of transports is 1 (regardless of number of units in the detachment)

Chimera
Says that the maximum number of Chimeras is 1 (regardless of number of units in the detachment)

**Comment by alphalas** [comment]
@kharn009 I deleted your comments and rolled them into the initial bugrep
