### ISSUE TITLE
Dedicated Transport Rules don't allow correct # of Transports

### ISSUE THREAD

**Issue by foolsama** [BSData/wh40k-9e#60]
**File/Catalogue:** Warhammer 8th v1.0.0

**BattleScribe version:** v2.01.02.89

**Platform:** Windows

**Dropbox:** Yes

**Description:** Dedicated Transports are 1 per *unit* choice for battalions, not 1 per *force org slot*. Getting errors on Vanguard and Spearhead battalions. Tested with Adepta Ministorum and Space Marines.

**Comment by foolsama** [comment]
It appears to only be those two detachments - all other detachments work as intended for Dedicated Transport.

**Comment by GenWilhelm** [comment]
Could you give a specific example, or steps to reproduce the error?

**Comment by foolsama** [comment]
OK, Adeptus Ministorum, Vanguard Detachment. Take 1 HQ, and 6 Elite choices (I took Canoness, Hospitalier, Imagifier, Priest, Mistress and 2 squads of Repentia). I can then only add 1 rhino, when I should be able to add 7.

**Comment by GenWilhelm** [comment]
Okay, I see why the Vanguard isn't counting Elites atm. What about the other detachment - the Spearhead?

**Comment by foolsama** [comment]
Hmm, can no longer get the error with the Spearhead detachment
