### ISSUE TITLE
Ynnari Missing Wraithknights and Forgeworld units.

### ISSUE THREAD

**Issue by Jaystar007** [BSData/wh40k-9e#601]
WraithKnights are not available for Ynnari in battlescribe.  They are Aeldari so they count as qualifying to be Ynnari, "With the exception of..., any Aeldari unit can be part of an Ynnari army."  It goes on to say that they gain the Ynnari keyword but they do loose Ancient doom.

Just updated and noticed eldar includes the new forgeworld models but the Ynnari do not.  Not sure if you guys are working on it but they do qualify since they are Aeldari units.

**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by shadowseercb** [comment]
The Wraithknight is in the Lord of War slot so I have to take a different detachment.  Sorry about that.  

But yeah Ynnari dont have the forgeworld units in battlescribe yet.  Not sure if you guys are working on it but they do qualify since they are Aeldari units.

**Comment by GenWilhelm** [comment]
Yep, they'll be there eventually. As soon as Craftworlds has all their FW units completed, they'll be copied across into Ynnari. No sense in doing everything twice.

FW Craftworlds progress can bee seen on their own issue: #396.

**Comment by FarseerVeraenthis** [comment]
as of Ynnari file version 12, the progress on FW units matches that made on the Craftworld issue, referenced by Gen.
And yes, they do qualify and we are working on it, so I'm closing this issue and referring you #396
