### ISSUE TITLE
Astra Militarum-Pask and Tank commanders wrong point cost

### ISSUE THREAD

**Issue by Ursakarcreed** [BSData/wh40k-9e#61]
**File/Catalogue:** 

**BattleScribe version:** 2.00.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
Pask and tank commanders only pay for weapons in addition to their cost,not their cost+leman russ+weapons.

**Comment by alphalas** [comment]
rolled into #6
