### ISSUE TITLE
Imperium - Astra Militarum: Issue with transport validation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#62]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Error appears when selecting two taurox. "Dedicated transport have one too many selections of taurox (maximum 1)

This occurs when three troop slots have been selected.

**Comment by alphalas** [comment]
duplicate of #6
