### ISSUE TITLE
[Anon] Bug report: Chaos Bikers PL miscalculation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#627]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** Chaos Bikers though say they cost 7PL they are showing up as 2PL in the Roster and when I view their Data sheet.

**Comment by BaconCatBug** [comment]
>using Power Level

Well, there's your problem.

**Comment by alphalas** [comment]
@baconcatbug, that's enough- we have to support it, so bugreps like this are a good thing.
