### ISSUE TITLE
Imperium: SM Assault Sergeant - Eviscerator error

### ISSUE THREAD

**Issue by likwid-dzign** [BSData/wh40k-9e#628]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by flakpanda** [comment]
It appears to work fine. Please remember that you have to replace **BOTH** pistol and chainsword to take an eviscerator.
<img width="1498" alt="screen shot 2017-07-03 at 11 35 32 pm" src="https://user-images.githubusercontent.com/19719565/27815268-6c7531a6-6048-11e7-8dde-609b46a8b880.png">

**Comment by likwid-dzign** [comment]
I am stil receiving this error. I removed all other options, even restarted afresh.

I'm using Android 2.01.05, not desktop also. Updated catalogues.

**Comment by likwid-dzign** [comment]
![screenshot_20170706-125008](https://user-images.githubusercontent.com/29274769/27893559-c6317c7e-6249-11e7-829e-7a80b689d28f.png)
![screenshot_20170706-125038](https://user-images.githubusercontent.com/29274769/27893564-ce109218-6249-11e7-8235-b93b67953cbb.jpg)

**Comment by likwid-dzign** [comment]
![screenshot_20170706-125144](https://user-images.githubusercontent.com/29274769/27893586-f0331e4c-6249-11e7-8fcc-ba6b1edf915c.jpg)

**Comment by flakpanda** [comment]
I still cannot reproduce this error. Please make sure you have the most
current app and data version.
