### ISSUE TITLE
Imperium - Astra Militarum: Pask missing sponsons and has profile errors

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#63]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.00

**Platform:** Android

**Dropbox:** No

**Description:** Knight Commander paddle has no option to equip sponson weapons.

And his Ballistic Skill damage chart should read 2+, 3+, 4+, rather then 4+, 5+, 6+.

**Comment by ziggurattt** [comment]
He seems to be using the standard Leman Russ Stat Damage chart, but he has a custom one. See page 41 of the Index: Imperium 2 book.

**Comment by alphalas** [comment]
rolled into #6
