### ISSUE TITLE
Bug/Rules error in Chaos Space Marine data

### ISSUE THREAD

**Issue by TheBigBadPanda** [BSData/wh40k-9e#7]
**File/Catalogue:** 

**BattleScribe version:** 2.00.

**Platform:** Android (probably all)

**Dropbox:** No

**Description:** When attempting to set up a unit of Chaos Space Marines i do not seem to have any options for wargear for the champion at all, and am not able to give the squad two Heavy Weapons or two Special Weapons, only one of each.

**Comment by Kohato** [comment]
You're gonna want to make sure your app is actually updated.  Then try again and if there's still an issue, let us know.  We can't replciate it on the updated version of battlescribe.

![image](https://user-images.githubusercontent.com/16939161/27225950-26096c76-5262-11e7-8ac2-7cb8232f31ab.png)
