### ISSUE TITLE
Open the Reliquaries issue

### ISSUE THREAD

**Issue by McWerp** [BSData/wh40k-9e#7293]
**File/Catalogue:** Warhammer 40000 v1.5.2

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Open the reliquaries strategem for Adeptas Sororitas is incorrectly marked as maximum one. It can be used as many times as you have CP.

**Comment by alphalas** [comment]
It has a spinner inside it that you increment for multiple relics.

**Comment by McWerp** [comment]
Cool didnt see that!

________________________________
