### ISSUE TITLE
Epidemicyst Blade doesn't replace Hellforged sword for Daemon Prince

### ISSUE THREAD

**Issue by CallMeSophie** [BSData/wh40k-9e#7298]
**File/Catalogue:** Chaos - Death Guard.catz

**BattleScribe version:** 2.03.21.165

**Platform:** Windows

**Dropbox:** No

**Description:** The Epidemicyst Blade doesn't replace Hellforged sword for Daemon Prince of Nurgle. After picking Epidemicyst Blade as relic, you still see Hellforged sword as wargear

**Comment by Mad-Spy** [comment]
Yes, it's a limitation of the data format. Most Relics don't replace their appropriate wargear.
