### ISSUE TITLE
Adeptus Custodes - Shield-Captain on Dawneagle Jetbike/Captain-Commander Requirement?

### ISSUE THREAD

**Issue by Isphera** [BSData/wh40k-9e#7302]
**File/Catalogue:** Adeptus Custodes v46, 40k v128

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** Yes

**Description:** During setup of a Shield-Captain on Dawneagle Jetbike, the logic check throws up an error saying that I must select one more trait for Captain-Commander (minimum 1). However, this occurs when SC on Bike is not selected as a Captain Commander, therefore shouldn't get/need one. This also occurs if a Standard Shield Captain is added, made Captain-Commander and is given a trait - there is still an error specifically on the SC on Bike.

**Comment by Mad-Spy** [comment]
I am unable to replicate this issue using v46, either on Desktop or mobile. Not sure why this is happening.

**Comment by Isphera** [comment]
I think I've figured out the trigger point. My list also had a
sub-detachment of Sisters of Silence (within the Batallion). When I
recreated the list again but without it, I got no error. But when I added
in the Sisters detachment to the force of Custodes and refreshed (on
Mobile), the error appeared. Could they trigger it somehow?

**Comment by Mad-Spy** [comment]
Well, that is some weird interaction. It requires that validation if you add any child detachment. I'll see if I can track down the problem.
