### ISSUE TITLE
Imperium - Questor Imperialis: Heirlooms of the House not allowing relics on non-Warlord models

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7303]
**File:** Imperium - Questor Imperialis.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** the heirlooms of the house no longer un-hide relics when selected . tested on android and ios . can continue to select warlord but no longer on other models .

**Comment by Mad-Spy** [comment]
Have you selected "Heirlooms of the Household" on the specific models which you want to have the additional Relic? You need to do this in addition to selecting the Stratagem at the Roster level.
