### ISSUE TITLE
Craftworlds - Choosing a specific Craftworld in an unbound detachment/list causes an error

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#7312]
**File/Catalogue:** Aeldari - Craftworlds v93

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** If you try to take a named Craftworld as one of the options for the Craftworld Attribute in an Unbound (non-Battleforged) detachment , an error is thrown, stating:
>Craftworld Attribute must have 1 more selections of None (Mixed Detachment) (minimum 1).

This would cause Craftworld-specific units to be in a seemingly illegal list, as they would need a specific Craftworld to be able to be taken.

**Comment by alphalas** [comment]
Easy solution would be to have an Aeldari option that unhides everything.

**Comment by FarseerVeraenthis** [comment]
You're not battle forged, so you don't get the benefit of a craftworld attribute. You can select anyone you like, the list is unbound, as long as your opponent is happy you're playing an unbound army there is nothing to fix.

**Comment by Mad-Spy** [comment]
@FarseerVeraenthis, this was discussed in chat. The issue is that CW-specific choices are hidden based on the selector, so if you want to use them, you end up with a validation error on an otherwise perfectly valid list.

**Comment by FarseerVeraenthis** [comment]
They shouldn't be... Which ones are hidden?
Please update the bug report to state specifically which options are missing and I'll update the CAT to show them.

**Comment by FarseerVeraenthis** [comment]
![Screenshot_20200711-084830](https://user-images.githubusercontent.com/23246922/87219495-9c49b700-c353-11ea-8ec5-bf8c6c842b8b.png)
This is a non issue until you tell me which options are hidden.
