### ISSUE TITLE
Imperium, agents of the imperium

### ISSUE THREAD

**Issue by akessamenos** [BSData/wh40k-9e#7313]
**File/Catalogue:** Warhammer Imperium, agents of the imperium

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux all

**Dropbox:** Yes/No no

**Description:** Detailed issue description.

Adding an imperial agent triggers a validation error. Maximum number of agents of the Imperium is set to 0 In the attached file, one inquisitor triggers three errors. 
![agents](https://user-images.githubusercontent.com/25237544/87238006-9e972a00-c3c2-11ea-9051-2ed737f6d7d6.PNG)

**Comment by akessamenos** [comment]
Never mind. I smoke crack.

**Comment by akessamenos** [comment]
I started a new roster with an Inquisitor, and it was okay, until I removed him and added him to another detachment. Got the same error as previous.

**Comment by Mad-Spy** [comment]
This seems to be an odd app bug, to do with having child detachments. We're looking into it.

**Comment by akessamenos** [comment]
Cool, thanks!
