### ISSUE TITLE
Imperium - Blood Angels: Incursor with Haywire mine counts as two models

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7317]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** A blood angels incursor squad with 5 models(5 PL) increases to 10 PL as soon as I add a model with a haywire mine, and it is impossible to bring back the PL to 5 even if there are only 5 squad members in total (1 sgt, 3 incursors and 1 incursor with the mine). Such a squad should cost 5 PL

**Comment by Mad-Spy** [comment]
The Haymine mine is defined as a model, so that Incursor is counting twice towards the total number of models in the squad.
