### ISSUE TITLE
Imperium-Deathwatch Terminator loadout options

### ISSUE THREAD

**Issue by DenymW** [BSData/wh40k-9e#7325]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

Some legal terminator load outs are not supported specifically with equipment trades listed:

Terminator>exchange storm bolter for cyclone missile launcher and storm bolter > exchange power fist for meltagun and powerfist>exchange stormbolter and powerfist for thunderhammer and stormshield >Creates heavy weapon terminator with cyclone missile launcher, meltagun, thunder hammer and storm shield

Terminator>exchange storm bolter for cyclone missile launcher and storm bolter > exchange power fist for meltagun and powerfist>Creates heavy weapon terminator with cyclone missile launcher, storm bolter and meltagun

Terminator> exchange power fist for meltagun and powerfist>exchange stormbolter and powerfist for thunderhammer and stormshield >Creates terminator with meltagun, thunder hammer and storm shield

**Comment by Mad-Spy** [comment]
~~All of those are supported. You can add a Cyclone to any Terminator, not just the heavy weapon one.~~

read the issue wrong

**Comment by DenymW** [comment]
can't add the melta-guns is the issue

**Comment by Mad-Spy** [comment]
We're in the middle of discussing this, there's no need to open a new issue.

**Comment by Mad-Spy** [comment]
The "Power fist and meltagun" is clearly a single option when it's modelled. You can't rip the meltagun off its mount on the fist and strap it to the hammer or shield, despite GW clearly overlooking the TFG potential of their blanket ruling.

**Comment by DenymW** [comment]
I actually converted a wrist mounted storm bolter from a grey knight terminator arm into a wrist mounted melta using inferno-pistol parts and had the hand hold the thunder hammer and other arm with a vanguard vet storm shield
