### ISSUE TITLE
FW:Elysian - FAQ Changes

### ISSUE THREAD

**Issue by lewis0460** [BSData/wh40k-9e#7328]
**File/Catalogue:** FW Elysian

**BattleScribe version:** 2.03.

**Platform:** MAC

**Dropbox:** NO

**Description:** Updates from the new imperial armour index FAQ.

Elysian Drop Troops Sniper Rifle update
Tauros Venator - Removal of Targeting Rule
Blast weapon keywords.
Aircraft keywords.

**Comment by Mad-Spy** [comment]
This content will not be released until 9th drops after on the 25th July, because most of it doesn't apply until then.
