### ISSUE TITLE
GST - Stronghold Assault profiles

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-9e#7330]
We still have Stronghold Assault profiles in the gamesystem file, which are definitely not used anywhere in *out* files.

Doing #5233

**Comment by DrTobogganMD** [comment]
Done

**Comment by amis92** [comment]
https://github.com/BSData/wh40k/issues/5233#issuecomment-660259860

@DrTobogganMD so what you're saying is these profiles are used somewhere?

**Comment by DrTobogganMD** [comment]
Things like the Void Shield generator were published in stronghold Assault. The game mode isn't used anymore and the detachments are bunk, but the profiles for buildings don't have any other source for publishing. So while we can remove the game modes and stuff like that, the publication should probably stay put for now until they are reprinted.
