### ISSUE TITLE
AM - Severina Raine publication

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-9e#7331]
`<publication id="53e9d88f--pubN183884" name="GW Datasheet"/>` is a publication for Severina Raine.

Please change the name to be explicit in *what* datasheet it is. Also I'd suggest using PublicationUrl (new field) to reference specific PDF.

Additional Astra Militarum (By The Ways):
- AM Library: `War Zone Damocles: Mont'ka` is set on Baneblade. My guess is, it's a deprecated fact.
- AM Library: `Codex: Leafblower` - it's set on `Vehicle Equipment List` SSEG; maybe it's time to remove it.
- AM Library: `Codex: Imperial Guard` is used in non-library AM:
  - Company Commander
  - Platoon Commander
  
  Which is also not up-to-date, I guess.

Doing #5233

**Comment by alphalas** [comment]
@amis92 iirc Raine does not have a datatsheet that has been released other then the one physically in her book (no official digital)

**Comment by DrTobogganMD** [comment]
https://www.games-workshop.com/resources/PDF/40k/40K_AM_Severina_Raine_Datasheet_ENG.pdf

This is her official Sheet.
