### ISSUE TITLE
Aeldari - Ynnari: Ynnari warlord and relic issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7351]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Ynnari armies consisting of one Harlequins detachment and one Craftworlds detachment cannot give their free relic to a character in the Craftworlds detachment if their warlord is in the Harlequins detachment despite both units sharing the YNNARI keyword. The reverse (Warlord in Craftworlds, relic in Harlequins) appears to function fine. Relics purchased for the Craftworlds detachment using the "Artefacts of Death" stratagem also appear to function fine.

**Comment by FarseerVeraenthis** [comment]
Likely this is tied to the separate selector for Ynnari warlord.
This selector should be rolled into standard warlord selection logic prior to the release of 9th Ed data.

**Comment by DrTobogganMD** [comment]
Combined into #8056
