### ISSUE TITLE
Chaos Knights - Knight Despoiler has incorrect Power Level cost

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#7352]
**File/Catalogue:** Chaos - Chaos Knights v35

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Knight Despoiler costs 25 PL, but should cost 23 PL

**Comment by Mad-Spy** [comment]
Already fixed it ;)
