### ISSUE TITLE
Black Templar Chaplain auto-select illegal Litany

### ISSUE THREAD

**Issue by VictorNiall** [BSData/wh40k-9e#7355]
**File/Catalogue:** wh40k-master / Imperium - Black Templars.cat

**BattleScribe version:** 2.03.

**Platform:** Windows
**Dropbox:** No

**Description:** 

Black Templar Chaplains appear to auto-select the Imperial Fists Chaplain only litany "Fortress of Resolve" which should not be available to them.

Thanks!
![image](https://user-images.githubusercontent.com/4655447/88130794-11fa2200-cba1-11ea-81fb-b9cb9b9853d8.png)

**Comment by acebaur** [comment]
It is available to them as they are a successor of the Imperial Fists. The FAQ of Faith and Fury only disallows BT from using the Imperial Fists supplement. The chapter litanies are found in Faith and Fury and are not restricted by that FAQ
