### ISSUE TITLE
DG - Chaos Decimators lack Hateful Assault Special rule

### ISSUE THREAD

**Issue by Streyder** [BSData/wh40k-9e#7357]
**File/Catalogue:** Chaos - Death Guard v86

**BattleScribe version:** 2.03.21-166

**Platform:** Windows

**Dropbox:** No

**Description:** Chaos Decimators lack the Hateful Assault Special Rule. They have the Death Guard Keyword so they should get it

**Comment by Mad-Spy** [comment]
Forgeworld models have never had an update which grants them the Hateful Assault rule. Currently, only Codex units have it.

**Comment by Mad-Spy** [comment]
Added to all FW models as per their update, which I had missed.
