### ISSUE TITLE
Drukhari - 9th edition QA points/PL check for file v72

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#7361]
**File/Catalogue:** Aeldari - Drukhari v72

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** All errors found during initial QA pass:

- Haemonculus can currently take a splinter pistol, but has no way to do so since the Flowchart of Doom has been removed.
- Incubi should be 16 points each, but are currently 14 points.
- Beastmaster’s default weapon should be an Agoniser.
- Dark Lance should cost 15 points for INFANTRY, but is currently 20 points on:
1. Kabalite Warriors
2. Kabalite Trueborn
3. Scourges
- Splinter Cannon should cost 10 points for INFANTRY, but is currently 15 points on:
1. Kabalite Warriors
2. Kabalite Trueborn
3. Scourges
- Kabalite Trueborn PL cost is 5/8/11/14, but should be 5/9/12/15.
- Hekatrix Bloodbride > Hekatrix Bloodbride with Wych Weapon does not appear to be using GST point values for Wych weapons, causing them to all be incorrect.
- Grotesques can currently take Weapons of Torture, but have no way to do so since the Flowchart of Doom has been removed.
- Hellions > Helliarch has unique weapon options rather than using GST values, meaning that:
1. Agoniser + splinter pistol costs 4 points, but should be 5 points
2. Power sword + splinter pistol costs 4 points, but should be 5 points
- Scourges > Solarite’s power lance costs 4 points, but should be 5 points.
- Ravager currently costs 95 points but should be 85 points.

**Comment by FarseerVeraenthis** [comment]
I'll get to it, thanks for the quick turnaround...!
(I hope it's not too obvious this was a rush job the first time around...)
