### ISSUE TITLE
Harlequins - 9th edition QA points/PL check for file v41

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#7362]
**File/Catalogue:** Aeldari - Harlequins v41

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** All errors found during initial QA pass:

- Webway Gate is currently 90 points, but should be 95 points.

**Comment by FarseerVeraenthis** [comment]
Yeah, that's a GST issue 👍

**Comment by FarseerVeraenthis** [comment]
closed, ref commit for #7361
