### ISSUE TITLE
Chaos Knights - 9th edition QA points/PL check for file v37

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#7369]
**File/Catalogue:** Chaos - Chaos Knights v37

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** All errors found during initial QA pass:

- [x] War Dog’s meltagun is currently 14 points, but should be 10 points
- [x] Taking two Avenger gatling cannons on a Knight Despoiler should cause their costs to increase from 90 points to 100 points each
- [x] Knight Despoiler’s heavy flamers currently cost 15 points, but should cost 0 points
- [x] Renegade Knight Asterius should be called Acastus Knight Asterius
- [x] Acastus Knight Asterius currently costs 600 points, but should cost 850 points
- [x] Acastus Knight Asterius’ karacnos mortar battery currently costs 20 points, but should cost 0 points
- [x] Acastus Knight Asterius’ twin conversion beam cannon currently costs 90 points, but should cost 0 points
- [x] Acastus Knight Asterius’ volkite culverin currently costs 15 points, but should cost 0 points
- [x] Renegade Knight Porphyrion should be called Acastus Knight Porphyrion
- [x] Acastus Knight Porphyrion currently costs 600 points, but should cost 820 points
- [x] Acastus Knight Porphyrion’s twin magna lascannon currently costs 100 points, but should cost 0 points
- [x] Acastus Knight Porphyrion’s autocannon currently costs 10 points, but should cost 15 points
- [x] Renegade Knight-Acheron should be called Cerastus Knight-Acheron
- [x] Cerastus Knight-Acheron currently costs 358 points, but should cost 520 points
- [x] Cerastus Knight-Acheron’s acheron flame cannon currently costs 80 points, but should cost 0 points
- [x] Cerastus Knight-Acheron’s reaper chainfist currently costs 40 points, but should cost 0 points
- [x] Renegade Knight-Atropos should be called Cerastus Knight-Atropos
- [x] Cerastus Knight-Atropos currently costs 405 points, but should cost 580 points
- [x] Cerastus Knight-Atropos’ atropos lascutter currently costs 80 points, but should cost 0 points
- [x] Cerastus Knight-Atropos’ graviton singularity cannon currently costs 70 points, but should cost 0 points
- [x] Renegade Knight Castigator should be called Cerastus Knight-Castigator
- [x] Cerastus Knight-Castigator currently costs 350 points, but should cost 460 points
- [x] Cerastus Knight-Castigator’s castigator bolt cannon currently costs 50 points, but should cost 0 points
- [x] Cerastus Knight-Castigator’s tempest warblade currently costs 30 points, but should cost 0 points
- [x] Renegade Knight-Lancer should be called Cerastus Knight-Lancer
- [x] Cerastus Knight-Lancer currently costs 360 points, but should cost 460 points
- [x] Cerastus Knight-Lancer’s cerastus shock lance currently costs 60 points, but should cost 0 points
- [x] Renegade Knight Magaera should be called Questoris Knight Magaera
- [x] Questoris Knight Magaera currently costs 380 points, but should cost 490 points
- [x] Questoris Knight Magaera’s lightning cannon currently costs 70 points, but should cost 0 points
- [x] Questoris Knight Magaera’s phased plasma-fusil currently costs 20 points, but should cost 0 points
- [x] Twin rad cleanser currently costs 25 points, but should cost 0 points on:
1. Questoris Knight Magaera
1. Questoris Knight Styrix
- [x] Hekaton siege claw currently costs 30 points, but should cost 55 points on:
1. Questoris Knight Magaera
1. Questoris Knight Styrix
- [x] Renegade Knight Styrix should be called Questoris Knight Styrix
- [x] Questoris Knight Styrix currently costs 340 points, but should cost 475 points
- [x] Questoris Knight Styrix’s graviton crusher currently costs 25 points, but should cost 0 points
- [x] Questoris Knight Styrix’s Volkite chieorovile currently costs 25 points, but should cost 0 points
- [x] War Dog Moirax currently costs 145 points, but should cost 155 points

**Comment by Mad-Spy** [comment]
WTF? I know I made the FW changes already. I must have deleted them somehow.

I'm really not sure on the names. The datasheets have the "Renegade" names and have never been updated, but every time GW update the points, they call them by the Loyalist names.

**Comment by Dunamis55** [comment]
For the names, I was going off the updated datasheets at:
https://www.warhammer-community.com/wp-content/uploads/2019/07/Chaos_Knights_FW_Army_List.pdf
which themselves are at:
https://www.warhammer-community.com/downloads/

So it looks like they got renamed since the Imperial Armour books dropped.
