### ISSUE TITLE
Gellerpox Infected - 9th edition QA points/PL check for file v5

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#7373]
**File/Catalogue:** Chaos - Gellerpox Infected v5

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** All errors found during initial QA pass:

- Vulgar Thrice-Cursed currently costs 65 points, but should cost 70 points.
- The Vox-Shamblers currently costs 8 points each, but should cost 9 points each.
- Glitchlings currently costs 4 points each, but should cost 5 points each.
- The Hullbreakers currently costs 31 points each, but should cost 35 points each.
- Eyestinger Swarms currently costs 3 points each, but should cost 5 points each.
- Cursemites currently costs 3 points each, but should cost 5 points each.
- Sludge-grubs currently costs 4 points each, but should cost 5 points each.

**Comment by Mad-Spy** [comment]
I only did these this morning; I'd marked them done by accident. Refresh your data and they should be good.

**Comment by Dunamis55** [comment]
Closing issue, as all points now correct.
