### ISSUE TITLE
Genestealer Cults - 9th edition QA points/PL check for file v51

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#7376]
**File/Catalogue:** Tyranids - Genestealer Cults v51

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** All errors found during initial QA pass:

- [x] Neophyte Hybrids > Neophyte Hybrid (Seismic)’s seismic cannon is currently 12 points, but should be 10 points
- [x] Atalan Jackals currently cost 10 points, but should cost 14 points
- [x] Atalan Jackals > Atalan Wolfquad currently costs 15 points, but should cost 20 points
- [x] Cult Leman Russ’ battle cannon currently costs 30 points, but should cost 20 points

**Comment by DrTobogganMD** [comment]
Resolved by @Guy-Markman
