### ISSUE TITLE
Monsters and Gribblies - 9th edition QA points/PL check for file v5

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#7380]
**File/Catalogue:** Unaligned - Monsters and Gribblies v5

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** All errors found during initial QA pass:

- [ ] Borewyrm Infestation is currently 15 points per model, but should be 15 points per unit.

**Comment by Mad-Spy** [comment]
Not convinced by this. Are they 7.5 points each then given the unit size is 1-2? It seems likely that it's a mistake on GW's part given that they were 12ppm previously.
