### ISSUE TITLE
9th Edition - GW publications problems/ambiguities

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-9e#7390]
@BSData/data-admins-wh40k  please add issues you found so we can have a checklist when inevitable errata hits.

**This thread is for posting issues in GW publications we found when _writing_ datafiles.**

Please use a table format:

```
Publication | Issue
-|-
MFM2020 | Points wrong for Unit 1.
PA: TGG FAQ | Keyword for Craftworld is invalid in rule X.
```

**Comment by amis92** [comment]
Publication | Issue
-|-
~~MFM2020~~ | ~~**T'au:** Shadowsun's MV37 Advanced Guardian Drone has no cost listed; her old datasheet's MV52 Shield Drone has (which is no longer used by any Codex units).~~
~~IAI: Xenos FAQ~~ | ~~**T'au:** Cyclic Ion Blaster is listed as gaining Blast profile; however current weapon profile (updated in latest Codex) no longer has random number of shots.~~
~~MFM2020~~ | ~~**Blackstone Fortress:** Bonewyrm Infestation listed as Unit size 1-2 and 15 points _per unit_. However, they were 12ppm in 8th.~~
~~MFM2020~~ | ~~**Tau:** The Eight is listed as "8 characters, 14 drones" in models per unit, with a cost of 1250 points per models, strictly speaking this unit would cost 10k pts _plus drones_. 😂~~
~~MFM2020 p54~~ | ~~**Tau:** XV107/109 are listed as Elites; however, they belong to (XV109) Fast Attack and (XV107) Heavy Support. I expect such changes to be made via Errata and not an MFM (@amis92).~~
~~Codex Supplement: Deathwatch~~ | ~~Kill Team Cassius' 3PL, previously 13PL in the index.~~
~~IA: Compendium~~ | ~~**T'au:** points section states all wargear not listed is free, making hazard suits have free support systems.~~
~~IA: Compendium~~ | ~~**Eldar:** Hornets do not have Hornet Pulse Lasers to trade for Heavy Weapons. This means RAW they're locked to Shuriken Cannons only. In anticipation of this being rectified in the FAQ I have hidden the other weapon options to save putting them back into the CAT.~~
~~Warhammer Legends~~ | ~~**Orks:** Deff Rolla Battle Fortress has no default wargear, so unable to create a default unit entry.~~
~~Warhammer Legends - Forgeworld pp. 91-93~~ | ~~**Renegades and Heretics:** "Minions of Chaos" rule references the non-existent CHAOS AND RENEGADES keyword. This should clearly be RENEGADES AND HERETICS.~~
~~Warhammer Legends - Forgeworld p94~~ | ~~**Renegades and Heretics:** The banners available to the Renegade Command Squad reference the `<CHAOS COVENANT>` keyword, which doesn't exist on any datasheets.~~

**Comment by KalChoedan** [comment]
Publication | Issue
-|-
MFM2020 | CWE: Points wrong for Wraithblades and their weapons. Currently 29 + increment 6 per weapon; should be 40 + 0 per weapon.

**Comment by amis92** [comment]
@KalChoedan if these are bugs in datafiles, please open a new issue. This thread is for posting issues in GW publications we found when writing datafiles.

**Comment by mzsilak** [comment]
Publication | Issue
-|-
Codex: GSC | Kellermorph: Gunslinger ability allows the model to target enemy CHARACTERS. There is no FAQ regarding the new Look Out Sir! rule (while another weapon received an FAQ). Newer publication take priority, meaning he is no character sniper anymore.

**Comment by mzsilak** [comment]
The Codex: GSC was fixed with an FAQ today. It gets to ignore Look Out Sir!

**Comment by fuckingenglish** [comment]
No force org imperial files ranging from Inquisitor's, assassin's, priests, combo plate's ; And move units into the no force after selecting me

**Comment by Mad-Spy** [comment]
@fuckingenglish I'm afraid your comment makes no sense. And what is a combo plate?

**Comment by amis92** [comment]
I've updated the title to reflect this issue's purpose more clearly which is, as stated in OP:

**This thread is for posting issues in GW publications we found when writing datafiles.**

**Comment by fuckingenglish** [comment]
Combo plate's is two models that have different keywords that interact with the data files.

**Comment by williamcaw** [comment]
#8109 / #8094

**Comment by Technoblazed** [comment]
Publication | Issue
-|-
Codex Supplement: Deathwatch | Kill Team Cassius' 3PL, previously 13PL in the index.

**Comment by Technoblazed** [comment]
Publication | Issue
-|-
Imperial Armour Compendium | T'au points section states all wargear not listed is free, making hazard suits have free support systems.
Warhammer Legends - Forgeworld pp. 91-93 | Renegades and Heretics "Minions of Chaos" rule references the non-existent CHAOS AND RENEGADES keyword. This should clearly be RENEGADES AND HERETICS.
Warhammer Legends - Forgeworld p94 | The banners available to the Renegade Command Squad reference the `<CHAOS COVENANT>` keyword, which doesn't exist on any datasheets.

**Comment by Technoblazed** [comment]
Publication | Issue
-|-
IA: Legends| Deff Rolla Battle Fortress has no default wargear, so unable to create a default unit entry.

**Comment by FarseerVeraenthis** [comment]
Publication | Issue
-|-
IA: Compendium | Hornets do not have Hornet Pulse Lasers to trade for Heavy Weapons. This means RAW they're locked to Shuriken Cannons only. In anticipation of this being rectified in the FAQ I have hidden the other weapon options to save putting them back into the CAT.

**Comment by DrTobogganMD** [comment]
I've consolidated all known issues into the first post.

**Comment by Ubikator** [comment]
Hey! Not sure if this is the right place to post this, but Fire Raptor Gunship point values are wrong in Adeptus Astartes (checked in UM and RG). It should be 340 base with autocannons and hellstrikes. Quad bolters are +30 points, and Twin lascannons are +10 pts. (Yes, I made an account here just to post this)

Cheers!

**Comment by DrTobogganMD** [comment]
All ambiguities are fixed!!!
