### ISSUE TITLE
Adeptus Astra Telepathica - 9th edition QA points/PL check for file v17

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#7391]
**File/Catalogue:** Imperium - Adeptus Astra Telepathica v17

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** All errors found during initial QA pass:

- [ ] Astropath’s Telepathica stave is currently 6 points, but should be 0 points

**Comment by Guy-Markman** [comment]
Should be fixed under #7393
