### ISSUE TITLE
Astra Militarum - 9th edition QA points/PL check for file v274

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#7393]
**File/Catalogue:** Imperium - Astra Militarum v274

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** All errors found during initial QA pass:

- [x] Rein and Raus currently cost 35 points, but should be 40 points
- [x] Aradia Madellan currently costs 40 points, but should be 45 points
- [x] Rough Riders > Rough Rider Sergeant’s power lance is currently 5 points, but should be 4 points
- [x] Flamer is currently 6 points, but should be 5 points on:
1. Rough Riders > Rough Rider w/ Special Weapons
1. Militarum Tempestus Scions > Scion w/ Special Weapon
1. Militarum Tempestus Command Squad > Tempestus Scion
1. Hades Breaching Drill Squadron > Veteran w/ Special Weapon
- [x] Grenade launcher is currently 3 points, but should be 5 points on:
1. Rough Riders > Rough Rider w/ Special Weapons
1. Militarum Tempestus Scions > Scion w/ Special Weapon
1. Militarum Tempestus Command Squad > Tempestus Scion
1. Hades Breaching Drill Squadron > Veteran w/ Special Weapon
- [x] Meltagun is currently 10 points, but should be 5 points
1. Rough Riders > Rough Rider w/ Special Weapons
1. Hades Breaching Drill Squadron > Veteran w/ Special Weapon
- [x] Plasma gun is currently 7 points, but should be 5 points on:
1. Rough Riders > Rough Rider w/ Special Weapons
1. Infantry Squad > Guardsman W/ Special Weapon
1. Special Weapons Squad > Guardsman W/ Special Weapon
1. Hades Breaching Drill Squadron > Veteran w/ Special Weapon
- [x] Rough Riders increase from 3 PL to 5 PL at 7 models instead of at 6 models
- [x] Lord Castellan Creed currently costs 55 points, but should be 60 points
- [x] Power fist currently costs 8 points, but should be 10 points on:
1. Company Commander
1. Platoon Commander
1. Hades Breaching Drill Squadron > Veteran Sergeant
- [x] Bolt pistol currently costs 1 point, but should be 2 points
1. Company Commander
1. Tempestor Prime
1. Infantry Squad > Sergeant
1. Militarum Tempestus Scions > Tempestor
1. Platoon Commander
1. Hades Breaching Drill Squadron > Veteran Sergeant
- [x] Boltgun currently costs 1 point, but should be 2 points on:
1. Company Commander
1. Lord Commissar
1. Infantry Squad > Sergeant
1. Platoon Commander
1. Commissar
- [x] Heavy bolter currently costs 10 points, but should be 15 points on:
1. Tank Commander
1. Knight Commander Pask
1. Hellhounds
1. Basilisks
1. Wyverns
1. Hydras
1. Deathstrike
1. Leman Russ Battle Tanks > All variants
1. Chimera
1. Gryphonne Pattern Chimera
1. Trojan Support Vehicle
1. Artemia Pattern Hellhound
1. Armageddon Pattern Basilisk
1. Armageddon Pattern Medusa
1. Colossus Bombard
1. Griffon Mortar Carrier
1. Leman Russ Annihilator
1. Leman Russ Conqueror
1. Leman Russ Stygies Vanquisher	
1. Crassus Armoured Assault Vehicle
1. Dominus Armoured Siege Bombard
1. Leman Russ Ryza Vanquisher
- [x] Heavy flamer currently costs 10 points, but should be 15 points on:
1. Tank Commander
1. Knight Commander Pask
1. Hellhounds
1. Scout Sentinels
1. Armoured Sentinels
1. Basilisks
1. Wyverns
1. Hydras
1. Deathstrike
1. Leman Russ Battle Tanks > All variants
1. Chimera
1. Gryphonne Pattern Chimera
1. Trojan Support Vehicle
1. Artemia Pattern Hellhound
1. Armageddon Pattern Basilisk
1. Armageddon Pattern Medusa
1. Colossus Bombard
1. Griffon Mortar Carrier
1. Leman Russ Annihilator
1. Leman Russ Conqueror
1. Leman Russ Stygies Vanquisher
1. Leman Russ Ryza Vanquisher
- [x] Lascannon currently costs 15 points, but should be 20 points on:
1. Tank Commander
1. Knight Commander Pask
1. Scout Sentinels
1. Armoured Sentinels
1. Leman Russ Battle Tanks > All variants
1. Valkyries
1. Baneblade > Both sponson variants
1. Banehammer > Both sponson variants
1. Banesword > Both sponson variants
1. Doomhammer > Both sponson variants
1. Hellhammer > Both sponson variants
1. Shadowsword > Both sponson variants
1. Stormlord > Both sponson variants
1. Stormsword > Both sponson variants
1. Leman Russ Annihilator
1. Leman Russ Conqueror
1. Leman Russ Stygies Vanquisher
1. Malcador Annihilator
1. Malcador Defender
1. Malcador Heavy Tank
1. Malcador Infernus
1. Arkurian Pattern Stormblade > Both sponson variants
1. Arkurian Pattern Stormhammer
1. Arkurian Pattern Stormsword > Both sponson variants
1. Crassus Armoured Assault Vehicle
1. Praetor Armoured Assault Launcher
1. Valdor Tank Hunter
1. Avenger Strike Fighter
1. Carnodon
1. Leman Russ Ryza Vanquisher
- [x] Sponson weapons versions of heavy bolters and heavy flamers only count once, but should count twice on:
1. Tank Commander
1. Knight Commander Pask
1. Leman Russ Battle Tanks > All variants
1. Leman Russ Annihilator
1. Leman Russ Conqueror
1. Leman Russ Stygies Vanquisher
1. Leman Russ Ryza Vanquisher
- [x] Multi-meltas currently costs 20 points, but should be 25 points on:
1. Tank Commander
1. Knight Commander Pask
1. Hellhounds
1. Leman Russ Battle Tanks > All variants
1. Artemia Pattern Hellhound
1. Leman Russ Annihilator
1. Leman Russ Conqueror
1. Leman Russ Stygies Vanquisher
1. Leman Russ Ryza Vanquisher
- [x] Plasma cannons currently costs 15 points each, but should be 20 points each on:
1. Tank Commander
1. Knight Commander Pask
1. Armoured Sentinels
1. Leman Russ Battle Tanks > All variants
1. Leman Russ Annihilator
1. Leman Russ Conqueror
1. Leman Russ Stygies Vanquisher
1. Leman Russ Ryza Vanquisher
- [x] Battle cannon currently costs 22 points, but should be 20 points on:
1. Tank Commander
1. Knight Commander Pask
1. Malcador Heavy Tank
- [x] “Turret-mounted demolisher siege cannon” should be called “demolisher cannon” on:
1. Tank Commander
1. Knight Commander Pask
1. Leman Russ Battle Tanks > Leman Russ Demolisher
- [x] “Turret-mounted eradicator nova cannon” should just be called “eradicator nova cannon” on:
1. Tank Commander
1. Knight Commander Pask
1. Leman Russ Battle Tanks > Leman Russ Eradicator
- [x] “Turret-mounted executioner plasma cannon” should just be called “executioner plasma cannon” on:
1. Tank Commander
1. Knight Commander Pask
1. Leman Russ Battle Tanks > Leman Russ Executioner
- [x] “Turret-mounted exterminator autocannon” should just be called “exterminator autocannon” on:
1. Tank Commander
1. Knight Commander Pask
1. Leman Russ Battle Tanks > Leman Russ Exterminator
- [x] “Turret-mounted punisher gatling cannon” should just be called “punisher gatling cannon” on:
1. Tank Commander
1. Knight Commander Pask
1. Leman Russ Battle Tanks > Leman Russ Punisher
- [x] “Turret-mounted vanquisher battle cannon” should just be called “vanquisher battle cannon” on:
1. Tank Commander
1. Knight Commander Pask
1. Leman Russ Battle Tanks > Leman Russ Vanquisher
- [x] Punisher gatling cannon currently costs 30 points, but should be 35 points on:
1. Tank Commander
1. Knight Commander Pask
1. Leman Russ Battle Tanks > Leman Russ Punisher
- [x] Hunter-killer missile currently costs 6 points, but should be 5 points on:
1. Tank Commander
1. Knight Commander Pask
1. Hellhounds
1. Basilisks
1. Wyverns
1. Hydras
1. Manticore
1. Deathstrike
1. Leman Russ Battle Tanks > All variants
1. Chimera
1. Vulture Gunship
- [x] Lord Commissar should also have a power sword selected as part of default wargear
- [x] Bolt pistol is currently 1 point, but should be 0 points on:
1. Lord Commissar
1. Commissar
- [x] Heavy bolter is currently 8 points, but should be 10 points on:
1. Infantry Squad > Heavy Weapon Team’s
1. Command Squad > Veteran Weapon Team
1. Veterans > Veteran Weapon Team
1. Servitors
1. Heavy Weapons Squad
- [x] Missile launcher is currently 10 points, but should be 15 points on:
1. Infantry Squad > Heavy Weapon Team
1. Command Squad > Veteran Weapon Team
1. Veterans > Veteran Weapon Team
1. Heavy Weapons Squad
- [x] Hot-shot volley gun is currently 7 points, but should be 5 points
1. Militarum Tempestus Scions > Scion w/ Special Weapon
1. Militarum Tempestus Command Squad > Tempestus Scion
1. Taurox Prime
- [x] Meltagun is currently 14 points, but should be 10 points on:
1. Militarum Tempestus Scions > Scion w/ Special Weapon
1. Militarum Tempestus Command Squad > Tempestus Scion
- [x] Plasma gun is currently 11 points, but should be 10 points on:
1. Militarum Tempestus Scions > Scion w/ Special Weapon
1. Command Squad > Veteran w/ Special Weapon
1. Veterans > Veteran w/ Special Weapon
1. Militarum Tempestus Command Squad > Tempestus Scion
- [x] Heavy flamer is currently 14 points, but should cost 10 points on:
1. Command Squad > Veteran w/ Heavy Flamer
1. Veterans > Veteran w/ Heavy Flamer
- [x] Special Weapons Squad is currently 6 points each, but should be 5 points each
- [x] Special Weapons Squad’s “Demo Charge” should be called “Demolition charge”
- [x] Sergeant Harker currently costs 66 points, but should be 55 points
- [x] Servitors are currently 4 PL, but should be 3 PL
- [x] Servitors’ multi-melta currently costs 15 points, but should be 20 points
- [x] Servitors’ plasma cannon currently costs 10 points, but should be 15 points
- [x] Ogryns currently cost 5/8/12 PL, but should cost 5/9/13 PL
- [x] Hellhounds are currently 93 points for each variant, but should be 95 points for each variant
- [x] Hellhounds > Bane Wolf’s “turret-mounted chem cannon” should just be called “chem cannon”
- [x] Hellhounds > Devil Dog’s “turret-mounted melta cannon” should just be called “melta cannon”
- [x] Hellhounds > Hellhound’s “turret-mounted inferno cannon” should just be called “inferno cannon”
- [x] Missile launcher is currently 15 points, but should be 20 points on:
1. Scout Sentinels
1. Armoured Sentinels
- [x] Basilisks can take a hunter-killer missile twice, but should only be able to take one at most
- [x] Heavy stubber currently costs 2 points, but should be 5 points on:
1. Hydras
1. Stormlord
1. Malcador Annihilator
1. Malcador Heavy Tank
1. Malcador Infernus
1. Gorgon Heavy Transporter
1. Macharius Heavy Tank
1. Macharius Omega
1. Macharius Vanquisher
1. Macharius Vulcan
1. Valdor Tank Hunter
1. Carnodon
- [x] Hydras’ storm bolter currently costs 2 points, but should be 3 points
- [x] Heavy bolter is currently 8 points, but should be 15 points
1. Manticore
1. Valkyrie
1. Atlas Recovery Tank
1. Salamander Command Vehicle
1. Salamander Scout Tank
1. Malcador Defender
1. Malcador Heavy Tank
1. Malcador Infernus
1. Arkurian Pattern Stormblade
1. Arkurian Pattern Stormhammer
1. Gorgon Heavy Transporter
1. Macharius Heavy Tank
1. Macharius Vanquisher
1. Macharius Vulcan
1. Minotaur Artillery Tank
1. Praetor Armoured Assault Launcher
1. Valdor Tank Hunter
1. Aquila Lander
1. Vendetta Gunship
1. Vulture Gunship
1. Carnodon
- [x] Heavy flamer is currently 14 points, but should be 15 points on:
1. Manticore
1. Salamander Command Vehicle
1. Tauros Assault Vehicle
1. Malcador Infernus
1. Arkurian Pattern Stormhammer
1. Crassus Armoured Assault Vehicle
1. Dominus Armoured Siege Bombard
1. Gorgon Heavy Transporter
1. Macharius Heavy Tank
1. Macharius Omega
1. Macharius Vanquisher
1. Macharius Vulcan
1. Praetor Armoured Assault Launcher
1. Valdor Tank Hunter
1. Carnodon
- [x] Valkyries’ hellstrike missiles are currently 0 points, but should be 10 points
- [x] Baneblade’s “Baneblade Battle cannon” should be called “Baneblade cannon”
- [x] Twin heavy bolter is currently 14 points, but should be 30 points on:
1. Baneblade
1. Banehammer
1. Banesword
1. Doomhammer
1. Hellhammer
1. Shadowsword
1. Stormlord
1. Stormsword
1. Gryphonne Pattern Chimera
1. Sabre Weapons Battery
1. Tarantula Battery
1. Arkurian Pattern Stormsword
1. Marauder Bomber
1. Marauder Destroyer
1. Arkurian Pattern Shadowsword
- [x] Banehammer’s “hull-mounted tremor cannon” should just be called “tremor cannon”
- [x] Banesword’s “hull-mounted quake cannon” should just be called “quake cannon”
- [x] Doomhammer’s “hull-mounted magma cannon” should just be called “magma cannon”
- [x] Doomhammer’s “hull-mounted vulcan mega-bolter” should just be called “vulcan mega-bolter”
- [x] Centaur Light Carrier’s heavy stubber is currentl	y 4 points, but should be 5 points
- [x] Artemia Pattern Hellhound currently costs 6/12/18 PL, but should be 6/11/17 PL
- [x] Twin multi-laster is currently 18 points, but should be 10 points on:
1. Tauros Venator
1. Arvus Lighter
1. Vulture Gunship
- [x] Collossus Bombard has a typo and should be named “Colossus Bombard”
- [x] Griffon Mortar Carrior currently costs 6/12/18 PL, but should be 6/13/19 PL
- [x] Leman Russ Annihilator currently costs 10/20/30 PL, but should be 11/22/33 PL
- [x] Leman Russ Annihilator’s “turret-mounted twin lascannon” should just be called “twin lascannon”
- [x] Leman Russ Conqueror’s “turret-mounted conqueror battle cannon” should just be called “conqueror battle cannon”
- [x] Leman Russ Stygies Vanquisher’s “turret-mounted vanquisher battle cannon” should be called “Stygies vanquisher battle cannon”
- [x] Sabre Weapons Battery currently costs 2/4/6 PL, but should be 3/6/9 PL
- [x] Twin autocannon is currently 25 points, but should be 30 points on:
1. Sabre Weapons Battery
1. Marauder Destroyer
1. Arvus Lighter
1. Thunderbolt Heavy Fighter
1. Vulture Gunship
- [x] Twin heavy stubbers are currently 7 points each, but should be 10 points each on:
1. Sabre Weapons Battery
1. Gorgon Heavy Transporter
1. Macharius Heavy Tank
1. Macharius Vanquisher
1. Macharius Vulcan
1. Arvus Lighter
- [x] Marauder Destroyer’s twin assault cannon is currently 44 points, but should be 40 points
- [x] Praetor Armoured Assault Launcher should also have two heavy bolters as default wargear
- [x] Hellstrike missiles currently cost 12 points, but should be 10 points
1. Arvus Lighter
1. Avenger Strike Fighter
1. Lightning Strike Fighter
1. Thunderbolt Heavy Fighter
1. Vulture Gunship
- [x] Avenger Strike Fighter’s missile launchers currently cost 10 points each, but should be 20 points each
- [x] Lightning Strike Fighter’s “long barreled autocannon” has a typo in its name and should be called “long-barrelled autocannon”
- [x] Lightning Strike Fighter’s long barrelled autocannon currently costs 20 points, but should be 15 points
- [x] Vulture Gunship’s twin punisher gatling cannon currently costs 60 points, but should be 70 points
- [x] Vulture Gunship’s multiple rocket pods currently cost 8 points each, but should be 5 points each
- [x] Carnodon’s twin autocannon currently costs 24 points, but should cost 30 points
- [x] Carnodon’s twin multi-laser currently costs 20 points, but should be 10 points
- [x] Carnodon’s volkite culverin currently costs 24 points, but should be 30 points
- [x] Carnodon’s volkite culverin currently costs 24 points, but should be 30 points
- [x] Carnodon’s volkite calivers currently cost 12 points each, but should be 15 points each

**Comment by Guy-Markman** [comment]
Can anyone who would fix it will take care of #7391? 
It's also on the same Catalogue
