### ISSUE TITLE
Corsairs - 9th edition QA points/PL check for file v21

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#7397]
**File/Catalogue:** Aeldari - FW Corsairs v21

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** All errors found during initial QA pass:

- [x] Lasblaster is currently 0 points, but should be 7 points on:
1. Corsair Reaver Band > Reaver w/ Lasblaster
1. Corsair Skyreaver Band > Skyreaver w/ Lasblaster
- [x] Dark lance is currently 20 points, but should be 15 points on:
1. Corsair Reaver Band > Reaver w/ Heavy Weapon
1. Corsair Skyreaver Band > Skyreaver w/ Heavy Weapon
- [x] Splinter cannon is currently 15 points, but should be 10 points on:
1. Corsair Reaver Band > Reaver w/ Heavy Weapon
1. Corsair Skyreaver Band > Skyreaver w/ Heavy Weapon
- [x] Corsair Cloud Dancer Band > Corsair Cloud Dancer Felarch is currently 16 points, but should be 23 points
- [x] Twin shuriken catapult is currently 2 points, but should be 0 points on:
1. Corsair Cloud Dancer Band > Corsair Cloud w/ Twin Shuriken Catapult
1. Corsair Cloud Dancer Band > Corsair Cloud Dancer Felarch
1. Corsair Falcon
- [x] Corsair Cloud Dancer Band > Cloud Dancer w/ Dark Lance’s dark lance is currently 15 points, but should be 20 points
- [x] Corsair Cloud Dancer Band > Cloud Dancer w/ Splinter Cannon’s splinter cannon is currently 10 points, but should be 15 points

**Comment by DrTobogganMD** [comment]
Resolved by @Guy-Markman
