### ISSUE TITLE
T'au Empire - 9th edition QA points/PL check for file v60

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#7399]
**File/Catalogue:** T'au Empire v60

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** All errors found during initial QA pass:

- [ ] Dahyak Grekkh is currently 20 points, but should be 40 points
- [ ] The Eight > Commander Brightsword’s MV4 Shield Drones are currently 0 points each, but should be 15 points each
- [ ] MV1 Gun Drones are currently 0 points each, but should be 10 points each on:
1. The Eight > Commander Bravestorm
1. The Eight > Shas’o Sha’vastos
1. The Eight > Shas’o Arra’kon
- [ ] The Eight > Sub-Commander Torchstar’s MV7 Marker Drones are currently 0 points each, but should be 10 points each
- [ ] The Eight > Broadside Shas’vre Ob’loati 9-0’s  MV8 Missile Drones are currently 0 points each, but should be 20 points each
- [ ] The Eight > O’Vesa’s  MV84 Shielded Missile Drones are currently 0 points each, but should be 30 points each
- [ ] Taking 1 or 2 Tactical Drones for a Pathfinder Team should increase its PL by 1
- [ ] Taking either or both of the Support Drones for a Pathfinder Team should increase its PL by 1
- [ ] Taking 1 or 2 Tactical Drones for a Commander in XV81 Crisis Battlesuit should increase its PL by 1
- [ ] Taking 1 or 2 Tactical Drones for a Commander in XV84 Crisis Battlesuit should increase its PL by 1
- [ ] Taking any Tactical Drones for a XV9 Hazard Support Team should increase its PL by 1 per drone
- [ ] Tiger Shark’s swiftstrike railgun is currently 101 points each, but should be 5 points each

**Comment by amis92** [comment]
For discussion about The Eight's drones, see #7400
