### ISSUE TITLE
Orks - 9th edition QA points/PL check for file v80

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#7405]
**File/Catalogue:** Orks v80

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** All errors found during initial QA pass:

- [x] Wartrakk [Legends] currently costs 3/9/15 PL, but should be 3/9/14 PL
- [x] Skorchas [Legends]’s skorcha currently costs 17 points, but should be 15 points
- [x] Big Gunz [Legends] currently costs 2/3/4/5/6/7 PL, but should be 1/2/3/4/5/6 PL
- [ ] Big Mek with Kustom Force Field’s kustom force field currently costs 0 points, but should be 20 points
- [x] Kustom shoota is currently 2 points, but should be 3 points on:
1. Boyz > Boss Nob
1. Nobz
1. Nobz on Warbikes
1. Warbikers > Boss Nob
1. Stormboyz > Boss Nob
- [x] Kustom mega-blasta is currently 9 points, but should be 10 points on:
1. Mek
1. Deffkopta
1. Grot Mega-Tank (heavy turret options)
- [x] Kustom mega-slugga is currently 7 points, but should be 5 points on:
1. Burna Boyz > Spanner
1. Lootas > Spanner
- [x] Stormboyz currently cost 3/5/10/14 PL, but should be 3/5/9/14 PL
- [x] Flash Gitz currently cost 7/13 PL, but should be 7/14 PL
- [x] Wazbom Blastajet’s wazbom mega-kannons are currently 10 points each, but should be 0 points
- [ ] Warboss on Warbike’s points include all wargear, so all options should be 0 points
- [x] Grot Mega-Tank’s skorchas (heavy turret options) currently cost 17 points each, but should be 15 points each
- [x] Meka-Dread’s rippa klaws are currently 50 points for one and 30 points for the second, but should be 20 points for one and 5 points for the second
- [x] Big Trakk’s grot sponsons are currently 8 points each, but should be 10 points each
- [x] Big Trakk’s big shootas are currently 0 points each, but should be 5 points each
- [x] Big Trakk’s rokkit launchas are currently 0 points each, but should be 10 points each
- [x] Big Trakk’s skorchas are currently 0 points each, but should be 15 points each
- [x] Deff Rolla is currently 19 points, but should be 20 points on:
1. Battlewagon with Supa-Kannon
1. Lifta Wagon
- [x] ‘Chinork’ Warkopta’s bigbomm currently costs 5 points, but should be 0 points
- [x] ‘Chinork’ Warkopta’s rattler kannon currently costs 32 points, but should be 0 points

**Comment by tag8833** [comment]
> - [ ] Warboss on Warbike’s points include all wargear, so all options should be 0 points

That is clearly a typo.  They don't want him to have free wargear.
