### ISSUE TITLE
Missing Stratagem Description for 9e Sisters

### ISSUE THREAD

**Issue by Turband** [BSData/wh40k-9e#7407]
**File/Catalogue:** 
Adepta Sororitas v113
**BattleScribe version:** 
2.03.21
**Platform:**
Windows
**Dropbox:** 
No
**Description:** 
When viewing the description for the Stratagem: Venerated Saint, Heroine in the Making. It appears as empty, like having no description.

**Comment by alphalas** [comment]
Low priority enhancement.
