### ISSUE TITLE
Wrong cost for Devourer with brainleech worms and Deathspitter with slimer maggots

### ISSUE THREAD

**Issue by peterkorsos** [BSData/wh40k-9e#7409]
**File/Catalogue:** Tyranids.cat

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:**
Two devourers with brainleech worms cost 14 and should cost 20
Two deathspitters with slimer maggots cost 14 and should cost 20

**Comment by alphalas** [comment]
Duplicate #7410
