### ISSUE TITLE
Wrong cost for body of Stonecrusher Carnifex Brood

### ISSUE THREAD

**Issue by peterkorsos** [BSData/wh40k-9e#7411]
**File/Catalogue:** Tyranids.cat

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** File/Catalogue: Tyranids.cat

BattleScribe version: 2.03.21.166

Platform: Windows

Dropbox: No

Description:
Stonecrusher Carnifex Body costs 80 and should cost 90

**Comment by alphalas** [comment]
Duplicate #7410
