### ISSUE TITLE
Agents of the Imperium issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7425]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** imperium- agents of the imperium  brakes after a warlord is selected if there is multiple selections of warlord ie activated stratagems and stranded warlord is selected

**Comment by williamcaw** [comment]
yep all no force org is broken

**Comment by williamcaw** [comment]
this is the selecting of a inquisitor's/assassins in a roster brings up to many hq's or taking a assassins in a roster

**Comment by Mad-Spy** [comment]
This should be resolved by the new Agents of the Imperium Primary and logic.
