### ISSUE TITLE
Super Heavy Aux Detachment requiring a Warlord

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7428]
**File:** Imperium - Titan Legions.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** super heavy detachments requesting warlord to be activated for aux and stranded taking of models

**Comment by williamcaw** [comment]
its also on the super heavy detachment -6 side

**Comment by DrTobogganMD** [comment]
That would be because per the game rules. You must select a warlord. Technically if you have no characters, it can be a non-character model but it gets no benefits. We do not allow this in battlescribe because the validation would be a nightmare.
