### ISSUE TITLE
Imperium - Officio Assassinorum: Vanguard Detachment requires a Warlord

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7429]
**File:** Imperium - Officio Assassinorum.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Execution Force [-1CP] no longer removes the requirement's for a hq's and warlord

**Comment by williamcaw** [comment]
![image](https://user-images.githubusercontent.com/22287376/88885221-f91aed80-d1ec-11ea-8a0b-69b6bc31e320.png)

**Comment by Mad-Spy** [comment]
The Warlord requirement is for the entire Roster, not a particular Detachment.

In order to simulate having an HQ, you need to add the "Execution Force" entry from the HQ slot.
