### ISSUE TITLE
Space wolves missing all indomitus options

### ISSUE THREAD

**Issue by mooftak** [BSData/wh40k-9e#7430]
**File/Catalogue** Imperium - Space Wolvess.catz
**BattleScribe version current, all platforms

**Dropbox:** Yes

**Description:** Space wolves does not include any indomitus options.

**Comment by DessaiImrane** [comment]
Indeed. I wish I could help to make a PR but I don't know how to use existing unit from another catalogue

**Comment by CrusherJoe** [comment]
Okay, it's done.
