### ISSUE TITLE
Space Wolves wulfen incorrect point values

### ISSUE THREAD

**Issue by Shoxaju** [BSData/wh40k-9e#7431]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/Android

**Dropbox:** Yes

**Description:** Wulfen option for Thunderhammer and Storm shield is listed at 19 points when it should be 15+5 for 20.

**Comment by williamcaw** [comment]
15 + 4 its set to other models as its equipment .

**Comment by Shoxaju** [comment]
well I feel sheepish, I was reading CA and my eyes read the teleport homer value instead of the shield value
