### ISSUE TITLE
Imperium - Dark Angels: Huntsman profile incorrect, Intercessors have AELDARI keyword

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7432]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The Huntsman Warlord trait is the old one, and tje intercesors have the Aeldari keyword

**Comment by Thairne** [comment]
![grafik](https://user-images.githubusercontent.com/8590840/88534488-7c2f1e80-d008-11ea-82e1-f4ea9c38bf5d.png)
