### ISSUE TITLE
Orks: Add Open Play characters from White Dwarf

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7437]
**File:** Orks.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Grukk Facerippa, Goff Rokkers and Skrak's Skull-Nobz are missing for Open Play and Crusade. Please add them.

**Comment by williamcaw** [comment]
Narrative Play only

Source: https://www.belloflostsouls.net/2020/05/warhammer-40k-3-new-ork-units-spotted-in-white-dwarf.html
