### ISSUE TITLE
Orks: Wazbom Blastajet weapon costs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7438]
**File:** Orks.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Wazbom blastajet has 20 points for the mega kannons and mega teleport blastas. These are now 0 points.

**Comment by williamcaw** [comment]
the  mega kannons are 0a Pair is 0, the  mega teleport blastas are 10 a Pair is 20. stikkbomb flinga 5 , supa-shoota is 10 a Pair is 20

**Comment by williamcaw** [comment]
> the mega kannons are 0a Pair is 0, the mega teleport blastas are 10 a Pair is 20. stikkbomb flinga 5 , supa-shoota is 10 a Pair is 20

chapter approved 2020 July 25
