### ISSUE TITLE
Aeldari - Craftworlds: Fusion gun cost on non-Fire Dragon units is incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7443]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Storm Guardians optional wargear - Fusion gun must have 10pts cost -its free only for Fire Dragons, not for other units: guardians. Autarhs, etc.

**Comment by KalChoedan** [comment]
#7403

**Comment by Dunamis55** [comment]
Duplicate issue of #7403
