### ISSUE TITLE
Craftworlds - power sword pts incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7446]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Powersword for everyone exept Swooping Hawks Exarch must have 0 pts cost: autarchs, winged or skyrunner too.

**Comment by williamcaw** [comment]
Exarch of Swooping Hawks are 5 points for power sword , Autarch with swooping Hawks 0 for power sword, autarch skyrunner is 0 
for power sword

**Comment by KalChoedan** [comment]
#7403

**Comment by Dunamis55** [comment]
Duplicate of #7403
