### ISSUE TITLE
Raven Guard - "Show primaris only" missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7447]
**File:** Imperium - Raven Guard.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** “Show primaris only” option is missing. Present in other space marine lists and very helpful.

**Comment by williamcaw** [comment]
its a request

**Comment by DrTobogganMD** [comment]
https://images-ext-2.discordapp.net/external/5NU51wWMU2VV_jMrTfMvsvQkgQ-Pi5uOOEW1Zmir2OE/https/i.tech-no.me/2020/07/31/200731003705.png Already present.
