### ISSUE TITLE
Thunderfire Cannon points cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7456]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Thunderfire cannon is adding up to 195pt but it’s 140, if you click on it the cannon and gunner points are correct and add up to 140 but it shows in your list as costing 195

**Comment by acebaur** [comment]
points are correct in the data. You probably need to check the delete existing data first.
