### ISSUE TITLE
Tau Empire - Knarloc Riders errors

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7463]
**File:** T'au Empire.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Unit Knarloc Riders under Fast Attack for the T'au Empire have a point cost of 28 per model, when they should have no point cost. I assume this has been mistakenly assigned to them, given Krootox Riders now also cost 28 points.

Knarloc Riders are also missing the weapon Kroot Rifle that they should be equipped with.

Knarloc Riders should have their points cost changed back to 0, and should have the Kroot Rifle weapon copied from the Kroot Carnivores unit

**Comment by Alvirulan** [comment]
As per 9th Chapter Approved (Munitorum Inventory), XV109 Y'vahra Battlesuit and XV107 R'varna Battlesuit are now Elites

**Comment by amis92** [comment]
@Alvirulan for independent issues, please open new ones. :)

**Comment by amis92** [comment]
@Alvirulan I've moved your issue here: https://github.com/BSData/wh40k/issues/7519

Although as I stated there, I don't think MFM2020 has "authority" to change unit's slot. It's purely a point cost update. So I'd expect this to be included in an Errata if it's supposed to be an actual change.
