### ISSUE TITLE
Imperial Knights - Cerastus Knight Atrapos point's cost incorrect

### ISSUE THREAD

**Issue by BenWithJam** [BSData/wh40k-9e#7473]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** Yes

**Description:** Points listed as 480, should be 580.

**Comment by SMCorey** [comment]
Atrapos is also stating wrong invuln. Should have a 5+ against all. Currently states vs shooting only. (note: only check chaos knights)

Thanks a million guys.

**Comment by DrTobogganMD** [comment]
@CORE461 Chaos Knight profiles do not apply to loyalist profiles. Per GW's published datasheet, it's a 5++ to all. https://www.forgeworld.co.uk/resources/PDF/fw_warscrolls/Cerastus-Knight-Atrapos-Imperial.pdf
