### ISSUE TITLE
Inquisition - Error when selecting Inqusitor in Roster

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7478]
**File:** Imperium - Inquisition.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** Adding an Agent of the Inquisition in its own detachment creates an error at the top level (roster rather than detachment) with respect to having an Agent of the Inquisition.  Eisenhorn used as an example here, but this works with any inquisitor with Agents keyword (Hector Rex does not give this error, for example).  Not checked with Assassins.

**Comment by williamcaw** [comment]
its being worked on dupe #7425

**Comment by Mad-Spy** [comment]
Agents has been reworked. This should be fixed.
