### ISSUE TITLE
Astra Militarum - Thunderbolt Heavy Fighter - Hellstrike Missiles points incorrect

### ISSUE THREAD

**Issue by Sayle** [BSData/wh40k-9e#7482]
**File/Catalogue:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.12

**Platform:** Windows

**Dropbox:** No

**Description:** Hellstrike Missiles are 10 points each but the Thunderbolt Heavy Fighter for Astra Militarum can currently take four for 10 points total. The Lightning Strike Fighter has the same option and correctly lists it as 40 points.

**Comment by lewis0460** [comment]
Lightning strike fighter's 6 hellstrike missile choice is also incorrect, however.

**Comment by CrusherJoe** [comment]
Fixed -- was in another bug report.
