### ISSUE TITLE
Space Wolves - Twin Ironhail auto cannon pts on Invictor incorrect

### ISSUE THREAD

**Issue by Muck1ng** [BSData/wh40k-9e#7483]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

Twin Ironhail auto cannon on the invictor Warsuit should be 0 points not 30.

**Comment by CrusherJoe** [comment]
According to the MFM the points for the Twin Ironhail autocannon are indeed 30.
