### ISSUE TITLE
White Scars - Stern and Kyganil missing 

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7484]
**File:** Imperium - White Scars.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Ephrael Stern and Kyganil from the Pariah Psychic Awakening update are not listed as options under the No Forge Org Slot category. Their rules state that they are available for inclusion in any Imperium detachment. This appears to be an issue with all space marine type detachments.

**Comment by williamcaw** [comment]
its being worked on dupe #7425

**Comment by williamcaw** [comment]
Issue has been fix by Mad-Spy #7425

**Comment by DrTobogganMD** [comment]
Contrary to what caw is commenting, this is not fixed.
