### ISSUE TITLE
Imperial Fists - Primaris Chaplain missing Benediction of Fury

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7486]
**File:** Imperium - Imperial Fists.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Primaris Chaplain does not have option for Benediction of Fury relic, even though it shows Chaplain in keywords list.

**Comment by cordwartman** [comment]
This seems to be all Primaris Chaplains, Ultramarines and Salamanders Primaris Chaplains are missing it too
