### ISSUE TITLE
Orks - boss nob pts incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7493]
**File:** Orks.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Boyz mob counting is wrong when the boss nob is added.

The points for the boss nob are not added up.

Hope i was useful.

Davide

**Comment by Technoblazed** [comment]
Already reported here: https://github.com/BSData/wh40k/issues/7422.

**Comment by Dunamis55** [comment]
Duplicate of #7422
