### ISSUE TITLE
Space Wolves - Wolf Priest Legend Wargear options removed

### ISSUE THREAD

**Issue by Type-40** [BSData/wh40k-9e#7495]
**40k 8th/9th** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** 

Wolf Priest Legend Wargear options are removed. 
Wolf Priest have a legend wargear option for stormbolter/combi ... no longer available in the app.

**Comment by Type-40** [comment]
Space Wolves.cat

**Comment by CrusherJoe** [comment]
I get it, and it should be there, but for the time being if Legends stuff has been removed it is going to stay removed until I re-do the datafile between now and October.
