### ISSUE TITLE
Battlescribe - 9th Edition zip corrupted?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7500]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** It's saying that the zip file for 9th evedotions army list is corrupt

**Comment by Thairne** [comment]
Noone else so far had this problem - did you try and refresh the data? If necessary with deleting the old data before.

**Comment by amis92** [comment]
If you've tried to use files directly from github, please just cleanup all data directories and use "standard" channels.
