### ISSUE TITLE
Cryptothralls are not present in the app at all

### ISSUE THREAD

**Issue by bbeltjr218** [BSData/wh40k-9e#7502]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** For the necrons in 9th edition warhammer 40,000, Cryptothralls cannot be taken with a cryptek in the app, nor are they an option in the elites slot.  I did not see anyone else talking about this problem.

**Comment by DrTobogganMD** [comment]
Cryptothralls are a unit of their own and are not taken as an Elite per the rules of the Cryptothrall. They are in No Force Org.

**Comment by bbeltjr218** [comment]
Thank you!
