### ISSUE TITLE
Ork: Big Mek with KFF Point's Correction

### ISSUE THREAD

**Issue by OCS223** [BSData/wh40k-9e#7506]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:** FAQ this morning changed Big Mek with KFF to 75 points.  Currently listed as 60

**Comment by Velgarn** [comment]
Because the FAQ are related to 8th, the CHAPTER APPROVED with all the points for 9th say it costs 60 excluding wargear and its data sheets doesn't mentions the KFF as equipment to pay for

**Comment by williamcaw** [comment]
chapter approved 2020 july 25. Choppa 0, Slugga 0, Stikkbomb 0 the price is correct page 34 at 60 points for big mek with kff  base cost

**Comment by Dunamis55** [comment]
The FAQ entry now causes conflicting information with the MFM, as the FAQ is for a previous publication and the points cost include wargear; whereas the points cost in the MFM excludes wargrear. Not sure which would be the correct version to use.

**Comment by williamcaw** [comment]
i missed that when reading it last night. the kff is 20 points 60+20=80

**Comment by Velgarn** [comment]
> i missed that when reading it last night. the kff is 20 points 60+20=80
It is BUT the Big Mek with KFF Data Sheet states that the big mek is equipped with Slugga, Choppa and Stikkibombs. it never mentions the KFF as equipment. The KFF cost is for the Big Mek in Mega Armor which appears in his Data sheet

**Comment by tag8833** [comment]
The FAQ is "Indomitus Version 1.0" AKA 9th ed.   So it overrides the MFM.   

PL is 4,  Pts are 75.   He doesn't have the KFF as wargear, but does have a KFF rule, and the KFF no longer works in Close Combat.
