### ISSUE TITLE
Solitaire missing

### ISSUE THREAD

**Issue by lats1367** [BSData/wh40k-9e#7510]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** Yes

**Description:** Detailed issue description.

Solitaire is missing from Harlequins Cat

**Comment by Technoblazed** [comment]
The Solitaire is at the bottom of the Elites section in the cat.

**Comment by lats1367** [comment]
My fault, had a Ynnari model in, problem solved sorry
