### ISSUE TITLE
Inquisitor Kyria Draxus costs 5pts too little

### ISSUE THREAD

**Issue by Dusldorf** [BSData/wh40k-9e#7511]
**File/Catalogue:** Warhammer 40,000 v9.0.0

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Inquisitor Kyria Draxus currently costs 80pts, but CA2020 shows that her correct cost is 85pts.

**Comment by Dunamis55** [comment]
Covered by QA pass in #7563
