### ISSUE TITLE
Manticore Heavy Bolter & Heavy Flamer options are priced incorrectly

### ISSUE THREAD

**Issue by Dusldorf** [BSData/wh40k-9e#7512]
**File/Catalogue:** Warhammer 40,000 v9.0.0

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The Manticore's Heavy Bolter currently costs 8pts, and its Heavy Flamer currently costs 14pts, but CA2020 indicates that both should cost 15.

**Comment by williamcaw** [comment]
dupe of #7457
