### ISSUE TITLE
The total cost of a Thunderfire Cannon (gun + guy) is incorrect

### ISSUE THREAD

**Issue by Dusldorf** [BSData/wh40k-9e#7515]
**File/Catalogue:** Warhammer 40,000 v9.0.0

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Battlescribe shows a total cost for the Thunderfire Cannon (gun + guy) of 195pts, but CA2020 indicates that the total cost is 140pts (85 for gun, 55 for guy including the 10 for his servo harness). Note that Battlescribe correctly shows the costs of these component parts; only the total cost is incorrect.

**Comment by GenWilhelm** [comment]
Looks like this was already fixed - 960344596d9c4e51bbee38632aefeaff7ff295ec
