### ISSUE TITLE
Dark Angels Terminator Weapon Selections

### ISSUE THREAD

**Issue by riverhawks32** [BSData/wh40k-9e#7516]
**File/Catalogue:** Imperium - Dark Angels v150

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Under Deathwing Terminator Squad, Cyclone Missile Launcher/Storm bolter as a heavy weapon selection conflicts with taking either Lightning Claws or Thunder Hammer & Storm Shield.

**Comment by Thairne** [comment]
Seeing that you dont have 3 hands, I find it reasonable that you cant wild 2 Lightning Claws AND a storm bolter.
