### ISSUE TITLE
Tau: XV109 and XV107 now Elites (MFM2020)

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-9e#7519]
As per 9th Chapter Approved (Munitorum Inventory), XV109 Y'vahra Battlesuit and XV107 R'varna Battlesuit are now Elites

_Originally posted by @Alvirulan in https://github.com/BSData/wh40k/issues/7463#issuecomment-664375604_

**Comment by amis92** [comment]
I don't think that Point Cost resource overrides Datasheet's properties like that.

**Comment by williamcaw** [comment]
page 54 cha2020725

**Comment by amis92** [comment]
I've added this to 9th ed problems issue: https://github.com/BSData/wh40k/issues/7390#issuecomment-663841932 and will track it there further.
