### ISSUE TITLE
Space Marines don't have option for "hero of the chapter" stratagem

### ISSUE THREAD

**Issue by Dusldorf** [BSData/wh40k-9e#7522]
**File/Catalogue:** Warhammer 40,000 v9.0.0

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Space Marine characters have no way of accessing the "hero of the chapter" stratagem (i.e., neither in their unit options, nor in their detachment's stratagem options), but this should be possible somewhere.

**Comment by acebaur** [comment]
Which characters? Which chapter? I suspect that you are opening the SM library instead of the individual supplements

**Comment by Dusldorf** [comment]
I discovered the issue with Black Templars but I just tested Raven Guard as well and the issue's there too. Same with Iron Hands. The "stratagems" header in all characters' options is just empty, and the stratagems section for the detachment only shows "relics of the chapter" and "specialist detachment".

**Comment by Valorcalls** [comment]
I can't replicate this unless I try and do it on a detachment without a warlord. It shows up fine for me on the character I try and apply it to.

**Comment by Dunamis55** [comment]
Tested on all Codex compliant chapters in a Patrol detachment, with a Captain as Warlord and Chaplain as secondary character.
Black Templars:
![image](https://user-images.githubusercontent.com/36267768/88577677-53764b80-d03f-11ea-8aff-96aeedb470a5.png)

Imperial Fists:
![image](https://user-images.githubusercontent.com/36267768/88577749-6d179300-d03f-11ea-81db-a877ba60a289.png)

Iron Hands:
![image](https://user-images.githubusercontent.com/36267768/88577927-a7813000-d03f-11ea-8741-a60416d42eae.png)

Raven Guard:
![image](https://user-images.githubusercontent.com/36267768/88577993-c089e100-d03f-11ea-915f-6ad0f2065dac.png)

Salamanders:
![image](https://user-images.githubusercontent.com/36267768/88577848-8e787f00-d03f-11ea-84a4-10fa58cf026b.png)

Ultramarines:
![image](https://user-images.githubusercontent.com/36267768/88577303-b4515400-d03e-11ea-81be-036efebe1f9d.png)

White Scars:
![image](https://user-images.githubusercontent.com/36267768/88577374-d2b74f80-d03e-11ea-93d4-e4677443b411.png)

Am unable to replicate the issue and everything appears to be working correctly.
Please be sure to delete/update your data, and to make sure your **Chapter Selection** option is not set to the "(None)" value:
![image](https://user-images.githubusercontent.com/36267768/88578167-0646a980-d040-11ea-8627-516fb21ba414.png)

**Comment by Dusldorf** [comment]
Ok I found the real problem. The "hero" strat is available if your Warlord is in a Space Marine detachment, but not otherwise. But the stratagem should still be available as long as you've selected a warlord, no matter their faction.

**Comment by Dunamis55** [comment]
Able to reproduce this; can confirm that it seems the stratagem isn't looking for an army-wide Warlord.

**Comment by Muck1ng** [comment]
This affects the new indomitus characters in the Space Wolves Cat also.

**Comment by Dusldorf** [comment]
Not sure if this issue was supposed to have been resolved in the latest update, but it still persists.

**Comment by rfancher** [comment]
Issue still occurring.
BattleScribe v2.03.15 40k 9th Ed v9.2.21
