### ISSUE TITLE
Blood Angels Scouts: Error when selecting camo-cloaks

### ISSUE THREAD

**Issue by Huwage** [BSData/wh40k-9e#7523]
**File/Catalogue:** Imperium - Adeptus Astartes - Blood Angels v159

**BattleScribe version:** 2.03.

**Platform:** iOS

**Dropbox:** No

**Description:** 

When selecting camo-cloaks for Scouts, the app gives the following error notification: 'Scout Squad has 6 too many selections of Camo cloack (maximum 0)

There are 6 Scouts in the squad, so it should be possible to select 6 cloaks...

**Comment by Dunamis55** [comment]
Duplicate of #7533
