### ISSUE TITLE
FAQ updates from 2020-07-27

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7524]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** second rounds of FAQ July 27 2020 effected :as the day goes a long all files

**Comment by amis92** [comment]
For Tau, PA: TGG update:

![image](https://user-images.githubusercontent.com/2671396/88568122-bf08ea80-d038-11ea-9c95-3496a296e91d.png)
