### ISSUE TITLE
Missing Necron Named HQs

### ISSUE THREAD

**Issue by DrVulcan** [BSData/wh40k-9e#7530]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Description:** 
The following Necron named HQs are missing currently:

Vargard Obyron (120 pts), Trazyn the Infinite (100 pts), Orikan the Diviner (110 pts), Nemesor Zahndrekh (135 pts), Imotekh the Stormlord (150 pts).

**Comment by acebaur** [comment]
They are locked to their respective dynasty

**Comment by Dunamis55** [comment]
The units should appear all ok if you ensure the detachment has the correct Dynasty Choice for the unit. E.g. With Sautekh:
![image](https://user-images.githubusercontent.com/36267768/88571482-9fbc8e00-d035-11ea-93f8-7b78ee109fd2.png)

**Comment by DrVulcan** [comment]
I am a potato, thank you very much! Sorry for the inconvenience!
