### ISSUE TITLE
Issue with dark angel primaris lieutenants

### ISSUE THREAD

**Issue by SeanT135** [BSData/wh40k-9e#7532]
**File/Catalogue:** Imperium - Dark Angels v150

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** Primaris Lieutenants unit option only has the choice of Indomitus lieutenants, not the original ones.

**Comment by DrTobogganMD** [comment]
*Technically* now that the Flowchart of Fuckery is gone, the new Datasheet supplants the old one entirely and the old options cannot legally be used.

But that sort of thinking is stupid.

**Comment by SeanT135** [comment]
@DrTobogganMD You're right, that is stupid XD 
What's the flowchart of fuckery?

**Comment by Technoblazed** [comment]
https://files.gitter.im/BSData/wh40k/LxoL/The-Flowchart-of-Fuckery.jpg

**Comment by Thairne** [comment]
This one already was fixed and will be released soon.

**Comment by Detmud** [comment]
Not fixed in 9.0.1
