### ISSUE TITLE
Dark Angels Points errors

### ISSUE THREAD

**Issue by dalamar666** [BSData/wh40k-9e#7535]
**Catalog / File:** Imperium - Dark Angels V150

**BattleScribe version:** 2.03.21.

**Platform:** Windows

**Dropbox:** No

**Description:** Deathwing Ancient Thunderhammer and Storm shield should be 50 points not 19.

Deathwing Knights Storm Shields are still at old cost of 2 points instead of 4.

**Comment by Thairne** [comment]
Storm shields are costed at 4.

![grafik](https://user-images.githubusercontent.com/8590840/88590525-29328700-d05b-11ea-8a0d-2448b10c3c9d.png)
