### ISSUE TITLE
Dark Angels Relics

### ISSUE THREAD

**Issue by dalamar666** [BSData/wh40k-9e#7540]
**File/Catalogue:** Imperium - Dark Angels

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Only tree options show up for relic selection.  Some options change depending on what character is selected, but not all available options are shown.  Example: the CORVUS OCULUS cannot be selected for a Talonmaster.

**Comment by Dunamis55** [comment]
Duplicate of #7475
