### ISSUE TITLE
Chaos Space Marines - Missing Sorcerer With Jump Pack

### ISSUE THREAD

**Issue by KHWELF** [BSData/wh40k-9e#7547]
File/Catalogue: Warhammer 40,000 v9.0.0 - Chaos - Chaos Space Marines v139

BattleScribe version: 2.03.25.338

Platform: Android

Description: Sorcerer With Jump Pack is missing from the HQ options for Chaos Space Marines. It is listed in the newest Munitorum Field Manual.

**Comment by Dunamis55** [comment]
The Jump Pack is available as a wargear option on the Sorcerer.
![image](https://user-images.githubusercontent.com/36267768/88587712-43b23380-d04e-11ea-90f9-0cf68dbaebb9.png)
