### ISSUE TITLE
Mixed Chaos Space Marines and Daemons requiring Supreme Creations

### ISSUE THREAD

**Issue by KHWELF** [BSData/wh40k-9e#7548]
File/Catalogue: Warhammer 40,000 v9.0.0 - Chaos - Chaos Space Marines v139

BattleScribe version: 2.03.25.338

Platform: Android

Description: When creating a mixed detachment of Chaos Space Marines and Chaos Daemons, after choosing a <Legion>, an error appears saying that every HQ unit "...must have 1 more selections from Supreme Creation (Minimum 1)". This is regardless of <Legion>, and doesn't matter if Fabius Bile is in the detachment or not.

**Comment by Dunamis55** [comment]
Need some more information here that might have been lost due to Github formatting. What causes the error to appear exactly?

**Comment by KHWELF** [comment]
When I create a Chaos Space Marines detachment, and add Chaos Daemons to it to make a mixed detachment, any HQ I add to the list pops up with a red exclamation point at the top saying every HQ in the list "...must have 1 more selections from Supreme Creation (minimum 1)"

**Comment by DrTobogganMD** [comment]
While that would create a non battleforged army, I cannot replicate your issue.

![image](https://user-images.githubusercontent.com/16939161/88589557-f66a9d80-d01e-11ea-8edb-cfa6da0f90bf.png)

Please attach a screenshot of your roster with this issue.

**Comment by KHWELF** [comment]
The detachment should be Battleforged as long as all the Daemons and CSM units have the same keyword. In this case Nurgle.

![Screenshot_20200727-133948](https://user-images.githubusercontent.com/68873653/88590062-f82c6500-d00e-11ea-9958-0d7d5a0473ab.jpg)

![Screenshot_20200727-133952](https://user-images.githubusercontent.com/68873653/88590081-fd89af80-d00e-11ea-86ef-51585e501e22.jpg)

**Comment by KHWELF** [comment]
I suppose I should have been more clear, I'm not using Creations of Bile, nor is Fabius Bile in the army at all.

**Comment by Dunamis55** [comment]
I was able to reproduce it, purely by:

1. Taking a Chaos Space Marine detachment
2. Taking any other kind of detachment as a child detachment (Chaos Daemons, Death Guard, Thousand Sons)
3. Taking any HQ choice (except Fabius Bile)

Removing the child detachment doesn't make the error go away, but if you then remove and re-add the HQ choice, the error doesn't reoccur.

**Comment by DylanSp** [comment]
Having the same issue with Fallen as a child detachment.

**Comment by Mad-Spy** [comment]
This is an app bug. It's causing validation to trigger when it shouldn't. I'll raise it with the developer.

https://github.com/BattleScribe/Release/issues/227

**Comment by Mad-Spy** [comment]
I've worked around this for now by making the min1 constraint on the SSEG only be enforced if the parent has a selection of "Supreme Creation".
