### ISSUE TITLE
Necrons-Indomitus Version of 'My Will Be Done' for Non-Indomitus Overlord

### ISSUE THREAD

**Issue by CSheph** [BSData/wh40k-9e#7550]
**File/Catalogue:** Warhammer 40,000 v9.0.0-Necrons v66

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** Yes

**Description:** Detailed issue description.
The non-Indomitus Overlord has the Indomitus version Overlord's 'My Will Be Done' ability when it should still retain the ability as printed in the codex.
![Overlord](https://user-images.githubusercontent.com/68874492/88589688-5efd4e80-d00e-11ea-939c-c549034c6155.png)

**Comment by DrTobogganMD** [comment]
I try to give everyone new things and this is what I get 🤣 

We discussed this in a very civil manner in Discord and I will be changing this as well as adding a unique Warrior and Scarab unit. Because that's how GW do.
