### ISSUE TITLE
Dark Angels - Primaris Lieutenants

### ISSUE THREAD

**Issue by LordBritish2** [BSData/wh40k-9e#7551]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** When adding Primaris Lieutenants I can only add the Indomitus Lieutenants and no other weapon configurations.  This does NOT impact Lieutenants in Phobos armor.

**Comment by Dunamis55** [comment]
Duplicate of #7532
