### ISSUE TITLE
Chaos - Chaos Space Marines: Reaper chaincannon points

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7556]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Reaper chaincannon is valued at 34 points when it is actually only 20

**Comment by Mad-Spy** [comment]
I think you've got confused. The cost you are paying is for the Marine (14pts) and the cannon (20pts).
