### ISSUE TITLE
Death Guard - WotS FAQ updates

### ISSUE THREAD

**Issue by hammyhamm-bugs** [BSData/wh40k-9e#7560]
**File/Catalogue:** Chaos - Death Guard.cat

**BattleScribe version:** 2.03.

**Platform:** Windows

**Description:** 

[as per WotS FAQ updates:](https://www.warhammer-community.com/wp-content/uploads/2020/07/RQcH6wZrusJHsEAr.pdf)

Contaminated monstrosity stratagem should not work on Possessed

Rotskull bomb should list Blast as an ability

**Comment by Mad-Spy** [comment]
Covered by #7594
