### ISSUE TITLE
Inquisition - 9th edition QA points/PL check for file v46

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#7563]
**File/Catalogue:** Imperium - Inquisition v46

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** All errors found during initial QA pass:

- [x] Lord Inquisitor Kyria Draxus is currently 80 points, but should be 85 points
- [x] Inquisitor Greyfax is currently 5 PL, but should be 4 PL
- [x] Ordo Malleus Inquisitor in Terminator Armour’s force axe is currently 0 points, but should be 10 points
- [x] Ordo Malleus Inquisitor in Terminator Armour’s force stave is currently 0 points, but should be 10 points
- [x] Ordo Malleus Inquisitor in Terminator Armour’s force sword is currently 0 points, but should be 10 points
- [x] Nemesis daemon hammer is currently 18 points, but should be 20 points on:
1. Ordo Malleus Inquisitor in Terminator Armour
1. Inquisitor
- [x] Ordo Malleus Inquisitor in Terminator Armour’s psycannon is currently 7 points, but should be 10 points
- [x] Inquisitor’s inferno pistol is currently 7 points, but should be 5 points
- [x] Inquisitor’s condemnor boltgun is currently 1 point, but should be 5 points
- [x] Hot-shot lasgun is currently 4 points, but should be 0 points on:
1. Inquisitor
1. Acolyte
- [x] Inquisitor’s incinerator is currently 20 points, but should be 15 points
- [x] Inquisitor’s meltagun is currently 10 points, but should be 14 points
- [x] Inquisitor’s plasma gun is currently 10 points, but should be 11 points
- [x] Inquisitor’s null rod [Legends] is currently 0 points, but should be 4 points
- [x] Jokaero Weaponsmith’s Jokaero weapons are currently 4 points, but should be 0 points
- [x] Acolyte’s combi-flamer is currently 8 points, but should be 10 points
- [x] Acolyte’s combi-melta is currently 15 points, but should be 10 points
- [x] Acolyte’s combi-plasma is currently 11 points, but should be 10 points
- [x] Acolyte’s flamer is currently 6 points, but should be 5 points
- [x] Acolyte’s power fist is currently 9 points, but should be 10 points
- [x] Acolyte’s power maul is currently 4 points, but should be 5 points
- [x] Acolyte’s power sword is currently 4 points, but should be 5 points
- [x] Acolyte’s storm bolter is currently 2 points, but should be 3 points
- [x] Acolyte’s thunder hammer is currently 16 points, but should be 15 points
- [x] Inquisition Land Raider Prometheus’s multi-melta is currently 25 points, but should be 22 points

**Comment by Forgemaster12** [comment]
An Inquisitor has the option to take Alpha Class Psyker stratagem for +1 Deny & Knows 1 more power for 1CP in the Pariah book, which does not seem to be included on Battlescribe.
