### ISSUE TITLE
Legion of the Damned - 9th edition QA points/PL check for file v9

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#7564]
**File/Catalogue:** Imperium - Legion of the Damned v9

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** All errors found during initial QA pass:

- [x] Damned Legionnaires currently cost 8 PL, but should be 8/14 PL
- [x] Damned Legionnaires > Legionnaire (Heavy Weapon)’s heavy flamer is currently 17 points, but should be 10 points
- [x] Damned Legionnaires > Legionnaire (Heavy Weapon)’s multi-melta is currently 27 points, but should be 22 points
- [x] Damned Legionnaires > Legionnaire (Special Weapon)’s flamer is currently 9 points, but should be 6 points
- [x] Damned Legionnaires > Legionnaire (Special Weapon)’s meltagun is currently 17 points, but should be 10 points
- [x] Damned Legionnaires > Legionnaire (Special Weapon)’s plasma gun is currently 17 points, but should be 11 points
- [x] Damned Legionnaires > Legionnaire Sergeant’s plasma pistol is currently 7 points, but should be 5 points
- [x] Damned Legionnaires > Legionnaire Sergeant’s power fist is currently 12 points, but should be 9 points

**Comment by Guy-Markman** [comment]
Should be fixed in the pull request
