### ISSUE TITLE
Chaos Atrapos Invulnerable only vs shooting

### ISSUE THREAD

**Issue by SMCorey** [BSData/wh40k-9e#7570]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:Android

**Dropbox:No

**Description:
Per GW's published datasheet, Chaos Atrapos has a 5++ to all. Not just ranged. https://www.forgeworld.co.uk/resources/PDF/fw_warscrolls/Cerastus-Knight-Atrapos-Chaos.pdf

**Comment by williamcaw** [comment]
fixed in  86ce39e
