### ISSUE TITLE
Imperium - Deathwatch: Stalker bolt rifle cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7581]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The Stalker Bolt Rifle option on Deathwatch Intercessors costs 1 point when it should be 0 points.

**Comment by DrTobogganMD** [comment]
Already Fixed
