### ISSUE TITLE
Blood angels 9th edition Points Values

### ISSUE THREAD

**Issue by KasmKat** [BSData/wh40k-9e#7582]
**File/Catalogue:** Imperium - Blood Angels v159

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Errors with Points From Munitorum Field Manual

- [ ] Death company Dreadnought and Furioso Dreadnought - Blood talons currently 45 points, Should be 35 points.

**Comment by DrTobogganMD** [comment]
Corrected cost.
