### ISSUE TITLE
Forge World Relic Unit Changes

### ISSUE THREAD

**Issue by KasmKat** [BSData/wh40k-9e#7583]
**File/Catalogue:** Forge World Units

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Several Forge World units have changed their Detachment slots with the New Chapter Approved (Minitorum Field Manual) and haven't been changed - 

- [ ] Relic Deredeo Dreadnought - Currently Elite Slot, should be Heavy Support
- [ ] Relic Javelin Attack Speeder - Currently Elite Slot, should be Fast Attack
- [ ] Relic Sicaran Arcus Strike Tank - Currently Elite Slot, should be Heavy Support
- [ ] Relic Sicaran Battle Tank - Currently Elite Slot, should be Heavy Support
- [ ] Relic Sicaran Omega Tank Destroyer - Currently Elite Slot, should be Heavy Support
- [ ] Relic Sicaran Punisher Tank - Currently Elite Slot, should be Heavy Support
- [ ] Relic Sicaran Venator Tank Destroyer - Currently Elite Slot, should be Heavy Support
- [ ] Relic Whirlwind Scorpius - Currently Elite Slot, should be Heavy Support
- [ ] Deimos Pattern Relic Predator - Currently Elite Slot, should be Heavy Support

Several Forge world units are no longer valid for matched play with the new Chapter approved - 

- [ ] Chaplain Venerable Dreadnought - No longer a valid unit until it gets added to Legends or is re-printed in another book.

Some weapons haven't had Blast added to their Stat blocks - 

- [ ] Grav Flux Bombard
- [ ] Aiolos Missile Launcher
- [ ] Dreadhammer siege cannon
- [ ] Magna-Melta Cannon
- [ ] Plasma Destroyer
- [ ] Thunderhawk Heavy Cannon

**Comment by acebaur** [comment]
We are discussing whether the MFM changes Battlefield role slots or not. However, the Chaplain Dread will remain where it is. The absence of a unit in the MFM does not mean it is no longer a valid option.

**Comment by KasmKat** [comment]
The MFM specifically states - 
"As with the previous editions of the Munitorum Field Manual, this book contains the point values for every single model and item of wargear that, at the time of printing, are supported for matched play games."

While I'll agree that for casual games it's perfectly fine to keep running units not listed in it I would request, for those of us using battlescribe to build tournament lists, that there was some kind of indicator of what isn't valid for matched play/tournaments any longer. Unless I've missed something somewhere that says otherwise that is.

**Comment by alphalas** [comment]
Except the fact that with previous editions of the MFM/CA GW has just said “yeah use last CA’s points, yer fine.”
