### ISSUE TITLE
T'au Empire: Unit slot changes

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7584]
**File:** T'au Empire.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Hi, the Y'vahra, like the R'varna, are in the Elites and not anymore in the Fast and Heavy supports.
Thanks!

**Comment by Technoblazed** [comment]
Reference https://github.com/BSData/wh40k/issues/7390

**Comment by amis92** [comment]
Duplicate of #7519
