### ISSUE TITLE
Imperium - Blood Angels: Death Company Thunder hammer cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7587]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Thunder Hammers for Death Company (the non-primaris ones) are currently 16 points per model, should be 15 points per model

**Comment by alphalas** [comment]
Already been fixed
