### ISSUE TITLE
Battlescribe 40k v9 Battle Forge CP

### ISSUE THREAD

**Issue by swifty-dave** [BSData/wh40k-9e#7588]
On Android

**Description:** Detailed issue description.
I'm seeing Battleforged CP still at 3 CP... is it not starting at 12 and then increasing/decreasing based on detachments/characters etc?

**Comment by Mad-Spy** [comment]
You need to add the "Battle Size" (once) and "Detachment CP" (for each Detachment) selections from the Configuration group and select the size of battle you want to play.
