### ISSUE TITLE
Blood Angels - Missing Units/Wargear

### ISSUE THREAD

**Issue by Huwage** [BSData/wh40k-9e#7590]
**File/Catalogue:** Imperium - Adeptus Astartes - Blood Angels v159

**BattleScribe version:** 2.03.

**Platform:** iOS

**Description:** 

Despite update 9579e42, the following wargear entries and units are still missing from the Blood Angels roster:

- Hand flamer (definitely from Scout and Tactical Sergeants and Company Veterans entries, possibly others)
- Inferno pistol (as above)
- Lightning claws, single and pair (from Tactical Sergeant)
- Normal Dreadnought is missing from unit selection - this does not appear to have been added in 9579e42 at all
- Non-Primaris Lieutenants are missing from unit selection - this also does not appear to have been added in 9579e42

I have updated my data multiple times to confirm this, and am running the latest version of the 40k 9th repositories.

**Comment by alphalas** [comment]
![E05D0171-C5EC-433B-859A-C14337DC973C](https://user-images.githubusercontent.com/15703066/88693443-4a33c000-d0cd-11ea-8675-0481904f0377.png)
![8F5B9B69-F479-4474-86AF-90054C55BBAA](https://user-images.githubusercontent.com/15703066/88693452-4b64ed00-d0cd-11ea-8127-b917c776492a.png)
Lieutenants are also there - weirdly the Dreadnought IS still missing though.

**Comment by DrTobogganMD** [comment]
Will require Lib SM fixes.

**Comment by DrTobogganMD** [comment]
Donezo
