### ISSUE TITLE
Blood Angels - List Entry Errors

### ISSUE THREAD

**Issue by Huwage** [BSData/wh40k-9e#7591]
**File/Catalogue:** Imperium - Adeptus Astartes - Blood Angels v160

**BattleScribe version:** 2.03.

**Platform:** IOS

**Description:** 

~~The Dreadnought list entry is under 'Uncategorised' rather than 'Elite' as it should be.~~

Company Veterans also still lack the option to take Inferno Pistols or Hand Flamers, despite fix 9579e42 .

**Comment by SanguinaryPriestMeros** [comment]
Judiciar is listed as HQ :) He should be under Elites as pr the rules book in the Indomitus box :)
![6ybvn3x3rh851](https://user-images.githubusercontent.com/68896481/88642660-0d61cc00-d0c1-11ea-8b4a-e6a8b39ee2fa.jpg)

**Comment by alphalas** [comment]
Ah that would be why the dreadnought is missing.

The CVets missing options is a separate issue from https://github.com/BSData/wh40k/commit/9579e420917af9444075c763a7d0bce798a3ea25.

**Comment by Mad-Spy** [comment]
Dreadnought issue is fixed in the Agents Rework commit.

**Comment by DrTobogganMD** [comment]
Requires SM Lib fix.
