### ISSUE TITLE
War of the Spider Indomitus Update 1.0

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k-9e#7594]
https://www.warhammer-community.com/wp-content/uploads/2020/07/RQcH6wZrusJHsEAr.pdf

- [ ] Adeptus Custodes
- [ ] Sisters of Silence
- [ ] Officio Assassinorum
- [x] Death Guard

**Comment by Technoblazed** [comment]
No changes to Adeptus Custodes, stratagems only.
