### ISSUE TITLE
Pariah Indomitus Update 1.0

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k-9e#7596]
https://www.warhammer-community.com/wp-content/uploads/2020/07/ZOtIzxxfcdSJudBV.pdf

- [ ] Inquisition

**Comment by Forgemaster12** [comment]
An Inquisitor has the option to take Alpha Class Psyker stratagem for +1 Deny & Knows 1 more power for 1CP in the Pariah book, which does not seem to be included on Battlescribe.

**Comment by Mad-Spy** [comment]
@Forgemaster12, please raise a separate issue. This one is to cover the new update only.
