### ISSUE TITLE
The Greater Good Indomitus Update 1.1

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k-9e#7598]
https://www.warhammer-community.com/wp-content/uploads/2020/03/dZub5FGKGGmigx3x.pdf

- [x] T'au
- [x] Militarum Tempestus
- [x] Genestealer Cults

**Comment by GenWilhelm** [comment]
No changes for GSC.

**Comment by Technoblazed** [comment]
There’s no changes for T’au to be done either. The FAQ change was already done previously. (potentially removed then readded to the FAQ)

**Comment by DrTobogganMD** [comment]
No tempestus changes.
