### ISSUE TITLE
Imperium - Raven Guard: Tome of Malcador validation error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7608]
**File:** Imperium - Raven Guard.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** Tome of Malcador on a Primaris Librarian reports an error when I try to give them a third power. First two powers are from the Librarius discipline. 
The Tome should let him pick another power from any discipline he has access to (in this case, Umbramancy) but when doing so it reports an error.
The error is "Primaris Librarian has 1 too many selections from Disciplines (maximum 2)". 
The three powers selected are from only two disciplines (Librarius and Umbramancy).

**Comment by acebaur** [comment]
All your powers must come from one discipline. The tome does not allow you to break this.
