### ISSUE TITLE
No Corvus Oculus

### ISSUE THREAD

**Issue by nobarkm** [BSData/wh40k-9e#7611]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/Android

**Dropbox:** No

**Description:** Ravenwing Talonmaster does not have access to the Corvus Oculus relic. Released in the Ritual of the Damned psychic awakening, the relic is for Ravenwing Talonmasters only.

**Comment by Mad-Spy** [comment]
Have you selected "Dark Angels" in the Chapter Selection entry in Configuration? The relic shows up fine as long as you have done that.

**Comment by nobarkm** [comment]
Huh, didn't notice there was another update on the 27th. Thank you, it
hadn't prior.
