### ISSUE TITLE
Imperium - Blood Angels: Death Company Jump Pack issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7614]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Death Company should get +1PL/5 models when equipped with jump packs

**Comment by Mad-Spy** [comment]
Additionally, the whole unit has to take Jump Packs at the same time; they can't choose individually according to their data sheet.

**Comment by DrTobogganMD** [comment]
Reworked DC Jump Pack entry/logic to apply to the entire unit and cost 2pts per model and 1PL per 5 models.
