### ISSUE TITLE
Adeptus Sororitas: Sisters Repentia and Repentia Superior

### ISSUE THREAD

**Issue by Grogera** [BSData/wh40k-9e#7618]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
When you try to add a unit of Sisters Repentia to a list with a Repentia Superior, BS will state that "Elites cannot have any selections of Repentia Superior (hidden)". If I then remove the Repenta Superior it will be hidden. If I then remove the Sisters Repentia, Repenta Superior will reappear in the list of choices.

**Comment by Mad-Spy** [comment]
That's because the Repentia Superior does not take up a slot if you take a Repentia squad. She therefore moves to No Force Org Slot, and you should select her from there.

**Comment by Grogera** [comment]
Ah, did not know that. Thanks for the answer!
