### ISSUE TITLE
Dark Angels Still have Issues

### ISSUE THREAD

**Issue by dalamar666** [BSData/wh40k-9e#7625]
**File/Catalogue:** Imperium - Dark Angels

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** I just updated my Data files and deleted old ones. Most of the issues seem to be fix but a few remain.  The Deathwing Ancient cannot select the  "Pennant of Rememberance" Relic. Only Key, Shroud, and Eye show up under Relics of Caliban. Yes chapter selection is Dark Angels not Successor.
![image](https://user-images.githubusercontent.com/17829946/88703260-173ffb00-d0d2-11ea-96fe-8a3dea040212.png)

Deathwing Knight Storm shield points were fixed, but the Knight Master is still wrong. the whole unit of 5 should cost 225.
![image](https://user-images.githubusercontent.com/17829946/88703144-f5df0f00-d0d1-11ea-872e-9dc34524e52e.png)

**Comment by Thairne** [comment]
What a fitting title for this chapter.. 👍
