### ISSUE TITLE
Adeptus Custodes - Error when selecting Storm Shields

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7635]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Custode Gaurd squad causes an error when you select “storm shields” the error says that 0 storm shields are allowed.  The point Value of “bone ‘ead” is incorrect in the bullgryn squad

**Comment by williamcaw** [comment]
Mixed messages.  Two different  publication problems . costodes guard not being re-created, bonhead is fixed

**Comment by Thairne** [comment]
Storm Shield is allowed in combination with a Sentinel Blade, not a spear.
