### ISSUE TITLE
Grey Knights - 9th edition QA points/PL check for file v60

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#7637]
**File/Catalogue:** Imperium - Grey Knights v60

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** All errors found during initial QA pass:

- [x] Techmarine’s combi-grav is currently 10 points, but should be 13 points due to Legends costing
- [x] Techmarine’s grav pistol is currently 5 points, but should be 8 points due to Legends costing
- [x] Techmarine’s lightning claw is currently 5 points, but should be 6 points due to Legends costing
- [x] Techmarine’s power fist is currently 10 points, but should be 9 points due to Legends costing
- [x] Techmarine’s power lance is currently 5 points, but should be 4 points due to Legends costing
- [x] Techmarine’s power maul is currently 5 points, but should be 4 points due to Legends costing
- [x] Techmarine’s power sword is currently 5 points, but should be 4 points due to Legends costing
- [x] Brotherhood Champion is currently 95 points, but should be 90 points
- [x] Brotherhood Champion’s storm bolter is currently 0 points, but should be 3 points
- [x] Twin heavy flamer is currently 30 points, but should be 28 points due to Legends costing on:
1. Dreadnought
1. Venerable Dreadnought
- [x] Purgation Squad’s Purgator (Falchion) currently has one falchion, but should be two falchions
- [x] Razorback no longer has access to lascannon and twin plasma gun (Index) due to removal of flowchart of doom
- [x] Razorback no longer has access to twin heavy flamer (Index) due to removal of flowchart of doom
- [x] Vortimer Pattern Land Raider Redeemer’s multi-melta is currently 25 points, but should be 22 points

**Comment by tekton** [comment]
The falchion thing is just naming- the points were right and it's TECHNICALLY correct, which is the WORST type of correct
