### ISSUE TITLE
Flesh Tearers Chapter Rule Discrepancy

### ISSUE THREAD

**Issue by PsychPenguin** [BSData/wh40k-9e#7640]
File: Imperium - Blood Angels.catz

BattleScribe version: 2.03.21

Platform: Windows

Dropbox: No

Description: Flesh Tearers list "The Red Thirst" as their chapter specific rule instead of their own "Fury Within."  The rule is within the code, just does not show up on Flesh Tearer units.

**Comment by DrTobogganMD** [comment]
I did black magic things to fix this the lazy way.
