### ISSUE TITLE
Space Wolves - Dark Imperium Units missing and no CP refund on WL

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7642]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Space wolves A) are missing the dark imperium units as well as don't have the ability to select battle forged and regain CP

**Comment by CrusherJoe** [comment]
...do you mean Indomitus? The Dark Imperium units were folded in long ago (though they have chapter-appropriate names now).

**Comment by CrusherJoe** [comment]
The Warlord/CP thing is fixed, though.
