### ISSUE TITLE
Imperium space marines - missing hero of the chapter stratagem 

### ISSUE THREAD

**Issue by Pacioman** [BSData/wh40k-9e#7645]
**Warhammer 40.000 9.0.0** 

**BattleScribe version:** v2.03.21.166

**Platform:** Windows/ 

**Dropbox:** No

**Description:** 
"hero of the chapter" stratagem checkbox is missing so it is impossible to give warlord traits to characters

**Comment by acebaur** [comment]
Unless your Warlord is someone other than a SM, it works. Unfortunately there is no way to implement it to make it available for when your Warlord is in another detachment.
