### ISSUE TITLE
Sevrin Loth cannot use his ancestor's psychic powers

### ISSUE THREAD

**Issue by Pacioman** [BSData/wh40k-9e#7646]
*Warhammer 40.000 9.0.0** 

**BattleScribe version:**v2.03.21.166

**Platform:** Windows 

**Dropbox:**  No

Magister Sevrin loth  can attempt to manifest two psychic powers in each friendly Psychic phase, and attempt to deny three psychic powers in each enemy Psychic phase. He knows the Smite psychic power and two psychic powers from the Librarius Discipline. they are six but only 3 of them can be chosen (veil of time, might of heroes and null zone) . 
furthermore models from  successor Chapters can know psychic powers from the first founding ancestor chapter's discipline in the same manner as LIBRARIAN models  of that first founding chapter but I cannot have these options . 

![image](https://user-images.githubusercontent.com/68929693/88739972-32dfeb80-d13c-11ea-8152-b15c8c96d377.png)

**Comment by acebaur** [comment]
Technically he doesn't get access to the codex librarius powers because his entry specifically calls out the index. But he would get access to his parent chapter ones. I'll look into it

**Comment by acebaur** [comment]
It's too much trouble to do the logic to give him the correct access of the Index powers and his parent chapter for one filthy witch, so just take whatever.
