### ISSUE TITLE
Multiple catalogues - wargear not free for certain Forgeworld characters

### ISSUE THREAD

**Issue by spartanbs** [BSData/wh40k-9e#7647]
**File/Catalogue:** 
Imperium - Adeptus Astartes - Iron Hands v15 (probably affects all Adeptus Astartes catalogues, I've checked Raven Guard too)
Imperium - Death Korps of Krieg v130
Orks v80

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 
As per CA2020, all Forgeworld name characters have wargear included in their points costs (denoted by the double asterisk). Certain characters have had the points added on in the above catalogues for common wargear (often wargear without a specific entry in the Forgeworld section of CA2020).

Chaplain Ivanus Enkomi - Catalogue has Power Fist at additional 10 points.
Death Korps Marshal Karis Venner - Catalogue has Memento Mori at additional 10 points and Power Sword at additional 5 points.
~~Warboss on Warbike - Catalogue has Big Choppa at additional 5 points (not 100% sure about this one - assumed the default wargear was what you get for the 100 points).~~ Done - Toboggan

**Comment by Technoblazed** [comment]
Chaplain points are already correct in the latest release, 

![image](https://i.tech-no.me/2020/07/31/200731144355.png)

**Comment by acebaur** [comment]
Astartes is already fixed
