### ISSUE TITLE
Harlequins - Solitaire missing from Elite

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7650]
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Unit Solitaire is missing from Harlequin’s Elites section.

**Comment by FarseerVeraenthis** [comment]
It is there for me.
Unless you have one of the Ynnari characters selected of course...
