### ISSUE TITLE
Imperial Knight Moirax claw 

### ISSUE THREAD

**Issue by Malthas5811** [BSData/wh40k-9e#7651]
**File/Catalogue:** Imperial Knights

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The Armiger Moirax needs the ability to remove the claw and rad cleanser. When attempting any of the multi gun options you get the error for too many weapons, but are unable to get rid of the claw

**Comment by williamcaw** [comment]
it's a button instead of a selectable amount.

**Comment by Mad-Spy** [comment]
You can remove any items from any unit by clicking the X on Windows. You can use this to remove the claw which you don't want.

![image](https://user-images.githubusercontent.com/29306451/88775042-1ebbde80-d17c-11ea-906d-ceac33947b3f.png)
