### ISSUE TITLE
Wrong FoC: helforged dreadclaw, predator, sicaran

### ISSUE THREAD

**Issue by ChaosRaven002** [BSData/wh40k-9e#7652]
**File/Catalogue:** chaos

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** the 'battlefield role' of the hellforged dreadclaw should be dedicated transport. And the hellforged predator and sicaran should be heavy support. This is from chapter approved 2020 MFM pg. 49

Big thanks to everyone who works on this app!

**Comment by Mad-Spy** [comment]
At this time, we are waiting for clarity from GW as to whether these units have actually moved role, or whether it is a mistake in the MFM.
