### ISSUE TITLE
Imperium - Space Wolves - Duplicated Lucius Pattern Dreadnought Drop Pod

### ISSUE THREAD

**Issue by imatsko** [BSData/wh40k-9e#7654]
**File/Catalogue:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.21.165

**Platform:** Linux

**Dropbox:** No

**Description:** Item "Lucius Pattern Dreadnought Drop Pod" is duplicated in unit list.

**Comment by CrusherJoe** [comment]
Good catch, thanks!
