### ISSUE TITLE
Space Wolves - Pts and Ven Dread loadout

### ISSUE THREAD

**Issue by imatsko** [BSData/wh40k-9e#7655]
**File/Catalogue:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.21.165

**Platform:** Linux

**Dropbox:** No

**Description:** Missed points changes in 9th edition:
- Intercessors Auto Bolt Rifle should cost 0pts instead of 5pts now.
- Wulfen dreadnought Fenrisian Great Axe and Great Wolf Claw should be 50 (30+20) instead of 30 (missed Great Wolf Claw profile) 
- Twin assault cannon should cost 30pts instead of 40pts now (CA2020MFM)

Other problems:
- Venerable Dreadnought may take Fenrisian Great Axe and Blizzard Shield alongside with storm bolter or heavy flamer (Codex says: "A Venerable Dreadnought is a single model equipped with an assault cannon, storm bolter and Dreadnought combat weapon." and "This model may replace its assault cannon and Dreadnought combat weapon with a Fenrisian great axe and
blizzard shield." So storm bolter is still on it when it takes Axe and Shield)

**Comment by CrusherJoe** [comment]
You're right about everything, except the storm bolter on the Ven dread -- the storm bolter is part of the DCCW.

**Comment by imatsko** [comment]
@CrusherJoe reopen please. I'm sure Ven Dread takes storm bolter while it has at least 1 CCW. Codex says "This model may replace its Dreadnought combat weapon **and storm bolter** with a missile launcher." or "This model may replace its Dreadnought combat weapon with a great wolf claw."
