### ISSUE TITLE
Lib - Space Marines: Land Raider Redeemer cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7664]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Space marine Land Raider redeemer incorrect points cost stating as 220 with all base  weapons where should be 285.

**Comment by Mad-Spy** [comment]
Duplicate of #7660
