### ISSUE TITLE
Ork Big Mek with Kustom Force Field Points

### ISSUE THREAD

**Issue by libbermeister** [BSData/wh40k-9e#7671]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** iOS

**Dropbox:** No

**Description:** It looks like the data for the Big Mek with Kustom Force Field unit is using the point value from the Saga of the Beast FAQ (which is 75 points). If you look at the new Munitorium Field Manual, this model is listed as 60 points. I'm guessing the wargear/loadout is the same as from the Saga of the Beast book, which would make it so that the Kustom Force Field is still free (as it's listed as an ability now, instead of equipment to take and pay for). You may want to double check with the folks on your dev/rules team, as this was a little confusing to me as to what's correct.

Munitorium Image
![image](https://user-images.githubusercontent.com/28568676/88827590-c1318d00-d18f-11ea-9afa-2173c99c4229.png)

P.S.:Thanks for the great work you guys/gals! Love this app!

**Comment by fuckingenglish** [comment]
It's all ready been fixed it's 80points

**Comment by libbermeister** [comment]
Can you please explain why it's 80 points? I'm just curious. Going off the Saga of the Beast data sheet it doesn't appear that you have to pay for the KFF, as it isn't listed as a wargear option. The aura is an inherent ability of the unit now. Again, I'm just curious, not trying to throw shade at your comment.

![image](https://user-images.githubusercontent.com/28568676/88836474-5d619100-d19c-11ea-8720-13782252592a.png)

**Comment by williamcaw** [comment]
chapter approved 2020 and addition the official app. its off by 5 points 
60 all equipment is free +20 for kff page 34 .

**Comment by Mad-Spy** [comment]
There's a previous FAQ (can't remember offhand which one) which says that Abilities that have the same name as a wargear option are effectively the wargear option and thus cost the same.

**Comment by tag8833** [comment]
Big Mek w/ KFF was FAQ'd to 75 points on Monday (7-26-2020).   This FAQ:  https://www.warhammer-community.com/wp-content/uploads/2020/07/kA6zZq83YtZHZ9Ea.pdf

4 PL, 75 points is correct.

**Comment by williamcaw** [comment]
![IMG_20200730_183254](https://user-images.githubusercontent.com/22287376/88991578-e1e40a80-d295-11ea-9980-7253a57c1837.jpg)
