### ISSUE TITLE
Imperium - Blood Angels: Sanguninary Guard missing Jump Pack Assault

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7682]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Sanguinary guard do not currently have the “Jump Pack Assault” rule on their data sheet. All sanguinary guard should have this rule.

**Comment by DrTobogganMD** [comment]
Applied missing profile link.
