### ISSUE TITLE
Custodes Telemon

### ISSUE THREAD

**Issue by Cystalmist** [BSData/wh40k-9e#7684]
**File/Catalogue:**  Adeptus Custodes 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux Windows

**Dropbox:** Yes/NoNo

**Description:** Detailed issue description.
Telemon Caestus Point wrong - listed in app as 45  in new CA its 30 for 1 and 40 for 2

**Comment by Mad-Spy** [comment]
The cost is for a Caestus (30) and its Twin Plasma projector (15). 45 in total, or 35 each when you take two.

Also, we are using printed material as our reference, not the app.
