### ISSUE TITLE
deathguard missing troop units, nurglings and plaguebearers.

### ISSUE THREAD

**Issue by rmay80** [BSData/wh40k-9e#7686]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** deathguard is missing nurglings and plaguebearers from their troops section.

**Comment by Mad-Spy** [comment]
These units are not valid in a DEATH GUARD Detachment as they do not have the DEATH GUARD keyword.. They are only in the Codex for summoning purposes.
