### ISSUE TITLE
Imperium - Dark Angels: Master Lazarus cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7690]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I think Master Lazarus costs 105 points, but he appears as 110 in the data.

**Comment by Thairne** [comment]
No, he is 110 in MFM 2020.
