### ISSUE TITLE
Imperium - Blood Angels: Blood Talon cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7691]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** According to the Field Manual, Blood Talons are supposed to be 35 not 45.

**Comment by DrTobogganMD** [comment]
Corrected cost.

**Comment by DrTobogganMD** [comment]
Duplicate of #7582
