### ISSUE TITLE
Multiple Catalogs - Land Raider Redeemer Points Incorrect

### ISSUE THREAD

**Issue by MedicinalCarrot** [BSData/wh40k-9e#7693]
**File:** Likely all Space Marines. Checked Imperium - Blood Angels.catz, Imperium - Salamanders.catz, and Imperium - Ultramarines.catz

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** Base cost of the Land Raider Redeemer should be 240 points (280 including the 40 point Assault Cannon), but is listed as 180 points (220 including the Assault Cannon)

**Comment by Mad-Spy** [comment]
Reported several times already.
