### ISSUE TITLE
Multiple Catalogs - Space Marine Heavy Weapons Points Issue When Duplicating Infantry Squads

### ISSUE THREAD

**Issue by MedicinalCarrot** [BSData/wh40k-9e#7694]
**File:** Likely all Space Marines. Checked Imperium - Blood Angels.catz, Imperium - Salamanders.catz, and Imperium - Ultramarines.catz

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** When duplicating an infantry squad containing one or more Heavy bolter, Heavy flamer, Lascannon, Missile launcher, or Multi-melta, the newly created squad will list the points of the heavy weapon(s) as 5 points higher than the actual points cost. Grav-cannon and grav-amp as well as Plasma cannon are unaffected.

Example: A Tactical Squad with a Space Marine w/Heavy Weapon equipped with a Lascannon will correctly list the points of the Lascannon as 15. If that squad is duplicated, the newly created squad will list the Lascannon as costing 20 points.

This is affecting Scout Squads, Tactical Squads, Servitors, Sternguard Veteran Squads, and Devastator Squads. Possibly others. Centurion Devastator Squads appear to be unaffected.

As soon as any other change is made to the list (deleting a squad, changing the loadout of that or another squad, adding a squad, etc), the points cost of the affected wargear will correct itself.

I suspect the issue to be related to the separate points costs for those weapons on infantry vs non-infantry.

**Comment by Mad-Spy** [comment]
It's a Battlescribe issue that we can't do anything about. It's been reported to the developer.
