### ISSUE TITLE
Imperium - Astra Militarum: Gotfret counts as Elite when taken as NFO.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7696]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Gotfret De Montbard correctly uses a "No Force Org Slot" rather than an Elite slot when added alongside a Ministorum priest. However he still counts to the Elite pool for the detachment limits. "Astra Militarum v279 (Patrol Detachment 0CP) has 1 too many selections from Elites (Maximum 2).
This error occurs when only 2 Elite slots are in use, but Gotfret is in the "No Force Org Slot". Therefore he still counts to the elite limit. Thanks!

**Comment by williamcaw** [comment]
The No force org is currently broken because of the agents of the imperium system with in the imperium gstz
