### ISSUE TITLE
How To: Multi Faction Detachments

### ISSUE THREAD

**Issue by FarseerVeraenthis** [BSData/wh40k-9e#77]
## This guide has been moved to our wiki.

See [Creating Detachments Using Multiple Factions](https://github.com/BSData/wh40k/wiki/Creating-Detachments-Using-Multiple-Factions)

---

*Archival content*

~~Want to have an Imperial Soup Army? How about Aeldari Soup? Or, Chaos Soup??~~

~~Sounds tasty, anyway, with the advent of Keywords in both Battlescribe and the New Edition of Warhammer 40,000 you can make whatever soup you want, here's how;~~

1. ~~Select your Parent Army List and choose a Detachment~~
2. ~~Highlight the parent army list, and add more forces, they can only have the same detachment type as the parent.~~
3. ~~Keep going until you heart is content~~

![multi-faction detachments](https://user-images.githubusercontent.com/23246922/27241728-d9605e28-52d1-11e7-9921-4352a7bed681.jpg)

4. ~~Add some units and admire the magic of cross-cat validation working magnificently.~~

![multi-faction detachments 2](https://user-images.githubusercontent.com/23246922/27241742-ed7a67e6-52d1-11e7-9b58-aecc706b45e9.jpg)

5. ~~Enjoy your lovely soupy army :+1: :smile:~~

**Comment by FarseerVeraenthis** [comment]
iOS screenshots from @alphalas 

![](https://farm5.staticflickr.com/4195/34504821944_b372038fda_b.jpg)

![](https://farm5.staticflickr.com/4195/34504821964_a22e8d3053_b.jpg)

![](https://farm5.staticflickr.com/4202/34538126443_780a3abdce_b.jpg)

**Comment by USSX-Hares** [comment]
@FarseerVeraenthis, iOs screenshots no more available.

**Comment by FarseerVeraenthis** [comment]
Yes, I literally just saw that too...

**Comment by FarseerVeraenthis** [comment]
I'm closing this bug, it can still be referenced when closing other issues, but is also referenced in the wiki, and the content is now hosted on the wiki too.
[Wiki Link - Creating Multi-CAT Detachments](https://github.com/BSData/wh40k/wiki/%2377:-Creating-Detachments-Using-Multiple-Catalogues)
