### ISSUE TITLE
Dark Angels - Repulsor is being counted as Heavy Support when it should be Dedicated Transport.

### ISSUE THREAD

**Issue by jasarien** [BSData/wh40k-9e#7705]
**File/Catalogue:** Imperium - Dark Angels v154

**BattleScribe version:** 2.03.15

**Platform:** iOS

**Dropbox:** No

**Description:** 

A Repulsor (not the Repulsor Executioner) is being counted as Heavy Support, when it should be a Dedicated Transport.

Steps to reproduce:

* create a Dark Angels roster, and add a Battalion detachment.
* add units to satisfy the requirements (Battle Size, Chapter Selection, 2 HQ, 3 Troops, select a Warlord) - notice the roster is shown as Valid.
* Add 2 heavy support options (roster still valid, as 3 Heavy Support can be taken)
* Add a Repulsor (selected from the Dedicated Transport section). (Roster still valid)
* Add another Repulsor. Roster shows as invalid and displays the error: "Imperium - Adeptus Astartes - Dark Angels v154 (Battalion Detachment 0CP) has 1 too many selections from Heavy Support (maximum 3)."

**Comment by Thairne** [comment]
Nicely structured report, well done!
But I cannot reproduce the issue.. your BS Vrsion seems to be quite out of date too, since we're up to 2.03.21 right now.
Try updating your BS, maybe this helps with that really weird behavior.

Edit:
Nevermind.
Reading comprehension is a valuable commodity.

**Comment by jasarien** [comment]
> Nicely structured report, well done!

Lol thanks. I’m an iOS developer myself, and I can’t stand bad bug reports, so I try my best not to do the same.
