### ISSUE TITLE
Bug Report: Blood Angels HQ Rule Discrepancies

### ISSUE THREAD

**Issue by PsychPenguin** [BSData/wh40k-9e#7708]
File: Imperium - Blood Angels.catz

BattleScribe version: 2.03.21

Platform: Windows

Dropbox: No

Description: 

There are a number of HQ models which come standard on BattleScribe with the "Black Rage" ability.  This ability is only available to models with the "Death Company" keyword and therefore only available to HQ models if they take the "Death Visions of Sanguinius" Stratagem.

The affected units are as follows:

- The Captain

- Captain in Terminator Armor

- Chaplain

- Chaplain in Terminator Armor

- Lieutenants

**Comment by DrTobogganMD** [comment]
Issue was a duplicated profile linked to the RSE. Verified profile was on Death Visions entry and deleted the duplicates.
