### ISSUE TITLE
Dark Angels - No Warlord Traits selectable when choosing a Primaris Captain (Indomitus) as the Warlord.

### ISSUE THREAD

**Issue by jasarien** [BSData/wh40k-9e#7719]
**File/Catalogue:** Imperium - Dark Angels v154

**BattleScribe version:** 2.03.15

**Platform:**iOS

**Dropbox:** No

**Description:**

When selecting the Primaris Captain (Indomitus) as my Warlord, there are no options for Warlord Traits.

Reproduce:

* Create a new roster with Imperum Dark Angels and add a detachment.
* Add a Primaris Captain (Indomitus) to the HQ section and select it as the Warlord. No options for traits appear.

Also, probably just a nitpick, but shouldn’t it be a Primaris _Master_ (Indomitus) when used in a Dark Angels force? 😆

**Comment by Thairne** [comment]
Nope, the sheet is for a Captain.
Blame GW, they're lazy as fuck.
