### ISSUE TITLE
Ultramarines Supreme Command Detatchment Not Showing Options

### ISSUE THREAD

**Issue by Shaggy002** [BSData/wh40k-9e#7723]
**File/Catalogue:** Imperium Adeptus Astartes Ultramarines v18

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes

**Description:** When adding the Supreme command detachment you get no units at all

**Comment by Technoblazed** [comment]
Related to https://github.com/BSData/wh40k/issues/7666 and https://github.com/BSData/wh40k/issues/7667

**Comment by williamcaw** [comment]
and #7665

**Comment by DrTobogganMD** [comment]
Yep, this was fixed today. Mag/Morty tonight hopefully. Those 3 are the only valid choices in 9e so we reworked the logic.
