### ISSUE TITLE
Ynnari Warlord Traits not Appearing for Harlequin Characters

### ISSUE THREAD

**Issue by SoullessSamurai** [BSData/wh40k-9e#7728]
**File/Catalogue:** Harlequins.catz and/or Ynnari.catz

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** When you select a Harlequin character as your Ynari Warlord, the Ynnari Warlord Traits don't appear at all. 

If you add the 'Exalted of Ynnead' stratagem, then 'Inspiring Leader' (a BRB trait) appears, but the Ynnari ones still aren't visible, nor for some reason are the other two BRB traits. 

However, Ynnari traits do work with Drukhari if you choose an Archon or Succubus as your Warlord. 

I don't know if this has anything to do with it, but with Drukhari there's simply a 'Warlord' box, whilst with Harlequins it changes to 'Ynnari Warlord'. Is it possible that 'Ynnari Warlord' is linking to an empty/nonexistent path?

**Comment by DrTobogganMD** [comment]
Ynnari traits missing is an issue of course, but the other 2 brb traits no longer exist in 9E.

**Comment by buckeyede06** [comment]
I am not sure if this is related to this bug, but now the app crashes entirely with only my Craftworld lists built with v97.

**Comment by FarseerVeraenthis** [comment]
Yes, sorry, we've not managed to get those rascal Ynnari to cooperate properly yet. 
Negotiations are ongoing, hopefully this sorry mess will be fixed Soon(TM).
As for the problem with v97 crashing, I don't know what that is just now, I'll look into it :-)

**Comment by SoullessSamurai** [comment]
Ah, I hadn't realised that the other BRB traits had been removed now. When I saw that only one of those was showing up, I just assumed it was the Ynnari aspect acting up. 

Apologies for bringing that up then.

**Comment by tierdar** [comment]
I have this working for myself now, as it pertains to Craftworlds.  Harlequins would follow a similar example to the CW catalog.

1. in the Ynnari data file:
  Deselect hidden on Warlord Trait (Ynnari) and Warlord Traits (Ynnari).
  Delete any "Hidden if" conditions in the Warlord Traits (with an "S")


2. In Craftworlds:

  1)	Remove warlord traits & ynnari warlord from all characters.
  2)	Add Warlord Traits (Combined)
  3)	Add Exalted of Ynnead stratagem
    a)	Hidden by default.
    b)	unhidden if Equal to 1 Selections in Force of Ynnari (Shared)
  4)	Update Remnants of Glory to Hidden
    a)	Unhide if:
    b)	(and)
      i)	Equal to 0 Selections in Force of ynnari
      ii)	(or)
        iii)	if Equal to 1 selections in Force of Treasures of the Craftworld (1 Relic)
        iv)	if Equal to 1 selections in Force of Treasures of the Craftworld (1 Relic)
        v)	if Equal to 1 selections in Parent of Warlord
  5)	Update Artefacts of Death to Hidden
    a)	Unhide if:
      b)	(and)
      i)	Equal to 1 Selections in Force of ynnari
      ii)	(or)
        iii)	if Equal to 1 selections in Force of Treasures of the Craftworld (1 Relic)
        iv)	if Equal to 1 selections in Force of Treasures of the Craftworld (1 Relic)
        v)	if Equal to 1 selections in Parent of Warlord
  6)	In each HQ profile, remove the "Hidden if" condition for Artefacts of Death
  7)	Create a new Shared Selection Entry Group 
    a)	Set hidden to False if:
    b)	or
      i)	if Equal to 1 Selections in Parent of Warlord
      ii)	if Equal to 1 Selections in Parent of Stratagem: Exalted of Ynnead (Shared) [Aeldari - Ynnari]
      iii)	if Equal to 1 Selections in Parent of Stratagem: Field Commander (Shared) [Warhammer 40,000 9th Edition]
    c)	Create 3 sub entry groups 
    d)	Craftworld Warlord Traits. (copy / paste the warlord traits entry, and rename)
      i)	Not hidden by default.
      ii)	Remove the "set Hidden to True" conditions under each trait.
      iii)	hide if parent is ynnari.
    e)	BRB Warlord Traits. (copy / paste the brb traits entry)
      i)	Not hidden by default.
      ii)	hide based on current "hidden" settings in the existing entry - and add 
      iii)	Delete the brb warlord traits entry from Craftworld warlord traits
    f)	Ynnari Warlord Traits.
    g)	Set Hidden.
    h)	Create a condition group
      i)	Set hidden to False if:
      ii)	Parent is warlord (9th)
      iii)	Parent contains stratagems, specialist detachment or exalted of ynnead

**Comment by DrTobogganMD** [comment]
Combined into #8056
