### ISSUE TITLE
Imperium - Space Wolves - Problem with warlord selection

### ISSUE THREAD

**Issue by imatsko** [BSData/wh40k-9e#7737]
**File/Catalogue:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.21.166

**Platform:** Linux

**Dropbox:** No

**Description:** On roster with single Warlord in single patrol detachment showed problem: 
![pic](https://user-images.githubusercontent.com/7344843/89003060-6f137780-d307-11ea-8423-a4b9374c3bd7.png)
[problem_roster.zip](https://github.com/BSData/wh40k/files/5005242/problem_roster.zip)

**Comment by Mad-Spy** [comment]
For Dev: The local SW Warlord SSE has the GST one linked inside it unnecessarily, which is causing BS to count the WARLORD category twice. It doesn't need the link, as all validation is done off of the Category.
