### ISSUE TITLE
Imperium - Dark Angels: Deathwing Terminator loadout

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7738]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Deathwing Terminators Should be able to change loadout to TH/SS or LigthingClaws and THEN take a Cyclone Missile Launcher.
[Anon] Bug report: Imperium - Dark Angels.catz #7701didnt fix the problem as the Stormbolter is still attached to the Cyclone Launcher...

**Comment by Mad-Spy** [comment]
Fixed in the latest release, DA v155.
