### ISSUE TITLE
Cost of handflamers genestealer cults bug

### ISSUE THREAD

**Issue by Madjikou** [BSData/wh40k-9e#7740]
Warhammer 40000 v9.0.4

2.03.21

 Windows

Issue with handflamer cost for genestealer cults (seen on Acolyt hybrids) it is 10, should be 2.

**Comment by Mad-Spy** [comment]
The 10pts is for the Acolyte _and_ his handflamer.

**Comment by Madjikou** [comment]
My bad :) 
Thanks !
