### ISSUE TITLE
[Anon] Bug report: Imperium - Blood Angels: Death Mask Points Cost Error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7744]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** In the "Sanguinary Guard" entry, the "Death Mask" option is still priced at 2 points per mask, which was its old cost in 8th Edition. In the new points, it was reduced to 0 points.

**Comment by DrTobogganMD** [comment]
Already Fixed
