### ISSUE TITLE
[Anon] Bug report: Imperium - Blood Angels: Judicar and Techmarine RSE Errors.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7745]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Judiciar is included in the "HQ" category, but it's an "Elite" choice. Same with the "Techmarine" entry, but on reverse: he's in the "Elite" category, but he sould be "HQ".

**Comment by DrTobogganMD** [comment]
Already Fixed
