### ISSUE TITLE
Deathwatch Points cost issues

### ISSUE THREAD

**Issue by corrinavatan** [BSData/wh40k-9e#7746]
**File/Catalogue:** 40k 143 / Deathwatch 95

**BattleScribe version:** 2.03.21

**Platform:** Windows/Android/

**Dropbox:** Yes/No

**Description:** The following points are incorrect for Deathwatch:

Intercessors datasheet: Auto Bolt Rifle listed as 1 point.  CA Grand Tournament has it listed as 0.

Intercessors datasheet:  Inceptors are paying 10p each for Assault Bolters, when these went down to 0.

Inceptors datasheet - Assault Bolters are incorrect points for non-Inceptor Sergeants, again showing 10p each when have been reduced to 0.

**Comment by GenWilhelm** [comment]
Looks like these were fixed this morning in Deathwatch v96 (ceaa02e408658676c2f9d38e53b736b041322b69) - it will be available with tonight's release.

**Comment by corrinavatan** [comment]
My apologies!
