### ISSUE TITLE
Nob 2nd Killsaw Points

### ISSUE THREAD

**Issue by epicdump** [BSData/wh40k-9e#7753]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Points for second Killsaw under "Nobz" and "Nobz on Warbikes" are both currently set at 8 pts.  The second Killsaw should be 5 pts according to chapter approved Munitorum Field Manual 2020 page 34

**Comment by Technoblazed** [comment]
This was already been resolved in a previous update. Please check that your datafiles are up to date.

![Image](https://i.tech-no.me/2020/07/31/200731220808.png)
