### ISSUE TITLE
[Anon] Bug report: Space Marines:  Primaris Chaplain missing Relic Options.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7756]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Primaris Chaplain in White Scars armies is missing the option to take the Codex Relic “Benediction of Fury”

**Comment by acebaur** [comment]
Already fixed
