### ISSUE TITLE
CSM Defilers explode is incorrect.

### ISSUE THREAD

**Issue by Acevenuis** [BSData/wh40k-9e#7759]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** All

**Dropbox:** No

**Description:** The Defilers explode section incorrectly states that you roll a D6 to determine the explosion radius. It should be a flat 6 inches.

**Comment by Mad-Spy** [comment]
This has been wrong for the entirety of 8th edition, and you are the first person to ever notice. You win some kind of (non-existent) prize.
