### ISSUE TITLE
[Anon] Bug report: Imperium - Adepta Sororitas: Canonness Power Sword Cost Wrong

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7761]
**File:** Imperium - Black Templars.catz

**BattleScribe version:** 9.00.03

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Adepta Sororitas Canonness Power Sword is 4pts, should be 5pts.

**Comment by alphalas** [comment]
update your data.
