### ISSUE TITLE
Add Grukk Facerippa, Goff Rokker and Skrak's Skull-Nobz for Orks open Play. White Dwarf 454

### ISSUE THREAD

**Issue by LestatBCN** [BSData/wh40k-9e#7762]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by fuckingenglish** [comment]
Hay it's all ready opened #7437

**Comment by Mad-Spy** [comment]
Duplicate of #7437
