### ISSUE TITLE
necrons: missing Cryptothralls from Indomitus 

### ISSUE THREAD

**Issue by ConstantinesGuard** [BSData/wh40k-9e#7765]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

I cannot find the Cryptothralls from the Indomitus box (Elite).

**Comment by DrTobogganMD** [comment]
Re-read the datasheet. They won't be in Elites. No Force Org.

**Comment by ConstantinesGuard** [comment]
Hi Earl,

Thank you so much. I found them 😃.

Kind regards,

Jens Müller



-------- Oorspronkelijk bericht --------
Van: Earl Bishop <notifications@github.com>
Datum: 01-08-2020 15:21 (GMT+01:00)
Aan: BSData/wh40k <wh40k@noreply.github.com>
Cc: ConstantinesGuard <jens.mueller.83@outlook.com>, Author <author@noreply.github.com>
Onderwerp: Re: [BSData/wh40k] necrons: missing Cryptothralls from Indomitus  (#7765)


Closed #7765<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBSData%2Fwh40k%2Fissues%2F7765&data=02%7C01%7C%7C4794410d64344a5ff5fc08d8361dbfc0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637318848674296744&sdata=LC6JfJ40HB1J7NL7VnwJ3WbGCsSgPXcA%2BrcQgJ%2Fdo%2FQ%3D&reserved=0>.
