### ISSUE TITLE
[Anon] Bug report: Chaos - Daemons: DP of Chaos cannot select a Psyker Power

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7766]
**File:** Chaos - Daemons.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The Daemon Prince of Chaos entry doesn't allow, as it should, to select a Psychic Power when a Allegiance other than Khorne has been selected.
It should offer the same multiple choice as the Daemon Prince from Chaos Space Marine data offers.
Thank you and keep up the good work!

**Comment by Mad-Spy** [comment]
You need to drill down into the Allegiance selection you made to select the powers.
