### ISSUE TITLE
Inquisitors and assassins not availble on Mobile app

### ISSUE THREAD

**Issue by Ryumidori** [BSData/wh40k-9e#7767]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** Yes

**Description:** Detailed issue description.
I made a roster on my Pc and shared in to my mobile phone to always have it ready but for some reason on the 9th update (9.0.4) and after on my phone the inquisitor is no longer available to select in the no force slot and it deleteds all the added ones ( i tried multiple different ones).

No clue why it wont do this on my pc but on phone they cant be added.

App is upto date as well is the database.

**Comment by DrTobogganMD** [comment]
They now have a unique slot in valid detachments to resolve some other bugs they were causing. Look for Agents of the Imperium in a valid detachment.

**Comment by Ryumidori** [comment]
Can you define valid for me cause i cant add one in a spearhead detatchment
Edit: also hector rex is missing

**Comment by alphalas** [comment]
The three main (pat, bat, brig)

**Comment by Ryumidori** [comment]
Oke, i thought they could go in any other but i gues i will work around that for the time being.

Thank you for the quick response

**Comment by DrTobogganMD** [comment]
"Oke, i thought they could go in any other but i gues i will work around that for the time being."

That's the rules for the unit, not a work around. You'll want to look at the Psychic Awakening books.

**Comment by Ryumidori** [comment]
My apologies,

It is indeed correct, I had to ask a friend since I dont own the inquisitor book myself. 
I based my answer on the description in battlescribe.
