### ISSUE TITLE
Ynarri WT Issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7769]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** When I select Yinari as a faction, and select a warlord, it gives me an option for relics, but not warlord traits. I have my roster built in Unbound Army Faction and select Yinari from that, which shouldn’t be an issue, but I thought I’d mention that.

**Comment by DrTobogganMD** [comment]
Combined into #8056
