### ISSUE TITLE
[Anon] Bug report: Imperium - Ultramarines: Robot Gorillaman Missing From SupCom

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7770]
**File:** Imperium - Ultramarines.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Roboute Guilliman seems to be missing from the Ultramarines file. I created an Ultramarines roster with the Supreme Command detachment and there was no force org menu for Lord of War or any other battlefield role. There were force org menus for "Configuration" and "Stratagems." The force org menu did not appear when I had no configuration selection and when I had added the minimum required configuration selections and all configuration selections I would normally use.  I tried creating an Ultramarines roster consisting only of a super heavy auxillary detachment to see if Lord of War selections were available at all, but it only had Forge World units, no Guilliman.

**Comment by DrTobogganMD** [comment]
Did you select UM as your chapter?
