### ISSUE TITLE
Necron Warlord Traits

### ISSUE THREAD

**Issue by jmarra0998** [BSData/wh40k-9e#7773]
**File/Catalogue:** 

**Platform:** Windows/iOS/Android/Mac/Linux

**BattleScribe version:** 2.03.

**Dropbox:** Yes/No

**Description:** Validation is demanding that all HQ choices take warlord and a warlord trait, but also isn't validating if you have multiple warlords
![bs error](https://user-images.githubusercontent.com/69090791/89109872-129d7e80-d413-11ea-8da2-bbf2baf5d304.PNG)

**Comment by DrTobogganMD** [comment]
Well poop. Ok I'll take a look and get it fixed for tonight's release.

**Comment by jmarra0998** [comment]
okay thank you (I was just taking some more screenshots, I'll include them in case you need them
![bs error 2](https://user-images.githubusercontent.com/69090791/89109913-6ad48080-d413-11ea-9605-407c737e64e8.PNG)
![bs error 3](https://user-images.githubusercontent.com/69090791/89109914-6b6d1700-d413-11ea-8922-877081c03138.PNG)

**Comment by DrTobogganMD** [comment]
Thanks. I'm fairly sure where I messed up. I moved the Warlord Traits up 1 level to lessen the clicks and make it so you didn't have to go a level deeper than needed. When I did that, I believe the logic I was using became invalid but I didn't check it.

**Comment by jmarra0998** [comment]
Glad I could help
