### ISSUE TITLE
SM White Scars Terminator units missing points and options

### ISSUE THREAD

**Issue by Gunfex** [BSData/wh40k-9e#7774]
**File/Catalogue:** Imperium - Adeptus Astartes - White Scars v15

**BattleScribe version:** 2.03.15

**Platform:** iOS

**Dropbox:** No

**Description:** Librarian in Terminator Armor does not have a selection to apply Hero of the Chapter strategem (also does not appear in general Strategems section) to take a Warlord Trait when not selected as the actual warlord.  Both Tartaros Terminators’ and Cataphractii Terminators’ Grenade Harness should now be 5 points each, not 0 points.

**Comment by acebaur** [comment]
Witch in TDA is correct, he has HOTC. Fixed the points on the harness
