### ISSUE TITLE
Imperium - Adeptus Custodes: FW Inquisitors missing from Agents of the Imperium

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7777]
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Inquisitor Lord Hector Rex does not show up Uber “Agents of the Imperium.”

**Comment by williamcaw** [comment]
it cant be unless theres a new publication stating that he is apart of the agents of the imperium

**Comment by Mad-Spy** [comment]
Hector Rex (and Solomon Lok) have not been given the AGENTS OF THE IMPERIUM keyword, so they are currently not able to be taken via that rule.

They were previously added there by mistake.
