### ISSUE TITLE
Dark Angels - Lieutenant Tactical Precision - <CHAPTER> instead of DARK ANGELS

### ISSUE THREAD

**Issue by Detmud** [BSData/wh40k-9e#7778]
**File/Catalogue:** 9.0.5

**BattleScribe version:** 2.03.

**Platform:** iOS

**Dropbox:** No

**Description:** Dark Angels - Lieutenant Tactical Precision - <CHAPTER> instead of DARK ANGELS (it's inconsistent with the other occurrences of the Tag

**Comment by Thairne** [comment]
A minor issue you'll have to live with till October due to the DA file using the general library. Once the new stuff rolls around, things will change anyway.
