### ISSUE TITLE
Dark Angels - Stratagem HERO OF THE CHAPTER Missing

### ISSUE THREAD

**Issue by Detmud** [BSData/wh40k-9e#7779]
**File/Catalogue:** 9.0.5

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** I can't choose too use the Stratagem HERO OF THE CHAPTER in Battlescribe. (Choosing a Warlord Trait without being the Warlord)

**Comment by Thairne** [comment]
You need a warlord first.
