### ISSUE TITLE
Space Wolves Wolf Priest issue

### ISSUE THREAD

**Issue by Shoxaju** [BSData/wh40k-9e#7780]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/Android

**Dropbox:** Yes

**Description:** Primaris Wolf Priest's Crozius (as well as other Primaris chaplains) is s+2 not s+1 as of indominus launch. It's supposed to only be for the one from indominus, but it's otherwise completely identical the regular Primaris Chaplain/Wolf Priest so I'm not sure if it there is supposed to be two entries for otherwise identical models or if it would be easier to just use the new stat line

**Comment by Muck1ng** [comment]
Rather than raising a new issue Ulriks profile needs updating to the one from the latest FAQ

**Comment by Shoxaju** [comment]
that's a separate issue that was already posted. I'm talking specifically about the Primaris Chaplain/wolf Priest.
