### ISSUE TITLE
FW Adeptus Astartes & Adeptus Astartes: Missing Catalogues

### ISSUE THREAD

**Issue by SargentJakeman** [BSData/wh40k-9e#7782]
**File/Catalogue:** Imperium_FW Adeptus Astartes.cat & Imperium-Space Marines.cat

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** When pulling up battlescribe list creator, the files above are not showing up. The other files are popping up fine, but these 2 are the only ones I'm having trouble seeing.

**Comment by Mad-Spy** [comment]
Those catalogues have not been visible for several months. All Forgeworld models have been merged into the parent catalogues.
Space Marines were split into Chapters to improve loading. You should choose the parent Chapter file instead.

**Comment by SargentJakeman** [comment]
So, what chapter would the minotaurs belong to? That's really the only problem I'm having.

**Comment by Mad-Spy** [comment]
Whichever one you choose to be their parent, as there is no lore to specify which it is.

Then choose Minotaurs from the Chapter Selection entry under Configuration.

**Comment by SargentJakeman** [comment]
That makes sense, thank you sir!
