### ISSUE TITLE
Imperium - Space Wolves: Primaris Lieutenant in Phobos Armour has gone missing.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7783]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Primaris battle leader in phobos armor is missing from the Space wolf catalog after most recent update to 9.0.6

**Comment by Mad-Spy** [comment]
Technically, there is no such unit. That unit was a duplicate of the "Primaris Lieutenant in Phobos Armour" (which never got renamed by GW). However, both are now missing so something has definitely gone awry.
