### ISSUE TITLE
Forge World Inquisitors missing from Agents of the Imperium List.

### ISSUE THREAD

**Issue by Muck1ng** [BSData/wh40k-9e#7785]
**File/Catalogue:**  I've checked the Adepta Soroitas and the Space Wolves and neither are showing the forgewold inquisitors are showing from Agents of the Imperium List.

**Comment by Mad-Spy** [comment]
Those models have never been given the "AGENTS OF THE IMPERIUM" keyword via any update, so they are not currently valid to be added via that rule.

**Comment by Muck1ng** [comment]
Ok  but they can't be added at all they should be in the "No Force Org" part?

**Comment by Muck1ng** [comment]
Will this issue be re-opened then?

**Comment by alphalas** [comment]
No because the rule that allowed them to be taken as a NFO was changed to require the AOI keyword.

**Comment by Muck1ng** [comment]
Surely that’s just for the inquisitors in the phariah book not the inquisitors in forgeworld book. They can still be taken as was because their data sheets are the same.

**Comment by alphalas** [comment]
No because the NFO inquisitor in any detachment  Rule was updated to require the keyword, which they lack.

**Comment by alphalas** [comment]
![Screen Shot 2020-08-02 at 11 26 29](https://user-images.githubusercontent.com/15703066/89126385-47f9a900-d4b3-11ea-8cca-f20401c3874b.png)
![Screen Shot 2020-08-02 at 11 27 29](https://user-images.githubusercontent.com/15703066/89126387-49c36c80-d4b3-11ea-922b-d6734f1da8e7.png)

**Comment by Muck1ng** [comment]
So you’re saying that Authority of the Inquisition no longer works? Is there somewhere that states this is no longer applicable?

**Comment by alphalas** [comment]
@Muck1ng 
![Screen Shot 2020-08-02 at 11 43 52](https://user-images.githubusercontent.com/15703066/89126657-77a9b080-d4b5-11ea-922b-7689ddfb72e3.png)

This is specifically what's preventing it.
Authority of the Inquisition ITSELF has changed

**Comment by alphalas** [comment]
This is Authority from the WD:
<img width="228" alt="Screen Shot 2020-08-02 at 11 42 10" src="https://user-images.githubusercontent.com/15703066/89126680-9e67e700-d4b5-11ea-840f-f01fda5405f3.png">
It was updated to this in PA: Pariah:
![](https://user-images.githubusercontent.com/15703066/89126385-47f9a900-d4b3-11ea-8cca-f20401c3874b.png)

because it's a rule with the same name, it is overwritten.

**Comment by alphalas** [comment]
take notice it use to be "one INQUISITOR may be included", but it updated the wording to be "you can include one AGENTS OF THE IMPERIUM", meaning the required keywords have changed. Rex and Look do not have said AOI keyword.

**Comment by Muck1ng** [comment]
Right. Ok that makes sense.  Shame this wasn’t picked up on the Indomitus FAQ they released not long ago. *Sigh* Submitted it to the FAQ team.   This is obviously an oversight as they've updated the points
