### ISSUE TITLE
Baneblade and variant weapons missing blast

### ISSUE THREAD

**Issue by normanthesquid** [BSData/wh40k-9e#7793]
**File/Catalogue:** Astra Militartum

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Multiple baneblade weapons are missing blast

- Baneblade Cannon (Baneblade)
- Tremor Cannon (Banehammer)
- Quake Cannon (Banesword)
- Magma Cannon (Doomhammer)
- Turret-mounted Hellhammer Cannon (Hellhammer)
- Volcano Cannon (Shadowsword)
- Stormsword Siege Cannon (Stormsword)

**Comment by Technoblazed** [comment]
Completed in https://github.com/BSData/wh40k/pull/7816.
