### ISSUE TITLE
Imperium - Ultramarines: Roboute Guilliman bonus CP from Author of the Codex does not work

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7794]
**File:** Imperium - Ultramarines.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Roboute Guilliman doesn't correctly grant his CP bonus when is the warlord.

**Comment by Mad-Spy** [comment]
@acebaur, The condition is set to "in Parent", but should be Self or "Roboute Guilliman"
