### ISSUE TITLE
Space Wolves Cat - Ulrik the Slayer new Datacard

### ISSUE THREAD

**Issue by Muck1ng** [BSData/wh40k-9e#7799]
Ulrik the slayer needs his datacard updating to match the new FAQ.

**Comment by DrTobogganMD** [comment]
https://www.warhammer-community.com/wp-content/uploads/2020/07/kA6zZq83YtZHZ9Ea.pdf

**Comment by CrusherJoe** [comment]
PR auto-closed, re-opening to add second Litany.

**Comment by Technoblazed** [comment]
Completed in https://github.com/BSData/wh40k/pull/7800, PR wasn't updated to reflect the extra change.
