### ISSUE TITLE
aggressors autoboltstorm pts

### ISSUE THREAD

**Issue by Garvlok** [BSData/wh40k-9e#7802]
**File/Catalogue:** Imperium - spacewolves.cat

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:** auto boltstorm pts for aggressors are 15 and should be 0

**Comment by Technoblazed** [comment]
Doesn't seem to be a bug, the fragstorm grenade launcher that goes alongside this is 5 points per model. 5 * 3 models = 15 points.
