### ISSUE TITLE
Imperium - Adepta Sororitas: Mortifiers unit size issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7805]
**File:** Imperium - Adepta Sororitas.catz

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** No

**Description:** The Adepta Sororitas unit 'Mortifiers' should be able to contain 6 Mortifier models in total (1 may be exchanged for an Anchorite), but currently it caps at 4. Please update the unit so that it can contain up to 6 models without giving an invalid error.

**Comment by Mad-Spy** [comment]
The limit was changed to max 4 in the unit in a previous Sororitas update.
