### ISSUE TITLE
[Anon] Bug report: T'au Empire: Commander Shadowsun Missing From SupCom

### ISSUE THREAD

**Issue by Nedwardo** [BSData/wh40k-9e#7806]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** I created an T'au Empire roster with the Supreme Command detachment and there was no option for HQ. I then made a Battalion detachment and Commander Shadowsun was listed, so it appears Commander Shadowsun is just missing the supreme commander tag.

**Comment by Mad-Spy** [comment]
Shadowsun does not have the SUPREME COMMANDER keyword which is required to be part of a SupCom; she has an ability which is called Supreme Commander. They are not the same thing. Currently, the only models which can be in that Detachment are Magnus, Mortarion and Roboute Guilliman.
