### ISSUE TITLE
Dark Angels - 9th edition QA points/PL check for file v156

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#7813]
**File/Catalogue:** Imperium - Adeptus Astartes - Dark Angels v156
**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** All errors found during initial QA pass:

- [x] Land Raider Excelsior is unable to be taken by Dark Angels, but should be as per Legends: Dark Angels publication
- [x] Litany: Stoic Prosecution is unavailable for selection on:
1. Chaplain on Bike [Legends] 
1. Asmodai
- [x] Power lance is currently 5 points, but should be 4 points on:
1. Techmarine on Bike [Legends]
1. Interrogator-Chaplain on Bike [Legends]
1. Interrogator-Chaplain
1. Master
1. Lieutenants
1. Techmarine
1. Company Ancient
1. Company Veterans
1. Chapter Ancient
1. Assault Squad > Space Marine Sergeant
1. Ravenwing Black Knights > Ravenwing Huntmaster
- [x] Litany: Stoic Prosecution is available for selection twice on:
1. Interrogator-Chaplain
1. Interrogator-Chaplain in Terminator Armour
- [x] Interrogator-Chaplain in Terminator Armour is currently 106 points, but should be 105 points
- [x] Master in Phobos Armour’s master-crafted instigator bolt carbine is currently 6 points, but should be 0 points
- [x] Lieutenant in Phobos Armour is currently 4 PL, but should be 5 PL
- [x] Primaris Master is currently 78 points, but should be 85 points
- [x] Primaris Master’s bolt carbine with special issue ammunition is currently 0 points, but should be 5 points
- [x] Infiltrator Squad currently costs 5/10 PL, but should cost 5/11 PL
- [x] Impulsor currently costs 4 PL, but should cost 6 PL
- [x] Azrael grants 1 Command Point, even if he isn’t the Warlord
- [x] Belial’s lightning claw (pair) currently costs 10 points, but should be 0, as his costs include wargear
- [x] Belial’s thunder hammer and storm shield currently costs 25 points, but should be 0, as his costs include wargear
- [x] Primaris Librarian is currently 5 PL, but should be 7 PL
- [x] Master in Terminator Armour should have a storm bolter and a relic blade as default wargear options
- [x] Master in Cataphractii Armour should have a combi-bolter and a chainfist as default wargear options
- [x] Primaris Master should have a master-crafted auto bolt rifle as a default wargear option
- [ ] Lieutenants should have a master-crafted boltgun and a chainsword as default wargear options
- [x] Techmarine currently costs 40 points, but should be 50 points
- [x] Primaris Lieutenants currently cost 65 points, but should be 70 points
- [x] Tactical Squad currently costs 4/7 PL, but should cost 5/9 PL
- [x] Scout Squad currently costs 4/7 PL, but should cost 4/8 PL
- [x] Primaris Apothecary currently costs 3 PL, but should be 4 PL
- [x] Chapter Ancient should have a bolt pistol as default wargear
- [x] Heavy flamer is currently 15 points, but should be 10 points on:
1. Deathwing Cataphractii Terminator Squad
1. Deathwing Tartaros Terminator Squad
- [x] Deathwing Tartaros Terminator Squad > Tartaros Terminator currently has access to standard Terminator heavy weapons, but shouldn’t be able to take such weapons
- [x] Contemptor Dreadnought is currently 88 points, but should be 105 points
- [x] Aggressor Squad is currently 6 PL, regardless of number of models, but should be 6PL at 3 models and 12 PL at 4+ models
- [x] Servitors are currently 2 PL, but should be 3 PL
- [x] Servitors’ plasma cannon is currently 15 points, but should be 10 points
- [x] Reiver Squad is currently 4/8 PL, but should be 5/10 PL
- [x] Scout Bike Squad is currently 4/7/10 PL, but should be 4/8/12 PL
- [x] Assault Squad is currently 4/8 PL, but should be 4/9 PL
- [x] Inceptor Squad is currently 10/17 PL, but should be 10/20 PL
- [x] Land Raider Redeemer is currently 240 points, but should be 245 points

**Comment by Thairne** [comment]
Chaplain on Bike [Legends] is from the legends, and AFAIK legends to not get access to Litanies of Battle

 Lieutenants should have a master-crafted boltgun and a chainsword as default wargear options
- not possible, as in all SM catalogues like this due to implementation
