### ISSUE TITLE
Salamanders - Indomitus Primaris Lt not available

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7818]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** I do not have primaris lieutenant (indomitus) available
 I did on the previous version but it gave a validation error on update. I deleted it and went to add it back and it was not there.

I tried refreshing by deleting existing data but this did not work.

Thanks for the work you guys do

**Comment by acebaur** [comment]
What chapter?

**Comment by thymos26** [comment]
This was for the salamanders chapter, sorry for forgetting that basic detail

**Comment by amis92** [comment]
@thymos26 also if you could re-check since the data website was down and is up now, so you can update.

**Comment by thymos26** [comment]
I refreshed and checked delete existing.  I just checked uncategorized from seeing the white scars bug and found it there
