### ISSUE TITLE
Imperium - Deathwatch: Primaris Chaplain missing Litanies

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7828]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Imperium - Deathwatch v97
The Primaris Chaplain doesn't have litany selection.

**Comment by Mad-Spy** [comment]
I fixed this in #7180 (https://github.com/BSData/wh40k/commit/e085f8931a4bf7d1279c55f0dcf1b4ad1d367842), but it appears that the change got overwritten by https://github.com/BSData/wh40k/commit/42e64d6dc2a190e5e6de37a9b51b1cbd412cf32e
