### ISSUE TITLE
Space Wolves - 9th edition QA points/PL check for file v143

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#7831]
**File/Catalogue:** Imperium - Space Wolves v143

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** All errors found during initial QA pass:

* [x]  Rhino Primaris [Legends] is currently 9 PL, but should be 5 PL
* [x]  Rhino Primaris [Legends]’s “orbital array” should be named “orbital comms array”
* [x]  Rhino Primaris [Legends]’s orbital comms array is currently 18 points, but should be 20 points
* [x]  Rhino Primaris [Legends]’s twin plasma gun is currently 20 points, but should be 22 points
* [x]  Rhino Primaris [Legends] is currently 70 points, but should be 52 points
* [x]  Land Raider Excelsior [Legends] is currently 24 PL, but should be 16 PL
* [x]  Land Raider Excelsior [Legends]’s “combi-plasma” should be named “Excelsior combi-plasma”
* [x]  Land Raider Excelsior [Legends]’s Excelsior combi-plasma is currently 10 points, but should be 11 points
* [x]  Rune Priest on Bike [Legends] is currently 8 PL, but should be 7 PL
* [x]  Twin boltgun is currently 2 points, but should be 0 points on:
 
 1. Rune Priest on Bike [Legends]
 2. Wolf Priest on Bike [Legends]
 3. Wolf Guard Battle Leader on Bike [Legends]
 4. Iron Priest on Bike [Legends]
 5. Wolf Guard on Bikes [Legends]
 6. Wolf Lord on Bike [Legends]
 7. Swiftclawsa
 
* [x]  Iron Priest on Bike [Legends] is currently 6 PL, but should be 5 PL
* [x]  Thunder hammer is currently 21 points, but should be 40 points on:
 
 1. Iron Priest on Bike [Legends]
 2. Iron Priest on Thunderwolf [Legends]
 
* [x]  Iron Priest on Thunderwolf [Legends] is currently 7 PL, but should be 6 PL
* [x]  Wolf Guard on Bikes [Legends] is currently 14/28 PL, but should be 13/26 PL
* [x]  Storm shield currently costs 2 points, but should be 4 points
 
 1. Wolf Guard on Bikes [Legends]
 2. Blood Claws > Wolf Guard Pack Leader
 3. Grey Hunters > Wolf Guard Pack Leader
 4. Wolf Scouts > Wolf Guard Pack Leader
 5. Wolf Guard > Wolf Guard
 6. Skyclaws > Wolf Guard Sky Leader
 7. Swiftclaws > Wolf Guard Bike Leader
 8. Long Fangs > Wolf Guard Pack Leader
 
* [x]  Wolf Lord on Bike [Legends] is currently 7 PL, but should be 6 PL
* [x]  Wolf Lord in Phobos Armour’s master-crafted instigator bolt carbine is currently 6 points, but should be 0 points
* [x]  Primaris Battle Leaders in Phobos Armour incorrectly have an extra 4 PL in the unit
* [x]  Primaris Battle Leaders in Phobos Armour’s master-crafted occulus bolt rifle is currently 4 points, but should be 0 points
* [x]  “Intercessor Squad” should be called “Intercessors”
* [x]  “Infiltrator Squad” should be called “Infiltrators”
* [x]  Infiltrators are currently 5/10 PL, but should be 5/11 PL
* [x]  “Incursor Squad” should be called “Incursors”
* [x]  “Suppressor Squad” should be called “Suppressors”
* [x]  Suppressors are currently 4 PL, but should be 5 PL
* [x]  “Eliminator Squad” should be called “Eliminators”
* [x]  Eliminators are currently 4 PL, but should be 3 PL
* [x]  Ulrik the Slayer is currently 6 PL, but should be 7 PL
* [x]  Ulrik the Slayer should have access to litanies and be able to take two Litanies of Battle, as per Saga of the Beast FAQ datasheet
* [x]  Wolf Lord in Cataphractii Armour is currently 7 PL, but should be 8 PL
* [x]  Grey Hunters currently only go to 8 PL when 5+ Grey Hunter w/Bolt Pistol are taken, but the Grey Hunter w/Plasma Pistol and Grey Hunter with Special Weapon should also be considered too
* [x]  Reivers should have 5 models by default
* [x]  Reviers’ grav chutes are counting one too many models, resulting in their total cost being 2 points too high
* [x]  Servitors’ plasma cannon is currently 15 points, but should be 10 points
* [x]  Great Company Champion’s combat shield is currently 1 point, but should be 3 points
* [x]  Wolf Guard’s jump packs are counting one too many models, resulting in their total cost being 2 points too high
* [x]  Wolf Guard’s jump packs currently always cost 1 PL, but should cost 2 PL when there are 10 models in the unit
* [x]  “Wolf Guard in Terminator Armour” should be named “Wolf Guard Terminators”
* [x]  Dreadnought combat weapon is currently 34 points when taken with a heavy flamer, but should be 20 points on:
 
 1. Dreadnought
 2. Venerable Dreadnought
 
* [x]  Dreadnought combat weapon is currently 23 points when taken with a storm bolter, but should be 20 points on:
 
 1. Dreadnought
 2. Venerable Dreadnought
 
* [x]  Wolf Guard Cataphractii Terminators > Wolf Guard Cataphractii Pack Leader is currently 27 points, but should be 26 points
* [x]  Wolf Guard Tartaros Terminators are currently 12/25 PL, but should be 12/24 PL
* [x]  Skyclaws are currently 5/9/17 PL, but should be 5/9/13 PL
* [x]  Swiftclaws > Wolf Guard Bike Leader is currently 3 PL, but should be 2 PL
* [x]  “Inceptor Squad” should be named “Inceptors”
* [x]  Inceptors’ plasma exterminators are currently 10 points each, but should be 5 points each. In addition, the total plasma exterminators are incorrectly adding an extra 5 points to the final sum
* [x]  Wolf Scout Bikers should have 3 models by default
* [x]  Wolf Scout Bikers currently cost 5/9/13 PL, but should be 5/10/15 PL
* [x]  Wolf Scout Bikers > Wolf Scout Biker w/Grenade Launcher’s Astartes grenade launcher is currently 6 points, but should be 0 points
* [x]  Vindicator is currently 8 PL, but should be 7 PL
* [x]  Land Raider Crusader is currently 17 PL, but should be 16 PL
* [x]  Razorback no longer has access to lascannon & twin plasma gun, now that the Flowchart of Doom is gone
* [x]  Razorback no longer has access to twin heavy flamer, now that the Flowchart of Doom is gone
* [x]  Land Speeder Storm no longer has access to assault cannon, now that the Flowchart of Doom is gone
* [x]  Land Speeder Storm no longer has access to heavy flamer, now that the Flowchart of Doom is gone
* [x]  Land Speeder Storm no longer has access to multi-melta, now that the Flowchart of Doom is gone
* [x]  Land Speeder Storm should have a heavy bolter by default

**Comment by Technoblazed** [comment]
### Ignore, it's so I can tick stuff off 👍 

* [x]  Rhino Primaris [Legends] is currently 9 PL, but should be 5 PL
* [x]  Rhino Primaris [Legends]’s “orbital array” should be named “orbital comms array”
* [x]  Rhino Primaris [Legends]’s orbital comms array is currently 18 points, but should be 20 points
* [x]  Rhino Primaris [Legends]’s twin plasma gun is currently 20 points, but should be 22 points
* [x]  Rhino Primaris [Legends] is currently 70 points, but should be 52 points
* [x]  Land Raider Excelsior [Legends] is currently 24 PL, but should be 16 PL
* [ ]  Land Raider Excelsior [Legends]’s “combi-plasma” should be named “Excelsior combi-plasma”
* [x]  Land Raider Excelsior [Legends]’s Excelsior combi-plasma is currently 10 points, but should be 11 points
* [x]  Rune Priest on Bike [Legends] is currently 8 PL, but should be 7 PL
* [x]  Twin boltgun is currently 2 points, but should be 0 points on:
 
 1. Rune Priest on Bike [Legends]
 2. Wolf Priest on Bike [Legends]
 3. Wolf Guard Battle Leader on Bike [Legends]
 4. Iron Priest on Bike [Legends]
 5. Wolf Guard on Bikes [Legends]
 6. Wolf Lord on Bike [Legends]
 7. Swiftclawsa
 
* [x]  Iron Priest on Bike [Legends] is currently 6 PL, but should be 5 PL
* [x]  Thunder hammer is currently 21 points, but should be 40 points on:
 
 1. Iron Priest on Bike [Legends]
 2. Iron Priest on Thunderwolf [Legends]
 
* [x]  Iron Priest on Thunderwolf [Legends] is currently 7 PL, but should be 6 PL
* [x]  Wolf Guard on Bikes [Legends] is currently 14/28 PL, but should be 13/26 PL
* [x]  Storm shield currently costs 2 points, but should be 4 points
 
 1. Wolf Guard on Bikes [Legends]
 2. Blood Claws > Wolf Guard Pack Leader
 3. Grey Hunters > Wolf Guard Pack Leader
 4. Wolf Scouts > Wolf Guard Pack Leader
 5. Wolf Guard > Wolf Guard
 6. Skyclaws > Wolf Guard Sky Leader
 7. Swiftclaws > Wolf Guard Bike Leader
 8. Long Fangs > Wolf Guard Pack Leader
 
* [x]  Wolf Lord on Bike [Legends] is currently 7 PL, but should be 6 PL
* [x]  Wolf Lord in Phobos Armour’s master-crafted instigator bolt carbine is currently 6 points, but should be 0 points
* [x]  Primaris Battle Leaders in Phobos Armour incorrectly have an extra 4 PL in the unit
* [x]  Primaris Battle Leaders in Phobos Armour’s master-crafted occulus bolt rifle is currently 4 points, but should be 0 points
* [ ]  “Intercessor Squad” should be called “Intercessors”
* [ ]  “Infiltrator Squad” should be called “Infiltrators”
* [x]  Infiltrators are currently 5/10 PL, but should be 5/11 PL
* [ ]  “Incursor Squad” should be called “Incursors”
* [ ]  “Suppressor Squad” should be called “Suppressors”
* [x]  Suppressors are currently 4 PL, but should be 5 PL
* [ ]  “Eliminator Squad” should be called “Eliminators”
* [x]  Eliminators are currently 4 PL, but should be 3 PL
* [x]  Ulrik the Slayer is currently 6 PL, but should be 7 PL
* [x]  Ulrik the Slayer should have access to litanies and be able to take two Litanies of Battle, as per Saga of the Beast FAQ datasheet
* [x]  Wolf Lord in Cataphractii Armour is currently 7 PL, but should be 8 PL
* [x]  Grey Hunters currently only go to 8 PL when 5+ Grey Hunter w/Bolt Pistol are taken, but the Grey Hunter w/Plasma Pistol and Grey Hunter with Special Weapon should also be considered too
* [x]  Reivers should have 5 models by default
* [x]  Reviers’ grav chutes are counting one too many models, resulting in their total cost being 2 points too high
* [x]  Servitors’ plasma cannon is currently 15 points, but should be 10 points
* [x]  Great Company Champion’s combat shield is currently 1 point, but should be 3 points
* [ ]  Wolf Guard’s jump packs are counting one too many models, resulting in their total cost being 2 points too high
* [ ]  Wolf Guard’s jump packs currently always cost 1 PL, but should cost 2 PL when there are 10 models in the unit
* [ ]  “Wolf Guard in Terminator Armour” should be named “Wolf Guard Terminators”
* [x]  Dreadnought combat weapon is currently 34 points when taken with a heavy flamer, but should be 20 points on:
 
 1. Dreadnought
 2. Venerable Dreadnought
 
* [x]  Dreadnought combat weapon is currently 23 points when taken with a storm bolter, but should be 20 points on:
 
 1. Dreadnought
 2. Venerable Dreadnought
 
* [x]  Wolf Guard Cataphractii Terminators > Wolf Guard Cataphractii Pack Leader is currently 27 points, but should be 26 points
* [x]  Wolf Guard Tartaros Terminators are currently 12/25 PL, but should be 12/24 PL
* [x]  Skyclaws are currently 5/9/17 PL, but should be 5/9/13 PL
* [x]  Swiftclaws > Wolf Guard Bike Leader is currently 3 PL, but should be 2 PL
* [ ]  “Inceptor Squad” should be named “Inceptors”
* [x]  Inceptors’ plasma exterminators are currently 10 points each, but should be 5 points each. In addition, the total plasma exterminators are incorrectly adding an extra 5 points to the final sum
* [ ]  Wolf Scout Bikers should have 3 models by default
* [x]  Wolf Scout Bikers currently cost 5/9/13 PL, but should be 5/10/15 PL
* [x]  Wolf Scout Bikers > Wolf Scout Biker w/Grenade Launcher’s Astartes grenade launcher is currently 6 points, but should be 0 points
* [x]  Vindicator is currently 8 PL, but should be 7 PL
* [x]  Land Raider Crusader is currently 17 PL, but should be 16 PL
* [x]  Razorback no longer has access to lascannon & twin plasma gun, now that the Flowchart of Doom is gone
* [x]  Razorback no longer has access to twin heavy flamer, now that the Flowchart of Doom is gone
* [x]  Land Speeder Storm no longer has access to assault cannon, now that the Flowchart of Doom is gone
* [x]  Land Speeder Storm no longer has access to heavy flamer, now that the Flowchart of Doom is gone
* [x]  Land Speeder Storm no longer has access to multi-melta, now that the Flowchart of Doom is gone
* [x]  Land Speeder Storm should have a heavy bolter by default
