### ISSUE TITLE
Imperium - Deathwatch: Indomitus Lieutenant counting as HQ twice

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7849]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Primaris lieutenants (Indomitus) counts as two HQ selections, should be one selection

**Comment by Mad-Spy** [comment]
The Indomitus Lieutenant is a single model, but has been implemented as a unit of 2.
