### ISSUE TITLE
Imperium - Deathwatch: Inceptors cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7857]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Inceptors in Inceptor squad with assault Bolters are currently priced at 60 points each. Should be 40? like the sergeant

**Comment by Technoblazed** [comment]
Please ensure your data is up to date, this has already been resolved in a previous update.

![Image](https://i.tech-no.me/2020/08/06/200806220352.png)
