### ISSUE TITLE
Imperium - Adeptus Astartes - Dark Angels - Lieutnant (in Phobos Armor) Warlord traits

### ISSUE THREAD

**Issue by darkAco** [BSData/wh40k-9e#7863]
**File/Catalogue:** 
Warhammer 40,000 v9.0.11

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** 
When selecting a Lieutnants in Phobos Armor as Warlord, I get validation errors either way.
I need to select a Warlord trait, but it wants me to select one both on the model and the unit (since Lieutnants can be units of 2). But when I do that, obviously, I get another validation error for selecting too many Warlord Traits.

**Comment by Thairne** [comment]
There is no selection on the unit level, only on the model level of the selection.

**Comment by g-walsh** [comment]
@Thairne 

I can reproduce this problem for Dark Angels on both Linux and Android. Roster Editor 2.03. DA Revision v158 and v160. 

It is a problem for both Lieutenant and Lieutenant in Phobos but **not** for Primaris Lieutenant.

I also tried with Ultramarines but that works fine.

**To reproduce** - Create new DA roster, add lieutenant (or lieutenant phobos), select model and tick warlord box. Now both the model and the unit get options for warlord traits and the roster can't validate.

Thanks for all the quick work on 9th ed!
