### ISSUE TITLE
T'au Empire - Coldstar default weapons validation issue

### ISSUE THREAD

**Issue by Ugaritic** [BSData/wh40k-9e#7866]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** iOS

**Dropbox:** No

**Description:** 

When selecting the Tau Coldstar Commander with a HoBC and 3 Fusion blasters BS errors and says I have to select a Missile Pod.

I believe this is an out dated rule as the codex replaces “and” with “and/or”

“This model may replace its high-output burst cannon **and/or** missile pod with two items from the Ranged Weapons and/or Support Systems lists.”

This is NOT a duplicate of #2936 as Codex trumps Index.

**Comment by Technoblazed** [comment]
This was FAQ’d and changed to `and` a long time ago in the T’au FAQ.

https://www.warhammer-community.com/wp-content/uploads/2019/10/m4O8MuJc4Qw3Xn67.pdf

**Comment by amis92** [comment]
And @Ugaritic if you'd have read the first comment, it says **Codex FAQ**. Where did you find it was about Index?

So indeed, it is a duplicate of #2936
