### ISSUE TITLE
Imperium - Inquisitor Lord Hector Rex missing from all Imperium catalogues

### ISSUE THREAD

**Issue by spartanbs** [BSData/wh40k-9e#7871]
**File/Catalogue:** All Imperium

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:**  Inquisitor Lord Hector Rex appears to be missing from the 'Agents of the Inquisition' section of all Imperium catalogues. Have tested multiple Space Marine catalogues, Imperial Guard and Custodes.

**Comment by acebaur** [comment]
That's because he does not have the Agents of the Imperium keyword. So the only way to take him is with an Inquisition detachment.
