### ISSUE TITLE
Imperium - Deathwatch: Several issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7876]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** 

- [ ] Deathwatch missing special rules for combat doctrines
- [x] Hellblaster statline not showing when building an intercessor mixed unit even when selected independently

**Comment by Technoblazed** [comment]
Storm shields being 3++ for non-indomitus models is a non-issue. All rules for models in the indomitus box are for the indomitus box only, per the FAQ.

**Comment by WindstormSCR** [comment]
Combat doctrines are a rule that you should check your WD/Errata for, and cause unnecessary bloat in the output
