### ISSUE TITLE
FW- blast weapons not listed (Imperial Armour - Index: Forces of the Adeptus Astartes - Indomitus Version 1.0 errata)

### ISSUE THREAD

**Issue by hamppa** [BSData/wh40k-9e#7878]
**File:** Imperium - FW Adeptus Astartes

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** It seems that blast rules have not been applied to forge world weapons as listed in Imperial Armour - Index: Forces of the Adeptus Astartes - Indomitus Version 1.0 errata.

BLAST APPENDIX
The following weapons gain the Blast ability, as described in the
Warhammer 40,000 Core Book:
• Aiolos missile launcher
• Air defence missiles
• Castellum air defence missiles
• Castellum battle cannon
• Demolisher cannon
• Dreadhammer siege cannon
• Dreadnought inferno cannon
• Frag grenade
• Grav-flux bombard
• Grenade discharger - Frag grenade
• Heavy plasma cannon - Standard
• Heavy plasma cannon - Supercharge
• Helios launcher
• Hyperios launcher
• Magna-melta cannon
• Missile launcher - Frag missile
• Plasma destroyer
• Quad launcher - Thunderfire shells
• ROC missile launcher
• Scorpius multi-launcher
• Tempest salvo launcher
• Thunderhawk heavy cannon
• Typhoon missile launcher - Frag missile
• Vengeance launcher
• Whirlwind Castellan launcher

Link to the warhammer community errata: 
https://www.warhammer-community.com/wp-content/uploads/2019/09/cukA8B58izV43IRs.pdf

**Comment by fuckingenglish** [comment]
Can the blast keyword be bold so that people notice the addition?

**Comment by DrTobogganMD** [comment]
@fuckingenglish  no. Formatting like that is not possible. It is also not needed. It is a weapon ability listed in the normal spot next to other abilities.
