### ISSUE TITLE
40k Chaos Daemons Bloodletters

### ISSUE THREAD

**Issue by JohnHOB** [BSData/wh40k-9e#7885]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/

**Dropbox:** No

**Description:** Windows platform will not let me add more than 9 bloodletters.  Should go up to 30.

**Comment by williamcaw** [comment]
pleas update your data and or battle scribe . bloodletters go up to 29 + the blood reaper no errors recreated, ios or android

**Comment by Dunamis55** [comment]
I was unable to recreate this error and Bloodletters were able to go up to 30 models, no problem.
![image](https://user-images.githubusercontent.com/36267768/89780681-d7353b00-db09-11ea-87c2-f43e25f00c64.png)
Please ensure your data and Battlescribe are up-to-date and if you are still encountering this issue after doing so, please reopen this report with any additional details.
