### ISSUE TITLE
Space Wolves - Razorback twin assault cannon cost

### ISSUE THREAD

**Issue by imatsko** [BSData/wh40k-9e#7895]
**File/Catalogue:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.21.166

**Platform:** Linux

**Dropbox:** No

**Description:** Twin assault cannon for Space Wolves costs 30pts, not 40 as for other chapters. (CA2020 MFM)

**Comment by DrTobogganMD** [comment]
Incorrect as of today.
