### ISSUE TITLE
Canoptek scarabs

### ISSUE THREAD

**Issue by zoboso** [BSData/wh40k-9e#7903]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** while looking at the new power levels; the necron's canoptek scarabs for indomitus do not match the unit sizes available in the new power levels document

**Comment by DrTobogganMD** [comment]
You are correct. Welcome to GW's writing. The datasheet is what determines how many can be taken, not a power level.
