### ISSUE TITLE
Armiger Moirax Weapons

### ISSUE THREAD

**Issue by Morkai5** [BSData/wh40k-9e#7905]
**File/Catalogue:** Imperial Knights

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No ?

**Description:** The Moirax Siege Claw cannot be exchanged by other weapons, for some reason.

**Comment by williamcaw** [comment]
there is a button on equipment that allows you to remove it

**Comment by Morkai5** [comment]
No, it looks like this:
![moirax](https://user-images.githubusercontent.com/69481821/89823362-a5e05d80-db51-11ea-958e-9bc2224a9135.png)

**Comment by williamcaw** [comment]
its on the model it self

**Comment by Morkai5** [comment]
Ok, I found it, but it's counterintuitive and it doesn't happen in the Chaos version. Thanks a lot!
