### ISSUE TITLE
Imperium - Death Korps of Kreig: Blast Weapons Missing

### ISSUE THREAD

**Issue by GenericCola** [BSData/wh40k-9e#7910]
**File/Catalogue:** Imperium - DKoK

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** All "Blast" weapons are missing the "Blast" ability.

**Comment by DrTobogganMD** [comment]
This has been updated.
