### ISSUE TITLE
Imperium - Death Korps of Krieg: Engineers have incorrect costs

### ISSUE THREAD

**Issue by GenericCola** [BSData/wh40k-9e#7911]
**File/Catalogue:** Imperium - DKoK

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** 

1)"Combat Engineer Watchmaster" is 8 points, should be 7 points.
2)"Combat Engineer" is 8 points per model, should be 7 points per model. 
3)"Engineer with Demolition Charge" should be 12 points (7+5) but is currently 13. 
4)"Engineer with Vox" should be 12 points (is currently 13). 
5)"Engineer Weapon Team" should be 34 points with Mole Launcher (is currently 36 points) or 24 points with Heavy Flamer

Oddly enough, Engineers with special weapons are costed correctly (7 points + weapon).

**Comment by DrTobogganMD** [comment]
These have been updated already.

**Comment by GenericCola** [comment]
Maybe I didn't see the update-- I was having trouble updating my data because it fell off of the repository. I'll try again.
