### ISSUE TITLE
Imperium - Death Korps of Krieg Incorrect Power Levels

### ISSUE THREAD

**Issue by GenericCola** [BSData/wh40k-9e#7912]
**File/Catalogue:** Imperium - DKoK

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Death Korps of Krieg and FW Astra Militarum units have outdated Power Level values as of Power Level Update 2020. Almost all units have seen a reduction in power level.

**Comment by Mad-Spy** [comment]
The work on this update has not been released yet as per #7899. Please wait until it has been before raising issues.

**Comment by GenericCola** [comment]
I checked and didn't see anything related to PL when I submitted the ticket, only saw things related to points values. Oops.
