### ISSUE TITLE
Imperium: Blood Angels - Figure of Death relic

### ISSUE THREAD

**Issue by VanDutch85** [BSData/wh40k-9e#7917]
**File/Catalogue:** Blood Angels v163

**BattleScribe version:** 2.03.15

**Platform:** iOS

**Dropbox:** Yes

**Description:** The Figure of Death relic from Blood of Baal is not a selectable relic choice for the Primaris Chaplain since the new 9th edition file was created, despite him having a Crozius Arcanum.

**Comment by DrTobogganMD** [comment]
Fixed. In next release
