### ISSUE TITLE
Imperium - Adeptus Astartes - Ultramarines: Squad size/weapon selection incrementation issue

### ISSUE THREAD

**Issue by Lionanator** [BSData/wh40k-9e#7921]
**File/Catalogue:** Imperium - Adeptus Astartes - Ultramarines

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** 
Using the up/down buttons for increasing squad size or for selecting a piece of wargear e.g. plasma pistol on a Sergeant, it increments the value by more than just one. For the example of the plasma pistol on the sergeant it will increase from 0 to 2 from one click of the button. As stated earlier this happens for all of these type of increment buttons for wargear and squad sizing. 
I have tested other factions and this does not seem to be an issue elsewhere.

**Comment by Technoblazed** [comment]
Do you have any specific units that this issue is occurring on? We can't seem to replicate this on our end.

**Comment by Lionanator** [comment]
@Technoblazed 
Just played around on battlescribe again and it seems like this is just an issue with my older lists (I tend to keep old lists and just edit them as things change), creating a new roster seems to have resolved the issue.
