### ISSUE TITLE
Tyranids - Genestealer Cults Patriarch might need language tweak on Lightning Reflexes

### ISSUE THREAD

**Issue by grekker** [BSData/wh40k-9e#7922]
https://github.com/BSData/wh40k/blob/d35050a171bbafc1dcd13101080e5d179903330d/Tyranids%20-%20Genestealer%20Cults.cat#L1872

Looks like the cat file has both the Patriarch and the Purestrain Genestealers pointing at the same Lightning Reflexes entry, which states: "Models in this unit have a 5+ invulnerable save."

However, the language on the Patriarch data sheet in the Codex (p. 80) says "A Patriarch has a 5+ invulnerable save."

This seems like splitting hairs but I don't think it is. The Patriarch can take optional Familiars, which are their own models with their own stat line. The current wording in the cat file would suggest the Familiars also gain a 5+ invulnerable save as "models in this unit" but I can't find an FAQ or any supporting evidence that the narrower language on the Patriarch data sheet was overruled or clarified.

For clarity and to avoid rules confusion can we use the language on the Patriarch data sheet instead of pointing to the Genestealer entry?

**Comment by grekker** [comment]
Man you guys are quick at fixing these. Thanks @GenWilhelm!

**Comment by GenWilhelm** [comment]
You're very welcome 🙂
