### ISSUE TITLE
Imperium - Astra Militarum: Vulture Multiple Rocket Pods are inconsistent

### ISSUE THREAD

**Issue by Citronnade** [BSData/wh40k-9e#7923]
**File/Catalogue:** Astra Militarum v281

**BattleScribe version:** 2.03.21.

**Platform:** Windows

**Dropbox:** Yes

**Description:** The Multiple Rocket Pods weapon in Imperial Armour Index: Forces of the Astra Militarum for the Vulture gunship is Heavy D6, 72".  The Multiple Rocket Pods weapon in Codex: Astra Militarum for the Valkyrie is Assault D6, 36".

Currently, the Vulture entry in Battlescribe has two different sets of MRPs.  The first option is the one is in the list for the "2 Hellstrike Missiles" entry, and that is listed as Heavy D6, 36".  The second option is the one in the list for the "Twin Multi-Laser" entry, and that is listed as Assault D6, 36".

1. Should the Vulture be using a 36" Assault profile or a 72" Heavy profile? #7155 implies that we should be using the entry in Imperial Armour.  https://github.com/BSData/wh40k/issues/7390#issuecomment-663841932 implies that we should be using the updated entry in the Codex (the CIB entry in IA: Xenos is variable shot).  Currently, both MRP entries on the vulture have their Ref. set to Codex: AM.
2. Regardless of what's decided above, a 36" Heavy profile is not correct for either the IA or Codex source.

**Comment by DrTobogganMD** [comment]
It would use the IA Profile. The change was made without updating the range to the IA Profile.
