### ISSUE TITLE
Astra Militarum/Tempestus Points costs wrong

### ISSUE THREAD

**Issue by gothmogbalrog** [BSData/wh40k-9e#7924]
**File/Catalogue:** Imperium - Astra Militarum v267

**BattleScribe version:** v2.03.25.338

**Platform:** Android

**Dropbox:** No

**Description:** 
I updated data then removed and re-added WH40k data files. 

Militarum Tempestus has wrong points costs for their Special Weapons.

Militarum Tempestus Command Squads are the wrong points cost

Taurox primes has the wrong points cost as does its options

Crusaders are improperly equipped (missing storm shield, equipped with 2 instead of 1 power sword)

Ogryn Bodyguard is the wrong points cost

**Comment by DrTobogganMD** [comment]
You have an extremely old version of the data. AM is now on version 282. Please delete your data and redownload.
