### ISSUE TITLE
Imperium- Astra Militarum Ogryns incorrect squad max

### ISSUE THREAD

**Issue by gothmogbalrog** [BSData/wh40k-9e#7925]
**File/Catalogue:** Imperium - Astra Militarum v267

**BattleScribe version:** v2.03.25.338

**Platform:** Android

**Dropbox:** No

**Description:** 

**Description:** Detailed issue description

Ogryn squad size allows you to add 9 ogryns. Ogryn bone 'ead is already included in the unit selection, making the squad 10 Ogryns. Max size is 9.

**Comment by DrTobogganMD** [comment]
Incorrect. Please re-read your codex.

**Comment by gothmogbalrog** [comment]
Incorrect. Reread it.

1 ogryn bone 'ead. 2 ogryns. May contain 3 additional for Pl+4 or 6 additional for pl+8.

1+2+6 = 9

**Comment by gothmogbalrog** [comment]
![20200812_140111](https://user-images.githubusercontent.com/30101040/90050537-50689580-dca4-11ea-945b-5b5fad4d0a5e.jpg)

**Comment by DrTobogganMD** [comment]
Yup, my fault. Thanks! Will change.
