### ISSUE TITLE
[Anon] Bug report: Dark Angels Typos

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7926]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** 1. Chaplain ability should be “recitation of focus” instead of “redication of focus”
2. All chaplain knows “Litany of hate”, incorrect to default as “stoic prosecution”.

**Comment by DrTobogganMD** [comment]
Closed via 6da186563255d5c34c521d53ac625083265d8935
