### ISSUE TITLE
Imperium - Death Korps of Krieg: Engineer Watchmaster Shotgun costed incorrectly

### ISSUE THREAD

**Issue by GenericCola** [BSData/wh40k-9e#7929]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Engineer Watchmaster's shotgun costed at 1 point rather than 0 points, resulting in incorrect cost for the model. Last time I submitted this bug I was told it was corrected, but everything ELSE in the Engineer squad was corrected-- and not this.

**Comment by williamcaw** [comment]
it is 1 point . update your data 9.0.12 current release

**Comment by GenericCola** [comment]
I updated my data before checking all of the points. For some reason my watchmaster is still 8 points total.

**Comment by Technoblazed** [comment]
This is as intended, the unit does not include wargear costs. The watchmaster is 7 points base, plus 1 more for the Krieg Combat Shotgun, totally the 8 points it's giving you.
