### ISSUE TITLE
Imperium - Death Korps of Krieg: Alpha Pattern Leman Russ Conqueror has incorrect hull weapon costs

### ISSUE THREAD

**Issue by GenericCola** [BSData/wh40k-9e#7930]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Alpha Mars Pattern Leman Russ hull weapons are still using 8th edition costs. There was an open ticket for this a while ago but the problem does not seem to have been fixed.

**Comment by williamcaw** [comment]
update your data 9.0.12 current release

**Comment by GenericCola** [comment]
Not sure why, but my data won't update past 9.0.11 :/

**Comment by Mad-Spy** [comment]
@GenericCola, the new release hasn't hit the server yet. It'll be there in a few hours. @williamcaw is getting ahead of the creaky technology.

**Comment by Technoblazed** [comment]
This was fixed in 9.0.12.
