### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Knights - Desecrator missing Taskmaster text.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7933]
**File:** Chaos - Chaos Knights.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** In the Chaos Knights faction, the datasheet for the Knight Desecrator unit is missing the ability "Taskmaster: Re-roll hit rolls of 1 for attacks made by models in friendly<QUESTOR TRAITORIS> WAR DOG units whilst they are within 6" of this model."

**Comment by Mad-Spy** [comment]
You need to choose a Faction for your Knight roster. The ability will then appear with the correct keyword.
