### ISSUE TITLE
Imperium - Adeptus Custodes: Valerian and Aleya cost issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7942]
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** i believe that Valerian and Aleya cost more then 20 points

**Comment by williamcaw** [comment]
its just a zero missing. 200

**Comment by DrTobogganMD** [comment]
Oops
