### ISSUE TITLE
Ork warboss on bike is NOT DELETED !!!

### ISSUE THREAD

**Issue by whitewolfmxc** [BSData/wh40k-9e#7949]
**File/Catalogue:** 40k 9th ed 9.012 ver

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** 

**Description:** Detailed issue description.

**Comment by whitewolfmxc** [comment]
Ork wasboss on bike was not ACTUALLY deleted by the MFM FAQ , what the FAQ is simply saying it was removed from page 52 BECUASE that part is for FORGEWORLD UNITS and ork warboss on bike is not a FW unit !!!

the index for 2018 still stands and that unit is still valid

**Comment by whitewolfmxc** [comment]
sorry i mean page 54

**Comment by DrTobogganMD** [comment]
After discussion in Discord and review of the MFM. This tag will stay on. The very beginning of the MFM states that the book contains points for all eligible matched play models. We're not removing the link in matched play because there's some wonderful discrepancies, but a label will remain.
