### ISSUE TITLE
[Anon] Bug report: T'au Empire XV-8 PL Cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7953]
**File:** T'au Empire.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Power level for XV-8’s is set to 12 and I believe they should be PL 9 per the recent update.

**Comment by Technoblazed** [comment]
Please update your data and try again, they're showing up as 9/18/27 as appropriate already.
