### ISSUE TITLE
Imperial space marine lists not loading

### ISSUE THREAD

**Issue by theguru1989** [BSData/wh40k-9e#7957]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** /iOS

**Dropbox:** No

**Description:** When trying to make a new space marine list it just gets stuck on the loading screen.

**Comment by acebaur** [comment]
Not replicating this, what chapter?

**Comment by theguru1989** [comment]
all of them only one I'v found to work is blood angels unbounded faction

**Comment by theguru1989** [comment]
problem solved, up date and it takes longer than i expected
