### ISSUE TITLE
Game size power levels incorrect 

### ISSUE THREAD

**Issue by mcargille** [BSData/wh40k-9e#7959]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** Yes

**Description:** The power level annotations when selecting game size are off. 

Current:
Combat Patrol 0-50
Incursion 51-100
Strike Force 101-200
Onslaught 201-300

Should be:
Combat Patrol 0-25
Incursion 26-50
Strike Force 51-100
Onslaught 101-150

See page 332 of the 9th core rulebook.

**Comment by DrTobogganMD** [comment]
Power levels are noted in the BRB as "TOTAL" which is reflected in the battle size entry.
