### ISSUE TITLE
Imperium - Space Wolves: Grey Hunters PL cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7960]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Power Level for 5 Grey Hunters is 11 when it should be 6

**Comment by williamcaw** [comment]
#7970 part of the same issue
