### ISSUE TITLE
Imperium - Space Wolves: Grey Hunter and Intercessor costs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7970]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Power Level for Grey Hunters is currently 11 (75 points)
Intercessors are 100 points and only 5PL - somethings not right.

**Comment by Technoblazed** [comment]
Duplicate of https://github.com/BSData/wh40k/issues/7960.
