### ISSUE TITLE
Custodes: Allarus Custodian power level

### ISSUE THREAD

**Issue by bbermanbates** [BSData/wh40k-9e#7975]
**File/Catalogue:*warhammer 40K v9.0.12

**BattleScribe version:** 2.03.15

**Platform:** iOS

**Dropbox:** 

**Description:** unit starts at -2 PL with no models so unit overall PL always 2 short of what is should be at 3PL per model.

**Comment by DrTobogganMD** [comment]
Already Fixed

**Comment by bbermanbates** [comment]
Sorry. Must have missed it in my search.
