### ISSUE TITLE
Imperium - Blood Angels Tactical Squad defaults not valid

### ISSUE THREAD

**Issue by kroy** [BSData/wh40k-9e#7977]
**File/Catalogue:** 
Imperium - Blood Angels.cat

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:**
The default size of a tactical squad isn't valid. It only includes 4 Tactical Marines and the Sergeant is missing weapons.

**Comment by williamcaw** [comment]
what root is it from ?

**Comment by kroy** [comment]
Looks like a bastard between Space Marines and its own thing. I had a PR open to fix, but I stupidly didn't open a corresponding issue: https://github.com/BSData/wh40k/pull/7944

will open a new PR

**Comment by williamcaw** [comment]
i think this is fixed in 13
so lets wait for appspot to blink

**Comment by alphalas** [comment]
@kroy please talk to us on the discord before you go making PR‘s – thank you
