### ISSUE TITLE
[Chaos daemon] Living whip/whip of agony missing 1" rule

### ISSUE THREAD

**Issue by Deceiver89** [BSData/wh40k-9e#7983]
**File/Catalogue:** Chaos - Daemons.cat

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
The rule allowing the wielder to use those weapons if there is enemy model within 1" of himself or can target enemy models within 1" of friendly models is missing

**Comment by Mad-Spy** [comment]
The data file is correct as per the Indomitus update for Engine War, which is the latest publication for that weapon.
