### ISSUE TITLE
Change Request : Please revert to old behavior with regard to Death Company Weapon selections

### ISSUE THREAD

**Issue by candidgamera** [BSData/wh40k-9e#7985]
**File/Catalogue:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 

Pertaining to https://github.com/bsdata/wh40k/issues/7123. 

I understand the thinking behind this, but I beg you to reconsider. Currently to switch between two options, I first have to make an extra, useless click back to 'none' on the radio buttons or to clear a checkbox. Battlescribe's job is to be easy to use, not to remove the need for players to pay attention to validation errors. (Though with the new BS interface, the errors are far less visible, I grant you.) Further, it is nice to be able to see, at a glance, what my loadout options are. since DC come pre-loaded with Bolt Pistol and Chainsword selected, new players (or old players used to the old Battlescribe interface) might wonder if the rules have changed, if they're looking at an out of date book, etc. It was not at all intuitive that I should have to actively modify the model (deleting a pre-selected weapons option) before seeing all my choices.

Battlescribe fails as a reference source if information is selectively and dynamically hidden. That places an obstacle between the user and the information that substantially decreases usability. The old behavior was demonstrably superior - yes, it allowed for invalid choices, but so does the new one. After all, I can check both Bolt Pistol and Chainsword, AND Thunder Hammer. The design change has not solved any problem, but has only created a new one.

**Comment by candidgamera** [comment]
It's also inconsistent with how the other models are presented in some cases - I'm looking at Scout Sergeant, and I see all available options, even with the defaults selected.

**Comment by candidgamera** [comment]
Adding a thank you for the direct discussion in Discord on the issue! Suggestion was to request a feature in Battlescribe allowing files to 'grey out' or disable options without hiding them - would allow better enforcement of valid weapons choices without concealing data.  Fingers crossed that the Battlescribe developer will consent to add that feature.

**Comment by DrTobogganMD** [comment]
Discussed further on Discord. Closing as Won'tFix for now until we can talk to the dev about a compromise option.
