### ISSUE TITLE
Imperium - Adeptus Astartes - Dark Angels - Lieutenant warlord traits validation error

### ISSUE THREAD

**Issue by g-walsh** [BSData/wh40k-9e#7987]
**File/Catalogue:** Warhammer 40,000 v9.0.13 - Dark Angels v161

**BattleScribe version:** 2.03.21

**Platform:** Windows/Android/Linux

**Dropbox:** No

Previously described in #7863

**Description:** 

Warlord traits for Dark Angels Lieutenants and Lieutenants in Phobos armour (not Primaris Lieutenants) will not validate.

**To Reproduce** 
- Add Lieutenants to your list and add a single Lieutenant model to that unit
- Make the model your Warlord and give it a Warlord Trait
- The Lieutenant unit and model now both have Warlord Trait options

Validation will always say there are too many/too few warlord traits selected whether you select it for the model/unit/both.

**Comment by Mad-Spy** [comment]
WLTs and Relics are incorrectly duplicated onto the unit level entries.
