### ISSUE TITLE
Chaos - Daemons - Incorrect Points Value for Nurgling Swarms

### ISSUE THREAD

**Issue by TomWija** [BSData/wh40k-9e#7988]
**File/Catalogue:** Chaos - Daemons v86

**BattleScribe version:** 2.03.21

**Platform:** Mac

**Dropbox:** No

**Description:** The official points value for Nurgling Swarms is 20pts each, currently they are listed in the repo at 18pts each

**Comment by Technoblazed** [comment]
Per MFM2020, the Nurglings are 18 points per model. Where are you seeing that they're 20 points?

**Comment by Mad-Spy** [comment]
Cost is correct as per MFM2020.

**Comment by TomWija** [comment]
The official Warhammer 40k App has them listed at 20pts each

**Comment by Technoblazed** [comment]
@TomWija you are using an outdated version of the app then, they are 18PT per model on there too :)
