### ISSUE TITLE
DS8 Tactical Support Turret increases PL of Strike Team by 1

### ISSUE THREAD

**Issue by fixmycode** [BSData/wh40k-9e#7993]
**File/Catalogue:** T'au Empire v67

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Excuse me if I'm out of place here, but I was under the impression that turrets could be taken without affecting the Power Rating of the unit. Was this changed somewhere?

**Comment by DrTobogganMD** [comment]
Yes. In the PL update a week or so ago.

**Comment by amis92** [comment]
https://www.warhammer-community.com/wp-content/uploads/2020/08/A643OEwxln6ZS8H4.pdf
