### ISSUE TITLE
Adepta Sororitas Canoness missing Rod of office

### ISSUE THREAD

**Issue by ThyDudeness** [BSData/wh40k-9e#7994]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows
![canoness](https://user-images.githubusercontent.com/69878014/90576366-5091f500-e1be-11ea-9c68-16fa0fbd9b4d.jpg)

**Description:** The "Rod of Office" is not in implemented in Battlescribe. The Canoness has the option to swap the initial boltpistol and the chainsword with a boltgun and a powersword. If she takes this specific combo of weapons, she automatically gains a "Rod of Office", boosting her "Lead the Righteous" aura by additional 3".
Neither is it possible to select this specific swap of weapons without being tagged as "[Legends]", nor does it provide the additional Rod of office. At this point, the Rod of Office simply is not included in battlescribe.

**Comment by DrTobogganMD** [comment]
This was changed via FAQ. https://www.warhammer-community.com/wp-content/uploads/2020/01/g5sCzOUe4NxQEILD.pdf

**Comment by ThyDudeness** [comment]
damn, u r right! thanks man! it works with power sowerd and plasma pistol!
