### ISSUE TITLE
Land Raider Variants Explodes Ability Incorrect

### ISSUE THREAD

**Issue by CubanoConGitHub** [BSData/wh40k-9e#7995]
**File/Catalogue:** Imperium - Space Marines and all other Space Marines catalogs with these datasheets

**BattleScribe version:** 2.03.

**Platform:** All

**Dropbox:** Yes

**Description:** The following datasheets have a special rule called Explodes which is incorrect:

Land Raider 
Land Raider Redeemer
Land Raider Crusader

The Space Marines Codex (2019) lists the rule as causing D6 mortal wounds upon exploding. The Indomitus FAQ has no updates for this rule for the profiles listed above. BattleScribe lists this rule as causing D3 mortal wounds. 

It’s possible this is also incorrect on other Land Raider variants but I have not checked.

**Comment by williamcaw** [comment]
adeptus custodes have the correct tag 
deathwach land raider variants are missing tag on sheet  for explosions only found in Selection Rules for stranded land raider 
gray knights have it in Selection Rules
space wolf is fine as is on all variants just needs clean up
Inquisition Land Raider Prometheus is fine

**Comment by fuckingenglish** [comment]
This is missing the tag for deathwatch

**Comment by acebaur** [comment]
It's listed as D6 in the file and the roster editor, not able to replicate

**Comment by fuckingenglish** [comment]
> It's listed as D6 in the file and the roster editor, not able to replicate

Not in the the deathwatch it's on one of them and that's the standard land raider
Sill reproducing in .16

**Comment by CubanoConGitHub** [comment]
Still reproducing in .19 in the Space Wolves catalog for at least the Land Raider Redeemer. This is true for both iPad and iPhone.
