### ISSUE TITLE
[Craftworlds] Dark reapers cost issue

### ISSUE THREAD

**Issue by Shovah42** [BSData/wh40k-9e#8]
File/Catalogue: Craftworlds v1

BattleScribe version: 2.01.02

Platform: Android

Dropbox: No

Description:

Dark Reaper Aspect warrior cost problem. When a new one is added to the unit, Its cost does not include the Reaper Launcher weapon cost. 5 points versus 36.

**Comment by ilaunchbury** [comment]
Are you adding your Craftworlds force as a child force? There's a known issue with BS which causes this problem.
See https://github.com/BattleScribe/Desktop-Alphas/issues/166

**Comment by FarseerVeraenthis** [comment]
Works fine on Android for me... as @ilaunchbury suggested, is your Aeldari force your parent or child force?

**Comment by Shovah42** [comment]
Child, I think, because Aeldari should be able to bring anything not just craftworld, created a main Ynnari detachment and added the 3 Aeldari forces into it.

**Comment by ilaunchbury** [comment]
In that case, it's almost certainly the issue referenced above.

**Comment by FarseerVeraenthis** [comment]
ha, yes, a proper Ynnari cat is coming shortly...

**Comment by Shovah42** [comment]
Yeah thanks It works if Craftworlds is the main forces, thanks for the help guys, Yeah great news on the Ynnari cat, indeed :)
