### ISSUE TITLE
Dark Angels - Deathwing Ancient and Interrogator Chaplain

### ISSUE THREAD

**Issue by wwhimpenny** [BSData/wh40k-9e#8001]
**File/Catalogue:** Imperium - Adeptus Astartes - Dark Angels v162

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** Detailed issue description.
Deathwing Ancient - Missing option for Chainfist & Stormbolter (This was an early bug that was fixed in 8th ed too).
Error: Interrogator Chaplain - Must have 1 more selection of Litany: Stoic Prosecution - This is not an option and does not come automatically

**Comment by Thairne** [comment]
No, the option is there.
![grafik](https://user-images.githubusercontent.com/8590840/90683609-1af51680-e267-11ea-9f36-956a172d0af3.png)
