### ISSUE TITLE
Issue: Kor'sarro Khan missing bolt pistol

### ISSUE THREAD

**Issue by DatNightingale** [BSData/wh40k-9e#8002]
**File/Catalogue:**  Imperium - Adeptus Astartes - White Scars

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** The profile for his bolt pistol is missing (12", Pistol 1, S: 4, AP: 0, D:1).

**Comment by Mad-Spy** [comment]
He is a named character. He can't take Relics or choose a Warlord Trait.

**Comment by DatNightingale** [comment]
> He is a named character. He can't take Relics or choose a Warlord Trait.

My bad. I'm new, first named character I've ever had. Only the bolt pistol profile missing then. Thanks!

**Comment by Mad-Spy** [comment]
@DatNightingale He can have a Warlord Trait, but it is a fixed one; he can't choose from the list. That's why he can still use Hero of the Chapter.
