### ISSUE TITLE
T'au Empire: Can take multiple Commanders in non-FSE list. 

### ISSUE THREAD

**Issue by AbonShell** [BSData/wh40k-9e#8003]
**File/Catalogue:** Tau empire

**BattleScribe version:** 2.03.25

**Platform:** Android/

**Dropbox:** No

**Description:** Validation for having multiple battlesuit commanders is not present on non-farsight enclave septs. The roster isn't throwing an error if I have multiple in a Tau Sept list.

**Comment by AbonShell** [comment]
Required game type matched

**Comment by amis92** [comment]
(Note to self): Because of the emphasis on **non-FSE**, I thought that maybe FSE validated max 2 even outside of Matched - but I checked and there's no max cap if no Matched. So all is good here as well. :)
