### ISSUE TITLE
Ork PL half updated 

### ISSUE THREAD

**Issue by Riicochet** [BSData/wh40k-9e#8006]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

Although many of the Ork units Power Levels were updated, many weren't. Warkoptas got cheaper and buggies don't cost 16 for 3 any more, are just some examples. Please help!

**Comment by Technoblazed** [comment]
## CODEX: ORKS

#### HQ
- [ ] Big Mek with Kustom Force Field: 4PL => 5PL

#### FAST ATTACK
- [ ] DeffKopta: 2PL/5PL => 2PL per model
- [x] Megatrakk Scrapjets: Adds another 1PL when there's more than 2 in the unit, needs removing.

## FORGE WORLD XENOS

#### HQ
- [x] Mek Boss Buzzgob: 6PL => 5PL
- [x] Zhadsnark da Ripper: 7PL => 5PL

#### HEAVY SUPPORT
- [x] Big Trakk: 9PL => 11PL
- [x] Grot Mega-tank: 7PL => 9PL
- Grot Tanks
  - [x] 4: 6PL => 9PL
  - [x] 5-8: 12PL => 18PL
- [x] Meka-Dread: 12PL => 14PL
- [x] Squiggoth: 12PL => 10PL

#### LORDS OF WAR
- [x] Gargantuan Squiggoth: 21PL => 23PL
- [x] Kill Tank: 15PL => 23PL
- [x] Kustom Stompa: 52PL => 58PL

#### DEDICATED TRANSPORT
- [x] 'Chinork' Warkopta: 8PL => 5PL

**Comment by Riicochet** [comment]
Direct quote from the update: 

Megatrakk Scrapjets 1-3 5 per model

But they still say 16PL when you add 3 in BS

The Chinork is also still 8PL no matter how much I update BS

**Comment by tag8833** [comment]
I'll get this fixed up tonight.  Thanks for the report.

**Comment by tag8833** [comment]
## CODEX: ORKS

#### HQ
- [ ] Big Mek with Kustom Force Field: 4PL => 5PL
There has been some debate about this.   Until such time as GW clarifies the Saga of the Beast FAQ takes precedence over the MFM or the PL Update FAQ.

#### FAST ATTACK
- [ ] DeffKopta: 2PL/5PL => 2PL per model
I could not find any problems here.  It looks right in the data file, and works right in the roster builder.
