### ISSUE TITLE
T'au: XV9 PL cost incorrect, Target lock wording

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8008]
**File:** T'au Empire.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** XV9 crisis battle suits are 5Pl, should be 4Pl. 
Wording of target lock is incomplete, should include passage about moving normally and not inflicting a penalty when firing a heavy weapon.

**Comment by amis92** [comment]
Target lock wording was updated in FAQ:
> *Pages 102 & 123 – Target Lock
> Change to read:
> ’A model with a target lock does not suffer the penalty to their
hit rolls for Advancing and firing Assault weapons. This model
can also Advance and fire Heavy or Rapid Fire weapons, but you
must subtract 1 from its hit rolls when it does so.’

https://www.warhammer-community.com/wp-content/uploads/2019/10/m4O8MuJc4Qw3Xn67.pdf

XV9 PL cost was already updated, will be in the next release.
