### ISSUE TITLE
Funky Patrol Detachment Death Korps bug.

### ISSUE THREAD

**Issue by MetalAdMech** [BSData/wh40k-9e#8011]
**File/Catalogue:** Death Korps v136

**BattleScribe version:** 2.03.25.338

**Platform:** Android

**Dropbox:** No

**Description:** 

If you start a new roster and pick DKoK Patrol Detachment. BS won't run it, and says Repository is empty. It doesn't crash the app, it just won't allow you to make a roster. I did find a way around it, choose a Battalion first, then a Patrol, delete Battalion. BS will accept as valid. But even then the bug persistent every time start off with a Patrol Detachment. 

Also this came up after I noticed the points from 9th Ed never updated. So I manually download Death Korps v136.

**Comment by DrTobogganMD** [comment]
This sounds like corrupted data. Manually delete all data and re-download the repo. App too perhaps.
