### ISSUE TITLE
Knight Valiant warlord doesn't refund super-heavy detachment cp

### ISSUE THREAD

**Issue by Dusldorf** [BSData/wh40k-9e#8013]
**File/Catalogue:** Warhammer 40,000 v9.0.12

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** My super-heavy detachment with Valiant (warlord) and two armigers should cost 0cp, but Battlescribe is charging me 3cp.

**Comment by Valorcalls** [comment]
I can't replicate this issue on up to date data. Please update your data and confirm you are still getting the issue, and if so, provide some photos to help sort the issue.

**Comment by DrTobogganMD** [comment]
Your data is out of date. Current release is 9.0.13
