### ISSUE TITLE
Aeldari - Craftworlds: Shard of Anaris cost has not been updated

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8016]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Autarch relic shard of anaris is listed as costing 4 points. It replaces a power sword so it should be 0 points.

**Comment by DrTobogganMD** [comment]
Combined into #8056
