### ISSUE TITLE
Aeldari - Ynnari: Error if non-Ynnari character is selected as Warlord

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8017]
**File:** Aeldari - Ynnari.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** All yenarri lists give a validation error if any non unique charicter is selected to be the warlord. Per rise of the phoenix, none of the named charicters are required to be the armies warlord.

**Comment by DrTobogganMD** [comment]
Combined into #8056
