### ISSUE TITLE
Imperium - Dark Angels - Master in terminator armour can't take any relics

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8018]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Master in terminator armour can't take any relics except for special issue wargear even if he is warlord

**Comment by Thairne** [comment]
![grafik](https://user-images.githubusercontent.com/8590840/91019439-47a38800-e5f1-11ea-8af2-624b239217b6.png)
