### ISSUE TITLE
IH dread and MOTA

### ISSUE THREAD

**Issue by Valorcalls** [BSData/wh40k-9e#8022]
**File/Catalogue:** IH v19

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** None of the dreads can be selected as warlord following being given the strat granting them character. Additionally, the chaplain ven dread cannot be given MOTA, even though he is eligible for the strat.

**Comment by acebaur** [comment]
Chaplain dread fixed, MOTA dreads can no longer be WL
