### ISSUE TITLE
Aeldari - Craftworlds: Dark Reaper PL calculated incorrectly

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8023]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Reaper have a PL of 14 if more than 3 models.
They should be 9PL from 4-5 models.

**Comment by DrTobogganMD** [comment]
Combined into #8056
