### ISSUE TITLE
T'au Empire - Pathfinder Support Drones cost too much PL

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8026]
**File:** T'au Empire.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** Pathfinder team is paying too much PL for support drones, PL cost in Power Rating Update 2020 differ from those in the 40k app. Given that the Text of the PRU2020 doesn't make sense, I feel it is a typo you can't have 2 MB3 Recon Drones so why is it's cost +1 per two models?
Text in the app reads:
This unit may be accompanied by up to 2 Tactical Drones (Power Rating +1) and/or an MB3 Recon Drone (Power Rating +1) equipped with a burst cannon and up to 2 Support Drones: 1 MV31 Pulse Accelerator Drone and/or 1 MV33 Grav-inhibitor drone (Power Rating +1).

**Comment by amis92** [comment]
Thank you for the report. I does look like a typo. However, since we're not recognizing the 40k app as a binding publication, we're going to wait for the FAQ here. Or rather errata in this case.

**Comment by DrTobogganMD** [comment]
Closing until FAQ or new Codex
