### ISSUE TITLE
Siege dreadnaught slot

### ISSUE THREAD

**Issue by ZiggyQubert** [BSData/wh40k-9e#8027]
**File/Catalogue:** 
Space marines (iron hands + others)

**BattleScribe version:** 2.03.25.338

**Platform:** Windows/iOS/Android/Mac/Linux
Android

**Dropbox:** Yes/No
No

**Description:** Detailed issue description.
The siege dreadnaughts is currently listed as a heavy support choice, and as per the ministorium field manual PG 42 it should now be an elite choice

**Comment by acebaur** [comment]
The MFM is not a source that can change battlefield roles. It is only for points
