### ISSUE TITLE
Tyranids: Maleceptor should be able to take Adrenal Glands

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8029]
**File:** Tyranids.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Maleceptor does not have the adrenal glands wargear option
Maleceptor should have the option to take them for 5 points

**Comment by GenWilhelm** [comment]
The option is not present in the codex, nor is it available via legends. Unless there's another source that I'm missing, there's currently no way to put adrenal glands on a Maleceptor.
