### ISSUE TITLE
T'au Empire: XV104 Riptide showing multiple profiles when equipped with an AIA

### ISSUE THREAD

**Issue by Technoblazed** [BSData/wh40k-9e#8030]
**File/Catalogue:** T'au Empire v68

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** Yes

**Description:** XV104 Riptide Battlesuit's `Ion Accelerator` profiles are not hidden when the `Amplified ion accelerator` Prototype Weapon System is added, resulting in both being displayed on the datasheets.

**Comment by amis92** [comment]
@Technoblazed isn't that the case for every single reli... erm prototype weapon? They all are implemented as additions, "replacing" the weapon but the original is kept.

I think it's how most catalogues in 40k are implemented in regard to item-replacing-relics. I think maybe Dark Angles had that done explicitly as expected by @Thairne but I'm pretty sure he wouldn't do that again had he known how hard it'll get. :D

**Comment by Mad-Spy** [comment]
@amis92 is correct; almost every catalogue does not do replacements for Relics. You will see both profiles.

**Comment by DrTobogganMD** [comment]
This is not possible until an application change happens. ETA: Unknown. Closing for now.
