### ISSUE TITLE
'PUTRESCENT RELIC's not available for Death Guard Warlord with Plague Company

### ISSUE THREAD

**Issue by EhSlashEh** [BSData/wh40k-9e#8033]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** 'PUTRESCENT RELIC's are not available for Death Guard Warlords. These are allowed with Plague Companies.

**Comment by Valorcalls** [comment]
What Version of the Death Guard data are you using? Are you following the requirements for the relics themselves a per the PA book they stem from? As I see all of those relics available to the correct subfactions and characters who meet the requirements.

**Comment by EhSlashEh** [comment]
Ah found what I was looking for. It was under 'Relics of Decay'. I was looking for 'Putrescent Relics'. Same thing I guess aha

**Comment by Valorcalls** [comment]
That's how they get treated yeah.
