### ISSUE TITLE
Dark Angels Issues

### ISSUE THREAD

**Issue by Eepid** [BSData/wh40k-9e#8043]
**File/Catalogue:** Adeptus Astartes - Dark Angels

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** A couple of potential issues with the Dark Angels Codex that I think are incorrect - Apologies if Im wrong!

1) Belial can take a TH/SS combo without being re-tagged as [Legends] (seems correct for Lightning Claws)
2) Deathwing Terminators can take both a Heavy Weapon and a Cyclone Missile Launcher - This shouldnt be possible per Codex "For every five models in the squad, one Deathwing Terminator may either take a cyclone missile launcher or replace his storm bolter with a plasma cannon or an item from the Terminator Heavy Weapons list."

**Comment by Thairne** [comment]
you can choose the second bullet point twice for the same model.

**Comment by Eepid** [comment]
Thanks mate - I don't think its possible to take a bullet point twice though.

I know this was from 8th edition, but this was the same edition the codex was written so I guess still holds true in general?- https://www.warhammer-community.com/wp-content/uploads/2017/07/Warhammer_40000_Stepping_into_a_New_Edition_of_Warhammer_40000.pdf

Index Books Questions
Q: Can a model take the same wargear option
more than once? For example, can a Space Marine
Terminator replace his storm bolter with a cyclone
missile launcher and another storm bolter, and then
replace its ‘new’ storm bolter with a heavy flamer?
A: No.
