### ISSUE TITLE
Drukhari Kabalit Warriors - add 5points if you copy heavy weapons

### ISSUE THREAD

**Issue by dididotwo** [BSData/wh40k-9e#8047]
**File/Catalogue:** Aeldari - Drukhari v74

**BattleScribe version:** 2.03.21

**Platform:** Windows/iOS/Android/Mac/Linux Windows

**Dropbox:** Yes

**Description:** Detailed issue description.

Kabalite Warriors add 5 Points to total, if you copy a Unit with 8 Warriors 1 Sybalit 1 Warrior with Heavy weapon

Happens by both heavy weapon options
dont happen by Only warriors or Warriors with special weapon

Disapears if List gets loaded
Only happens 1 once, if you copy 3 times the same unit only one unit have the additional 5 points

**Comment by DrTobogganMD** [comment]
Combined into #8056
