### ISSUE TITLE
Mechanicus Daedalosus missing warlord traits

### ISSUE THREAD

**Issue by crackedgear** [BSData/wh40k-9e#8053]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** The Daedalosus hq is able to select warlord traits only from those available in the codex, not any of the newer ones from Engine War.

**Comment by DrTobogganMD** [comment]
Daedalosus is a named character so cannot take EW traits.
