### ISSUE TITLE
Elysian Drop troops catalog still has the old weapon costs

### ISSUE THREAD

**Issue by Millambr** [BSData/wh40k-9e#8054]
File/Catalogue: Imperium - FW Elysians.cat 

BattleScribe version: 2.03.21

Platform: Windows

Dropbox: No

Description: While the Elysian units that did now receive new point costs in CA2020 should remain at their most recent published values, (i.e. CA2019) most of the weapons have had their points costs updated. In the latest catalogue file almost all of the weapon costs are still the old costs, with the exception of the heavy flamer and HK missile which have been updated to the new cost.

**Comment by DrTobogganMD** [comment]
EDT did not get weapon points costs updated in MFM at all. In fact according to the MFM's introduction they aren't even matched play legal anymore. Until the new FW books drop, sadly EDT stays at their last published points costs.

**Comment by lewis0460** [comment]
Couldn't the argument be made that they share the same weapon datasheets as the other imperial guard units? For example, the sky talon has two rocket pods or two hellstrike missiles. This is the same weapon on every single other imperial navy aircraft and there is no precedent currently set in the imperial navy of one option being more expensive or less than another between any of the aircraft. TO's i've spoken to who allow legends units have said just to use the most up to date weapon costs. 

In fact GW themselves released that flow chart (albeit during 8th) for examples like this, where you use the most up to date points cost from the new books and the datasheets from old books. 

Us Elysian's are already facing an existential identity crisis, all we are asking for is the weapon points to reflect the costs they WOULD be, if GW bothered to mention us in the first place. 

But that being said, I understand your reasoning for not wanting to change these. But considering pretty much everyone wont be using these at tournaments anymore, it's only those using them for narrative or casual play that would be doing as described above themselves anyway, but on old fashioned paper. 

Thanks for your efforts none the less.

**Comment by DrTobogganMD** [comment]
So we refer to that as the flowchart of fuckery. It no longer exists and is not used. Precedent for not doing this change exists in that DKoK has its own section. EDT does not so received no changes.
