### ISSUE TITLE
Sokar Stormbird

### ISSUE THREAD

**Issue by Zinkaghost** [BSData/wh40k-9e#8055]
**File/Catalogue:** Warhammer 40K 

**BattleScribe version:** 2.03.

**Platform:** Windows 10 64bit

**Dropbox:** no

**Description:** do not have access to Sokar Stormbird for Grey Knights in Battalion.

**Comment by Technoblazed** [comment]
It is a Lord of War choice, you will need to use either the Super Heavy/Super Heavy Auxiliary detachment.
