### ISSUE TITLE
EDT - Officer of the Fleet

### ISSUE THREAD

**Issue by lewis0460** [BSData/wh40k-9e#8058]
**File/Catalogue:** Elysian Drop Troops

**BattleScribe version:** 2.03.

**Platform:** Mac

**Dropbox:** No

**Description:** Officer of the Fleet in the Elysian catalogue should be 25 points as per CA MFM

**Comment by Technoblazed** [comment]
Elysians are no longer included in the MFM2020 book and therefore fall back to the last publication (CA2019).

**Comment by lewis0460** [comment]
The officer of the fleet is a codex Astra Militarum unit that _can_ be included as part of an Elysian Detachment and has points listed on page 18 of MFM2020
