### ISSUE TITLE
Blood Angels Death Company missing most options

### ISSUE THREAD

**Issue by TomTheHand** [BSData/wh40k-9e#8059]
**File/Catalogue:** Blood Angels

**BattleScribe version:** 2.03.

**Platform:** Android (/all)

**Dropbox:** No

**Description:** Blood Angels Death Company are missing most of their configuration options; the only options currently available are bolt pistol/chainsword and thunder hammer.

**Comment by Mad-Spy** [comment]
Uncheck bolt pistol and chainsword.
