### ISSUE TITLE
No Nerglings or Plaguebearers for Deathguard

### ISSUE THREAD

**Issue by deathwingelite** [BSData/wh40k-9e#8064]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Technoblazed** [comment]
You need to add a Daemon detachment, either as a separate detachment, or as a child detachment in the force creator.

**Comment by Mad-Spy** [comment]
To elaborate, this is because they do not have the DEATH GUARD keyword and so can't be taken in a Death Guard Detachment.
