### ISSUE TITLE
Update Open/Narrative play to include Crusade

### ISSUE THREAD

**Issue by mzsilak** [BSData/wh40k-9e#8068]
**File/Catalogue:** N/A (v9.0.15)
**BattleScribe version:** 2.03.21
**Platform:** Windows
**Dropbox:** Yes
**Description:** 

Old narrative elements from 8th edition exist. New 9th edition crusade elements (battle honors/scars) missing.

**Comment by acebaur** [comment]
Crusade will not be added to the catalogs due to the enormous strain they'd put on the memory of mobile devices

**Comment by mzsilak** [comment]
Fair enough. Will the old stuff be removed?

**Comment by DrTobogganMD** [comment]
No. No updates to the 8e repo are planned and the chapter approved items are in a sort of limbo. We don’t know if they’re allowed to be used or not.
