### ISSUE TITLE
Bug Report - Dark Angels Stratagem issues

### ISSUE THREAD

**Issue by Kensairabbit37** [BSData/wh40k-9e#8069]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** 
-No option for "Master of Sanctity" stratagem with Primaris Chaplain
-"relics of the rock" stratagem does not provide selection for additional relic(s)

**Comment by Valorcalls** [comment]
As per page 32 of PA F&F, DA are not currently eligible for the strat to make a Master of Sanctity.

As for Relics of the Rock, please post the version of the data you are using as I can't replicate your issue.
