### ISSUE TITLE
FW DKOK: Momento Mori is the wrong spelling

### ISSUE THREAD

**Issue by plaguedroneofblight** [BSData/wh40k-9e#8077]
**File/Catalogue:** FW Death Korps of Krieg

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** The correct spelling of Momento Mori is with an E - Memento Mori. The typo stems from GW's typo that appeared in the 8th Edition FW Index. Earlier Codexes has it right with Memento Mori.

**Comment by plaguedroneofblight** [comment]
That was quick! Why closed?

**Comment by DrTobogganMD** [comment]
The spelling is correct as of the latest publications.

**Comment by plaguedroneofblight** [comment]
True, but that's ONE publication vs:
Imperial Armour 5, 6, 7, Vraks 2nd Ed and 12.
Also, Googling the phrase its clear the expression is Memento Mori.

**Comment by DrTobogganMD** [comment]
So by that logic we should publish points values from prior publications because you believe that's correct?

The spelling is correct as of the latest publications. If you have that much of an issue with spelling, please take it up with Games Workshop.

**Comment by alphalas** [comment]
I can also cite several things where GW has intentionally misspelled the Latin just because that’s the way they want to do it. As of the index (in several places in the index I might add) it’s spelled as it is

**Comment by plaguedroneofblight** [comment]
So every time someone spells something wrong, THATS the way to spell it from here on out? We can't apply common sense? What's next, bolt ruffles and lass-gunns?

**Comment by DrTobogganMD** [comment]
Your wrong is not GW's wrong. Again if you are this hung up on the way the company has chosen to spell something. Take it up with that company. We transcribe what is printed in the latest publication.
