### ISSUE TITLE
Imperium: Adeptus Mechanicus - Heavy Phosphor Blaster ability text incorrect

### ISSUE THREAD

**Issue by Relycs** [BSData/wh40k-9e#8078]
**File/Catalogue:** 
Warhammer 40k 9th Edition
**BattleScribe version:**
v9. 0.15
**Platform:** Windows/iOS/Android/Mac/Linux
Windows/Android
**Description:** Detailed issue description.
Introduced in Engine War (with the Archaeopter Stratoraptor), the new version of the Heavy Phosphor Blaster has the wording "does not receive the benefit of cover".
In Battlescribe, the wording on the Heavy Phosphor Blaster is still the old one from the Kastellan Robots: "does not receive the benefit for their saving throws for being in cover".It's wrong on both the Kastellan Robots (Heavy Support) and the Archaeopter Stratoraptor (Flyer) 
They use the same weapon.

**Comment by Thairne** [comment]
Actually that point is covered by the rare rules text on the BRB page 360. Therefore we can imply that occurences of this specific text are expected to be found in the rules. Which solves the problem and does not require to change a datasheet that has not been FAQed or Errata'ed.
