### ISSUE TITLE
Imperium - Adepta Sororitas: Battle Sanctum not providing CP refund

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8080]
**File:** Imperium - Adepta Sororitas.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Taking the faction fortification - Battle Sanctum - is not receiving the CP refund anymore.

**Comment by DrTobogganMD** [comment]
Battlescribe has no way to validate if every detachment in your force + your warlord is the same faction as the fortification. You have to click into "Detachment CP" to check the Command Benefit box if your army qualifies.

![image](https://user-images.githubusercontent.com/16939161/92401037-83127c00-f0f2-11ea-88a7-cbf12d3fb0ee.png)
