### ISSUE TITLE
Imperium - Adepta Sororitas - Canoness

### ISSUE THREAD

**Issue by Alice-Darkmetal** [BSData/wh40k-9e#8081]
File/Catalogue: Imperium - Adepta Sororitas v120

BattleScribe version: v2.03.21.166

Platform: Windows and Android used.

Dropbox: No

Description: The Canoness isn't given the option to replace the bolt pistol with a Bolter and be able to take the Rod of Office when the Bolter and Power sword are taken.

**Comment by Valorcalls** [comment]
This was FAQed to be different, the options you take when you swap your base weapons to get the rod of office are now leaving you with a plasma pistol, power sword, and the rod of office.
