### ISSUE TITLE
Orks: Can't find Mad Doc Grotsnik

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8083]
**File:** Orks.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Mad doc grotsnik is not longer in the ork elites. Was this removed by mistake?

**Comment by Technoblazed** [comment]
What Subcultur are you using? It’s showing up correctly when Deathskullz is selected.

**Comment by EhSlashEh** [comment]
![image](https://user-images.githubusercontent.com/70245073/92337131-e0201a80-f07d-11ea-9029-deeb6dabd70d.png)
