### ISSUE TITLE
Grey Knight Units Missing Selections Subheading

### ISSUE THREAD

**Issue by cpugeek** [BSData/wh40k-9e#8084]
**File/Catalogue:** Grey Knights v153

**BattleScribe version:** 2.03.21.166

**Platform:** Windows/Android

**Dropbox:** No

**Description:** The issue is with five different entries. They are as follows: Rhino, Razorback, Stormtalon Gunship, Stormraven Gunship, and Stormhawk Interceptor. The issue at hand is that all these units are missing their selection sub heading right under the unit name. This is not occurring in other factions that have these units case in point the Ultramarine faction they have the subheading. Also of note there is a distinct difference in the UI layout between the two factions for load out selection with the Ultramarines having and box named Weapon Options enabled and the Grey Knights do not as well as different verbiage being used on the load out options.  Embedded is screen shots of both the Grey Knights Stormraven and the Ultramarines showing the missing subheading.
![Grey Knight selection issues](https://user-images.githubusercontent.com/7662757/92317346-94ae3380-efcd-11ea-9379-df488a14621e.png)
![Ultramarine Selection Issue](https://user-images.githubusercontent.com/7662757/92317347-9546ca00-efcd-11ea-843b-ac505d5d76c3.png)

**Comment by Mad-Spy** [comment]
The units are just implemented differently because they were implemented by different people. Both units display all of their equipment correctly just in a slight different way.

**Comment by DrTobogganMD** [comment]
As Mad-Spy said. The selections are present, they're simply implemented a different way.
