### ISSUE TITLE
Chaos Knights - Super-Heavy Auxiliary Detachment receives Household Bonds incorrectly

### ISSUE THREAD

**Issue by EhSlashEh** [BSData/wh40k-9e#8086]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** A model in a Chaos Knight Super-Heavy Auxiliary Detachment should not get any household abilities. This is working correctly for Imperial knights, but not Chaos Knights.

**Comment by williamcaw** [comment]
its a general choice its a left over dont worry about it
