### ISSUE TITLE
FW POTM delete in FAQ

### ISSUE THREAD

**Issue by Alex-40k** [BSData/wh40k-9e#8094]
**File/Catalogue:** Adeptus Astartes, all

**BattleScribe version:** newest

**Platform:** Android

**Dropbox:** No 

**Description:** 

Per the newest FAQ forces of the adeptus astartes the following vehicles need to have POWER OF THE MACHINE SPIRIT ability deleted:

Relic Land Raider Proteus, 
Land Raider Helios, 
Land Raider Prometheus, 
Land Raider Achilles, 
Relic Spartan Assault Tank, 
Relic Typhon Heavy Siege Tank, 
Relic Cerberus Heavy Tank Destroyer, 
Relic Fellblade Super-Heavy Tank, 
Relic Falchion Super-heavy Tank 
Destroyer, 
Relic Mastodon Super-heavy Siege Transport, 
Storm Eagle Assault Gunship, 
Storm Eagle Assault Gunship – ROC 
Pattern, 
Caestus Assault Ram, 
Thunderhawk Assault Gunship, Thunderhawk Transporter, 
Sokar Pattern Stormbird, 
Grey Knights Vortimer Pattern Land 
Raider Redeemer, 
Grey Knights Thunderhawk Assault Gunship 
Inquisition Land Raider Prometheus. 

Fire raptor had already been reported in a previous bug report.

**Comment by williamcaw** [comment]
Adeptus Custodes: Orion Assault Dropship
Adeptus Custodes: Ares Gunship
Adeptus Custodes: Coronus Grav-Carrier
Adeptus Custodes: Pallas Grav-Attack 
Adeptus Custodes: Caladius Grav-tank
the intent was to get rid of "POWER OF THE MACHINE SPIRIT" from all data sheets from official source it  has been removed from these models 
if it was sill there on a roll of a 1 to hit

**Comment by Mad-Spy** [comment]
@williamcaw, despite the fact that PotMS now does nothing, as all vehicles are able to fire Heavy weapons without penalty, the FW Custodes datasheets have not (yet) been updated to remove it.
