### ISSUE TITLE
Agents of the Imperium units get duplicated in child detachments

### ISSUE THREAD

**Issue by KalChoedan** [BSData/wh40k-9e#8101]
**File/Catalogue:** SoS v155

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** When creating a child detachment, all Agents of the Imperium units are duplicated and re-duplicated upon making changes to the roster.

Steps to reproduce:
1) Create Custodes Patrol
2) Add Sisters of Silence Patrol as child detachment
2a) In Sisters detachment, note "Agents of the Imperium" section is duplicated
2b) In both Sisters/Agents of the Imperium sections, note units are duplicated within each section
3) Add any unit to the active roster
3a) In both Sisters/Agents of the Imperium sections, note units have been duplicated additional times

![image](https://user-images.githubusercontent.com/1786901/92940789-728e3880-f447-11ea-8492-97f345b0ce0f.png)

**Comment by Mad-Spy** [comment]
This looks like some weird combination of the data config and the app performing weirdly. It's definitely something to do with child Detachments and catalogueLinks.

It also happens when using any catalogue which has Agents linked in as a child, not specifically Sisters.

**Comment by DrTobogganMD** [comment]
It's an issue with GST links. Easy fix.

**Comment by DrTobogganMD** [comment]
@KalChoedan Are you on discord?
