### ISSUE TITLE
Space wolf Chaplain Dreadnought no litanies

### ISSUE THREAD

**Issue by Shoxaju** [BSData/wh40k-9e#8104]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/Andriod

**Dropbox:** Yes

**Description:** Chaplain Dreadnought does not have access to litanies despite the latest FW FAQ adding it.

**Comment by Valorcalls** [comment]
The latest FAQ for the Chaplain dread explicitly excludes non-codex SM chapters from getting litanies (this includes SW, BA, DA, and DW, as well as successors where possible).
