### ISSUE TITLE
Imperium - Adeptus Mechanicus: Arquebus is missing the 3rd sentence of its abilities

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8106]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** For the Adeptus Mechanicus, the transuranic arquebus should be listed as doing mortal wounds on a wound roll of 6 as per page 90 of the Adeptus mechanicus codex.

Thank you

**Comment by Mad-Spy** [comment]
Looks like the 3rd sentence was mistakenly removed when the Indomitus update was done.
