### ISSUE TITLE
Adepta Sororitas: Self-Repair missing in Sororitas Rhino profile

### ISSUE THREAD

**Issue by Fistberg** [BSData/wh40k-9e#8111]
**File/Catalogue:** Imperium - Adepta Sororitas.cat

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The Self-Repair ability is missing from the Sororitas Rhino profile. It looks like it's currently under "Selection rules" and not as an ability on the profile itself au contraire to every other rhino entry I'm aware of.

**Comment by Mad-Spy** [comment]
The rule is correctly linked to the unit. Whether it is configured as a rule or as a profile a choice of the data author, so there is nothing to fix here.
