### ISSUE TITLE
FW inquisition not in Agents of Imperium list

### ISSUE THREAD

**Issue by jlarue46** [BSData/wh40k-9e#8112]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
In the salamanders files the options to take the Forge world Inquisitors isn’t available for Agents of the Imperium drop down list

**Comment by Technoblazed** [comment]
That's because they do not have the Agents of the Imperium keyword. So the only way to take him is with an Inquisition detachment.
