### ISSUE TITLE
Aeldari - Craftworlds: Unable to select Ynnari Warlord Traits

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8122]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Ynnari warlord - when you select craftworld ynnari and a ynnari warlord, you cannot select a warlord trait.

**Comment by Mad-Spy** [comment]
~~Please ensure your data is up to date. This is working correctly in the current release (v103 of the Craftworlds file).~~

This will be fixed in the next release. I thought the changes had already been done.
