### ISSUE TITLE
T'au Empire: XV95 with flamers does not allow use of High-powered Incinerator

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8125]
**File:** T'au Empire.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Bug found in T'au Empire v69 - XV95 Ghostkeel with flamers cannot take prototype High-powered incinerator.

**Comment by Technoblazed** [comment]
If you add a Warlord to your roster, or use either of the 2 Emergency Dispensation options, the Prototype Weapon Systems will appear under the ghostkeel.

**Comment by amis92** [comment]
@Technoblazed the issue is in validation, not visibility. Even if you have Flamers selected, the H-PInc errors out as "max 0".

Wanna fix?
