### ISSUE TITLE
Ultramarine Inceptors

### ISSUE THREAD

**Issue by DudeChris33** [BSData/wh40k-9e#8168]
**File/Catalogue:** Warhammer 40k v9.0.17

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** When you select the "2x Plasma Exterminators" for a squad of 3 Inceptors, it puts a normal plasma exterminator on one unit, the supercharged plasma exterminator on another, and nothing on the sergeant.

**Comment by acebaur** [comment]
That's just how it displays on the output. They all have 2x plasma. There's no need to show the weapon profile 3 times

**Comment by DudeChris33** [comment]
I realize it may not matter as much to those who don't play on it but when I import them to Tabletop Simulator this is a pain for each to have only one of their profiles.
