### ISSUE TITLE
Lord Hector Rex is missing from the Agents of the Imperium

### ISSUE THREAD

**Issue by kingrodriguez** [BSData/wh40k-9e#8169]
**File/Catalogue:** Adeptus Mechanicus

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:**

As stated, Lord Hector Rex is missing from the Agents of the Imperium.
I honestly did not check all, but for 6 it was the case.

**Comment by alphalas** [comment]
Neither Rex nor Lok have the agents of the imperium keyword. As such, you can only take them in an inquisition detachment anymore

**Comment by DrTobogganMD** [comment]
Lord Hector Rex does not have the rule that allows that.

**Comment by Mad-Spy** [comment]
The Forgeworld Inquisitors have not been given the AGENTS OF THE IMPERIUM keyword, so they can't be taken using that rule.
