### ISSUE TITLE
Astra Militarum Supreme Command

### ISSUE THREAD

**Issue by Erik1366** [BSData/wh40k-9e#8171]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Detailed issue description.

AM Supreme Command Detachment is asking for a primarch choice & 2 warlord picks. No units in the roster to choose from.

**Comment by Mad-Spy** [comment]
That's because there _are_ no Astra Militarum units which can be in a Supreme Command Detachment. Only PRIMARCH, DAEMON PRIMARCH or SUPREME COMMANDER keyword units can be in one as per the rules for that Detachment.
