### ISSUE TITLE
Imperium - Astra Militarum: Psychic Awakening content missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8178]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Astra militarum is missing most of the psychic awakening content. No custom regiment doctrines or vehicle trait upgraded. Tempestus is also missing new doctrines as well.

**Comment by Mad-Spy** [comment]
Please give specifics. Custom Doctrines and Tempestus are definitely in the current release (AM v289).

![image](https://user-images.githubusercontent.com/29306451/93640753-05544780-f9f3-11ea-8264-2b082b03f842.png)

**Comment by Mad-Spy** [comment]
Closing due to lack of response.
