### ISSUE TITLE
Imperium - Imperial Knights: Cold Eradication missing from WLT list

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8188]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Imperial knights data file for 40k 

Cold eradication from engine wars is a warlord trait. Unable to take it on knights at the moment using the extra warlord trait for 1cp.

**Comment by Mad-Spy** [comment]
Unable to reproduce. As long as you have selected "Questor Mechanicus" from the Household Choice selector (as Cold Eradication is a Mechanicus Trait) it appears in the list of WLTs.

**Comment by Tarentus** [comment]
File: Warhammer 40,000 9th Edition v178

BattleScribe version: 2.03.21

Platform: Windows

Dropbox: No

Description: Imperial knights data file for 40k

I cant access the "Questor Mechanicus" specific warlord traits for my knights that use "Exalted Court", but i do have access to those traits when my knight is the 'real' Warlord.

**Comment by Mad-Spy** [comment]
Please raise a new issue. We're not going to reopen a 6 month old issue.
