### ISSUE TITLE
Craftworlds - Wraithseer missing <Craftworld> keyword and unable to choose warlord traits

### ISSUE THREAD

**Issue by Ithalan** [BSData/wh40k-9e#8190]
**File/Catalogue:** Aeldari - Craftworlds

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** The Wraithseer is missing the `<Craftworld>` keyword, and doesn't get any warlord trait options if selected as warlord.

**Comment by Mad-Spy** [comment]
Which keyword is missing?

**Comment by Ithalan** [comment]
Description updated, Github mistook the keyword for formatting
