### ISSUE TITLE
Drukhari - Some obsessions do not validate correctly, do not filter units correctly.

### ISSUE THREAD

**Issue by gbohnen** [BSData/wh40k-9e#8194]
**File/Catalogue:** Aeldari - Drukhari.cat

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** Selecting obsessions in a given detachment creates several false negatives, depending on the obsession. This behavior is inconsistent between saved lists created with older versions and new lists created with this release. Generally, the HQ Urien Rekarth seems to be removed from all table of contents when making a new list. All other units are otherwise available in most other cases, even with a mismatched obsession. Included are a couple examples, and I'm happy to provide more as needed.

Pictured: A detachment with Kabal of the Black Heart selected showing errors for the included Archon, Kabalite Warriors, and Razorwing Jetfighter. Additionally, both characters for other obsessions are shown in the troop list, along with Wracks and Wyches. This screenshot was loaded from a roster created with an older version of the data source.
![image](https://user-images.githubusercontent.com/5383236/93916573-fd342a80-fcc6-11ea-8708-f97972b1fdcb.png)

Pictured: A detachment with Prophets of Flesh selected showing errors for the included Urien Rekarth HQ. Additionally, several other units are available to add which were formerly filtered.  This screenshot was loaded from a roster created with an older version of the data source.
![image](https://user-images.githubusercontent.com/5383236/93916688-281e7e80-fcc7-11ea-9883-d069c6b286de.png)

Pictured: A detachment with Prophets of Flesh selected cannot add Urien Rekarth, but can add an Archon, Succubus, or Kabalite Warriors. This screenshot was loaded from a newly created roster.
![image](https://user-images.githubusercontent.com/5383236/93916907-7b90cc80-fcc7-11ea-9a93-e48ad47e2ed2.png)

**Comment by gbohnen** [comment]
Update: Seems I missed a release, sorry about that. The Urien Rekarth issue seems to be resolved with 9.0.20, but I'm still seeing issues with the Kabal of the Black Heart obsession, and with troop filtering.

**Comment by Mad-Spy** [comment]
The problem is the hide conditions on the RSEs. They are triggering on exactly 1 selection of a particular keyword. Because the Faction selectors have keywords (unnecessarily, IMO) this causes the hidden selections to reappear as soon as you add any units.

Additionally, it means that you cannot have a mixed Detachment, because selecting units makes others which _should_ be valid disappear.

The hide conditions should trigger off a selection from the Sect picklists to avoid this issue.

**Comment by FarseerVeraenthis** [comment]
I'll look into it, I just wanted to get something close to working for the first pass :smile:

**Comment by FarseerVeraenthis** [comment]
@Mad-Spy was correct (thanks for the tip!!), I'd used "Exactly 1" as opposed to "Greater Than 0" when triggering off keywords. This worked beautifully during controlled testing when I was trying to get the logic working with Ynnari, but obviously didn't work in reality!!
It should work now, and mixed detachments are now a thing too 😄 👍
