### ISSUE TITLE
Land Raider Variants Explodes Ability Incorrect: Redux

### ISSUE THREAD

**Issue by CubanoConGitHub** [BSData/wh40k-9e#8195]
File/Catalogue: Imperium - Space Wolves v149 

BattleScribe version: 2.03.15

Platform: All

Dropbox: Yes

Description: The following datasheets have a special rule called Explodes which is incorrect:

Land Raider
Land Raider Redeemer
Land Raider Crusader

The Space Marines Codex (2019) lists the rule as causing D6 mortal wounds upon exploding. The Indomitus FAQ has no updates for this rule for the profiles listed above. BattleScribe lists this rule as causing D3 mortal wounds for Space Wolves.

It’s possible this is also incorrect on other Land Raider variants but I have not checked.

Note: This issue was previously opened as #7995 and was marked unreproducible. While it is correct in one or more Space Marines catalogs (Raven Guard, etc.), it is still incorrect in Space Wolves.

**Comment by DrTobogganMD** [comment]
Closed in b43ec74
