### ISSUE TITLE
Dark Angels Phobos Warlord Traits - Still Presents "Princeps of Deceit" Instead Of "Lord of Deceit"

### ISSUE THREAD

**Issue by Wolfsburgerwithcheese** [BSData/wh40k-9e#8198]
**File/Catalogue:** Warhammer 40,000 v9.0.20, Imperium - Adeptus Astartes - Dark Angels v149

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Any Phobos HQ in a Dark Angels detachment that is designated as a Warlord presents Option 2: Princeps of Deceit, which is the old rule that has been superseded as of PA: Ritual of the Damned by Lord of Deceit, a more restrictive rule which applies to PHOBOS units instead of INFANTRY units. All other Space Marine factions appear to properly list Lord of Deceit.

**Comment by Thairne** [comment]
WIth the newest FAQ, no longer relevant.
