### ISSUE TITLE
Imperium - Blood Angels - Clarify Applicability of Defenders of Humanity Rule on Roster Output

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8199]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** The rule "DEFENDERS OF HUMANITY " IS only for TROOPS,  noti Élite or other types of units. Thank you for the awesome job.

**Comment by Valorcalls** [comment]
I'm not exactly sure what your trying to say is the issue here given the rule is a force rule, not a rule on a specific model.

**Comment by Mad-Spy** [comment]
The Force rule on the output doesn't state that it only applies to Troops, and it's not applied to individual units as a shared rule. I can see where OP is coming from on this.

**Comment by Ssergi0** [comment]
I see this in the codex :All units (excluding SERVITORS) in BLOOD ANGELS Detachments and Blood Angels successor Chapter Detachments (other than Super-heavy Auxiliary Detachments) gain the Red Thirst ability, and all  **Troops** units in such Detachments gain the Defenders of Humanity ability. In addition, if your army is Battle-forged, all units from your army with the Combat Doctrines ability gain the Savage Echoes ability, so long as every unit from your army (with the exception of those that are UNALIGNED) is a BLOOD ANGELS unit or every unit from your army is from the same Blood Angels successor Chapter. - From codex -section DETACHMENT RULES.  I understand that only the Troops gain DEFENDERS OF HUMANITY.  Sorry for my english. Thank you, bye.
