### ISSUE TITLE
Bug Report Imperium - Grey Knights

### ISSUE THREAD

**Issue by LokHar** [BSData/wh40k-9e#82]
File/Catalogue: Imperium - Grey Knights
BattleScribe version: 2.01.
Platform: Windows

Description: Terminator Squads only pay for one of the storm bolters of the non-justicar non-special weapon terminators.
![gk](https://user-images.githubusercontent.com/29492202/27242805-8210c534-52e7-11e7-967b-217cd930d007.png)

Also daemon hammers are free for terminator squads instead of the 13 points they actually cost.

**Comment by LokHar** [comment]
The Storm bolters are now calculated correctly but the daemon hammers are still free

**Comment by tekton** [comment]
I think I know what happened there; I'll get it working tonight.

**Comment by tekton** [comment]
The Daemon Hammer still costs points, but it's not auto populated btw. But yeah, I'll take care of that after work.
