### ISSUE TITLE
missing data

### ISSUE THREAD

**Issue by thorinas** [BSData/wh40k-9e#8200]
**BattleScribe version:** 2.03.

hi. im missing the beasts of nergle from the death guard list

**Comment by Technoblazed** [comment]
You need to add a daemon sub-detachment through the roster creator.

**Comment by thorinas** [comment]
thank you for the fast reply and help

**Comment by DrTobogganMD** [comment]
It's also worth noting that if you do this, you no longer have a Death Guard list. It would become a Nurgle List and lose any Death Guard benefits.

**Comment by thorinas** [comment]
Even though they are in the death guard codex?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by alphalas** [comment]
If you look at their keywords you’ll notice they have neither the heretic astartes nor the death guard keywords

**Comment by thorinas** [comment]
Oh yer, sorry iv only been playing a few weeks


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
