### ISSUE TITLE
Imperium - Grey Knights - Inconsistent Casing

### ISSUE THREAD

**Issue by chancelang** [BSData/wh40k-9e#8203]
**File/Catalogue:** Imperium - Grey Knights.cat

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

Very minor, but, _Twin Assault Cannon_ is written as _Twin **a**ssault **c**annon_ in some instances which causes duplicate entries when using summary. Also affects Twin Heavy Bolter, and potentially others. Easy way to reproduce is add a default Razorback and a Land Raider to a list.

![image](https://user-images.githubusercontent.com/31452250/94069325-5f238b80-fdbe-11ea-97ad-33b8b67f84a5.png)

**Comment by tekton** [comment]
It's due to how they're linked; going to won't fix this for now as it will get re-re-done when the codex comes out. Thanks for the report though!
