### ISSUE TITLE
Adding a drukhari dedicated transport invalidates the list

### ISSUE THREAD

**Issue by eugenehiggins** [BSData/wh40k-9e#8204]
**File/Catalogue:** Drukhari

**BattleScribe version:** 2.03.21

**Platform:** Android/Mac (haven't tried on anything else)

**Dropbox:** Yes

**Description:** Adding a dedicated transport (raider or venom) causes the HQ and troops choices to give the errors:

`HQ cannot have any selections of Archon (hidden)`
`Troops cannot have any selections of Kabalite Warriors (hidden)`

If I remove the HQ or troops from the roster then that option disappears from the list on the left as well.

The roster has been attached with the `.zip` extension because the drag and drop wouldn't accept `.rosz` 
[kabal combat patrol.rosz.zip](https://github.com/BSData/wh40k/files/5273395/kabal.combat.patrol.rosz.zip)

**Comment by Mad-Spy** [comment]
There's an ongoing rewrite of all the Eldar catalogues. It should be fixed in the next release.
