### ISSUE TITLE
Orks: Incorrect KFF profile text

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8207]
**File:** Orks.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The kff ability is now for more than just ranged attacks with the psychic awakening update

**Comment by Mad-Spy** [comment]
All KFF entries are correct as per the current version of the datasheet they appear on. There has been no update to any datasheet except the Big Mek with Kustom Forcefield.
