### ISSUE TITLE
Drukhari Obsessions hiding incorrect units

### ISSUE THREAD

**Issue by Samui-Kage** [BSData/wh40k-9e#8209]
**File/Catalogue:** Warhammer 40k v9.0.20

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** when choosing a Wych Cult or Kabal obsession, the Wych and Kabal options are being hidden.

When choosing a Covern Obsession, the Wych and Cabal units are not hidden.

This is then causing previously created forces to generate warnings as they then have Units that are incorrectly hidden

**Comment by Mad-Spy** [comment]
Fixed in release 9.0.21.

**Comment by Samui-Kage** [comment]
> Fixed in release 9.0.21.

Has that been made available?
As an update (with a file delete) was completed before posting.
