### ISSUE TITLE
Imperium - Astra Militarum: Conscript PL should be 5 since August PL Update

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8210]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 3.25.33

**Platform:** Android

**Dropbox:** No

**Description:** Conscript Powerlevel should be 5, is 3.
I have deleted and updated the files .
Problem persists.

**Comment by Mad-Spy** [comment]
Conscript Power Level is correct as per the August 2020 PL Update. https://www.warhammer-community.com/wp-content/uploads/2020/08/A643OEwxln6ZS8H4.pdf
