### ISSUE TITLE
Chaos Knights - Missing ‘Heretek Power Core’ relic

### ISSUE THREAD

**Issue by EhSlashEh** [BSData/wh40k-9e#8220]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:**No

**Description:**  HOUSE VEXTRIX‘s special relic Heretek Power Core is not available

**Comment by Mad-Spy** [comment]
Looks like some idiot wrote all the code and then forgot to link it into the right places. Fixed in Chaos Knight v50.
