### ISSUE TITLE
Archon can not be chosen as HQ for Ynnari army

### ISSUE THREAD

**Issue by svyatmikh** [BSData/wh40k-9e#8221]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
<img width="1038" alt="Screenshot 2020-09-28 at 01 06 36" src="https://user-images.githubusercontent.com/31831403/94377015-e6f2f800-0126-11eb-871b-955728da8a96.png">

When you create Ynnari army you can not add Archon&Kabalites which is wrong.

**Comment by Mad-Spy** [comment]
Fixed in the next release, Drukhari v83
