### ISSUE TITLE
Chaos - Death Guard: Extra Plaguespurt gauntlet should cost points

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8223]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** In Datafile Warhammer 40,000 9th Edition v159 Deathshroud Champion has an option to take a second Plaguespurt gauntlet. When the number of gauntlets is increased to 2, the points for the model do not change. The cost of a Plaguespurt gauntlet is listed at 8pts. Therefore the cost for a Deathshroud Champion with 2 Plaguespurt gauntlets should increase from 47pts to 55pts

**Comment by Mad-Spy** [comment]
Plaguespurt gauntlets cost 0 points as of MFM2020. You are using an old source for the point cost.
