### ISSUE TITLE
Reinforcements Issue

### ISSUE THREAD

**Issue by Rorschach2033** [BSData/wh40k-9e#8228]
**File/Catalogue:** Warhammer 40,000 v9.0.21, Imperium - Adeptus Astartes - Blood Angels

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Units in my Reinforcements detatchment (Death Company and Lematres) are still receiving their detachment bonuses (Red Thirst), even though units who are added to the battle as Reinforcements shouldn't receive any detachment bonuses.

**Comment by Mad-Spy** [comment]
In 9th, Reinforcements (those units which have a specific rule which allows them to start off table) and Strategic Reserves (when you pay to start them off table) are still part of your Battle-forged army, so all the rules _do_ apply to them.

You don't need to put them into a "Reinforcements" Detachment at all.

**Comment by DrTobogganMD** [comment]
@Mad-Spy is correct. You are using a detachment designed for Summoning for something else entirely. Blood Angels do not have any units that are eligible to be brought onto the battlefield via Reinforcement Points.
