### ISSUE TITLE
Imperium - Ultramarines: Sunwrath Pistol not unlocking on eligible models 

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8229]
**File:** Imperium - Ultramarines.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** When the Primaris Captain has the wargear option of plasma pistol and powerfist I should be able to give him the the Ultramarines Special issue wargear sunwrath pistol but the option is not appearing in the Ultramarines Special issue wargear list.

**Comment by zacan94** [comment]
I have just check other units that should have the sunwraith pistol as a special issue wargear option and found that I am unable to give it to them aswell

**Comment by Mad-Spy** [comment]
@acebaur The Condition Group should be an "and" not an "or".
