### ISSUE TITLE
Aeldari - Craftworlds: Blazing Star of Vaul does not unlock for eligible models

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8235]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Blazing Star of Vaul gone from Remnants of Glory Options. Was present in v101, but gone in v108 and v109 updates.

**Comment by Mad-Spy** [comment]
@FarseerVeraenthis, I'm also not sure why it's blocked from Wraithseers (as they can never have a weapon that qualifies). Should it be blocked from Spiritseers instead? This would also seem to apply to Kurnous' Bow.

**Comment by FarseerVeraenthis** [comment]
> @FarseerVeraenthis, I'm also not sure why it's blocked from Wraithseers (as they can never have a weapon that qualifies). Should it be blocked from Spiritseers instead? This would also seem to apply to Kurnous' Bow.

It is blocked because of the way relics work in the Craftworlds CAT. It was a good idea at the time, but I think it could be improved... the problem with changing it is that it will be a massive re-write due to the way it was initially built...
