### ISSUE TITLE
Aeldari - Craftworlds: Autarch Skyrunner Relics which replace wargear cannot be taken

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k-9e#8236]
Any Relic which replaces a wargear option on an Autarch Skyrunner cannot be taken without a validation error, as unlocking it requires the base weapon, but adding the Relic requires you to remove the base weapon.

Also, the Novalance of Saim-Hann has a point cost of 8, which should be 5 if it is replacing a Power Lance.

**Comment by FarseerVeraenthis** [comment]
> Any Relic which replaces a wargear option on an Autarch Skyrunner cannot be taken without a validation error, as unlocking it requires the base weapon, but adding the Relic requires you to remove the base weapon.
> 
> Also, the Novalance of Saim-Hann has a point cost of 8, which should be 5 if it is replacing a Power Lance.

Hahahaha! Whoops, looks like I dun goofed that up...
