### ISSUE TITLE
 removing the battle honor system from narrative

### ISSUE THREAD

**Issue by williamcaw** [BSData/wh40k-9e#8246]
**File/Catalogue:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

iOS

 No

request of striping of the battle honor system. up for grabs. that is and in narrative tab of gameplay  as of this writing is is now a defunct system and is no longer acknowledge as applicable to the game .

**Comment by DrTobogganMD** [comment]
There is no confirmation this is defunct as there has been no ruling on previous Chapter Approved books.

**Comment by williamcaw** [comment]
crusade has replaced this system

**Comment by DrTobogganMD** [comment]
Crusade has been introduced in the 9th Edition rulebook. Nowhere has it been said that Battle Honors are now defunct.
