### ISSUE TITLE
Orks - Super Heavy Detachments are not correctly recognising Titanic units for CP costs

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#8250]
**File/Catalogue:** Orks v90

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Super Heavy Detachments for Orks are not recognising the following units as Titanic, causing such detachments to cost 3 CP instead of 6 CP:

- Kill Tank
- Kustom Stompa
- Stompa

**Comment by Technoblazed** [comment]
Ork cat uses it's own titanic category instead of the one from the main gst, should probably be moved to the shared one.
