### ISSUE TITLE
Death Guard units missing references 

### ISSUE THREAD

**Issue by EhSlashEh** [BSData/wh40k-9e#8259]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Death Guard units are missing book references.

![image](https://user-images.githubusercontent.com/70245073/95103936-a3daeb00-070b-11eb-9bef-889ef988c297.png)

**Comment by EhSlashEh** [comment]
Chaos Knights are missing references as well. 
![image](https://user-images.githubusercontent.com/70245073/95104330-11871700-070c-11eb-9706-fac67b1b8295.png)

**Comment by Mad-Spy** [comment]
Book references are optional. If you want to go through and put them all in for me, please feel free. I might do them when the new book comes out.
