### ISSUE TITLE
Drukhari - Taking Wyches in a Ynnari army causes valid unit choices to vanish

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#8261]
**File/Catalogue:** Aeldari - Drukhari v83

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Taking a Ynnari HQ, then taking a Wych Cult unit removes all Kabalite units from unit selection. Affected units are:

- Archon
- Kabalite Warriors
- Kabalite Trueborn [Legends]
- Lhamean
- Medusae
- Sslyth
- Ur-Ghul
- Ravager

**Comment by FarseerVeraenthis** [comment]
They are villans. I'm sure I fixed this already, but apparently not well enough...

**Comment by FarseerVeraenthis** [comment]
the file was not seeing the Ynnari selector to unlock a mixed detachment.
Now it should do :+1:
(hopefully)
