### ISSUE TITLE
Aeldari - Craftworlds.cat

### ISSUE THREAD

**Issue by brningpyre** [BSData/wh40k-9e#8272]
**File/Catalogue: Aeldari - Craftworlds.cat** 

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:** There are several problems with the Farseer Skyrunner entry in "Aeldari - Craftworlds.cat", and Remnants of Glory. This same issue also applies to the Spiritseer.
It is impossible to take a replacing/modifying Remnant of Glory (relic) with the Farseer Skyrunner without causing an error in validation.

When taking "Kurnous' Bow" (which replaces "Shuriken Pistol") it has the error "Too many selections of Shuriken Pistol". Additionally, the Remnant of Glory "Blazing Star of Vaul" is not available to choose, even though the unit qualifies for that relic.

When I was looking through the changes, it seems that the "Blazing Star of Vaul" had its requirements changed to the incorrect, pre-errata text in revision 110 of "Aeldari - Craftworlds.cat". https://github.com/BSData/wh40k/commit/773ac4717b654d500c77bd7d3bbd308697daa616

As of the FAQ, the requirements for "The Blazing Star of Vaul" to be taken are "‘Model with a shuriken pistol or twin shuriken catapult only." for which the Farseer Skyrunner and Spiritseer qualify.

Additionally, it would be nice to be able to say which weapon the "Blazing Star of Vaul" modifies on the Farseer Skyrunner, as they have both qualifying weapons ("Shuriken Pistol" and "Twin Shuriken Catapult"), and the relic only modifies one of them.

**Comment by Mad-Spy** [comment]
Fixed in the next release.
