### ISSUE TITLE
Multiple Necrons issues

### ISSUE THREAD

**Issue by 4533josh** [BSData/wh40k-9e#8288]
**File/Catalogue:** Necrons v77.13

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** 

### Shared Selection Entries down to L and a few extras.

I apologise for being anal, but a complete list of issues I can find. The Formatting ones are largely me being harsh on discrepancies between data and codex, and I appreciate that it's easy to criticise, so thank you for your hard work <3
There are a lot of instances of semicolons where the codex uses colons, so I'm not going to list them, as it seems intentional.

### - Reference 

**[Reference] Command Protocols** 
- Vengeful Stars - Directive 2: 

> Each time a model in this unit makes a ranged attack **tha ttargets** ...

_change to:_ 

> Each time a model in this unit makes a ranged attack that targets ...

**[Reference] Fractured Personalities** 
- Add a period to the end of the description of #3 - Sentient Necrodermis.
- Transdimensional Displacement - Merely states the C'tan Shard gains the Transdimensional Displacement ability, but does not add the rule itself to the datasheet. Possible to add the rule to the Fractured Personalities reference sheet?

**[Reference] Necron Secondary Objectives**

- Secondary Objective - Ancient Machineries: 

> Shadow Operations Objective: If you selected this secondary objective, then after both sides have finished deploying, starting with your opponent, the players alternate selecting objective markers that are not within any player's deployment zone to be Ancient Machinery objective markers until 3 objective markers have been selected (if there is only 1 such objective marker, then only that objective marker is an Ancient Machinery objective marker).

> NECRONS CORE or NECRONS CANOPTEK units from your army can start to perform this action. Each unit from your army that starts to perform this action must be in range of a different Ancient Machinery objective marker. A unit cannot start this action while there are any enemy units (excluding AIRCRAFT) in range of the same objective marker. The action is completed at the end of your next Command phase, provided the unit attempting the action is still within range of that Ancient Machinery objective marker.

> Score 3 victory points each time a unit from your army completes the Awaken Ancient Machinery action. (Codex: Necrons p69)

_change to:_

> Shadow Operations Objective: If you selected this secondary objective, then after both sides have finished deploying, starting with your opponent, the players alternate selecting objective markers that are not within any player's deployment zone to be Ancient Machinery objective markers, until 3 objective markers have been selected (if there is only 1 such objective marker, then only that objective marker is an Ancient Machinery objective marker).

> NECRONS CORE or NECRONS CANOPTEK units from your army can attempt the following action:

> Awaken Ancient Machinery (Action): At the end of your Movement phase, one or more NECRONS CORE or NECRONS CANOPTEK units from your army can start to perform this action. Each unit from your army that starts to perform this action must be in range of a different Ancient Machinery objective marker. A unit cannot start this action while there are any enemy units (excluding AIRCRAFT) in range of the same objective marker. The action is completed at the end of your next Command phase, provided the unit attempting the action is still within range of that Ancient Machinery objective marker.

> Score 3 victory points each time a unit from your army completes the Awaken Ancient Machinery action. (Codex: Necrons p69)

- Secondary Objective - The Treasures of Aeons: 

> Score a number of victory points at the end of **the** turn if you control one or more of those objective markers, as shown in the table below:
_change to:_ 
> Score a number of victory points at the end of your turn if you control one or more of those objective markers, as shown in the table below:

**[Reference] Powers of the C'Tan**

Unique C'tan powers are all named "Transdimensional Thunderbolt".
- Deceiver unique power - should be "Cosmic Insanity".
- Nightbringer unique power - should be "Gaze of Death"
- Void Dragon unique power - should be "Voltaic Storm"

**[Reference] Warlord Traits (All)**
- "(Codex 2) Enduring Madness" - change name to - "(Codex 2) Eternal Madness". 
- Spelling: change text of the above to: 
> Each time this WARLORD _makes_ a melee attack, you can re-roll the wound roll.

- Spelling: (Codex 4) Thrall of the Silent King: change to:
> Add 3" to the range of this WARLORD's aura abilities (to a maximum of 9"). In addition, when this WARLORD uses its My Will Be Done, The Lord's Will or Adaptive Strategy abilities, you can select one friendly <DYNASTY> CORE unit within 12" of this WARLORD, instead of 9".

- Spelling: "(Codex 6) _Honorable_ Combatant" _change to:_ (Codex 6) Honourable Combatant

- (Novokh) Crimson Haze - _change to:_ (Novokh) Blood-fuelled Fury

### Non-[Reference] Profiles

**Anrakyr the Traveller** Unit ref - currently reads Codex: Necrons p82 _should be_ p83

 - **Mind in the Machine:** spelling. Change to:
> At the start of your Shooting phase, you can select one enemy VEHICLE model that is visible to and within 12" of this model and roll 3D6 (if the model you selected is TITANIC, roll 2D6 instead). If the result is greater than or equal to the Leadership characteristic of the selected model, you can shoot one of that model's ranged weapons as if that model was a unit from your army, using this model's Ballistic Skill characteristic instead of the target model's.

**Arkana: Fail-Safe Overcharger** - Spelling: change to:
> In your Command phase, you can select one friendly CANOPTEK unit within 9" of the bearer. Until the start of your next Command phase, add 1 to the Attacks characteristic of models in that unit. If that unit is a MONSTER or VEHICLE unit, add D3 to the Attacks characteristic of models in that unit instead of 1.

**Arkana: Quantum Orb -** Currently only available to Technomancer, should be only available to Plasmancer.

**C'tan Shard of the Deceiver -** Change S - currently 7, should be 6.

**C'tan Shard of the Void Dragon -** Change Save - currently 4+, should be 3+.

**Canoptek Control Node -** Spelling - Change to:
>The bearer has the following ability: 'Control Node (Aura): While a friendly <DYNASTY> CANOPTEK unit is within 6" of this model, each time a model in that unit makes an attack, add 1 to that attack's hit roll.'

**Canoptek Spyders -** Scarab Hive - Spelling - Change to:
>In your Command phase, one destroyed model from each friendly <DYNASTY> CANOPTEK SCARAB SWARM unit within 6" of this unit is Reanimated. Each unit can only be affected by this ability once per phase.

**Dynasty: Nephrekh** - Spelling: Change to:
> Models with this code have a 6+ invulnerable save. Each time a unit with this code Advances, it can translocate. If it does, do not make an Advance roll for it. Instead until the end of the phase, add 6" to the Move characteristic of models in that unit. If a unit translocates, until the end of the turn, models in that unit cannot shoot. Each time a unit with this code Falls Back or translocates, until the end of the phase, models in that unit can move across models and terrain as if they were not there. When the Protocol of the Sudden Storm becomes active for your army, if every unit in your army (excluding DYNASTIC AGENT and C'TAN SHARD units) has this code, you can select both of that command protocol's directives instead of just one.

**Convergence of Dominion**
- Starstele - Starstele Track 3 - Change Remaining W to 1-2+, change BS to 5+.
- Translocation Protocols - grammar, literally just a semicolon where there is currently a comma.
>While there are any STARSTELE units from y our army on the battlefield, CRYPTEK units in your army can attempt the following action: 'Activate Translocation Protocols (Action): At the end of your Movement phase, one friendly CRYPTEK unit from your army that is within 3" of any friendly STARSTELE units can start to perform this action. The action is completed at the end of your turn. Once completed, select one of those STARSTELE units and remove it from the battlefield; in the Reinforcements step of your next Movement phase, set that STARSTELE unit back up on the battlefield, anywhere that is more than 9" away from any enemy models. If the battle ends and that Starstele unit is not on the battlefield, it is destroyed.'

**Death Ray -** Change Type to Heavy 1 (currently Heavy D3).

**Eldritch Lance -** Both sub-types - Change Publication to Codex: Necrons (currently Psychic Awakening IX: Pariah). Pages are correct.

**Flayed Ones-** Terrifying Foes (Aura) - Change "LEadership" to "Leadership".

**Imotekh the Stormlord -** Lord of the Storm: Spelling - change to:
>Once per battle, in your Shooting phase, this model can call the storm. If it does, select one enemy model within 48" of and visible to it (you can only select a CHARACTER model with a Wounds characteristic of 9 or less if it is the closest enemy model to Imotekh). Roll one D6 for each other enemy unit within 6" of that model; on a 4+, that unit suffers D3 mortal wounds. Then roll one D6; on a 4+, that model suffers 3 mortal wounds.

**Scouring Eye:** _Add ref page:_ p112

**Solar Staff:** Spelling: Change ability on both profiles to read:
> Each time an attack is made with this weapon against an INFANTRY unit, if a hit is scored, then until the end of the turn that unit is blinded. Blinded units cannot fire Overwatch or Set to Defend. This Relic replaces a staff of light.

**Vassal Kingdom: Nephrekh** - Spelling: Change to:
> Models with this code have a 6+ invulnerable save. Each time a unit with this code Advances, it can translocate. If it does, do not make an Advance roll for it. Instead until the end of the phase, add 6" to the Move characteristic of models in that unit. If a unit translocates, until the end of the turn, models in that unit cannot shoot. Each time a unit with this code Falls Back or translocates, until the end of the phase, models in that unit can move across models and terrain as if they were not there. When the Protocol of the Sudden Storm becomes active for your army, if every unit in your army (excluding DYNASTIC AGENT and C'TAN SHARD units) has this code, you can select both of that command protocol's directives instead of just one.

**Comment by 4533josh** [comment]
I pressed Enter too early >.>

Editing further.

**Comment by DrTobogganMD** [comment]
All fixed
