### ISSUE TITLE
Arrow of Infinity Missing Wargear

### ISSUE THREAD

**Issue by balkyne** [BSData/wh40k-9e#8289]
**File/Catalogue:** Necrons v77.13

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** 

Arrow of Infinity is not a Wargear option for any HQ. It should be a Relic replacement for a Tachyon Arrow, but I am unable to add it to an Overlord.

**Comment by DrTobogganMD** [comment]
Fixed
