### ISSUE TITLE
Necrons: Some typos

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8290]
**File:** Necrons.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** This is for the new Necron update, which I have acquired the data through...means.

The Death Ray on the Monolith is Heavy 1, not Heavy D3, which was hilarious.

Also, the Cryptek Wargear "Prismastic Obfuscatron" is named "Prismatic Obfuscation" instead. Minor, but it's something.

**Comment by DrTobogganMD** [comment]
Fixed
