### ISSUE TITLE
Necrons - Initial QA pass v77

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#8292]
**File/Catalogue:** Necrons v77

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [x] Anrakyr the Traveller’s reference is “Codex: Necrons p82” but should be “Codex: Necrons p83”.
- [x] Lychguard’s reference is “Codex: Necrons” but should be “Codex: Necrons p94”
- [x] C’tan Shard of the Deceiver currently has S7, but should be S6
- [x] C’tan Shard of the Void Dragon currently has Sv4+, but should be Sv3+
- [x] Transcendent C’tan’s reference is “Codex: Necrons” but should be “Codex: Necrons p100”
- [x] Canoptek Scarab Swarm are currently called “Scarab Swarm” in the roster profile information, but should be now be called “Canoptek Scarab Swarm”
- [x] Lokhust Destroyers are currently called “Destroyer” in the roster profile information, but should be now be called “Lokhust Destroyer”
- [x] The Silent King’s Szarekh profile does not have a degrading Movement characteristic, but should be 8” at 9+ wounds, 6” at 5-8 wounds, and 4” at 1-4 wounds.
- [x] Starstele’s degrading Wound Track 2 is BS3+ but should be BS4+
- [x] Starstele’s degrading Wound Track 3 has Remaining W at 6+ but should be 1-2+
- [x] Starstele’s degrading Wound Track 3 is BS1-2+ but should be BS5+
- [x] Plasmancer is unable to take the Quantum Orb as a Cryptek Arkana

**Comment by DrTobogganMD** [comment]
Fixed
