### ISSUE TITLE
Imperium - Deathwatch: Eradicator melta Rifle and multi-melta profiles are incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8293]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Testing Techno's new Deathwatch update. In the Indomitor Kill Team, the Eradicator with Melta Rifle and Eradicator with Multi-melta use the old versions of those weapons, rolling two dice and discarding the lowest.

**Comment by Technoblazed** [comment]
Fixed in smlib.
