### ISSUE TITLE
Imperium - Deathwatch: Incorrect points for Veteran weapon options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8294]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Testing Techno's new Deathwatch update. In the Veterans and Proteus Kill Team units, almost half of the weapon options for Veterans, Watch Sergeants, and Black Shields have incorrect points costs. It appears as if they are using the points that Veteran Bikers use for those weapons.

**Comment by Technoblazed** [comment]
Fixed already
