### ISSUE TITLE
[Join Request] I'd like to contribute.

### ISSUE THREAD

**Issue by nb007MkII** [BSData/wh40k-9e#8298]
I'd like to help maintain the catalogs/catalogues in this repo. Specifically I'd like to commit some changes to standardize how some ancillary things are recorded, e.g. vehicle Wound Track profiles and Explosion profiles.

**Comment by DrTobogganMD** [comment]
Hello, currently we are not looking for standard maintainers on any catalogs. You can join our discord and discuss what changes you think might be appropriate and create PRs after speaking with the current maintainers. https://discord.gg/S4Ex4zm
