### ISSUE TITLE
Imperial Guard Issues

### ISSUE THREAD

**Issue by DudeChris33** [BSData/wh40k-9e#8305]
**File/Catalogue:** Imperial Guard

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** Several things: 
The Leman Russ' and Tank Commander's Sponson Weapons show as only one of the weapon because it is labeled as "Heavy Bolters" instead of "2x Heavy Bolter".
The Heavy Weapons Squad is counted as not infantry for how many points the heavy weapons cost when you duplicate them.
[Bug Report Video.zip](https://github.com/BSData/wh40k/files/5396784/Bug.Report.Video.zip)

**Comment by DudeChris33** [comment]
Bump

**Comment by Mad-Spy** [comment]
The second one is a Battlescribe bug, not a data issue. Amending anything on the duplicated unit or reopening the Roster will make BS recalculate the points.

**Comment by DudeChris33** [comment]
Ok good to know. What is the consensus on the first issue?
