### ISSUE TITLE
Primaris Apothecary - Incorrect Abilities/Weapon Range

### ISSUE THREAD

**Issue by jwheatca** [BSData/wh40k-9e#8307]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** 1) Primaris Apothecary should have COMBAT RESTORATIVES ability and newly worded Narthecium ability ... as per Space Marine Codex page 145.

2) Absolver bolt pistol is showing range of 16" ... actual range is 18" as per Space Marine Code Page 145.

**Comment by acebaur** [comment]
The update is still being worked on
