### ISSUE TITLE
Eradicator Squad - should be PL6

### ISSUE THREAD

**Issue by jwheatca** [BSData/wh40k-9e#8308]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
Space Marine Eradicator units currently show a Power Level of 5 ... the actual Power Level is 6 as per Space Marine Codex Page 175.

**Comment by Technoblazed** [comment]
The update is still being worked on and this is already fixed, please be patient and wait for a release before creating issues.
