### ISSUE TITLE
Salamander - Forged in Battle wording is incorrect.

### ISSUE THREAD

**Issue by jwheatca** [BSData/wh40k-9e#8309]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.  Salamander Forge in battle chapter tactics is obsolete and incorrect.  New wording can be found on Page 95 of Space Marines Codex.

**Comment by alphalas** [comment]
PLEASE STOP POSTING NEW SM BUGREPS.

**Comment by alphalas** [comment]
The data is still in progress. If you insist please join us on the discord

**Comment by jwheatca** [comment]
I'm sorry but I did check and these issues are not open.  I get that people are working on the release but if they close the issues before the release, how do we know?

**Comment by alphalas** [comment]
By checking the date of the last release which was over a week ago? Which also the title of said the data isn’t done yet

**Comment by jwheatca** [comment]
Issues should not be closed until the version is released ... They should be put into a pending release status rather than closed.
