### ISSUE TITLE
Indomitus units uncategorised - Ultramarines

### ISSUE THREAD

**Issue by ComradeKyle** [BSData/wh40k-9e#8311]
**File/Catalogue:** Warhammer 40,000 9th edition v164 Imperium - Adeptus Astartes Ultramarines

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Detailed issue description. Indomitus units are showing up as 'uncategorised'.

- Assault Intercessor Squad
- Bladeguard Ancient
- Bladeguard Veteran Squad
- Eradicator Squad
- Judiciar
- Outrider Squad

I have checked the Imperial fist, and blood angels, the issue is not replicated there. Pic below for what i was seeing.

![image](https://user-images.githubusercontent.com/30250829/96389988-fd034e00-11e4-11eb-8e39-a509d2db45ec.png)

**Comment by acebaur** [comment]
SM are still being worked on.

**Comment by alphalas** [comment]
The smurfs file probably isn’t done. AFAIK only files that are are IF and BA.

**Comment by alphalas** [comment]
We’ll announce when stuff is ready for QA
