### ISSUE TITLE
Orks: Big Mek with KFF PL cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8314]
**File:** Orks.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Orks HQ Big Mek W/Kustom force field is PL 4 should be PL 5 according to latest power level update 10/08/2020 https://www.warhammer-community.com/wp-content/uploads/2020/08/A643OEwxln6ZS8H4.pdf

**Comment by Mad-Spy** [comment]
The Saga of the Beast Indomitus Update 1.3 was released on 05/10/20 (after the August PL update) and states that the PL cost should be 4.

https://www.warhammer-community.com/wp-content/uploads/2020/10/Ft8Jxz17NVNxpZjR.pdf
