### ISSUE TITLE
Salamander (possibly relevant to all SM)

### ISSUE THREAD

**Issue by nocturnal40k** [BSData/wh40k-9e#8315]
**File/Catalogue:** Salamanders.cat

**BattleScribe version:** 2.03.21

**Platform:** Mac

**Dropbox:** No

**Description:** 

- Invader ATV not available as selection
- Incursor Squad not available as selection
- Firestrike Servo-turret not available as selection.
- Scouts still a troops choice.

- Heavy Intercessors Executor Bolt Rifle and Hellstorm Bolt Rifle do not have points costs.
- Astartes Grenade Launcher still costed at 2pts (should be 5pts).
- Storm Bolter not costed on Hunter (Should be 5pts).

- Eradicators Power Level not increasing with squad size.
- Bladeguard Veteran Squad PL not increasing with squad size.

- Obsidian Aquila relic still has pre-FAQ wording.

- Chapter Master WL Trait (Codex Warfare) not available for selection.

**Comment by acebaur** [comment]
Fixed
