### ISSUE TITLE
Imperial Guard Grenades

### ISSUE THREAD

**Issue by DudeChris33** [BSData/wh40k-9e#8317]
**File/Catalogue:** Warhammer 40k 9th Edition v162

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Guardsmen do not have their Frag Grenades in their profile.

**Comment by Mad-Spy** [comment]
Which specific instance of Guardsmen? The Infantry Squad do.

![image](https://user-images.githubusercontent.com/29306451/96558472-a0229900-12b3-11eb-9f0f-f8cefb6d469d.png)

**Comment by DudeChris33** [comment]
I updated Battlescribe and they appeared. Thank you
