### ISSUE TITLE
Necrons.cat needs few changes and additions 

### ISSUE THREAD

**Issue by Spaztick** [BSData/wh40k-9e#8318]
**File/Catalogue:** 
Necrons 77.tobagan
**BattleScribe version:** 9.0.23

**Platform:** Windows/iOS/Android/Mac/Linux

**Description:** Necrons found issues are:
Overlord missing relic The Arrow of Infinity, an option for replacing a tachyon arrow.
Maynarkh dynasty seems to have been squatted.
Quantum Orb is an Arkana option for the Technomancer; should be Plasmancer only.

**Comment by DrTobogganMD** [comment]
1) No it is not, you have to have the arrow selected.
2) No it is not, you choose it normally
3) Already been fixed.

**Comment by Spaztick** [comment]
Glad to see most issues are already solved. Maynarkh has been effectively squatted; they added new dynasty references in the fluffy front section but the word Maynarkh isn’t even in the codex. Should be removed from dynasty choices.

**Comment by alphalas** [comment]
It’s still technically valid (Thanks FW! /sarcasm)

**Comment by DrTobogganMD** [comment]
Correct. All Fw Indexes are valid until the new ones arrive. Maynarkh directed you to choose a custom dynasty code to follow. This would mean the standard custom dynasty process is followed for Maynarkh, which is reflected in the cat.
