### ISSUE TITLE
Imperium - Adeptus Astartes - Dark Angels: Assault Intercessors and Deathwing Command Squad "uncategorized"

### ISSUE THREAD

**Issue by bbobson7** [BSData/wh40k-9e#8321]
**File/Catalogue:** Imperium - Adeptus Astartes - Dark Angels "Master Data"

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Assault Intercessors and Deathwing Command Squad are in the Uncategorised category. Assault Intercessors doesn't show up in troops. Deathwing Command Squad does show up in No Force org slot when using Belial or a Captain in Terminator Armor. Using the "Master Data"

**Comment by FarseerVeraenthis** [comment]
Yup, I know why this has happened, I'll get it fixed 😄
