### ISSUE TITLE
Imperium - Adeptus Astartes - Dark Angels: Deathwing Terminator Points; Chief Apothecary Selections; Chapter Command

### ISSUE THREAD

**Issue by hagamemnon** [BSData/wh40k-9e#8322]
**File/Catalogue:** Imperium - Adeptus Astartes - Dark Angels "Master Data"

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** Yes

**Description:** 

- [x] Deathwing Terminator Points Costs are Off - base cost with Lightning Claws should be 33 points, showing at 43 points. Cost with Stormbolter + Powerfist should be 38 points, showing as 43 points. Also, there is an option for Thunder Hammer & Stormshield with Cyclone Missile Launcher, but it is not shown.

- [x] Chapter Command (Chief Apothecary, Master of Sanctity, etc) are using the points from page 98 of the Codex rather than the higher ones shown on Page 220 as agreed upon. - This is a GST Issue.

- [x] Ravenwing Apothecary and Deathwing Apothecary are not selectable for Chief Apothecary despite having correct keywords.

- [x] Talonmaster also doesn't have lieutenant ability of taking 2 for 1 slot.

 ("Company Heroes: If your army is Battle-forged, then for each Lieutenant unit included in a Detachment, a second Lieutenant unit can be included in that Detachment without taking up an additional Battlefield Role slot")

Using the "Master Data"

**Comment by FarseerVeraenthis** [comment]
Ohhhh... Tricksy Talonmaster...! The other bits are completely unsurprising...
