### ISSUE TITLE
DA v172 issues

### ISSUE THREAD

**Issue by cbcunningham** [BSData/wh40k-9e#8323]
**File/Catalogue:** Master Data

**BattleScribe version:** 2.03.

**Platform:** Mac

**Dropbox:** No

**Description:** 

- [x] Ravenwing Apo cannot be made into Chief Apo. 

- [x] No option of Steadfast Example WLT for any Ancient listed. 

- [x] No option for Selfless Healer for Primaris Apo, even if Chief Apo option slected. 

- [x] Talonmaster lists the old "And they shall know no fear rule." 

- [x] Making the Primaris Chap on Bike a Master of Sanctity throws an error when selecting two litanies.

**Comment by FarseerVeraenthis** [comment]
I'll get to it :+1:
