### ISSUE TITLE
Every Character but the Deathwing Ancient can take the Penitent of Remembrance

### ISSUE THREAD

**Issue by bbobson7** [BSData/wh40k-9e#8324]
**File/Catalogue:** Imperium - Adeptus Astartes - Dark Angels "Master Data"

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Penitent of Remembrance which should only be able to be taken by the Deathwing Ancient can be taken on every generic character other than the Deathwing Ancient.

**Comment by FarseerVeraenthis** [comment]
Hahahaha! Whoops...
