### ISSUE TITLE
Space Marine Chapter Master

### ISSUE THREAD

**Issue by nocturnal40k** [BSData/wh40k-9e#8325]
**File/Catalogue: Space Marines.cat

**BattleScribe version:** 2.03.

**Platform:** Mac

**Dropbox:** No

**Description:** 

Master of the codex available to all characters as a WL trait.

Chapter Master re-roll ability not showing.

MC Boltgun costing 5pts. Should be free (included in 85pts).

**Comment by acebaur** [comment]
Not replicating the CM re-roll ability showing, It works for me.

**Comment by nocturnal40k** [comment]
Perhaps depends on Captain selected.

Captain (First Born) and Primaris Captain lose base Rites of Battle when being upgraded to CM.

Gravis Captain and Terminator Captain have both Rites of Battle and new re-roll, but old CM re-roll wording.

Phobos Captain, Captain on Bike and Master Crafted Heavy Bolt Rifle captain ok
