### ISSUE TITLE
Incursor Squad

### ISSUE THREAD

**Issue by nocturnal40k** [BSData/wh40k-9e#8326]
**File/Catalogue:Space Marines.cat / Salamanders.cat

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Incursor squad not available for selection under Salamanders.

**Comment by acebaur** [comment]
Please specify a chapter as they had to be relinked.

**Comment by nocturnal40k** [comment]
Sorry, Salamanders.
