### ISSUE TITLE
DA v172 Discrepancies

### ISSUE THREAD

**Issue by Talberon** [BSData/wh40k-9e#8327]
**File/Catalogue:** Imperium - Adeptus Astartes - Dark Angels (Master data)

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** 
This the stuff I could find after looking at Dark Angels v172 on `master`. Hopefully this helps!

- [x] - Grim Resolve - Has the old description about rerolling 1s to hit instead of adding 1 to the hit roll
- [x] Brilliant Strategist - No Description present.
- [x] DA Relics - Don't seem to appear. For example, the Interrogator Chaplain can't take Key of Achrabael even though he is Deathwing etc.
  - The Special Issue Wargear seems to appear fine.
- Missing HQs
  - [x] Primaris Techmarine (new)
  - [x] Primaris Captain/Master (existing)
- Missing Troops
  - [x] Incursor Squad (existing)
  - [x] Heavy Intercessor Squad (new)
- Missing Fast Attack
  - [x] Storm Speeders (new)
- Missing Heavy Support
  - [x] Gladiators (new)
- [x] Elites that should not be selectable - why not?? - Page 124 under Non-Codex Compliant Chapters prohibits Dark Angels from taking these units (all DA 1st Company is Terminators/Bladeguard) - Thanks for this, I haven't got my copy of the codex yet so I'm on the back foot somewhat!!
  - Vanguard Veterans
  - Sternguard Veterans
- In Uncategorized Category
  - [x] Eradicators (Heavy Support)
  - [x] Assault Intercessor Squad (Troops)
  - [x] Bladeguard Veteran Squad (Elites)
  - [x] Bladeguard Ancient (Elites)
    - Should be able to take Pennant of Remembrance as he is a `DEATHWING` `ANCIENT`
  - [x] Relic Terminator Squad (Elites)
- Ravenwing Talonmaster
  - [x] Cannot take the Pennant of Remembrance as he is not an Ancient
  - [x] Cannot take the Reliquary of the Repentant as he is not a Biker
- Ravenwing Black Knights
  - [x] Corvus hammers are no longer baked-in; they cost 5 points per model
- Interrogator Chaplain in Terminator Armour
  - [x] Though in the index the icon next to his sheet is the Elite one, he is an HQ in the points listing at the end of the index and he has always been an HQ before, so this is likely an error in the index slate icon and he should be an HQ.
- Interrogator Chaplains (all)
  - [x] Should be able to be selected for Master of Sanctity
- Ravenwing Champion
  - [x] Should be able to be selected for Chapter Champion
- Deathwing Champion
  - [x] Should be able to be selected for Chapter Champion
- Ravenwing Apothecary
  - [x] Should be able to be selected for Chief Apothecary
- Deathwing Apothecary
  - [x] Should be able to be selected for Chief Apothecary
- Deathwing Command Squad
  - [x] Missing the Bodyguard rule
- Hellblaster Squad
  - [x] Assault Plasma Incinerator
    - Regular (non-supercharged) profile is Assault 2 when it should be Assault 3 - GST Issue

**Comment by FarseerVeraenthis** [comment]
I'll have a look, Relic validation is still a work in progress, but use your codex and you're golden 😉
