### ISSUE TITLE
Imperial Fists/Space Marines - Missing "Command Squad" rule from company veterans

### ISSUE THREAD

**Issue by Duriel201** [BSData/wh40k-9e#8330]
**File/Catalogue:** Warhammer 40,000 9th Edition v164

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Detailed issue description.

Company Veterans have the rule "Command Squad" in the new Codex. It states "If a Detachment includes a <chapter> Captain, then one <Chapter> Company Veterans unit can be included in that Detachment without taking up a Battlefield Role slot."

This rule is missing in the current battlescribe data and neither working with a normal nor with a primaris captain (you should be able to take a 7th elite unit if at least one of them is a unit of company veterans and you have a captain in your detachment)

**Comment by alphalas** [comment]
You take a company veteran squad from the no force org section to satisfy.

**Comment by alphalas** [comment]
Because that squad “... without taking up a Battlefield Role slot." so it’s in the NFO section.
