### ISSUE TITLE
Death Guard Sorcerers

### ISSUE THREAD

**Issue by DudeChris33** [BSData/wh40k-9e#8332]
**File/Catalogue:** Warhammer 40k 9th Edition v162

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Death Guard Sorcerers and Sorcerers with Terminator Armor do not have access to the Dark Hereticus Discipline but Sorcerers on Palanquins of Nurgle do.

**Comment by Mad-Spy** [comment]
Correct. Sorcerers have access to the disciplines which are listed on their datasheets.
