### ISSUE TITLE
Space Marines - Initial QA pass for shared SM library

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#8333]
**File/Catalogue:** Imperium - Space Marines v194

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [x] Captain on Bike’s profile is named “Captain”, but should be named “Captain on Bike”
- [x] Multiple models have a BS characteristic of 3+, but should be 2+:
- Primaris Lieutenant
- Lieutenant in Reiver Armour
- Lieutenant
- Lieutenant in Phobos Armour
- [x] Multiple units have typos in their unit name – should be spelt “armour”, but is currently spelt as “armor”
- Captain in Gravis Armour
- Captain in Phobos Armour
- Captain in Terminator Armour
- Librarian in Terminator Armour
- Chaplain in Terminator Armour
- [x] Librarian in Terminator Armour’s profile is named “Librarian”, but should be named “Librarian in Terminator Armour”
- [x] Chaplain in Terminator Armour’s profile is named “Chaplain”, but should be named “Chaplain in Terminator Armour”
- [x] Multiple units are listed under Uncategorised in the unit list:
- Incursor Squad
- Ancient in Terminator Armour
- [x] Primaris Apothecary has an A characteristic of 3, but should be 4.
- [x] Bladeguard Ancient has an A characteristic of 2, but should be 4.
- [x] Veteran Intercessor Squad should have 4x Veteran Intercessors models by default, but currently has 0 by default
- [x] Veteran Intercessor Squad’s profile has models named as “Intercessor” and “Intercessor Sergeant”, but should be named “Veteran Intercessor” and “Veteran Intercessor Sergeant”
- [x] Veteran Intercessor Squad > Veteran Intercessors have an A characteristic of 2, but should be 2
- [x] Veteran Intercessor Squad > Veteran Intercessors have a Ld characteristic of 7, but should be 8
- [x] Veteran Intercessor Squad > Veteran Intercessor Sergeant has an A characteristic of 3, but should be 4
- [x] Veteran Intercessor Squad > Veteran Intercessor Sergeant has a Ld characteristic of 8, but should be 9
- [x] Company Veteran’s profile has models named as “Space Marine Veteran” and “Veteran Sergeant”, but should be named “Company Veteran” and “Company Veteran Sergeant”
- [x] Vanguard Veteran’s profile has models named as “Space Marine Veteran” and “Veteran Sergeant”, but should be named “Vanguard Veteran” and “Vanguard Veteran Sergeant”
- [x] Sternguard Veteran’s profile has models named as “Space Marine Veteran” and “Veteran Sergeant”, but should be named “Sternguard Veteran” and “Sternguard Veteran Sergeant”
- [x] Terminator Assault Squad’s profile has models named as “Terminator” and “Terminator Sergeant”, but should be named “Assault Terminator” and “Assault Terminator Sergeant”
- [x] Relic Terminator Squad’s profile has a “Relic Sergeant”, but it should be named “Relic Terminator Sergeant”
- [x] Centurion Assault Squad’s profile has models named as “Centurion” and “Centurion Sergeant”, but should be named “Assault Centurion” and “Assault Centurion Sergeant”
- [x] Multiple models have a M characteristic of 4” but should be 5”:
- Centurion Assault Squad > Assault Centurions
- Centurion Assault Squad > Assault Centurion Sergeant
- Centurion Devastator Squad > Devastator Centurions
- Centurion Devastator Squad > Devastator Centurion Sergeant
- [x] Assault Squad’s profile has models named as “Space Marine” and “Space Marine Sergeant”, but should be named “Assault Marine” and “Assault Marine Sergeant”
- [x] Outrider Squad is not available in the unit list
- [x] Bike Squad is showing up twice in the available unit list
- [x] Multiple models have a W characteristic of 2, but should be 3:
- Bike Squad > Space Marine Biker
- Bike Squad > Biker Sergeant
- [x] Land Speeder Tornado’s profile is named “Land Speeder”, but it should be named “Land Speeder Tornado”
- [x] Land Speeder Tornado has a M characteristic of 18” but should be 16”
- [x] Land Speeder Tornadoes currently have the Datalink Telemetry ability, but shouldn’t have this ability
- [x] Land Speeder Typhoon’s profile is named “Land Speeder”, but it should be named “Land Speeder Typhoon”
- [x] Land Speeder Typhoon has a M characteristic of 18” but should be 16”
- [x] Land Speeder Typhoons currently have the Datalink Telemetry ability, but shouldn’t have this ability
- [x] Centurion Devastator Squad’s profile has models named as “Centurion” and “Centurion Sergeant”, but should be named “Devastator Centurion” and “Devastator Centurion Sergeant”
- [x] Devastator Squad’s profile has models named as “Space Marine” and “Space Marine Sergeant”, but should be named “Devastator Marine” and “Devastator Marine Sergeant”
- [x] Predator Destructor’s profile is named “Predator”, but it should be named “Predator Destructor”
- [x] Multiple units’ Wound Track 3 has an A characteristic of 1, but should be D3:
- Land Raider
- Land Raider Crusader
- Land Raider Redeemer
- Repulsor
- Repulsor Executioner
- Stormraven Gunship
- [x] Land Raider Crusader’s profile is named “Land Raider”, but it should be named “Land Raider Crusader”
- [x] Land Raider Redeemer’s profile is named “Land Raider”, but it should be named “Land Raider Redeemer”
- [x] Land Speeder Storm has a T characteristic of 5, but should be 6
- [x] Stormhawk Interceptor’s Wound Track 2 has a M characteristic of 20-40”, but should be 20-45”
- [x] Stormhawk Interceptor’s Wound Track 3 has a M characteristic of 20-25”, but should be 20-30”
- [x] Stormtalon Gunship’s Wound Track 2 has a M characteristic of 20-35”, but should be 20-40”
- [x] Stormtalon Gunship’s Wound Track 3 has a M characteristic of 20”, but should be 20-30”
- [x] Stormraven Gunship’s Wound Track 2 has a M characteristic of 20-30”, but should be 20-35”
- [x] Stormraven Gunship’s Wound Track 3 has a M characteristic of 20”, but should be 20-25”
- [x] Stormraven Gunship’s Wound Track 1 has an A characteristic of 3, but should be 6
- [x] Stormraven Gunship’s Wound Track 2 has an A characteristic of D3, but should be D6
- [x] Stormraven Gunship has a S characteristic of 6, but should be 8
- [x] Hammerfall Bunker has no wound tracks for deteriorating characteristics.
- [x] Primaris Captain’s plasma pistol and power fist currently costs 15 points, but should be 10 points
- [x] Primaris Captain’s master-crafted auto bolt rifle currently costs 5 points, but should be 0 points
- [x] Captain in Phobos Armour’s master-crafted instigator bolt carbine currently costs 5 points, but should be 0 points
- [x] Captain in Gravis Armour’s master-crafted power sword currently costs 10 points, but should be 0 points
- [x] Captain in Terminator Armour’s thunder hammer currently costs 20 points, but should be 15 points
- [x] Captain in Terminator Armour’s storm shield currently costs 10 points, but should be 5 points
- [x] Combi-flamer currently costs 10 points, but should be 5 points for:
- Captain
- Lieutenant
- [x] Combi-grav currently costs 10 points, but should be 5 points for:
- Captain
- Lieutenant
- [x] Combi-melta currently costs 10 points, but should be 5 points for:
- Captain
- Lieutenant
- [x] Combi-plasma currently costs 10 points, but should be 5 points for:
- Captain
- Lieutenant
- [x] Storm bolter currently costs 5 points, but should be 0 points for:
- Captain
- Lieutenant
- [x] Lieutenant in Reiver Armour is currently 78 points, but should be 75 points
- [x] Lieutenant’s master-crafted Boltgun currently costs 5 points, but should be 0 points
- [x] Lieutenant is unable to take a pair of lightning claws for 5 points
- [x] Lieutenant’s plasma pistol currently costs 5 points, but should be 0 points
- [x] Lieutenant’s grav pistol currently costs 5 points, but should be 0 points
- [x] Chapter Command: Chief Librarian currently costs 25 points, but should be 35 points for:
- Primaris Librarian
- Librarian
- Librarian in Phobos Armour
- Librarian in Terminator Armour
- [x] Librarian in Terminator Armour is unable to take combi-grav as a combi-weapon choice
- [x] Librarian in Terminator Armour’s storm bolter is currently 0 points, but should be 5 points
- [x] Chapter Command: Master of Sanctity currently costs 25 points, but should be 35 points for:
- Primaris Chaplain
- Primaris Chaplain on Bike
- Chaplain in Terminator Armour
- Chaplain
- [x] Chapter Command: Master of the Forge currently costs 20 points, but should be 30 points for:
- Primaris Techmarine
- Techmarine
- [x] Techmarine’s lightning claw currently costs 5 points, but should be 0 points
- [x] Techmarine’s power axe currently costs 5 points, but should be 0 points
- [x] Techmarine’s power fist currently costs 10 points, but should be 5 points
- [x] Techmarine’s power maul currently costs 5 points, but should be 0 points
- [x] Techmarine’s power sword currently costs 5 points, but should be 0 points
- [x] Techmarine’s thunder hammer currently costs 20 points, but should be 15 points
- [x] Servitors’ heavy bolter currently costs 10 points, but should be 5 points
- [x] Servitors’ multi-melta currently costs 20 points, but should be 15 points
- [x] Infiltrator Squad wargear options are now like any other type of wargear and should no longer add an additional model when chosen.
- [x] Infiltrator Squad’s Infiltrator comms array is currently 4 points, but should be 5 points
- [x] Incursor Squad is currently costing 5 PL, regardless of the number of models in the unit, but should be increasing to 10 PL at 6+ models.
- [x] Company Champion’s Chapter Command: Chapter Champion is currently 15 points, but should be 25 points
- [x] Chapter Command: Chief Apothecary is currently 15 points, but should be 25 points for:
- Primaris Apothecary
- Apothecary
- [x] Chapter Command: Chapter Ancient is currently 20 points, but should be 30 points for:
- Company Ancient
- Primaris Ancient
- Ancient in Terminator Armour
- [x] Bladeguard Ancient is unable to take Chapter Command: Chapter Ancient
- [x] Ancient in Terminator Armour should have storm bolter and power fist equipped by default
- [x] Ancient in Terminator Armour’s storm bolter and power fist currently costs 10 points, but should be 0 points
- [x] Veteran Intercessor Squad currently costs 12 PL at 7+ models, but should be at 6+ models
- [x] Veteran Intercessor Squad’s Astartes grenade launcher currently costs 2 points, but should be 5 points
- [x] Company Veterans from non-Dark Angels chapters can take combat shields.
- [x] Judiciar is currently 4 PL, but should be 5 PL
- [x] Terminator Squad > Terminator w/ Heavy Weapon’s power fist is currently 10 points, but should be 0 points
- [x] Terminator Squad > Terminator w/ Heavy Weapon’s chainfist is currently 10 points, but should be 0 points
- [x] Terminator Squad > Terminator w/ Heavy Weapon’s assault cannon is currently 15 points, but should be 10 points
- [x] Terminator Squad > Terminator w/ Heavy Weapon’s heavy flamer is currently 10 points, but should be 5 points
- [x] Centurion Assault Squad > Assault Centurion Sergeant is currently 45 points, but should be 55 points
- [x] Missile launcher is currently 20 points, but should be 0 points for:
- Dreadnought
- Venerable Dreadnought
- [x] Assault Squad > Space Marine w/ Eviscerator currently costs 15 points, but should be 18 points
- [x] Bike Squad > Attack Bike’s multi-melta is currently 10 points, but should be 25 points
- [x] Grav-chutes are currently 2 points, but should be 0 points for:
- Suppressor Squad > Suppressor
- Suppressor Squad > Suppressor Sergeant
- [x] Eradicator Squad > Eradicator with MM’s multi-melta is currently 20 points, but should be 10 points
- [x] Devastator Squad currently costs 15 per model, but should be 18 points per model
- [x] Thunderfire Cannon > Techmarine Gunner’s plasma cutter is currently 15 points, but should be 0 points
- [x] Stalker’s Icarus stormcannon is currently 20 points, but should be 0 points
- [x] Storm bolter is currently 0 points, but should be 5 points for:
- Stalker
- Whirlwind
- Vindicator
- Razorback
- [x] Predator Destructor is currently 90 points, but should be 140 points
- [x] Predator Destructor is unable to take a hunter-killer missile
- [x] Predator Destructor is unable to take a storm bolter
- [x] Predator Annihilator is unable to take a hunter-killer missile
- [x] Predator Annihilator is unable to take a storm bolter
- [x] Vindicator’s siege shield is currently 0 points, but should be 10 points
- [x] Land Raider Redeemer’s twin assault cannon is currently 40 points, but should be 0 points
- [x] Rhino is currently 75 points, but should be 80 points
- [x] Rhino’s second storm bolter is currently 0 points, but should be 5 points

**Comment by Technoblazed** [comment]
- [x] `And They Shall Know No Fear` needs updating to use the correct updated rules.
- [x] `Bolter Discipline` needs updating to use the correct updated rules.
- [x] The Option to choose the Teeth of Terra Relic does not appear for a Warlord equipped with an Astartes Chainsword (Captain, Captain on Bike, Lieutenants, Techmarine) #8336

**Comment by ComradeKyle** [comment]
- [x] Ultramarines V32 (warhammer 40,000 v164) shows squads as being uncategorised. (Ancient in Terminator armour, Incursor squad, and Captain with Master-crafted Heavy Bolt Rifle

- [x] able to select multiple lieutenants through > + lieutenants, >(lieutenant type), able to choose multiple of these options without it affecting the the maximum amount of Lieutenants allowed(2).
![image](https://user-images.githubusercontent.com/30250829/96842916-402d1d80-1480-11eb-9b68-468fd10da8a9.png)

**Comment by Technoblazed** [comment]
**Deathwatch SM-Lib issues**

 * [x]  Captain is unable to take a xenophase blade
 * [x]  Multiple models are unable to take a hand flamer:
 * Captain
 * Captain on Bike
 * Lieutenant
 * Librarian
 * Chaplain
 * Company Ancient
 * Company Veterans > Company Veteran
 * Company Veterans > Company Veteran Sergeant
 * Assault Squad > Assault Marine Sergeant
 * Bike Squad > Biker Sergeant
 * [x]  Multiple models are unable to take an inferno pistol
 * Captain
 * Captain on Bike
 * Lieutenant
 * Librarian
 * Chaplain
 * Company Ancient
 * Company Veterans > Company Veteran
 * Company Veterans > Company Veteran Sergeant
 * Vanguard Veteran Squad > Vanguard Veteran
 * Vanguard Veteran Squad > Vanguard Veteran Sergeant
 * Assault Squad > Assault Marine Sergeant
 * Bike Squad > Biker Sergeant
 * [x]  Multiple models are unable to take a heavy flamer:
 * Company Veterans > Company Veteran

**Comment by mdmagnusson** [comment]
"**Predator Destructor is currently 90 points, but should be 140 points**" marked as completed but is still showing 90 points.
_Imperium - Space Marines.cat_ - line 18340

**Comment by alphalas** [comment]
- [ ] Multiple units have a typo in their name as “Armor” but should be spelt “Armour” for:
- Ancient in Terminator Armour
- Chaplain in Terminator Armour
- [x] Multiple units don’t have the WOLF GUARD keyword:
- Primaris Lieutenant
- Veteran Intercessor Squad
- [x] Multiple units don’t have the WOLF PRIEST keyword:
- Primaris Chaplain
- Primaris Chaplain on Bike
- [x] Scout Squad > Scout W/Heavy or Special Weapon is currently named as “Scout w/Heavy Weapon” in the unit’s top level, but should be “Scout W/Heavy or Special Weapon”

**Comment by alphalas** [comment]
- [x] Bike Squad with 9+ Space Marine Biker models currently costs 14 PL, but should cost 18 PL for 9-11 Space Marine Biker models and 23 PL for 12-14 Space Marine Biker models
- [x] Bike Squad is unable to take more than 7 Space Marine Biker w/Bolt Pistol, but should be able to take up to 14
- [x] Bike Squad is unable to take more than 7 Space Marine Biker w/Chainsword, but should be able to take up to 14

**Comment by Dunamis55** [comment]
Just a quick clarification about the above Bike Squad changes - they're only adjusted limits for Space Wolves, so might need a keyword check to go with them. :)

**Comment by ip5en** [comment]
Where are you getting your points values for chapter command upgrades? They seemed to be all correct to the book before they were changed according to this issue...

**Comment by Dunamis55** [comment]
Points for Chapter Command upgrades are taken from the back of the codex.

**Comment by ip5en** [comment]
Ha, they are different within the same book. Good job GW.

**Comment by DessaiImrane** [comment]
Hello,

Why are thunder hammers 15pts for HQ but are 20ps in codex and supplement ? 

Thanks

**Comment by Dunamis55** [comment]
@DessaiImrane, can you be more specific please? Which HQ units are thunder hammers incorrectly at 15 points?

**Comment by DessaiImrane** [comment]
@Dunamis55 sorry. The Wolf Lord on Thunderwolf in the Space Wolve file. 
Now his thunder hammer costs 15 pts. It should be 20 pts.

**Comment by Dunamis55** [comment]
It's already fixed in the Github data, just isn't live yet.

**Comment by ip5en** [comment]
SM errata came out. Company command points are the ones from the front of the book.
