### ISSUE TITLE
Tomblades wrong guns, tesla and gauss

### ISSUE THREAD

**Issue by cookiesoldier** [BSData/wh40k-9e#8337]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux
Android
**Dropbox:** Yes/No

**Description:** Detailed issue description.
The tombblade is listed in the app as having 2 Gauss blasters, in the codex they now have 1 twin gauss blaster.
This has an impact on the stratagem fractal targeting.
The tombblade is listed in the app as having 2 tesla carbines, in the codex they now have 1 twin  tesla carbines.

**Comment by Technoblazed** [comment]
You're either using outdated data or not the data that is on master, as they are properly equipped per the codex.
