### ISSUE TITLE
Duplicate Detachments?

### ISSUE THREAD

**Issue by DudeChris33** [BSData/wh40k-9e#8339]
**File/Catalogue:** Warhammer 40k 9th Edition v162

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Can we get a way to duplicate detachments like units or is that a request for the battlescribe designers?

**Comment by Technoblazed** [comment]
App request, create a feature request here: https://github.com/BattleScribe/Release/issues
