### ISSUE TITLE
Deathwatch - Initial QA pass

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#8341]
**File/Catalogue:** Deathwatch v105

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [ ] Chaplain on Bike [Legends] is listed under the Uncategorised category
- [ ] Inceptor Squad is listed under the Uncategorised category
- [ ] Lieutenants is listed under the Uncategorised category
- [ ] When Vanguard Veterans in a Proteus Kill Team are equipped with Jump Packs, their M characteristic remains 6”, but should be 12”
- [ ] Deathwatch can take Tactical Squads, but shouldn’t be able to
- [ ] Deathwatch can take Assault Squads, but shouldn’t be able to
- [ ] Deathwatch can take Land Speeder Storm, but shouldn’t be able to
- [ ] Captain is unable to take a xenophase blade
- [ ] Multiple models are unable to take a hand flamer:
- Captain
- Captain on Bike
- Lieutenant
- Librarian
- Chaplain
- Company Ancient
- Company Veterans > Company Veteran
- Company Veterans > Company Veteran Sergeant
- Assault Squad > Assault Marine Sergeant
- Bike Squad > Biker Sergeant
- [ ] Multiple models are unable to take an inferno pistol
- Captain
- Captain on Bike
- Lieutenant
- Librarian
- Chaplain
- Company Ancient
- Company Veterans > Company Veteran
- Company Veterans > Company Veteran Sergeant
- Vanguard Veteran Squad > Vanguard Veteran
- Vanguard Veteran Squad > Vanguard Veteran Sergeant
- Assault Squad > Assault Marine Sergeant
- Bike Squad > Biker Sergeant
- [ ] Multiple models are unable to take a heavy flamer:
- Company Veterans > Company Veteran

**Comment by Technoblazed** [comment]
* [x]  Chaplain on Bike [Legends] is listed under the Uncategorised category
 * [x]  Inceptor Squad is listed under the Uncategorised category
 * [x]  Lieutenants is listed under the Uncategorised category
 * [x]  When Vanguard Veterans in a Proteus Kill Team are equipped with Jump Packs, their M characteristic remains 6”, but should be 12”
 * [x]  Deathwatch can take Tactical Squads, but shouldn’t be able to
 * [x]  Deathwatch can take Assault Squads, but shouldn’t be able to
 * [x]  Deathwatch can take Land Speeder Storm, but shouldn’t be able to

**Comment by Technoblazed** [comment]
Completed all deathwatch cat issues, moved remaining lib issues to #8333.
