### ISSUE TITLE
Dark Angel Black Knight and Deathwing issues

### ISSUE THREAD

**Issue by dalamar666** [BSData/wh40k-9e#8346]
**File/Catalogue:** Dark Angels Master

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** The points on Black knights are now correct, however the default load-out is now without the hammers.  The Hammers should be an equipment option for 5pts on a per model basis.

The points for the Deathwing command squad armament are wrong.  All the costs are the same as Deathwing Terminators.

There are no options for Heavy weapons on DW Command Squad at 5 man strength.

DW termies, and DW Command Squad Sergeant; the Storm Bolter & Power Sword option should be 0pts,

**Comment by hagamemnon** [comment]
You can replace the sword on Deathwing Sergeants for both Terminator squads as well as Command Squads:
Deathwing Command Squad:
`• Any number of models can each have their storm bolter and power fist or power sword replaced with one of the
following: 2 lightning claws; 1 thunder hammer and 1 storm shield.`
Deathwing Terminator Squad:
`• Any number of models can each have their storm bolter and power fist or power sword replaced with: 2 lightning claws;
1 thunder hammer and 1 storm shield`

**Comment by dalamar666** [comment]
> You can replace the sword on Deathwing Sergeants for both Terminator squads as well as Command Squads:
> Deathwing Command Squad:
> `• Any number of models can each have their storm bolter and power fist or power sword replaced with one of the following: 2 lightning claws; 1 thunder hammer and 1 storm shield.`
> Deathwing Terminator Squad:
> `• Any number of models can each have their storm bolter and power fist or power sword replaced with: 2 lightning claws; 1 thunder hammer and 1 storm shield`

Thank you for the correction. I read it and read it, but my brain would not see power sword in that quote.  fixed Issue.
