### ISSUE TITLE
(Beta) Blood Angels Librarian Dreadnought has old weapon profile for Force Halberd & old points costs for Heavy Flamer and Meltagun 

### ISSUE THREAD

**Issue by ShovelNate** [BSData/wh40k-9e#8351]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by alphalas** [comment]
Please do not open a separate bug report for each problem you find if you’re going through and QAing.

**Comment by alphalas** [comment]
And don’t use the title as the bug report please
