### ISSUE TITLE
Aeldari Craftworlds - Warlord Trait 'Revered by the Dead' no showing for Wraith Host detachment HQs

### ISSUE THREAD

**Issue by Tech-Ninja** [BSData/wh40k-9e#8352]
**File/Catalogue:** WH40K v162 / Craftworlds Eldar v109

**BattleScribe version:** 2.03.21

**Platform:** Mac

**Dropbox:** Yes

**Description:** If taking an Eldar Detachment as a Wraith Host Specialist Detachment the option to select the Warlord Trait 'Revered by the Dead' should show up as a Warlord Trait when selecting a HQ from that detachment as the army's warlord (from Vigilus) but it does not show up as an option.  To reproduce:

Start new roster from Craftworld.
Select Detachment type
Under Specialist Detachment select 'Wraith Host'
Assisgn HQ unit (Spiritseer etc)
Select 'Warlord'
'Revered by the dead' should show up and be selectable  as a Warlord Trait.

**Comment by Tech-Ninja** [comment]
Just by way of an update.  Had two friends try this using Windows machines.  Same issue, so doesn't look to be platform specific.

**Comment by FarseerVeraenthis** [comment]
this was actually a bug in the Ynnari CAT where the warlord traits are held.
It is now working and will be inlcuded in the next official release (Thursday)
