### ISSUE TITLE
Battle Sisters - Power Sword Doesn't Have Latest Stats

### ISSUE THREAD

**Issue by GreatAmNovella** [BSData/wh40k-9e#8354]
**File/Catalogue:** Warhammer 40,000 v9.0.23

**BattleScribe version:** 2.03.21

**Platform:** Win10

**Dropbox:** Yes

**Description:** Power Sword weapon profile states that S is User which does not reflect latest updates to Codex rules that Power Swords are +1 Strength. Screen shot attached from latest codex upload from Warhammer Community BS Indomitus Version 1.2 update from GW on 5 Oct 2020 available here: https://www.warhammer-community.com/wp-content/uploads/2020/10/LR1EZE6loJzSINlP.pdf

![Battle Sisters Power Sword Profile](https://user-images.githubusercontent.com/73411250/97096787-f8a0c000-163e-11eb-9b33-372f3ad71da8.jpg)

**Comment by GreatAmNovella** [comment]
From a quick glance, it looks like a few of the other weapons profile upgrades that were made on 5 Oct 2020 in the FAQ have not yet been made to the Sisters' weapons profiles - e.g., hunter-killer missiles, meltagun and multi-meltas all still have the old profiles in the software. Thank you for making these updates; they are much appreciated.

**Comment by Technoblazed** [comment]
This has already been fixed and is in the latest master data, but has yet to be released.
