### ISSUE TITLE
There is no chaos familiar option for thousand sons

### ISSUE THREAD

**Issue by vickyj9** [BSData/wh40k-9e#8358]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:**  there is no chaos familiar option for thousand sons psykers it would be a neat addition for the strategem but overall not too important figured it was just and oversight

**Comment by Mad-Spy** [comment]
Chaos Familiar is used in the Psychic Phase, not during list building. We only include stratagems which affect list-building in the data set.
