### ISSUE TITLE
Dark Angels v174 Issues

### ISSUE THREAD

**Issue by hagamemnon** [BSData/wh40k-9e#8365]
**File/Catalogue:** Adeptus Astartes - Dark Angels v174 (latest)

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** Did a check of DA unique items, found the following remaining issues:

- [x] Deathwing Command Squad has the wrong points cost. Lightning claws should be free, Chainfist should be 5 points.

- [x] Deathwing Command Squad, Deathwing Terminator Squad, Deathwing Knights are still listed as 2 wounds per model, should be 3 wounds per model.

- [x] Text on Watcher in the Dark should be corrected to read: `"Once per battle, this unit can attempt to Deny the Witch as if it were a Psyker. If the model attempting to manifest the psychic power is a Chaos Psyker, you can re-roll that Deny the Witch test."` Current text says "this model can attempt"

- [x] Ravenwing Talonmaster are listed as having 6 wounds, should be 8 wounds. Ballistic Skill is currently 3+, should be 2+; explodes text is wrong, listed as d3 mortal wounds when it only deals 1 mortal wound on explosion.

- [x] Ravenwing Darkshroud cost for Assault Cannon is currently listed as 20 points, should be 10 points.

- [x] Ravenwing Land Speeder Vengeance cost for Assault Cannon is currently listed as 20 points, should be 10 points. As well, Plasma Storm Battery is currently Heavy D6 for both profiles, should be Heavy 2D3 for both profiles.

- [x] Ravenwing Ancient should be a valid target for Hero of the Chapter.

- [x] Ravenwing Apothecary should be a valid target for Hero of the Chapter.

- [x] Ravenwing Champion should be a valid target for Hero of the Chapter.

- [x] Deathwing Champion should be a valid target for Hero of the Chapter.

- [x] Deathwing Apothecary should be a valid target for Hero of the Chapter.

- [x] Ravenwing Black Knights - Huntmaster currently has Corvus Hammer by default, should have a "no weapon" option.

- [x] Attack Bike Squad and Bike Squad both have JINK listed as an ability, however these do not currently have this ability. They only gain the Ravenwing keyword if they are in a Dark Angels (or successor) detachment. (this might be an issue with the SM datafile, not sure whose issue it is)

**Comment by FarseerVeraenthis** [comment]
Thanks again for the QA, I admit that I didn't check the existing unit thoroughly at all, at first glance they looked "OK" - apparently that wasn't a very good first glance...!!
I note that the Assault Cannons are in fact 5pts, and the Talonmaster's stats changed quite a bit more than just wounds, BS and exploding in a different way... 
Otherwise, I would appreciate further checking, it lightens the load on our resident QA experts :smile:
