### ISSUE TITLE
Ork Blood Axe Klan  specail Gubbins upgrade "Morgog's Finkin' Cap""

### ISSUE THREAD

**Issue by whitewolfmxc** [BSData/wh40k-9e#8368]
**File/Catalogue:**  warhammer 40k  Orks 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** /No

**Description:** 

This upgrade item for HQ units (using blood axe klan kulture) its meant to give 2 warlord traits but it doesnt seem to work in the app , rules as below 

Morgog's Finkin' Cap | BLOOD AXE model only. If the bearer is your Warlord, you can generate a second Warlord Trait for them. If the bearer is not your Warlord, generate a Warlord Trait for them (note that the bearer is only regarded as your Warlord for the purposes of that Warlord Trait). The same Warlord Trait cannot be generated for both the bearer and your Warlord. | Codex: Orks p131

**Comment by Technoblazed** [comment]
This functionality already exists, you need to expand the unit or click through on the mobile app to view the Finkin' Cap, where you are then able to click the upgrade and select another trait.
