### ISSUE TITLE
SM Purgatorus Relic - Still shows heavy bolt pistol in wargear after selection

### ISSUE THREAD

**Issue by Mofoman1** [BSData/wh40k-9e#8371]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** Yes/No

**Description:** Detailed issue description.

Unit - Primaris Captain with Relic Shield and MC PWR SW

When the Purgatorus relic is selected it doesn't replace the Heavy Bolt pistol in the equipment but just adds Purgatorus to the Wargear.

**Comment by acebaur** [comment]
This is the same with every relic in the codex
