### ISSUE TITLE
DA v175 - Final Issues (hopefully!)

### ISSUE THREAD

**Issue by hagamemnon** [BSData/wh40k-9e#8383]
**File/Catalogue:** Imperium - Adeptus Astartes - Dark Angels v175

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** 

- [x] No option for Relics of the Chapter (extra relic stratagem)

- [x] Deathwing Command Squad - points cost are wrong for Lightning Claw (pair) - current 10 points, should be 0 points.

- [x] All non-named characters should be able to take Brilliant Strategist as a warlord trait.

- [x] All non-named characters (except the Talonmaster) should have access to the Codex: Space Marines relics and special issue wargear.

- [x] Captain in Terminator Armour should have access to the Blade of Burden relic.

- [x] Ravenwing Apothecary is missing the Combat Restoratives ability.

- [x] Deathwing Apothecary is missing the Combat Restoratives ability.

- [x] Deathwing Terminators are currently 2 wounds, they should be 3 wounds.

- [x] When Deathwing Champion is upgraded using the Chapter Champion, the Attacks characteristic should be upgraded to 5, and the Leadership characteristic upgraded to 9. This currently has no effect aside from adding the chapter champion abilities to the unit.

**Comment by FarseerVeraenthis** [comment]
Thank you! I could have sworn I already fixed some of these, apparently not...!
I'll have another go tonight 😄

**Comment by Gingrel** [comment]
- [x] Interrogator-Chaplain in Terminator Armour - points costs are wrong for combi-weapons. All are currently 10 points, should be 5.
- [x] Interrogator-Chaplain in Terminator Armour should not have options from the _Terminator Melee Weapons_ list (unless these are legends options in which case they need to display the appropriate tag)
- [x] Interrogator-Chaplain has multiple incorrect wargear points values:
- All combi weapons should be 5 (currently 10)
- Thunder Hammer should be 20 (currently 15)
