### ISSUE TITLE
Space marines - most Masters of the Chapter points costs are too high

### ISSUE THREAD

**Issue by Wurrkop** [BSData/wh40k-9e#8386]
**File/Catalogue:** 
Space marines - Masters of the Chapter
**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
The Masters of the Chapter upgrades are too high:
Chaplain/Master of Sanctity is 35, should be 25.
Librarian/Chief Librarian is 35, should be 25.
Techmarine/Master of the Forge is 30, should be 20.
Ancient/Chapter Ancient is 30, should be 20.
Company Champion/Chapter Champion is 25, should be 15.
Apothecary/Chief Apothecary is 25, should be 15.

**Comment by acebaur** [comment]
We are going by the points in the back of the book in the points section.
