### ISSUE TITLE
Imperial Guard Leman Russ Conquerors

### ISSUE THREAD

**Issue by DudeChris33** [BSData/wh40k-9e#8387]
**File/Catalogue:** Warhammer 40k 9th Edition v162

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The Leman Russ Conqueror squad is labeled as a model, which interferes with exporting and external encoding.
![Screenshot (40)](https://user-images.githubusercontent.com/43427245/97346111-40466800-1848-11eb-81be-d1104f453474.png)

**Comment by DudeChris33** [comment]
No fix?

**Comment by alphalas** [comment]
... do you not read m8?
<img width="389" alt="Screen Shot 2020-10-27 at 20 03 04" src="https://user-images.githubusercontent.com/15703066/97374750-6e02cf80-188f-11eb-954f-a3b29188c0e0.png">

**Comment by DudeChris33** [comment]
Oh you mean you fixed it. My bad thought you just closed it without response.
