### ISSUE TITLE
Necrons v77 Issues

### ISSUE THREAD

**Issue by UraharaKisuke88** [BSData/wh40k-9e#8393]
**File/catalogue:** Necrons.cat v77

**BattleScribe version:** 2.03.21

**Platform:** Mac

**Dropbox:** No

**Description:** The Rarefied Nobility stratagem is not available for named characters (unlike similar stratagems, the Necron version strangely has no 'non-named character' clause).

Plasmancer does not have access to the Quantum Orb Arkana but the Technomancer does.

Dynasty specific relics aren't locked to Dynasty characters. For example, if you have a Sautekh and a Novokh detachment the Vanquisher's mask is available for the Novokh characters and the Blood Scythe is available to the Sautekh characters.

Prismatic Obfuscatron Arkana is misspelled as 'Prismatic Obfuscation'.

Hexmark Destroyer is unable to take any regular character upgrades like WLTs/relics despite being a character.

Command Protocols description has misspelled Dynastic Agent in the first sentence.

**Comment by DrTobogganMD** [comment]
Half of these were fixed already - But I fixed the rest in this commit.
