### ISSUE TITLE
Tau - Strike/Breacher Team Pulse Pistols free?

### ISSUE THREAD

**Issue by Marconius6** [BSData/wh40k-9e#8395]
**File/Catalogue:** Tau Empire v70

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** Yes

**Description:** I've noticed that "Fire Warrior" and "Fire Warrior w/ Pulse Pistol" both cost 9pts each; similar for every other combination. The Codex says Pulse Pistols are 1pt and I can't find any update to this anywhere.

**Comment by Technoblazed** [comment]
Pulse pistols were updated to 0 points each in the 2020 Chapter Approved MFM.
