### ISSUE TITLE
Blood Angels QA #2

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#8396]
File/Catalogue: Blood Angels v191

BattleScribe version: 2.03.21

Platform: Windows

Dropbox: No

Description: 
- Death Company Intercessors are missing its' stats from their datasheet. No "M", "WS", "BS", "S", "T", "W", "A", "Ld", and "Save"
- That whole section is completely missing
- I believe Sanguinary Priests can get the "Chief Apothecary" upgrade since they have the "Apothecary" keyword but they do not have it currently

**Comment by mdmagnusson** [comment]
All Blood Angel Ancients are missing option to upgrade to Chapter Ancient.
* Ancient in Terminator Armor
* Bladeguard Ancient
* Company Ancient
* Company Ancient on Bike [Legends]
* Primaris Ancient
* Sanguinary Ancient

**Comment by alphalas** [comment]
<img width="270" alt="Screen Shot 2020-10-28 at 07 51 06" src="https://user-images.githubusercontent.com/15703066/97432676-b7d0d180-18f2-11eb-9c11-59a0a6d0fed2.png">
@mdmagnusson BA cannot have Chapter ancient according to the codex.
