### ISSUE TITLE
Imperium - Space Marines - Heavy intercessor heavy bolter points cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8397]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** on Imperium - Space Marines v197 I have noticed the following points are incorrect:

 - the Chapter Command: Master of the Forge option is currently set to 30 points instead of 20 points
 - The Heavy Bolter option for the Heavy Intercessors is currently set to 15 points instead of 10 points

**Comment by acebaur** [comment]
Masters of the chapter points from the points section are being used
