### ISSUE TITLE
Imperium - Dark Angels - Missing Captain on Bike entry/ravenwing keyword

### ISSUE THREAD

**Issue by dalamar666** [BSData/wh40k-9e#8399]
**File/Catalogue:** Dark Angels v176

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Maybe I'm blind but I don't see an entry for the Captain on Bike.

**Comment by FarseerVeraenthis** [comment]
Good News!! You passed your sight test, you're not blind!!
Also good news, he will be in the next update!!
