### ISSUE TITLE
Blood Angels QA LibSM/GST #3

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#8400]
- The heavy bolter upgrades on all units with the "infantry" keyword is costed at 15 pts but should be 10pts for infantry units. This is in other SM catalogues too.
- Techmarine is 50pts base but should be 70pts base
- Techmarine is completely missing his Omnissian power axe, which will be free for him

**Comment by acebaur** [comment]
Omnissian power axe is on there, just not set as default

**Comment by RespectableJack** [comment]
Okay I see it now thank you.
Also I just found it but did not wanna make a full post just for one bug. When I make a Primaris Captain, Captain in Phobos Armor, and Captain in Terminator Armor a chapter master, the chapter master benefits are still the old version on their data sheets.

**Comment by RespectableJack** [comment]
Captain in Gravis Armor* not the Phobos Captain, my bad

**Comment by acebaur** [comment]
fixed on master

**Comment by RespectableJack** [comment]
okay and thanks for all the work you guys do
