### ISSUE TITLE
Dark Angels - QA

### ISSUE THREAD

**Issue by chronocobra** [BSData/wh40k-9e#8401]
**File/Catalogue: Imperium - Dark Angels

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:

- [x] Dark Angels currently do not have access to SM Relics from the Codex.
- [ ] Dark Angels currently do not start with a free relic slot.
- [x] Corvus Hammer is still a mix with the old profile. (2 dmg but has d3 dmg ability)
- [x] Chapter Master in Terminator Armour is still displaying old CM rules.

**Comment by FarseerVeraenthis** [comment]
1 & 3 are done, I'm not sure what you mean by 2, if you have a warlord you get a relic without a validation error...
4 is a complete mystery, I cannot figure out why it is not pulling the correct wording...
