### ISSUE TITLE
Chaos - Chaos Space Marines - Chosen Champion upgrade validation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8406]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** The Chosen Champion is unable to take upgrades because a verification error pops up whenever you switch out either the bolt pistol or the boltgun, in any combination. Also applies to the Android version.

**Comment by Mad-Spy** [comment]
Unable to duplicate. The weapon layout is validating correctly as per the datasheet. If you believe a specific valid loadout is not working, please state which combination.
