### ISSUE TITLE
Bloond Angels QA

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#8408]
File/Catalogue: Blood Angels v196

BattleScribe version: 2.03.2

Platform: Windows

Dropbox: No

Description: 

- [x] Death Company Marines have chainswords, but they should have Astartes chainswords
- [x] Still the issue of not being able to take a second litany if you select the Master of Sanctity upgrade for any chaplain without there being an error saying he can only have a maximum of 1
- [x] Still the issue of not being able to take a third psychic power if you select the Chief Librarian upgrade for any librarian without there being an error saying he can only have a maximum of 2
- [ ] This has been there awhile, but whenever you select "Chapter" then "Chapter Selection" you can only choose from Forge World Chapters, no successor chapter option. Is it possible to add the system of making a successor chapter to Blood Angels, just like all the other Space Marine chapters have? 
- [x] The Magna-grapple still has the old rule for "plus 2 to charge when charging a vehicle." Needs to be updated to the new rule in the Index

**Comment by alphalas** [comment]
per point 4 - Flesh tearers are there in the selector as an option though, and Lamenters are in the FW list. technically as of right now you can't use BA units for custom chapters.

**Comment by RespectableJack** [comment]
okay thank you
