### ISSUE TITLE
Imperium - Space Marines - VV/Captains missing special wargear/weapons

### ISSUE THREAD

**Issue by GuillermoDiazGarcia** [BSData/wh40k-9e#8411]
**File/Catalogue:** 

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:**

Vanguard veterans and characters are missing inferno pistols and hand flamers. ~~Captains are also missing xenophase blades~~

**Comment by Technoblazed** [comment]
Hand Flamer/Inferno Pistol on the Pistols SSEG need changing to `and` instead of `or`.

**Comment by Technoblazed** [comment]
Can't replicate any of this anymore, make sure your data is up to date.
