### ISSUE TITLE
Imperium - Space Wolves - extra abilities from SDEG

### ISSUE THREAD

**Issue by kyleharvey68** [BSData/wh40k-9e#8413]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** Yes/No

**Description:** All SW entries have access to too many rules. need to replace SDE with savage fury.

**Comment by kyleharvey68** [comment]
Bjorn the Fell-handed also has Berserk Charge, Headstrong, Savage Fury and Swift Hunters, which he should not.

**Comment by kyleharvey68** [comment]
I've only just started looking through the datasheets

**Comment by alphalas** [comment]
I’m the guy who did the update I know EVERYTHING has all three of those

**Comment by alphalas** [comment]
> Bjorn the Fell-handed also has Berserk Charge, Headstrong, Savage Fury and Swift Hunters, which he should not.

Bjorn *should* have SF btw.
