### ISSUE TITLE
Company Vets don't have Command Squad Ability

### ISSUE THREAD

**Issue by tirion5** [BSData/wh40k-9e#8414]
**File/Catalogue:** v9.1.0

**BattleScribe version:** 2.03.

**Platform:** Android/Windows

**Dropbox:** no

**Description:** Company Vets should not count towards the elites selection when in a detachment with a captain. 

Keep up the great work!

**Comment by acebaur** [comment]
They are in the No Force Org section

**Comment by tirion5** [comment]
> They are in the No Force Org section

my bad thank you!
