### ISSUE TITLE
Eradicators MM unit count is off

### ISSUE THREAD

**Issue by tirion5** [BSData/wh40k-9e#8415]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/Android

**Dropbox:** no

**Description:** Eradicators can have a MM for every 3 models in the unit. Currently there is no way to decrease the "normal" eradicators lower than 2. It results in a minimum squad size of 4 if you want to have a MM.

**Comment by khinzaw** [comment]
Also shouldn't you be able to individually select which models get heavy meltas instead of all or nothing?

**Comment by tirion5** [comment]
No it's all  or nothing

**Comment by khinzaw** [comment]
Ah, my mistake. Never mind.
