### ISSUE TITLE
Infiltrator options faulty

### ISSUE THREAD

**Issue by Saymos** [BSData/wh40k-9e#8416]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Infiltrators don't have the upgrade "Infiltrators Helix Adept" anymore but instead "Helix Gauntlet" for 10 pts. The Infiltrator Comms Array is also not 29 pts but 5 pts.

**Comment by acebaur** [comment]
Those options go on a model, which is why they cost what they do. Points are correct
