### ISSUE TITLE
Assault marine special weapon space marine incorrect cost

### ISSUE THREAD

**Issue by Jonjacob34** [BSData/wh40k-9e#8418]
**File/Catalogue:** 
Imperium - Space Marines 

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** no

**Description:** 

Assault Squad special weapons space marines are 18pts per model not 20pts. 
![Screenshot_20201029_190506_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/73666370/97621992-899ae100-1a1b-11eb-9708-3b0380fc0ced.jpg)

**Comment by acebaur** [comment]
They do have an incorrect points cost of 15, the weapons are each 5 making it incorrectly 20 instead of of the correct 23. Will fix for the next update
