### ISSUE TITLE
Blood Angels - Sanguinary Priest missing “hero of the chapter” option

### ISSUE THREAD

**Issue by jtaustx** [BSData/wh40k-9e#8420]
**File/Catalogue:** WH40K 

**BattleScribe version:** 2.03.15

**Platform:** iOS 

**Dropbox:** 

**Description:** The Sanguinary Priest Option for Blood Angels is missing the “Hero of the Chapter” ability, which all characters should have.

**Comment by alphalas** [comment]
moved to #8515
