### ISSUE TITLE
Blood Angels - App crash when adding Lieutenant

### ISSUE THREAD

**Issue by jtaustx** [BSData/wh40k-9e#8421]
**File/Catalogue:** wh40k 

**BattleScribe version:** 2.03.15

**Platform:** iOS 13.7

**Dropbox:** 

**Description:** adding Lieutenant to Blood Angels army list. The initial selection works fine. Going into the sub-options, every time I select “Primaris Lieutenant” the app hard crashes.

**Comment by alphalas** [comment]
Fixed on master will be in next release
