### ISSUE TITLE
Lieutenant extra power level cost for storm shield and volkite is missing

### ISSUE THREAD

**Issue by MrAwesomdary** [BSData/wh40k-9e#8422]
Missing the +1 power cost for Lieutenant, atleast for space wolves

**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by tirion5** [comment]
i had this as an open case but it was closed for some reason. It isn't just SW

**Comment by acebaur** [comment]
It was closed because it's fixed on master

**Comment by tirion5** [comment]
Thanks for the explanation
