### ISSUE TITLE
SW points issues/missing options

### ISSUE THREAD

**Issue by Shoxaju** [BSData/wh40k-9e#8428]
**File/Catalogue:** space wolves

**BattleScribe version:** 2.03.

**Platform:** andriod

**Dropbox:** Yes

**Description:** number of issues I've seen so far, trying not to duplicate other open issues.

- [x] Cyberwolf(s) not available 
- [x] Wolflord on Thunderwolf has no WL trait option or option to upgrade to Chapter master
- [x]  Thunderwolf Cavalry shield cost is now 5, not the 8 listed
- [x] Grey Hunters should have option for Astartes chainswords at +1ppm
- [x] Eradicator Multi Melta option is overcosted (+20, should be +10) LIBRARY ISSUE FIXED ELSEWHERE
- [x] Trophies of Fenris, relic strategem, should be replaced with codex version and cost 1/2 instead of 1/3
- [x] Primaris Chaplain on bike (and other chaplains) count Litany of Hate and chapter litany towards their max litany count and should not (reads as 4 litanies max 2 for a master of sanctity)
- [x] None of the characters seem to have access to relics
- [x] Chapter litany (Tales of the wolf king in the deep) was removed in the FAQ update on Oct. 5th
- [x] SW specific Warlord trait from the codex is unavailable

**Comment by renegadejade** [comment]
- [x] Cyberwolf option for Fenrisian Wolves missing in addition to the Cyberwolf unit mentioned above.

**Comment by Shoxaju** [comment]
update on #8 some characters seem to have access to relics, it appears most of the general codex characters are alright. I've encountered the issue so far with wolf lords, Primaris chaplain on bike, librarian (non primaris, just the regular version)

I believe there might be a related issue with not getting access to relics at all if a wolf lord on thunderwolf is your warlord.

**Comment by Garvlok** [comment]
I think all the units units have extra abilities headstrong, berserk charge and swift hunters when they arent suppose to. For example eradicators, hellblasters, assault intercessors, primaris Librarian. 

The ven dread is in the no force org slot.

**Comment by joggy011** [comment]
Chaplain upgrade to Master of Sanctity cost 35 and in book it's 25

**Comment by Shoxaju** [comment]
> 
> 
> Chaplain upgrade to Master of Sanctity cost 35 and in book it's 25

in the point summary on the back of the book it is listed at 35
