### ISSUE TITLE
Can't take "no force org slot" Company Champion

### ISSUE THREAD

**Issue by ThePants999** [BSData/wh40k-9e#8437]
**File/Catalogue:** Imperium - Space Marines v9.1.0

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Description:** Having a Captain in a detachment correctly adds Company Veterans to the No Force Org Slot options, as per their Command Squad ability. Adding the Company Veterans then adds Apothecary and Company Ancient to the No Force Org Slot options. However, it doesn't add Company Champion, and should, as they also have **Command Squad**: For each **<CHAPTER> COMPANY VETERANS** unit included in a Detachment, one **<CHAPTER> COMMAND SQUAD COMPANY CHAMPION** unit can be included in that Detachment without taking up a Battlefield Role slot.

**Comment by ThePants999** [comment]
I've also spotted that the Company Champion is missing the **COMMAND SQUAD** keyword, and that's probably what's causing the bug above.

**Comment by acebaur** [comment]
What chapter?

**Comment by ThePants999** [comment]
White Scars
