### ISSUE TITLE
Erradicators Fixes

### ISSUE THREAD

**Issue by joarangoe** [BSData/wh40k-9e#8438]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** 

*** Erradicators mising Melta Rifle Equipment each as base weapon (Only Bolt Pistol is listed for each model)

*** Total Obliteration rule outdated (Only valid if the unit did not advance. codex pg 175 )

**Comment by acebaur** [comment]
Melta rifles are listed under Unit Weapon Options
