### ISSUE TITLE
Master of the Codex able to be taken by anyone

### ISSUE THREAD

**Issue by bbobson7** [BSData/wh40k-9e#8439]
**File/Catalogue:** Imperium - Adeptus Astartes -Black Templars v27

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** I've noticed this in other catalogues but if I have a  Chapter Master in the army anyone can take the Chapter Master Warlord trait Master of the Codex

**Comment by acebaur** [comment]
Not reproducing
