### ISSUE TITLE
Night Shroud still on necron flyer section

### ISSUE THREAD

**Issue by KitsuneLegion** [BSData/wh40k-9e#8445]
**File/Catalogue:** Necron Flyer section

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Necron Night Shroud is still on the flyer section even though it was removed from the codex.

**Comment by Valorcalls** [comment]
Night Shroud is a Necron Flyer from Forge World, not from the necron codex.
