### ISSUE TITLE
Dark Angels - Talon Master has incorrect PL

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8446]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Ravenwing Talonmaster is 9pl and should be 8pl. As per faq. 
Thank you for all you do.

**Comment by LunarWarrior21** [comment]
RWTM is currently missing from the roster, so I think they are currently fixing this.  Just wondering, do both land speeders, outriders, and normal bike squad for DA all not get jink?

**Comment by Technoblazed** [comment]
@LunarWarrior21 the talon master is under the lieutenants option.
