### ISSUE TITLE
Imperium - Blood Angels - Missing invader ATV

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8448]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Fast attack section is missing invader ATV. I guess all space marine sections are missing it
Thanks

**Comment by Dunamis55** [comment]
Duplicate of #8483
