### ISSUE TITLE
Born Heroes successor trait has the old rule

### ISSUE THREAD

**Issue by ATR3US** [BSData/wh40k-9e#8451]
**File/Catalogue:** Adeptus Astartes Raven Guard

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Born Heroes trait needs to be updated to +1 to hit in close combat if that unit charged that turn

**Comment by Mad-Spy** [comment]
Fixed in #8488
