### ISSUE TITLE
Death Company Intercessors weapon options

### ISSUE THREAD

**Issue by StuxTW** [BSData/wh40k-9e#8453]
**File/Catalogue:** Blood Angels

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:** 

As much as I would love to be able to, I do not believe it should be possible to arm the unit with Chainswords AND give a model a power weapon.

The only way to get a power power weapons explicitly forbids the model having a chainsword, and there is no way to swap out a chainsword for anything once you give the unit them.

**Comment by alphalas** [comment]
Order of operations mate, GW said you can do the bullet points in any order inna faq - it’s why you can have Astartes Chainswords and AGLs on then too. It’s stupid.

**Comment by StuxTW** [comment]
I dont think that's the issue here. The issue is that the bullet says you can't have a chainsword AND a power weapon. If you change the order you still violate that.

You can swap in any order, but you still have to satisfy all restrictions in the final state.
