### ISSUE TITLE
Chaos - Death Guard - Blight Hauler points costs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8454]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Chaos - Death guard 
Fast attack - Myphitic Blight Haulers should be 100 pts and they are currently 90pts in the app.

**Comment by Mad-Spy** [comment]
Fixed in next release.
