### ISSUE TITLE
Infiltrator Squad - Comms Array counts towards troop count

### ISSUE THREAD

**Issue by takimeta** [BSData/wh40k-9e#8455]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Mac 10.15.7

**Dropbox:** Yes/No

**Description:** Infiltrator Squad - Comms Array counts towards troop count
STEPS
1. Create a Space Marines army of any point size
2. In the TROOPS selection, select _Infiltrators_
3. In the Army List, highlight _Infiltrators_
4. In the Unit Selection bar, check the _Infiltrator Comms Array_ count
5. Increase the Troop count to 9

RESULT
A "1 too many selections from Infiltrators (maximum 10)" error message appears.
![Screen Shot 2020-10-29 at 3 46 53 PM](https://user-images.githubusercontent.com/35934408/97640536-2cdcfd80-19fe-11eb-967d-25a1430780de.png)

**Comment by ATR3US** [comment]
Hi mate, this is because the sergeant it’s out of the “troop count” if you want 10 men with coms array select 8 in the box and tick the coms array :)

**Comment by ThePants999** [comment]
It's not counting the comms array itself - "Infiltrator Comms Array" is an Infiltrator model WITH a Comms Array, not just the Comms Array.

**Comment by takimeta** [comment]
Huh... it should be a bit more detailed in the unit's title heading, then. As it stands, it's pretty confusing. Either way, this ticket can be closed, then.
