### ISSUE TITLE
Ravenwing Talonmaster has no selection entry

### ISSUE THREAD

**Issue by ip5en** [BSData/wh40k-9e#8462]
**File/Catalogue:**  Imperium - Adeptus Astartes - Dark Angels v177

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Ravenwing Talonmaster has no entry in Root Selection Entries

**Comment by holydakka** [comment]
same issue for android

**Comment by ip5en** [comment]
It's under lieutenants
