### ISSUE TITLE
Blood Angels issues

### ISSUE THREAD

**Issue by KasmKat** [BSData/wh40k-9e#8464]
**File/Catalogue:** Blood Angels

**BattleScribe version:** 2.03.

**Platform:** Windows

**Description:**
Several Errors noted for Blood angels - 

- [ ] Chapter Selection doesn't have successor options

- [ ] No Invader ATV in Fast attack

- [ ] Chaplains still forced to Know Invocation of destruction when it no longer exists

**Comment by alphalas** [comment]
Blood angels still only have Lamentors, FT, and FW chapters as successor options rn.
