### ISSUE TITLE
Various Dark Angels chapter command units cannot take the associated warlord traits

### ISSUE THREAD

**Issue by ip5en** [BSData/wh40k-9e#8466]
**File/Catalogue:** Imperium - Adeptus Astartes - Dark Angels v177

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Dark angels v177 doesn't have Shared Selection Entry Groups; Warlord Traits (Chapter Champion), Warlord Traits (Chapter Master), Warlord Traits (Chief Librarian), Warlord Traits (Master of Sanctity), or Warlord Traits (Master of the Forge).

Also missing Warlord Traits (Vanguard)

**Comment by FarseerVeraenthis** [comment]
moved to #8587 and closed
