### ISSUE TITLE
Imperium - Blood Angels - DC/FD bugs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8468]
**File:** Imperium - Black Templars.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Chaplain still had Invocation of Destruction, five Death Company with Jump Packs should be Power Level 8 (there is still a +1 modifier to the Power Level in the Data Editor), and Furioso Dreadnought should be Power Level 8. Thanks for the hard work!

**Comment by CallMeCraven** [comment]
To add to the DC marines PL with jump packs, when you increase the unit size to 6+, the PL for jump packs jumps to 4, should be 2 per BA index.

**Comment by alphalas** [comment]
moved to #8515
