### ISSUE TITLE
Sisters of battle - all inquisition missing

### ISSUE THREAD

**Issue by ratman99uk** [BSData/wh40k-9e#8469]
**File/Catalogue:** 
**BattleScribe version:** 2.03.25
**Platform:** iOS and Android
**Dropbox:** Yes

**Description:** 
I wiped all my old 8th data (from phone, iPad and Dropbox) and started a fresh with 9th edition.

However when doing my sisters of battle list all the inquisition models are missing from HQ.  
Grayfax for example, isnt there anymore.

Screen grab from Android:
https://photos.app.goo.gl/V4WqX6xZ5dPDA9Nw5

Went back to 8th last night and confirmed they are there in that still. 

Feel free to contact me if you want any more info
Regards
ratman99uk

**Comment by alphalas** [comment]
They no longer are part of the SoB army mate, look at the codex. They can be taken as auxiliary options but they will not fulfill HQ slots of your sisters army.

**Comment by ratman99uk** [comment]
Omg no!!!!!!!!!!!!!!!!!!!!

Thanks for getting back to me. Even if it is crushing news.

Please close the ticket

Regards
Ratman99UK
