### ISSUE TITLE
Imperium - Dark Angels - WLT, Relic and nephilim issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8472]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** 1. Warlord traits Brilliant Strategist: the description is wrong. 
2. Terminator sergeant: can’t use power fist + Storm Bolter, only three default choices.
3. Raven wing Talonmaster: unable to take relic Corvus Occulus. Setting was maximum relic = 0
4. Nephilim fighter : strafing run ability is no more
5. Nephilim fighter : Can carry 2 black sword missile

**Comment by FarseerVeraenthis** [comment]
Moved to #8587  and closed
