### ISSUE TITLE
Blood Angels: Pistols and Relics

### ISSUE THREAD

**Issue by 3Cows1Trenchcoat** [BSData/wh40k-9e#8478]
**File/Catalogue:** Imperium - Blood Angels.cat

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** A few more Blood Angels things I noticed:

- [ ] Under the Captain and Lieutenant listings, Inferno Pistol and hand flamers are 5 points, but should be 0 points. Unlike Librarians, Chaplains and Techmarines (all of which work as intended), the codex does not give them an additional cost for Captains and Lieutenants. 

- [ ] Blood Angels still have the old codex's "Armoury of Baal" stratagem for extra relics. They should use "Relic of the Chapter" like the other Chapters.

Thanks for the help. Have a great day! :)

**Comment by SashaOrlov** [comment]
Would also like to note that under Blood Angels, the Captain options seem to not be able to select the "Angel Artifice" relic when selected as Chapter Master (tested with the Captain with Master-crafted Heavy Bolt Rifle, and briefly looked at the basic Captain option, not sure if its true for other Captain options in Blood Angels/ Space Marines)

**Comment by CallMeCraven** [comment]
To add to primaris lieutenant wargear errors,  the 1 neo-volkite pistol, master crafter power sword and storm shield option should add 1 PL as well as the 15 points for the pistol.

**Comment by alphalas** [comment]
all moved to #8515
