### ISSUE TITLE
Dark Angels contemptor dreadnought cost

### ISSUE THREAD

**Issue by ARtheBear** [BSData/wh40k-9e#8479]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** Yes/No huh?

**Description:** the elite unit "Contemptor Dreadnought" costs 153 pts, the correct points cost is 150 pts.  
Thank you.

**Comment by FarseerVeraenthis** [comment]
Moved to #8587 and closed
