### ISSUE TITLE
Blood Angels QA

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#8483]
File/Catalogue: Blood Angels v198

BattleScribe version: 2.03.21

Platform: Windows

Dropbox: No

Description:
- Invader ATV squad is completely missing from the catalogue
- Still the issue of the Chief Librarian upgrade not allowing you to know a 3rd psychic power, still gives the error "has 1 too many selections from Disciplines (maximum 2)) on any Librarian even with the Chief Librarian upgrade selected 
- Death Company Marine default loadout is "bold pistol and chainsword" but it should be an Astartes chainsword instead of chainsword
- This is minor but on Sanguinary Guard data sheet, the angelus boltgun range is 1"8 instead of 18"
- Brother Corbulo is missing the "Chief Apothecary" keyword
- Technically the Librarian Dreadnought can have the Chief Librarian upgrade since he has the "Librarian" keyword
- I think you can add the ability to be able to make a successor chapter, like in all the other Space Marine catalogues since right now all there is when you click on "Chapter Selection" is Forge World chapters. There is an entire section in Index Astartes: Blood Angels dedicated to running a successor chapter of your choosing, not jsut Flesh Tearers or Lamenters.
- Or maybe, which i think may be better, do it like the Dark Angels catalogue for picking a successor, it's much simpler where you pick "successor" and just lose the characters and keep everything else even unique units

**Comment by CallMeCraven** [comment]
-Also minor, but Chief Librarian Mephiston (Primaris)'s chief librarian key word is combined with the Mephiston keyword, should be separate. 
![image](https://user-images.githubusercontent.com/73680588/97657247-9c66e300-1a26-11eb-9be1-e2dc670b6bc3.png)
![image](https://user-images.githubusercontent.com/73680588/97657271-b274a380-1a26-11eb-85fe-7697d62b1797.png)
-Sanguinary Priest with jump pack should have 12" movement, currently remains at 6"

**Comment by alphalas** [comment]
moved to #8515
