### ISSUE TITLE
Imperium - Blood Angels - Baal predator weapon pricing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8487]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Heavy Bolters/Heavy Flamers on the Baal Predator should be 15 each for a total of 30 points not 20. Thanks.

**Comment by alphalas** [comment]
moved to #8515
