### ISSUE TITLE
Imperium - Space Marines - Chapter tactics

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8488]
**File:** Imperium - Raven Guard.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Chapter tactics are not updated, e.g. stealthy is now light cover if more than 18" instead of 12", long range marksmen adds 3" but only to heavy and rapid fire, raven guard second bullet point lists dense cover for infantry only if in/on terrain and more 12" away.

**Comment by ATR3US** [comment]
I found a few more, maybe is better to add it here than to open a new issue:
Fearsome aspect: Now is an Aura ability(important for things like vox espiritum)
Long-range marksman: Now excludes flamers
Master artisans: Now only allows for a Reroll to hit(Not to wound)
Preferred Enemy: Now only Reroll 1s
Born Heroes: changed completely(there is an issue opened about this one)
