### ISSUE TITLE
Chaos black legion ghorisvex teeth

### ISSUE THREAD

**Issue by Rhynok** [BSData/wh40k-9e#8489]
**File/:** 

**BattleScribe version:** 2.03.

**Platform:** IOS 

**Dropbox:** /No

**Description:** ghorisvex teeth not appearing on black legion relics possibly other relics as well

**Comment by Mad-Spy** [comment]
Ghorisvex's Teeth can only be taken on a model with a chainsword. CSM no longer have chainswords and GW have not FAQed  it to be allowed for models with an "Astartes chainsword".

**Comment by Rhynok** [comment]
Wow

**Comment by JDCain** [comment]
The FAQ that was put out for the updates to the weapon includes the following line which I believe should cover this. 

In addition, replace every instance of ‘chainsword’ within the rules section of this book with ‘Astartes chainsword’.

**Comment by JDCain** [comment]
Never mind it was pointed out to me, by you,  ghorisvex teeth is not in the chaos 2.0 codex and is just in vigilous ablaze.

**Comment by Rhynok** [comment]
Why would that make a difference?

**Comment by alphalas** [comment]
@Rhynok because Vigilus Ablaze was not FAQ’d to match the ACS change so the relic still requires a CS.

**Comment by Rhynok** [comment]
Fair still seems daft though haha, still has chainsword in the name. I’ll still use it unless opponent really opposes it. Hopefully we get a new codex soon anyway.

**Comment by Rhynok** [comment]
Apparently it’s still accessible on Android for anyone wanting to use it
