### ISSUE TITLE
Lib - Space Marines: Company Veterans missing Heavy weapon option

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8494]
**File:** Imperium - Imperial Fists.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Company Vets should have the option to take a Heavy weapon but option is not available. Earlier in the day, the option was available but tried to make a list now and it is gone

**Comment by Mad-Spy** [comment]
If you increase the unit size to 5 models (as is required), the options will appear.
