### ISSUE TITLE
Bug report: Imperium - Adeptus Astartes - Salamanders

### ISSUE THREAD

**Issue by dr0ne23** [BSData/wh40k-9e#8496]
**File/Catalogue:** Imperium - Salamanders

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** Missing Primaris Lieutenants in roster options

**Comment by Mad-Spy** [comment]
All Lieutenants are now under the "Lieutenants" HQ options as you can mix and match which you want to take.
