### ISSUE TITLE
Imperium - Space Marines - Chief Apothecary Pts Correction

### ISSUE THREAD

**Issue by not-that-stephen-king** [BSData/wh40k-9e#8497]
**File/Catalogue:** Imperium - Space Marines

**BattleScribe version:** 2.03.

**Platform:** Windows

**Description:** Chief Apothecary upgrade listed as +25pts instead of +15pts

**Comment by Mad-Spy** [comment]
We are using the higher of the points values printed in the Codex, as per page 202.
