### ISSUE TITLE
Tyranids - Can Mawlocs Take Toxin Sacs?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#85]
**File:** Tyranids.catz

**BattleScribe version:** 2.01.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Mawloc cannot take Toxin Sacs, but should be able to. Under points section in index: Xenos 2 for Toxin Sacs there is a listing that shows Mawloc pays 1 point for Toxin Sacs.

**Comment by GenWilhelm** [comment]
Mawlocs don't have any wargear options listed on their dataslate.

**Comment by FarseerVeraenthis** [comment]
@genwilhelm that is true, but in the "other wargear" list there are several different costs for Toxin Sacs for different lists of models, one of which says "Toxin sacs (Hive Guard, Gargoyle, **Mawloc**, Termagant, Tervigon and Tyrant Guard)" - hence the question from the OP.
tbh, I think the datasheet overrules the points list, so Mawlocs can't take Toxin Sacs, and I'm closing the bug report.

**Comment by GenWilhelm** [comment]
That was my thinking too, hence why it currently works that way in the catalogue. I was planning to leave this open as a reminder, but I guess if it ever gets clarified by GW then we will just fix it anyway without needing an open issue.
