### ISSUE TITLE
Primaris Techmarine Master of the Forge is pointed incorrectly

### ISSUE THREAD

**Issue by shinjji** [BSData/wh40k-9e#8501]
**File/Catalogue:** Space Marines catz

**BattleScribe version:** 2.03.21

**Platform:** ALL

**Dropbox:** Yes

**Description:** Primaris Techmarine option 'Chapter Command: Master of the Forge' is set incorrectly at 30 points when it should be 20 points

**Comment by Mad-Spy** [comment]
We are using the higher of the two values printed in the book, as per page 202.
