### ISSUE TITLE
Death Guard - Myphitic Blighthauler weapon pts need adjustment

### ISSUE THREAD

**Issue by jollohandley** [BSData/wh40k-9e#8502]
**File/Catalogue:** Death Guard

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:** Myphitic Blighthaulers weapons are wrongly costed. Currently, Multi-Melta is 20pt. Should be 25pt. Missile Launcher is currently 15pt. Should be 20pt.

**Comment by Mad-Spy** [comment]
Duplicate of #8454
