### ISSUE TITLE
Necrons - Wrong Monolith Keywords

### ISSUE THREAD

**Issue by githubuser-riddip** [BSData/wh40k-9e#8504]
**File/Catalogue:** Necrons.catz

**BattleScribe version:** 2.03.15

**Platform:** iOS

**Dropbox:** No

**Description:** The Necron Monolith still has the FLY and LORD OF WAR keyword, but they are no longer listed in the new codex.

**Comment by DrTobogganMD** [comment]
It indeed lost FLY, but it is very much a LOW (sadly)
