### ISSUE TITLE
Chaos - Chaos Space Marines: Thunderhammer cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8510]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Chaos Chosen, the cost of thunderhammers is 40 points for all of them, i think it should be 15 points, since they are not characters.

**Comment by Mad-Spy** [comment]
Fixed in next release.
