### ISSUE TITLE
Space Marine Eradicators - allow minimum squad size of 3 when adding multi-melta

### ISSUE THREAD

**Issue by sumo89** [BSData/wh40k-9e#8512]
This was tested on the latest version of the Android app.
The rules for Eradicators are that for every 3 models in the squad, one can upgrade their gun to a multi-melta. On the app this is achieved by adding a unit under the header "Eradicator with MM", but doing so now means the minimum squad size is 4 and you cannot reduce the amount of normal Eradicators below 2 (+ 1 reserved for Sgt).

**Comment by acebaur** [comment]
Duplicate
