### ISSUE TITLE
Ultramarines - Several issues reported via Github

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#8514]
**File/Catalogue:** Imperium - Adeptus Astartes - Ultramarines v33

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [x] Primaris Techmarine is unable to take Relics from the Special Issue Wargear list
- [x] Chief Librarian Tigurius has the Master of Strategy Warlord trait ability even if he isn’t the Warlord
- [ ] Honour Guard is flagged as [Legends] in the available units list by default for Ultramarines, but shouldn’t be
- [x] Silver Templars relics can currently be taken by Ultramarines characters, but should be hidden for non-Silver Templars chapters

**Comment by acebaur** [comment]
Honor Guard will change to non legends when UM is selected as the chapter.
