### ISSUE TITLE
Death Company Intercessors can't take the assault intercessor loadout

### ISSUE THREAD

**Issue by bbobson7** [BSData/wh40k-9e#8521]
**File/Catalogue:** Imperium - Adeptus Astartes _ Blood Angels v186

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Death Company Intercessors should be able to trade their bolt rifle and bolt pistol for a heavy bolt pistol and Astartes Chainsword.

**Comment by Valorcalls** [comment]
Please update your data, as this works in v198.
