### ISSUE TITLE
Sanguinary Guard/Ancients melee weapons are pointed and profiled wrong

### ISSUE THREAD

**Issue by bbobson7** [BSData/wh40k-9e#8522]
**File/Catalogue:** Imperium - Adeptus Astartes - Blood Angels v186

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Encarmine weapons should be D2 rather than Dd3 and they don't have the +1 strength across power weapons. Only the fists should cost an extra 5 pts but only on the Guard and not the Ancient.

**Comment by Mad-Spy** [comment]
Consolidated into #8515
