### ISSUE TITLE
Dark Angels: Ravenwing Talonmaster Missing

### ISSUE THREAD

**Issue by Sk8erclone25** [BSData/wh40k-9e#8529]
**File/Catalogue: Dark Angels v177

**BattleScribe version: 2.03.

**Platform: Windows

**Dropbox: No

**Description: Ravenwing Talonmaster HQ is missing entirely.

**Comment by hagamemnon** [comment]
It's not missing - it's filed under Lieutenant(s)

**Comment by FarseerVeraenthis** [comment]
Thanks @hagamemnon you're right, he is a lieutenant so that's where he is due to the way BS handles things that can be selected without taking up a detachment slot.
