### ISSUE TITLE
Invader ATV Multimelta cost

### ISSUE THREAD

**Issue by Deltadal** [BSData/wh40k-9e#8535]
**File/Catalogue:** Iron Hands

**BattleScribe version:** 2.03.

**Platform:** iOS

**Dropbox:** No

**Description:** Invader ATV multimelta cost in BattleScribe is 25, the codex/GW app price is 5.

**Comment by acebaur** [comment]
Points are showing correct for me

**Comment by Deltadal** [comment]
I’m seeing Invader ATV with multimelta at 105, should be 85.

**Comment by hagamemnon** [comment]
Issue occurs when duplicating selections. Re-selecting the multi-melta resolves it back to 5 points

**Comment by alphalas** [comment]
@hagamemnon that’s a BS bug then not a data bug.
