### ISSUE TITLE
Dark Angels - Dark Angels Terminator Squad Heavy Weapons

### ISSUE THREAD

**Issue by Elttat** [BSData/wh40k-9e#8536]
**File/Catalogue:** Dark Angels

**BattleScribe version:** 2.03.

**Platform:** iOS

**Dropbox:** Yes/No

**Description:** The terminator squad heavy weapons are confusing and possibly incomplete. Option “Cyclone Missile Launcher and Storm Bolter” does not give the storm bolter. Option “Cyclone Missile Launcher, Thunder Hammer, Storm Shield” does not give thunder hammer or storm shield or add points for same. There is no option provided for taking a cyclone missile launcher and 2 lightning claws.

**Comment by FarseerVeraenthis** [comment]
Moved to #8587 and closed
