### ISSUE TITLE
Deathwing Terminator Sgt needs another wound

### ISSUE THREAD

**Issue by LunarWarrior21** [BSData/wh40k-9e#8540]
**File/Catalogue: Dark Angels** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:**Super small, but just thought I would let you know.  The sgt. Deathwing terminator needs 3 wounds, but it only has two.

**Comment by FarseerVeraenthis** [comment]
Duplicate of #8534

I'm sure I fixed this already prior to release but apparently not!
