### ISSUE TITLE
Space Marine White Scars - Adding a primaris lieutenant crashes BattleScribe 

### ISSUE THREAD

**Issue by agile-heresy** [BSData/wh40k-9e#8542]
**File/Catalogue:** Space Marines White Scars

**BattleScribe version:** 2.03.

**Platform:** iOS

**Dropbox:** Yes

**Description:** Adding a primaris lieutenant crashed the entire BattleScribe app. Recording of the crash: https://imgur.com/gallery/c4qAl1r

**Comment by Mad-Spy** [comment]
As per the number of other issues reporting this, it will be fixed in the next release.

Please take a minute to look at recently closed issues before raising new ones on Github.
