### ISSUE TITLE
Chief Apothecary points

### ISSUE THREAD

**Issue by Rattleme** [BSData/wh40k-9e#8549]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux
Windows
**Dropbox:** Yes/No

**Description:** Detailed issue description.
Chapter Command Chief Apothecary should be 15 points not 25
Thank you for the hard work

**Comment by Technoblazed** [comment]
We are using the higher points costs from the points summary section at the back of the book until an FAQ is made.
