### ISSUE TITLE
Dark Angels unable to select Successor Chapter Tactics

### ISSUE THREAD

**Issue by MrRWJP** [BSData/wh40k-9e#8551]
**File/Catalogue:** Dark Angels v177

**BattleScribe version:** 2.03.21.166

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** When selecting the "Successor" option in "Chapter Selection" in a Dark Angels list the successor chapter tactic options are not shown

**Comment by FarseerVeraenthis** [comment]
Moved to #8587 and closed
