### ISSUE TITLE
Blood Angel Chapter Litany 

### ISSUE THREAD

**Issue by Nastosa** [BSData/wh40k-9e#8554]
**File/Catalogue:** Imperium - Adeptus Astartes - Blood Angels V198

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** The Litany "Innovation of destruction" is still listed and mandatory for a Battle Forged Blood Angels Chaplains. As it is not listed in "Index: Blood Angels" it has been deleted.

**Comment by Mad-Spy** [comment]
Consolidated into #8515
