### ISSUE TITLE
Interrogator Chaplain unable to take special wargear

### ISSUE THREAD

**Issue by Rattleme** [BSData/wh40k-9e#8555]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux
Windows
**Dropbox:** Yes/No

**Description:** Detailed issue description.
Interrogator Chaplains cannot take special issue wargear (i.e. Angel's Ambit)
Thank you for your hard work

**Comment by FarseerVeraenthis** [comment]
Moved to #8587 and closed
