### ISSUE TITLE
Imperium - Space Marines - Primaris Lt. "Indomitus" loadout doesn't increase Power Level

### ISSUE THREAD

**Issue by FistnStoneWG** [BSData/wh40k-9e#8556]
File/Catalogue:
BattleScribe version: 2.03.21
Platform: Windows/Android
Dropbox: Yes
Description:
The "Indomitus" loadout (Neo-Volkite/MCPS/SS) for a Primaris Lt. has an increase of +1 PL in addition to points cost.  This is not reflected in the Roster.

**Comment by acebaur** [comment]
Already updated in the latest release
