### ISSUE TITLE
Imperium - Space Marines - Command Squad rule not working correctly.

### ISSUE THREAD

**Issue by FistnStoneWG** [BSData/wh40k-9e#8557]
File/Catalogue:
BattleScribe version: 2.03.21
Platform: Windows/Android
Dropbox: Yes
Description:
The "Command Squad" special rule applies to non-Primaris Company Veterans, Company Ancient, Company Champion and Apothecary.  This goes to roster validation and battlefield role slots.

For each Captain, one Company Veterans unit does not take up a battlefield role slot.
For each unit of Company Veterans, one of each of the following do not take up a battlefield role slot: Company Ancient, Company Champion and Apothecary 

I added all 4 of the above in BS to an army with a Captain and it still said I used 4 "elite" slots, when it should be none.

The rules also allow a command squad to exist without a Captain, but at the cost of an "elite" slot for the Company Veterans.

**Comment by acebaur** [comment]
They are in the No Force Org slot

**Comment by FistnStoneWG** [comment]
Thank you, I see it now.  Wasn't as intuitive, kept looking for an option on the right.
