### ISSUE TITLE
Centurions Price Points wrong

### ISSUE THREAD

**Issue by TheSoulReapers** [BSData/wh40k-9e#8558]
Price points for centurions, according new Space Marine Codex are 70 points, 20 more with las cannon, or 15 for Grav or Heavy Bolter.
Points on battle scribe are in old format and wrong cost. Centurion with lascannon should be 90 points not 110.
Also Suppressors smoke launcher rule its wrong, it has changed in the new codex to keyword with strat instead of hability.

**Comment by acebaur** [comment]
Centurion points are correct. They are 70 each and have a single grav cannon which is 15 or TWO HB which is 30 or TWO lascannon which is 40.
