### ISSUE TITLE
Imperium Space Marines - Assault Squad Special Weapon wrong points

### ISSUE THREAD

**Issue by FistnStoneWG** [BSData/wh40k-9e#8559]
File/Catalogue: Imperial Fists v25
BattleScribe version: 2.03.21
Platform: Windows/iOS/Android/Mac/Linux
Dropbox: Yes/No
Description:
Space Marine w/Special Weapon within the Assault squad should be 23 points now (18+5), not 20.

**Comment by acebaur** [comment]
Duplicate
