### ISSUE TITLE
Penitent Engines

### ISSUE THREAD

**Issue by harrisdmartin** [BSData/wh40k-9e#8561]
**File/Catalogue:**  Adapta Sororitas v.122

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Detailed issue description.
The Penitent Engines are listed at 50 points a model on the current version of Battle Scribe.  The 9th edition points value for the Penitent Engine is actually 20 points.

**Comment by Mad-Spy** [comment]
Cost is correct. 20pts for the model, 2x 15pts for the Heavy Flamers.
