### ISSUE TITLE
Imperium - Blood Angels: Heavy bolter cost for Devastators

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8569]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Devastator Squad Heavy Bolters are 15 when should be 10. Possibly related to fixing the Heavy Bolters on the Baal Predator?

 Five Death Company with Jump Packs are still Power Level 9 when they should be Power Level 8.

**Comment by Mad-Spy** [comment]
Consolidated into #8515
