### ISSUE TITLE
Necrons: Lokhust Lord should not have Phase Shifter

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8570]
**File:** Necrons.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Lokhust Lord has a Phase Shifter when he should not have a Phase Shifter.

**Comment by DrTobogganMD** [comment]
He very much should have a phase shifter. Please review your codex.
