### ISSUE TITLE
Imperium - Adeptus Astartes - Salamanders - Fast Attack Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8578]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Imperium-Adeptus Astartes-Salamanders v26 not showing fast attack units added, but adding points cost to total list cost.

**Comment by acebaur** [comment]
Not sure what you mean can you post images?

**Comment by Mad-Spy** [comment]
Closing as no update from OP.
