### ISSUE TITLE
Dark Angels - Ravenwing Ancient should be able to be the Chapter Ancient

### ISSUE THREAD

**Issue by Gingrel** [BSData/wh40k-9e#8581]
**File/Catalogue:** Dark Angels v178

**BattleScribe version:** 2.03.25.338

**Platform:** Android

**Dropbox:** Yes

**Description:**The Ravenwing Ancient has the ANCIENT keyword, but is unable to take the Chapter Ancient upgrade

**Comment by FarseerVeraenthis** [comment]
Moved to #8587 and hence closed
