### ISSUE TITLE
Imperium - Deathwatch - Missing Terminator Meltafist, Spectrus KT Issue, Relic Leviathan missing Volkite Option

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8583]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Terminator w/ Heavy Weapon unable to take Meltafist
Spectrus Kill Team won't allow less than 3 basic Infiltrators
Relic Leviathan Dreadnought unable to take Volkite Chargers instead of Heavy Flamers

**Comment by bluegrey3** [comment]
To add onto this, Vanguard Vets in the Proteus Kill Team have no associated PL cost, and are still equipped w/ standard Chainswords and not Astartes Chainswords.

**Comment by Valorcalls** [comment]
1) That weapon option is only available on 1 model in the kill team Cassius currently.
2) That's the minimum legal basic infils allowed in the unit.
3) That's not legal until next weekend.

**Comment by bluegrey3** [comment]
Wouldn't the minimum Infiltrator count be 2 if you take a Helix Adept,
Infiltrator w/ Comms Array, and a Sgt for a total of 5?

**Comment by Technoblazed** [comment]
@bluegrey3 You can take a Helix Adept OR a Comms Array, not both.

**Comment by bluegrey3** [comment]
Yeah I reread that, you're correct. Thanks!

**Comment by Technoblazed** [comment]
Vanguard vets are fixed in the supplement data which will release after the book releases.
