### ISSUE TITLE
Dark Angels - Interrogator Chaplain in Terminator armor Master of Sanctity no option for warlord trait Wise Orator

### ISSUE THREAD

**Issue by GingerRage95** [BSData/wh40k-9e#8586]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/Android

**Dropbox:** Yes

**Description:** Interrogator Chaplain in Terminator armor when selecting Chapter Command Mater of Sanctity there is no option to select Wise Orator as a Warlord Trait.

**Comment by FarseerVeraenthis** [comment]
Moved to #8587 and hence closed here.
