### ISSUE TITLE
Necron: Cryptothrall Bound Creation not active

### ISSUE THREAD

**Issue by Gorkamecha** [BSData/wh40k-9e#8589]
**File/Catalogue:** 

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Created a spearhead detachment with 2 Cryptek technomancers, 1 void dragon and 2 units of cryptothralls, was warned I am over elite choices by 1 - neither cryptothralls should have counted against my total elites.

**Comment by acebaur** [comment]
Add them from the cryptek entry
