### ISSUE TITLE
Death Guard: Multi Melta + Missile launcher cost incorrect

### ISSUE THREAD

**Issue by ShaneRing11** [BSData/wh40k-9e#8593]
**File/Catalogue:** Death Guard v102

**BattleScribe version:** 2.03.25.338

**Platform:** Android

**Dropbox:** Yes

**Description:** Multi Melta cost should be 25 (currently 20), missile launcher should cost 20 (currently 15).

**Comment by Mad-Spy** [comment]
As you haven't actually said what unit this is on, I'm going to assume it's a duplicate of #8454
