### ISSUE TITLE
Blood Angels Firestirke Servo Turret

### ISSUE THREAD

**Issue by rktrevor** [BSData/wh40k-9e#8594]
**File/Catalogue: ** Imperium - Adeptus Astartes - Blood Angels*

**BattleScribe version:** 2.03.

**Platform:** Linux

**Dropbox:** No

**Description:**  The Firestrike Servo Turret is not listed in the Blood Angels Data File under the Heavy Support Section.

**Comment by Mad-Spy** [comment]
Consolidated into #8515
