### ISSUE TITLE
Blood Angels - Sanguinary Priest missing "Hero of the Chapter" stratagem

### ISSUE THREAD

**Issue by FloYoung** [BSData/wh40k-9e#8598]
**File/Catalogue:** Imperium - Adeptus Astartes - Blood Angels

**BattleScribe version:** 2.03.

**Platform:** Mac

**Dropbox:** No

**Description:** Sanguinary Priest missing "Hero of the Chapter" stratagem

**Comment by Mad-Spy** [comment]
Duplicate of #8515
