### ISSUE TITLE
Eradicators - Multi Melta cost to High

### ISSUE THREAD

**Issue by Charlesfox9999** [BSData/wh40k-9e#8599]
**File/Catalogue:**  Space Marine Codex

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux ANdroid & Windows

**Dropbox:** Yes/No

**Description:** Detailed issue description. The program has the multi melta eradicator at 60 points.  It should be 50 points.  40 points for the base eradicator, then +5 Heavy Melta Rifle OR + 10 for Multi Melta, which means if you add a Multi melta, the person should be 50 total, not 60.  Thank you.

**Comment by acebaur** [comment]
Already fixed on master
