### ISSUE TITLE
Necrons Keywords Missing

### ISSUE THREAD

**Issue by cronsOP125** [BSData/wh40k-9e#86]
**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** Yes/No

**Description:** Detailed issue description.
None of the Necrons unit entries have Keywords i.e. Infantry, Dynasty, Fly, etc.

**Comment by Kohato** [comment]
Known Bug.  Issue with BS, not data.  Keywords are in, they do not display yet.
