### ISSUE TITLE
Captain on Bike - Pistol war gear options

### ISSUE THREAD

**Issue by Charlesfox9999** [BSData/wh40k-9e#8600]
**File/Catalogue:**  Space Marines

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux All

**Dropbox:** Yes/No

**Description:** Detailed issue description. Captain on Bike should have access under pistols to hand flamer for 5 points, currently that is not an option.

**Comment by acebaur** [comment]
That option is only available for BA and DW. Working as intended
