### ISSUE TITLE
Space Marines - Heavy Intercessor Heavy Bolter is 15 points instead of 10

### ISSUE THREAD

**Issue by Zolt01** [BSData/wh40k-9e#8602]
**File/Catalogue:** Imperium - Adeptus Astartes - Ultramarines 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Heavy Intercessors have the heavy bolter listed at 15 points, when it's 10 points in the codex.

**Comment by acebaur** [comment]
Fixed on the master
