### ISSUE TITLE
Space Marines - Ven Dread and Cpt in Term Armour issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8610]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 9.01.01

**Platform:** Android

**Dropbox:** No

**Description:** Venerable Dreadnought (Space Wolves v160) - Heavy Weapon and Arm Weapon do not have the None Options. Causes clashing issue when selecting Fenrisian Axe & Shield

Captain in Terminator Armour - When selecting weapons, if a Storm Shield is selected and you aren't using a Thunder Hammer or Power Fist, you cannot select another Melee Weapon. Becomes problem when substituting Wolf Lord in Cataphractii Terminator Armour (Power Sword/Relic Blade and Storm Shield)

**Comment by Mad-Spy** [comment]
Ven Dread issue is fixed
