### ISSUE TITLE
Imperium - Dark Angels: Validation error when adding relics to Captain

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8611]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** I am building a Dark Angels army.
Vanguard detachment
Added in a Captain in Terminator Armor as my Warlord
When I add a relic to him, it gives me an error "Too many selections of Relic (maximum 0)"
I should be able to give 1 free relic to the army

**Comment by Thairne** [comment]
Cannot reproduce on current master.

**Comment by FarseerVeraenthis** [comment]
Cannot reproduce on Android with current released data.
