### ISSUE TITLE
Aeldari - Drukhari: Drukhari WLTs not unlocked for Warlord when Roster has Drukhari-based Ynnari detachment.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8615]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Only "Warload (BRB)" traits are availeble for drukhari warlord, when other drukhari detachment as ynnari is in the same rooster

**Comment by FarseerVeraenthis** [comment]
it was looking at Roster rather than Force for validation.
