### ISSUE TITLE
Aeldari - Ynnari, Psychic power validation on Android client fails in non-Ynnari detachments

### ISSUE THREAD

**Issue by KalChoedan** [BSData/wh40k-9e#8618]
**File/Catalogue:** Aeldari - Drukhari v84, Aeldari - Craftworlds v114, Aeldari - Harlequins v49.

**BattleScribe version:** 2.03.25.338

**Platform:** Android

**Dropbox:** No

**Description:** Validation fails for psychic powers for Ynnari HQs in non-Ynnari detachments. The psychic power selector does not display for the unit when a non-Ynnari subfaction is chosen.

Fault only verified on the Android client; N.B. fault does not occur on the Windows client. Untested on iOS.

**Comment by FarseerVeraenthis** [comment]
Closed, ref #8577 should be in the next release!
