### ISSUE TITLE
Librarians error with Tome of Malcador

### ISSUE THREAD

**Issue by ATR3US** [BSData/wh40k-9e#8619]
**File/Catalogue:** Raven guard

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** When using Tome of Malcador relic and selecting an adicional power from a different discipline an error appears saying “one too many selections from that discipline”

**Comment by Technoblazed** [comment]
Which librarian?

It's also worth noting that you can only select an additional power from the powers you have access to, which depends on the librarian being used.

**Comment by acebaur** [comment]
You cannot select powers from more than one discipline

Edit: unless you have the tome of velcona

**Comment by ATR3US** [comment]
> You cannot select powers from more than one discipline

With the relic Tome of Malcador you can, that’s why I’m saying it is giving an error 
![C124D9B0-939F-4C02-B1EB-27E71DEFF5FA](https://user-images.githubusercontent.com/45937376/97886165-8dcf4300-1d28-11eb-9472-7f8fa0a558fb.jpeg)

**Comment by ATR3US** [comment]
> Which librarian?
> 
> It's also worth noting that you can only select an additional power from the powers you have access to, which depends on the librarian being used.

It happens with all the librarians when selecting the additional power from another discipline(because the relic allows you to do so)

**Comment by Technoblazed** [comment]
The relics allows you to select an extra power from what they have access to, they either have access to the Umbramancy discipline OR the Librarius/Obscuration disciplines. Page 62 states that they can know all of their powers from Umbramancy *instead of* Librarius/Obscuration

**Comment by ATR3US** [comment]
> The relics allows you to select an extra power from what they have access to, they either have access to the Umbramancy discipline OR the Librarius/Obscuration disciplines. Page 62 states that they can know all of their powers from Umbramancy _instead of_ Librarius/Obscuration

That is exactly what the relic is for, it allows to chose an additional power from any discipline he has access to, which are both but you only select from one, but access is for both
