### ISSUE TITLE
Black Templars - Ancient in Terminator Armor is Uncategorised

### ISSUE THREAD

**Issue by bbobson7** [BSData/wh40k-9e#8623]
**File/Catalogue:** Imperium - Adeptus Astartes - Black Templars v27

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** Yes

**Description:** Ancient in Terminator Armor is Uncategorized in Black Templars

**Comment by Dunamis55** [comment]
Consolidated into #8753
