### ISSUE TITLE
-Deathwatch- Phobos librarian - too many smites?

### ISSUE THREAD

**Issue by CrispyXenos** [BSData/wh40k-9e#8624]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
![image](https://user-images.githubusercontent.com/73856128/97921375-c6841200-1d52-11eb-90a8-1f6f58b3d0d6.png)

**Comment by Technoblazed** [comment]
Fixing on dev branch.
