### ISSUE TITLE
Imperium - Space Wolves: Add Successor options to catalogue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8626]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** According to the current Space Marines Codex, Space Wolves are able to have successor chapters. Using this option is currently not possible.

**Comment by Mad-Spy** [comment]
Fixed in next release.
