### ISSUE TITLE
Deathwatch Kill Team model minimums are set/applied incorrectly

### ISSUE THREAD

**Issue by jaronow** [BSData/wh40k-9e#8629]
**File/Catalogue:** Imperium - Deathwatch.cat

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** Constraints around Indomitor kill team composition in Deathwatch armies don't handle heavy intercessors with executor or hellstorm bolt rifles correctly. Hellstorm-equipped models don't count toward the minimum of 4 non-sergeant heavy intercessors required (throws an error saying you need 4 more heavy intercessors with heavy bolt rifle) and executor-equipped models appear to count double toward that same minimum (if you have one, it says you need two more when you in fact need three more. When you have two, there's no error even though you need two more).

In addition, for all four kill team types the minimum number of models appears to be set to 4, when the actual minimum number of models in the squad is five (sergeant plus four base models).

![indomitor with hellstorms](https://user-images.githubusercontent.com/73862661/97938958-a135da80-1d37-11eb-92ad-0d2af09350c9.jpg)
![indomitor with two executors](https://user-images.githubusercontent.com/73862661/97938959-a1ce7100-1d37-11eb-8ab0-08c7c58ad118.jpg)
![indomitor with one executor](https://user-images.githubusercontent.com/73862661/97938960-a1ce7100-1d37-11eb-8a23-65a55493c05a.jpg)
![fortis with three total models](https://user-images.githubusercontent.com/73862661/97938961-a2670780-1d37-11eb-8c2a-38d974e9c672.jpg)

**Comment by Technoblazed** [comment]
Fixed in the supplement update.
