### ISSUE TITLE
Space Marines: Multiple issues

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#8630]
File/Catalogue: Space Marines
 
BattleScribe version: 2.03.

Platform: Windows/IOS

Dropbox: No

Description: 
- All Ironhail heavy stubbers and Icarus Ironhail heavy stubbers  are "Heavy 3" but should be "Heavy 4" 
- Icarus Ironhail heavy stubbers still have the old wording. They do not have the subtract 1 from hit rolls against all other targets anymore
- The Gladiator Lancer's Aquilon Optics rule is wrong. It should be "Each time this model makes an attack with a Lancer laser destroyer, add 1 to that attack's hit roll"
- On IOS, when selecting an Eradicator squad, it only adds the sergeant and one eradicator, but it should add two eradicators by default
- The Librarian in Phobos Armour has access to the Librarius and Obscuration Disciplines but based on the wording he only gets the Obscuration Discipline I believe
- The Hellblaster's "Assault Plasma Incinerator, Standard" is Assault 2 but should be Assault 3
- Smite is not appearing on the data sheets for any Librarians
- Tactical squad's Heavy bolter is 15 pts but should be 10 pts
- On Heavy Intercessor Squad data sheet, on the Executor heavy bolter's profile it says its AP is 2 but should be -2
- All litanies of battle need to be updated to match the current codex versions

**Comment by Dunamis55** [comment]
Consolidated into #8753
