### ISSUE TITLE
Codex Space Marines - Ultramarines Supplement (9th edition)

### ISSUE THREAD

**Issue by CaptainIdaho** [BSData/wh40k-9e#8631]
**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:** Ultramarines Honour Guard are flagged as Legends when the datasheet is otherwise in the Supplement. 

Terminator Captain cannot take a Relic Blade and Storm Shield, though this is an option available. 

Many thanks.

**Comment by Mad-Spy** [comment]
Both of these issues have already been reported and are being worked on.
