### ISSUE TITLE
Imperium - Space Marines - Blood Angels - Some issues

### ISSUE THREAD

**Issue by tjw007** [BSData/wh40k-9e#8632]
**File/Catalogue:** Warhammer 40,000 v9.1.0

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 

1.  All Chaplains (including named characters Astorath, Lemartes, Dreadnought, all armour variants, standard and Primaris marines) include an extra litany by default - "Invocation of Destruction".  This should be removed.

2.  When choosing Primaris Librarian and choosing the "Chapter Command: Chief Librarian" option, I do not get the option to choose an extra Librarius Discipline (when I add a third one, BS flags an error).  I have not tested this on other models.

3.  Choosing the "Armoury of Baal" stratagem does not allow me to add another relic to my Warlord (this was when I made my Primaris Librarian the Warlord, and chose "Reliquary of Gathalamor" and "Adamantine Mantle").  BS flags this as an error.

4.  There are no Invader ATV squad options in Fast Attack :'-(  We need to share the love with those poor Blood Angels

**Comment by acebaur** [comment]
2. All psychic powers must come from the same discipline

**Comment by tjw007** [comment]
Just realised these issues are already documented under #8515 .  Apologies for overlooking that report.  This can be closed as a duplicate I guess?

**Comment by tjw007** [comment]
> 
> 
>     1. All psychic powers must come from the same discipline

My mistake - I should have said I could not choose a third psychic power from the same discipline

**Comment by alphalas** [comment]
duplicate #8515
