### ISSUE TITLE
Imperium - Space Marines - Primaris Captain - Relic Shield

### ISSUE THREAD

**Issue by stsjpn** [BSData/wh40k-9e#8634]
File/Catalogue: Warhammer 40,000 v9.1.0
BattleScribe version: v2.03.21.166
Platform: Windows
Dropbox: No

Description:
The characteristics of Relic Shield is written as below on latest "Imperium - Space Marines.catz" file, but it's updated in new 9th Codex: Space Marines.
WRONG: "Each time the bearer suffers a mortal wound, roll a D6; on a 4+, that mortal wound is ignored. Add 1 to armour saving throws made for the bearer."
↓
CORRECT: "Add 1 to armour saving throws made for the bearer. In addition, each time the bearer would lose a wound as the result of a mortal wound, roll one D6: on a 4 +, that wound is not lost."

**Comment by acebaur** [comment]
That's literally the same wording

**Comment by stsjpn** [comment]
> That's literally the same wording

acebaur, I respect your opinion, although it's a clear modification to the explanation of the relic shield.
It might be literally same as a result, but I think it's worth updating.
Primaris Captain is the first model that comes in the datasheet section, many people would realize that it's outdated.
