### ISSUE TITLE
LibSM BA

### ISSUE THREAD

**Issue by alphalas** [BSData/wh40k-9e#8635]
Under the Captain and Lieutenant listings, Inferno Pistol and hand flamers are 5 points, but should be 0 points. Unlike Librarians, Chaplains and Techmarines (all of which work as intended), the codex does not give them an additional cost for Captains and Lieutenants.

**Comment by acebaur** [comment]
Isn't this fixed on master? Could have sworn I put a modifier in there for it

**Comment by alphalas** [comment]
idk it was reported in my bugreps
