### ISSUE TITLE
Land Speeders Weapons

### ISSUE THREAD

**Issue by lotlp** [BSData/wh40k-9e#8636]
**File/Catalogue:** Space Marines

**BattleScribe version:** 2.03.

**Platform:** Android/Windows

**Dropbox:** No

**Description:**

Land Speeders (regular, Firstborn ones) only have one weapon option. There should be the option to mount a second weapon.

**Comment by acebaur** [comment]
They are separate data sheets now. See land speeder Tornado and Typhoon
