### ISSUE TITLE
White Scars - Khan Spear +1S in latest FAQ

### ISSUE THREAD

**Issue by joarangoe** [BSData/wh40k-9e#8641]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Khan Spear for the Khan on Bike was updated from USER to +1 Strength on the latest WS FAQ.

**Comment by Dunamis55** [comment]
Consolidated into #8753
