### ISSUE TITLE
Heavy Bolters on Heavy Intercessors, and BA Sang priest and Librarian dreadnought

### ISSUE THREAD

**Issue by SoGrumpy** [BSData/wh40k-9e#8643]
**File/Catalogue:** Space Marines and Blood Angels

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:**
Space Marines
Heavy Bolters on Heavy Intercessor Squads are listed as 15 points currently, but should be 10.

Blood Angels
Sanguinary priests - cannot currently but should be able to choose Stratagem: Hero of the Chapter to take a warlord trait, currently bugged I believe.
Librarian Dreadnought -  as they have the LIBRARIAN keyword can be made into CHIEF LIBRARIAN, they currently do not have the option.

**Comment by alphalas** [comment]
All already fixed on master, will be in next release.

**Comment by SoGrumpy** [comment]
Fantastic,
Thanks for letting me know, and thanks for your work on this.
Cheers
