### ISSUE TITLE
Incorrect Transport text for Stormwolf

### ISSUE THREAD

**Issue by TobyWanBJ** [BSData/wh40k-9e#8645]
**File/Catalogue: Imperium - Adeptus Astartes - Space Wolves v160

**BattleScribe version:2.03.21

**Platform:** all

**Dropbox:** Yes

**Description: Transport  for the stormwolf should read "this model has a transport capacity of 16 SPACE WOLVES INFANTRY models. Each JUMP PACK, WULFEN or TERMINATOR model takes the space of two INFANTRY models and each CENTURION takes the space of three INFANTRY models. It cannot transport PRIMARIS models."
![Stormwolf](https://user-images.githubusercontent.com/8384219/98095116-0e558700-1e82-11eb-9eb9-81028a5820f0.PNG)

**Comment by Mad-Spy** [comment]
Fixed in next release.
