### ISSUE TITLE
Imperium - Blood Angels: Dante's Lord Regent rule not giving CP benefit.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8646]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** When Commander Dante is chosen as the Warlord, he gives 1 additional Command Point (which he doesn't as of now).

**Comment by Mad-Spy** [comment]
He's actually subtracting a PL in v203, rather than adding a CP?

**Comment by alphalas** [comment]
Yeah I forgot that the way we do CP is technically the same as points for some reason I thought it was opposite.
