### ISSUE TITLE
Imperium Dark Angels Deathwing Command Squad Cyclone Missile Launcher, Thunder Hammer

### ISSUE THREAD

**Issue by Milliway** [BSData/wh40k-9e#8647]
Imperium . Adaptus Astartes Dark Angels

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** Yes/No

**Description:** for the Elites Deathwing Command Squad i can equip everyone with Cyclone Missile Launcher, Thunder Hammer without complaint

and it will also complain when i select the appropriate melee weapon to go with it to achieve the correct point cost of 70

**Comment by Mad-Spy** [comment]
What version of the Dark Angels file are you using?

**Comment by Milliway** [comment]
![image](https://user-images.githubusercontent.com/73940971/98107779-4b7a4300-1e9b-11eb-8ac4-11b961d151b4.png)

**Comment by Mad-Spy** [comment]
The DW Command Squad has been completely reworked for the next release and this issue has been resolved.
