### ISSUE TITLE
Imperium Dark Angels Ravenwing Land Speeder Vengeance is Elite should be Fast Attack

### ISSUE THREAD

**Issue by Milliway** [BSData/wh40k-9e#8648]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** I realize there's confusion from the index where they put the elite symbol on the entry, however in the points section it's listed as fast attack and it's sold as fast attack on the gw store

was also fast attack in 8th

**Comment by Mad-Spy** [comment]
GW's instructions on how to read data sheets tell us that the data sheet determines the battlefield role, not the points section. Please contact GW to issue an errata for the Index.
