### ISSUE TITLE
Space Marines - Minor Issues

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#8649]
**File/Catalogue:** Space Marines

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 
- Smite is not appearing on the data sheets for any Librarians
- Tactical squad's Heavy bolter is 15 pts but should be 10 pts
- On Heavy Intercessor Squad data sheet, on the Executor heavy bolter's profile it says its AP is 2 but should be -2

**Comment by Mad-Spy** [comment]
Consolidated into #8630. Please add anything else you find into your other open issue, until it gets closed.

**Comment by RespectableJack** [comment]
Okay
