### ISSUE TITLE
[Anon] Bug report: Imperium - space marine chapter tactics 

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8655]
**File:** Imperium - Salamanders.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Founding Chapter Selection Rules first sentence currently states: When a unit with this tactic fires Overwatch or is chosen to shoot or fight with, you can re-roll a single hit roll and you can re-roll a single wound roll. Should be: Each time a unit with this tactic is selected to shoot or fight, you can re-roll one wound roll when resolving that unit's attacks.

**Comment by acebaur** [comment]
All chapter tactics need to be updated

**Comment by Dunamis55** [comment]
Consolidated into #8753
