### ISSUE TITLE
Imperium - Dark Angels - Warlord Traits missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8658]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Dark angels missing warlord traits for Deathwing, Ravenwing, and just the standard traits

**Comment by FarseerVeraenthis** [comment]
ensure you have a warlord selected.
