### ISSUE TITLE
Space Marines - Devastator Squad missing CORE keyword

### ISSUE THREAD

**Issue by Blandy84** [BSData/wh40k-9e#8661]
**File/Catalogue:** Imperium - Space Marines.cat

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** Yes

**Description:** The devastator squad is missing the CORE keyword

**Comment by Blandy84** [comment]
Thanks for the awesome work you do by the way!

**Comment by Dunamis55** [comment]
Consolidated into #8753
