### ISSUE TITLE
Imperium - Blood Angels: Additional Relic validation not working properly

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8664]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Captain on Bike is missing the Relic Blade option. 

When running 3 relics in a Strike Force, 1 should be free and then the next 2 should costs 1 CP each, adding up to 2 CP, not 3 CP as the current option stands in BS.

**Comment by Dunamis55** [comment]
1. A Captain on Bike isn't able to take a Relic Blade in the new codex, so this is working correctly
2. The Relics stratagem increases the maximum number of relics you can take by the amount of CP you spend, and you get 1 free with a Warlord. I tested this alongside the various Battle Sizes and everything seems to be working correctly with the Blood Angels catalogue.
