### ISSUE TITLE
Imperium - Blood Angels: Hero of the Chapter not working for Sanguinary Priest

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8665]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Sanguinary Priest doesn't have the Hero of the ~~Imperium~~ Chapter option to allow him to take a warlord trait. This needs to be added

**Comment by Mad-Spy** [comment]
Fixed for next release.
