### ISSUE TITLE
Warhammer 40,000: Some kind of loading problem?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8671]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Whenever I try to log in to my army lists for Space Wolves and Raven guard, it takes a long time to log in. And when ever I do finally get in, it'll eventually automatically log me out.

**Comment by Mad-Spy** [comment]
Do you mean it takes a long time to load? You don't "log in" to Battlescribe. This can happen on older devices.

Do you get any kind of error when you get "logged out"? Are you doing any particular action in the data set? Without actual details of the problem, it's impossible to even start looking at it.

**Comment by williamcaw** [comment]
recommend only loading one Space marines detachment at a time . "battlescribe issue"

**Comment by acebaur** [comment]
> recommend only loading one Space marines detachment at a time . "battlescribe issue"

That issue was fixed a long time ago

**Comment by williamcaw** [comment]
its back with the new data added in 9e. and im not the one that submitted this

**Comment by Mad-Spy** [comment]
No update from OP. Closing.
