### ISSUE TITLE
Space wolves don't have access to Indomitus bladeguard captain and no longer have Primaris Battle Leader on the HQ list

### ISSUE THREAD

**Issue by Triken34** [BSData/wh40k-9e#8673]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Mad-Spy** [comment]
1. Yes, they do. It's just a Captain now.
2. That datasheet no longer exists. It's a Primaris Lieutenant now.

Take a look at the Space Marines Codex again.
