### ISSUE TITLE
Imperium - Inquisition; Acolyte Thunder Hammer Cost incorrect

### ISSUE THREAD

**Issue by leckergano** [BSData/wh40k-9e#8674]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows&Andoid

**Dropbox:** No

**Description:** The cost for a thunderhammer on an acolyte is listed as 40pts instead of 16pts, as given from PA Pariah

**Comment by Technoblazed** [comment]
Per the MFM they're meant to be 15 points, but it's still broken regardless so I'll fix it.
