### ISSUE TITLE
Imperium - Space Marines: Combat shield has incorrect text 

### ISSUE THREAD

**Issue by ThePants999** [BSData/wh40k-9e#8677]
**File/Catalogue:** Imperium - Space Marines.cat

**Description:** Combat shields still have the old text of "A model with a combat shield has a 5+ invulnerable save." The new codex wording is "The bearer has a 5+ invulnerable save. In addition, add 1 to armour saving throws made for the bearer."

**Comment by Dunamis55** [comment]
Consolidated into #8753
