### ISSUE TITLE
Dark Angels Deathwing Terminator Sergeant still has 2 wounds

### ISSUE THREAD

**Issue by DudeChris33** [BSData/wh40k-9e#8685]
**File/Catalogue:** Adeptus Astartes- Dark Angels

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Dark Angels Deathwing Terminator Sergeant still has 2 wounds

**Comment by FarseerVeraenthis** [comment]
Seriously...?! I can't even... Ok I'll fix it - again!!!

**Comment by Dunamis55** [comment]
Fixed in latest data.
