### ISSUE TITLE
Chief Librarian Mephiston MIA

### ISSUE THREAD

**Issue by SashaOrlov** [BSData/wh40k-9e#8693]
**File/Catalogue:**  Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:** Chief Librarian Mephiston seems to be missing from the HQ choices in the current ver. (9.1.2, Blood Angels v204). Untested on other platforms.

Thanks for your hard work in correcting the previous bugs, keep it up!

**Comment by Technoblazed** [comment]
Select Blood Angels as your chapter under Chapter Selection in the config section at the top.
