### ISSUE TITLE
Imperium - Blood Angels: Heavy bolters in Tac squads have incorrect cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8696]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Tactical squads have heavy bolters listed as 15 points, per codex space marines they should be 10 points.

**Comment by Dunamis55** [comment]
Consolidated into #8753
