### ISSUE TITLE
First born infantry heavy weapons using vehicle points

### ISSUE THREAD

**Issue by Jonjacob34** [BSData/wh40k-9e#8699]
**File/Catalogue:** 
Space marine adeptus Astartes 

**BattleScribe version:** 2.03.

**Platform:** 
Android

**Dropbox:**
 no

**Description:** Detailed issue description.

It appears all first born infantry are using points costs from vehicles for heavy weapons.

Tactical 
Devastators 
Sternguard 
Company Veterans 
Scouts

**Comment by Dunamis55** [comment]
Consolidated into #8753
