### ISSUE TITLE
Aeldari - Windrider Shuriken Cannon Values

### ISSUE THREAD

**Issue by geologic9** [BSData/wh40k-9e#87]
**File/Catalogue:** Aeldari - Craftworlds

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Adding additional Windriders with Shuriken Cannons increments points value by 20pts rather than 32pts.

**Comment by Sourborn** [comment]
Dire Avengers and Dark Reaper points also don't increase correctly.

**Comment by FarseerVeraenthis** [comment]
Is this in a child force or a parent force? 
Child forces are slightly bugged at present, once you've added the models, try changing the weapon selection and see if the points update themselves.

**Comment by Sourborn** [comment]
Having trouble reproducing the issue with the same data as when I submitted it. I believe it was child force but everything seems to be working now. I'll fiddle with it a bit more to see if I can reproduce it.

**Comment by FarseerVeraenthis** [comment]
This is likely caused by the parent/child bug in BS...
