### ISSUE TITLE
Space Wolves thunderhammers and storm shields pts bug

### ISSUE THREAD

**Issue by Akaiyou** [BSData/wh40k-9e#8701]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
Thunderhammers on Thunderwolf mounted characters is 20 pts not 15. Stormshields on Thunderwolf Cavalry Pack Leader is 0 pts not 5.

**Comment by Mad-Spy** [comment]
Thunderhammers fixed.

Thunderwolf Cavalry Storm shield cost is 5pts for all models in the unit.
