### ISSUE TITLE
Deathwatch: Multiple issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8704]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Deathwatch Veteran Bikers - if you add an Astartes Chainsword to an individual Veteran Biker, it adds the chainsword to all your bikers, even if they have a different weapon. When you try to remove it from the ones that don't need it, it removes it from all of them again including the one who you want to have it.

Deathwatch Reivers - giving the sergeant a bolt carbine leads to a validation error, even though it's a legitimate choice for him to have it even if his squad doesn't.

Deathwatch Terminator Captain - Combi bolter is listed as an option, even though it isn't, and Storm bolter is listed separately.

**Comment by Technoblazed** [comment]
> Deathwatch Veteran Bikers - if you add an Astartes Chainsword to an individual Veteran Biker, it adds the chainsword to all your bikers, even if they have a different weapon. When you try to remove it from the ones that don't need it, it removes it from all of them again including the one who you want to have it.

Resolved.

> Deathwatch Reivers - giving the sergeant a bolt carbine leads to a validation error, even though it's a legitimate choice for him to have it even if his squad doesn't.

Incorrect assumption, you would need to replace ALL combat knifes in the unit, then the sergeant can gain the combat knife back afterwards.

> Deathwatch Terminator Captain - Combi bolter is listed as an option, even though it isn't, and Storm bolter is listed separately.

Incorrect assumption, the captain can replace his storm bolter with a combi-bolter.
