### ISSUE TITLE
Imperium - Ultramarines: Master of Sanctity applying to all Chaplains in detachment

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8708]
**File:** Imperium - Ultramarines.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When the master of sanctaty is selected and an other chaplain is in the same detachment he benefits from the strat. “Selecting an extra litany is not seen as a list fail” Which i think it’s not supposed to do

**Comment by Dunamis55** [comment]
Consolidated into #8753
