### ISSUE TITLE
Imperium - Grey Knights: Multiple issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8717]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** - While updating And they shall know no fear fot adeptus astartes (autopass attrition), grey knights' was changed as well. But grey knights still have the old one to "reroll failed morale tests".
- grey knights' rhino missing smoke launchers ability, should have it. 
- vortimer pattern razorback missing Masters of the warp ability, should have it.

**Comment by tekton** [comment]
The Vortimer pattern vehicles didn't make it to 9th Edition- they have been lost to the warp officially with IA and Legends
