### ISSUE TITLE
Imperium - Blood Angels: Tome of Malcador doesn't give extra power.

### ISSUE THREAD

**Issue by khinzaw** [BSData/wh40k-9e#8718]
When selecting the Tome of Malcador relic it doesn't seem to actually increase the cap on psychic powers and selecting an extra one will still prompt the error.

**Comment by Mad-Spy** [comment]
Please be more specific about your issue with the Tome. It appears to be working correctly.

**Comment by khinzaw** [comment]
> Please be more specific about your issue with the Tome. It appears to be working correctly.

A regular librarian knows 2 powers from the librarius discipline correct? Well the tome should be allowing me to take a third, but selecting a third triggers the "librarian has 1 too many selections from Disciplines (maximum 2)" error.

**Comment by acebaur** [comment]
Not replicating this. What chapter are you using? Also the terminator Sgt can't change is loadout, so that is working as intended.

**Comment by khinzaw** [comment]
> Not replicating this. What chapter are you using? Also the terminator Sgt can't change is loadout, so that is working as intended.

I am using Blood Angels. Here is an image link: https://i.gyazo.com/2e2a736036f462abf2dc04da959b0d66.png

Also, whoops I guess I missed the wording was specifically replace power fists.

**Comment by Mad-Spy** [comment]
It's a Blood Angels specific issue. Reassigned.

**Comment by Dunamis55** [comment]
Consolidated into #8753
