### ISSUE TITLE
space marines: wrong costs for various masters of the chapter

### ISSUE THREAD

**Issue by THusky1** [BSData/wh40k-9e#8722]
every 'master of the chapter' except captain > chapter master is 10 points more expensive than it should be.
chaplain: 35 should be 25
techmarine: 30 should be 20
librarian: 35 should be 25
apothecary: 25 should be 15
ancient: 30 should be 20
company champion: 25 should be 15

**Comment by acebaur** [comment]
Look at the points in the back of the book

**Comment by THusky1** [comment]
look at the points on page 98.

**Comment by alphalas** [comment]
@THusky1 since there are two points values printed in the book, it needs an FAQ. We are going with the more expensive option just in case it is FAQ’d to use that value. If it is FAQ’d to use the lower points value, we will use it when that happens.

**Comment by THusky1** [comment]
told ya so
