### ISSUE TITLE
space marines: relic requirement not validated

### ISSUE THREAD

**Issue by THusky1** [BSData/wh40k-9e#8724]
if youre running a successor chapter, the only way to get a chapter relic is to take a strat (which has different names depending on chapter) to allow this - however, this strat only permits a single chapter relic to be taken, using an available relic "slot" whether it be your free one for having a warlord, or one-or-more from the "relics of the chapter" strat: however, this strat does NOT give you the relic.

Currently, list validation does not flag this if you have taken the chapter relic as a successor - effectively treats it like giving you a free extra relic.

**Comment by Mad-Spy** [comment]
Which Chapter are you using?
