### ISSUE TITLE
Space wolves - Company Heroes interactions

### ISSUE THREAD

**Issue by THusky1** [BSData/wh40k-9e#8725]
The various lieutenants from codex space marines have an ability called “Company Heroes” that allows you to take a second lieutenant in the same HQ slot.

The space wolf index &/or supplement added 2 more lieutenants - the wolf guard battle leader in terminator armor, and wolf guard battle leader on thunder wolf - both of which have the lieutenant keyword, and therefor qualify to be taken in the same HQ slot as a firstborn, primaris, phobos or reiver lieutenant even though they lack the company of heroes ability themselves.

You need to modify the lieutenant entry for space wolves to reflect this.

**Comment by Mad-Spy** [comment]
Models are only subject to rules on their datasheets or army-wide rules. Thus, the two Wolf Guard Battle Leaders are _not_ subject to Company Heroes.

**Comment by THusky1** [comment]
Company of heroes explicitly affects other lieutenants - there is no requirement that the other lieutenant has company of heroes.

The only conditions are clear - battle forged, same detachment, lieutenant (keyword).

**Comment by Mad-Spy** [comment]
OK, I agree that you can take a WGBL and a Codex SM Lieutenant. What you cannot do at present is have two WGBLs in a single FOC slot, because they themselves do not have the Company Heroes ability.

I suggest you contact GW and get them to clarify the situation.

**Comment by THusky1** [comment]
That’s correct as far as I can tell. I’m not sure what clarification is needed - unless it gets FAQ’d away, it seems legal for now and should be reflected in the unit entry.

**Comment by Mad-Spy** [comment]
One could reasonably assume that all LIEUTENANTS should have the Company Heroes ability, but it has been mistakenly left off of the Space Wolves datasheets. Anyway, I'll be implementing it so you can only have one or the other for now.
