### ISSUE TITLE
Vanguard veterans have heavy thunder hammers for free

### ISSUE THREAD

**Issue by GuillermoDiazGarcia** [BSData/wh40k-9e#8730]
**File/Catalogue:** Deathwatch

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** Yes

**Description:**
Vanguard veterans have no cost on the heavy thunder hammer. They're correctly costed in the Proteus killteam, but not in the separate unit

**Comment by Technoblazed** [comment]
Space marine lib issue, they’re fine in the DW specific kill team.

**Comment by Dunamis55** [comment]
Consolidated into #8753
