### ISSUE TITLE
Deathwatch Terminators with Cyclone Launcher cannot swap Storm Bolter for Hammer

### ISSUE THREAD

**Issue by bluntpencil2001** [BSData/wh40k-9e#8731]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** 
Based on the rules from the Core Rulebook, you are able to take upgrades in any order you like - with the Deathwatch Terminator, that means if you take a Cyclone Launcher and Storm Bolter, you should then be able to swap the Storm Bolter and Power Fist for a Thunder Hammer and Storm Shield. As it stands, this can't be done with the Battlescribe App.

**Comment by Technoblazed** [comment]
Click the single Cyclone Missile Launcher at the top, then select the TH+SS in the melee option.
