### ISSUE TITLE
KX139 Ta'unar Supremacy Armour data problem

### ISSUE THREAD

**Issue by Rob9898989898** [BSData/wh40k-9e#8733]
**File/Catalogue:** data, Tau empire 

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:** The data in the KX139 Ta'unar Supremacy Armour is messed up. There is a random gun called 
The heavy rail cannon that isn't supposed to be there no matter how you load it out. (This is different from the heavy rail cannons array which you can select). The toughness and weapon skill do not show as well.
How it looks on my galaxy s10
(https://user-images.githubusercontent.com/9154822/98599376-7b618600-22a1-11eb-8f44-83f5714e01e8.jpg)

**Comment by Technoblazed** [comment]
Fixed in https://github.com/BSData/wh40k/commit/8cea7c1.

**Comment by Rob9898989898** [comment]
Did that fix remove the random extra gun placed in there? @Technoblazed

**Comment by Technoblazed** [comment]
Yes
