### ISSUE TITLE
Chapter command point values

### ISSUE THREAD

**Issue by ATR3US** [BSData/wh40k-9e#8734]
**File/Catalogue:** space marines

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** As per the FaQ for space marines codex, chapter command point values should be the ones on page 98, not the ones on page 202

**Comment by Technoblazed** [comment]
Duplicate of https://github.com/BSData/wh40k/issues/8727
