### ISSUE TITLE
Space Wolves missing relics

### ISSUE THREAD

**Issue by Rattleme** [BSData/wh40k-9e#8735]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
The Wulfen stone is not showing up listed among the Relics of the fang and also generic wolf lords and battle leaders do not have access to the Mountain Breaker Helm.

**Comment by Mad-Spy** [comment]
Already fixed for next release.
