### ISSUE TITLE
Imperium - Blood Angels: Furioso PL cost and weapon options incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8737]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Furioso Dreadnoughts should be Power Level 7 not Power Level 8. Also, they should not be able to take a meltagun as a fist weapon when they take a frag cannon since they trade the frag cannon for the furioso fist with the meltagun now. The storm bolter can be traded for a heavy flamer but not a meltagun.

**Comment by Dunamis55** [comment]
Consolidated into #8753
