### ISSUE TITLE
Imperial Knights: Moirax weapon option issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8738]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Knight Moirax Weapon Selection is bugged, siege claw w/ rad cleanser is permanently selected, i cant switch to two graviton pulsars

**Comment by williamcaw** [comment]
you select the item off of the selectable weapon on the profile you remove it your self #7905

**Comment by williamcaw** [comment]
it is some what hard to do in ios or android

**Comment by DrTobogganMD** [comment]
It is a bug and not intended to work this way. It will be fixed.
