### ISSUE TITLE
Necrons: Silent King missing NOBLE keyword.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8739]
**File:** Necrons.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The silent King doesn't have the noble keyword on its profile. 
We should see under keyword the noble keyword.

**Comment by DrTobogganMD** [comment]
Yes he does. It's under Szerekh, because the menhirs do not have it.
