### ISSUE TITLE
Dark Angel : Deathwing Apothecary taking a elite slot when a Deathwing command squad is added.

### ISSUE THREAD

**Issue by Pycnomerus** [BSData/wh40k-9e#8741]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** iOS

**Dropbox:** No

**Description:** when a Deathwing apothecary is added to an elite slot, and a Deathwing command squad is already there. the apothercary doesn't count as free.

**Comment by Mad-Spy** [comment]
You need to add the Apothecary from the "No Force Org Slot" group, not Elites. This is how almost all units which don't take up a slot are implemented in the data.
