### ISSUE TITLE
Space Marines - Consolidated bug list

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#8753]
**File/Catalogue:** Various Space Marines

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:**

**_Shared_**
- [x] Drop Pod has incorrect text in its Drop Pod Assault ability and the full text should read as: “This transport must start the battle set up high in the skies (see Death From Above, page 125) but neither it, nor any units embarked within it, are counted towards any limits that the mission you are playing places on the maximum number of Reinforcements units you can have in your army. This transport can be set up in the Reinforcements step of your first, second or third Movement phase, regardless of any mission rules. Any units embarked within this transport must immediately disembark after it has been set up on the battlefield, and they must set up more than 9" away from any enemy models. After this transport has been set up on the battlefield, no units can embark within it.”
- [x] Heavy bolter is currently 15 points, but should be 10 points for:
1. Tactical Squad > Space Marine w/ Heavy Weapon
1. Devastator Squad > Space Marine w/ Heavy Weapon
1. Scout Squad > Scout w/Heavy Weapon
1. Sternguard Veteran Squad > Space Marine Veteran w/Heavy Weapon
1. Company Veterans > Space Marine Veteran
- [x] Lascannon is currently 20 points, but should be 15 points for:
1. Tactical Squad > Space Marine w/ Heavy Weapon
1. Devastator Squad > Space Marine w/ Heavy Weapon
1. Sternguard Veteran Squad > Space Marine Veteran w/Heavy Weapon
- [x] Missile launcher is currently 20 points, but should be 15 points for:
1. Tactical Squad > Space Marine w/ Heavy Weapon
1. Devastator Squad > Space Marine w/ Heavy Weapon
1. Scout Squad > Scout w/Heavy Weapon
1. Sternguard Veteran Squad > Space Marine Veteran w/Heavy Weapon
- [x] Combat Shield has incorrect ability text and should read as: “The bearer has a 5+ invulnerable save. In addition, add 1 to armour saving throws made for the bearer.” for:
1. Company Champion
1. Company Veterans > Space Marine Veteran
1. Company Veterans > Veteran Sergeant
1. Assault Squad > Space Marine Sergeant
- [x] Devastator Squad is missing the CORE keyword
- [x] Lieutenants can take multiples of lightning claw (pair), but this should be a single option
- [x] Several weapons currently have the Type characteristic of Heavy 3, but should be Heavy 4:
1. Ironhail heavy stubber
1. Icarus Ironhail heavy stubber
- [x] Icarus Ironhail heavy stubber should have the ability text: “Each time an attack is made with this weapon against an AIRCRAFT unit, add 1 to that attack’s hit roll.”
- [x] Gladiator Lancer’s Aquilon Optics ability text is incorrect and should read: “Each time this model makes an attack with a Lancer laser destroyer, add 1 to that attack’s hit roll.”
- [x] Smite is not listed for:
1. Librarian
1. Librarian in Terminator Armour
1. Librarian on Bike [Legends]
- [x] Executor heavy bolter has an AP characteristic of 2, but should be -2
- [x] Litany of Faith (Aura) has uncapitalised keywords and typos, and should read as: “If this litany is inspiring, then while a friendly <CHAPTER> CORE or <CHAPTER> CHARACTER unit is within 6" of this PRIEST, each time a model that unit would lose a wound as the result of a mortal wound, roll one D6: on a 5+, that wound is not lost.”
- [x] Catechism of Fire has uncapitalised keywords and the first sentence should read as: “If this litany is inspiring, select one friendly <CHAPTER> CORE or <CHAPTER> CHARACTER unit is within 6" of this PRIEST.”
- [x] Exhortation of Rage has uncapitalised keywords and typos, and the first sentence should read as: “If this litany is inspiring, select one friendly <CHAPTER> CORE or <CHAPTER> CHARACTER unit within 6" of this PRIEST.”
- [x] Mantra of Strength has uncapitalised keywords, and should read as:
“If this litany is inspiring:
 - Add 1 to this PRIEST's Attacks and Strength characteristics.
 - Add 1 to the Damage characteristic of melee weapons this PRIEST is equipped with.”
- [x] Recitation of Focus has uncapitalised keywords and typos, and the first sentence should read as: “If this litany is inspiring, select one friendly <CHAPTER> CORE or <CHAPTER> CHARACTER unit within 6" of this PRIEST.”
- [x] Canticle of Hate (Aura) has uncapitalised keywords and typos, and the first sentence should read as: “If this litany is inspiring, then while a friendly <CHAPTER> CORE or <CHAPTER> CHARACTER unit within 6" of this PRIEST:”
- [x] Scout Heavy weapons should max 1 in Parent.

**_Black Templars_**
- [x] Ancient in Terminator Armour is list under Uncategorised

**_Deathwatch / SMLIB_**
- [x] Vanguard Veterans > Space Marine Veteran’s heavy thunder hammer currently costs 0 points, but should be 15 points
- [x] Land Speeders are unavailable to be taken

**_Salamanders_**
- [x] **Chapter Selection** > Salamanders’ Forged in Battle ability has incorrect text and should read as:
“Each time a unit with this tactic is selected to shoot or fight, you can re-roll one wound roll when resolving that unit's attacks.
Each time an attack with an Armour Penetration characteristic of -1 is allocated to a model with this tactic, that attack has an Armour Penetration characteristic of 0 instead.”

**_Ultramarines_**
- [x] Marneus Calgar [Legends] has the MK X GRAVIS and PRIMARIS key words, but should have the TERMINATOR keyword
- [x] Several units have the Adept of the Codex ability, even when not the Warlord:
1. Marneus Calgar
1. Marneus Calgar [Legends]
- [x] Marneus Calgar [Legends] should have the Teleport Strike ability: “During deployment, you can set up this model in a teleportarium chamber instead of setting it up on the battlefield. If you do, at the end of one of your Movement phases you can set up this model anywhere on the battlefield that is more than 9" away from any enemy models.”
- [x] Marneus Calgar [Legends] should have a relic blade equipped
- [x] Marneus Calgar [Legends] currently has a M characteristic of 6”, but should be 5”
- [x] Marneus Calgar [Legends] currently has a T characteristic of 5, but should be 4
- [x] Taking Chapter Command: Master of Sanctity on one Chaplain increases the maximum litanies of all Chaplains in the list to 2 instead of just that one
- [x] Chapter Selection > Ultramarines’ Codex Discipline ability has incorrect text and should read as:
“Add 1 to the Leadership characteristic of models with this tactic.
Units with this tactic are eligible to shoot in a turn in which they Fell Back, but if they do, then until the end of the turn, each time a model in that unit makes a ranged attack, subtract 1 from that attack’s hit roll.”
- [x] Marneus Calgar’s Chapter Master ability has incorrect text and should read as: “In your Command phase, select one friendly ULTRAMARINES CORE or ULTRAMARINES CHARACTER unit within 6" of this model. Until the start of your next Command phase, each time a model in that unit makes an attack, you can re-roll the hit roll.”
- [x] Standard of Macragge Inviolate’s ability text is missing text and the first bullet point should read as: “Unshakable Pride (Aura): While a friendly ULTRAMARINES CORE unit is within 6" of the bearer, add 1 to the Attacks characteristic of models in that unit.”
- [x] Special Issue Wargear profiles need to be updated.

**_White Scars_**
- [x] Ephrael Stern and Kyganil of the Bloody Tears are showing as Uncategorised
- [x] When a Captain and Veteran Squad are added to the list, the Company Champion is not listed as a No Force Org slot. Instead, two Company Champions show in the list of available Elites
- [x] Firestrike Servo-Turret is unavailable to be taken
- [x] Khan on Bike’s Khan’s spear currently has a Strength characteristic of User, but should be +1

**Comment by zeoevil** [comment]
Add Death Company Jet Packs should cost 3 points each instead of 2 points each to Blood Angels list. This was posted last week in another bug report, but got overlooked when that issue was closed.

**Comment by alphalas** [comment]
@zeoevil thats why we say post new bugreps instead of commenting

**Comment by khinzaw** [comment]
For the Blood Angels Tome of Malcador bug, if you need to fix it per unit, you should also include the Primaris Librarian and Librarian Dreadnought. Probably with any other librarian bug too.
