### ISSUE TITLE
Adeptus Mechanicus Secutarii Hoplites Minimum Unit Size Issue

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-9e#8755]
**File/Catalogue:** Imperium - Adeptus Mechanicus

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** The minimum unit size of the Secutarii Hoplites is listed in BattleScribe as five (one alpha with four hoplites), however in the rules, the minimum unit size is currently ten (one alpha and nine hoplites). The maximum unit size of twenty is correct. Thank you for this wonderful data that you maintain, and thank you for your help in this matter.

**Comment by BrandonNoble** [comment]
New compendium makes the minimum unit size 4 and 1 alpha. 

That being said, the peltasts are wrong. They are still at 9 and 1, and they were updated to be 4 and 1 as well in the new compendium. 

Edit: also, the hoplites points are wrong. It's 10pts/model, not 12. It's never been 12.

**Comment by ghost** [comment]
Ah apologies and thank you-I will close the issue :)
