### ISSUE TITLE
Imperium - Dark Angels: Relics

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-9e#8756]
**File/Catalogue:** Dark Angels v180

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:**
- Not all relics are being counted towards the maximum number per army.
- Ravenwing Talonmaster is a VEHICLE, and therefore should not have access to codex relics.

**Comment by FarseerVeraenthis** [comment]
not to be difficult, but which ones are not working properly...??

**Comment by GenWilhelm** [comment]
All of the codex relics and chapter command relics (chapter ancient, chapter champion, etc.).

**Comment by FarseerVeraenthis** [comment]
righto, I've obviously not pulled them into the CAT properly then... I'll have to look at how relic validation is performed in the other CAT's and figure it out from there...
