### ISSUE TITLE
Wrong Tau entries afte Imperial Armor

### ISSUE THREAD

**Issue by Fuleng** [BSData/wh40k-9e#8757]
**File/Catalogue:** 

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** 
a) XV107 R'varna is wrongly placed in fast attack instead of heavy support. 
b) Discontinued Units in the new imperial armor still show up

**Comment by williamcaw** [comment]
was not in last update 9.1.2 hopefully its in next release

**Comment by Technoblazed** [comment]
- The r'varna is no longer heavy support, it is fast attack.
- The "Discontinued" units are now legends and will be appropriately marked in the next version.
