### ISSUE TITLE
Battle Size Options

### ISSUE THREAD

**Issue by DudeChris33** [BSData/wh40k-9e#8758]
**File/Catalogue:** Warhammer 40k 9th Edition v170

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Could another battle size option be added for a custom battle size where you can input how many CP you are given? I would like this for those of us that play 6k and 10k points and don't want the error notification that we have 3 too many choices of battle size.

**Comment by DrTobogganMD** [comment]
It is not possible for us to allow an open ended value input in Battlescribe. Using something like an incrementor works well up until about 10, at that point Battlescribe starts to heavily disagree. We are discussing adding a 3000+ option that grants 0 CP so you can track the additional CP on your own.

**Comment by DrTobogganMD** [comment]
![image](https://user-images.githubusercontent.com/16939161/99158322-13db7a00-2697-11eb-9bec-39f423d3a848.png)
After testing some things, it seems 100 entries of "CP" does not crash BS on PC. 

Be aware that this very well may be an issue when you get a large number of things added - but this should work for you.

**Comment by DrTobogganMD** [comment]
Closed in 4d3960b232ffdc211bd880d783285175eb58f6e6

**Comment by DudeChris33** [comment]
Thank you :)

**Comment by DudeChris33** [comment]
When will this be implemented?

**Comment by DudeChris33** [comment]
Thank you :)
