### ISSUE TITLE
Gametype restrictions

### ISSUE THREAD

**Issue by DudeChris33** [BSData/wh40k-9e#8759]
**File/Catalogue:** Warhammer 40k 9th Edition v170

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** When a person chooses Gametype: Matched Play it should disable the option for specialist detachments and any legends equipment right?

**Comment by acebaur** [comment]
Nope, both of those are legal in matched play

**Comment by DudeChris33** [comment]
Oh lol mb
