### ISSUE TITLE
Adeptus Mechanicus Forge World Units Issue - Secutarii Hoplites points cost and Secutarii Peltasts minimum unit size

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-9e#8763]
**File/Catalogue:** Adeptus Mechanicus

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** Adeptus Mechanicus Secutarii Hoplites are listed as 12 points per model, when they are in fact 10 points per model. Additionally, Secutarii Peltasts are listed with a minimum unit size of 10, when it is in fact 5. I have attached a photo from the Imperial Armour Compendium to confirm this, as well as a link to the same photo hosted on imgur in case either one fails. Thank you very much for your continued support and for your help.

https://imgur.com/gallery/oL2aDub

![admech FW points](https://user-images.githubusercontent.com/33130571/99013624-cd780500-2548-11eb-8709-e82c7289d677.jpeg)

**Comment by williamcaw** [comment]
was not in last update 9.1.2 hopefully its in next release
