### ISSUE TITLE
Tau: "The Eight" is still requiring a -3CP command benefit, despite this being removed in a previous FAQ of PSYCHIC AWAKENING: THE GREATER GOOD

### ISSUE THREAD

**Issue by Omnipotentia01** [BSData/wh40k-9e#8764]
**File/Catalogue:** Tau Empire

**BattleScribe version:** 2.03.

**Platform:** Windows,iOS,Android,Mac&Linux

**Dropbox:** No

**Description:** The FAQ includes;

*Page 46 – Including The Eight in your army
Change the second sentence to read:
‘If your army is Battle-forged, you can only include this
datasheet in a Super-heavy Auxiliary Detachment; if you do, you
cannot give any model in your army a Signature System.’

This was previously written as;

*Page 46 – Including The Eight in your army
‘If your army is Battle-forged, you can only include this datasheet in a Super-heavy Auxiliary Detachment; if you do the command Benefits of that Detachment are changed to "-3 Command Points", and you cannot give any model in your army a Signature System.’

When adding 'The Eight' to a Super Heavy-Auxiliary Detachment in a Tau force, there is validation forcing you to include the Command Benefit, despite it no longer being required.

**Comment by DrTobogganMD** [comment]
SH Aux costs 3CP to take. Please review your Core Rulebook.

**Comment by Omnipotentia01** [comment]
Please re-open. As the description states, I'm not referring to the Detachment Cost (which is also 3CP), I'm referring to the additional 3CP tax from "Command Benefits" which was a tax from eighth edition, that was removed in the above mentioned FAQ. 

As it stands currently, it costs 6CP to take "The Eight" on Battlescribe, which is incorrect per the quoted FAQ. 

https://www.warhammer-community.com/wp-content/uploads/2020/10/UAlvbFZ9OvsRpfqG.pdf

**Comment by DrTobogganMD** [comment]
![image](https://user-images.githubusercontent.com/16939161/99018441-b2dd6600-251f-11eb-82b3-22569777ca61.png)
Command Benefits was removed a while ago, are you on the most up to date data version for tau?

**Comment by Omnipotentia01** [comment]
I stand corrected. I used the option to update data and ticked the option to delete data first, but it was still flagging as an issue. I've just removed the repo and added it back and now the error is gone. 

I guess it was caching it despite using the option to delete data first! 

It would also explain why I couldn't see it after cloning on to my local to fix it myself. 😅

**Comment by DrTobogganMD** [comment]
Sadly that delete data box has been bugged for a while and the app dev has yet to fix it. We always suggest a full repo delete and re-dl (you can do this without losing lists).

**Comment by Omnipotentia01** [comment]
Yup, exactly what I did when I couldn't see the entry in T'au Empire.cat

In future, I'll make sure I do that before raise the issue! Thanks!
