### ISSUE TITLE
Imperium - Dark Angels: Captains

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-9e#8767]
**File/Catalogue:** Dark Angels v180

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** Some models have the MASTER category instead of CAPTAIN, which also means the Company Command rule is not being correctly applied to detachments with those models.

**Comment by FarseerVeraenthis** [comment]
you'll need to provide a list to track this down properly, but I've deleted the Master keyword from the CAT anyway just for good measure :smile: :+1:
