### ISSUE TITLE
Hellforged Fellblade

### ISSUE THREAD

**Issue by DudeChris33** [BSData/wh40k-9e#8770]
**File/Catalogue:** Warhammer 40k 9th Edition v170

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The Chaos Space Marine Hellforged Fellblade's damage table indicates that its second row has a BS of 5+ when it should be 4+ according to its datasheet. I do not know if this is also the case for the Death Guard and Thousand Sons versions.

**Comment by Technoblazed** [comment]
Your data is out of date, this is fixed in the latest release that will roll out at some point today.
