### ISSUE TITLE
Space wolves - lieutenants

### ISSUE THREAD

**Issue by THusky1** [BSData/wh40k-9e#8775]
Lieutenants unit isn’t counting the second lieutenant as a free HQ selection if it’s a terminator or thunder wolf rider.

When you fix this, I also recommend you code this unit entry to allow 0-1 of either terminator or thunder wolf rider per lieutenant unit entry.

**Comment by Technoblazed** [comment]
Neither of these characters have the `Company Heroes` rule which is required to have a second lieutenant in the NFO slot in the roster. Just having the `Lieutenant` keyword isn't good enough.

**Comment by THusky1** [comment]
They don’t have the company heroes ability, however if you also take a lieutenant who does, that lieutenants company of heroes ability allows you to take the terminator or thunder wolf rider as it keys off the lieutenant keyword which they do have.

**Comment by Technoblazed** [comment]
~~Turns out this was already changed, update your data :) ~~

https://github.com/bsdata/wh40k/issues/8725

Spy commented on your thread from the other day, looks like it's staying implemented how it is at the minute.

**Comment by THusky1** [comment]
I have a correction to this big report - turns out the actual bug is that the WGBL in terminator armor or riding thunder wolf gives a validation error even if taken solo; it gives a “too many HQ choices for this detachment” error, even if it’s the only lieutenant selection in the unit.

**Comment by THusky1** [comment]
I’ll submit a new bug report
