### ISSUE TITLE
Space wolves: thane of the retinue

### ISSUE THREAD

**Issue by THusky1** [BSData/wh40k-9e#8776]
This stratagem should allow any pack leader or wolf guard pack leader to take a special issue relic - however it only seems to be applying to a few eligible units, not all. It needs to apply to wolf guard pack leaders that have been added to other units, and thunder cavalry pack leaders (maybe others - I haven’t checked exhaustively)

**Comment by Mad-Spy** [comment]
You're right, I forgot the WG Pack Leaders and the Cavalry one. Can't find any others missing.
