### ISSUE TITLE
Imperium - Space Wolves: Storm Caller Warp charge incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8781]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** SW Wolf Guard Battle Leader On TW is missing from HQ slot.

**Comment by HaxoIronWolf** [comment]
Wolf Guard Battle Leader in Terminator Armour is also missing

Tempestas Dicipline: Storm caller details text still uses the old warp charge of 8 rather than the updated value of 6

**Comment by Mad-Spy** [comment]
Both of the Battle Leaders are "Lieutenants" and can therefore be taken as a choice in that "unit".
