### ISSUE TITLE
Chaos - Chaos Space Marines: Lord Arkos cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8784]
**File:** Chaos - FW Heretic Astartes.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Forgeworld legends update:
Lord arkos showing 115 pts. Should be 120 according to legends file on gw website.

**Comment by Mad-Spy** [comment]
Update your data. The cost is 120pts in the latest release.
