### ISSUE TITLE
Chaos - FW Heretic Astartes: Sicaran Battle Tank HB cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8785]
**File:** Chaos - FW Heretic Astartes.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Forgeworld legends update:
Chaos sicaran Battle tank. Cost is showing 180 which mistakenly counts the mandatory heavy bolter as upgrade instead of as "base gear". The book entry shows that the mandatory heavy bolter is included in the base cost of 165. Additional heavy bolter sponsons would be subject to the cost shown. This is consistent with 9th edition codex adeptus astartes pricing.

**Comment by Mad-Spy** [comment]
The heavy bolter has a cost in the points section, therefore it costs for all instances of it. There are no rules anywhere saying that default wargear is exempt from this rule. The costing is correct. If the Loyalist version has a different cost, that one is wrong.
