### ISSUE TITLE
Ork DEFF ROLLA BATTLE FORTRESS missing from legends ?

### ISSUE THREAD

**Issue by whitewolfmxc** [BSData/wh40k-9e#8787]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

Ork DEFF ROLLA BATTLE FORTRESS missing from legends ? its on the Legends sheet for FW 

if you are not sure what the original equipment it has by default (since they forgot to put that in) its the same as the old ver
http://wahapedia.ru/wh40k9ed/factions/orks/Dethrolla-Battle-Fortress

"A Dethrolla Battle Fortress is a single model equipped with a kannon, two zzap guns and a Dethrolla."

**Comment by Technoblazed** [comment]
Even while substituting the old default weapons in, there are still more weapons that can be replaced that are missing from the defaults, until it’s fixed and we know what the model actually has, it’s staying as open instead of just guessing what the model has.

**Comment by Technoblazed** [comment]
Fixed in next release.

**Comment by whitewolfmxc** [comment]
Humm not fixed in ver 9.1.8 ?

the Grot rigger rule and the wargear upgrades (like the zapp gun) is not correct ? i should be able to have 3 weapons of the same type

**Comment by Technoblazed** [comment]
@whitewolfmxc it's working fine?

**Comment by whitewolfmxc** [comment]
in Battlescribe 

""Grot Riggers | At the end of the turn, roll a D6. On a roll of 6, this model regains one lost wound.""

in FW legends (updated recently document)

"Grot Riggers: In your Command phase, this model regains up to 1 lost wound."


in battlescribe 

![image](https://user-images.githubusercontent.com/65846291/103182345-abaec380-48e5-11eb-9431-ed7f70079943.png)

it gives aleart for having 3 of the same main weapons (example zapp guns)


in FW legends  (updated recently document) , cleary says you can have a combinations of the 3 main weapons including 3 of the same type 

![image](https://user-images.githubusercontent.com/65846291/103182364-c2edb100-48e5-11eb-8681-b10d98dad04d.png)
