### ISSUE TITLE
SW - hero of the chapter strat & skyclaw gravguns cost

### ISSUE THREAD

**Issue by Wookalicious** [BSData/wh40k-9e#8788]
**File/Catalogue:** 

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** 
1. Space wolves characters have no option for taking hero of the chapter SM stratagem to allow more characters to take warlord traits. 

2. skyclaws gravgun option is pointed incorrectly they should be 5 not 10 as per the supplement points index. Thanks

**Comment by Mad-Spy** [comment]
1. Which specific characters? I thought I added it to all of them. Remember that named Characters can no longer use that stratagem.

**Comment by Mad-Spy** [comment]
No update from OP. Closing.
