### ISSUE TITLE
Imperium - Dark Angels - DW Terminator Points Cost Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8795]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** In the section DW Terminator Heavy Weapons: Assault Cannon, Plasma Cannon and Thunder Hammer must have a cost of 10 pts; Heavy Flamer must have a cost of 5 pts.

**Comment by FarseerVeraenthis** [comment]
update your data, I'm sure this is already fixed.

**Comment by marneuscalgar** [comment]
Updated right before this report...

**Comment by FarseerVeraenthis** [comment]
Thanks for the report, it was broken, then fixed, but apparently that fix didn't work as intended, so it broke, now it is working again :smile_cat: should be in the next release.

**Comment by marneuscalgar** [comment]
Thank you for the great work you constantly make!
