### ISSUE TITLE
Helbrute/Sonic Dreadnought missile launcher cost

### ISSUE THREAD

**Issue by kyleaoman** [BSData/wh40k-9e#8801]
**File/Catalogue:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Helbrute missile launcher should be 20 points, not 15 (per Munitorum Field Manual 2020). Also applies to Sonic Dreadnought.

**Comment by Mad-Spy** [comment]
Update your data. There is no "Sonic Dreadnought" entry any longer, and the points cost for the missile launcher is correct in the current release.
