### ISSUE TITLE
Lib - Space Marines: Terminator Captain lightning claw validation error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8803]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Captain in Terminator Armour: when two lightning Claws selected a warning reading 1 too many selections of Lightning Claws (maximum 1). Two Lightning Claws are Legal per Space Marine Codex, Roster Error warning should not appear.

**Comment by Mad-Spy** [comment]
Appears to have been fixed.
