### ISSUE TITLE
Lord Castellan Creed WL Trait and Tank Aces

### ISSUE THREAD

**Issue by DudeChris33** [BSData/wh40k-9e#8805]
**File/Catalogue:** Astra Militarum v294

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Taking Lord Castellan Creed's warlord trait does not count as taking a warlord trait for the purpose of getting na additional tank ace from not having one. Not a critical issue but just thought I should let y'all know.

**Comment by alphalas** [comment]
Rephrase your statement please

**Comment by DudeChris33** [comment]
Normally when you add a tank ace to a vehicle, it checks that you either a) have the tank ace stratagem added, or b) have a warlord without a warlord trait. When you add a second it checks for both, so you can only have 2 tank aces, assuming you have the stratagem and a warlord without a trait.

Because of how Creed's WL Trait is added I assume it was not marked as a warlord trait, so you are able to have 2 tank aces with Creed still having his trait.

Note that you cannot make him not have his trait and still be the warlord because he is a named character.

**Comment by DudeChris33** [comment]
[Uploading Roster Editor 2.03.21 - Imperial Guard Mechanised (Warhammer 40,000 9th Edition v172) 2020-11-22 17-05-26_Trim.mp4.zip…]()

**Comment by DudeChris33** [comment]
This is what I am talking about sorry for the confusion

**Comment by Technoblazed** [comment]
Fixed in next release.
