### ISSUE TITLE
Chaos Space Marines - Imperial Armour Compendium - Initial QA Pass

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#8810]
**File/Catalogue:** Chaos - Chaos Space Marines v153

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [x] Decimator’s Wound Track 1’s currently has a M characteristic of 8”, but should be 9”
- [x] Decimator’s Wound Track 3’s currently has a M characteristic of 6”, but should be 5”
- [x] Several units’ Explode ability currently affects units within D6”, but should be 6”:
1. Decimator
1. Blood Slaughterer
- [x] Hellforged plasma blaster currently has the supercharged profile above the standard profile, but it should be below the standard profile
- [x] Hellfire plasma carronade – standard currently has a Damage characteristic of 3, but should be 2
- [x] Blightreaper cannon currently has a Damage characteristic of 2, but should be 1
- [x] Dreadclaw Drop Pod’s transport ability has incorrect text. The first sentence is missing words and should read as: “This model has one of the following transport capacities:”
- [x] Dreadclaw Drop Pod’s thermal jets should be taken by default and not be able to be removed
- [x] Dreadclaw Drop Pod’s thermal jets can be taken multiple times, but should be only able to be equipped once
- [x] ~~Chaos Rapier Carrier is currently equipped with a boltgun, but shouldn’t be able to take it~~ This weapon is on its datasheet.
- [x] Quad heavy bolter currently has a Damage characteristic of 1, but should be 2
- [x] Twin Terrax volkite charger currently has ability text of “-“, but should be “Each time an attack is made with this weapon, an unmodified wound roll of 6 inflicts 1 mortal wound on the target in addition to any normal damage.”
- [x] Hell Talon’s infernal bomb has a typo in its ability text. The second sentence should read as: “Immediately after the bearer has moved, you can select one point on the battlefield the bearer moved across this phase.”
- [x] Twin hellstrike launcher’s ability text is currently “-“, but should be “Each time an attack is made with this weapon against an AIRCAFT unit, add 1 to that attack’s hit roll. Each time an attack made with this weapon is allocated to an AIRCRAFT model, that attack has a Damage characteristic of D3+3.”
- [x] Kharybdis storm launcher - Frag missile currently has an AP characteristic of 0, but should be -1
- [x] When a Decimator is armed with two Decimator claws with hellflamer, they currently cost 40 points each, but they should be 0 points each
- [x] Chaos Whirlwind Scorpius’ Scorpius multi-launcher is currently 40 points, but should be 0 points
- [x] Kytan Ravager is currently 430 points, but should be 440 points

**Comment by Chaosari** [comment]
Not sure if this has been noticed.  The Greater Brass Scorpion of Khorne is missing the Demolisher Canon in the datasheet
