### ISSUE TITLE
White Scars Korsarro Khan not displaying wlt with hero of the chapter. 

### ISSUE THREAD

**Issue by Alex-40k** [BSData/wh40k-9e#8814]
**File/Catalogue:** space marines white scars 

**BattleScribe version:** 2.03.

**Platform:** Android 

**Dropbox:** no

**Description:** When Korsarro Khan is selected as a warlord, his mandatory warlord trait is displayed, however when designating him as hero of the chapter his mandatory warlord trait does not display in the same manner.

**Comment by acebaur** [comment]
Well he's not eligible for hero of the chapter so if that option is still showing then it needs to be removed
