### ISSUE TITLE
Space Wolves: Hero of the Chapter stratagem missing for some characters

### ISSUE THREAD

**Issue by Wookalicious** [BSData/wh40k-9e#8815]
**File/Catalogue:** 

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes
**Description:** appologies mad spy for not replying on the original issue #8788 in regards to hero of the chaptor, Your confusing 2 different strats for the same strat, Hero of the chaptor allows to to put a single warlord trait onto another character, it is a base SM strat, were as Warriour of legend strat in SW supplement allows your chosen SW warlord character (not named characters) to take a 2nd warlord trait himself( must be from the SW warlord traits inorder to take the 2nd pick), Ie warriour of legend allows your chosen warlord to have 2 warlord traits, were as Hero of the chaptor allows you to take a single warlord trait on another character. I hope Ive explained this clearly enough, as far as im aware NONE of the character choices have a box to tick for hero of the chaptor strat. (I think you assumed warriour of legend was SW version of hero of the chaptor, not the case, they are 2 different stratagems) cheers :)

**Comment by Mad-Spy** [comment]
Can you please give a specific example of a CHARACTER choice which is missing the stratagem? I see it on every model which should have it, as far as I can tell. Have you chosen a Warlord for your Roster; it won't show if you haven't?

**Comment by Wookalicious** [comment]
Excellent, Just went through all unnamed characters and I now can see the hero of the chaptor stratagem for all, cheers.
