### ISSUE TITLE
Lib - Space Marines: Judiciar unable to take Purgatorus

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8818]
**File:** Imperium - White Scars.catz

**BattleScribe version:** 3.21.16

**Platform:** Windows

**Dropbox:** Yes

**Description:** Judiciar unable to take Purgatorus relic despite being equipped with Absolver Bolt Pistol

**Comment by Mad-Spy** [comment]
The Judiciar needs to be changed over to the shared copy of the absolver.
