### ISSUE TITLE
Thousand Sons missing Vindicator

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8820]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** Chaos Vindicator not visible in the Thousand Sons list.

**Comment by Mad-Spy** [comment]
They are not allowed to take it, as per the IA Compendium.

**Comment by Valorcalls** [comment]
Chaos Vindicator is in the Tsons Codex, page 82. They can't take the IA one, but they also have that codex one too

**Comment by Mad-Spy** [comment]
Yes, you're right. I got a little carried away with taking out the FW stuff!
