### ISSUE TITLE
Ork speedboss Zhadsnark Da Ripper [FW Legends] Da beast rule missing ?

### ISSUE THREAD

**Issue by whitewolfmxc** [BSData/wh40k-9e#8822]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

Ork speed boss Zhadsnark Da Ripper [FW Legends] Da beast rule missing ?

Da Beast: When this model Advances, do not make an Advance roll. Instead, until the end of the phase, add 6" to the Move characteristic of this model.
--

**Comment by Technoblazed** [comment]
Fixed in next release.
