### ISSUE TITLE
Baal Predator Flamer Sponsons

### ISSUE THREAD

**Issue by zweinsteinsings** [BSData/wh40k-9e#8827]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/

**Dropbox:** Yes/No

**Description:** Baal Predator Heavy Flamer Sponsons are 15 point each (30 together) in the 9th ed codex but BattleScribe has them listed at 45 points and 30 points. 

[Baal Predator.pdf](https://github.com/BSData/wh40k/files/5562002/Baal.Predator.pdf)

**Comment by Mad-Spy** [comment]
Fixed in next release

**Comment by zweinsteinsings** [comment]
Thank you!  

Sincerely,
Zach W.
