### ISSUE TITLE
Craftworlds - Imperial Armour Compendium - Initial QA Pass

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#8833]
**File/Catalogue:** Aeldari - Craftworlds v116

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [x] Irillyth doesn’t gain the Inspiring Warlord warlord trait if he is made Warlord
- [x] Irillyth’s Reaper of Souls (Aura) ability is currently named “Reaper of Souls”, but should be “Reaper of Souls (Aura)
- [x] Irillyth is missing the Shadow Spectres Phoenix Lord ability
- [x] Shadow Spectres’ prism rifle’s dispersed profile is currently named “Prism Rifle (Diffuse)”, but should be named “Prism Rifle (Dispersed)”
- [x] Shadow Spectres’ prism rifle’s dispersed profile has incorrect ability text and should be “Blast”
- [x] Shadow Spectres’ prism rifle’s dispersed profile currently has a Range characteristic of 8”, but should be 18”
- [x] Shadow Spectres’ prism rifle’s focused profile is currently named “Prism Rifle (Coherent)”, but should be named “Prism Rifle (Focused)”
- [x] Shadow Spectres’ prism rifle’s focused profile has incorrect ability text and should be “-”
- [x] Shadow Spectres’ prism rifle’s focused profile currently has a Range characteristic of 18”, but should be 24”
- [x] Shadow Spectres’ prism rifle’s focused profile currently has a Damage characteristic of 1, but should be 3
- [x] Plasma grenades can be taken multiple times, but should only be able to be taken once for:
1. Shadow Spectres > Shadow Spectre
1. Shadow Spectres > Shadow Spectre Exarch
- [x] Plasma grenades should be taken by default and be unable to be removed for:
1. Shadow Spectres > Shadow Spectre
1. Shadow Spectres > Shadow Spectre Exarch
- [x] Hornets are currently able to take less than two shuriken cannons, but should always have two shuriken cannons
- [x] Hornets can currently take a crystal targeting matrix on an individual unit basis, but this upgrade should be for all models in the unit - They are collective, if you select it for one it will be applied to all other models in the unit automatically :smile:
- [x] Hornets can currently take a spirit stone on an individual unit basis, but this upgrade should be for all models in the unit - They are collective, if you select it for one it will be applied to all other models in the unit automatically :smile:
- [x] Hornets can currently take star engines on an individual unit basis, but this upgrade should be for all models in the unit - They are collective, if you select it for one it will be applied to all other models in the unit automatically :smile:
- [x] Hornets can currently take vectored engines on an individual unit basis, but this upgrade should be for all models in the unit - They are collective, if you select it for one it will be applied to all other models in the unit automatically :smile:
- [x] Hornet’s Lightning Assault ability has a typo: “Each timea ranged attack” should read as “Each time a ranged attack”
- [x] Wraithseer has no Psyker profile showing its casts/denies/known powers
- [x] Scorpion’s Wound Track 3 is currently named “Scorpion [3] (1-4 Wounds remaining)”, but should be named “Scorpion [3] (1-6 Wounds remaining)”
- [x] Skathach Wraithknight’s Wound Track 3 currently has a W characteristic of 24, but should be N/A
- [x] Revenant Titan’s Explodes ability has a typo: “On a 4+ it explodes” should read as “On a 5+ it explodes”
- [x] Wraithseer’s D-cannon currently costs 1 PL and 40 points, but should be just 40 points
- [x] Spirit stones currently cost 10 points, but should be 15 points for:
1. Cobra
1. Scorpion
- [x] Revenant Titan’s sonic lances currently cost 60 points each, but should be 0 points each

**Comment by FarseerVeraenthis** [comment]
so I also appreciate that I have some Legends work to do as well... I best get busy!!
