### ISSUE TITLE
Drukhari - Imperial Armour Compendium - Initial QA Pass

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#8838]
**File/Catalogue:** Aeldari - Drukhari v85

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 
- [x] Reaper’s Wound Track 1 currently has a M characteristic of *, but should be 14”
- [x] Reaper’s Wound Track 1 currently has a BS characteristic of *, but should be 3+
- [x] Reaper’s Wound Track 1 currently has an A characteristic of *, but should be 3
- [x] Reaper Max wounds should be 10
- [x] Tantalus’s Transport ability text’s second sentence should read as: “Each GROTESQUE model takes the space of 2 models.”
- [x] Tantalus’s Explodes ability currently affects units within 9”, but should be 6”
- [x] Tantalus’s Twilight Field ability currently has the profile name “Night Shield”, but should be “Twilight Field”
- [x] Tantalus’s dire scythe blade currently has a Strength characteristic of User8, but should be User

**Comment by dalamar666** [comment]
The Reapers Wounds characteristic dropped to 10 as well
