### ISSUE TITLE
Orks - Imperial Armour Compendium - Initial QA Pass

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#8841]
**File/Catalogue:** Orks v99

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [x] Nobz on Warbikes’s Keepin’ Order ability has a typo: “friendly < Cl an > units” should read as “friendly < CLAN > units”
- [x] Nobz on Warbikes > Nob on Warbike currently has a profile name of “Nob on Bike”, but should be “Nob on Warbike”
- [x] Nobz on Warbikes > Boss Nob on Warbike currently has a profile name of “Boss Nob on Bike”, but should be “Boss Nob on Warbike”
- [x] When a Squiggoth is equipped with a Kannon, its Transport capacity remains at 10 models, but should drop to 6 models
- [x] Stampede ability is currently named “Stampede!”, but should be named “Stampede” for:
- Squiggoth
- Gargantuan Squiggoth
- [x] Squiggoth’s Stampede ability currently has incorrect text and should read as: “Each time this model finishes a charge move, select one enemy unit within Engagement Range of it and roll one D6; on a 2+, that unit suffers D3 mortal wounds.”
- [x] Squiggoth’s Wound Trackers are not built into its profile’s stat line in the new style
- [x] Big Trakk’s Explodes ability currently deals D6 mortal wounds, but should be D3 mortal wounds
- [x] Big Trakk equipped with a Supa-Kannon currently has the TRANSPORT keyword, but should lose this keyword
- [x] Big Trakk’s Wound Trackers are not built into its profile’s stat line in the new style
- [x] Kannonwagon’s Wound Trackers are not built into its profile’s stat line in the new style
- [x] Gargantuan Squiggoth’s Wound Trackers are not built into its profile’s stat line in the new style
- [x] When a Gargantuan Squiggoth is equipped with a Squiggoth supa-kannon, its Transport capacity remains at 20 models, but should drop to 15 models
- [x] Gargantuan Squiggoth’s Stampede ability has a typo: “roll a D6 for eachenemy unit” should read as “roll a D6 for each enemy unit”
- [x] Kill Tank’s Wound Trackers are not built into its profile’s stat line in the new style
- [x] Kustom Stompa’s Wound Trackers are not built into its profile’s stat line in the new style
- [x] Kustom Stompa’s Gaze of Mork is named “The Gaze of Mork”, but should be named “Gaze of Mork”
- [x] Kustom Stompa’s Stompa Lifta-Droppa currently has a Strength characteristic of -, but should be *
- [x] Kustom Stompa’s Stompa Klaw has a typo: “in addition to any normal damagen.” should read as “in addition to any normal damage.”

**Comment by tag8833** [comment]
Thanks for the work.  I've started on these, and will have them done tomorrow.

**Comment by Technoblazed** [comment]
Fixed in https://github.com/BSData/wh40k/commit/586e6f4431863bba26cf0fc3924a4e62316c0274.
