### ISSUE TITLE
Aeldari - Craftworlds: Wraithseer should be able to select from Runes of Fortune

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8842]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The Hornet has only the option to take shuriken cannons. That has to be changed to take two of the following weapons
hornet pulse laser 5 points each (36" heavy2 S7 DS-2 D2)
Starcannon 5 points each
Bright Lance 10 points each
AML 10 points each

As you can see on the Page "Craftworld Point Values" from the armour compendium it should be only possible to take Hornet Pulslasers or heavy weapons. The wording on the hornetpage is an typo error. Its native loadout are two hornet pulse lasers.

The Wraithseer should be able to swap out smite for the runes of fortune from the war of the phoenix book

**Comment by Valorcalls** [comment]
RAW that's all hornets can currently be given, It's obviously a typo, but given it's GW it's going to be stuck like that until it's FAQed at least 1 month after the book release date to clarify which way it's supposed to be.

The wraithseer issue is the only issue is definitely something that needs fixed.
