### ISSUE TITLE
Primaris Lieutenant not available to Deathwatch

### ISSUE THREAD

**Issue by Butsch91** [BSData/wh40k-9e#8843]
**File/Catalogue:** Warhammer 40,000 v9.1.4 (version from Nov 20, 2020) Deathwatch v111

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
Deathwatch should have access to all Primaris Lieutenants datasheets. It is currently not available and has never been since v9.

Thank you

**Comment by Valorcalls** [comment]
It's been available for quite a while. It's part of the combined "Lieutenants" entry.

**Comment by Butsch91** [comment]
My apologies, I never thought to select the "Lieutenants" as I was assuming it was the First Born (or old marines ones) since the Data Sheet in the codex is a separate one.
