### ISSUE TITLE
Blood Angels Invader ATV missing Rules

### ISSUE THREAD

**Issue by tjw007** [BSData/wh40k-9e#8845]
**File/Catalogue:** Blood Angels v205 / Warhammer 40,000 v9.1.4

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** Blood Angels Invader ATV squad missing Red Thirst, Savage Echoes rules.

**Comment by Technoblazed** [comment]
Fixed in current release.
