### ISSUE TITLE
Deathwatch - Relic Leviathan and Relic Contemptor

### ISSUE THREAD

**Issue by goodkidnz** [BSData/wh40k-9e#8853]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
Both Leviathan and Relic Contemptor are using old profiles and points costs in Deathwatch section. Sorry if you guys just haven’t made it there yet, thought it may have been missed.

**Comment by Technoblazed** [comment]
Update your data.
