### ISSUE TITLE
Deathwatch - Indomitor Kill Team's heavy bolter has incorrect points cost

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#8861]
**File/Catalogue:** Imperium - Adeptus Astartes - Deathwatch v111

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 
Indomitor Kill Team > Heavy Intercessor w/ Heavy Bolter's heavy bolter costs 15 points, but should be 10 points.

**Comment by Fanxoa1** [comment]
Moreover, the rules says "for every 5 models, replace 1 with heavy bolter" but in battlescribe, the heavy bolter seems to be the 6th model, otherwise the app put an error message.

**Comment by Dunamis55** [comment]
@Fanxoa1, that particular issue is already fixed in the next release.
