### ISSUE TITLE
Leviathan Dreadnaught/Sicaran Battle Tank

### ISSUE THREAD

**Issue by vikinghorde** [BSData/wh40k-9e#8862]
Warhammer 40k file

Leviathan dreadnaught does not incur a cost when changing both the Gravflux bombards to a weapon not listed with a point cost. ie, the Seige claw.   the seige claw includes a meltagun. Currently if you change both is tacks on 15 points each.  

Sicaran Battle tank comes with a heavy bolter at the base cost of 165. Only sponsons have a cost to add heavy bolters.

**Comment by acebaur** [comment]
You pay for all weapons in your profile if they have a points cost even if they are stock. So the sicaran pays the 15 points for HB it comes with

I'll look into the Levi, that's weird

**Comment by acebaur** [comment]
Levi issue fixed
