### ISSUE TITLE
Space wolves: master of sanctity bugged

### ISSUE THREAD

**Issue by THusky1** [BSData/wh40k-9e#8864]
Master of sanctity for space wolves chaplains is still bugged - I reported the issue for the last 2 versions but the report was dismissed; it’s not a common issue with space marine shared files / other chapters.

Currently master of sanctity if chosen by one chaplain in a space wolf force is applied to all chaplains - its giving an error “not enough litanies selected” for the non-MoS chaplain.

**Comment by Mad-Spy** [comment]
This is 100% a problem with the Chaplain entries in the Space Marine library and has already been reported.
