### ISSUE TITLE
Imperium - Space Marine Library - Primaris captain. primarch's wrath option missing. 

### ISSUE THREAD

**Issue by miku2020** [BSData/wh40k-9e#8866]
**File/Catalogue:**  Imperium - Adeptus Astartes - Dark Angels V182

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

Primarch's Wrath isn't option for Primaris Captain when having Special Issue Bolt Carbine selected.

**Comment by FarseerVeraenthis** [comment]
This is infact a Space Marine Library issue
