### ISSUE TITLE
Imperial Guard Infantry Squads

### ISSUE THREAD

**Issue by DudeChris33** [BSData/wh40k-9e#8872]
**File/Catalogue:** Astra Militarum v294

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Can the Infantry Squad Sergeants be set to always have the chainsword when you add the unit? There's no reason not to take it and it gets annoying having to manually add a chainsword every time I create an infantry squad. And yes I know you can duplicate units but I build many guard lists and they also have multiple detachments.

**Comment by alphalas** [comment]
No because it’s not his default Wargear

**Comment by DudeChris33** [comment]
oh ok oof
