### ISSUE TITLE
Grey Knights - Librarian doubling storm bolter equipment

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8876]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** I have noticed for the Grey knight librarian the storm bolter is coming up as 6pts when it should be 3pts.

Many thanks you guys are amazing

**Comment by tekton** [comment]
Duplicate of #8760
