### ISSUE TITLE
Ynnari named characters are unable to use Exalted of Ynnead to gain a warlord trait

### ISSUE THREAD

**Issue by dode74** [BSData/wh40k-9e#8877]
**File/Catalogue: Warhammer 40,000** 

**BattleScribe version: 2.03.**

**Platform: Windows**

**Dropbox: Yes**

**Description: There is no option to use the Exalted of Ynnead stratagems on any of the 3 Ynnari characters.**

**Comment by KalChoedan** [comment]
Confirmed as described in v67 of the Ynnari library.
