### ISSUE TITLE
Astartes chainsword doesn't appear in Blood claws (SW) stats

### ISSUE THREAD

**Issue by Edoshi56** [BSData/wh40k-9e#8885]
**File/Catalogue:** 

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes/No

**Description:** Detailed issue description. : Astartes chainsword doesn't appear in Blood claws (SW) stats

**Comment by Mad-Spy** [comment]
Update your data. It is there in the current release.

**Comment by Edoshi56** [comment]
Nope, v9.1.4, updated a second time to be sure, deleted unit and re-add one, and still no astartes chainsword on blood claws non pack leader
