### ISSUE TITLE
T'au Longstrike has no access to relic (High-Capacitance Railgun)

### ISSUE THREAD

**Issue by Nymcom** [BSData/wh40k-9e#8886]
![longstrike](https://user-images.githubusercontent.com/74966065/100091196-36feea00-2e4c-11eb-97a5-d264052843cb.png)
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** The rule states that the relic can be equipped on TX7 Hammerhead gunships and longstrike has the TX7 Hammerhead gunship keyword. Said relic cannot be equipped as seen in the screenshot.

"TX7 HAMMERHEAD GUNSHIP model equipped with a railgun only. This Weapon System replaces a railgun and has the following profile..."

Very small bug but for a long time I thought it could not be equipped on longstrike until I was told otherwise.

**Comment by alphalas** [comment]
He’s a named character though, named characters can’t have relics

**Comment by Mad-Spy** [comment]
Named characters cannot take Relics, so Longstrike can't take it.

**Comment by alphalas** [comment]
![4B446EA5-7F22-4CBE-87C8-91D4180F1E3D](https://user-images.githubusercontent.com/15703066/100092450-102cbd80-2e24-11eb-8ca4-8b1ccabbb572.png)

**Comment by Technoblazed** [comment]
He is a named character, named characters cannot be given relics.

**Comment by Nymcom** [comment]
Alright thanks for clearing that up, I knew it wasn't possible but a friend said I could. Thought I could help others too

**Comment by alphalas** [comment]
Yeah tell your friend he needs to read the codex better next time ;)
