### ISSUE TITLE
Chaos Space Marines - Missing Imperial Armour Heavy Support Units

### ISSUE THREAD

**Issue by Gwennec** [BSData/wh40k-9e#8889]
**File/Catalogue:** Chaos - Chaos Space Marines V153

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Missing two heavy support unit entries for Chaos Space marines from the latest Imperial Armour compendium. The missing units are the Chaos Sicaran Punisher and the Chaos Rapier Charrier.

**Comment by Mad-Spy** [comment]
Already fixed for next release
