### ISSUE TITLE
Imperium - Astra Militarum: Tempestor Prime unable to select regiment relics

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8894]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Tempestor Prime in Tempestus Drop Force detachments do not have access to their regiment specific relics. As far as I understand, they should be retaining the regimental bonuses. Regimental warlord traits appear as normal. This issue does not occur if the Tempestus Drop Force specialist detachment is not selected.

**Comment by Technoblazed** [comment]
Can't replicate this with a warlord selected, did you definitely have a warlord selected in your roster?

**Comment by Technoblazed** [comment]
No response, locking.
