### ISSUE TITLE
[Space Marines] Whirlwind Scorpius is missing

### ISSUE THREAD

**Issue by Duriel201** [BSData/wh40k-9e#8897]
**File/Catalogue:** Warhammer 40,000 v1.9.4

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** The datasheet for the Whirlwind Scorpius isnt currently in the catalogue but it should still be there as it's listed in imperial armour (so hasn't gone to legends)

**Comment by acebaur** [comment]
It's in HS now

**Comment by Dunamis55** [comment]
Which Space Marine catalogue are you having this problem in?
