### ISSUE TITLE
Imperium - Space marine - Chapters & Masters of the chapter

### ISSUE THREAD

**Issue by Fanxoa1** [BSData/wh40k-9e#8904]
**File/Catalogue:**  Warhammer 40,000 v9.1.4

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** ?

**Description:** It should be possible to have 2 detachments from different chapters and 2 Masters of the chapter with the same chapter command keyword, each from 2 different chapter. For instance, 1  white scars masters of sanctity and 1 deathwatch master of sanctity). I check for Librarian, ancient, chaplain, techmarine, all trigger the error saying it should only contains 1 of this msater keyword.

**Comment by alphalas** [comment]
Unfortunately it’s a limitation of the BS program, not a data error.
