### ISSUE TITLE
Imperium - Adeptus Custodes: Aquilon Terminator PL cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8906]
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Aquilon terminators have incorrect power leval shown, one terminator gives 15PL, and every other one gives 4, a 3man squad has 23PL instead of 12PL

**Comment by Wolfbrother41** [comment]
As per Imperial Armour Compendium, the 1st one should be 11 PL, then 0 for the next 2, then 11 for the 4th, then 0 for the last 2. (Don't know how easy it is to do within battlescribe, though)
