### ISSUE TITLE
Dark Angels Elite Issues

### ISSUE THREAD

**Issue by Mordrot66** [BSData/wh40k-9e#8912]
**File/Catalogue:** 40k Dark Angels data

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** 
The Dark Angels have several issues in the elite category. Deathwing Command Squads and Ravenwing Black Knights being taken in a list automatically allow the player to include specialist champions, ancients, & apothecaries from their respective companies without occupying force org slots. Taking these units should create the option for these specialist elite characters in the "no force org" category. 

Also, the Land Speeder Vengeance and Dark Shroud are in the elite category when they should be in fast attack as per the index points section.

**Comment by Valorcalls** [comment]
1) they should appear in the "No Force Org Slot" section as options when the relevant command squad is added. If this isn't showing for you, please delete and re-download local data and try again.

2) the points section doesn't determine FoS, the datasheet does. The index datasheet says elite.
