### ISSUE TITLE
Aeldari - Craftworlds - Shadow Specter weapon profiles incorrect/exarch special weapon

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8916]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** In Craftworld, Elite, the Shadow Specter weapon profile isn't up to date.
It should be :
Prism Rifle :
-Dispersed 18" Assault D6 S5 AP-1 1dmg Blast
-Focus 24" Assault 1 S6 AP-3 3dmg

And the Exarch doesn't have a special weapon anymore :)

Thank u

**Comment by FarseerVeraenthis** [comment]
Already fixed on master.
