### ISSUE TITLE
Necrons - Doomsday Arks only 1 Gauss Flayer Array

### ISSUE THREAD

**Issue by Streyder** [BSData/wh40k-9e#8919]
**File/Catalogue:** Necrons v79

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** Doomsday Arks only have a single Gauss Flayer Array, although they get two according to Codex: Necrons pg. 104: "A Doomsday Ark is equipped with: doomsday cannon; 2 gauss flayer arrays."

**Comment by acebaur** [comment]
Look again it has 2 in its entry

**Comment by Streyder** [comment]
"Doomsday Cannon (High Power), Doomsday Cannon (Low Power), Gauss Flayer Array". There is only one. Where in the datasheet are the 2 mentioned than?

**Comment by alphalas** [comment]
In your codex because battlescribe is not a codex replacement.

**Comment by Technoblazed** [comment]
@Streyder 

![Image](https://i.tech-no.me/2020/11/30/201130215344.png)

**Comment by Streyder** [comment]
Hmm okay I see. Where exactly do you get that view? If I select VIEW Selection, this block is not there

**Comment by Technoblazed** [comment]
It's in view selection as well, make sure you have `full output` selected.

**Comment by Streyder** [comment]
I have full output enabled. It does not show this part in the profile. I just wanna know so I don't report errors like this again
