### ISSUE TITLE
Chaos Decimator Claws

### ISSUE THREAD

**Issue by DudeChris33** [BSData/wh40k-9e#8920]
**File/Catalogue:** Chaos Space Marines v153

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The Decimator's Decimator claw with hellflamer has no listed point value, and when you add one of them this stays true, but when you add a second one it adds 80pts to the cost. I do not know which part of this is wrong just that it is inconsistent. The same does not happen for any of the other weapons.

**Comment by Mad-Spy** [comment]
Fixed in next release.
