### ISSUE TITLE
Can't choose two lightning claws for wolfguard space wolves

### ISSUE THREAD

**Issue by Type-40** [BSData/wh40k-9e#8922]
**File/Catalogue:** 
Adeptus astartes Space wolves

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux
all
**Dropbox:** Yes/No

**Description:** Detailed issue description.
when I try to take two lightening claws on a wolfgaurd pack leader I get "Wolf guard Skyclaw Pack Leader has 1 too many selection from Space Wolves Melee Weapons (maximum 1)
there is no maximum 1 restriction. just a maximum 1 restriction on the storm shields

![Capture](https://user-images.githubusercontent.com/15158244/100678897-8ecab300-336e-11eb-9d90-cbd6dd285c1b.PNG)

**Comment by Mad-Spy** [comment]
Fixed in SW v171.
