### ISSUE TITLE
WG Pack leaders should have access to Thane of the retinue 

### ISSUE THREAD

**Issue by Type-40** [BSData/wh40k-9e#8924]
**File/Catalogue:** 
SWs 
**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux
all
**Dropbox:** Yes/No

**Description:** Detailed issue description.
When using the "Thane of the retinue" Stratagem. Wolf Gaurd pack leaders who have been added to the unit should also have accesses to the "special issue wargear" as they are also "Pack Leaders"

**Comment by Mad-Spy** [comment]
I think I only missed the Skyclaw, the others work in the current release.

**Comment by Mad-Spy** [comment]
Fixed in SW v171.
