### ISSUE TITLE
Njal Stormcaller is missing smite

### ISSUE THREAD

**Issue by Rattleme** [BSData/wh40k-9e#8925]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
In Njal Stormcaller's psyker description it says he knows three tempestas discipline powers and smite. Smite is missing

**Comment by Mad-Spy** [comment]
Fixed in SW v171.
