### ISSUE TITLE
Indomitor Kill Team requires too many Heavy Intercessors to add Heavy Bolter type weapons

### ISSUE THREAD

**Issue by HigherCalibur** [BSData/wh40k-9e#8927]
File: Imperium - Deathwatch.catz

BattleScribe version: 2.03.21.166

Platform: Windows

Dropbox: Yes

Description: User receives a roster error when attempting to add a Heavy Intercessor w/ Heavy Bolter if there are 4 other Heavy Intercessors in the Indomitor Kill Team (including Sergeant). It appears as though the Heavy Intercessor w/ Heavy Bolter option is not counting as a Heavy Intercessor w/ Heavy Bolt Rifle (which it should as long as there are 5 Heavy Intercessors in the squad).

**Comment by Technoblazed** [comment]
Fixed in next release.
