### ISSUE TITLE
Grey Knights: Doomglaive Dread missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8928]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The Doomglaive Dreadnought in Grey Knights elite slot is missing from the RSE link. And cannot be seen in the elites section of battle scribe.

**Comment by tekton** [comment]
It doesn't exist anymore! The option to take a doomglaive is in legends, and will show up when "Show Legends" is turned on.

**Comment by CaptianFordo** [comment]
It doesnt exist even when you use the legends option
