### ISSUE TITLE
Space Wolves Issues

### ISSUE THREAD

**Issue by illtrythis** [BSData/wh40k-9e#8930]
**File/Catalogue:** 9.1.4 (Main), also checked commit (c3914306f83c6ea3db93bd7d65811f9b251e565b)

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Description:**

- [x] Wolf Guard Terminator Pack Leaders Storm Shields cost 5pts in the roster builder but they should be 0pts like for their brethren in the squad.

- [ ] Librarian in Phobos, Primaris Librarian, and the generic Librarian with Psychic Mastery WLT and Tome of Malcador relic are currently throwing errors. Normal casting rules are "know 2, cast 2, deny 1". With Psychic Master it becomes "know 3, cast 2, deny 2". With Tome of Malcador in addition it becomes "know 4 (1 from ANY discipline it has access to), cast 2, deny 2). I think this issue is with Psychic Mastery not giving an additional power AND Tome of Malcador not allowing access to a Discipline outside the original choice of the caster.

- [x] "Thane of the Retinue" counts towards "3 max relics". I have 1 relic granted to my Warlord for free. I buy 2 with "Relics of the Chapter", and then I'm giving Frost Claws to a Pack Leader and I get an error.

- [x] Wolf Tail Talisman ~~is~~ should not ~~currently~~ be allowed to be given through "Thane of the Retinue" ~~despite the fact that the wording of Wolf Tail Talisman does imply that it should be able to be given to a unit through "Thane of the Retinue."~~

**Comment by acebaur** [comment]
Tome of malcador does not grant access to a power from another discipline. All powers must come the same discipline

**Comment by illtrythis** [comment]
> 
> 
> Tome of malcador does not grant access to a power from another discipline. All powers must come the same discipline

**Tome of Malcador** (SM page 109) - "**Librarian** model only. The bearer knows one additional psychic power from _any_ discipline it has access to."

**Tempestas Discipline**  (SW page 52) - "... _can_ know _all_ of their psychic power from the Tempestas discipline _instead_ of the Librarius or Obscuration disciplines."

There are some operative words in question here. Any, all, can, and instead.

I believe Tome of Malcador provides an exemption to this rule. If this was not intended other words would or could have been chosen. Any --> the, can --> must

- The bearer knows one additional psychic power from **the** discipline it **[currently]** has access to."

- "... **must** know _all_ of their psychic power from the Tempestas discipline _instead_ of the Librarius or Obscuration disciplines."

We also cannot use 8th edition FAQs concerning the RAI. Those FAQs are dead and gone. Explicitly stated from GW.

**Comment by alphalas** [comment]
@illtrythis until it is FAQ’d it stays as it is- because I read it as not an exception just an addition

**Comment by alphalas** [comment]
> I believe Tome of Malcador provides an exemption to this rule. If this was not intended other words would have been chosen.

Except they never changed the wording in the old FAQs - they just said that that’s not how that works

Your *belief* is incorrect.

**Comment by illtrythis** [comment]
> they just said that that’s not how that works

We cannot use 8th edition FAQs concerning the RAI. Those FAQs are dead and gone. Explicitly stated from GW.

Unless there is a brand new FAQ that I am not aware of. That's a grossly untrue statement.

**Comment by illtrythis** [comment]
I should not be arguing the RAI simply RAW but..

Think of use cases for Tome of Malcador now that Chapter Command exists with your interpretation. You can have one caster with 4 powers, or 2 casters with 3 powers. I simply cannot think of a use for this relic unless the any is an exception. There are instances of bad relics and inherently worthless relics but I doubt very much they intended anything to be considered clutter while writing the new 9E codices.

**Comment by alphalas** [comment]
*laughs in half the Tau septs/relics and most of the eldar relics*

That being said, further discussion should be on the discord, not here.

**Comment by HaxoIronWolf** [comment]
Wolf Guard & Wolf Guard Terminators missing CORE keyword
