### ISSUE TITLE
Imperium - Space Marines: - Bolt sniper rifle Mortis round

### ISSUE THREAD

**Issue by ChthonicKnight** [BSData/wh40k-9e#8936]
**File/Catalogue:** 
Imperium - Adeptus Astartes - Deathwatch v112
**BattleScribe version:** 2.03.
2.03.21
**Platform:** Windows/iOS/Android/Mac/Linux
Windows
**Dropbox:** Yes/No
Yes
**Description:** Detailed issue description.
Under Spectrus Kill Team, Bolt sniper rifle - Mortis round shows Damage as D3, should be Damage 2.

**Comment by Technoblazed** [comment]
Space marine lib issue, reassigned.

**Comment by acebaur** [comment]
It is damage 2 in BS
