### ISSUE TITLE
Chaos Space Marines - daemons missing as troop options

### ISSUE THREAD

**Issue by RobDonkey** [BSData/wh40k-9e#8937]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

Profiles missing for Bloodletters, Daemonettes, Plaguebearers and Horrors as per pages 133-135 of the Heretic Astartes Codex.

Units do not appear in Chaos Space Marine rosters.

**Comment by Technoblazed** [comment]
Go to the roster creation screen, select your current detachment and add a Chaos - Daemons detachment as a sub detachment.
