### ISSUE TITLE
Imperium - Grey Knights: Dreadnought missing legends weapon options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8945]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.03.25

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Please don't mark this as a duplicate of 8928 
This is a different bug as when I have made sure that legends options is selected Doomglaive Dreadnought still does not appear as a selectable option in the elites section.

**Comment by Mad-Spy** [comment]
Yeah, we noticed it wasn't fixed properly. It'll be sorted in the next release.
