### ISSUE TITLE
Aeldari: Plasma grenades are missing the Blast rule.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8946]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** Plasma Grenade should have the Blast rule. This same issue concerns Craftworlds cat.

**Comment by FarseerVeraenthis** [comment]
Yeah, I mean, plasma grenades could probably get moved to the library...

**Comment by FarseerVeraenthis** [comment]
Actually, only the Drukhari are missing Blast, and I'm not minded to faff about pulling them up to a library entry.
So I just updated the Drukhari CAT and be done :smile:
