### ISSUE TITLE
Imperium: Space Wolves - Missing unit entry

### ISSUE THREAD

**Issue by KurisuFenrisWolf** [BSData/wh40k-9e#8949]
**File:**  Imperium - Space Wolves.cat

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** There is currently no option to select a Wolf Guard Battle Leader on Thunderwolf, There is no unit entry within the HQ section.

**Comment by alphalas** [comment]
WGBLoTW is a Lieutenant. As such, he is in the Lieutenants entry.
