### ISSUE TITLE
Imperium - Iron Hands: Chapter Master for Captain on Bike is still counting as a Captain

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8950]
**File:** Imperium - Iron Hands.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When using a captain on a bike, making it a chapter master still brings up an error of too many captains when bringing in another captain.

I have tried with other captains, I can't recreate it with them. The issue most likely sits with the Bike captain.

**Comment by DAN38100** [comment]
Looks like not only Iron Hands. - I got the same problem for Salamander.
