### ISSUE TITLE
Chaos - FW Renegade and Heretics: Points values for AM units incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8952]
**File:** Chaos - FW Renegade and Heretics.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The points values for the various vehicles which can be taken from the Astra Militarum codex are incorrect - the values are from 8th edition, not the new points in 9th. The following units have incorrect points:

Fast Attack
Hellhound
Salamander Scout Tank

Heavy Support
Armageddon Pattern Medusa
Basilisks
Colossus Bombard
Earthshaker Carriage Battery
Griffon Mortar Carrier Squadron
Heavy Mortar Battery
Heavy Quad Launcher
Hydras
Leman Russ Battle Tanks
Malcador Defender
Malcador Heavy Tank
Medusa Carriage Battery
Rapier Laser Destroyer
Wyverns

Flyer
Arvus Lighter (wargear options)
Valkyrie

Dedicated Transport
Chimera

**Comment by Mad-Spy** [comment]
This work is waiting on some work being done in the Astra Militarum catalogue.

**Comment by Technoblazed** [comment]
Completed as part of https://github.com/BSData/wh40k/commit/a1c3a8fe0c8e21b54f2a6b48142fdc1f3718ef43 - will be released with the next release.
