### ISSUE TITLE
Bug Report: Space Marines - Servitors

### ISSUE THREAD

**Issue by MrFirebug** [BSData/wh40k-9e#8953]
**File/Catalogue:** 

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Servitor Mindlock ability does not seem to be calculating the second half of the ability "In addtion, if your army is Battle-forged, then for each <CHAPTER> TECHMARINE unit included in a detachment, one <CHAPTER> SERVITORS unit can be included in that detachment without taking up a Battlefield Role slot." for Primaris or regular Techmarine.  Also, misspelling of "addition".

**Comment by alphalas** [comment]
You take that unit in the no force org slot

**Comment by MrFirebug** [comment]
Ok, they show up in the no force org slot with Ultramarines when I take a techmarine, but it doesn't show up as an option for Space Wolves with Primaris/Regular Techmarine or either Iron Priest on bike/thunderwolf for legends. 
I mentally generalized to all Space Marines without double checking apparently.
