### ISSUE TITLE
Bug Report: Servitors Mindlock not working for certain chapters

### ISSUE THREAD

**Issue by MrFirebug** [BSData/wh40k-9e#8954]
File/Catalogue:

BattleScribe version: 2.03.21

Platform: Windows

Dropbox: No

Description:  Reposted as the first issue was closed (appropriately), but as a new issue because it is a specific chapter issue not general Space Marines.  

For specific Chapters only (Blood Angels, Dark Angels, Space Wolves) Servitors are not showing up in No Force Org Slot when a Techmarine(Primaris, Regular, Iron Priest) is included.

In addition, the Mindlock ability has a misspelling with " In addtion," should be "In addition,".

---
Ok, they show up in the no force org slot with Ultramarines when I take a techmarine, but it doesn't show up as an option for Space Wolves with Primaris/Regular Techmarine or either Iron Priest on bike/thunderwolf for legends. 
I mentally generalized to all Space Marines without double checking apparently.

_Originally posted by @MrFirebug in https://github.com/BSData/wh40k/issues/8953#issuecomment-738327844_

**Comment by Mad-Spy** [comment]
Already fixed in SW for next release.
