### ISSUE TITLE
thane of the retinue strat wont allow me to give a relic to a long fang wolf guard leader, just the regular long fang sergeant

### ISSUE THREAD

**Issue by Dusldorf** [BSData/wh40k-9e#8966]
**File/Catalogue:** 40k v9.1.4

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** thane of the retinue lets you give a special issue relic to a sergeant or wolf guard leader, but battlescribe wont let me give one to a long fang wolf guard leader (terminator or regular).

**Comment by Mad-Spy** [comment]
Fixed in current release (Wolves v172)
