### ISSUE TITLE
rune priest upgraded to chief libby but returns an error if i select 3 powers

### ISSUE THREAD

**Issue by Dusldorf** [BSData/wh40k-9e#8967]
**File/Catalogue:** 40k v9.1.4

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** the chief libby upgrade lets a libby select one more power from their chosen discipline, but when i make a rune priest a chief libby and select a third power i get an error: "librarian has 1 too many selections from disciplines (maximum 2)."

**Comment by BrotherLogos** [comment]
Also happens with Phobos Librarian in Dark Angels.

**Comment by Mad-Spy** [comment]
Do you specifically mean the "Rune Priest on Bike" (which is the only Rune Priest which still exists) or do you mean a Librarian in the Space Wolves catalogue? If so, which one?

**Comment by Dusldorf** [comment]
I mean a regular rune priest, the librarian in the space wolves catalogue

**Comment by alphalas** [comment]
@Dusldorf update your data then because the regular rune priest does not exist anymore - there are only librarians and the rune priest on bike

**Comment by Dusldorf** [comment]
@alphalas i edited my reply, i mean the librarian in the space wolves catalogue
