### ISSUE TITLE
Imperium - Dark Angels: Several issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8971]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** 1. DA relic contemptor dreadnought(forged world) : melee weapon with Bolter should be 0 points (instead of +5 points on the storm Bolter)

2. Corvus oculus relic for Ravenwing Talonmaster is missing.

3. Belial sword of silence, stats all wrong.

4. Scorpius whirlwind , should be under Heavy Support. Not uncategorized slot.

**Comment by Thairne** [comment]
![grafik](https://user-images.githubusercontent.com/8590840/101336331-a4fad680-387a-11eb-86a0-c1c1d94effcb.png)
![grafik](https://user-images.githubusercontent.com/8590840/101336696-0cb12180-387b-11eb-8d0b-99b5c8c161c2.png)

**Comment by acebaur** [comment]
Comtemptor issue fixed

**Comment by FarseerVeraenthis** [comment]
so I think through the combined efforts of Ace and Thairne this can be closed...
