### ISSUE TITLE
Bug, Difference between tome of malcador and chaptor command chief librarian not reflected in the tome of malcador relic

### ISSUE THREAD

**Issue by moonbearer** [BSData/wh40k-9e#8974]
**File/Catalogue:**  Imperium - Space Marines.cat.

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Description:** 

Tome of malcador relic. New changes to space marine librarians allow them to take two powers from a chosen discipline it has access to. 

The chief librarian chapter command upgrade, allows a librarian to take one additional power FROM their chosen discipline
![image](https://user-images.githubusercontent.com/68803697/101265796-50752f80-3784-11eb-9443-7248a5310f38.png)

But providing the tome of malcador allows them to take one additional power FROM any discipline it has access to
![image](https://user-images.githubusercontent.com/68803697/101265812-7ac6ed00-3784-11eb-90b5-ffc5d8b4f2ec.png)

The wording is explicitly different from the tome of malcador. Rules as written, the tome of malcador provides an additional power from any discipline it has access to, not just the chosen discipline.

**Comment by acebaur** [comment]
Unfortunately that's wrong. The disciplines section requires that all powers must be from the same discipline. The wording for the tome has not changed in the new book to allow this.
