### ISSUE TITLE
BUG, difference in tome of malcador and chief librarian chapter command

### ISSUE THREAD

**Issue by moonbearer** [BSData/wh40k-9e#8975]
**File/Catalogue:**  Imperium - Space Marines.cat.

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Description:** 

Tome of malcador relic. New changes to space marine librarians allow them to take two powers from a chosen discipline it has access to. 

The chief librarian chapter command upgrade, allows a librarian to take one additional power FROM their chosen discipline
![image](https://user-images.githubusercontent.com/68803697/101265796-50752f80-3784-11eb-9443-7248a5310f38.png)

But providing the tome of malcador allows them to take one additional power FROM any discipline it has access to
![image](https://user-images.githubusercontent.com/68803697/101265812-7ac6ed00-3784-11eb-90b5-ffc5d8b4f2ec.png)

The wording is explicitly different from the tome of malcador. Rules as written, the tome of malcador provides an additional power from any discipline it has access to, not just the chosen discipline. This is currently not reflected as of the latest pull Dec 5 1:39pm

![image](https://user-images.githubusercontent.com/68803697/101265911-81099900-3785-11eb-86e0-b045501a65d1.png)

**Comment by moonbearer** [comment]
I think a further discussion on the matter is required. It seems consistent with another analogous case of exceptions. 

An example is all reinforcements must come in at turn 2. Unless explicitly defined by an ability. Such as in the case of the drop pod. Which explicitly states, that it can come at turn 1.

![image](https://user-images.githubusercontent.com/68803697/101266172-75b76d00-3787-11eb-804b-794eabfcf4ae.png)

Tome of Malcador's wording explicitly states "any discipline it has access to". Doesn't this supersede the restriction of choosing powers from the same discipline? In a similar fashion of drop pod assault ability superseding the general reinforcements restrictions? 

John Lennon and his team are entering a GT with lists that use this interpretation of the written rules
![image](https://user-images.githubusercontent.com/68803697/101266212-ccbd4200-3787-11eb-8a51-dd94ab2f6355.png)
https://www.youtube.com/watch?v=IPq9DpEPHm4

**Comment by moonbearer** [comment]
@acebaur would like to get your thoughts on this. thank you!

**Comment by alphalas** [comment]
@moonbearer Bug reports are not where we discuss issues, that’s the discord.

**Comment by alphalas** [comment]
And posting multiple duplicate bug reports because you’re not happy with our justifications are also a good way to get us to ignore you.
