### ISSUE TITLE
Bug, "Duplicate Selection" copies points incorrectly

### ISSUE THREAD

**Issue by njawlf** [BSData/wh40k-9e#8977]
**File/Catalogue:** 
Warhammer 40k, 9e, Imperium, Astra Militarum
**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** Yes/No

**Description:** 
When an Astra Militarum Infantry unit that contains a Heavy Weapon Team has "Duplicate Selection" used on it the new unit generated will cost 5 points more. This cost appears to be placed on the selected weapon, and will be corrected if you change the weapon selection or if use "Duplicate Selection" again but then _that_ new unit will have this same problem. This happens on Infantry Squads, Command Squads, and Veteran Squads, but for some reason doesn't happen to Heavy Weapon Squads.

**Comment by alphalas** [comment]
It’s a BS bug not a data bug.
