### ISSUE TITLE
Space Marines: Raptor Gunship point values are incorrect

### ISSUE THREAD

**Issue by Technoblazed** [BSData/wh40k-9e#8980]
Hey! Not sure if this is the right place to post this, but Fire Raptor Gunship point values are wrong in Adeptus Astartes (checked in UM and RG). It should be 340 base with autocannons and hellstrikes. 2x Quad bolters are +30 points, and 2x Twin lascannons are +10 pts. (Yes, I made an account here just to post this)

Cheers!

_Originally posted by @Ubikator in https://github.com/BSData/wh40k/issues/7390#issuecomment-739513673_

**Comment by Ubikator** [comment]
> Hey! Not sure if this is the right place to post this, but Fire Raptor Gunship point values are wrong in Adeptus Astartes (checked in UM and RG). It should be 340 base with autocannons and hellstrikes. 2x Quad bolters are +30 points, and 2x Twin lascannons are +10 pts. (Yes, I made an account here just to post this)
> 
> Cheers!
> 
> _Originally posted by @Ubikator in [#7390 (comment)](https://github.com/BSData/wh40k/issues/7390#issuecomment-739513673)_

Sorry I double checked right now its +30 pts for quad bolters each and +10 pts twin lascannon each. :)
![Zrzut ekranu (51)](https://user-images.githubusercontent.com/75575074/101284148-d6be5f80-37de-11eb-889f-5747a1bc7356.png)

**Comment by acebaur** [comment]
Points are correct. One quad bolter is 30 points but it has 2
