### ISSUE TITLE
Captain and Lt default loadouts show an error - too many weapons taken

### ISSUE THREAD

**Issue by dode74** [BSData/wh40k-9e#8984]
**File/Catalogue:Warhammer 40,000 v9.1.6** 

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** Captains and Lts should be able to take MC Boltgun, Bolt Pistol and Astartes Chainsword as default.  If you give them this loadout you are told they have taken too many weapons.  This same error comes up if you swap them out for any codex-legal option.  Tested and this happens in BA and RG so far - BA file included.
[BloodAngels2k.zip](https://github.com/BSData/wh40k/files/5649756/BloodAngels2k.zip)

**Comment by acebaur** [comment]
He can't trade the bolt pistol, so if you are choosing one from the pistol list its a second one. The first one is built in
