### ISSUE TITLE
Aspiring Champions

### ISSUE THREAD

**Issue by DudeChris33** [BSData/wh40k-9e#8992]
**File/Catalogue:** Chaos Space Marines v154

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** All of the aspiring champions have the same name so I don't know which one goes with which squad and what model to use. Can you please add "Havoc Aspiring Champion" and stuff like that so that exporters can tell them apart?

**Comment by Mad-Spy** [comment]
There are only two models called "Aspiring Champion" in the CSM catalogue and they are set up to match the GW datasheet. If GW change the datasheet, then the name will be changed.

The data output clearly shows what equipment each has, so it shouldn't be difficult to determine which model is which.

**Comment by alphalas** [comment]
Just to elaborate, we don’t make the data for exporters so there likely will never be optimizations that are specifically for people to export the data for anything other then list printouts.

**Comment by DudeChris33** [comment]
Ok thank you for clarifying. That is unfortunate that that is the case. Is there any way I could join the team so that I could work on those optimizations? There is a large community that uses this for importing into Tabletop Simulator and I would love for it to have some support.

**Comment by alphalas** [comment]
Unfortunately not really- we already have about as many people working on the data as is practically possible

**Comment by alphalas** [comment]
If you’d like a further explanation come talk to us on the discord
