### ISSUE TITLE
Sisters of Silence

### ISSUE THREAD

**Issue by NiceLamp** [BSData/wh40k-9e#8994]
**File/Catalogue: Sisters of Silence

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description: Points costs of Sisters of Silence not updated to War of the Spider points versions. For example all models are now 10 points, and weapons costs are different. Boltguns 0 points, which would make a prosecutors squad 50.. Still showing as 60 in the app.

**Comment by Technoblazed** [comment]
War of the Spider is so out of date, have you looked at the Chapter Approved 2020 points?

**Comment by Mad-Spy** [comment]
As per the previous comment, the Munitorum Field Manual is the latest point source for Sisters of Silence and those point values are in use.

**Comment by NiceLamp** [comment]
Thanks everyone, this was entirely my bad.
