### ISSUE TITLE
Howling Banshees Power Swords should not have +1S

### ISSUE THREAD

**Issue by KalChoedan** [BSData/wh40k-9e#8995]
**File/Catalogue:** Craftworlds v119

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Currently Howling Banshees have been given the new +1S version of the Power Sword that was released via FAQ to other armies when the 9th ed Marines codex dropped.

For Eldar the only publication that received this FAQ update was Codex: Craftworlds. Unfortunately for Howling Banshees, they received an updated datasheet in Psychic Awakening: Phoenix Rising. This datasheet contains the current Howling Banshee stats including their weapons. As it's the most recent datasheet, this is the one we have to use - and in fact it explicitly states it supersedes the datasheet from Codex: Craftworlds.

Because Phoenix Rising didn't get an FAQ to update the power sword stats, Howling Banshees have the dubious honor of being the only power-sword-wielding Eldar unit that is stuck with the old, weaker, version.

**Comment by WindstormSCR** [comment]
Respectfully, while you might be correct in some narrow form, the intent of the changes is clear and GW has a bad case of right hand not knowing what the left did two weeks ago. So this is being closed
