### ISSUE TITLE
Imperium - Adeptus Mechanicus: Daedalosus should be able to use Mechanicum Locum stratagem

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8996]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.03.20

**Platform:** Android

**Dropbox:** No

**Description:** Daedalosus should be able to use the strategems "mechanicum locum" to take a warlord trait, or mechanicum order trait. He can't benefit from forge world dogmas, but he can take a warlord trait as he is a character.

**Comment by Valorcalls** [comment]
You can't use Mechanicum Locum to get the Mechanicum order traits at all, but otherwise this is correct as far as I can tell.

**Comment by DedusJovus** [comment]
I think you can't use the stratagem on him because he doesn't have FORGE WORLD keyword that the stratagem requires. What you can do is give him only standard warlord traits form the Codex. He can't have any of the Holy Order Warolrd Traits from Engine War because he is a named character.

**Comment by Valorcalls** [comment]
You are correct. This makes him working as he should be then, and not an issue.
