### ISSUE TITLE
T'au Empire - The Eight: Torchstar's Flamers have range 8" instead of 12"

### ISSUE THREAD

**Issue by BrucknerC** [BSData/wh40k-9e#8997]
**File/Catalogue:** T'au Empire.cat

**BattleScribe version:** 2.03.21

**Platform:** Windows/Android/Linux

**Dropbox:** No

**Description:** The Flamers for the T'au Empire were recently updated to have range 12". However Sub-Commander Torchstar's Flamers are still at range 8".

**Comment by Technoblazed** [comment]
Unfortunately only the T'au Codex was updated with the FAQ. Similar to the rest of the PA books (and because GW didn't seem to want to fix the rest of it), The Eight are still stuck with the terrible 8" flamers. :(
