### ISSUE TITLE
Chaos Knight Households

### ISSUE THREAD

**Issue by DudeChris33** [BSData/wh40k-9e#9001]
**File/Catalogue:** Chaos Knights v55

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The Chaos Knight Households do not show their effects

**Comment by Mad-Spy** [comment]
All appear to be working fine.

Are you perhaps using a Super-Heavy Aux Detachment? You don't get Household benefits in a SHAD, so the message on the output shows this.

**Comment by DudeChris33** [comment]
I am using an Unbound Army

**Comment by DudeChris33** [comment]
The names show up but they have no descriptions for what they do

**Comment by DudeChris33** [comment]
Just checked and it does show up for Super-Heavy detachments just not in Unbound armies. Dunno why but doesnt matter as long as i have the reference. Ty

**Comment by alphalas** [comment]
Because if you are unbound you do not get those benefits – you have to be a battle forged army to gain them

**Comment by DudeChris33** [comment]
ah ok cool
