### ISSUE TITLE
FW Ork Nob bikers missing wargear options

### ISSUE THREAD

**Issue by whitewolfmxc** [BSData/wh40k-9e#9002]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

FW Ork Nob bikers missing wargear options - missing the shooty weapon options and the legends options from before

**Comment by whitewolfmxc** [comment]
example is Kobi weapon with rocket / Kustom shooter etc

**Comment by whitewolfmxc** [comment]
![image](https://user-images.githubusercontent.com/65846291/101571765-cf7f9780-3a12-11eb-86e6-0744c2bceb6f.png)

also can take a pAIR of kill saws too

**Comment by Valorcalls** [comment]
The only options listed on the datasheet for the Nobz on Warbikes is to add slugga, and replace the choppa. There is no option on their datasheet, or in their section of the legends pdf for shooting options, or even to actually be given a pair of killsaws.
