### ISSUE TITLE
Imperium - Blood Angels: Sanguinary Discipline Missing

### ISSUE THREAD

**Issue by ViraVola** [BSData/wh40k-9e#9003]
**File/Catalogue:** Imperium - Adeptus Astartes - Blood Angels v205

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Blood Angels Librarians do not have access to the Sanguinary Discipline, only Librarius is listed.

**Comment by Mad-Spy** [comment]
The data has not yet been updated with the data from the Blood Angels supplement.
