### ISSUE TITLE
Imperium - Adeptus Astartes: Various Vehicles Improve Wound Profile Readability

### ISSUE THREAD

**Issue by Lairdd1989** [BSData/wh40k-9e#9004]
**File/Catalogue:**  Imperium - Ultramarines.cat
Also present on all other Adeptus Astartes variants

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** Yes

**Description:** Improve wound profile readability of vehicles by changing the wound table column headers.
Currently most have the following headers:

Wound Track | Remaining W | Characteristic 1 | Characteristic 2 | Characteristic 3 | Ref

I would like to see Characteristic 1,2,3 changed to their relevant names.  M | BS | A

This can be seen on the following vehicles but is not limited to just these.

**Repulsor**
Characteristic 1 = M
Characteristic 2 = BS
Characteristic 3 = A

**Repulsor Executioner**
Characteristic 1 = M
Characteristic 2 = BS
Characteristic 3 = A

**Hunter**
Characteristic 1 = M
Characteristic 2 = BS
Characteristic 3 = A

**Whirlwind**
Characteristic 1  = M
Characteristic 2 = BS
Characteristic 3 = A

**Vindicator**
Characteristic 1  - M
Characteristic 2 - BS
Characteristic 3 - A

**Comment by Technoblazed** [comment]
We're actually changing characteristic layouts to match the new format in the codexes and IA book. Here's a rough example but they'll be done at some point soon:

![image](https://i.tech-no.me/2020/12/09/201209091115.png)

**Comment by Lairdd1989** [comment]
Great to hear.

Feel free to close or leave open just in case others report similar request.
