### ISSUE TITLE
Bug report: Necrons v79 - Plasmacyte

### ISSUE THREAD

**Issue by Samus666** [BSData/wh40k-9e#9005]
**File/Catalogue:** Necrons datasheets

**BattleScribe version:** 2.03.25.338

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Plasmacytes should not fill a **slot** if there is already another destroyer cult unit in such detachment. In addition, there can be only one plasmacyte per destroyer  cult unit. Destroyer cult units >= plasmacytes

**Comment by Valorcalls** [comment]
Plasmacytes should be in no force org if you have destroyer cult units.
