### ISSUE TITLE
Chaos Knights Relic

### ISSUE THREAD

**Issue by DudeChris33** [BSData/wh40k-9e#9014]
**File/Catalogue:** Chaos Knights v55

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** Chaos Knights relic Gauntlet of Ascension has no description. I have it in a Super-Heavy Detachment using the heirloom stratagem and the other relics have descriptions

**Comment by Mad-Spy** [comment]
The Relics which replace weapons change out the weapon profile on the model. They don't have (or really need) a separate description.

![image](https://user-images.githubusercontent.com/29306451/101892840-ccfc7980-3b9b-11eb-8a28-90b61391d47d.png)
