### ISSUE TITLE
Aeldari - Craftworlds - Hornet Weapon selection issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9019]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** The Craftworlds Hornet cannot select anything other than Shuriken Cannons as weapons.

**Comment by FarseerVeraenthis** [comment]
This is RAW until Forgeworld release an FAQ.
Sorry...
