### ISSUE TITLE
Problem with Lord Inquisitor Hector Rex Warlord Trait

### ISSUE THREAD

**Issue by BrotherLogos** [BSData/wh40k-9e#9024]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
When using Hector Rex as your Warlord, or giving him a warlord trait using the stratagem "Inquisitorial Mandate" it does not give you any options to select a trait.

**Comment by Technoblazed** [comment]
Correct. You are forced to take Inspiring Leader as the warlord trait for Rex.

**Comment by Technoblazed** [comment]
Update, I've found an issue regarding the mandate and that will be fixed in the next release.
