### ISSUE TITLE
Imperium - Raven Guard: Token of Brotherhood not working for RG successors

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9032]
**File:** Imperium - Raven Guard.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** When I select a Raven Guard successor chapter, I cannot use the "Token of Brotherhood" stratagem which lets a successor borrow a Raven Guard relic. Weirdly, it only appears as an option if I select the Raven Guard themselves.

**Comment by acebaur** [comment]
Unable to replicate this
