### ISSUE TITLE
Chief Librarian Tigurius cannot select psychic powers from the Indomitus discipline

### ISSUE THREAD

**Issue by SenshiKenpachi** [BSData/wh40k-9e#9034]
**File/Catalogue:** v9.1.6

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Chief Librarian Tigurius cannot select psychic powers from the Indomitus discipline. ref: "It knows Smite and either three psychic powers from the Librarius discipline or three psychic powers from the Indomitus discipline."

**Comment by acebaur** [comment]
Already fixed on master
