### ISSUE TITLE
It seems the Warhammer 40k 9th Edition data can't be accessed by the Windows/Android apps.

### ISSUE THREAD

**Issue by Ratstail91** [BSData/wh40k-9e#9036]
**File/Catalogue:** Warhammer 40,000 9th Edition

**BattleScribe version:** 2.03.

**Platform:** Windows/Android, possibly others

**Dropbox:** No

**Description:** I'm unable to load or refresh data from the repository on my android phone or windows computer. This seems to be only affecting Warhammer 40k 9th edition files.

**Comment by Technoblazed** [comment]
Related to https://github.com/BSData/wh40k/issues/1706
