### ISSUE TITLE
Ultramarines chaplain cassius issues

### ISSUE THREAD

**Issue by rashius87** [BSData/wh40k-9e#9037]
**File/Catalogue:** 
Ultramarines chaplain cassius bs is incorrect. As per 40k app he is 2+ not 3+.

Also too many selected error is given when choosing correct number of litanies.

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
[
![Screenshot_20201215-084852_WH 40K](https://user-images.githubusercontent.com/76053253/102224685-435aed80-3eb4-11eb-9ddd-c619797a6e3c.jpg)
](url)

**Comment by rashius87** [comment]
2+ bs. Showing 3+

**Comment by rashius87** [comment]
Warlord trait warden of mccrage also displays when not selected as warlord.

**Comment by Technoblazed** [comment]
The app is incorrect, we don't recommend using that as a good "source" with all of the mistakes. He is BS3.

**Comment by Dunamis55** [comment]
![image](https://user-images.githubusercontent.com/36267768/102224937-816d0700-3ede-11eb-9758-f2e1b41c2f18.png)
Book has him listed as BS3+ and there's been no FAQ to update him. The official app is incorrect as a result.

**Comment by acebaur** [comment]
Also the litanies should be fixed on master

**Comment by rashius87** [comment]
Thank you for your time. Appreciate it.
