### ISSUE TITLE
Imperium - Ultramarines: Sevrin Loth has incorrect profile

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9039]
**File:** Imperium - Ultramarines.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Hi,

Not necessarily limited to ultramarines but servrin Loth of the red scorpions has some problems. He is listed at 150 points when he is actually  135. He also should only get 2 casts and 2 denies as he has the same datasheet as a primaris librarian with chapter command (chief librarian). It also appears as a bug if you give him any chapter specific powers but i believe this should be allowed (him accessing the indomitus discipline if you play red scorps as ultramarines sucessors for example). 

Thanks for everything, you are all great!

**Comment by Dunamis55** [comment]
All issues duplicated in #9060
