### ISSUE TITLE
Imperium - Astra Militarum: Heavy Mortar Battery missing ability

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9041]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 3.21.16

**Platform:** Windows

**Dropbox:** No

**Description:** Heavy Mortar Battery is missing ability Artillery and Crew: "Each Heavy Mortar and its crew are treated as a single model for all rules purposes (crew models must remain within 1" of their Heavy Mortar model). This means that the crew models cannot be targeted or attacked separately and that visibility and all ranges are measured to and from the Heavy Mortar's model, not the crew models. This unit cannot Advance, is never eligible to charge or Heroically Intervene, and cannot make pile-in or consolidation moves."

**Comment by Technoblazed** [comment]
Fixed as part of https://github.com/BSData/wh40k/issues/8667
