### ISSUE TITLE
Hornets can now properly have other weapon options

### ISSUE THREAD

**Issue by enhanced94** [BSData/wh40k-9e#9046]
**File/Catalogue:**  Warhammer 40k

**BattleScribe version:** 2.03.21.166

**Platform:** All

**Dropbox:** -

**Description:** Until now, BS did not show all the weapon options for Craftworlds Hornets as there was a typo on Imperial Armour Compendium. More specifically, Hornets did not have Hornet Pulse Laser as baseline weapons, so they cannot change it to the other heavy weapon options on BS.
As you can see from the new FAQ 17/12/20 (https://www.warhammer-community.com/wp-content/uploads/2020/12/TG5TwX0VYl8BM5pK.pdf) they now do have a Hornet Pulse Laser as base weapon, so they can have the other weapon options.

Below you can see how it is now, only showing shuriken cannons and nothing else.
![hornets](https://user-images.githubusercontent.com/74932658/102523083-6265a500-4097-11eb-90ba-6ce6626f0e15.png)

Lastly, the Hornet Pulse Laser profiles must be updated, as it got changed in the Imperial Armour Compendium.

Thank you

**Comment by Technoblazed** [comment]
Will be fixed as part of https://github.com/BSData/wh40k/issues/9045
