### ISSUE TITLE
Doom glaive not appearing in legends/ index option in army builder elite. not a copy of #8928

### ISSUE THREAD

**Issue by CaptianFordo** [BSData/wh40k-9e#9052]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by CaptianFordo** [comment]
Sorry I created this as I dont know if comments on closed threads are seen.  Yeah when I was trying to use the elite slot and the legends was switched on I cannot access its data sheet. This isn't a copy as the previous asked why it wasnt displaying however I clicked the suggested filter

**Comment by CaptianFordo** [comment]
Sorry grey knights option

**Comment by tekton** [comment]
Duplicate of #8945
