### ISSUE TITLE
Death Guard Plague Marines

### ISSUE THREAD

**Issue by DudeChris33** [BSData/wh40k-9e#9053]
**File/Catalogue:** Death Guard v106

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** When you make the plague marine squad have only "Plague Marine w/ Melee Weapon"s and the Plague Champion, it does not let you have an Icon of Despair.

**Comment by Mad-Spy** [comment]
As per the datasheet, only Plague Marines with bolt guns or 2 plague knives can carry the Icon. If you don't have any of those in your squad you can't take one.
