### ISSUE TITLE
IMPERIAL ARMOUR COMPENDIUM - rule amendments 

### ISSUE THREAD

**Issue by pawmiszczyk** [BSData/wh40k-9e#9056]
**File/Catalogue:** 

**BattleScribe version:** v2.03.21.166

**Platform:** Windows

**Dropbox:** /No

**Description:** As you all probably know, there was an update released for IMPERIAL ARMOUR COMPENDIUM. Some Chaos toys are once again available for Death Guards and 1000 Sons. If those could be added back we would be much appreciated.

Thank you for your work! HMerry Christmas or whatever you are celebrating and Happy New Year!

**Comment by Technoblazed** [comment]
Fixed in next release.
