### ISSUE TITLE
Imperium - Adeptus Astartes: Infiltrator Comms Array not showing any weapons

### ISSUE THREAD

**Issue by Citronnade** [BSData/wh40k-9e#9065]
**File/Catalogue:** Imperium - Adeptus Astartes (tested on v29 of White Scars, v172 overall, release v9.1.7)

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:**  When adding an Infiltrator Comms Array to a unit of Infiltrators, the selection is missing the "Selections:" row that would contain its weapons (Bolt pistol, Frag & Krak grenades, Marksman bolt carbine).  These correctly show up for the rest of the selections (Infiltrator, Infiltrator Helix Adept, and Infiltrator Sergeant).

**Comment by Mad-Spy** [comment]
Fixed in next release. Neither this option nor the Helix Gauntlet are separate models any longer (they are wargear), and shouldn't be included as such.
