### ISSUE TITLE
Shadowsun missing weapon profile

### ISSUE THREAD

**Issue by Alex-40k** [BSData/wh40k-9e#9066]
**File/Catalogue:** T'au empire 

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:** Shadowsun is missing her Dispersed Fusion Blaster profile, currently only shows the high energy shot.

**Comment by Technoblazed** [comment]
Did you actually equip any of the dispersed fusion blasters on her?

**Comment by Alex-40k** [comment]
Dang
