### ISSUE TITLE
Codex: SM & Index DA. 

### ISSUE THREAD

**Issue by miku2020** [BSData/wh40k-9e#9072]
**File/Catalogue:** Imperium - Adeptus Astartes - Dark Angels v186

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** 

Primaris Chaplain on Bike has Infantry keyword, which it shouldn't have. 

none of the Dark Angels Index units have Angels of Death Rule in them, which they should.

**Comment by FarseerVeraenthis** [comment]
Thanks for letting us know :+1:
