### ISSUE TITLE
SM - Deathwatch - Hunter missing from Heavy Support list

### ISSUE THREAD

**Issue by ishootzdaface** [BSData/wh40k-9e#9073]
**File/Catalogue:** Imperium - Adeptus Astartes - Deathwatch v112

**BattleScribe version:** 2.03.21

**Platform:** Windows + Andriod

**Dropbox:** No

**Description:** 
Under the Heavy Support options, Hunter is not a unit choice that can be selected. So far, this is only missing in the Deathwatch Supplement. Replicated on Android app.

**Comment by Technoblazed** [comment]
Fixed in next release.
