### ISSUE TITLE
Death Watch Kill Team Specialism costs

### ISSUE THREAD

**Issue by MCSocrates** [BSData/wh40k-9e#9077]
**File/Catalogue:** Death Watch

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** Yes/No

**Description:** The costs for the Death Watch Kill Team specialisms are higher than noted in the codex supplement.  Understandable since the codex supplement has two points values, but a faq has come out clarifying which costs to use.

**Comment by Valorcalls** [comment]
Please update your data.
