### ISSUE TITLE
"Show Primaris Only" missing

### ISSUE THREAD

**Issue by SenshiKenpachi** [BSData/wh40k-9e#9079]
**File/Catalogue:** All Space Marines

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** There is no "Show Primaris Only" option anymore - this was one of the most useful settings, please bring it back =)

**Comment by acebaur** [comment]
Unfortunately SM is causing slow loading again, so we are trimming unnecessary things. It won't be added back
