### ISSUE TITLE
[SW] Problem with chaplains selection of litanie & Master of sanctity 

### ISSUE THREAD

**Issue by Rortak** [BSData/wh40k-9e#9082]
**File/Catalogue:** 

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes [https://drive.google.com/file/d/16drcotz2rlf_qoRe-hEOEB1ZqWIbwerr/view?usp=sharing](url)

**Description:** When selecting the option on a space wolves v172

- [ ] chapter command : master of sanctity  . 1PL 25pts

an error apears when selecting the second litanie : "Chapelain has 1 too many selections from litanies (maximum 2)"

I tryed it wth every entrance of chaplain ; terminator, primaris, on bike... The error comes on evry entrance. (see screenshot on drive file)

**Comment by Mad-Spy** [comment]
Should be fixed in SW v175, which was released 4 hours ago. Update your data tomorrow.
