### ISSUE TITLE
Imperium - Adeptus Custodes: Venatari PL cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9083]
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Venatari are listed at 20PL for a 3 man squad on battlescribe. I'm assuming this is an error as based on their 165 point cost they should be 8. They're PL score has also been adjusted to 8 in the FW IA compendium update.

**Comment by Thairne** [comment]
![grafik](https://user-images.githubusercontent.com/8590840/103151803-ad5f7680-4781-11eb-87f6-7d509934d3cc.png)
