### ISSUE TITLE
DKOK Death Rider Command Squadron Battlefield Role Slot w/ Commander

### ISSUE THREAD

**Issue by battosai** [BSData/wh40k-9e#9085]
**File/Catalogue:** Imperium - FW Death Korps of Krieg.cat

**BattleScribe version:** 2.03.25.338

**Platform:** Android

**Dropbox:** No

**Description:** The DKOK Death Rider Command Squadron still takes up a battlefield role slot even if the detachment includes a Death Rider Squadron Commander. They should not take up a slot in this case as per the "Command Squadron" rule they have.

**Comment by Technoblazed** [comment]
You need to select the Command Squadron from the No Force Org Slot.
