### ISSUE TITLE
Blood angels sanguinary discipline missing

### ISSUE THREAD

**Issue by R1ven36** [BSData/wh40k-9e#9087]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
Blood angels psychic discipline is not available to select powers from.
Tested with Mephiston, lib dreadnought and primaris lib.
Force org chapter selected as blood angels and successors

**Comment by R1ven36** [comment]
Blood angels librarians do not have access to sanguinary discipline when selecting powers. Chapter has been selected as blood angels

**Comment by alphalas** [comment]
We know; the codex update isn’t done.
