### ISSUE TITLE
DKOK Marshal can only select from 2 Heirlooms of Conquest as Warlord

### ISSUE THREAD

**Issue by battosai** [BSData/wh40k-9e#9089]
**File/Catalogue:** Imperium - FW Death Korps of Krieg.cat

**BattleScribe version:** 2.03.25.338

**Platform:** Android

**Dropbox:** No

**Description:** DKOK Marshal only has the options of "Blade of Conquest" or "Deathmask of Ollanius" for Heirlooms of Conquest when selected as warlord. Should also have access to some other Infantry/Officer relics.

**Comment by Technoblazed** [comment]
Fixed in next release.
