### ISSUE TITLE
Imperium - Astra Militarum: Bullgryn Bone 'ead "Weapon" choices show the "Shield" choices

### ISSUE THREAD

**Issue by GCSChris** [BSData/wh40k-9e#9090]
**File/Catalogue:** Imperium - Astra Militarum.cat

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** Yes

**Description:** Rather than show "Bullgryn maul" and "Grenadier gauntlet" as the weapon choices, it shows Brute Shield and Slab Shield. This only happens for the Bullgryn Bone 'ead, not normal Bullgryn.

**Comment by Dunamis55** [comment]
Consolidated into #9095
