### ISSUE TITLE
Scion w/ Special Weapon Hot-Shot Volley Gun cost

### ISSUE THREAD

**Issue by battosai** [BSData/wh40k-9e#9091]
**File/Catalogue:** Imperium - Astra Militarum.cat

**BattleScribe version:** 2.03.25.338

**Platform:** Android

**Dropbox:** No

**Description:** Hot-Shot Volley Gun for Scion w/ Special Weapon costs 7pts, should be 5pts.

**Comment by Dunamis55** [comment]
Consolidated into #9095
