### ISSUE TITLE
Scion w/ Special Weapon must have Hot-shot Volley Gun

### ISSUE THREAD

**Issue by raimarL** [BSData/wh40k-9e#9093]
**File/Catalogue:** 

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 

Since the last update, it is no longer possible to assign a special weapon other than Hot-shot Volley gun (e.g. meltgun) to a scion. There is always a validation error "Scion w/ Special Weapon must have 1 more selections of Hot-shot Volley Gun (minimum 1 each)". However, scions can freely chose their special weapons and are not obliged to take Hot-shot Volley-Gun. Furthermore, the point costs of the Hot-shot Volley Gun are wrong (7 pts, should be 5 pts). The issue completely breaks astra lists including scions created before the update, too!

**Comment by Nboaram** [comment]
Yup, seconding this, is making my scions list even more hard mode. Psychic Maelstrom also has a spelling mistake. It says "you can ten roll another die"

**Comment by Dunamis55** [comment]
Consolidated into #9095
