### ISSUE TITLE
AM / DKoK / EDT - Imperial Armour Compendium / Legends - Initial QA Pass

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#9094]
**File/Catalogue:** Imperium - Astra Militarium v296 / Imperium - Elysian Drop Troops v93 / Imperium - Death Korps of Krieg v142

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 

**_Death Korps of Krieg_**

- [x] Death Korps Marshal currently has a Ld characteristic of 8, but should be 9
- [x] Combat Engineer Squad > Combat Engineers should be equipped with an Engineer shotgun by default
- [x] Combat Engineer Squad > Combat Engineers should not be able to unequip or take multiple Engineer shotguns
- [x] Mole launcher has incorrect ability text and should read as “Blast. This weapon can target units that are not visible to the bearer.”
- [x] Death Korps Marshal Karis Venner [Legends] is missing their Voice of Command ability
- [x] Death Korps Grenadier Squad [Legends] > Death Korps Grenadier Weapons Team can take multiple hot-shot lasguns, but shouldn’t be able to take any at all
~~- [ ] Death Rider Commissar [Legends] is missing his Cult of Sacrifice ability~~
- [x] Death Rider Commissar [Legends] is unable to swap his laspistol for a hot-shot lasgun
- [x] Quartermaster Cadre > Quartermaster Revenant’s medi-pack (Aura) currently costs 5 points, but should cost 0 points
- [x] Quartermaster Cadre > Quartermaster Revenant’s hot-shot laspistol currently costs 0 points, but should cost 20 points

**_Elysian Drop Troops_**

- [x] Breacher charge [Legends] is missing from the Special Weapons options for:
1. Infantry Squad > Guardsman w/ Special Weapon
1. Command Squad > Veteran w/ Special Weapon
1. Special Weapons Squad > Guardsman w/ Special Weapon
1. Veterans > Veteran w/ Special Weapon
- [x] Lascutter [Legends] is missing from the Special Weapons options for:
1. Infantry Squad > Guardsman w/ Special Weapon
1. Command Squad > Veteran w/ Special Weapon
1. Special Weapons Squad > Guardsman w/ Special Weapon
1. Veterans > Veteran w/ Special Weapon

**_Astra Militarium_**

- [x] Carnodon’s Explodes ability currently has a 6” range, but should be D6” range
- [ ] Several units can take Tank Aces even when no Warlord has been taken:
1. Armageddon-pattern Basilisk > Armageddon-pattern Basilisk
1. Valdor Tank Hunter
1. Macharius
1. Macharius Vanquisher
1. Macharius Vulcan
1. Praetor
1. Crassus
1. Stormblade
1. Arkurian Stormhammer [Legends]
1. Dominus Armoured Siege Bombard [Legends]
1. Gorgon Heavy Transport [Legends]
1. Macharius Omega [Legends]
- [x] Malcador’s Wound Tracker [2] currently has a WS characteristic of 5+, but should be 6+
- [x] Malcador’s Wound Tracker [2] currently has a BS characteristic of 4+, but should be 5+
- [x] Vendetta hellstrike rack currently has an S characteristic of 9, but should be 8
- [x] Vendetta hellstrike rack currently has an AP characteristic of -3, but should be -2
- [x] Vendetta hellstrike rack currently has a D characteristic of D6, but should be D6+2
- [x] Vendetta Gunship can take 1 heavy bolter, but should only be able to 0 or 2 heavy bolters
- [x] Vendetta Gunship is missing its transport rules
- [x] Adamantium tracks are missing for:
1. Macharius
1. Macharius Vanquisher
1. Macharius Vulcan
- [x] Steel Behemoth ability text has multiple unnecessary line breaks in it for:
1. Macharius
1. Macharius Vanquisher
1. Macharius Vulcan
1. Praetor
1. Crassus
1. Minotaur
1. Arkurian Stormhammer [Legends]
1. Dominus Armoured Siege Bombard [Legends]
1. Gorgon Heavy Transport [Legends]
1. Macharius Omega [Legends]
- [x] Several units’ Explodes ability currently occurs on a 6, but should be a 6+:
1. Hades Breaching Drill
1. Valdor Tank Hunter
1. Macharius
1. Macharius Vanquisher
1. Macharius Vulcan
1. Praetor
1. Crassus
1. Minotaur
- [x] Marauder Bomber’s inferno bomb ability should have capitalised keywords so that it reads as: “Once per turn, if the bearer has any inferno bombs remaining, it can drop one of them. Immediately after the bearer has moved, you can select one point on the battlefield the bearer moved across this phase. Roll one D6 for each unit within 9" of that point, subtracting 1 if that unit is a CHARACTER (excluding VEHICLE and MONSTER units): on a 4+, that unit suffers D3 mortal wounds. Each inferno bomb can only be dropped once per battle.”
- [x] Stormblade’s Stormblade plasma blastgun – standard has a profile name of “Plasma Blastgun, Standard”, but should be “Stormblade plasma blastgun – standard”
- [x] Stormblade’s Stormblade plasma blastgun – supercharge has a profile name of “Plasma Blastgun, supercharged”, but should be “Stormblade plasma blastgun – supercharge”
- [x] Tarantula Battery is unable to be taken, but should be in the Fortification unit options
- [x] Quartermaster Cadre Squad > Medicae-servitor has its reference as “Imperial Armour: Compendium”, but should be “Warhammer Legends”
- [x] Mukaali Riders [Legends] can be taken in Regiments that aren’t Astra Militarum or Tallarn
- [x] Salamander Scout Tanks currently cost 3 PL regardless of the number of models, but should cost 4/6/9 PL
- [x] Manticore Battery [Legends] currently has a Move characteristic of +, but should be –
- [x] Sabre Weapons Battery [Legends] currently has the Explodes ability, but shouldn’t have
- [x] Arkurian Stormhammer [Legends] > Stormhammer cannon currently has a D characteristic of 2D2, but should be 2D3
- [x] Dominus Armoured Siege Bombard [Legends] > Dominus Triple Bombard Stationary weapon profile should have the following ability text: “Blast. This weapon can target units that are not visible to the bearer. You can only select the stationary bombardment profile if the bearer Remained Stationary in your previous Movement phase.”
- [x] Macharius Omega [Legends] currently has a WS characteristic of 6+, but should be 5+
- [x] Macharius Omega [Legends] currently has a Strength characteristic of 7, but should be 8
- [x] Macharius Omega [Legends]’s Wound Track [1] currently has an Attacks characteristic of 6, but should be 3
- [x] Macharius Omega [Legends]’s Wound Track [2] currently has an Attacks characteristic of D6, but should be D3
- [x] Macharius Omega [Legends]’s Wound Track [3] currently has an Attacks characteristic of D3, but should be 1
- [x] Macharius Omega [Legends] can currently take 2 heavy stubbers, but should be 2 heavy bolters
- [x] Imperial Fortress Walls [Legends] currently cost 10 PL per gate tower section, but should be 10 PL per 2 gate tower sections
- [x] Primaris Redoubt [Legends] Wrecked ability currently has a range of 9” and deals D6 mortal wounds, but should have a range of 6” and deal D3 mortal wounds
- [x] Salamander Scout Tanks currently cost 55 points per model, but should be 75 points per model

**Comment by Technoblazed** [comment]
Fixed in next release.
