### ISSUE TITLE
Astra Militarum - Default wargear options QA pass

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#9095]
**File/Catalogue:** Imperium - Astra Militarum v296

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [x] Gryphonne Pattern Chimera should have a twin heavy bolter as a turret weapon by default
- [x] Manticore should have a heavy bolter as a hull weapon by default
- [x] Rough Riders [Legends] > Rough Rider Sergeant should have a laspistol and chainsword by default
- [x] Veterans should have 9 Veterans w/ Lasgun by default
- [x] Veterans > Veteran Sergeant should have a laspistol by default
- [x] Veterans > Veteran Sergeant should not throw an error if no melee is equipped
- [x] Veterans have frag grenades in their profile, but are not showing them as equipped weapons on the unit list
- [x] Servitors should have 4 Servitor (Servo-arm) by default
- [x] Platoon Commander should have a laspistol equipped by default
- [x] Ogryn Bodyguard should have a ripper gun and a huge knife equipped by default
- [x] Militarum Tempestus Command Squad > Tempestus Scion is equipped with a hot-shot volley gun by default, but should be equipped with a hot-shot lasgun by default
- [x] Militarum Tempestus Command Squad > Tempestus Scion should not throw an error when a weapon is taken that isn't a hot-shot volley gun
- [x] Militarum Tempestus Command Squad > Tempestus Scion's hot-shot volley gun currently costs 7 points, but should cost 5 points
- [x] Commissar should be equipped with a bolt pistol by default
- [x] Command Squad should have 4 Veterans by default
- [x] Command Squad > Veteran should be equipped with a lasgun by default
- [x] Bullgryns > Bullgryn should be equipped with a grenadier gauntler and a slabshield by default
- [x] Bullgryns > Bullgryn Bone’ead should be equipped with a grenadier gauntler and a slabshield by default
- [x] Bullgryns > Bullgryn Bone’ead’s Weapons wargear options are listed as brute shield and slabshield, but should list grenadier gauntlet and Bullgryn maul
- [x] Astropath should be equipped with a Telepathica stave by default
- [x] Infantry Squad should have 9 Guardsman by default
- [x] Infantry Squad > Sergeant should be equipped with a laspistol by default
- [x] Lord Commissar should be equipped with a bolt pistol and power sword by default
- [x] Lord Commissar can take a power sword an unlimited number of times, but should only be able to take it once. In addition, power sword is listed twice in the same weapons options list.
- [x] Company Commander should be equipped with a laspistol by default
- [x] Company Commander should not throw an error if no melee is equipped

**Comment by Technoblazed** [comment]
Fixed for next release.
