### ISSUE TITLE
Space Marines Tome of Malcador

### ISSUE THREAD

**Issue by DudeChris33** [BSData/wh40k-9e#9098]
**File/Catalogue:** Iron Hands v31

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** The Tome of Malcador relic does not increase the number of psychic powers known. (The error message still shows up)

**Comment by acebaur** [comment]
It is working as intended. Make sure you aren't selecting from more than one discipline

**Comment by DudeChris33** [comment]
That was it my bad
