### ISSUE TITLE
Named inquisitors (Coteaz, Eisenhorn, etc) can't take WLTs

### ISSUE THREAD

**Issue by GuillermoDiazGarcia** [BSData/wh40k-9e#9103]
**File/Catalogue:** Inquisition

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:**
Named inquisitors, such as Hector Rex, Coteaz, Eisenhorn..... can't take warlord traits, either when made warlords or when given the Inquisitorial Mandate stratagem. I'm not sure why Hector can't take one, but the others should be able to choose their assigned WLT in Pariah

**Comment by Technoblazed** [comment]
All of the named characters have their forced WLTs included on their profiles, not something that you can select.
