### ISSUE TITLE
Adepta Sororitas Geminae Superia cost incorrect

### ISSUE THREAD

**Issue by Sayle** [BSData/wh40k-9e#9104]
**File/Catalogue:** 

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** 

**Description:** The power sword cost is not added to the Geminae Superia cost. The base cost of 18pts is correct, but the power sword should cost an additional 5pts.

**Comment by Mad-Spy** [comment]
Their cost _includes_ their wargear, as per p16 of MFM2020.
