### ISSUE TITLE
Imperium - Ultramarines: Silver Templar Relics not visible with Templars Warlord

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9106]
**File:** Imperium - Ultramarines.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Hey, just reporting some missing data. Silver Templar Relics have not been included. The Chapter Tactic and Warlord Traits have been but not the Relics.

**Comment by Technoblazed** [comment]
Hide modifier on the Silver Templars relic selector isn't including child selections.
