### ISSUE TITLE
Scion special weapon issue (V2)

### ISSUE THREAD

**Issue by Tim-Sleigh** [BSData/wh40k-9e#9110]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** Yes/No

**Description:** 

Unit of 10 Scions.
1 Tempestor, 1 Vox Scion, 6 meat sack scions and 2 special weapon scions.
Options for special weapons display, but when you select anything other than Hot shot volley guns, you get an error.
Using roster 9th Ed, V173

**Comment by Tim-Sleigh** [comment]
Unit of 10 Scions.
1 Tempestor, 1 Vox Scion, 6 meat sack scions and 2 special weapon scions.
Options for special weapons display, but when you select anything other than Hot shot volley guns, you get an error.
Using roster 9th Ed, V173
(Previous submission stuffed when submitting. version 2)

**Comment by Technoblazed** [comment]
Already fixed in next release

**Comment by Tim-Sleigh** [comment]
Thanks
