### ISSUE TITLE
Chaos - Chaos Space Marines: Supreme Command Detachment showing no units and seems to want both Primarchs and Regular HQ

### ISSUE THREAD

**Issue by Enderborn6th** [BSData/wh40k-9e#9111]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Mac

**Dropbox:** No

**Description:** I was trying to make an army including a Supreme Command Detachment, but I really can't since theres no option to pick a unit other than the options Configuration and Stratagem. Along with this, the requirements demand I add both a Primarchs and some regular HQs. I am unsure if this issue extends to the other armies, though I am sure it is effecting Chaos Space Marines.

**Comment by Mad-Spy** [comment]
Please re-read the current rules for Supreme Command Detachments. CSM do not have any units which can be in such a Detachment.
