### ISSUE TITLE
Space Wolves Missing Named HQs/Characters

### ISSUE THREAD

**Issue by JamieWizard** [BSData/wh40k-9e#9112]
**File/Catalogue:**  - Space wolves

**BattleScribe version:** 2.03. - Latest

**Platform:** Windows/iOS/Android/Mac/Linux - All I think

**Dropbox:** No

**Description:**
We are still missing the named HQs/Characters in the Space Wolves 9th Codex. I have been patiently waiting but wasn't sure you knew. Can we pretty please have them back! This appears to be an issue in all the OS Platforms  :-D

**Comment by Valorcalls** [comment]
Please go into the chapter selection and select space wolves as your chapter.
