### ISSUE TITLE
Imperium: Astra Militarum - Tank Commander Sponson Weapons show Heavy Flamers costing 10pts

### ISSUE THREAD

**Issue by 0K-Jeff** [BSData/wh40k-9e#9113]
**Tank Commander, Astra Militarum** 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Selecting a Sponson weapon for the Tank commander costs 30pts for Heavy bolters, but 10 for Heavy Flamers - both are normally 15pt weapons, so a pair should cost 30pts.

**Comment by Technoblazed** [comment]
Fixed in next release.
