### ISSUE TITLE
Drukhari Obsession does not match with some unit selections

### ISSUE THREAD

**Issue by raimarL** [BSData/wh40k-9e#9116]
**File/Catalogue:** 

**BattleScribe version:** 2.03.21

**Platform:** Mac

**Dropbox:** No

**Description:** 

If you chose a Kabal Obsession (e.g. Kabal of the Black Heart or just Custom Kabal), you can still take a Cronos from Heavy Support. However, the Cronos has "Faction: <Haemonculus Coven>" just like e.g. the Talos and should only be available for Covens.

On the other hand, the Razorwing Jetfighter is not available for Coven, but has no tag that links it to an obsession. Therefore, it should be a viable choice for any Coven Obsession.

**Comment by Valorcalls** [comment]
Razorwings are restricted as per their datasheet in the codex for who can take them. 

Meanwhile the Chronos part is correct, Kabal should not be able to see them. However when you select a Chronos to the list, it does the reverse and hides everything covens can't take, as well as throwing an error if you have kabal taken.

**Comment by FarseerVeraenthis** [comment]
Yeah, I'll see what I can do but it could be tricky to implement fully in BS because of the way category show/hide works...

**Comment by FarseerVeraenthis** [comment]
that was a cheeky wotsit to figure out with the Chronos...
