### ISSUE TITLE
WH 40k v9.1.3 Ork Nob should have Nob Arm2 maximum of 1

### ISSUE THREAD

**Issue by GrimlockZ** [BSData/wh40k-9e#9117]
**File/Catalogue:** Warhammer 40k 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** When attempting to give a Bos Nobb a weapon on Nob Arm2, any selection is incorrect except (None). The Boss Nob should have access to a variety of melee weapons instead and also be able to take a weapon on Nob Arm 1.
v173

**Comment by GrimlockZ** [comment]
Thank you.

**Comment by GrimlockZ** [comment]
When attempting to give a Bos Nobb a weapon on Nob Arm2, any selection is incorrect except (None). The Boss Nob should have access to a variety of melee weapons instead and also be able to take a weapon on Nob Arm 1.

**Comment by Technoblazed** [comment]
Please provide a better report, you’re also weeks behind the latest data, we’re on v9.1.8 now.

**Comment by Technoblazed** [comment]
Works fine for me. Update your data. 

![Image](https://i.tech-no.me/2020/12/29/201229104450.png)
