### ISSUE TITLE
Imperium Astra Militarum Tempestus incorrect Wargear Requirements

### ISSUE THREAD

**Issue by njawlf** [BSData/wh40k-9e#9120]
**File/Catalogue:** Imperium, Astra Militarum

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** Yes/No

**Description:** Militarum Tempestus Command Squads when added to a list spawn with Hot-shot Volley-guns instead of Hot-shot Las-guns and even if you then give them a different weapon you get a Validation Error stating they must be equipped with a Hot-shot Volley-gun. This only happens to the "normal" scions in the squad the ones with the Vox, Medi-pack, and Platoon Standard don't have this problem

**Comment by Technoblazed** [comment]
Already fixed in next release.
