### ISSUE TITLE
Imperium - Astra Militarum: Salamander Scout Tank entry has incorrect cost

### ISSUE THREAD

**Issue by waefre1** [BSData/wh40k-9e#9123]
**File/Catalogue:** Imperium - Astra Militarm

**BattleScribe version:** 2.03.21.166

**Platform:** Windows/Linux

**Dropbox:** No

**Description:** Salamander Scout Tanks are wonkily costed - they should be 75 pts base but the individual tanks are only costed 55 pts base. Additionally, the entry appears to be costed at 75 pts base even when there are no tanks in the squadron (in the attached screenshot, Salamanders were bought from the left-hand pane twice, and the lower entry had its Salamander deleted so that the squad had no vehicles in it).

![sst_cost1](https://user-images.githubusercontent.com/7123699/103330913-2df3d080-4a29-11eb-9526-7d0c7e8b2380.PNG)

**Comment by Technoblazed** [comment]
Already fixed in next release
