### ISSUE TITLE
Lib - Space Marines: Venerable dreadnought is missing bolter/flamer option on claw/great axe and shield

### ISSUE THREAD

**Issue by DrColm** [BSData/wh40k-9e#9124]
**File/Catalogue:** 

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Hi new to this website, and I am also dyslexic, so I am sorry if I am doing this wrong or if it reads oddly.
So under the space wolves ven dread data sheet on battle scribe, under the claw/axe and shield weapons there is no bolter when there should be (like it is with the wulfen dread who has a bolter on his claw/axe and shield which are the same weapons as the venerable dreds, like they are the same arm and building instructions for these weapons and they say to put a bolter or flamer on both)
The data sheet says:
"• If this model is from the Space Wolves Chapter (or one of its successor Chapters), its **Dreadnought combat** weapon can be replaced with 1 great wolf claw.
 • If this model is from the Space Wolves Chapter (or one of its successor Chapters), its assault cannon and **Dreadnought combat** weapon can be replaced with 1 Fenrisian great axe and 1 blizzard shield."
see how it does not say to replace the bolter with the combat weapon. You can see earlier in the data sheet that it would say to also remove the bolter like it does for other weapons on the data sheet e.g.:
"his model’s **Dreadnought combat weapon and storm bolter** can be replaced with one of the following:
  - 1 missile launcher.
  - 1 Dreadnought combat weapon and 1 heavy flamer."

 I hope I have explained this well. also as a side note because of the way it reads on the sheet replace a "dreadnought combat weapon" and the sheet does list a "dreadnought combat weapon and 1 heavy flamer" as a option before adding the bit "if your detachment is from space wolves" I think it means you can also take the heavy flamer on the claw/axe as well but that is less clear. 
However if it helps in the space wolves codex which is newer, it does list the the claw/axe and shield as being able to take the heavy flamer or a bolter and I believe the rule for weapons like this is that if a codex changes a weapon (which I think this counts as a change for the weapon, the space marine codex one being the old version and the one in the space wolf codex being the newer version) but yea i can understand if you were to say "No it should for now only have a bolter" Sorry for how long this is I am just trying to be clear, I hope this helps [<3]

Links to pictures below, for clarity:
[https://gyazo.com/14402dbe54e63a2eb9af2c37dafe84e1](url)
[https://gyazo.com/3b917d97aaad95ca0f3935936b44b034](url)
[https://gyazo.com/26b285af80050a149596bd58feb6bc26](url)
Also tried  uploading them not sure it worked tho :(
![Upload 1](https://user-images.githubusercontent.com/76765535/103334351-db3a0900-4a68-11eb-8801-e7ecd7a44d7b.png)
![Upload 2](https://user-images.githubusercontent.com/76765535/103334345-d5dcbe80-4a68-11eb-8192-84fd935e2bbb.png)
![upload 3](https://user-images.githubusercontent.com/76765535/103334347-d6755500-4a68-11eb-9238-78fb690b06f9.png)

**Comment by DrColm** [comment]
Very sorry about how messy this reads I hope I was able to get my point across. Also not very useful but still a point to be made it could take a bolter/heavy flamer in 8th, if that means anything, which I dont think it really does, but thought I would say

**Comment by DrColm** [comment]
the TLDR of the above problem: It says it is equipped with a dreadnought combat weapon AND a storm bolter, yet the axe and shield says it replaces the combat weapon (Nothing about replacing or removing the storm bolter) and because of how oddly it's written I think it mean you cant take a heavy flamer but at the same time you can also say you could cuss you can replace a combat weapon, and there are two combat weapon profiles listed before the space wolf section implying you can pick one of the two profiles. So you could read it as either way

**Comment by Mad-Spy** [comment]
OP is correct. Ven Dread _should_ have the choice of storm bolter or heavy flamer when taking a wolf claw or axe and shield, because you can use the 2nd bullet to swap to the flamer **before** replacing just the DCCW in bullet 3 or 4.

**Comment by DrColm** [comment]
Also idk if I am being a twat but when i read over my post I think one of my points kinda gets lost, one of the points is the dread lacks a bolter on battle-scribe, like it has no guns it at all on it's battle scribe sheet, when i think it should. Sorry if sounds redundant for me to say but i wanted to make sure I got that across, cuss to me when I read my post I kinda do but the point kinda gets lost.

Wanted to say you guys working on the app are truly MVPs, I think everyone who plays WH are thankful <3 happy holidays and i hope I have been helpful <3 (pic of Battle Scribe sheet below)
![image](https://user-images.githubusercontent.com/76765535/103380456-d749cd80-4ae0-11eb-902c-d84da52498fd.png)
