### ISSUE TITLE
File is missing from repositories

### ISSUE THREAD

**Issue by DudeChris33** [BSData/wh40k-9e#9126]
**File/Catalogue:** the whole thing

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** The entire data repository of Warhammer 40k 9th edition is missing
![Screenshot (63)](https://user-images.githubusercontent.com/43427245/103383792-ef055f80-4aa8-11eb-9774-0c663454bcd7.png)

**Comment by acebaur** [comment]
See #1706
