### ISSUE TITLE
Magister Sevrin Loth Points Value and Cast/Deny Incorrect (Red Scorpions)

### ISSUE THREAD

**Issue by rexmcgeed** [BSData/wh40k-9e#9127]
Warhammer 40,000 v9.1.8

**BattleScribe version:** 2.03.

Android

No

Hi,

Sevrin Loth, a HQ choice for the Red Scorpions chapter, has some issues. He is listed at 150 points but the imperial armour compendium lists him at 135. He also has 2 casts and 3 denies, but the same book lists him as a primaris chief librarian for the purposes of his psychic. So I believe he should only have 2 casts and 2 denies. 

Otherwise all good! Keep up the great work.

**Comment by acebaur** [comment]
It should be 2 casts and 1 deny per the primaris librarian entry.

**Comment by rexmcgeed** [comment]
Hi, i believe because he is listed as primaris librarian +chief librarian he gets an extra deny, alongside knowing 3 powers from his chosen discipline.

Just checked and chief librarian is listed under his abilities.

Thanks :)
