### ISSUE TITLE
Tempestus Scions Costs and special weapon requirements and Volley Gun Costs

### ISSUE THREAD

**Issue by SpearOfAchilles** [BSData/wh40k-9e#9128]
**File/Catalogue:** 

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Scion squads are requiring Hotshot Volley guns, whose price is also wrong. 

![image](https://user-images.githubusercontent.com/34262621/103422322-de1f2180-4b6e-11eb-89c5-1aed35b500e1.png)

**Comment by Mad-Spy** [comment]
Please ensure you check closed issues before raising issues here. This has been reported multiple times already.
