### ISSUE TITLE
Dark Angels Successor is missing.

### ISSUE THREAD

**Issue by DuskFae** [BSData/wh40k-9e#9131]
**File/Catalogue:** Warhammer 40k v9.1.8

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Dark Angels Successor Chapter option is missing in Chapter Select.
Currently prevents any Custom Chapter based in Dark Angels from being able to select Relics of Caliban,

**Comment by Technoblazed** [comment]
Fixed in next release.
