### ISSUE TITLE
Bulgryn Bone 'ead Equipment Choices

### ISSUE THREAD

**Issue by Pizzabagels** [BSData/wh40k-9e#9140]
Imperium Astra Militarum v296

Version - 2.03.21

Windows 10

Dropbox: No

Description: Bullgryn Bone'eads do not have the correct weapons for their loadout. In the weapon selection slot you can only pick shields and cannot equip the regular grenade launcher or maul. 

![image](https://user-images.githubusercontent.com/40036724/103449485-b955a780-4c5d-11eb-9cb6-a063c9661b6c.png)

**Comment by Technoblazed** [comment]
Update your data.
