### ISSUE TITLE
Imperium Deathwatch Stalker-pattern Boltgun

### ISSUE THREAD

**Issue by Maladictus** [BSData/wh40k-9e#9142]
**File/Catalogue:** Imperium - Adeptus Astartes - Deathwatch

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** When choosing wargear for Deathwatch Veteran as part of Proteus Kill Team points cost for Stalker-pattern Boltgun is still 5 when should be 3. Points are correct if creating squad of just Deathwatch Veterans.

**Comment by Technoblazed** [comment]
Update your data.

![Image](https://i.tech-no.me/2021/01/02/210102154014.png)
