### ISSUE TITLE
Imperium - Blood Angels: Angels Exemplar doesn't allow selection of 2 WLTs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9144]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Angels Exemplar not working correctly. When a Warlord trait is selected from the ‘Angels Exemplar WLT’ selection table, an error is returned if you have already selected a Warlord train from the normal selection. This wont allow you to have an additional Warlord Trait

**Comment by Technoblazed** [comment]
Fixed in next release.
