### ISSUE TITLE
Blood Angels Sanguinary Discipline

### ISSUE THREAD

**Issue by Andretton** [BSData/wh40k-9e#9145]
**File/Catalogue:** Blood Angels
**BattleScribe version:** 2.03.21
**Platform:** Windows
**Dropbox:** No

**Description:** The Sanguinary Psychic Discipline needs to be added for Blood Angels Librarians. Currently the only one available to Librarian Dreadnought and Mephiston. Optional for other Librarian variants.

**Comment by Technoblazed** [comment]
Fixed in next release.
