### ISSUE TITLE
Imperium - Blood Angels: Flesh Tearers relics not working

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9147]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** All Flesh Tearer relics are missing. I have correctly selected them to enable the Chapter Tactic and unlock Gabriel Seth, but their Chapter Relics (Severer and Crimson Plate) never show up as options on any valid units.
The Honoured by the Arx Angelicum strat is missing entirely.
The Angel Exemplar strat is listed as costing 0cp when it actually costs -1cp.
Angel Exemplar unlocks the Angel Exemplar WLT box on a Warlord, but selecting a trait therein makes the checker say you can only have 1 WLT (defeating the purpose of the stratagem). The purpose of the strat is to allow your unNamed Character Warlord to take 2 WLT.

**Comment by DemkoIIB** [comment]
I submitted this thinking I had already signed in. My apologies.
