### ISSUE TITLE
Blood Angels Librarian Dreadnaught Relics

### ISSUE THREAD

**Issue by SoSaltySalt** [BSData/wh40k-9e#9149]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** 
The Blood Angels Librarian Dreadnaught can take Codex, Special Issue wargear & chapter specific relics, when all the relics sections I've seen say "Named characters and Vehicles cannot take any of the following relics"
I hope it's just me misunderstanding, cause I really want a 2+/5++ on my Librarian Dread, but as I read it, I'm not allowed.

**Comment by Technoblazed** [comment]
Fixed in next release.
