### ISSUE TITLE
Bug Report: Imperium - Admech

### ISSUE THREAD

**Issue by JohnMadgob** [BSData/wh40k-9e#9150]
**File/Catalogue:** Imperium - Adeptus Mechanicus

**BattleScribe version:** 2.03.25.338

**Platform:** Windows/Android

**Dropbox:** No

**Description:**  The Onager Dunecrawler's equipment list doesn't reflect having Cognis Heavy Stubber x2 on its equipment list if it is fitted with both the Neutron Laser and Heavy Stubber turret as well as the hull-mounted Heavy Stubber. The Heavy Stubber is accurately reflected on the equipment list if either the turret or the hull weapon are chosen but the equipment list doesn't change when an Onager with the Laser/Stubber turret has the hull weapon switched on or off even though the points-cost of the vehicle does change to reflect the 5-point cost of the weapon.

**Comment by Mad-Spy** [comment]
Output is correct. Both heavy stubbers are on the output.

![image](https://user-images.githubusercontent.com/29306451/103490502-20b55800-4e14-11eb-9c5d-806e86a01c76.png)

**Comment by JohnMadgob** [comment]
Oh. You're absolutely right. My mistake. Thanks for looking into it.
