### ISSUE TITLE
Missing Death Company officer options

### ISSUE THREAD

**Issue by Kal451** [BSData/wh40k-9e#9151]
**File/Catalogue:** 
Blood Angels

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Detailed issue description.
Primaris Captain has no Death Company Option
Lieutenant has no Death Company Option
Primaris Lieutenant has no Death Company Option
Primaris Lieutenant in Phobos Armour has no Death Company Option
Primaris Lieutenant in Reiver Armour has no Death Company Option

**Comment by Technoblazed** [comment]
Blood angels isn’t finished, be patient.

**Comment by Kal451** [comment]
Ta folks. thought it had been released as some captains DO have the options! just trying to be helpful :)
