### ISSUE TITLE
Blood Angels SIW Gleaming Pinons

### ISSUE THREAD

**Issue by Andretton** [BSData/wh40k-9e#9154]
**File/Catalogue:** 
Blood Angels
**Platform:** Windows

- [ ] The Blood Angels Special Issue Wargear "Gleaming Pinions" is missing for selection.

- [x] Icon of the Angel is available under two categories and in one has the old rules and correctly listed in the other.

EDITED BY @alphalas

**Comment by Technoblazed** [comment]
Gleaming Pinions no longer exists and the other one is fixed in next release.

**Comment by robhob2187** [comment]
Gleaming pinions does exist in new codex ![image](https://user-images.githubusercontent.com/73329547/103671067-51130880-4f72-11eb-9a39-2e0b82d637c7.jpeg)

**Comment by alphalas** [comment]
Show us in the book; not the GW app.

**Comment by alphalas** [comment]
Ah I see the issue. It’s not a relic, it’s a SIW.
