### ISSUE TITLE
Lib - Space Marines: Scout Bikes should not be limited to 3 grenade launchers

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9163]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Noticed that scout bikes only allow a max of 3 grenade launcher s even though the space marine codex states any number may have them.

**Comment by Mad-Spy** [comment]
Additionally, as a QoL improvement, it might be good to limit the max number of Scout Bikers to 8 on the individual SEs. Currently I can add 40 bikers if I want. There is a validation message, but locking it to max 8 would be better.
