### ISSUE TITLE
Tempestus Scions w/ Special Weapons

### ISSUE THREAD

**Issue by DudeChris33** [BSData/wh40k-9e#9166]
**File/Catalogue:** Astra Militarum v296

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** Tempestus Scions with special weapons in both normal scion squads and scion command squads have an error message when they pick any weapon but a hotshot volley gun.

**Comment by Mad-Spy** [comment]
This is fixed in 9.1.9. Try deleting local data when updating.
