### ISSUE TITLE
Missing units from space wolves

### ISSUE THREAD

**Issue by saevelland** [BSData/wh40k-9e#9176]
**File/Catalogue:** 
 Space wolves
**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux
Android
**Dropbox:** Yes/No

**Description:** Detailed issue description.
Wolfgard battle leader on thunderwolf completely missing.

**Comment by Technoblazed** [comment]
Add a lieutenants unit.
