### ISSUE TITLE
Blood Angels Points Issues

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#9182]
**File/Catalogue:** Blood Angels v207

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Apologies if any of these have already been repeated.
- Currently all melee and ranged weapons (excluding thunder hammer and hand flamer) on Death Company Marines are missing their points cost 
- Death Company Intercessor w/ melee weapon's power sword and plasma pistol are missing their points cost
- Intercessors squad sergeant's power sword and plasma pistol are missing their points cost
- Assault intercessors squad sergeant's plasma pistol is missing its point cost
- Veteran power sword and plasma pistol are missing their points cost
- Bladeguard veteran sergeant's plasma pistol is missing its point cost

**Comment by Technoblazed** [comment]
Please avoid using the master branch while we work on point updates, all points have been removed from the space marine wargear. We recommend using the v9.1.10 release in the meanwhile.
