### ISSUE TITLE
Drukhari - MFM Points & Power Ratings QA Pass

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#9189]
**File/Catalogue:** Aeldari - Drukhari v90

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [x] Archon is currently 60 points, but should be 65 points
- [x] Archon’s phantasm grenade launcher is currently 5 points, but should be 0 points
- [x] Several units’ agoniser is currently 5 points, but should be 0 points:
1. Archon
1. Haemonculus
1. Succubus
1. Beastmaster
- [x] Several units’ venom blade is currently 5 points, but should be 0 points:
1. Archon
1. Haemonculus
- [x] Archon’s blaster is currently 15 points, but should be 0 points
  - ***LEGENDS, IGNORED***
- [x] Haemonculus is currently 75 points, but should be 80 points
- [x] Several units’ ichor injector is currently 5 points, but should be 0 points:
1. Haemonculus
1. Talos
- [x] Haemonculus’ electrocorrosive whip is currently 5 points, but should be 0 points
- [x] Several models’ flesh gauntlet is currently 5 points, but should be 0 points:
1. Haemonculus
1. Grotesques > Grotesque with Liquifier Gun
1. Grotesques > Grotesque with Monstrous Cleaver
- [x] Haemonculus’ mindphase gauntlet is currently 5 points, but should be 0 points
- [x] Haemonculus’ scissorhand is currently 10 points, but should be 0 points
- [x] Haemonculus’ stinger pistol is currently 5 points, but should be 0 points
- [x] Haemonculus’ hexrifle is currently 5 points, but should be 0 points
- [x] Haemonculus’ liquifier gun is currently 10 points, but should be 0 points
- [x] Succubus’ blast pistol is currently 5 points, but should be 0 points
- [x] Succubus’ impaler is currently 5 points, but should be 0 points
- [x] Succubus’ hydra gauntlets are currently 5 points, but should be 0 points
- [x] Succubus’ razorflails are currently 5 points, but should be 0 points
- [x] Succubus’ shardnet and impaler are currently 10 points, but should be 0 points
- [x] Kabalite Warriors > Kabalite Warrior with special weapon’s blaster is currently 15 points, but should be 10 points
- [x] Kabalite Warriors > Kabalite Warrior with special weapon’s shredder is currently 10 points, but should be 5 points
- [x] Several models’ power sword is currently 0 points, but should be 5 points:
1. Kabalite Warriors > Sybarite
1. Wyches > Hekatrix
1. Reavers > Arena Champion
- [x] Mandrakes currently cost 17 points each, but should be 15 points each
- [x] Razorwing Flocks with 10-12 models currently cost 6 PL, but should cost 8 PL
- [x] Reavers’ cluster caltrops currently cost 3 points, but should be 5 points
- [x] Reavers’ grav-talon currently cost 3 points, but should be 5 points
- [x] Scourges > Solarite’s power lance currently costs 0 points, but should be 5 points
- [x] Scourges > Scourge with Special / Heavy weapon’s blaster currently costs 15 points, but should be 10 points
- [x] Scourges > Scourge with Special / Heavy weapon’s shredder currently costs 10 points, but should be 5 points
- [x] Ravager’s dark lance (Starboard Weapon version) currently costs 20 points, but should be 0 points
- [x] Several models’ chain snares currently costs 2 points, but should be 5 points:
1. Ravager
1. Raider
1. Venom
- [x] Several models’ grisly trophies currently costs 2 points, but should be 5 points:
1. Ravager
1. Raider
1. Venom
- [x] Talos’ macro-scalpel currently costs 5 points, but should be 0 points
- [x] Talos’ chain-flails currently costs 5 points, but should be 0 points
- [x] Talos’ Talos gauntlet currently costs 15 points, but should be 5 points
- [x] Talos’ stinger pod currently costs 10 points, but should be 0 points
- [x] Talos’ haywire blasters currently cost 10 points, but should be 0 points
- [x] Talos’ heat lances currently cost 10 points, but should be 0 points
- [x] Talos’ splinter cannons currently cost 15 points, but should be 0 points
- [x] Venom’s splinter cannon currently costs 15 points, but should be 10 points
- [x] Razorwing Jetfighter’s splinter cannon currently costs 15 points, but should be 5 points
- [x] Razorwing Jetfighter’s dark lances currently cost 20 points, but should be 0 points
- [x] Voidraven Bomber is incorrectly named as “Voidraven” on both unit name and profile name
- [x] Voidraven Bomber’s Voidraven missiles currently cost 0 points, but should be 15 points
- [x] Voidraven Bomber’s dark scythes currently cost 0 points, but should be 5 points each

**Comment by FarseerVeraenthis** [comment]
Wow, that's a long list...
