### ISSUE TITLE
Eldar Corsair Bug and Point Costs

### ISSUE THREAD

**Issue by gabebrodbeck** [BSData/wh40k-9e#9190]
**File/Catalogue:** 
Craftworlds/Eldar Corsairs
**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Description:**
Hello! Thanks for moving Eldar corsairs to craftworld detachments! However their point values are currently incorrect and there are a couple bugs.
-----
Points:
-Forgeworld Legends reduced the cost of brace of pistols from 5 points to 0 points. It is still listed as 5 points.
-The point cost of a voidsabre is now 0 points. Battlescribe has it listed at the old 10 point value still.
-Corsair Cloud Dancer Dark Lances are now 20 points. Battlescribe lists them at 15.
-Corsair Cloud Dancer Splinter Cannons are now 15 points. Battlescribe lists them at 10.
Bugs:
-Reaver w/ Shuriken Catapult is listed as having a shuriken Cannon instead of a shuriken catapult.
-Skyreaver w/ Shuriken Catapult is listed as having a shuriken Cannon instead of a shuriken catapult.
------
Thanks again for getting to updating Corsairs! I really appreciate it!!!

**Comment by Dunamis55** [comment]
Consolidated into #9194
