### ISSUE TITLE
CSM - Havocs failing to add non-Heavy Marines as per Codex

### ISSUE THREAD

**Issue by Cubahaxxor** [BSData/wh40k-9e#9192]
**File/Catalogue:** Warhammer 40k v9.1.10

**BattleScribe version:** 2.03.21.166 (Windows)

**Platform:** Windows & Android 

**Dropbox:** Yes

**Description:** The file does not allow the adding of Chaos Space Marines to a Havoc Squad beyond the default 5, which is allowed based on the codex.  Recreated the issue on Windows and Android.  Believe to be a data file issue (bug) not within the app itself
![Capture](https://user-images.githubusercontent.com/77149290/104003288-35755100-5170-11eb-8aab-974c3cd688e8.PNG)

**Comment by Mad-Spy** [comment]
You must be looking at the old Codex. Havocs were limited to max 5 in the 2019 CSM Codex.

![image](https://user-images.githubusercontent.com/29306451/104003460-59e62300-519a-11eb-9632-110aaf467ce9.png)

**Comment by Cubahaxxor** [comment]
Was this errata? Because I checked gw just to be sure and my 8th Ed codex was the latest release

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Mad-Spy** [comment]
No, this is the datasheet in the latest version of the Codex. As per the **Important Note** on the GW page, the Codex was re-released to include the updates from Vigilus Ablaze, which included this new datasheet.
