### ISSUE TITLE
Imperium - Dark Angels: Whirlwind 5PL should be 7PL 

### ISSUE THREAD

**Issue by Rademonek** [BSData/wh40k-9e#9196]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

BS 2.03.21
WH40K 9ed v174
Dark Angels v187

Whirlwind should be 7PL instead of 5PL

**Comment by Technoblazed** [comment]
The new points aren't in the release yet, they are on master and will be included in the next release.
