### ISSUE TITLE
Space Marine Techmarine

### ISSUE THREAD

**Issue by nocturnal40k** [BSData/wh40k-9e#9203]
**File/Catalogue: Space Marines

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Selecting combi-flamer for the space marine techmarine causes the data for both a Boltgun and a Flamer to populate, rather than the profile for a combi-flamer (with the -1 to hit when firing both profiles).

**Comment by acebaur** [comment]
This is how it is displayed in all instances of this. Working as intended
