### ISSUE TITLE
Spacewolves - Librarian Powers

### ISSUE THREAD

**Issue by Garvlok** [BSData/wh40k-9e#9204]
**File/Catalogue:** Space Wolves v175

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** 

pick 2 spells from a psychic discpline and its good

Pick chief librarian and pick a third spell, you get an error

Pick tome of malcador to take another spell and you get an error as well

Also if i pick 2 from the tempestus discipline and then pick a third with tome of malcador, i should be able to get a spell from the librarius discipline.

**Comment by alphalas** [comment]
On that last point nope, not how that works. You get an extra power from a discipline you have access to. Once you pick a power from a disciple, you only have access to that discipline.

**Comment by Garvlok** [comment]
> On that last point nope, not how that works. You get an extra power from a discipline you have access to. Once you pick a power from a disciple, you only have access to that discipline.

I didnt realize the community is split on this topic. Guess we'll have to wait for the FAQ. Thanks!

After digging around i found this

"however, from the FAQ:
Q: Space marines tome of Malcador relic, can you take a power from a different discipline than your original power(s), as long as you have access to it? For example, could an Iron Hands librarian take null zone and might of heroes from the base discipline and then use the tome of Malcador to take Pysteel armor from iron hands discipline?
A: Yes."

But i cant find the faq it was pulled from.

I did email gwfaq. Ill update if they respond!

**Comment by Mad-Spy** [comment]
That's from an 8th edition FAQ, so it's no longer a valid answer. Unfortunately.

**Comment by Mad-Spy** [comment]
Looks like this was only totally broken for Primaris Libbys, other Libbys would give 1 extra power but not both. Now fixed.
