### ISSUE TITLE
Blood Angels: One of Astorath’s Litanies, Exhortation of Rage, has the incorrect definition.

### ISSUE THREAD

**Issue by SanguineNate** [BSData/wh40k-9e#9206]
One of Astorath’s Litanies has the incorrect definition. (Codex Space Marines p. 112)

Exhortation of Rage should read: “If this litany is inspiring, select on friendly Blood Angels character or Blood Angels Character unit within 6” of this priest. Each time a model in that unit makes a melee attack, add 1 to that attack’s wound roll.” (Codex Space Marines p. 112)

This may be incorrect across multiple chaplains / space marine factions, I do not know, I just know it is wrong for Astorath.

**Comment by Technoblazed** [comment]
Fixed in next release.

**Comment by SanguineNate** [comment]
I'm sure you guys caught it, but I jacked up my post and wrote "character" twice instead of "core" and "character".

**Comment by Technoblazed** [comment]
I did yes :)
