### ISSUE TITLE
Elyisan Drop Troops - Legends 

### ISSUE THREAD

**Issue by lewis0460** [BSData/wh40k-9e#9207]
**File/Catalogue:** Imperium Elysian 

**BattleScribe version:** 2.03.

**Platform:** Mac

**Dropbox:** No

**Description:** Couple of things:

-Elysian Drop Sentinel's aerial drop ability has a typo 'instaed'. In addition this ability seems to get removed when the 'Elysian Drop Troops' regimental doctrine is selected?

-Speaking of doctrine, since we weren't given any specific doctrine wording in legends *sigh*, am I right in thinking that we then use it as a custom doctrine? If so, there is currently no way to select these traits at present? 

Many thanks for your continued efforts :)

**Comment by Technoblazed** [comment]
I'll fix the doctrine stuff later :)

**Comment by Technoblazed** [comment]
Fixed in next release.
