### ISSUE TITLE
Blood Angels: "Angel Exemplar" Pre-Game Stratagem; multiple issues.

### ISSUE THREAD

**Issue by SanguineNate** [BSData/wh40k-9e#9208]
•	The Battlescribe rosters generated as-is, with a character having an Angel Exemplar WL Trait along with the original 1 baked-in WL Trait will populate an error message stating the character has (1) too many Warlord Traits. This is incorrect. Angel Exemplar's entire purpose is allowing for two WL traits on one body, so this error should not occur unless the character has at least 3. (Blood Angels Supplement p. 48)
o	Additionally, adding this stratagem to my list should knock my CP down by (1) and it currently does not decrease my CP at all.

**Comment by Technoblazed** [comment]
Fixed in next release
