### ISSUE TITLE
Adepta Sororitas- Open The Reliquaries counting issue

### ISSUE THREAD

**Issue by SanguineNate** [BSData/wh40k-9e#9212]
The pre-game stratagem "Open The Reliquaries" allows for an additional generic character to take a relic on your list for 1CP a piece, but in my testing of my lists it is not discounting the initial free relic you get on your list when determining if you have taken enough instances of this stratagem for the amount of relics on your list. 

For example, taking three relics on a Battleforged list should cost 2CP and via 2 instances of Open the Reliquaries, but doing this still results in the error that your list has 1 too many relics. Similarly, taking two relics and one instance of Open the Reliquaries still results in the error that your list has 1 too many relics.

**Comment by Technoblazed** [comment]
Did you add a warlord?

**Comment by SanguineNate** [comment]
Yes, in this current iteration I have a Canoness nominated as Warlord with one relic (Iron Surplice of St. Istaela), and an Imagifier with a second relic (Book of St. Lucius), while using one iteration of Open the Reliquaries, and it still says that I have one too many relics. The app also isn't giving me the error that I need a warlord to finish my army, so I don't think it's miscommunication of the app not understanding that the Canoness is my Warlord.

**Comment by Mad-Spy** [comment]
It's a problem with the way the Book of St. Lucius has been implemented, not any of the other logic. The way it's done would have worked in previous versions of the app, but is no longer workable. It needs rewriting.
