### ISSUE TITLE
Imperium - Adeptus Astartes - Iron Hands: Teeth of Mars is not showing up

### ISSUE THREAD

**Issue by Citronnade** [BSData/wh40k-9e#9219]
**File/Catalogue:** Imperium - Adeptus Astartes - Iron Hands v32 (v176/v9.1.10 overall)

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** Teeth of Mars is not showing up to replace an Astartes Chainsword.

Reproduction instructions: Create a new roster, set **Chapter Selection** to Iron Hands, add a Captain, give them an Astartes Chainsword.  Teeth of Mars does not show up, but other ~~Relics of Medusa~~ Iron Hands Special Issue Wargear does.

I searched for related bugs with iron hands chainswords and could not find any.  If this behavior is working as intended because the Iron Hands supplement still mentions Chainsword and not Astartes Chainsword, then at least this bug can serve as a reference.

**Comment by Mad-Spy** [comment]
The validation is still triggering off the old chainsword, instead of the new one.
