### ISSUE TITLE
Imperium - Adeptus Custodes - Vertus Praetors Cost

### ISSUE THREAD

**Issue by Keviebear** [BSData/wh40k-9e#9220]
**File/Catalogue:** Imperium - Adeptus Custodes v69

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** In the MUNITORUM FIELD MANUAL 2021 MK I the Vertus Praetors are listed as 85 points, they are still listed in Battle Scribe as 95 points.

**Comment by Mad-Spy** [comment]
Point updates have not been released yet.
