### ISSUE TITLE
Drukhari: MFM Issues on master branch

### ISSUE THREAD

**Issue by dalamar666** [BSData/wh40k-9e#9221]
**File/Catalogue:** v92

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:**No

**Description:**

1.  Wrack Unit size now 5-20
2.  Venom cost now base 65 and Splinter cannons +10 pts not 15pts.
3. Grotesques with Liquifier gun 45 pts not 50.  The gun is only 5pts for them.

**Comment by Technoblazed** [comment]
Point 1 is incorrect; the MFM cannot change unit sizes, it's probably a change from the new book and will need to wait until the actual datasheet is updated.
