### ISSUE TITLE
Imperium - Death Korps of Krieg: Should be able to include Militarum Tempestus units

### ISSUE THREAD

**Issue by SebastianThielman** [BSData/wh40k-9e#9222]
**File/Catalogue:** Death Korps of Krieg

**BattleScribe version:** 2.03.15

**Platform:** iOS

**Dropbox:** No

**Description:** Death Korps of Krieg detachments ought to be able to include Militarum Tempestus units as of the Imperial Armour Compendium but are currently unable to do so.

**Comment by Technoblazed** [comment]
Fixed in next release
