### ISSUE TITLE
Tau Supreme Command Detachment missing Commander Shadowsun

### ISSUE THREAD

**Issue by Rob9898989898** [BSData/wh40k-9e#9231]
**File/Catalogue:** T'au Empire.cat

**BattleScribe version:** 2.03.

**Platform:**Android

**Dropbox:** No

**Description:** Currently under a Supreme Command Detachment it only has Configuration and Stratagems. There should be HQ listed with the option for Commander Shadowsun because she has the "Supreme Commander" keyword.

**Comment by Technoblazed** [comment]
This isn't released yet, it's in the next release.
