### ISSUE TITLE
Imperium - Astra Militarum: Chimera turret weapon costs incorrect in v298

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9233]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The Chimera Entry for Turret Weapon should list Heavy Bolter and Heavy Flamer as 15pts when it should be 10pts

**Comment by Mad-Spy** [comment]
Points updates from MFM2021 have not yet been released.

**Comment by Kyton113** [comment]
I manually downloaded it.....

**Comment by Mad-Spy** [comment]
Ok, but there's nothing in your report which says that, so you can understand why I didn't know.

If you're testing on unreleased data, it's always helpful to actually say that.
