### ISSUE TITLE
Knight Moiraxes can now take 2 Conversion Beam Cannons

### ISSUE THREAD

**Issue by Celepito** [BSData/wh40k-9e#9234]
**File:**  Imperium - Imperial Knights.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** According to the Imperial Armour Compendium, the Knight Moiraxes should be able to carry two Moirax Converersion Beam Cannons into battle. In the current version, it can only be outfit with one.

**Comment by Mad-Spy** [comment]
I'd better fix that in Chaos as well.
