### ISSUE TITLE
Tyranid Points Update

### ISSUE THREAD

**Issue by TaulValentine** [BSData/wh40k-9e#9236]
**File/Catalogue:**  Tyranids

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The January 7 2021 update didn't update points on Tyranids. Judging by the other open reports neither have the other armies.

Hive Tyrant Wings upgrade should be 30pts not 45pts

Tyranid Warriors should be 17pts not 21pts

Hive Guard should be 35pts not 40pts

Zoanthropes should be 50pts not 40pts

**Comment by Mad-Spy** [comment]
Correct, it did not. Points changes will be in _this_ week's release.

Apologies that the 6 hours between the points  update and our release wasn't enough time to get them done. /s
