### ISSUE TITLE
Tyranid point cost issue

### ISSUE THREAD

**Issue by Termaran** [BSData/wh40k-9e#9241]
**File/Catalogue:**  

**BattleScribe version:** 2.03.25.338

**Platform:** Windows/iOS/Android/Mac/Linux

**Description:** 
With the Current FAQ changes there seems to be an Issue with the updated cost of the Tyranid Trygon and Carnifex. They should not gone up in points due to no changes in the FAQ. In the current version of the app the Trygon has a base cost of 180 and should be 150, and it seems that the Carnifex also got up 5 points from 95 base to 100 base.

**Comment by Mad-Spy** [comment]
Trygon is incorrect; its massive scything talons should be free.

Carnifex monstrous scything talons went up 5 points in the new MFM. Cost is correct.
