### ISSUE TITLE
[Astra Militarum] Lord Commissar power sword missing cost

### ISSUE THREAD

**Issue by Orta15a** [BSData/wh40k-9e#9242]
**File/Catalogue: 
9.1.11 version updated on 14 January 22:32.
Astra militarum v298

**BattleScribe version:** 2.03.

**Platform:** Windows/Android

**Description:** Detailed issue description.

The Lord Commisar default equipment is a bolt pistol and power sword. The Lord Commisar is correctly priced at 35, bolt pistol 0. But the power sword is priced at 0 also whereas in the latest MFM, the power sword is listed as 5pts.

**Comment by Valorcalls** [comment]
Update your data.

**Comment by Orta15a** [comment]
I did previously, I am running the 9.1.11 version updated on 14 January 22:32.
Astra militarum v298

**Comment by Valorcalls** [comment]
Click the checkbox to delete previous data then, since the live data doesn't have this issue

**Comment by Orta15a** [comment]
Did that again, still listing the Commisar power sword at 0pts instead of 5.
I'm not sure what is going on, as usually don't have any issue with data updates.

**Comment by Valorcalls** [comment]
Hm, well I'll let them figure it out then
