### ISSUE TITLE
Adepta Sororitas cost error

### ISSUE THREAD

**Issue by DrCox83** [BSData/wh40k-9e#9247]
**File/Catalogue:** Warhammer 40,000 V9.1.1.11

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** Yes/No

**Description:** Detailed issue description.

error cost for :
-sisters repentia (15 -> 16pts/model)
-Zephyrim Squad (20 -> 18pts/model)

**Comment by Technoblazed** [comment]
Not quite sure what v9.1.1.11 is, but you're definitely not on v9.1.11. Update your data.

**Comment by Mad-Spy** [comment]
It's also not clear if you think the costs are too high or too low. Too much detail when reporting errors is better than too little.

**Comment by DrCox83** [comment]
Sorry, V9.1.11 (see picture)
![data](https://user-images.githubusercontent.com/77501204/104750371-4b78a800-5754-11eb-9c56-bfaf19d7d870.png)
, data are update (that is what data manager say).

about cost, I gave the current cost -> actual cost

ex : in my version, cost of repentia are 15pts, but the right cost 16pts.

**Comment by Technoblazed** [comment]
Update your data and delete existing data then.

![Image](https://i.tech-no.me/2021/01/15/210115161217.png)

**Comment by DrCox83** [comment]
problem solved by deleting and re-downloading datas, thanks ! ;-)

Do you recommand to always choose to delete old datas before updating ?

**Comment by Technoblazed** [comment]
Usually doesn't hurt

**Comment by DrCox83** [comment]
ok, so I'm just unlucky ! ^_^'
