### ISSUE TITLE
Wrong point costs for Eradicators in Deathwatch-Killteam

### ISSUE THREAD

**Issue by Hellgore1974** [BSData/wh40k-9e#9252]
**File/Catalogue:** warhammer40k v178 Deathwatch v117

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

The Eradicator Primaris Marines are still at 40pts/piece. Should be at 45 pts after FAQ update.

**Comment by Technoblazed** [comment]
Already fixed in next release
