### ISSUE TITLE
Vespid Tau point cost

### ISSUE THREAD

**Issue by Termaran** [BSData/wh40k-9e#9257]
**File/Catalogue:** 

**BattleScribe version:** 2.03.21

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** I updated the battlescribe app due to the point change of tau units. One of the changes should be Vespid going to 11 points from 14. The app still has the 14 point costs of the vespid.

**Comment by Technoblazed** [comment]
Not exactly sure where you're seeing 11 point vespids?

![Image](https://i.tech-no.me/2021/01/17/210117121656.png)

**Comment by Termaran** [comment]
wow I'm very sorry. Read and old article and was so happy.
