### ISSUE TITLE
Adepta Sororitas points changes

### ISSUE THREAD

**Issue by steck638** [BSData/wh40k-9e#9258]
**File/Catalogue:** Imperium - Adepta Sororitas.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** In the new MFM update the Null Rod upgrade for the Canoness is free, as is the Simulacrum upgrade for Battle sisters, Celestians, Dominions, and Retributors as both items do not have a points listed in the update.

**Comment by Technoblazed** [comment]
Update your data and click the delete existing data box.
