### ISSUE TITLE
Aeldari - Ynnari relic validation incorrect for additional detachments when an Ynnari Warlord is included

### ISSUE THREAD

**Issue by KalChoedan** [BSData/wh40k-9e#9264]
**File/Catalogue:** Aeldari - Ynnari v??

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Having an Ynnari detachment of any Aeldari subfaction with an Ynnari Warlord currently allows all additional detachments to be granted a "free" relic from their faction's list. Thus a 3 detachment army is shown as valid with 3 free relics, one per detachment.

What should happen is that only detachments matching the Warlord's faction i.e. Ynnari should be granted access to a free relic, and only 1 free relic total between those detachments. If any Ynnari detachments want more than that initial relic between them, or if there are any other non-Ynnari (e.g. pure Craftworlds) detachments, they should be required to use their factions 1/3CP stratagem to bring any additional relics.

**Comment by Technoblazed** [comment]
Out of curiosity, where is this rule written?

**Comment by KalChoedan** [comment]
@Technoblazed In the scenario I described, only the Warlord's detachment should be granted a free relic. Every other detachment should have to use their own "1/3CP for 1/2 relics" stratagem. The error is that they are all being granted a relic for free, instead of just the Warlord's detachment.

I've updated the issue to make it a bit less ambiguous!

**Comment by WindstormSCR** [comment]
I think I know why this is happening, but it might be a bit more complicated than usual to fix because of the nature of how ynnari are implemented (oh how we hates them, precious!)

**Comment by FarseerVeraenthis** [comment]
> I think I know why this is happening, but it might be a bit more complicated than usual to fix because of the nature of how ynnari are implemented (oh how we hates them, precious!)

Yeah, sorry about that... Does anyone actually play Ynnari...?

**Comment by KalChoedan** [comment]
Hah! I wouldn't have thought so either, but apparently they do - I only caught it because I was looking through a list someone had posted on reddit and noticed the errors in there.

**Comment by WindstormSCR** [comment]
Special bonus: visibility will remain, but at least it will now throw an error for having too many if you have a ynnari warlord.
