### ISSUE TITLE
Asmodai - Dark Angels Chaplain 

### ISSUE THREAD

**Issue by Myndsync** [BSData/wh40k-9e#9269]
**File/Catalogue:** Imperium - Adeptus Astartes - Dark Angelsv190

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Asmodai, as listed in the Index Astartes - Dark Angels, has the Priest rule, "This model knows the Litany of Hate and **two** other litanies from the Litanies of Battle (see Codex: Space Marines).
In your Command phase, if this model is on the battlefield, it can recite one litany it knows that has not already been
recited by a friendly model that battle round. Roll one D6: on a 3+, the recited litany is inspiring and takes effect until the
start of your next Command phase.

In Battlescribe, when giving him 2 other litanies, it gives an error, saying he knows only 1 other litany, which is incorrect as it is listed in the Index.

**Comment by Mad-Spy** [comment]
This is a lib problem. The lib doesn't know Asmodai should have 2 Litanies.
