### ISSUE TITLE
Bug Report: Thousand Sons v87: Predator cost not updated

### ISSUE THREAD

**Issue by LuckyLee84** [BSData/wh40k-9e#9276]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
The points cost for the Chaos Predator are currently at 90 in the app. I checked the FAQ and they should be 130 for the base cost.

**Comment by KalChoedan** [comment]
Chaos Predator is 130pts in the current data.

![image](https://user-images.githubusercontent.com/1786901/105327178-7df82a00-5bc6-11eb-855e-0445272a527b.png)
