### ISSUE TITLE
Orks latest data update

### ISSUE THREAD

**Issue by 1Trickpony65** [BSData/wh40k-9e#9283]
Latest data is missing ORK Chinork (legends)

**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Mad-Spy** [comment]
This "Chinork Warcopta"?

![image](https://user-images.githubusercontent.com/29306451/105478607-4e672180-5c9b-11eb-842f-66b2c8a2ada1.png)
