### ISSUE TITLE
Deathwatch Indomitor/Fortis Kill Team

### ISSUE THREAD

**Issue by sindinista** [BSData/wh40k-9e#9285]
**File/Catalogue:** Warhammer 40,000 v9.1.11 

**BattleScribe version:** 2.03.15

**Platform:** iOS

**Dropbox:** No

**Description:** Post the 1/14 release, Inceptor and Eradicator options in the **Indomitor Kill Team** need to be increased 5 pts.  Outriders in the **Fortis Kill Team** also need to be increased 5 pts.  Each unit is costed correctly when added in the stand-alone Fast/Heavy slot, but not when added via the specific Deathwatch Kill Team Troop choice.

**Comment by Technoblazed** [comment]
Already fixed in next release.
