### ISSUE TITLE
Ultramarines honour guard unit not present, they are not Legends. 

### ISSUE THREAD

**Issue by Jonjacob34** [BSData/wh40k-9e#9294]
ultramarines Catalogue 

**BattleScribe version:** 
v2.03.25.338

**Platform:** Android

**Dropbox:** No

**Description:**

Ultramarines Honour Guard unit is not Legends unit. 
Lastest Points update from Munitorum Field Manual pg 7 show this. Furthermore ultramarines honour guard are keyworded differently to the index version.

**Comment by Technoblazed** [comment]
Did you actually try adding the unit to your roster? It removes the legends tag when you add them.

**Comment by Mad-Spy** [comment]
As per Techno's comment, the Honour Guard are only not Legends for UM, so they don't switch until you add them to your list.
