### ISSUE TITLE
Imperium - Astra Militarum: Tempestor in Scions unit plasma pistol should be 5pts

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9295]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** I have tried deleting my app, clearing the cache/data then deleting the app, clearing the data files and downloading them and I STILL am showing Scion Tempestors as having Plasma Pistols costing "no cost". I am on Warhammer 40,000 v9.1.12

**Comment by Mad-Spy** [comment]
Incorrectly closed previously.
