### ISSUE TITLE
Chaos - Death Guard: Orb of Dessication should be Grenade 3D3

### ISSUE THREAD

**Issue by Gallahorn** [BSData/wh40k-9e#9298]
**File/Catalogue:** Death Guard

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Detailed issue description.

Lord of Contagion with Manreaper and Orb of Dessication
Orb of dessication is 3d3 not 2d3 in the codex.

https://gyazo.com/835a2e712c561b9651c64d7bab284f13

**Comment by SenshiKenpachi** [comment]
and it is also a Plague Weapon!
and there is a typo "dessication" is spelled "de**s**i**cc**ation"
