### ISSUE TITLE
Death Guard: Can't pick a WL trait for Mortarion

### ISSUE THREAD

**Issue by Everborne** [BSData/wh40k-9e#9301]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Can't pick any WL traits for Mortarion.

**Comment by Valorcalls** [comment]
He has fixed wlts when you make him your warlord, and the other wlt he can get isnt part of listbuilding, so what is the confusion?

**Comment by Everborne** [comment]
Apologies, didn't realize the one WLT you can choose isn't part of listbuilding. Thanks for clarifying, will close the issue.
