### ISSUE TITLE
Missing Point cost of Sword Brother (Crusader squad of Black Templars)

### ISSUE THREAD

**Issue by Boodman87** [BSData/wh40k-9e#9302]
**File/Catalogue:**  Imperium - Adeptus Astartes - Black Templars v33

**BattleScribe version:** Warhammer 40,000 v9.1.12

**Platform:** Android
Description:

Preconditions:

1. Create a roster: Imperium - Adeptus Astartes - Black Templars v33

Steps to reproduce:

1. In Troops section, select "Crusader Squad".
2. Open newly added "Crusader Squad" unit in Troops section to modify the unit.
3. Pay attention to the point cost of the Sword Brother in the squad.

Actual Results:
Point Cost of the Sword Brother shows: "No cost".

Expected Results: 
Point Cost of the Sword Brother shows: "15 pts".

**Comment by acebaur** [comment]
will be out in the next release

**Comment by Boodman87** [comment]
Thanks, Alex!

You are doing a great Job - BattleScribe rules!:-)
Best Regards,
Constantine Budkevych
constantine.budkevych@gmail.com

"When everything seems to be going against you,
remember that the airplane takes off against the wind,
not with it"

-- Henry Ford


вс, 24 янв. 2021 г. в 15:08, Alex Baur <notifications@github.com>:
