### ISSUE TITLE
Hive Tyrant tyranid

### ISSUE THREAD

**Issue by morlinge** [BSData/wh40k-9e#9303]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** "A Hive Tyrant may replace both pairs of monstrous scything talons with two items from the Monstrous Bio-cannons or two items from the Monstrous Bio-weapons list, **or with one item from each list.**" The current settings only allow you to choose two bio-cannons and pay for them both.
![error](https://user-images.githubusercontent.com/74674615/105639941-038b0c80-5e49-11eb-89b0-67bafed73b8e.jpg)

**Comment by GenWilhelm** [comment]
Two deathspitters and two devourers are each a single **item** from the Monstrous Bio-cannons list:

![image](https://user-images.githubusercontent.com/22036809/105639995-537ec900-5e73-11eb-94ca-ab465549da30.png)
