### ISSUE TITLE
Death Guard - Codex QA Pass

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#9307]
**File/Catalogue:** Chaos - Death Guard v115

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [x] Death Guard Daemon Prince’s Wings wargear option should be named “Foetid wings”
- [x] Typhus is missing his Vector of Disease ability
- [x] WON'T FIX _It_ **is** _an ability and is displayed as such_ Teleport Strike is currently listed as an ability, but should be listed as a rule
- [x] WON'T FIX _It_ **is** _an ability and is displayed as such_ Disgustingly Resilient is currently listed as an ability, but should be listed as a rule
- [x] WON'T FIX _It_ **is** _an ability and is displayed as such_ Remorseless is currently listed as an ability, but should be listed as a rule
- [x] Lord of Contagion’s orb of desiccation is incorrectly named as “Orb of dessication”
- [x] Lord of Contagion’s orb of desiccation currently has a Type characteristic of Grenade 2D3, but should be Grenade 3D3
- [x] Lord of Contagion’s orb of desiccation’s abilities section has some missing text and should read as: “Blast. Plague Weapon. The bearer can only shoot with this weapon once per battle.”
- [x] Malignant Plaguecaster currently has an Attacks characteristic of 3, but should be 4
- [x] Plague Marines’ plague belcher currently has a Range characteristic of 9”, but should be 12”
- [x] Death Guard Cultists’ shotgun currently has incorrect ability text and should read as: “-“
- [x] Death Guard Cultists’ shotgun currently has a Range characteristic of 12”, but should be 18”
- [x] More than 29 models can be take for:
1. Death Guard Cultists > Death Guard Cultist w/ Autogun
1. Death Guard Cultists > Death Guard Cultist w/ autopistol and brutal assault weapon
- [x] Foul Blightspawn’s Putrefying Stink ability has a typo: “Tht unit is not” should read as “That unit is not”
- [x] Helbrute is missing its Frenzy ability
- [x] Helbrute’s Explodes ability currently has a range of 6”, but should be 3”
- [x] Chaos Spawn’s 3 - Toxic Haemorrhage ability has a typo: “each time a modle” should read as “each time a model”
- [x] Chaos Rhino currently has the Self-repair ability, but shouldn’t have
- [x] Chaos Rhino currently has the Smoke Launchers ability, but shouldn’t have
- [x] Several units’ Putrid Explosion ability currently deals 1 mortal wound, but should be D3 mortal wounds:
1. Mortarion
1. Miasmic Malignifier
- [x] Miasmic Malignifier’s Putrescent Fog (Aura) ability has a typo: “thne each time” should read as “then each time”
- [x] Death Guard Cultists > Death Guard Cultist w/ special weapon’s flamer currently costs 0 points, but should cost 5 points
- [x] Death Guard Cultists > Death Guard Cultist w/ special weapon’s heavy stubber currently costs 0 points, but should cost 5 points
- [x] Mortarion’s Arch-Contaminator (Aura) Warlord trait has incorrect text: “While a friendly <PLAGUE COMPANY> CORE” should read as “While a friendly DEATH GUARD CORE”
- [x] Ferric Blight (Contagion) ability has missing text and should read as: “While an enemy unit is within Contagion Range of this unit, each time an attack is made by a friendly INEXORABLE model against that enemy unit, improve the Armour Penetration characteristic of that attack by 1.“
- [x] WON'T FIX - _It automatically replaces the ability for the model_ The Daemon’s Favour relic has no ability text when mousing over the selection.

**Comment by masterchiief** [comment]
First of all, thank you for your hard work, it is very much appreciated, I just want to help.
Two issues I've encountered while making lists:
- [x] Bubotic Axe's profile should be +2S AP-2 D1 plague weapon when it's currently +1S Ap-2 D1 plague weapon.
- [x] WON'T FIX Deadly Pathogens grant the extra ability to the weapon (like Virulent Fever) but they are missing the default +1S to the weapon.
Thank you

**Comment by Mad-Spy** [comment]
Making every possible plague weapon gain 1 Strength when adding Pathogens is not viable.

**Comment by masterchiief** [comment]
I understand Mad-Spy, maybe as an extra reminder in the text-box within the abilities section, next to the description (say Viscous Death: "... In addition, add 1 to the S characteristic of the weapon"). Did not mean to imply adding it to every single profile it is attached to, sorry for the confusion.

**Comment by Mad-Spy** [comment]
@masterchiief The rule was there, but it wasn't displaying correctly. It'll show in the Rules section at the bottom of the list output. Fixed now ready for the next release.

**Comment by masterchiief** [comment]
Thank you very much, you guys are the best
