### ISSUE TITLE
Chaos - Death Guard: Helbrute missing Frenzy ability

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9310]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.03.21

**Platform:** Android

**Dropbox:** No

**Description:** Helbrute missing the Frenzy ability: "each time this model makes an attack, if it has 7 or fewer wounds remaining, re-roll a wound roll of 1"

**Comment by Mad-Spy** [comment]
Fixed in next release, see #9307
