### ISSUE TITLE
[Astra Militarum] Straken warlord trait

### ISSUE THREAD

**Issue by Orta15a** [BSData/wh40k-9e#9311]
**File/Catalogue:** 
wh40k 9.1.12
astra militarum v298

**BattleScribe version:** 2.03.21

**Platform:** Windows/Android

**Description:**
When selecting Catachan as regiment and Straken, when making him the Warlord, its mandatory warlord trait (lead from the front) cannot be added resulting in a validation error.

**Comment by Mad-Spy** [comment]
This should be an OR

![image](https://user-images.githubusercontent.com/29306451/105698731-2fb49500-5efe-11eb-832a-90b566346f5c.png)
