### ISSUE TITLE
Space Wolves : missing obscuration discipline for librarian

### ISSUE THREAD

**Issue by TwiggyWan** [BSData/wh40k-9e#9315]
**File/Catalogue:** Imperium Space Wolves

**BattleScribe version:** BattleScribe v2.03.21.166
**Platform:** Windows

**Dropbox:** : No

**Description:** 

Hello,

Got an issue with standard librarian : Codex says "SW psykers can take psy powers from tempestas discipline instead of librarius or obscuration". This means that a librarian can choose between 3 disciplines but there are only two discipline boxes on the UI (librarius and tempestas). I am basing this claim on the latest space wolves codex & the only FAQ for it : https://www.warhammer-community.com/wp-content/uploads/2020/12/s69zaNVopCLyoo3F.pdf

Thanks.

**Comment by Valorcalls** [comment]
The only Librarian with access to the Obscuration discipline is the Librarian in Phobos Armor.

**Comment by TwiggyWan** [comment]
My bad, thanks.
