### ISSUE TITLE
Deathwatch: Proteus kill team - Vanguard veterans Storm shield cost

### ISSUE THREAD

**Issue by marthings** [BSData/wh40k-9e#9317]
Sorry if I have posted this issue wrong. 

**File/Catalogue:** 
Deathwatch

**BattleScribe version:** 2.03.
v9.1.11

**Platform:** Windows/iOS/Android/Mac/Linux
iOs

**Dropbox:** Yes/No
No

**Description:** Detailed issue description.

Storm shield option for Vanguard Veterans in Proteus kill teams cost 0pt. Should cost 4pts like normal Vanguard veterans squad cost.

**Comment by Technoblazed** [comment]
This is already fixed and released, update your data.

**Comment by marthings** [comment]
Thank you! Had some problems upgrading :) Works now. @Technoblazed Do you know if A vigil unmatched and Castellan of the black vault is working as it should? 

I get stuck in a situation where the validation says I need one more relic and another validation saying I have more relics than i can have.

Sorry for hijacking this issue. Thinking there might be a fix out there already for this as well?

**Comment by Technoblazed** [comment]
You need to click the warlord trait/castellan options below the unit entry, not select an additional relic from the unit.
