### ISSUE TITLE
Aeldari - Craftworlds: Novalance points issue

### ISSUE THREAD

**Issue by Citronnade** [BSData/wh40k-9e#9319]
**File/Catalogue:** Aeldari - Craftworlds v126 (repo version v9.1.12)

**BattleScribe version:** 2.03.25.338

**Platform:** Android

**Dropbox:** Yes

**Description:** Taking the Novalance on an Autarch Skyrunner charges twice: 5 points for the Laser lance, and 5 points for the Novalance (the original weapon's cost isn't deleted anymore).  Taking the Novalance should only charge for the base Laser lance, and not an additional price for the relic.

**Comment by FarseerVeraenthis** [comment]
Select "None" instead of the original laser Lance and you're golden :+1:
