### ISSUE TITLE
Space wolf

### ISSUE THREAD

**Issue by Danibluewolfs** [BSData/wh40k-9e#9321]
**File/Catalogue:** 
Space wolf
**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
Missing Lieutenants, and Wolf Guard Battle Bosses in the Space Wolves Repository

**Comment by Valorcalls** [comment]
Select the entry titled "Lieutenants" and add whichever of these things you want as per the rules from codex SM and codex supplement SW.

**Comment by Danibluewolfs** [comment]
Thank you very much
