### ISSUE TITLE
DG - Plague belcher incorrect range

### ISSUE THREAD

**Issue by SenshiKenpachi** [BSData/wh40k-9e#9339]
**File/Catalogue:** Chaos - Death Guard v114

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Plague belcher, Plague Marines, has a range of 12" not 9"

**Comment by Mad-Spy** [comment]
Fixed in the release that just went out. Give it 24 hours, then update your data.
