### ISSUE TITLE
Imperium - Astra Militarum: Special weapons troopers must incorrectly take a sniper rifle

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9363]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Unbound imperial guard.
All troopers with special weapons have to have a sniper rifle or battlescribe tells me it's an error.

**Comment by Mad-Spy** [comment]
Duplicate of #9342
