### ISSUE TITLE
Imperium - Astra Militarum: Special weapons sniper rifle bug

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9366]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Astra Militarum infantry squad - insists that special guardsman with special weapon must take a sniper rifle, shows roster error on any other choice

**Comment by Mad-Spy** [comment]
Duplicate of #9342

**Comment by Deecee29** [comment]
This is also a bug on iOS
