### ISSUE TITLE
ORKS - Nobz on warbikes wrong reference and PL cost

### ISSUE THREAD

**Issue by barBUGga** [BSData/wh40k-9e#9371]
**File/Catalogue:** Orks

**BattleScribe version:** 2.03.

**Platform:** Windows/Androi

**Dropbox:** Yes

**Description:** Detailed issue description.
Nobz on warbikes should cost 6PL as per last FAQ (07-01-2021) and also reference to the "Imperial Armour: Compendium p195" while the're also on the codex page99

**Comment by Technoblazed** [comment]
The IA book is the latest publication of the unit by the same name, so that is the unit data sheet we provide in BattleScribe.
