### ISSUE TITLE
Blood Angels - Death Company Wargear

### ISSUE THREAD

**Issue by DanteValoris** [BSData/wh40k-9e#9375]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** The Death Company Marines in the current release do not have the proper wargear selections from the newest codex.  It currently lists Boltgun, Bolt Pistol and Chainsword, and Thunder Hammer.  Power weapons and the other pistol options are missing.

**Comment by acebaur** [comment]
unselect default wargear
