### ISSUE TITLE
Blood Angels - Artisan of War, error for selecting two relics

### ISSUE THREAD

**Issue by DanteValoris** [BSData/wh40k-9e#9376]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Artisan of War - a blood angels warlord traits, allows the selection of a relic + special issue wargear. Currently taking both will trigger an alert for too many relics.

**Comment by alphalas** [comment]
Artisan has it's own separate list to take from, Labeled Artisan of War SIW
