### ISSUE TITLE
Grey Knights: GMNDK HI pts

### ISSUE THREAD

**Issue by nairul** [BSData/wh40k-9e#9377]
**File/Catalogue:** Imperium - Grey Knights

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Description:** In latest 2021 Munitorum Field Manual the point cost of Heavy Incinerator was omitted for Grand Master in Nemesis Dreadknight. According to the rules of that document: "weapons and wargear not listed in a unit’s entry cost no additional points to include in that unit" (pg 1). So technically the Heavy Incinerator should be 0pts for GMNDK, and not cost 20pts as it does in Battlescribe now. While it's very possible this was an oversight on GW's part, the cost in Battleforged is reflected at 0pts as well.

**Comment by tekton** [comment]
I was wondering how long it would take people to see that...we're also only a little bit from FAQ territory so going to leave it as is for now, but will change it if its still not in there.

**Comment by tekton** [comment]
MFM stealth update kept it at free
