### ISSUE TITLE
Chaos - Chaos Space Marines: Can't add Mortarion to a CSM Supreme Command Detachment

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9379]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Mortarion is only selectable in DG supreme command, not Heretic Astartes.

**Comment by Mad-Spy** [comment]
Correct, he's a Death Guard character and appears in that catalogue.

**Comment by brentsimon** [comment]
However, as he also has Faction Keyword: Heretic Astartes, shouldn't he be selectible in both catalogs?

**Comment by alphalas** [comment]
You can. Include a child detachment.

**Comment by alphalas** [comment]
https://github.com/BSData/wh40k/wiki/Creating-Detachments-Using-Multiple-Factions

**Comment by brentsimon** [comment]
Current build of Battlescribe is not allowing a child Supreme Command to attach to a parent Supreme Command in iOS.

**Comment by alphalas** [comment]
Tangential question; since a SCD is one unit only why are you trying to take a HA detachment and loose all the DG benefits?

**Comment by brentsimon** [comment]
HA Mortarion loses plague company only assuming mixed force already. 
Then slaanesh demon detachment. 
Then Tzeentch detachment with Terminators and LoC. Use the HA SC to unlock term strats and get a relic.

**Comment by Mad-Spy** [comment]
Mortarion cannot grant a Chaos Space Marines Relic, as he can never be a "Chaos Space Marines Warlord". "Chaos Space Marines" units cannot be from the DEATH GUARD Legion.

In your example, ~~having your Tzeentch CSM Detachment is enough to allow you to use CSM Stratagems, but you will only be able to get a Relic for that Detachment by paying for it via the Gifts of Chaos Stratagem.~~ you can only possibly get Relics in the Slaanesh Daemon Detachment as it is the only one that fulfils the necessary criteria, but you'd have to pay CP to get any.
