### ISSUE TITLE
Astra Militarum - Guardsman W/ Special Weapon limited to Snipers

### ISSUE THREAD

**Issue by CaptainJin** [BSData/wh40k-9e#9380]
**File/Catalogue:** Imperium - Astra Militarum v296

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Guardsman W/ Special Weapon are restricted to only Sniper Rifles

**Comment by CaptainJin** [comment]
This also happens to Veterans w/ Special Weapons

**Comment by Valorcalls** [comment]
Duplicate of #9342
