### ISSUE TITLE
Dark Angels Issues

### ISSUE THREAD

**Issue by chronocobra** [BSData/wh40k-9e#9389]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:**

1) Redemptor Dreadnought is 15pts, should be 175
2) Primaris Lieutenant is 15pts, should be 75
3) Rites of Initiation for a Captain is 15pts, should be 20
4) Rites of Initiation for a Dreadnought is 20pts, should be 15.
4) Spelling error in 'Fury of the Lion' WL trait
5) Special Issue Bolt Carbine currently has AP 2 instead of AP -2
6) Narthecium [Aura] is currently 3" for both the Ravenwing & Deathwing Apothecary, should be 6"
7) 'Atonement' Relic is not available for the Primaris Captain with Plasma Pistol & Power Fist
8) Missing Stratagem 'Marked for Command' (the one that allows Special Issue Wargear to be taken by a Sergeant or equiv)
9) Primaris Chaplain cannot currently take the 'Mace of Redemption' relic, should be able to.

**Comment by Thairne** [comment]
Where is that Special Issue Bolt Carbine to be found?

**Comment by chronocobra** [comment]
Space Marines Catalogue under Shared Selection Entries
