### ISSUE TITLE
Infantry and Command Squad Special weapons Validation error

### ISSUE THREAD

**Issue by Kal451** [BSData/wh40k-9e#9396]
**File/Catalogue:** 
Imperium - Astra Militarum

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux
Windows

**Dropbox:** 
No

**Description:** Detailed issue description.
When selecting special weapons in Infantry and Command squads selecting any weapon other than sniper rifle produces a validation error that the "Veteran\Guardsman w/ Special weapon must have 1 more selections of Sniper Rifle (minimum 1)"

**Comment by Technoblazed** [comment]
Update your data.
