### ISSUE TITLE
Ultramarines - Honour Guard has incorrect ability text

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#9398]
**File/Catalogue:** Imperium - Adeptus Astartes - Ultramarines v41

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Honour Guard's Honour Guard ability has incorrect text and should read as: "While a friendly ULTRAMARINES CHARACTER unit that has a Wounds characteristic of 9 or less is within 3" of this unit, enemy models cannot target that CHARACTER unit with ranged attacks."

**Comment by acebaur** [comment]
This is because they are also a Legend's unit for everyone. The compromise is UM get to have both abilities listed rather than further bloat the Lib with the insane hide logic it would need.
