### ISSUE TITLE
Ravenwing Talonmaster/Deathwing strikemaster missing 

### ISSUE THREAD

**Issue by Etharin** [BSData/wh40k-9e#9401]
**File/Catalogue:** Imperium - Adeptus Astartes - Dark Angels v192

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** Ravenwing Talonmaster is missing as a HQ option. Have got Dark Angels selected as chapter so Asmodai, Ezekial etc. show up. Deathwing strikemaster also not showing.

**Comment by Mad-Spy** [comment]
They are Lieutenants, and thus is in the Lieutenants "squad" due to the Company Heroes rule.
