### ISSUE TITLE
Death Guard: Noxious blightbringer not showing

### ISSUE THREAD

**Issue by tomal07** [BSData/wh40k-9e#9412]
**File/Catalogue:** Death Guard (data version 9.1.14)

**BattleScribe version:** 2.03.25.338.

**Platform:** Android

**Dropbox:** Yes

**Description:** I can't find the Noxious Blightbringer to add to my list. Should be in elites, but it's not there and nowhere else.

**Comment by Mad-Spy** [comment]
Try under "Foetid Virions".
