### ISSUE TITLE
No Data on Emperor's Spears UM successor WT and Relics

### ISSUE THREAD

**Issue by MetalAdMech** [BSData/wh40k-9e#9423]
**File/Catalogue:** Warhammer 40k v9 1.14

**BattleScribe version:** 2.03..25.338

**Platform:** Android

**Description:** When building a list all ES Warlord Traits and Relics are unavailable as choices. 

Warlord traits:

Bloodied But Unbroken: Warlord gains +1A and an additional +1A after they lose their first wound.

Tribal Heritage: Once per battle, this Warlord can re-roll one failed hit, wound, OR saving throw, and if your army is Battle-Forged, one Epic Deed stratagem can be used on your Warlord for free.

Sentinel of The Veil: Warlord always fights first and can make a 6" Heroic Intervention.

Relics:

Druidic Talisman: Librarian or Chaplain only. Once per turn, you can re-roll a Psychic Test or Inspiring Litany Test. 

Beast-Hide Cloak: Attacks against the bearer suffer -1D (D1 minimum). 

Horizon Blade: Replaces bearers power sword or master-crafted power sword. S+2, AP-4, D2, becomes AP-5 and D3 if the bearer charged or made a Heroic Intervention.

**Comment by acebaur** [comment]
It will be out in the next release
