### ISSUE TITLE
Updated Dark Angels?

### ISSUE THREAD

**Issue by LunarWarrior21** [BSData/wh40k-9e#9424]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Sorry, this isn't exactly an issue, but when will the dark angels be updated with the new units?  I understand the subject implies that they are coming soon, but when will that be?  Not trying to sound rude, just curious.  Thanks!

**Comment by Mad-Spy** [comment]
When it's done. Probably in this week's release, on Thursday.
