### ISSUE TITLE
Dark Angels - Codex QA Pass

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#9427]
**File/Catalogue:** Imperium - Adeptus Astartes - Dark Angels v192

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [x] Inner Circle is listed as an ability but should be a rule
- [x] Inner Circle has non-capitalised keywords and should read as:
“If this unit has the Grim Resolve Chapter Tactic, or it has the Inheritors of the Primarch Successor tactic and it is using the Chapter Tactic of the Dark Angels, then: 
• Each time a Morale test is taken for this unit, it is automatically passed.
• While this unit is within Engagement Range of any enemy FALLEN units, unless this unit has the VEHICLE keyword, this unit cannot be selected to Fall Back. 
• Each time you select this unit to Fall Back, unless it has the VEHICLE, RAVENWING or CHAPTER MASTER keywords, roll 2D6: if the result is less than or equal to the unit’s Leadership characteristic it can Fall Back, otherwise it cannot Fall Back and must Remain Stationary instead.
• Each time an attack is made against this unit, if this unit has the INFANTRY keyword, an unmodified wound roll of 1-3 always fails, irrespective of any abilities that the weapon or the model making that attack may have.”
- [x] Chapter Master has non-capitalised keywords and should read as: “In your Command phase, select one friendly DARK ANGELS CORE or DARK ANGELS CHARACTER unit within 6" of this model. Until the start of your next Command phase, each time a model in that unit makes an attack, you can re-roll the hit roll.”
- [x] Azrael’s Lion’s Wrath is listed as an ability but should be listed as a weapon profile
- [x] Azrael’s master-crafted boltgun is named incorrectly and should be named as “Lion’s Wrath - master-crafted boltgun”
- [x] Azrael’s master-crafted plasma gun is named incorrectly and should be named as “Lion’s Wrath - master-crafted plasma gun”
- [x] Watcher in the Dark has non-capitalised keywords and should read as: “Once per battle, this unit can attempt to Deny the Witch as if it were a PSYKER. If the model attempting to manifest the psychic power is a CHAOS PSYKER, you can re-roll that Deny the Witch test.”
- [x] Rites of Battle (Aura) has non-capitalised keywords and should read as: “While a friendly DARK ANGELS CORE unit is within 6" of this model, each time a model in that unit makes an attack, re-roll a hit roll of 1.”
- [x] Lion Helm (Aura) has non-capitalised keywords and should read as: “While a friendly DARK ANGELS INFANTRY or DARK ANGELS BIKER unit is within 6" of this model, models in that unit have a 4+ invulnerable save against ranged attacks.”
- [x] Belial’s lightning claw (pair) aren’t flagged as [Legends] in the wargear selection panel
- [x] Belial’s thunder hammer & storm shield aren’t flagged as [Legends] in the wargear selection panel
- [x] Belial’s Sword of Silence’s ability text has non-capitalised keywords and should read as: “Each time an attack is made with this weapon against a unit that is not a VEHICLE, an unmodified wound roll of 2+ is always successful.”
- [x] Belial’s Grandmaster of the Deathwing ability has non-capitalised keywords and should read as: “In your Command phase, select one friendly DEATHWING CORE or DEATHWING CHARACTER unit within 6" of this model. Until the start of your next Command phase, each time a model in that unit makes an attack, you can re-roll the hit roll.”
- [x] Jink is listed as an ability but should be a rule
- [x] Sammael’s Grand Master of the Ravenwing ability has non-capitalised keywords and should read as: “In your Command phase, select one friendly RAVENWING CORE or RAVENWING CHARACTER unit within 6" of this model. Until the start of your next Command phase, each time a model in that unit makes an attack, you can re-roll the hit roll.”
- [x] Sammael currently has a Move characteristic of 14”, but should be 15”
- [x] Ezekiel’s Traitor's Bane’s ability text has non-capitalised keywords and should read as: “Each time an attack made with this weapon is allocated to a FALLEN or HERETIC ASTARTES unit, that attack has a Damage characteristic of 3.”
- [x] Ezekiel’s Book of Salvation (Aura) ability has non-capitalised keywords and should read as: “While a friendly DARK ANGELS CORE or DARK ANGELS CHARACTER unit is within 6" of this model, each time that unit fights, until that fight is resolved, add 1 to the Attacks characteristic of models in that unit. This is not cumulative with the additional attack granted by the Shock Assault ability (see Codex: Space Marines).”
- [x] Spiritual Leaders (Aura) ability has typos and non-capitalised keywords, and should read as: “While a friendly DARK ANGELS CORE unit is within 6" of this model, models in that unit can use this model’s Leadership characteristic instead of their own.”
- [x] Ravenwing Talonmaster’s No Escape (Aura) ability text has non-capitalised keywords and should read as: “In your Command phase, you can select one enemy unit visible to this model. Until the start of your next Command phase, while a friendly DARK ANGELS RAVENWING CORE unit is within 6” of this model, each time a model in that RAVENWING unit makes an attack, that enemy unit does not receive the benefits of cover to its saving throw against that attack.”
- [x] Tactical Precision (Aura)	 ability has non-capitalised keywords and should read as: “While a friendly DARK ANGELS CORE unit is within 6” of this model, each time a model in that unit makes an attack, re-roll a wound roll of 1.”
- [x] Lazarus’s profile is incorrectly named as “Master Lazarus”
- [x] Lazarus’s Enmity’s Edge has a typo in its name, and is incorrectly named “Emnity’s Edge”
- [x] Lazarus’s Enmity’s Edge’s ability text has non-capitalised keywords and should read as: “Each time an attack made with this weapon is allocated to a PSYKER model, that attack has a Damage characteristic of 4.”
- [x] Lazarus’s The Spiritshield Helm (Aura) ability has non-capitalised keywords and should read as: “While a friendly DARK ANGELS unit is within 6" of this model, each time a model in that unit would lose a wound as the result of a mortal wound, roll one D6, adding 1 to the result if it is this model that would lose a wound: on a 5+, that wound is not lost.”
- [x] Several models appear to currently have a unique version of the Narthecium (Aura) ability, but there doesn’t appear to be a need for this:
1. Deathwing Apothecary
1. Ravenwing Apothecary
- [x] Deathwing Champion currently has an Attacks characteristic of 3, but should be 4
- [x] Deathwing Champion’s Halberd of Caliban currently has an AP characteristic of -4, but should be -3
- [x] Combat Squads is currently an ability but should be a rule
- [x] When a Deathwing Command Squad has exactly 3 models, it currently costs 4 PL, but should cost 10 PL
- [x] The Command Squad ability seems unnecessary, due to being covered by Battlescribe’s logic, for several units:
1. Deathwing Apothecary
1. Deathwing Champion
1. Ravenwing Apothecary
1. Ravenwing Champion
1. Ravenwing Ancient
- [x] Martial Superiority ability has non-capitalised keywords and should read as: “At the start of the Fight phase, if this model is within Engagement Range of any enemy CHARACTER units, it can fight first that phase.”
- [x] Ravenwing Champion is unable to exchange their plasma talon for am Astartes grenade launcher
- [x] Plasma Talon (supercharge) is incorrectly named as “Plasma Talon (overcharge)”
- [x] Plasma Talon (supercharge) has incorrect ability text and should read as: “If any unmodified hit rolls of 1 are made for attacks with this weapon profile, the bearer is destroyed after shooting with this weapon.”
- [x] Ravenwing Ancient’s Astartes Banned (Aura) has non-capitalised keywords and the first sentence should read as: “While a friendly DARK ANGELS CORE unit is within 6" of this model, add 1 to the Leadership characteristic of models in that unit.”
- [x] Ravenwing Black Knights are missing the Combat Squads rule
- [x] Ravenwing Dark Shroud’s Icon of old Caliban (Aura) ability has non-capitalised keywords and should read as: “While a friendly DARK ANGELS unit is within 6” of this model, each time a ranged attack is made against that unit, subtract 1 from that attack’s hit roll.”
- [x] Ravenwing Land Speeder Vengeance’s Plasma storm battery (supercharge) is incorrectly named as “Plasma storm battery (overcharge)”
- [x] Ravenwing Dark Talon is still using the old profile system from 8th edition
- [x] Ravenwing Dark Talon currently has a Wounds characteristic of 10, but should be 11
- [x] Ravenwing Dark Talon’s Wound Tracker 1 currently has a Remaining W profile of 6-10, but should be 6+
- [x] Ravenwing Dark Talon’s Stasis Bomb ability has non-capitalised keywords and the final sentence should read as: “While a unit (excluding VEHICLE and MONSTER units) is caught in stasis, it cannot Fall Back.”
- [x] Ravenwing Dark Talon is missing its Explodes ability
- [x] Nephilim Jetfighter is still using the old profile system from 8th edition
- [x] Nephilim Jetfighter’s Air Superiority ability has non-capitalised keywords and should read as: “Each time this model makes a ranged attack against an AIRCRAFT unit, add 1 to that attack’s hit roll.”
- [x] Nephilim Jetfighter’s Wound Tracker 1 currently has a Remaining W profile of 6-10, but should be 6+
- [x] Nephilim Jetfighter currently has a Wounds characteristic of 10, but should be 11
- [x] Nephilim Jetfighter’s Wound Tracker 2 currently has a Move profile of 20”-35”, but should be 20-40”
- [x] Nephilim Jetfighter’s Blacksword missile launcher’s ability text has a typo and non-capitalised keywords and should read as: “Each time an attack made with this weapon is allocated to an AIRCRAFT model, that attack has a Damage characteristic of 4.”
- [x] If a Primaris Lieutenant takes Rites of Initiation when not equipped with a storm shield, no error is thrown
- [x] Several units that can transport Terminators are unable to take the Rites of Initiation:
1. Mastodon
1. Sokar-Pattern Stormbird
1. Spartan
1. Thunderhawk Gunship
1. Thunderhawk Transporter [Legends]
- [x] Grim Resolve has incorrect rule text and should read as:
“• Each time a model with this tactic makes an attack, unless that model’s unit has moved this turn (excluding pile-in and consolidation moves), add 1 to that attack’s hit roll.
• Each time a Combat Attrition test is taken for a unit with this tactic, it is automatically passed.”
- [x] 1st Company rule has typos and non-capitalised keywords, and should read as:
“If every unit in your army (except UNALIGNED units) has the DARK ANGELS keyword, then DARK ANGELS Vanguard Detachments that only contain models with the DEATHWING and/or INNER CIRCLE keywords gain the 1st Company ability.
• Deathwing Terminator Squad, Terminator Squad, Terminator Assault Squad and Relic Terminator Squad units in this Detachment gain the Objective Secured ability.
• If your WARLORD is part of this Detachment, this Detachment's Command Benefits are changed to '+3 Command points'.”
- [x] 2nd Company rule has typos and non-capitalised keywords, and should read as:
“If every unit in your army (except UNALIGNED units) has the DARK ANGELS Keyword, then DARK ANGELS Outrider Detachments that only contain models with the RAVENWING keyword gain the 2nd Company ability.
• Bike Squad and Outrider Squad units in this Detachment gain the Objective Secured ability.
• If your WARLORD is part of this Detachment, this Detachment's Command Benefits are changed to '+3 Command points'.”
- [x] Speed of the Raven rule has typos and non-capitalised keywords, and should read as:
“While the Devastator Doctrine is active for your army:
• Add 3" to the Move characteristic of RAVENWING models from your army.
• RAVENWING units from your army are eligible to shoot with in a turn in which they Advanced. Each time a model in that unit makes a ranged attack in a turn in which it Advanced, that attack suffers the penalty incurred to the hit roll as if firing an assault weapon.
- [x] Fire Discipline rule has typos and non-capitalised keywords, and the first sentence should read as: “While the Tactical Doctrine is active for your army, INFANTRY models from your army (excluding DEATHWING models) can make attacks with Rapid Fire and Assault Weapons (excluding Blast weapons) while withing Engagement Range of enemy units, but must target an enemy unit that is within Engagement Range of its own unit when they do so.”
- [x] Implacable rule has typos and non-capitalised keywords, and should read as: “While the Assault Doctrine is active for your army, each time a DEATHWING INFANTRY or DEATHWING DREADNOUGHT model from your army makes a melee attack against a CHARACTER unit or unit that contains any models with a wounds characteristic if 8 or more, you can re-roll the wound roll.”
- [x] The Relentless Hunt rule is no longer applicable and should be removed
- [x] Configurations options for Ravenwing Outrider Detachment and Deathwing Vanguard Detachment should be max 0 in Force unless the Warlord is in the Detachment. ~~unique and not be able to stack with one another, due to being Warlord limited~~ 
- [x] 1. Brilliant Strategist Warlord trait has non-capitalised keywords, and the first sentence should read as: “In your Command phase, you can select one friendly DARK ANGELS unit within 6" of this WARLORD.”
- [x] 2. Fury of the Lion (Aura) Warlord trait has non-capitalised keywords, and should read as: “While a friendly DARK ANGELS unit is within 6" of this WARLORD, if this WARLORD has made a charge move, was charged or performed a Heroic Intervention this turn, add 1 to the Strength Characteristic of models in that unit.”
- [x] 3. Calibanite Knight Warlord trait has a typo in its name, and is currently named “3.Calibanite Knight”
- [x] 3. Calibanite Knight Warlord trait has non-capitalised keywords, and should read as: “Each time this WARLORD makes a melee attack against an INFANTRY or BIKER unit, an unmodified wound roll of 2+ is always successful.”
- [x] 4. Stubborn Tenacity Warlord trait has a typo and non-capitalised keywords, and should read as: “When this WARLORD is destroyed, if it does not explode, you can use this Warlord Trait instead of using any other abilities that take effect as a result of this model being destroyed (e.g. Astartes Banner). If you do, this WARLORD is not removed from play until the start of the next turn or the end of the battle (whichever comes first). Until that happens, it is still considered to be in play, but any further wounds this WARLORD would lose are not lost.”
- [x] 5. Decisive Tactician (Aura) Warlord trait has a typo in its name and is incorrectly named “5. Decisive Tactitian (Aura)”
- [x] 5. Decisive Tactician (Aura) Warlord trait has non-capitalised keywords, and should read as: “While a friendly DARK ANGELS CORE unit is within 6" of this WARLORD, add 1 to Advance and charge rolls made for that unit.”
- [x] 6. Honour of the First Legion Warlord trait has incorrect text, and should read as:
“• This WARLORD is eligible to perform a Heroic Intervention if it is within 6" horizontally and 5" vertically of an enemy unit.
• Each time this Warlord makes a Heroic Intervention move, so long as it ends that move closer to the closest enemy model, it can move up to 6”. All other rules for Heroic Interventions still apply.”
- [x] 1-3. Lightning-fast Reactions Warlord trait has non-capitalised keywords, and should read as: “Each time an attack is made against this WARLORD, subtract from the attack's hit roll.”
- [x] 4-6. Master of Manoeuvre Warlord trait has non-capitalised keywords, and should read as: “This WARLORD is eligible to either shoot and charge in a turn in which it Fell Back.”
- [x] 1-3. Watched Warlord trait has incorrect text, and should read as: “Once per battle, in your opponent’s Psychic phase, this WARLORD can attempt to resist one additional psychic power, even if it is not a PSYKER and even if it is not within 24" of the enemy model manifesting that psychic power. When taking that Deny the Witch test, do not roll the dice; it is automatically passed.”
- [x] 4-6. Inexorable Warlord trait has non-capitalised keywords, and should read as: “Each time an attack is allocated to this WARLORD, subtract 1 from that attack's Damage characteristic (to a minimum of 1).”
- [x] Several units can only take a specific Warlord trait each, but all illegal options are still showing instead of being hidden:
1. Asmodai
1. Azrael
1. Belial
1. Ezekiel
1. Lazarus
1. Sammael
- [x] 1) Mind Worm Psychic Power has non-capitalised keywords, and the first sentence should read as: “Malediction: Mind Worm has a warp charge value of 6. If manifested, select one enemy unit within 18" of this PSYKER.”
- [x] 2) Aversion Psychic Power has non-capitalised keywords, and should read as:
“Malediction: Aversion has a warp charge value of 6. If manifested, select one enemy unit within 24" of this PSYKER. Until the start of your next Psychic phase:
• While that unit is within 6" of this PSYKER, subtract 1 from the Attacks characteristic of models in that unit.
• Each time a model in that unit makes an attack, subtract 1 from that attack's hit roll.”
- [x] 3) Righteous Repugnance Psychic Power has non-capitalised keywords, and the second sentence should read as: “If manifested, select one friendly DARK ANGELS unit within 12" of this PSYKER.”
- [x] 4) Trephination Psychic Power has non-capitalised keywords, and the second sentence should read as: “If manifested, the closest enemy unit within 18" and visible to this PSYKER suffers D3 mortal wounds.”
- [x] 5) Engulfing Fear Psychic Power has typos and non-capitalised keywords, and should read as:
“Malediction: Engulfing Fear has a warp charge value of 7. If manifested, select one enemy unit within 24" of this PSYKER. Until the start of your next psychic phase:
• Subtract 1 from Leadership characteristic of models in that unit.
• That unit cannot use the Objective Secured ability or any similar abilities that allow them to control an objective marker regardless of the number of enemy models within range of an objective marker.
• If the result of the Psychic test was equal to or greater than that unit's Leadership characteristic, that unit cannot perform actions (if that unit is currently performing an action, it immediately fails).”
- [x] 6) Mind Wipe Psychic Power has non-capitalised keywords, and the second sentence should read as: “If manifested, select one enemy unit within 18" of this PSYKER, then select one aura ability that unit has.”
- [ ] Relics of Caliban are currently selectable as tick boxes allowing multiple relics to be taken, but should be only selectable as radio buttons to allow a single option
- [x] Mace of Redemption’s relic ability text has typos and non-capitalised keywords, and should read as: “Each time an attack is made with this weapon against a FALLEN or HERETIC ASTARTES unit, an unmodified wound roll of 4+ inflicts 2 mortal wounds on the target and the attack sequence ends.”
- [x] Pennant of Remembrance’s relic ability text has typos and non-capitalised keywords, and should read as: “In your Command phase, select one DEATHWING INFANTRY CORE unit from your army within 6" of the bearer. Until the start of your next Command phase, each time an attack is allocated to a model in that unit, subtract 1 from the Damage characteristic of that attack (to a minimum of 1).“
- [x] Reliquary of the Repentant’s relic ability text has typos, and should read as: “While an enemy unit is within 3" of the bearer, each time an invulnerable saving throw is made for a model in that unit that has an invulnerable save of 4+ or better, the saving throw is only successful on an unmodified roll of 5+.”
- [x] Eye of the Unseen’s relic ability text has missing text and non-capitalised keywords, and should read as:
“• The bearer gains the following ability 'Fear (Aura): While an enemy unit is within 6" of the bearer, subtract 1 from the Leadership characteristic of models in that unit.'
• At the start of the Fight phase, if an enemy CHARACTER unit is within Engagement Range of the bearer, that unit is not eligible to fight until all other eligible units from your army have done so.”
- [x] Cup of Retribution relic’s Feast of Malediction litany ability has non-capitalised keywords, and should read as: “While a friendly DARK ANGELS CORE unit is within 6" of this PRIEST, add 1 to the Attacks characteristic of models in that unit.”
- [x] Artificer Armour is unable to be taken as a Special-Issue Wargear relic on any character
- [x] Bolts of Judgement’s relic ability text has typos and non-capitalised keywords, and should read as: “When you give a model this Relic, select one bolt weapon (see Codex: Space Marines) that model is equipped with. Each time the bearer shoots with that weapon, you can choose for it to fire a bolt of judgement. If you do, you can only make one attack with that weapon, but that attack has an Armour Penetration characteristic of -2 and a Damage characteristic of 3. When making that attack, unless the target is a VEHICLE or MONSTER unit, a wound roll of 2+ is always successful.”

**Comment by Thairne** [comment]
Deathwing Apothecary and Ravenwing Apothecary have a 6" radius for their Narc.

Turning Combat Squads into a rule is something that affects all marine cats and should be done after talking to @acebaur.

That means, as of now, only relics as radio buttons, combat squads rule and hiding of WLTs is in need of doing. Don't know if I can do that before today's release, but since they're all UX improvements they shouldn't be a concern.
