### ISSUE TITLE
Tyranid Warriors missing weapon replacement selection

### ISSUE THREAD

**Issue by Sp0RK3d** [BSData/wh40k-9e#9428]
**File/Catalogue:** Warhammer 40,000 v9.1.14

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description:** Found that Tyranid Warriors are missing the ability to modify the Wargear options when it comes to weapons. Tyranid codex, page 89,  states for the Tyranid Warriors:
"Any model may replace it's devourer with one weapon from the Basic Bio-weapons or Mele Bio-weapons list."
"Any model may replace it's scything talons with one weapons from the Mele Bio-weapons list."
"For every three models in the unit, one model may replace its devourer with one weapon from the Basic Bio-cannon list."

**Comment by Technoblazed** [comment]
Add the Tyranid Warrior with Bio-cannon from the unit selection.

![Image](https://i.tech-no.me/2021/02/11/210211035117.png)
