### ISSUE TITLE
Dark Angels - 1st Company / 2nd Company gives CP regardless of Warlord location

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#9431]
**File/Catalogue:** Imperium - Adeptus Astartes - Dark Angels v193

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Ravenwing Outrider Detachments and Deathwing Vanguard Detachment configuration options always give +3 CP when taken, but only the one which contains the army's Warlord should give +3 CP and the others should give 0 CP.

**Comment by Thairne** [comment]
Forgot to #mention this one
