### ISSUE TITLE
Imperium - Dark Angels: Some Special Issue Wargear missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9434]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.00

**Platform:** Android

**Dropbox:** No

**Description:** DA SIW are missing (Mostly the SIW power sword) as well as Paragon of the Chapter not showing for the warlord

**Comment by Thairne** [comment]
Heavenfall blade replaces a power sword. Are you sure the model has one?
