### ISSUE TITLE
Dark Angels - Stratagem: Relics of the Chapter is not functioning correctly

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#9439]
**File/Catalogue:** Imperium - Adeptus Astartes - Dark Angels v194

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Stratagem: Relics of the Chapter is increasing the max amount of Relics by 2, regardless of the amount of CP spent.

**Comment by Thairne** [comment]
![grafik](https://user-images.githubusercontent.com/8590840/107771418-05a30580-6d3b-11eb-92a0-2b0c4aa95f31.png)
