### ISSUE TITLE
Grey Knights: Dreadknight incinerator cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9448]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Grey Knights dreadknight incinerator is no 0 points when it used to be 20 and should still remain 20

**Comment by Technoblazed** [comment]
![Image](https://i.tech-no.me/2021/02/19/210219155246.png)

It already is 20 points.
