### ISSUE TITLE
Space Wolves Characters Missing

### ISSUE THREAD

**Issue by LostFatty** [BSData/wh40k-9e#9450]
**File/Catalogue:** Warhammer 40,000 v9.1.15

**BattleScribe version:** 2.03.

**Platform:** Mac and iOS

**Dropbox:** No

**Description:** All of the named characters in the Space Wolves chapter are not listed on the available selection list.  The last time I know the characters were available was Space Wolves v172.  I am able to use an old list to copy and build a new list but I am assuming the points do not get updated.

**Comment by acebaur** [comment]
Select space wolves as your chapter

**Comment by LostFatty** [comment]
Sorry about that, never noticed that selection.

Respectfully,

*Matt Langdon*

Connect on LinkedIn <https://www.linkedin.com/in/mattlangdon/>
