### ISSUE TITLE
Dark Angels - some Lieutenants can't take Paragon Of The Chapter

### ISSUE THREAD

**Issue by ThePants999** [BSData/wh40k-9e#9451]
**File/Catalogue:** Imperium - Adeptus Astartes - Dark Angels v193

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** 
DA have the "Paragon of the Chapter" stratagem to give their Warlord a second Warlord Trait. If you add Lieutenants to a Dark Angels detachment, this option is offered to "Lieutenant", "Deathwing Strikemaster" or "Ravenwing Talonmaster", but it is not offered to "Lieutenant in Phobos Armour", "Lieutenant in Reiver Armour" or "Primaris Lieutenant".

**Comment by ThePants999** [comment]
I'll add this here rather than open a new issue - in addition, Paragon of the Chapter doesn't seem to always _work_ when it is taken. I've got a Ravenwing Champion who is my Warlord; I've given him Paragon of the Chapter plus Fury of the Lion and Decisive Tactician, and I'm being told that he has too many warlord traits ("maximum 1").

Oh, and while I'm here, a typo - "Decisive Tactitian", should be "Decisive Tactician".

**Comment by Thairne** [comment]
![grafik](https://user-images.githubusercontent.com/8590840/107862624-37f15780-6e4e-11eb-9cca-b545d5ce9f71.png)
