### ISSUE TITLE
Thousand Sons - Rubric Marines > Aspiring Sorcerer can take illegal wargear

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#9454]
**File/Catalogue:** Chaos - Thousand Sons v90

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:**
Rubric Marines > Aspiring Sorcerers can currently swap their force stave for a force axe or force sword, but has no wargear option on their datasheet or in Legends that allows them to do so.

**Comment by Mad-Spy** [comment]
Yup, that's an Index option that I've forgotten to remove!
