### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Antyctus** [BSData/wh40k-9e#9456]
Hello all, I'm on the Discord and wanted to contribute.

**Comment by Technoblazed** [comment]
As informed on Discord, due to no previous pull requests/commits, the admins did not wish to provide join request access at this time.

**Comment by amis92** [comment]
Did not wish to bless @Antyctus with push permissions at this time, though please kindly consider contributing via Pull Requests, after having obtained a blessing from The High Lord Owner of The Catalogue in Question.

**Comment by Antyctus** [comment]
@Technoblazed @amis92 Thank you for letting me know, I will see what I can do via Pull Requests.
