### ISSUE TITLE
Blood Angels: Artisan of War WLT is not working correctly.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9472]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** The blood angel warlord trait Artisan of War is not working right. When I select 1 relic and then a Special issue warhead option it says I have two relics so I think it’s counting war gear as relics when they aren’t. Also, that trait specifically allows you to take a special issue wargear option in addition to any relics. Blood Angels Death Company Captain also not available so it gives error message.

**Comment by acebaur** [comment]
Special issue wargear are relics

**Comment by Mad-Spy** [comment]
You must select your SIW from the Artisan of War SIW picklist, not the standard Relic picklist.
![image](https://user-images.githubusercontent.com/29306451/108090587-af9fcc00-7072-11eb-9960-252c833cb5dc.png)

Please raise a separate issue for the Death Company Captain issue with full details of when you see the error. It does appear to be working correctly though.
