### ISSUE TITLE
Dark Angels - Paragon of the Chapter should only apply to warlord

### ISSUE THREAD

**Issue by DrDeadKnee** [BSData/wh40k-9e#9484]
**File/Catalogue:** 
DA Codex 9th Ed
 
**BattleScribe version:** 2.03.21

**Platform:** Windows
**Dropbox:** No

**Description:** Detailed issue description.
Paragon of the Chapter is a requisition stratagem from the Dark Angels codex that grants the option for warlord characters to take a second warlord trait. 

Currently, it can only be checked for non-warlord characters. This is backwards.

**Comment by Mad-Spy** [comment]
Working correctly in the current release. Update your data.

**Comment by Sheenaan** [comment]
**File/Catalogue:**
DA Codex 9th Ed (Repo v9.1.16)

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Description:**
Paragon of the Chapter, which should be pickable ONLY by warlord is:
1. Pickable even if warlord is not selected: see Strikemaster in attached link (no big deal, it raises a violation)
2. **Not pickable on Blade Guard Ancient**, even if it's warlord: see Bladeguard Ancient in attached link (that's a problem)

[DA DW 2k v01.zip](https://github.com/BSData/wh40k/files/6008889/DA.DW.2k.v01.zip)

**Comment by Mad-Spy** [comment]
1. is deliberate.
2. Please raise a separate issue to get this fixed.

**Comment by Sheenaan** [comment]
Sorry, my first time raising an issue on this git (I assume no reopening of closed issues, then).

[Issue 9489 opened.](https://github.com/BSData/wh40k/issues/9489)

Thank you for your hard work.

**Comment by DrDeadKnee** [comment]
Thank you; my apologies. I thought I had updated, but I was mistaken..
