### ISSUE TITLE
Imperium - Raven Guard: Ephrael Stern missing from catalogue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9486]
**File:** Imperium - Raven Guard.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Missing Unit and Category: Ephrael Stern & Kyganil of the BloodyTears (Non Force Org Slot, present in several other Space Marine data files, such as Space Wolves. Unit should be available for all Imperium faction forces, I believe)

**Comment by Dunamis55** [comment]
Consolidated into #9491
