### ISSUE TITLE
Cryptothralls produce error when added as Bound Creation

### ISSUE THREAD

**Issue by Emanresu123p** [BSData/wh40k-9e#9487]
![Cryptothrall Error](https://user-images.githubusercontent.com/79298990/108461509-6dc48080-7240-11eb-97d5-da996085b457.PNG)
**File/Catalogue:** Necron Codex 9th Ed

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** When adding cryptothralls through the Bound Creations ability, the program gives an error stating that a maximum of 0 cryptothralls is allowed. This only seems to occur when Orikan the Diviner or Illuminor Szeras is in the roster.

**Comment by Mad-Spy** [comment]
![image](https://user-images.githubusercontent.com/29306451/108466560-ba797d00-727b-11eb-9ddb-4a1d3967f5b6.png)

The repeat needs to be duplicated for the other CRYPTEK keyword.

**Comment by Emanresu123p** [comment]
How do you get to that menu? I'm fairly new to using battlescribe so I'm not familiar with all the ins and outs of the program.

**Comment by DrTobogganMD** [comment]
As a user, you do not. As a data dev, I do. If you're curious about data maintenance, you can open up the data editor on desktop and then open the necrons.cat file - the menu pictured is in there.  @Mad-Spy was adding that for my reference when I fix it later tonight.

**Comment by Emanresu123p** [comment]
ok thank you for the help.
