### ISSUE TITLE
Death Guard - Foetid Virion slot removed from elites choices

### ISSUE THREAD

**Issue by poliwrath86** [BSData/wh40k-9e#9488]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** The Foetid Virion slot has been removed from the elites section of the Death Guard roster, causing roster errors if trying to add Foetid Virion units individually

**Comment by Mad-Spy** [comment]
Virions have been reworked to improve the layout of the output. Remove the old version and re-add the models from the Elites and No Force Org Slot groups.

**Comment by poliwrath86** [comment]
Ah ok cool, thanks. However it does still give roster errors for patrol detachments, it either says I have too many choices in elites if I put 3 Foetid Virion units in both elites and no force org, or if I remove them from elites and just leave them in no force org, it says I have too many choices in no force org. Am I doing something wrong here?

**Comment by Mad-Spy** [comment]
You put 1 in Elites to mark the slot as in use, then add the next two from NFO.
