### ISSUE TITLE
Dark Angels - Deathwing Vanguard Detachment abilities seem not to trigger

### ISSUE THREAD

**Issue by Sheenaan** [BSData/wh40k-9e#9490]
**File/Catalogue:**
9.1.16

**BattleScribe version:** 2.03.21

**Platform:** Windows/iOS/Android/Mac/Linux

**Description:** 
Sorry to bother again: it seems that Deathwing/ Ravenwing detachment abilities are not correctly/ fully implemented yet.

In particular (I did not test exhaustively Ravenwing) when selecting Deathwing Vanguard Detachment:
1. Obsec seems to be missing from various terminator units
2. Inner Circle -> Transhuman Phisiology - seems to be missing from Inner Circle Units
3. Command Points are not refunded for warlord presence

[Only rules reference I could share](https://www.belloflostsouls.net/2021/01/warhammer-40k-dark-angel-full-detachment-rules.html)

Attached you find a [list](https://github.com/BSData/wh40k/files/6009665/DA.DW.2k.v01.zip) which reproduces the error: second detachment should be 10 CP, instead of 7.

**Comment by Mad-Spy** [comment]
1. These rules are not represented on the units themselves. They are shown in the Rules section at the bottom of the Roster.
2. These rules are not represented on the units themselves. They are shown in the Rules section at the bottom of the Roster.
3. This does appear to be broken.

**Comment by Sheenaan** [comment]
Thank you for the clarification: Good job!

**Comment by Sheenaan** [comment]
The fix doesn't seem to affect Ravenwing.
When tagging an outrider detachment as Ravenwing Outrider Detachment it awards 3 CP even if NO UNITS are in the rooster.

[This was the original issue that listed bot DW and RW detachments problem with CP and warlords](https://github.com/BSData/wh40k/issues/9431)
