### ISSUE TITLE
Imperium - Adeptus Astartes - Lieutenant validation errors

### ISSUE THREAD

**Issue by Citronnade** [BSData/wh40k-9e#9501]
**File/Catalogue:** Imperium - Adeptus Astartes v9.1.16

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** 

On the Ultramarines, Black Templars, and Deathwatch catalogues (possibly in other chapters as well), the Primaris Lieutenant is not being counted as part of the Company Command limit for lieutenants: it is possible to add multiple entries of Lieutenants, each with multiple Primaris Lieutenants in the "Up to Two" category, so that more than 2 Lieutenants are in the roster without a validation error.

In the Dark Angels and Space Wolves catalogues, this error doesn't exist--instead, there's an error if multiple entries of Lieutenants are included (so that there is an error if one tries to include 2 Lieutenants, each occupying a separate battlefield role slot [i.e. not using the Company Heroes rule to make the second one not take a slot]).

I have not tested the other catalogues.

**Comment by Mad-Spy** [comment]
1. Primaris Lts are missing the LIEUTENANT keyword.
2. DA, BA and SW should allow more than one Lieutenants units for those situations where people want to fill slots.
