### ISSUE TITLE
Imperium - Imperial Knights - Exalted Court Allegiance WLTs

### ISSUE THREAD

**Issue by Tarentus** [BSData/wh40k-9e#9502]
**File/Catalogue:** Imperium - Imperial Knights v73

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Knights can't select Questor Mechanicus/Questor Imperialis warlord traits when using Exalted Court.

**Comment by DrTobogganMD** [comment]
@Tarentus I believe you're referring to the 6 traits present in Engine War. These are not allowed for use in Exalted Court per the GW FAQ regarding the same traits for Admech.

![image](https://user-images.githubusercontent.com/16939161/109169890-e26a5400-7745-11eb-854b-f2d9fd7dd8e0.png)
