### ISSUE TITLE
DG missing rules for plague companies

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-9e#9503]
The list of warlord traits does not changes when i select different plague company. 
For example, Mortarion's Anvil get the trait ~~"Glooming boat"~~ Gloaming Bloat and the list is still 6 basic ones.

**Comment by Mad-Spy** [comment]
All the Plague Company Traits are in the data; the only time they sometimes don't show up properly is if you change Company after starting your list. Modifying something on your Warlord or reloading the list will fix that though.

![image](https://user-images.githubusercontent.com/29306451/108631251-cffbcc00-7460-11eb-9165-77a519a9ed1b.png)


![image](https://user-images.githubusercontent.com/29306451/108631239-c4a8a080-7460-11eb-9095-e1bf9bc0c6b5.png)
