### ISSUE TITLE
Deathwatch Teleport Homer has copy/pasted 8th edition keywords

### ISSUE THREAD

**Issue by corrinavatan** [BSData/wh40k-9e#9504]
**File/Catalogue:** Deathwatch

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** The text for the Deathwatch Teleport Homer looks like it was partially copy/pasted some info from the 8th edition wording of the wargear.

In the Deathwatch file, the Deathwatch Teleport Homer is worded to use the **TERMINATOR** keyword, specifically that it can only be used with a **TERMINATOR** model in the unit.

The datafile has the Homer worded as:

_Once Per Battle, at the start of your Movement phase, if this unit contains a TERMINATOR model..._

However, reading the 9e Deathwatch Codex Supplement page 58, the wording does not mention the **TERMINATOR** keyword at all, and has the following sentence:

_Once per battle, at the start of your Movement phase, you can remove this unit from the battlefield and then, In the Reinforcements step of any of your next Movement Phase, you can set this unit back up on the battlefield..._ (etc).  Nowhere does is the TERMINATOR keyword even mentioned in the entire rule for the Deathwatch Teleport Homer.

**Comment by Technoblazed** [comment]
The `if this unit contains a TERMINATOR model` is coming from the fact it can be taken in each of the Kill Teams. Not really sure what the best option here is as we can't duplicate ability names (because they will overwrite each other on output) and it doesn't exactly hurt the regular terminators output.

**Comment by Technoblazed** [comment]
We have decided we won't be fixing this as the Proteus, Cassius' and terminator squads all require a TERMINATOR model to use this ability anyway, and GW can't help but duplicate wargear entries with *different* rules.
