### ISSUE TITLE
Imperium - Dark Angels: Cup of Retribution validation issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9507]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Interrogator-Chaplain is unable to pick the "Cup of Retribution" relic. Other Chaplains are able to pick it

**Comment by Mad-Spy** [comment]
@Thairne, the Interrogator-Chaplain is using the FW instance of the CHAPLAIN keyword rather than the SM lib one which is why this isn't working.
