### ISSUE TITLE
Space Wolves Successor Relics

### ISSUE THREAD

**Issue by Bij0rn** [BSData/wh40k-9e#9509]
**File/Catalogue:** 

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes/No

**Description:** Detailed issue description.
The application does not take into account the "free" Warlord relic for a Space Wolves Successor army when it is a special issue wargear.

**Comment by Mad-Spy** [comment]
This appears to be working correctly as far as I can tell.  I can mark the Detachment as a Wolves successor, add a model which is the Warlord, and give a model a relic (whether an SIW or not) with no errors.


Please give more details on the exact composition of your list and what you are trying to achieve, or upload a copy here.

**Comment by Bij0rn** [comment]
++ Patrol Detachment 0CP (Imperium - Adeptus Astartes - Space Wolves) [47
PL, 9CP, 815pts] ++

+ Configuration +

**Chapter Selection**: Born Heroes , Space Wolves Successor, Whirlwind of
Rage

Battle Size [12CP]: 3. Strike Force (101-200 Total PL / 1001-2000 Points)

Detachment Command Cost

+ Stratagems +

A Trophy Bestowed [-1CP]

+ No Force Org Slot +

Company Veterans [8 PL, 60pts]
. Company Veteran: Bolt pistol, Boltgun
. Company Veteran: Bolt pistol, Boltgun
. Company Veteran Sergeant: Bolt pistol, Boltgun

+ HQ +

Lieutenants [6 PL, -1CP, 115pts]
. Wolf Guard Battle Leader on Thunderwolf: Astartes Chainsword, Rites of
War, Stratagem: Hero of the Chapter, The Armour of Russ, Thunder hammer

Wolf Lord on Thunderwolf [9 PL, -1CP, 170pts]: Astartes Chainsword,
Beastslayer, Chapter Command:  Chapter Master, Master-Crafted Weapon,
Stratagem: Warrior of Legend, The Imperium's Sword, Thunder hammer, Warlord

+ Troops +

Infiltrator Squad [6 PL, 130pts]: Helix gauntlet
. 4x Infiltrator: 4x Bolt pistol, 4x Frag & Krak grenades, 4x Marksman bolt
carbine
. Infiltrator Sergeant

+ Heavy Support +

Long Fangs [7 PL, 135pts]: Armorium Cherub
. Long Fang: Grav-cannon
. Long Fang: Grav-cannon
. Long Fang: Grav-cannon
. Long Fang: Grav-cannon
. Long Fang Pack Leader: Astartes Chainsword
. . Boltgun and Bolt Pistol

Long Fangs [7 PL, 135pts]: Armorium Cherub
. Long Fang: Grav-cannon
. Long Fang: Grav-cannon
. Long Fang: Grav-cannon
. Long Fang: Grav-cannon
. Long Fang Pack Leader: Astartes Chainsword
. . Boltgun and Bolt Pistol

+ Dedicated Transport +

Drop Pod [4 PL, 70pts]: Storm bolter

++ Patrol Detachment -2CP (Imperium - Adeptus Astartes - Space Wolves) [61
PL, -4CP, 1,185pts] ++

+ Configuration +

**Chapter Selection**: Born Heroes , Space Wolves Successor, Whirlwind of
Rage

Detachment Command Cost [-2CP]

+ Stratagems +

Relics of the Chapter [-1CP]: Number of Extra Relics

+ HQ +

Librarian [6 PL, 115pts]: 2. Murderous Hurricane, 4. Instincts Awoken, 5.
Storm Caller, Boltgun, Force stave, Jump Pack, Tome of Malcador

Primaris Chaplain on Bike [7 PL, -1CP, 140pts]: 2. Catechism of Fire, 3.
Exhortation of Rage, Chapter Command:  Master of Sanctity, Stratagem: Hero
of the Chapter, Wise Orator

+ Troops +

Infiltrator Squad [6 PL, 130pts]: Helix gauntlet
. 4x Infiltrator: 4x Bolt pistol, 4x Frag & Krak grenades, 4x Marksman bolt
carbine
. Infiltrator Sergeant

+ Fast Attack +

Thunderwolf Cavalry [14 PL, 275pts]
. Thunderwolf Cavalry: Lightning Claw, Storm shield
. Thunderwolf Cavalry: Lightning Claw, Storm shield
. Thunderwolf Cavalry: Lightning Claw, Storm shield
. Thunderwolf Cavalry: Lightning Claw, Storm shield
. Thunderwolf Cavalry Pack Leader: Lightning Claw, Storm shield

Thunderwolf Cavalry [14 PL, 275pts]
. Thunderwolf Cavalry: Lightning Claw, Storm shield
. Thunderwolf Cavalry: Lightning Claw, Storm shield
. Thunderwolf Cavalry: Lightning Claw, Storm shield
. Thunderwolf Cavalry: Lightning Claw, Storm shield
. Thunderwolf Cavalry Pack Leader: Lightning Claw, Storm shield

+ Heavy Support +

Eradicator Squad [14 PL, 250pts]: Heavy melta rifle
. 4x Eradicator: 4x Bolt pistol
. Eradicator Sgt

++ Total: [108 PL, 5CP, 2,000pts] ++

Created with BattleScribe (https://battlescribe.net)

**Comment by Mad-Spy** [comment]
That list gives no validation errors. What's the problem with it?

**Comment by Bij0rn** [comment]
The application tells me that there is a problem with the relics.
When I add an additional occurrence of the "Relics of the Chapter" ploy,
the error message on the relic disappears.
Or when I remove the "special issu wargear" relic from Wolf Lord on
Thunderwolves, the error message disappears.
The application seems not to take into account the "free" nature of a relic
for the Warlord.

**Comment by Mad-Spy** [comment]
The list only qualifies for 2 Relics ~~and, as posted, only contains 2 Relics.~~ One from the Warlord, and one from Relics of the Chapter.

Are you expecting one from A Trophy Bestowed? That Stratagem does not give an extra Relic; it allows you to take a Wolves Relic _instead_ of an SIW, as per its text.

Edit: I missed the MCW on the Lord, sorry.
