### ISSUE TITLE
Imperium - Iron Hands Primaris Librarian with Tome of Malcador can't split disciplines with Technomancy

### ISSUE THREAD

**Issue by kdotalpha** [BSData/wh40k-9e#9512]
**File/Catalogue:** Imperium - Adeptus Astartes - Iron Hands v35

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No?

**Description:** If you give a Primaris Librarian (and perhaps other Librarians) the Tome of Malcador relic, you cannot take 2 powers from Librarius Discipline and 1 from the Technomancy Discipline as the relic allows. Doing so gives the error "Primaris Librarian has 1 too many selections from Technomancy Discipline (maximum 0)." Issue may replicate on other faction disciplines.

**Comment by Technoblazed** [comment]
Please reference the following issues regarding Battlescribe's implementation of this:

#7028
#9006
#8975
#8974
#8718
#8619
#7608

**Comment by kdotalpha** [comment]
Your implementation of this is objectively incorrect.

**Comment by DrTobogganMD** [comment]
> Your implementation of this is objectively incorrect.

If you can provide a published clarification from GW regarding the rules behind this Relic, please forward it to us so we can correct the mistake. Assuming you cannot provide this (as it does not exist yet), please refer to the myriad of other closed issues explaining this implementation.
