### ISSUE TITLE
Orks: Big Mek weapon costs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9516]
**File:** Orks.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Big Mek in Mega Armour Power Klaw is listed as "No cost". According to the Feb 4 2021 Munitorum Field Manual p.34, Power Klaw on Big Mek in Mega Armour costs 10 points. Killsaw also costs 10 points, but is not listed as an option for Big Mek in Mega Armour. Power Klaw should be costed correctly and Killsaw should be added as an alternative to Power Klaw.

**Comment by Mad-Spy** [comment]
Cost are correct for the next release.

A Kill saw _is_ an option for this model and does not replace the power klaw, as per its datasheet.

![image](https://user-images.githubusercontent.com/29306451/109159688-d04fdc00-776c-11eb-9a83-f32026c0faa3.png)
