### ISSUE TITLE
Blood Angels - Librarian Dreadnought can't take relics

### ISSUE THREAD

**Issue by kdotalpha** [BSData/wh40k-9e#9519]
**File/Catalogue:** Imperium - Adeptus Astartes - Blood Angels v215

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** Don't know what this means

**Description:** Librarian Dreadnoughts are non-named characters and thus should be able to take relics. The specific relics available to them are Adamantine Mantle, Artificer Armour, Digital Weapons, Icon of the Angel, Master-crafted Weapon, Armor Indomitus, Honour Vehement, and Tome of Malcador.

**Comment by Valorcalls** [comment]
Please refer to the intro paragraph for the relics you listed where it states vehicles can't be given relics
