### ISSUE TITLE
Unable to select 133rd Lambdan Lions Relic

### ISSUE THREAD

**Issue by Muck1ng** [BSData/wh40k-9e#9520]
**File/Catalogue:**  Astra Militarium 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux
iOS 
**Dropbox:**
Yes
**Description:** Detailed issue description.
When selecting 133st lambdan Lions as a Tempestus scions regiment I am unable to select their heirloom of conquest it’s just not listed.  “Refractor Field Generator”

**Comment by Technoblazed** [comment]
Cannot replicate, please ensure your data is up to date or provide more detailed issue instructions.

![Image](https://i.tech-no.me/2021/02/25/210225200240.png)

**Comment by Mad-Spy** [comment]
Seems to be working fine in the current release. What model are you trying to add it to?

**Comment by Muck1ng** [comment]
I’m on data file 9.1.17

I have 1 battalion as custom guard regiment. 

Then I’ve added a Patrol selected Tempestus scions lambdan lions I’m able to select the warlord trait but not the relic. 

I’ve attached some pictures.  
![3DB8E22A-18C6-499D-8C2A-9991F80EAD51](https://user-images.githubusercontent.com/10154047/109211053-9949ec80-77a5-11eb-9fd1-4df37bbc10e7.png)
![5EEFF5EB-727A-42A7-915C-CEA819FDFBD6](https://user-images.githubusercontent.com/10154047/109211056-9b13b000-77a5-11eb-85f7-ea3133bf222b.png)
![2254AB1A-EEFB-47C9-B953-2AD558504CD9](https://user-images.githubusercontent.com/10154047/109211058-9bac4680-77a5-11eb-88da-b5fff652f4f6.png)
![9561C03F-13B8-4472-AB74-372C271744FB](https://user-images.githubusercontent.com/10154047/109211062-9cdd7380-77a5-11eb-9af7-f8bb916b7626.png)
![5246FE4B-5165-4245-AE74-E8DBA17710F1](https://user-images.githubusercontent.com/10154047/109211065-9d760a00-77a5-11eb-9a5d-f038ec72d06e.png)

**Comment by Technoblazed** [comment]
Which model is your Warlord?

**Comment by Muck1ng** [comment]
> Which model is your Warlord?

Tank commander in the battalion

**Comment by Technoblazed** [comment]
~~You need to click the Warlord box then, it's unticked in your pictures.~~

You need a tempestus warlord in order to use the tempestus relics.

**Comment by Muck1ng** [comment]
Ah ok. Where is that stated? For my future reference.  I only have GW app and not the codex.

**Comment by Technoblazed** [comment]
> If your army is led by a Warlord in a MILITARUM TEMPESTUS Detachment, you can give one of the following Relics to a CHARACTER model in a MILITARUM TEMPESTUS Detachment from your army instead of giving them a Relic from Codex: Astra Militarum.
From the PA: TGG book.

It's worth noting that Battlescribe isn't a replacement for the codexes and that the GW app will lose previous codexes as new codexes are released.

**Comment by Muck1ng** [comment]
> > If your army is led by a Warlord in a MILITARUM TEMPESTUS Detachment, you can give one of the following Relics to a CHARACTER model in a MILITARUM TEMPESTUS Detachment from your army instead of giving them a Relic from Codex: Astra Militarum.
> > From the PA: TGG book.
> 
> It's worth noting that Battlescribe isn't a replacement for the codexes and that the GW app will lose previous codexes as new codexes are released.

yeah. Only just got into guard so I’m not willing to buy 2 books with new releases around the corner.  This kind of information should really be in the official app.  Thank you dude.
