### ISSUE TITLE
Tau - Named characters appear to be available for any Sept

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#9533]
**File/Catalogue:** T'au Empire v84

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Regardless of chosen Sept, several named characters appear to be taken in a detachment. Although an error is thrown, the units are still visible for selection. Units affected:

- Aun'Shi
- Aun'Va
- Commander Farsight
- Darkstrider
- Longstrike
- Shas'o R'alai
- Shas'o R'myr [Legends]

**Comment by Mad-Spy** [comment]
This is technically how they _should_ be done, according to our guidelines. I suggest you discuss with amis on Discord.
