### ISSUE TITLE
[Craftworld] War Walker weapons loadout

### ISSUE THREAD

**Issue by tron-solo** [BSData/wh40k-9e#9534]
**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:** This might be by design.  When selecting the same weapon on the War Walker the PDF view only shows 1 weapon instead of listing both weapons or a times 2.

**Comment by Mad-Spy** [comment]
It definitely shows both weapons.

![image](https://user-images.githubusercontent.com/29306451/109393143-17c69b80-7918-11eb-8f83-5e1b7506460e.png)

**Comment by tron-solo** [comment]
Ah I was looking at weapons and not selections. TY

**Comment by Mad-Spy** [comment]
Yes, there's only one weapon _profile_ listed, because there's only one type of weapon.

**Comment by tron-solo** [comment]
makes sense, thanks for the quick response
