### ISSUE TITLE
Astra Militarum - Tempestor Prime/Tempestor Plasma Pistol Costs Switched

### ISSUE THREAD

**Issue by lewa2321** [BSData/wh40k-9e#9536]
**File/Catalogue:** Warhammer v9.1.17

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** Yes/No

**Description:** Tempestor Prime plasma pistols are free, should cost 5 points. Tempestus Scion Tempestor plasma pistols cost 5 points, should be free.

**Comment by Technoblazed** [comment]
Already fixed in next release.
