### ISSUE TITLE
Primaris Captain confused with Captain with master-crafted Heavy Bolt Rifle

### ISSUE THREAD

**Issue by DWOF** [BSData/wh40k-9e#9538]
**File/Catalogue:** 
V9.1.17

**BattleScribe version:** 2.03.
V2.03.25.338

**Platform:** Windows/iOS/Android/Mac/Linux
Android 

**Dropbox:** Yes/No

**Description:** Detailed issue description.
Primaris Captain has the data for Captain with master-crafted Heavy Bolt Rifle
No unit for Captain with master-crafted Heavy Bolt Rifle

I'm too new to figure out if I can fix this myself, feel free to point me at the relevant resources.

**Comment by Technoblazed** [comment]
Do you have any better reproduction steps, can't really replicate this here?

![Image](https://i.tech-no.me/2021/02/28/210228122709.png)

**Comment by Mad-Spy** [comment]
Which catalogue? The two models are both present and correct in every relevant catalogue as far as I can see.

**Comment by DWOF** [comment]
It was blood Angels

But I am sorry as it's probably my mistake "captain with mater -crafter heavy blot rifle" is there, and I can now see the correct options for Primaris Captain.

Going to put this down to complete user error on my side. And a big thankyou for how quickly you looked into this.
