### ISSUE TITLE
Tome of Malcador error

### ISSUE THREAD

**Issue by carlisle9** [BSData/wh40k-9e#9545]
**File/Catalogue: Warhammer 40,000 v9.1.16

**BattleScribe version: BattleScribe v2.03.21.166

**Platform:** Windows

**Dropbox:** No

**Description: Selection of Tome of Malcador on a Primaris Librarian who selects a 3rd psychic power outside of the chosen discipline gives the error: Primaris Librarian has 1 too many selections from XXXXX Discipline (maximum 0).

The same occurs for normal librarians.

**Comment by acebaur** [comment]
Data is correct, all your powers must come from the same discipline. The tome does not override this.
