### ISSUE TITLE
Tau Fusionblaster cost for Stealth Shas'vre too high

### ISSUE THREAD

**Issue by Embrandt** [BSData/wh40k-9e#9547]
**File/Catalogue:** Tau Empire 9.1.17

**BattleScribe version:** 2.03.21.166

**Platform:** Windows

**Dropbox:** Yes

**Description:**
Tau XV25 Stealth Suit Shas'vre Fusionblaster costs 15 points, should be 7

Points taken from MUNITORUM FIELD MANUAL 2021 MK I 01.03

**Comment by Dunamis55** [comment]
Confirmed that the Shas'ui w/ Fusion blaster is costed correctly, whereas the Stealth Shas'vre's fusion blaster is 15 points but should be 7 points.
