### ISSUE TITLE
Imperium - Space Wolves: WG Terminators missing power sword option

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9549]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** In Wolf Guard Terminators entry Power Sword is missing from the melee weapons list

**Comment by Mad-Spy** [comment]
They can only swap their storm bolter for a power sword, so it only appears in that list. They cannot swap their power fist for one.
