### ISSUE TITLE
DKOK Death Rider Command Squadron taking a slot

### ISSUE THREAD

**Issue by Donkkey23** [BSData/wh40k-9e#9551]
**File/Catalogue:** Imperium, Death Korps of Kreig v144

**BattleScribe version:** 2.03.21

**Platform:** Window

**Description:** Detailed issue description.

DKOK Death rider command squads are not meant to take up a fast attack slot if you are running the HQ: Death rider Squadron commander.

**Comment by Technoblazed** [comment]
You need to add the Death Rider Command Squadrons from the "No Force Org Slot" at the top.
