### ISSUE TITLE
Incorrect Data entry for Adeptus Sorroritas (Point Values)

### ISSUE THREAD

**Issue by Mchammdada** [BSData/wh40k-9e#9553]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** On closer inspection, Points values of the highlighted units are incorrect as of current Errata/FAQ of Chapter approved: Munitorum Field Manual 2021 MK1 (Updated 04/02/2021)

- Sisters Repentia
- Zephyrim Squad
- Retributor Squad

**Comment by Technoblazed** [comment]
Sounds like your data is out of date to me, all of the points for all of these units are correct per this document:

https://www.warhammer-community.com/wp-content/uploads/2020/08/gxruRl769G2olA3v.pdf
