### ISSUE TITLE
Space Marines FW - Sicaran Arcus is overpriced

### ISSUE THREAD

**Issue by kdotalpha** [BSData/wh40k-9e#9556]
**File/Catalogue:** Imperium - Space Marines v234

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** Don't know what this means

**Description:** The Sicaran Arcus costs 155pts including the Arcus launcher and a Heavy Bolter. Battlescribe charges for the first Heavy Bolter making the tank cost 170pts, which is 15 over.

**Comment by Mad-Spy** [comment]
No wargear is included in the base cost of any model unless specifically stated. All heavy bolters on the Arcus cost 15pts.

**Comment by kdotalpha** [comment]
Please re-open, this is not wargear, the model **comes** with a Heavy Bolter base for its price.

**Comment by kdotalpha** [comment]
![IMG-2550](https://user-images.githubusercontent.com/7718531/110200252-d94a4880-7e11-11eb-8598-ed044c33c5f3.jpg)
![IMG-2549](https://user-images.githubusercontent.com/7718531/110200253-da7b7580-7e11-11eb-9db3-c19885ec4970.jpg)

**Comment by Mad-Spy** [comment]
That is not how costs work. You do not get default wargear for free.

The second paragraph in the introduction to the MFM makes this clear.
