### ISSUE TITLE
Necrons: Chronomancer Selection Entry is an Upgrade, but should be a Model

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9558]
**File:** Necrons.catz

**BattleScribe version:** 2.03.21

**Platform:** Linux

**Dropbox:** No

**Description:** Chronomancer entry is described to be an upgrade, but it should be a model:

Line:

<selectionEntry id="e4d8-225b-cae1-1f20" name="Chronomancer" publicationId="61c6-c8c5-pubN65537" hidden="false" collective="false" import="true" type="upgrade">

should be:

<selectionEntry id="e4d8-225b-cae1-1f20" name="Chronomancer" publicationId="61c6-c8c5-pubN65537" hidden="false" collective="false" import="true" type="model">

**Comment by miguelcb84** [comment]
The tags I included were filtered. I meant:

Line:
```
<selectionEntry id="e4d8-225b-cae1-1f20" name="Chronomancer" publicationId="61c6-c8c5-pubN65537" hidden="false" collective="false" import="true" type="upgrade">
```

should be
```
<selectionEntry id="e4d8-225b-cae1-1f20" name="Chronomancer" publicationId="61c6-c8c5-pubN65537" hidden="false" collective="false" import="true" type="model">
```
