### ISSUE TITLE
Missing Entry: Thousand Son Screamers

### ISSUE THREAD

**Issue by RonaldHand** [BSData/wh40k-9e#9559]
**File/Catalogue:**  THousand Sounds

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/  

**Dropbox:** N/A

**Description:** Missing Entry for Screamer unit for Thousand Sons army

**Comment by Dunamis55** [comment]
Screamers aren't keyworded to Thousand Sons and can be found in the Chaos Daemons catalogue. They can be added as a child detachment if needed:
![image](https://user-images.githubusercontent.com/36267768/110214349-13602c80-7e9c-11eb-99f6-9b68e681d9f6.png)
