### ISSUE TITLE
Warhammer 40k Space Wolves Data File missing Arjac Rockfist

### ISSUE THREAD

**Issue by mschmeiz** [BSData/wh40k-9e#9566]
**File/Catalogue:** 
Warhammer 40,000 v9.1.18, v179, -> Imperium - Adeptus Astartes - Space Wolves v 184
**BattleScribe version:** 2.03.
2.03.21
**Platform:** Windows/iOS/Android/Mac/Linux
Mac
**Dropbox:** Yes/No
Yes
**Description:** Detailed issue description.
HQ Drop Down box on the unit selection menu no longer contains Arjac Rockfist as a selection potion. 
<img width="1435" alt="Screen Shot 2021-03-07 at 20 48 06" src="https://user-images.githubusercontent.com/21978093/110275717-775f1f80-7f86-11eb-80d9-c6fa73cafda0.png">

**Comment by Mad-Spy** [comment]
He's a LIEUTENANT and is therefore subject to Company Heroes despite not having it himself. You'll find him with the other Lts in their "unit".
