### ISSUE TITLE
Adepta Sororitas - Repentia Superior being hidden incorrectly

### ISSUE THREAD

**Issue by TorchStone** [BSData/wh40k-9e#9568]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** When adding a Sisters Repentia unit to a detachment the Repentia Superior is Hidden, instead it should not take up a detachment slot (i.e. not count against the elites slots in a detachment)

**Comment by Valorcalls** [comment]
See no force org slot after adding repentia to a detachment.
