### ISSUE TITLE
Ynnari - Revanant Discipline pick cannot be deselected for single power units

### ISSUE THREAD

**Issue by KalChoedan** [BSData/wh40k-9e#9571]
**File/Catalogue:** Ynnari library

**BattleScribe version:** 2.03.21
**Platform:** Windows

**Dropbox:** No

**Description:** In the radio button UI used by units which can only pick one psychic power, the "(None)" option in the Revanant discipline is hidden after a selection from that discipline is made. Unfortunately this means a unit can become stuck in an error state if the Craftworld attribute is then changed from Ynnari as it is no longer possible to unselect the existing Revenant power choice. 

Doesn't affect units which get multiple power picks as they use a checkbox UI so can uncheck an unwanted Revanant power. Can be worked around by removing and readding the affected unit to the list after switching the Craftworld, but ideally the "(None") option should stay, as happens with the Craftworld psychic disciplines for those units.

**Comment by Mad-Spy** [comment]
This is standard BS behaviour where a minimum is set with no default. 

You _can_ remove the selection directly from the model, by clicking the X in the desktop UI, or tapping the "..." menu and Remove in the mobile UI.

**Comment by KalChoedan** [comment]
Quite right - but it's not very intuitive and is definitely inconsistent with how the Runes of Battle discipline works, for example. If it's got to be one or the other, the RoB implementation certainly gives the better experience.
