### ISSUE TITLE
Craftworlds - Field Commander is not functioning correctly for non-named characters

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#9572]
**File/Catalogue:** Aeldari - Craftworlds v129

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [x] Field Commander is unable to be taken on several units when a Specialist Detachment is in use:

1. Autarch
1. Autarch [Legends]
1. Autarch with Swooping Hawk Wings
1. Autarch with Swooping Hawk Wings [Legends]
1. Autarch with Warp Jump Generator [Legends]
1. Farseer
1. Warlock
1. Bonesinger [Legends]

- [x] Taking Field Commander does not grant access to the Specialist Detachment's Warlord trait for several units:
1. Autarch Skyrunner
2. Autarch Skyrunner [Legends]
2. Farseer Skyrunner
3. Spiritseer
3. Warlord Skyrunner

**Comment by FarseerVeraenthis** [comment]
This is likely a hangover from the Ynnari untangling, thanks for raising it :smile:
