### ISSUE TITLE
Bug with Blood Angels HQ Choice: Hecaton Aiakos is supposed to be an Elite Choice

### ISSUE THREAD

**Issue by Lord-Argieus** [BSData/wh40k-9e#9574]
**File/Catalogue:** Imperium - Blood Angels

**BattleScribe version:** 2.03. 

**Platform:** Windows

**Dropbox:** No

**Description:** In the Blood Angels HQ Options we can find Hecaton Aiakos as seen in Image. This specific character is no longer a HQ but now an Elite Choice. It is correctly inputted for Salamanders but not for Blood Angels.

![Capture](https://user-images.githubusercontent.com/80419273/110677192-25f89f80-81d5-11eb-9b3e-d380a01c89d1.JPG)

Hope this can be fixed and have a great day!

**Comment by Technoblazed** [comment]
https://www.warhammer-community.com/wp-content/uploads/2020/12/TG5TwX0VYl8BM5pK.pdf

![Image](https://i.tech-no.me/2021/03/10/210310182518.png)

**Comment by Technoblazed** [comment]
Re-opening because this needs to be fixed in Salamanders and any other cats where it's wrong.

**Comment by Lord-Argieus** [comment]
Ohhh thanks for informing!

**Comment by Technoblazed** [comment]
Can't replicate in any of the other cats either, can only assume it's some out of date data. :)
