### ISSUE TITLE
Space Marines | Deathwatch | Tome of Malcador not supported

### ISSUE THREAD

**Issue by raddue** [BSData/wh40k-9e#9575]
**File/Catalogue:** Imperium - Adeptus Astartes - Deathwatch v124

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:**
1. Tome selected, but no powers selected: https://www.dropbox.com/s/rrkq2rgaq8am2mp/2021-03-10%2010_30_37-Roster%20Editor%202.03.21%20-%20Deathwatch%202000pt%20Terminator%20Missile%20More%20Melee%20%28Warhamm.png?dl=0
2. Tome selected, with a power selected (note the second discipline disappears): https://www.dropbox.com/s/q53p3ytzwy4c8kw/2021-03-10%2010_30_55-Roster%20Editor%202.03.21%20-%20Deathwatch%202000pt%20Terminator%20Missile%20More%20Melee%20%28Warhamm.png?dl=0

**Description:** 

The Tomb of Malcador is not supported properly.  After choosing it, none of the other psychic disciplines that the Librarian has access to appear after any since power is selected.

Tested flows:
1. After removing all selected powers after selecting the relic, all of the supported disciplines appear but selecting any of the powers in either of them lock the Librarian into that specific discipline.
2. After removing all relics and powers from the Librarian, re-adding the relic and selecting any one power locks the Librarian into that specific discipline.

**Comment by acebaur** [comment]
Data is correct, Tome does not override the supplement restrictions.
