### ISSUE TITLE
Grey Knights - Multiple units have collective wargear at the squad level instead of per model

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#9580]
**File/Catalogue:** Imperium - Grey Knights v79

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Several units have Frag & Krak Grenades and Psyk-Out Grenades at the squad level, instead of per model:

1. Strike Squad
2. Terminator Squad
3. Paladin Squad
4. Purifier Squad
5. Interceptor Squad
6. Purgation Squad

**Comment by tekton** [comment]
it slows things down a ton on mobile if you put them on individuals, that's why its on top

**Comment by tekton** [comment]
Half done- now that I’m home should be able to finish
