### ISSUE TITLE
Imperium - Dark Angels - Deathwing Ancient Missing Inner Circle Ability

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9581]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Deathwing Ancient in Terminator Armor currently only displays the rules “Angels of Death” and “Teleport Strike” after rendering the roster. Deathwing Ancient should also have the “Inner Circle” rule, per having the “Deathwing” keyword.

**Comment by Dunamis55** [comment]
When using the roster, please ensure you're using the "Inline profiles" or "Profile summary" options, as they should show the unit's abilities as such:
![image](https://user-images.githubusercontent.com/36267768/111002951-2d0ee180-837e-11eb-82ab-5e4cac31a115.png)
Please note that "Rules" are considered to be army/detachment-wide rules and "Abilities" are datasheet-specific abilities.

Confirmed that the unit is missing the INNER CIRCLE keyword though.
