### ISSUE TITLE
Twin volkite on the chaos achilles landraider shows 3 shots instead of 8

### ISSUE THREAD

**Issue by Theoya** [BSData/wh40k-9e#9582]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Dunamis55** [comment]
Confirmed twin volkite culverin is currently Heavy 3, but should be Heavy 8, in Chaos - Chaos Space Marines v161.
