### ISSUE TITLE
Grey Knights - Multiple profile abilities are listed as Rules instead of Abilities

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#9584]
**File/Catalogue:** Imperium - Grey Knights v81

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 
The following abilities are currently flagged as profile Rules, but should be considered profile Abilities:
1. Bane of Evil
1. Blessings of the Omnissiah
1. Chapter Master
1. Crash and Burn
1. Crux Terminatus
1. Explodes
1. Explodes (D6)
1. Force Shielding
1. Force Shielding and Iron Halo
1. Frag Assault Launchers
1. Heroic Sacrifice
1. Infernium Halo-launcher
1. Interceptor
1. Iron Halo
1. Master Swordsman
1. Mindlock
1. Narthecium
1. Personal Teleporters
1. Psychic Hood
1. Psychic Locus
1. Psyk-out Assault Launchers
1. Purifying Flame
1. Rites of Battle
1. Rosarius
1. Sacred Banner
1. Spiritual Leaders
1. Strafing Run
1. The Perfect Warrior
1. Transport (10)
1. Transport (12)
1. Transport (16)
1. Unyielding Ancient
1. Warp Emergence

**Comment by tekton** [comment]
Closing this for now not because it won't get done, but because I want to come back to it when the new codex drops.
