### ISSUE TITLE
Imperium - Dark Angels - Relic Terminators missing Inner Circle ability

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9587]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Relic Terminators should have the Inner Circle ability.

Also, the Ravenwing apothecary is shown as having the infantry keyword in the app.

**Comment by FarseerVeraenthis** [comment]
Ravenwing Apothecary does not have the infantry keyword in the published rules in Codex Supplement: Dark Angels.
