### ISSUE TITLE
Chaos - Chaos Knights: Dreadblades shouldn't belong to Houses

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9588]
**File:** Chaos - Chaos Knights.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** When you select Dreadblade option cks lose their house hold tradition by rules, this situation is not shown as they still keep it

**Comment by Mad-Spy** [comment]
Removed specific Household keywords, but they do still get the top-level Household keywords and abilities. They just don't get Bonds.
