### ISSUE TITLE
Orks: Can add more then 30 boys to a unit

### ISSUE THREAD

**Issue by tron-solo** [BSData/wh40k-9e#9591]
**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** Yes/No

**Description:** You are able to add more than 30 boys to a Orks boys unit, where 30 should be the maximum.

**Comment by Technoblazed** [comment]
The app throws an error when you add more than 30, there's no way to restrict the upper limit of the input box with the current way the app works with units that have multiple loadout options.
