### ISSUE TITLE
Bug Report! Chapter Selection NOT AVAILABLE for Black Templars

### ISSUE THREAD

**Issue by Lord-Argieus** [BSData/wh40k-9e#9594]
**File/Catalogue:** Imperium- Adeptus Astartes - Black Templars

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Description:** In comparison to all others like Salamanders, Blood Angels, there is no option for the "Chapter Selection" in the Black Templars Segment.

Here you can see it is not added:

![Capture](https://user-images.githubusercontent.com/80419273/111309954-c4b15000-865c-11eb-9048-f8d7b696da9e.JPG)

Here for Blood Angels for example you can see it is:

![Capture 2](https://user-images.githubusercontent.com/80419273/111310042-e4e10f00-865c-11eb-87ef-d198e286f45f.JPG)

Thanks!

**Comment by alphalas** [comment]
It’s because black Templars are not a first founding chapter, so if you take black Templars, you can’t do anything special with them.

**Comment by Lord-Argieus** [comment]
But shouldnt I still be able to play Minotaurs with the Black Templar Tactics?

**Comment by Lord-Argieus** [comment]
> It’s because black Templars are not a first founding chapter, so if you take black Templars, you can’t do anything special with them.

But shouldnt I still be able to play Minotaurs with the Black Templar Tactics?

**Comment by Lord-Argieus** [comment]
That way I can add HQ's like Hecaton etc.

**Comment by DrTobogganMD** [comment]
@Lord-Argieus 
![image](https://user-images.githubusercontent.com/16939161/111311960-cd8a2d80-862c-11eb-9ca9-94d09b7d2e78.png)

Minotaurs are allowed to choose a custom tactic that's true. But Inheritors of the Primarch specifically list which "Founding" chapter tactics are allowed to be taken. Black Templars is not on that list.

**Comment by alphalas** [comment]
It's the same reason you can't be deathwatch, FT, or CF and minotaurs at the same time￼.
