### ISSUE TITLE
Imperium - Grey Knights: Grey Knights weapons using old profiles

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9595]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** Multimelta options for all land raider variants are all still using the old profile. Should be updated to Heavy 2 and have a damage profile of D6+2 when in half range.

**Comment by Mad-Spy** [comment]
A number of weapons are using local profiles that should probably link to the SM lib versions
Hurricane bolter
Multi-melta
Twin assault cannon
Twin heavy bolter
Twin lascannon

**Comment by tekton** [comment]
i'll look at it with other things this weekend

**Comment by tekton** [comment]
Half done- now that I’m home should be able to finish

**Comment by tekton** [comment]
due to some significant changes made while i was trying to work on some QoL stuff for linking ahead of the new codex, I halted those to redo them when the times comes. Thanks data editor...

So instead just fixed the main one while I cry over wasted bits
