### ISSUE TITLE
Grukk Face Rippa(Orks) should be able to get the Stratagem: Da Biggest Boss

### ISSUE THREAD

**Issue by LestatBCN** [BSData/wh40k-9e#9596]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by LestatBCN** [comment]
Is not done

**Comment by Technoblazed** [comment]
Update your data.

![Image](https://i.tech-no.me/2021/03/24/210324070355.png)

**Comment by LestatBCN** [comment]
I've done it this morning but mine is 108, is there any kind of issue with servers?

**Comment by Technoblazed** [comment]
Servers are fine at the minute, orks are on v111 now.

**Comment by LestatBCN** [comment]
Hi again and thanks for your kindness, I've found my error. All seems fine now.

**Comment by LestatBCN** [comment]
I've got a general question. is it planned to add the crusade mode? Where should I ask it? Thanks again.
