### ISSUE TITLE
Bug Report Imperium - Dark Angels

### ISSUE THREAD

**Issue by McChew** [BSData/wh40k-9e#96]
**File/Catalogue:** Dark Angels

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Description:** 
Devastator Squad missing stats, abilities, cherub. Boltgun not being replaced when choosing a heavy weapon.
Assault Squad sergeant should be able to take an eviscerator or 2 melee weapons.
Assault squad eviscerators and special weapons have collective tag which duplicates these models into other assault squad units.
Deathwing knights: Knight master is missing storm shield
Missing Deathwing Champion.

**Comment by muttoneer** [comment]
There's also an issue with deathwing Terminator squads. If you choose cyclone missile launchers, it's priced so that you pay for a storm bolter twice over.
