### ISSUE TITLE
Astra Militarum: Lightning Strike Fighter is missing

### ISSUE THREAD

**Issue by HaradosTheLock** [BSData/wh40k-9e#9606]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/Android

**Dropbox:** No

**Description:** Detailed issue description. Lightning Strike Fighter is missing from the Flyers selection. Was available last update

**Comment by Mad-Spy** [comment]
There is no longer a "Lightning Strike Fighter" datasheet since the IA Compendium was released.
