### ISSUE TITLE
Imperium - Astra Telepathica, Sisters of Silence Excluded

### ISSUE THREAD

**Issue by Naturalnuke** [BSData/wh40k-9e#9607]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS

**Dropbox:** No

**Description:**
Sisters of Silence units possess the Astra Telepathica faction keyword and should be included with the Astra Telepathica Faction.

**Comment by alphalas** [comment]
No, because the AAT file is a holdover from the index where AAT and SoS were separated.

**Comment by alphalas** [comment]
They are separate factions even though they have the same keywords.

**Comment by Naturalnuke** [comment]
The sisters of silence are explicitly the militant arm of the astra telepathica, although the distinction is made if you want to take a detachment of all faction keyword ‘Astra Telepathica’ you can include sisters of silence models

**Comment by alphalas** [comment]
If they were intended to be taken together in a detachment, they would have been in the same force strict according to GW. Sister of Silence are considered part of Custodes by faction, not AAT. If sisters were meant to be run as a part of AAT, they would have not needed the headless detachment that they were given.￼Complain at GW, they are not being combined.

**Comment by alphalas** [comment]
If you wish to discuss this further, discuss it on the discord.￼
