### ISSUE TITLE
Imperium - Custodes , Vanguard Detachment Error

### ISSUE THREAD

**Issue by SoulStarzzz** [BSData/wh40k-9e#9608]
**Platform:** Windows
**Description:** Vanguard detachment is giving a error when I only have one HQ selected. Says I need a minimum of 2 when I actually need 1-2.

**Comment by Technoblazed** [comment]
Can’t replicate this at all, please provide screenshots of the error, list or a .ros file

**Comment by Technoblazed** [comment]
Closing due to no response and unable to reproduce.
