### ISSUE TITLE
Imperium - Astra Militarum: Tank sponson weapon naming is unclear

### ISSUE THREAD

**Issue by Citronnade** [BSData/wh40k-9e#9610]
**File/Catalogue:**  Imperium - Astra Militarum (Overall v179/9.1.20)

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** When AM tanks take sponson weapons, they always take a pair of weapons (e.g. "This model may take two heavy bolters, two heavy flamers, two multi-meltas or two plasma cannons.").  In Battlescribe, this is displayed by pluralizing the name of the sponson weapons (e.g. "Heavy bolters", "Heavy flamers", and so on).  I've seen several new players get confused by this nomenclature over whether the resulting tank has one or two copies of its sponson weapons.

I propose renaming the entry to something like "2x Heavy bolters" or "Two Heavy bolters". The latter matches how paired sponsons are shown in the Space Marines data.

**Comment by Dunamis55** [comment]
As a bonus request, if the sponson weapons could be adjusted to being a grouped entry, it'd also assist with readability and BS2TTS compatibility.

**Comment by alphalas** [comment]
Now you're just being greedy @Dunamis55 :p
