### ISSUE TITLE
Renegades & Heretics - Several wargear options have incorrect points costs + misc issues

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#9611]
**File/Catalogue:** Chaos - Renegades & Heretics [LEGENDS] v56

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [x] Several units’ power axe currently costs 0 points, but should be 5 points:
1. Renegade Commander
1. Renegade Militia Squad > Renegade Militia Champion
1. Renegade Mutant Rabble > Mutant Champion
1. Renegade Disciple Squad > Disciple Champion
1. Renegade Enforcer
1. Renegade Marauder Squad > Marauder Chief
- [x] Several units’ power maul currently costs 0 points, but should be 5 points:
1. Renegade Commander
1. Renegade Militia Squad > Renegade Militia Champion
1. Renegade Mutant Rabble > Mutant Champion
1. Renegade Disciple Squad > Disciple Champion
1. Renegade Enforcer
1. Renegade Marauder Squad > Marauder Chief
- [x] Several units’ power sword currently costs 0 points, but should be 5 points:
1. Renegade Commander
1. Renegade Militia Squad > Renegade Militia Champion
1. Renegade Mutant Rabble > Mutant Champion
1. Renegade Disciple Squad > Disciple Champion
1. Renegade Enforcer
1. Renegade Marauder Squad > Marauder Chief
- [x] Renegade Mutant Rabble > Mutant Champion is unable to exchange their laspistol for a shotgun
- [x] Renegade Militia Squad > Renegade Militia w/ Chaos Sigil can be taken multiple times, but only 1 of these model should be able to be taken
- [x] Renegade Militia Squad > Renegade Militia w/ Vox-caster can be taken multiple times, but only 1 of these model should be able to be taken
- [x] Renegade Command Squad > Disciple w/ Banner can be taken multiple times, but only 1 of these model should be able to be taken
- [x] Renegade Command Squad > Disciple w/ Vox-caster can be taken multiple times, but only 1 of these model should be able to be taken
- [x] Renegade Cultists > Renegade Cultist w/ special weapon’s flamer currently costs 0 points, but should cost 5 points
- [x] Renegade Cultists > Renegade Cultist w/ special weapon’s heavy stubber currently costs 0 points, but should cost 5 points

**Comment by Mad-Spy** [comment]
- [x] Mutant Champion's Stub gun has incorrect profile
