### ISSUE TITLE
Imperium - Imperial Knights: Cadmus WLT missing from list

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9633]
**File:** Imperium - Imperial Knights.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The cadmus' warlord trait "Veteran of Gryphonne IV" is missing.

I created the following:
1) Imperial knight super heavy detachment (v73)
2) Battle Size = 3. Strike Force
3) Household Choice = Questor Imperialis, House Cadmus
4) Lord of war selection = Knight Gallant, Knight Gallant, Knight Gallant
5) Knight Gallant #1 = Character (Knight Lance) -> Warlord -> Warlord Traits:

The only Warlord traits available are:
Revered Knight
Strike and Shield
Tireless Duty
Blessed by the Sacristans
Cunning Commander
Fearsome Reputation
Ion Bulwark
Knight Seneschal
Landstrider

**Comment by Mad-Spy** [comment]
It exists in the data, but is not linked into the WLTs SSEG.
