### ISSUE TITLE
Erroor in the file Warhammer 40000 v9.1.20 Blood angel. 

### ISSUE THREAD

**Issue by emprorium** [BSData/wh40k-9e#9634]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

Hello, 

when i choose blodd angel to builod a list, the named HQ are absent 

Please, can you check and resolved 

Thank you

**Comment by alphalas** [comment]
Pick Blood Angels in the chapter selector.
