### ISSUE TITLE
Inquisitors are not Agents of the Imperium

### ISSUE THREAD

**Issue by Hoagie68** [BSData/wh40k-9e#9639]
**File/Catalogue:*40k, Adepta Sororitas* 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Inquisitors are a"Authority of the Inquisition" Selection... not a "Agent of the Imperium" selection?  hence an Inquisitor AND an Assassin should be allowed in a Dettachment

**Comment by Mad-Spy** [comment]
The rule is that you cannot have more than one AGENT OF THE IMPERIUM in your army. That is a keyword. Both Assassins and Inquisitors have that keyword. Thus you cannot have more than one of them in your detachment.

As per p35 of Psychic Awakening - Pariah.
