### ISSUE TITLE
Inquisitors in any Detachment

### ISSUE THREAD

**Issue by Hoagie68** [BSData/wh40k-9e#9640]
**File/Catalogue:* 40k, Sororitas* 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:**No

**Description:** Shouldnt the Rule "Authority of the Inquisition" allow an Inquisitor to be chosen in any type of Dettachment?

Because the Auxilary det. seems to have no options for an Inquisitor.

f your army does not include any INQUISITION detachments, one INQUISITOR unit can be included in **any** other detachment without taking up a slot so long as every unit in your army (with the exception of those that are UNALIGNED) has the IMPERIUM keyword (and does not have the FALLEN keyword). That INQUISITOR unit does not prevent other units in your army benefiting from Detachment abilities (e.g. Chapter Tactics), and does not prevent abilities that require every model in your army to have that ability (e.g Combat Doctrines, Canticles of the Omnissiah). In a matched play game, that INQUISITOR unit is ignored for the purposes of the Battle Brothers rule (although all units in your army must still have the IMPERIUM faction keyword).

**Comment by Dunamis55** [comment]
Patrol, Battalion, and Brigade Detachments only:
![image](https://user-images.githubusercontent.com/36267768/112390098-aa771200-8ced-11eb-9354-865296a5a041.png)

**Comment by Mad-Spy** [comment]
I believe you're reading out of date rules. The current Inquisition rules come from Psychic Awakening - Pariah, as I mentioned on your previous issue.

**Comment by alphalas** [comment]
Authority of the Inquisition was superseded by Agents of the Imperium.
