### ISSUE TITLE
Thousand Sons cannnot select HQ units from Supreme Command Detachment

### ISSUE THREAD

**Issue by srecio** [BSData/wh40k-9e#9644]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Valorcalls** [comment]
The only unit in the Thousand sons roster eligible for the Supreme Command detachment is Magnus, who is a lord of war.

**Comment by srecio** [comment]
> The only unit in the Thousand sons roster eligible for the Supreme Command detachment is Magnus, who is a lord of war.

Oh, Thanks, I didn't know that! Rules changed in 9th ed for that
