### ISSUE TITLE
Exorcist relics missing after index release

### ISSUE THREAD

**Issue by J3nbuu** [BSData/wh40k-9e#9646]
**File/Catalogue:** Imperium - adeptus Astartes - Imperial Fists v37

**BattleScribe version:** 2.03.21

**Platform:** Windows/Android/

**Dropbox:** Yes

**Description:** When creating a exorcists battle force, after selecting a none named character or vehicle to be the war lord, no options for exorcist  relics appear.

When using relics of the chapter stratagem and selecting other non named characters no options for relics are provided
![exorcists](https://user-images.githubusercontent.com/75937880/112767781-84fd4780-9010-11eb-8d1b-e1b4bf2936b7.PNG)

**Comment by acebaur** [comment]
Yes because I am reworking the chapter selector so the data exists its just hidden. Will be fixed when the selector is updated

**Comment by J3nbuu** [comment]
> Yes because I am reworking the chapter selector so the data exists its just hidden. Will be fixed when the selector is updated

Thanks :)
much appreciated
