### ISSUE TITLE
Imperium - Inquisition - Strategem Arbiter of the Emperor's Will Does not Properly Affect Inquistors 

### ISSUE THREAD

**Issue by GinFizzz** [BSData/wh40k-9e#9647]
**File/Catalogue:** Warhammer 40,000 v9.1.21

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** All Inquisitors currently do not properly utilize **Stratagem: Arbiter of the Emperor's Will**, which should allow the selection of one new Inquisitor Warlord trait. Additionally, if the model is not a named Inquisitor, meaning the Ordo Malleus Inquisitor in Terminator Armour and the standard Inquisitor, it should also be able to select an Inquisitor artifact as well.

![image](https://user-images.githubusercontent.com/47032978/112769685-51aac080-8ff0-11eb-9083-b77b56bebe56.png)

**Comment by GinFizzz** [comment]
Once selected, no new warlord traits are generated.
This was attempted a Sisters of Battle Battalion with Bloody Rose Conviction. File is attached below.
[New Roster.zip](https://github.com/BSData/wh40k/files/6218183/New.Roster.zip)

**Comment by Mad-Spy** [comment]
All appears to be working correctly in the current data release.

Named characters do not get to _select_ a  Trait; they must take their fixed one (which can only be Inspiring Leader for FW models) and this _is_ appearing on the output when Arbiter is selected for them.

Both the standard Inquisitor and the Terminator _are_ given access to the Relics list when Arbiter is selected.

**Comment by GinFizzz** [comment]
@Mad-Spy Where does it say that FW units may only select Inspiring Leader?

The rules state that if the selected model is not a named character, it can select an artifact, but all Inquisitors get to select a trait.
![image](https://user-images.githubusercontent.com/47032978/113369663-d28af480-932f-11eb-916a-6485b8ab2500.png)

**Comment by alphalas** [comment]
![018E3BD0-0A1D-43FB-BBAE-0F5DD1212072](https://user-images.githubusercontent.com/15703066/113373583-2a7a2900-9339-11eb-9fb7-6ef27263a0c1.png)
@GinFizzz check the FW Index.
