### ISSUE TITLE
Suppressor Squad Smoke Launcher ability

### ISSUE THREAD

**Issue by ColeNOXyd2nd** [BSData/wh40k-9e#9649]
**File/Catalogue:** Imperium - Space Marines.cat

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Suppressor Squad still shows the  Smoke Launcher ability, this was replaced by a Keyword in 9th.

**Comment by Technoblazed** [comment]
This definitely isn't there anymore, even on master. Try updating your data.
