### ISSUE TITLE
Dark Angels PL errors

### ISSUE THREAD

**Issue by Rick031973** [BSData/wh40k-9e#9651]
**File/Catalogue:** imperium - adaptus Astartes - dark angels

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:**
Wrong PL value (must have PL value of space Marine codex, if not in the supplement codex: dark angels)

Whirlwind 5 PL should be 7 PL
Predators 9 PL should be 8 PL
Hunter 5 PL should be 6 PL
Land Raider 19 PL should be 15 PL
Land Raider Crusader 16 PL should be 15 PL
Land Raider Redeemer 18 PL should be 15 PL

**Comment by Mad-Spy** [comment]
@Thairne, it looks like there are costs on some of the RSE links.

**Comment by Rick031973** [comment]
Wonder why this ticket is close? No cost fixed in the 5th April update

**Comment by Mad-Spy** [comment]
Because it was closed this morning? The 6th? It will be in the next release.

**Comment by Rick031973** [comment]
Great 😁, thanks
