### ISSUE TITLE
40K -Imperium - Space Wolves - Arjac Rockfist not appearing

### ISSUE THREAD

**Issue by Da-claw** [BSData/wh40k-9e#9654]
**File/Catalogue:** Warhammer 40,000 9th Edition v180
Imperium - Space Wolves v187

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Description:** When using the Chapter Selection Space Wolves which then gives all the Space Wolf special characters as choices, there is no Arjac Rockfist as an option. He was in earlier versions.

**Comment by Valorcalls** [comment]
He is a LT, and found under the entry for LTs.
