### ISSUE TITLE
Imperium - Space Wolves: Can't find named characters

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9655]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I want start off by saying BattleScribe is fantastic. Here’s the problem, first of all I can’t access any of the Space Wolves specific heroes(Ragnar, Logan Grimnar, etc) also the app is not allowing me to add more than one detachment per list.

**Comment by Mad-Spy** [comment]
1. Make sure you have selected Space Wolves in the Chapter Selection option under Configuration.
2. Either 
a. add them when you first create a list by tapping the big orange + in the  bottom right on the "Create Roster" screen.
b. add them after creating a list by opening the menu and choosing Edit Forces, switch to the Forces tab, and then do a.
