### ISSUE TITLE
Imperium - Imperial Knights: Bringer of Justive validation is incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9660]
**File:** Imperium - Imperial Knights.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The newly improvemented relic the bringer of Justice is targeting valiant and castellan frames instead of paladin, Warden,Errant,Gallant,Styrix , Magaera that have reaper chainswords

**Comment by DrTobogganMD** [comment]
Not sure what you're talking about. It is properly validating to models that have a Reaper Chainsword.
