### ISSUE TITLE
Imperium - Astra Militarum: Medusa carriage battery incorrect points

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9662]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Medusa Carriage Battery has incorrect points and stats:  Battlescribe is 110 points, correct points is 120.  There are no "standard shells" anymore, just one kind of gun. 
Correct stats for Medusa are as follows:

WEAPON                        RANGE  TYPE        S    AP  D    ABILITIES
Medusa siege cannon	36"         Heavy D6  10  -3    D6  Blast. This weapon can target units that are not visible to the bearer.

Points Source:   Warhammer Community FAQ
https://www.warhammer-community.com/wp-content/uploads/2020/08/gxruRl769G2olA3v.pdf

Rules Source:  Wahpedia.ru
http://wahapedia.ru/wh40k9ed/factions/astra-militarum/Medusa-Carriage-Battery

Thanks, love BattleScribe! Its my primary way to make a list.

**Comment by Mad-Spy** [comment]
I think you need to update your data. The cost and weapon profile are correct in the current data release.
