### ISSUE TITLE
Aeldari - Drukhari - Not ready just yet.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9663]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Drukari codex isn’t updated.  Has exactly the same content as prior to codex drop.  No updated stats for units, equipment, rules for Kabals, Covens or Cults.

**Comment by Valorcalls** [comment]
This would be because it hasn't been finished yet.

**Comment by FarseerVeraenthis** [comment]
Please check #9656 - QA is in progress.
