### ISSUE TITLE
Imperium - Astra Militarum: Power axe, lance, and maul costs are incorrect

### ISSUE THREAD

**Issue by Citronnade** [BSData/wh40k-9e#9664]
**File/Catalogue:**  Imperium - Astra Militarum

**BattleScribe version:** 2.03.23

**Platform:** Android

**Dropbox:** Yes

**Description:** Power axes, lances, and mauls are currently free in BattleScribe.  AM legends has their points costs at 5 points for a power axe, 4 points for a power lance, and 4 points for a power maul.

**Comment by Technoblazed** [comment]
For which units?

**Comment by Citronnade** [comment]
I've checked:
* Company Commander
* Lord Commissar
* Tempestor Prime
* Infantry Squad Sergeant
* Veterans Sergeant
* Platoon Commander
* Commissar

for power maul + power axe.

Rough Rider Sergeant for power lance (and axe and maul).
