### ISSUE TITLE
Ad Mech - Book of Rust QA Pass

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#9665]
**File/Catalogue:** Imperium - Adeptus Mechanicus v126

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [x] Several units do not gain the Extremis Sentinel Protocols rule when Army of Renown – Mechanicus Defence Cohort is taken:
1. Kataphron Breachers
1. Kataphron Destroyers
1. Servitors
1. Kastelan Robots
- [x] Cacophonous Leadership (Aura)	has a typo and the first sentence should read as: “While a friendly MECHANICUS DEFENCE COHORT unit is within 6" of this WARLORD, that unit has the Objective Secured ability.”
- [x] Codex Supplement: Metalica warlord traits are unable to be taken unless Army of Renown – Mechanicus Defence Cohort is also taken
- [x] Omni-steriliser relic can currently be taken on all characters, but should only be able to be taken on a Tech-Priest Dominus equipped with an eradication ray.
- [x] Delta Pistol relic can currently be taken on all characters, but should only be able to be taken on a Cybernetica Datasmith.

**Comment by Thairne** [comment]
The Extremiss Sentinel Protocols rule was implemented as a Force rule - it is a lather longish text and (almost) every unit is affected b it anyway.
