### ISSUE TITLE
Imperial Knights - Book of Rust QA Pass

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#9666]
**File/Catalogue:** Imperium - Imperial Knights v76

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [x] HOUSE RAVEN units are unable to use the Knight of the Iron Cog stratagem when a Metalica Adeptus Mechanicus detachment is in the roster
- [x] Bringer of Justice relic can be taken by characters who are not equipped with a reaper chainsword
- [x] Bringer of Justice relic is able to be taken by characters in an army that isn't a Freeblade Lance Army of Renown
- [x] Taking Character (Favoured Knight) on a unit shows two extra tables of relics to choose from, instead of one extra table
- [x] Blessed by Metalica warlord trait is missing text and the final sentence should read as: “This WARLORD can be repaired by METALICA TECH-PRIEST units as if it were a METALICA VECHICLE model.”
- [x] Relentless Wrath relic has incorrect Abilities text and should read as: “Blast”
- [x] Fury of the Keep relic has incorrect Abilities text and should read as: “Blast”

**Comment by williamcaw** [comment]
valiant and castellan are some how able to take the bringer of Justice non character via honor of the household
