### ISSUE TITLE
Death Guard - Book of Rust QA Pass

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#9667]
**File/Catalogue:** Chaos - Death Guard v125

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 
- [x] ~~VEHICLE units are still able to be added to a roster when Terminus Est Assault Force is taken.~~ It generates a Roster level error for selection of the Army of Renown. I'm not going through and hiding every vehicle.
- [x] ~~Units in a Terminus Est Assault Force army do not gain the Outbreak Assault rule~~ The rule appears on the selection instead (as a reference to the book). Adding a conditional to every unit would impact performance.
- [x] Harbinger of Death (Aura) warlord trait has a typo and the last sentence should read as: “In addition, while one or more enemy models are in range of this aura, add 1 to this WARLORD's Attacks characteristic.”
- [x] Accelerated Entropy psychic power has typos and should read as: “Witchfire: If manifested, select one enemy model within 12" of and visible to this PSYKER. Both players then roll one D6 and add their model's Toughness characteristic. If your result is higher than your opponent's, that enemy model suffers 3 mortal wounds. if your result is double your opponent's, or more than double your opponent's, that model's unit suffers D3+3 mortal wounds.”
- [x] Rotgrip relic currently has a S characteristic of 0.30, but should be x3

**Comment by Mad-Spy** [comment]
@Dunamis55 if you could specify exactly where typos occur when reporting, it would make life a lot easier. 

i.e. Accelerated Entropy has a typo "while one or **mode** enemy models"
