### ISSUE TITLE
Imperium - Space Marine: Intercessor Grenade Launcher

### ISSUE THREAD

**Issue by GinSoakedBoy** [BSData/wh40k-9e#9669]
File/Catalogue: Imperium - Space Marines.cat

BattleScribe version: 2.03.21.166

Platform: Windows

**Dropbox:** No

**Description:** The Astartes grenade launcher wargear option is listed as a rule and not attached to a model. Also, the labelling for thrown grenades is the same as the grenade launcher. The range is obviously very different between the two but it does make it a little less clear. This also causes issues when importing a list into TTS or a tool for printing such as Buttscribe/Prettyscribe.

![image](https://user-images.githubusercontent.com/13789412/113424838-d3a73a80-939e-11eb-952b-224779722552.png)

The Eradicator squad handles the addition of a Multi-Melta as a separate model allowing you to easily see what weapon each model within a squad is carrying:

![image](https://user-images.githubusercontent.com/13789412/113425001-19640300-939f-11eb-97da-30aae55345c9.png)

**Comment by acebaur** [comment]
It's on an upgrade instead of counting as a model because anyone can take it. I will however make it more clear on the weapon profile.

**Comment by GinSoakedBoy** [comment]
> It's on an upgrade instead of counting as a model because anyone can take it. I will however make it more clear on the weapon profile.

With WYSIWYG only the one model holding the grenade launcher can take the upgrade. Will updating the weapon profile also fix importing to TTS and printing tools like Buttscribe/Prettyscribe?
