### ISSUE TITLE
Drukhari - Codex & Book of Rust QA Pass

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#9671]
**File/Catalogue:** Aeldari - Drukhari v109

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [x] Raiding Forces can be taken in non-Patrol detachments
- [x] ~Archon’s entire Aura Ability table should be hidden when not in a Realspace Raid detachment~ this is not possible due to the way BS works.
- [x] If a detachment is made a Realspace Raid detachment, the Restricted version of Cult of Strife should be unavailable to be taken
- [x] Twisted Animator warlord trait doesn’t have capitalised keywords and the first sentence should read as: “In your Command phase, you can select one friendly < **HAEMONCULUS COVEN** > WRACK unit within 3" of this WARLORD.”
- [x] Haemoxytes’ Haemoxytes ability is missing text: “Improve this unit's invulnerable save by 1 (to a maximum of 4+).”
- [x] Labyrinthine Cunning warlord trait has a typo and should read as: “… one D6 **for** each …”
- [x] Kabal of the Flayed Skull: Slay From The Skies ability has a typo and should read as: “… that can FLY **makes** a ranged attack …”
- [x] The Obsidian Veil relic has a typo and should read as: “… invulnerable save.”
- [x] Dark Mirth obsession has missing text and should read as: “Units with this Obsession have the following ability:
Dark Mirth (Aura): While it is within 12" of this unit, each time an enemy unit is selected to make a Normal Move, Advance, Fall Back or is selected to charge, roll one D6: on a 5+, that enemy unit suffers 1 mortal wound.”
- [x] Torturous Efficiency obsession has a typo and should read as: “Each time a model with this **Obsession** …”
- [x] Soul Bound obsession has a typo and should read as: “… one D6: on a **5+**, that …”
- [x] Traitor's Embrace relic has a typo and should read as: “**If** the bearer is destroyed …”
- [x] The Blood Glaive relic is unable to be taken when a Succubus takes the Blast Pistol & Archite Glaive or the Splinter Pistol & Archite Glaive wargear options
- [x] Agile Hunters obsession has (All Consuming) in its profile name, but other obsessions that are All Consuming do not have this mentioned in their profile name
- [x] Berserk Fugue obsession has a typo and should read as: “… an unmodified **hit** roll of 6 …”
- [x] Precise Killers obsession has a typo and should read as: “… instead **of 6**.”
- [x] The Vexator Mask relic has a typo and should read as: “… fire **Overwatch** at …”
- [x] The Dark Creed: Distillers of Fear obsession has a typo and should read as: “… Aura **of Terror** (Aura): …”
- [x] The Coven of Twelve: Butchers of Flesh obsession has a typo and should read as: “… Obsession **makes** an attack …”
- [x] No error is thrown when Stratagem: Alliance of Agony WLT and Stratagem: Tolerated Ambition are both taken on either a Succubus or Haemonculus.
- [x] Stratagem: Prizes from the Dark City has a hard limit of 7 extra relics, but should have a maximum hard limit of 3 extra relics.
- [x] Master Regenerist warlord trait has a typo and should read as: … WARLORD **uses** their Fleshcraft …”
- [x] Huskblade currently has a S characteristic of +1, but should be User
- [x] Huskblade currently has a D characteristic of D3, but should be 2
- [x] Haemonculus currently costs 5 PL, but should cost 4 PL
- [x] Sustained by Dark Science has a typo and should read as: “… choose to roll one **D6** at …”
- [x] Several units have a splinter rifle listed as a heavy weapon:
1. Kabalite Warriors > Kabalite Warrior w/ Special Weapon
1. Kabalite Trueborn > Kabalite Trueborn w/ Special Weapon
I disagree that this is strictly a bug, but since you and MadSpy have moaned about it I've changed it.
- [x] Several units have a splinter rifle listed as a special weapon: 
1. Kabalite Warriors > Kabalite Warrior w/ Heavy Weapon
1. Kabalite Trueborn > Kabalite Trueborn w/ Heavy Weapon
1. Reavers > Reaver with special weapon (up to 1 for 3 models)
I disagree that this is strictly a bug, but since you and MadSpy have moaned about it I've changed it.
- [x] Kabalite Trueborn > Sybarite has a non-unique profile name, causing it to overwrite the profile of Kabalite Warriors > Sybarite when Profile Summary is enabled in the View Roster window.
- [x] Shredder currently has a Range characteristic of 12”, but should be 18”
- [x] ~Kabalite Trueborn who have 6+ models currently cost 7 PL, but should cost 8 PL~ This is incorrect interpretation of the increment for Trueborn. They are +1PL for every 5 models. Therefore, until you have a squad of 10 you do not need to aply the second +1PL.
- [x] Wyches > Wych currently has an Attacks characteristic of 2, but should be 3
- [x] Wyches > Hekatrix currently has an Attacks characteristic of 3, but should be 4
- [x] Hekatrix Bloodbrides > Hekatrix has a non-unique profile name, causing it to overwrite the profile of Wyches > Hekatrix when Profile Summary is enabled in the View Roster window.
- [x] Wracks can only currently take a maximum of 10 models in a unit, but should be able to take up to 20 models
- [x] Several units don’t currently have the Blade Artists rule, but should:
1. Wracks
1. Haemoxytes
- [x] ~Haemoxytes who have 6+ models currently cost 7 PL, but should cost 8 PL~ Ref. Trueborn, above.
- [x] Haemoxytes > Acothyst has a non-unique profile name, causing it to overwrite the profile of Wracks > Acothyst when Profile Summary is enabled in the View Roster window
- [x] Several units are missing the Power From Pain rule:
1. Court of the Archon > Lhamean
1. Court of the Archon > Ur-Ghul
- [x] Court of the Archon > Lhamean currently costs 1 PL each, but should be 0 PL each
- [x] Court of the Archon > Medusae currently costs 1 PL each, but should be 0 PL each
- [x] Court of the Archon > Sslyth currently costs 1 PL each, but should be 0 PL each
- [x] Court of the Archon > Ur-Ghul currently costs 1 PL each, but should be 0 PL each
- [x] Court of the Archon should cost 5/10/15/20 when it has 4/5-8/9-12/13-16 models
- [x] Court of the Archon’s Cold-blooded Bodyguard ability has a typo and should read as: “… within 3" of this **unit**, enemy …”
- [x] Beasts of the Arena ability has a typo and should read as: “… you **can** only include a maximum …”
- [x] Khymerae state in the options pane that they have a model limit of “1 - 6 Khymerae”, but it should read as “2 - 6 Khymerae”
- [x] Reavers > Reaver can be taken up to a hard limit of 12 models, but it should be a hard limit of 11 models
- [x] Cronos’ Explodes ability currently has a range of 6”, but should be 3”
- [x] Venom’s Flickerfield ability has a typo and should read as: “… invulnerable save against **ranged** attacks.”
- [x] Razorwing missiles - Monoscythe missile is incorrectly named as “Monoscythe missile”
- [x] Razorwing missiles - Necrotoxin missile is incorrectly named as “Necrotoxin missile”
- [x] Razorwing missiles - Shatterfield missile is incorrectly named as “Shatterfield missile”
- [x] Voidraven missiles - Shatterfield missile have incorrect abilities text and should read as: “Blast”
- [x] Voidraven Bomber is missing its Night Shield ability
- [x] ~ Ynnari units should be hidden from the available units if Drazhar, Lelith Hesperax, Urien Rakarth, or Haemonculus units are already taken in a roster ~ Not possible to implement this logic in BS without pulling all named characters into Ynnari Lib, OR copying Ynnari three times into each Space Elf Cat.
- [x] Several units are currently unavailable in a Cult of Strife (Restricted) detachment, but should be:
1. Lelith Hesperax
1. Mandrakes
- [x] Several units are currently available in a Cult of Strife (Restricted) detachment, but shouldn't be:
1. The Visarch
1. The Yncarne
1. Yvraine
- [x] ~Corsair units should only be able to be taken in < KABAL > or Mixed detachments~ not possible due to data structure and BS limitations.
- [x] Raven Strike Fighter [Legends] is incorrectly named “Raven Strike Fighter”
- [x] Raven Strike Fighter [Legends] is still using the 8th edition profile layout
- [x] Raven Strike Fighter [Legends] should have 2 dark lances and splinterstorm cannon equipped by default. In addition, these shouldn’t display as tables in the wargear option pane.
- [x] Competitive Edge warlord trait should be available in a non-restricted Cult of Strife detachment
- [x] Unparalleled Agility warlord trait should be available in a non-restricted Cult of Strife detachment
- [x] Master Executioner warlord trait should be available in a non-restricted Cult of Strife detachment
- [x] Morvaine’s Agoniser relic should be available in a non-restricted Cult of Strife detachment
- [x] Garland of Spite relic should be available in a non-restricted Cult of Strife detachment
- [x] The Glaive Exquisite relic should be available in a non-restricted Cult of Strife detachment
- [x] Dark Lotus Toxin relic should be available in a non-restricted Cult of Strife detachment
- [x] No error is thrown if Stratagem: Hekatrix of the Crucibael is taken over multiple units

**Comment by FarseerVeraenthis** [comment]
Drukhari is released...

... and there was much rejoicing
