### ISSUE TITLE
Imperium - Deathwatch: Company Vets should have access to heavy flamer and be limited to 1 heavy weapon on a model

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9672]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The unit entry for Company Veterans does not allow Heavy Flamer as a Heavy weapon option. The Deathwatch can take the weapon alongside the Blood Angels. Bug is not present in Blood Angels.

**Comment by Mad-Spy** [comment]
In addition, Company Vet heavy weapons are not limited to one per model.
