### ISSUE TITLE
Imperium - Dark Angels - Talon master is missing from selection.

### ISSUE THREAD

**Issue by MrSnickaLoaf** [BSData/wh40k-9e#9673]
**File/Catalogue:** 
 imperium - adaptus Astartes - dark angels
**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux
windows
**Dropbox:** Yes/No
no
**Description:** Detailed issue description.
the Dark Angels talon master is no longer in HQ, I have tried looking with a battalion, vanguard, outrider, the talon master no longer shows up.

**Comment by alphalas** [comment]
Look in the Lieutenants selection.
