### ISSUE TITLE
Age of Sigmar Hedonites missing/incorrect data

### ISSUE THREAD

**Issue by LordJerdan** [BSData/wh40k-9e#9674]
**File/Catalogue:** 
Warhammer: Age of Sigmar v2.2.33

**BattleScribe version:** 
2.03.21

**Platform:** 
Windows

**Dropbox:** 
Yes

**Description:** 
Incorrect values: 
- Seekers "to hit"-value is 3+ (4+ in file) / Source: Hedonites of Slaanesh Battletome 2021; checked for errata and FAQ on 4/3/21

Missing abilities:
- Dreadful Visage´s "Flensing Tongues" / Source: Hedonites of Slaanesh Battletome 2021; checked for errata and FAQ on 4/3/21
(After this model has moved, roll 6 dice for the closest other unit within 6". If more than 1 other unit is equally close, the player that moved this model can choose which unit to roll the 6 dice for. That unit suffers 1 mortal wound for each roll of 4+.)
- The Dread Pageant´s "Blissbarb Bow - Melee" / Source: Errata for Hedonites of Slaanesh Battletome, March 2021

Updated Abilities:
- The Host of Syll`Esske Battle Trait: Deadly Symbiosis / Source: Errata for Hedonites of Slaanesh Battletome, March 2021
(Add 1 to the number of depravity points (instead of command points) you receive in the battleshock phase... etc)

I hope this is helpful... :)

Thank you for your awesome work!

[Official Errata 3_2021.pdf](https://github.com/BSData/wh40k/files/6254395/Official.Errata.3_2021.pdf)
[Warscroll Seekers.pdf](https://github.com/BSData/wh40k/files/6254406/Warscroll.Seekers.pdf)

**Comment by Mad-Spy** [comment]
You've raised this in the 40k repo by mistake.
