### ISSUE TITLE
Aeldari - Drukhari - Stratagem: Tolerated Ambition is missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9679]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Strategems Tolerated Ambition missing from Strategems. Allows a Drukhari Character to be given a Warlord Trait.

**Comment by Valorcalls** [comment]
Please confirm you are on the latest version of the Drukari file (v111), and if possible please post a screenshot of the error

**Comment by FarseerVeraenthis** [comment]
This is selected on the Character itself, it is not selected from unit tree
