### ISSUE TITLE
Aeldari - Drukhari - Urien Rakarth is missing Master Haemonculus Keyword

### ISSUE THREAD

**Issue by Valheru26** [BSData/wh40k-9e#9680]
Updated the new battlescribe Drukhari file.

When coven is selected you can't choose transports for them.

When Urien is selected you can't upgrade wracks to haemoxytes.

**Comment by Technoblazed** [comment]
What version of the file are you using?

**Comment by Valorcalls** [comment]
1 should be fixed in next release (it was found and fixed between the time release was pushed and github picked it up).
2 is the main bug here, and I'm pretty sure it's because urien is lacking the master haemon keyword in BS on the release data

**Comment by FarseerVeraenthis** [comment]
Hahaha! Yeah, I didn't even realise Urien had those keywords... I'll get to it 😄
