### ISSUE TITLE
Drukhari Raider doesn't allow Coven subfaction

### ISSUE THREAD

**Issue by FranklinTemba** [BSData/wh40k-9e#9681]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:** Raiders only allow for selecting Kabal or Wych Cult as the subfaction. Codex also permits Raiders to be a Haemonculus Coven unit.

**Comment by Valorcalls** [comment]
duplicate of #9680 and also should be fixed for next release
