### ISSUE TITLE
Archon Warlord Ability Not Replaced in Realspace

### ISSUE THREAD

**Issue by Eyeball720** [BSData/wh40k-9e#9684]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** The warlord Ability is not replaced it is an option in the app. When it should be replaced.

**Comment by FarseerVeraenthis** [comment]
The codex states "you can" therefore it is optional to choose one or the other.
