### ISSUE TITLE
Aeldari - Drukhari - Reaver PL is not incrementing properly

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9688]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Master succubus selection is empty.

Reaver PL increases to at 4-6 models. Should be 6.

**Comment by FarseerVeraenthis** [comment]
Yup, the Master issue is already updated on the master data, Reaver PL is a new one though.
