### ISSUE TITLE
Bug Report- Drukhari

### ISSUE THREAD

**Issue by ClawzNFangz** [BSData/wh40k-9e#9692]
**Warhammer 40,000 v9.125:** 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:**  Alliance of Agony is taking 1CP to add as a stratagem (good) but taking another CP each time you identify the succubus or homunculus (-2 CP- bad). So a 1CP stratagem is removing 3CP atm.

**Comment by WindstormSCR** [comment]
fixed in v112
duplicate of #9678
