### ISSUE TITLE
Aeldari - Drukhari: Stratagem Hekatrix of the Crucibael should be selectable 

### ISSUE THREAD

**Issue by Lokilicious** [BSData/wh40k-9e#9693]
**File/Catalogue:** Aeldari - Drukhari

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** It should be possible to select the Stratagem "Hekatrix of the Crucibael" in battlescribe and assign a relic to a Hekatrix model.

**Comment by Valorcalls** [comment]
You should currently be able to do this inside the model itself in the required restricted cult of strife detachment.

**Comment by Lokilicious** [comment]
You are right - i did miss that. Can be closed 👍

**Comment by Valorcalls** [comment]
Excellent
