### ISSUE TITLE
Aeldari - Drukhari: Lelith should have MASTER SUCCUBUS keyword

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9694]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Lelith doesn’t seem to be counting as a master Succubus for the purposes of adding Hekatrix Bloodbrides to a detachment.

**Comment by Technoblazed** [comment]
Not just a keyword issue, Lelith will also need the show stealer upgrade adding to her too.

**Comment by FarseerVeraenthis** [comment]
> Not just a keyword issue, Lelith will also need the show stealer upgrade adding to her too.

Named characters cannot be upgraded... So it is just s missing keyword

**Comment by Technoblazed** [comment]
@FarseerVeraenthis the Hekeatrix constaint is only unhiding the unit if there's an instance of the show stealer in the roster.

EDIT: Created new issue for the above: https://github.com/BSData/wh40k/issues/9698

**Comment by Mad-Spy** [comment]
Fixed in next release
