### ISSUE TITLE
Aeldari - Drukhari: Realspace Raiders Archon WL Validation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9702]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** When making real space raiders brigade detachment, if you take more than one archon, roster validation error claims that all archons must be warlord.

**Comment by WindstormSCR** [comment]
Leaving a note for myself
- [ ] move validation to SSE containing WL to allow correct triggering

**Comment by FarseerVeraenthis** [comment]
@WindstormSCR is it valid to have more than one Archon in a Realspace raider detachment...?
I think not, hence why it works as it is...

**Comment by dalamar666** [comment]
> @WindstormSCR is it valid to have more than one Archon in a Realspace raider detachment...?
> I think not, hence why it works as it is...

Technically there is nothing in the rule stopping you from having 2 Archons, just one Archon that must be your warlord and one of each other plus the troops.  Now I'm not putting it past GW to forget that you can fit those requirements into the Brigade when writing these rules.

**Comment by WindstormSCR** [comment]
Actually there is upon further review.
https://puu.sh/HwBbb/ac3d2a39a3.png
The text specifically states "one" while 1+N is always stated as "at least one" as is the case with the troops units in the same paragraph, so the current implementation is correct
