### ISSUE TITLE
Aeldari - Drukhari: Double Splinter Cannon on Talos old stats

### ISSUE THREAD

**Issue by Dreyven** [BSData/wh40k-9e#9705]
File: Drukhari.cat

Version: 2.03.21

The Double Splinter Cannon on Talos is still 0 AP 1 Damage.

**Comment by FarseerVeraenthis** [comment]
![image](https://user-images.githubusercontent.com/23246922/115079748-904ddf80-9ef9-11eb-965d-7806882d6d0c.png)
It looks OK on the Master, as released yesterday it should be OK, please update your data.
