### ISSUE TITLE
Drukhari Reavers points sould be 20 not 10.

### ISSUE THREAD

**Issue by TexasRed1850** [BSData/wh40k-9e#9710]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by FarseerVeraenthis** [comment]
Latest English publication has them at 10.
So they will stay at 10 until FAQ'd

**Comment by TexasRed1850** [comment]
The Codex was released on March 27th. The Munitorum Field which was updated on April 2nd per the Warhammer Community FAQs and errata has them listed at 20pts which means that is the correct points cost.

**Comment by Valorcalls** [comment]
This is False. The MFM FAQ is from Feb 4th, not April 2nd.

**Comment by FarseerVeraenthis** [comment]
> This is False. The MFM FAQ is from Feb 4th, not April 2nd.

#becauseukdates
