### ISSUE TITLE
Drukhari Reavers should be 20pts, not 10pts per model

### ISSUE THREAD

**Issue by TexasRed1850** [BSData/wh40k-9e#9713]
The Codex was released on March 27th. The Munitorum Field Manual was updated on April 2nd. Therefor that is the most recent, and correct point value per official GW FAQ and Errata. Please fix this. Thank you. 

You can look and see for yourself.

https://www.warhammer-community.com/faqs/#warhammer-40000

**Comment by Valorcalls** [comment]
That FAQ is from Feb 4th, not April 2nd.

**Comment by alphalas** [comment]
They use British dating which is dd/mm/yyyy not mm/dd/yyyy
