### ISSUE TITLE
IK Moirax and Relic Issues

### ISSUE THREAD

**Issue by DrTobogganMD** [BSData/wh40k-9e#9720]
I gotta fix the thing. Moirax can't take the thing, and Relics/WTs cant be given if you take the other thing.

**Comment by Technoblazed** [comment]
Yes

**Comment by WindstormSCR** [comment]
Specifically heirloom of the exalted court character can't take WLTs if a qualifying combination of stratagems are taken (2+ extra wlts and heirloom)

and Moirax can't take knight of the cog.

**Comment by DrTobogganMD** [comment]
Discussed with Wind on discord. No issues are present.
