### ISSUE TITLE
THOUSAND SONS demon prince price is wrong

### ISSUE THREAD

**Issue by abelpablo** [BSData/wh40k-9e#9721]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** THOUSAND SONS demon prince price is wrong, it shows 160, should be 150.

**Comment by Valorcalls** [comment]
This is as intended, since its 150+10 for the base wargear.

**Comment by abelpablo** [comment]
Are you sure about that ?
The latest MUNITORUM FIELD MANUAL, says 0 pts for one and 15 for the second one.

![image](https://user-images.githubusercontent.com/5048376/114812969-80ae8980-9d87-11eb-864a-5d376ad2635c.png)

**Comment by Valorcalls** [comment]
The default wargear (what shows in the list) is the first free talon, and the 10p sword.

**Comment by abelpablo** [comment]
ohhh I see, thanks!
