### ISSUE TITLE
Aeldari - Craftworlds - No Phoenix Lords visible

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9724]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 3.25.33

**Platform:** Android

**Dropbox:** No

**Description:** In the Craftworlds, there are no Phoenix Lords at all. This is a major issue since they are some of the most important units in the army.

**Comment by Valorcalls** [comment]
Have you accidentally selected the list to be Ynnari?

**Comment by FarseerVeraenthis** [comment]
![image](https://user-images.githubusercontent.com/23246922/115080157-313c9a80-9efa-11eb-9c92-1ba30aead0ee.png)
They are definitely there.
Note that selecting any of the Ynnari characters will cause them to be hidden.
