### ISSUE TITLE
Death Company Intercessor Weapon Option Bug

### ISSUE THREAD

**Issue by ChristopherBuilderman** [BSData/wh40k-9e#9729]
**File/Catalogue:** Warhammer v182 Blood Angels

**BattleScribe version:** 2.03.

**Platform:** Windows

**Description:** 
Death Company Intercessor with a melee weapon has a really weird options page on the rifle unit options. It doesn't allow you to select a rifle replacement and a melee weapon, and I'm pretty sure they can have both. It should just be the same as the Heavy Bolt Pistol w/ Chainsword options. Also Power Sword is in the options for Rifle replacements for some reason along with Chainsword?

Obviously no one really uses them so this should be fairly low on the list of things to fix, but still an issue.

**Comment by Mad-Spy** [comment]
A power sword _is_ a valid swap for the model's rifle, as per sub-option 2 of option 5 on the datasheet.

![image](https://user-images.githubusercontent.com/29306451/115266470-23705a80-a130-11eb-93f3-c3d475405b0d.png)

What you should also be able to do is both swap the rifle for a pistol _and_ then add a melee weapon, by using sub-option 2 to select a pistol swap, and then sub-option 3.

It's also confusing that the Melee Weapon model is automatically added to the unit, as it's not mandatory to make the swaps and if you just want a rifle unit that's a valid choice.

**Comment by ChristopherBuilderman** [comment]
That looks like an older datasheet. What I'm saying it there is a melee weapon options section, and then a pistol option section, but the power sword alone is in both for some reason. Even on that older datasheet it has the Chainsword also there.

**Comment by DrTobogganMD** [comment]
![image](https://user-images.githubusercontent.com/16939161/115308277-16ec0200-a130-11eb-99df-21d34bc56b12.png)
What @Mad-Spy linked is the most current data from the index. Here it is in a less yellow colouring.

**Comment by DrTobogganMD** [comment]
![image](https://user-images.githubusercontent.com/16939161/115309583-1ce2e280-a132-11eb-957b-154eebc8e719.png)
One of our other maintainers posted the Errata from FAQ for this.

**Comment by ChristopherBuilderman** [comment]
See from that FAQ it looks like you can equip one model with a Chainsword or other melee weapon without replacing the rifle. It's the pistol that replaces the rifle. That's very different wording from what you and @Mad-Spy posted, which I realize now IS actually the 9th edition supplement, but has been updated with that FAQ.

He is right though that it is a bit confusing to add the Melee one immediately. I think making it like a Sergeant would be on another datasheet might be more clear, since that is sort of what they are trying to replace.

**Comment by ChristopherBuilderman** [comment]
Specifically just the normal Intercessor Sergeant. I think it's the exact same system for the wargear. The Heavy Bolt Pistol and Chainsword one can stay the same as that one is totally accurate.

**Comment by Mad-Spy** [comment]
Yes, you can give a rifle-armed model a melee weapon, in both versions of the data sheet (via sub-bullet 3 in the first version, and sub-bullet 2 in the updated version).

It is effectively the Sgt model in the unit, but DCo don't have Sgts.

**Comment by ChristopherBuilderman** [comment]
Right but the difference is what you replace. The Battlescribe file is actually accurate to the original datasheet, but its no longer accurate to the FAQ. Also you might have been able to get a melee weapon, but you couldn't have a melee weapon and an upgraded pistol while using a rifle loadout, which you can on the new datasheet.

And yeah its sort of annoying how they have to write their way around a Sergeant model without having a Sergeant model but the lore demands it.

**Comment by alphalas** [comment]
We understand. If you wish to discuss further please take to the discord.
