### ISSUE TITLE
Imperium - Dark Angels: Storm Eagle should be available in Deathwing Detachment

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9731]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** The Deathwing detachment doesn’t list the Stormeagle Gunship even though it can transport Terminators and has the checkbox for Rites of Initiation.

**Comment by Technoblazed** [comment]
The Storm Eagle shouldn't have the ability to take Rites of Initiation, that's the mistake there.
