### ISSUE TITLE
Astartes Deathwatch: Captain has no access to Chapter Command option

### ISSUE THREAD

**Issue by idjmv** [BSData/wh40k-9e#9732]
**File/Catalogue:** Warhammer 40,000 v9 1.27

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Description:** As title says

**Comment by Mad-Spy** [comment]
Appears to be working fine in the current release data. Captains in Dark Angels lists (assuming "Astartes Deathwing" means Dark Angels) have access to Chapter Command options exactly the same as all other Captains.

Maybe a screenshot of the problem would help, @idjmv?

**Comment by idjmv** [comment]
Apologies, i meant the Deathwatch chapter, Deathwings was a typo, it was past midnight.

**Comment by Mad-Spy** [comment]
This is correct behaviour. See the second column, first paragraph, p98 of Codex: Space Marines.

![image](https://user-images.githubusercontent.com/29306451/115885520-f1b90580-a447-11eb-84eb-8820941eeda3.png)
