### ISSUE TITLE
Acolyte hybrids

### ISSUE THREAD

**Issue by ivoryhammer** [BSData/wh40k-9e#9743]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** no

**Description:** Acolyte Hybrids are improperly point costed.   They are supposed to be 7 points and their hand flamers are supposed to be 1 point.

**Comment by Technoblazed** [comment]
They are 8 points base and the flamers are free per the latest MFM update.

![Image](https://i.tech-no.me/2021/04/24/210424221616.png)

https://www.warhammer-community.com/wp-content/uploads/2020/08/gxruRl769G2olA3v.pdf
