### ISSUE TITLE
Imperium - Space Marines: Wrong Power Level for Assault Squad

### ISSUE THREAD

**Issue by kaeldavan** [BSData/wh40k-9e#9748]
File: Imperium - Dark Angels.catz

BattleScribe version: v2.03.21.166

Platform: Windows

Dropbox: No

Description: The Power Level for an Assault Squad is wrongly listed as 4 per 5 Marines. Should be 5 per 5 Marines according to the codex and latest FAQ's.

**Comment by Mad-Spy** [comment]
Which catalogue is this in? It appears to be correct in the ones I've checked.

**Comment by kaeldavan** [comment]
Whats a catalogue?
My Data was from 15. April. I just updated now and can check if its still wrong.

**Comment by kaeldavan** [comment]
After the update to data from the 22. April its now correct..
I update my data every time i start BattleScribe so i don't know why is still said 15. April on the 25th when i made this post. I am sorry for the inconvenience. Please close the issue.

**Comment by Mad-Spy** [comment]
FYI, the catalogue is the faction you selected.

**Comment by kaeldavan** [comment]
Thank you for the information.
