### ISSUE TITLE
Chaos - Death Guard - Missing Malicious Volleys rule

### ISSUE THREAD

**Issue by Malignence** [BSData/wh40k-9e#9749]
**File/Catalogue:** Warhammer 40k 9e v182 - Chaos - Death Guard

**BattleScribe version:** 2.03.

**Platform:** Windows/Android

**Dropbox:** No

**Description:** None of the Bubonic Astartes units show the malicious volleys rule on their sheets.

**Comment by Mad-Spy** [comment]
~~That rule is not in their Codex and therefore does not apply to them.~~

I'm clearly blind and it needs to be applied to the relevant units (which is not ALL units).
