### ISSUE TITLE
Imperium - Raven Guard: Primaris Captain with Relic shield should have access to Silentus

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9754]
**File:** Imperium - Raven Guard.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Primaris Captain with the indomitus loadout (heavy bolt pistol, master-crafted power sword, and relic shield) appears unable to be given the Silentus Pistol relic, even though that relic states it replaces a bolt pistol or heavy bolt pistol), even though a Bladeguard Sargent can take it via a stratagem.

**Comment by Technoblazed** [comment]
Can't replicate this at all, are you sure that you had a warlord in your roster and raven guard selected as your chapter?

**Comment by acebaur** [comment]
It's already fixed on master
