### ISSUE TITLE
Chaos - Death Guard - Missing text from The Deamon's Favour relic

### ISSUE THREAD

**Issue by Ma09ro** [BSData/wh40k-9e#9755]
**File/Catalogue:** Chaos - Death Guard.catz

**BattleScribe version:** 2.03.25.338

**Platform:** Android

**Dropbox:** No

**Description:** The relic The Deamon's Favour is missing it's rules and text. It is a relic for Malignant Plaguecaster for The Wreatched. When viewing the relic it only shows it's name and then blank.

**Comment by Mad-Spy** [comment]
That's the one that changes the Plaguecaster's ability, right? So when you select it, that's what it does.

![image](https://user-images.githubusercontent.com/29306451/116236085-87110e00-a756-11eb-8b19-8349b4e4f908.png)
