### ISSUE TITLE
Dark Apostle Weapon Options

### ISSUE THREAD

**Issue by righter8** [BSData/wh40k-9e#9761]
**File/Catalogue:** Chaos Space Marines v162

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/

**Description:** Dark Apostle should have options
to replace its bolt pistol with one item from the Pistols or Combi-weapons lists.
It does not.

**Comment by Technoblazed** [comment]
Which publication allows them to replace these?

**Comment by righter8** [comment]
Codex: Chaos Space Marines 2017 page 126
![3E16B54C-B01E-415F-91FC-E72318F743E4](https://user-images.githubusercontent.com/83378002/116491304-903dd000-a867-11eb-8e01-ac995f7318ec.jpeg)

**Comment by Technoblazed** [comment]
That datasheet was superseded by Codex: Chaos Space Marines 2019.

![Image](https://i.tech-no.me/2021/04/29/210429022323.png)
