### ISSUE TITLE
Craftworlds: Some models are referencing the GST Warlord SSE for conditions

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k-9e#9766]
Prince Yriel and Illic Nightspear are referencing the GST Warlord SSE to unhide their WLTs which means they currently do not unhide because they should be referencing the Ynnari one.

**Comment by FarseerVeraenthis** [comment]
The cheeky little wotsits...!

**Comment by WindstormSCR** [comment]
Fixed in 29072b60aae77df890b10f160c10c4effb59bcd7
