### ISSUE TITLE
Death Guard - April 2021 FAQ points updates are missing

### ISSUE THREAD

**Issue by Malignence** [BSData/wh40k-9e#9769]
**File/Catalogue:** 40k 9e v182

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Several units are still mis-costed. Looked into fixing it myself but not a contributor and don't honestly have the will to learn guidelines.

**Comment by Technoblazed** [comment]
Which FAQ are you referring to exactly?

**Comment by AbonShell** [comment]
> Which FAQ are you referring to exactly?

I believe they're referring to the February 4th Munitorum Field Manual, thinking it came out April 2nd.

**Comment by Technoblazed** [comment]
> > Which FAQ are you referring to exactly?
> 
> I believe they're referring to the February 4th Munitorum Field Manual, thinking it came out April 2nd.

That's what I'm thinking too, the only April FAQ is for Kill Team :)

Regardless, the points should match the MFM FAQ update released on February 4th, if you have specific units that are incorrect, those would be better to provide.

**Comment by Mad-Spy** [comment]
I don't have the will to fix vague reports. Raise a new issue with examples.
