### ISSUE TITLE
Death Guard - 2021 Points Update not showing

### ISSUE THREAD

**Issue by Malignence** [BSData/wh40k-9e#9770]
**File/Catalogue:** 40k 9e

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** New issue to clarify problem - Attached is DG PL update for 2021, from Feb (not Apr as originally believed) Notable issues are Plague Marines, Tallyman and Blightlords though there's a couple others.
[FLCRqqt2W2mN7Biv.pdf](https://github.com/BSData/wh40k/files/6400606/FLCRqqt2W2mN7Biv.pdf)

**Comment by Mad-Spy** [comment]
The PL update came out before the Codex and was superseded by it. Note how all of the new Codex models are missing.

**Comment by Malignence** [comment]
Not to seem like a pest, but I believe this is incorrect - You're right the codex units are missing but the codex was released Jan 23 while that doc I included is Feb 4. I've emailed GW to confirm as well.

**Comment by Mad-Spy** [comment]
The doc was originally released on (or around) 7th Jan, _before_ the Codex. That is the timestamp I have on the version I have. It _was_ later updated.

The updates refer to the old names of units (Chaos Lord, Daemon Prince of Nurgle), old unit size options (Plague Marines only have 1 size increment now, Cultists cannot be taken in 40 man units), do not include new units, and include Daemons, which are not in the 9e Codex.

All of this points to it being an update for the 8e Codex and not applicable to the new Codex.
