### ISSUE TITLE
Sammael missing from Dark Angels Lists

### ISSUE THREAD

**Issue by Rattleme** [BSData/wh40k-9e#9779]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
In Dark Angels lists Sammael is not able to be selected from the menu. Literally not there. The other named characters are available but not Sammael. Please fix this
![Screenshot (1)](https://user-images.githubusercontent.com/73722339/116790616-6c9aa580-aa72-11eb-933a-414cdeb03b74.png)

**Comment by Technoblazed** [comment]
Already fixed in next release.
