### ISSUE TITLE
Adeptus Custodes - Achillius Dreadnought has too many attacks

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9787]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The achillius dreadnought for custodes has 1 too many attacks on its profile. It shows 5 base attacks and should be 4

**Comment by Technoblazed** [comment]
Referencing #9786, the downloads publication being referenced is outdated and no longer the newest publication, please consult the Imperial Armour: Compendium for the latest rules.
