### ISSUE TITLE
Sammael missing from Dark Angels

### ISSUE THREAD

**Issue by C0rruptedAI** [BSData/wh40k-9e#9798]
**File/Catalogue:** Dark Angels.cat

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Sammael is no longer a selectable HQ option in Dark Angels. His entry in line 244 of the Dark Angels.cat file seems like it's truncated or missing content. He should be available in the standard formation, Deathwing formation, and Ravenwing formation.

**Comment by Technoblazed** [comment]
This is already fixed in the next release.
