### ISSUE TITLE
Sly Marbo should probably be in the Elites slot instead of HQ slot

### ISSUE THREAD

**Issue by DaCleanerCode** [BSData/wh40k-9e#9800]
**File/Catalogue:** 
Warhammer 40,000 9th edition v183

**BattleScribe version:** 2.03.
2.03.21

**Platform:** Windows/iOS/Android/Mac/Linux
Windows

**Dropbox:** Yes/No
No

**Description:** Detailed issue description.
Sly Marbo is listed under the HQ slot when building an Astra Militarum army. I believe he should be listed under the Elites slot:
http://wahapedia.ru/wh40k9ed/factions/astra-militarum/Sly-Marbo

**Comment by Mad-Spy** [comment]
Wahapedia is not the rules and can be wrong (same as Battlescribe). Please provide a GW source.

**Comment by DaCleanerCode** [comment]
https://www.warhammer-community.com/wp-content/uploads/2020/08/76UtmPgtSCGKJAnW.pdf

This shows sly marbo as an elite's choice. I think this is a GW source, but am unsure. Does this work for you?

**Comment by Mad-Spy** [comment]
His current datasheet (and the 40k app) list him as HQ. The MFM doesn't have permission to change FOC slots, so until GW releases a new datasheet for him, he's an HQ.
