### ISSUE TITLE
successor chapter tactics on forgeworld chapters

### ISSUE THREAD

**Issue by Pacioman** [BSData/wh40k-9e#9804]
**File/Catalogue:** 9.1.29

**BattleScribe version:** 2.03.

**Platform:** Windows 

**Dropbox:** Yes/No

**Description:** Detailed issue description.
when selecting successor chapters like Red Scorpions or Minotaurs i cannot choose successor chapter tactics or I have an illegal list. For example if i choose salamanders repository and then red scorpions chapter (i know it's suggested use them as ultramarines but technically I can use them in any chapter flavour)  i cannot choose successor chapters tactics.

**Comment by DAN38100** [comment]
I have the same problem. I'm playing the red scorpions as a salamander successor chapter.
Problem is, the chapter tactics list only unfolds when you click on "custom chapter". Forge World chapters can choose their successor chapters and are eligible to choose chapter tactics too.
But, as soon as I have a FW chapter + click on "custom chapter" (to unfold the chapter tactics list) my list gets invalid.

I dindn't update a BS  for a few weeks, but it was all  working before.
