### ISSUE TITLE
Blood Claws, Wolf Guard error

### ISSUE THREAD

**Issue by Darikson** [BSData/wh40k-9e#9805]
File/Catalogue: Imperium - Space Wolves

BattleScribe version: 2.03.21

Platform: Windows and Android

Dropbox: No

Description: Hello,there is an issue with the blood claws. The wolf guard doesn't count as a member to unlock the 2nd special weapon with 15 members. Thanks (Repaired on issue 7111, but it comes back)
![BCW](https://user-images.githubusercontent.com/43108840/117066777-7863c180-ad29-11eb-933b-beb825f87554.png)

**Comment by Mad-Spy** [comment]
This is correct behaviour. They no longer count since the new supplement because they do not have the BLOOD CLAW keyword which is now required to unlock the special weapon.

![image](https://user-images.githubusercontent.com/29306451/117067465-f4f2a200-ad21-11eb-8aee-7d723e0383cb.png)

**Comment by Darikson** [comment]
Sorry! I didn't see it, thanks for all!
