### ISSUE TITLE
Switching craftworld attribute from Eldar to Ynnari results in relic error in my other detachment

### ISSUE THREAD

**Issue by DataGooner** [BSData/wh40k-9e#9811]
**File/Catalogue:** 

[Eldar Error.zip](https://github.com/BSData/wh40k/files/6427171/Eldar.Error.zip)

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

In the attached zip, I have two lists.  When I switch the CWE detachment to Ynnari, an error pops up that I have too many relics of the black library in my harlequin battalion detachment.  There are no errors when I select Ulthwe or another CWE attribute.  I believe there should be no penalty, but the behavior should be the same for attributes.

Thank you!

**Comment by Mad-Spy** [comment]
@WindstormSCR, Looks like there's an incorrect condition on the Enigmas SSEG. Pretty sure the highlighted one should only be checking the Force.

![image](https://user-images.githubusercontent.com/29306451/117154521-d50bbe80-adb3-11eb-95a0-2d9f332b23b5.png)

Tbh, that condition is redundant given that the whole SSEG gets hidden if the Force is Ynnari anyway.

**Comment by DataGooner** [comment]
Was the change included on the BattleScribe update from May 6th?  I'm still seeing the validation error on my end.  Thank you!

**Comment by Mad-Spy** [comment]
Yes, and is working fine for me on that version. You might need to recreate the list.

**Comment by Mad-Spy** [comment]
Your example list also validates successfully for me in the new version.

**Comment by DataGooner** [comment]
I must not have deleted my old data file.  It works now.   Thank you very much!
