### ISSUE TITLE
Chaos - Chaos Space Marines: Issue with Chaos Contemptor Dreadnought

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9814]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Chaos Space marines hellforged contemptor dreadnoughts from the Imperial Armour compendium still has an error saying detachments “has too many selections from Relic” when dreadnoughts do not have this restriction anymore, despite still maintaining the “relic” keyword

**Comment by Technoblazed** [comment]
Do you have an example roster, data version or something to replicate this? It appears to work fine as far as I can see.

**Comment by Mad-Spy** [comment]
There's also no such thing as a _Hellforged_ Contemptor Dread any more, so if you have one in an older list somehow, I wouldn't be surprised if it gives you errors.
