### ISSUE TITLE
Refactor Filed Generator 133rd Lambdan Lions Relic cannot be given to non warlord Tempestor Primes

### ISSUE THREAD

**Issue by DaCleanerCode** [BSData/wh40k-9e#9815]
**File/Catalogue:** 
40k 9th edition v183

**BattleScribe version:** 2.03.
2.03.21

**Platform:** Windows/iOS/Android/Mac/Linux
Windows

**Dropbox:** Yes/No

**Description:** Detailed issue description.
I want to give my non-warlord Lambdan Lions tempestor prime the Refactor Filed Generator relic, but that relic is only visible to tempestor primes that are a warlord. I don't see in the rules that the relic has to be given to a warlord, only that it has to be given to a Lambdan Lions model.

**Comment by Technoblazed** [comment]
For Heirlooms of the Regiments from PA:

> If your army is led by a Warlord in a MILITARUM TEMPESTUS Detachment, you can give one of the following Relics to a CHARACTER model in a MILITARUM TEMPESTUS Detachment from your army instead of giving them a Relic from Codex: Astra Militarum.

Is your Warlord inside a MILITARUM TEMPESTUS Detachment?

**Comment by DaCleanerCode** [comment]
@Technoblazed No i wasn't, so there is no bug Battlscribe knew better than me! Thanks for pointing out the text I missed.
