### ISSUE TITLE
Sammael has disappeared 

### ISSUE THREAD

**Issue by SpacedUK** [BSData/wh40k-9e#9817]
**File/Catalogue:** Warhammer 40,000 v9.1.29 - Dark Angels

**BattleScribe version:** 2.03.15

**Platform:** ios

**Dropbox:** No

**Description:** I logged in and my lists said that Sammael was not valid (hidden).  I removed him in order to re-add, but he no longer appears as an option

**Comment by Mad-Spy** [comment]
Fixed for next release.
