### ISSUE TITLE
Relic Contemptor melee costs wrong

### ISSUE THREAD

**Issue by mong01** [BSData/wh40k-9e#9822]
**File/Catalogue:** Imperium - FW Adeptus Astartes.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Taking two of the same melee weapon for the Relic Contemptor Dreadnought increases the points cost of both weapons.

**Comment by acebaur** [comment]
Fixed on Master
