### ISSUE TITLE
Chaos - Daemons - No hellforged artefacts for daemon prince

### ISSUE THREAD

**Issue by Chepelash** [BSData/wh40k-9e#9835]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
After update on May 6th there are no hellforged artefacts for daemon prince on daemon roster.

![image](https://user-images.githubusercontent.com/26011914/117587411-7ed9ab00-b126-11eb-9f8e-1a91e393bf7b.png)

**Comment by Mad-Spy** [comment]
Fixed in next release
