### ISSUE TITLE
AdMech

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#9836]
**File/Catalogue:** Adeptus Mechanicus v131

**BattleScribe version:** 2.03.15

**Platform:** iOS

**Dropbox:** No

**Description:** 
- Whenever I select the Army of Renown - Mechanicus Defense Cohort, it also takes away Agents of the Imperium and No Force Rog Slot even though I believe you still get those since you only lose Skitarii units

**Comment by Mad-Spy** [comment]
The bullet point before the one you quote states that you can _only_ include ADEPTUS MECHANICUS models in your army. Agents of the Imperium do not have that keyword.
