### ISSUE TITLE
Legends Units in Chapters

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#9837]
**File/Catalogue:** Blood Angels v224

**BattleScribe version:** 2.03.15

**Platform:** iOS

**Dropbox:** No

**Description:** 
- When I select Hide Legends Units in the Unit Filter, it does not hide Chief Librarian Mephiston [Legends] or Sanguinary Priest on Bike [Legends]

**Comment by Mad-Spy** [comment]
@Thairne probably need to check whether there are any units in DA which aren't being hidden correctly. There were a few in Wolves.
