### ISSUE TITLE
necron ccb missing warlord option

### ISSUE THREAD

**Issue by raven1840** [BSData/wh40k-9e#9840]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows
**Dropbox:** No

**Description:** Detailed issue description.
There is no way to select warlord option for the Command Control Barge on PC

**Comment by Technoblazed** [comment]
Can you provide more information on your full roster, do you have the silent king or a phaeron in your roster?

**Comment by raven1840** [comment]
++ Patrol Detachment -2CP (Necrons) [48 PL, -7CP, 960pts] ++

+ Configuration +

Detachment Command Cost [-2CP]

Dynasty Choice: Dynasty: Mephrit

+ HQ +

Overlord [6 PL, -3CP, 100pts]: Dynastic Heirlooms, Hand of the Phaeron, Relic: Veil of Darkness
. Tachyon Arrow and Hyperphase Glaive: Tachyon Arrow

Royal Warden [4 PL, -1CP, 75pts]: Dynastic Heirlooms, Relic (Mephrit): Conduit of Stars

+ Troops +

Immortals [8 PL, 170pts]: Gauss Blaster, 10x Immortal

Necron Warriors [12 PL, 260pts]
. 10x Necron Warrior (Gauss Flayer): 10x Gauss Flayer
. 10x Necron Warrior (Gauss Reaper): 10x Gauss Reaper

+ Elites +

Hexmark Destroyer [4 PL, -1CP, 75pts]: Dynastic Heirlooms, Relic: Gauntlet of the Conflagrator

+ Heavy Support +

Canoptek Doomstalker [7 PL, 140pts]

Canoptek Doomstalker [7 PL, 140pts]

++ Patrol Detachment -2CP (Necrons) [47 PL, 10CP, 1,013pts] ++

+ Configuration +

Battle Size [12CP]: 3. Strike Force (101-200 Total PL / 1001-2000 Points)

Detachment Command Cost [-2CP]

Dynasty Choice: Dynasty: Mephrit

+ HQ +

Catacomb Command Barge [9 PL, 155pts]: Gauss Cannon, Warscythe

Illuminor Szeras [8 PL, 160pts]

+ Troops +

Necron Warriors [12 PL, 260pts]
. 10x Necron Warrior (Gauss Flayer): 10x Gauss Flayer
. 10x Necron Warrior (Gauss Reaper): 10x Gauss Reaper

+ Elites +

Skorpekh Destroyers [10 PL, 210pts]
. 2x Skorpekh Destroyer (Reap-Blade): 2x Hyperphase Reap-Blade
. 4x Skorpekh Destroyer (Thresher): 4x Hyperphase Threshers

+ Fast Attack +

Tomb Blades [8 PL, 228pts]
. Tomb Blade: Shadowloom, Shieldvanes, Twin Gauss Blaster
. Tomb Blade: Shadowloom, Shieldvanes, Twin Gauss Blaster
. Tomb Blade: Shadowloom, Shieldvanes, Twin Gauss Blaster
. Tomb Blade: Shadowloom, Shieldvanes, Twin Gauss Blaster
. Tomb Blade: Shadowloom, Shieldvanes, Twin Gauss Blaster
. Tomb Blade: Shadowloom, Shieldvanes, Twin Gauss Blaster

++ Total: [95 PL, 3CP, 1,973pts] ++

Created with BattleScribe (https://battlescribe.net)

________________________________

**Comment by Technoblazed** [comment]
You have used the stratagem `Hand of the Phaeron` on the Overlord, this makes the catacomb command barge non-eligible for your warlord.

> When mustering your army, if it contains THE SILENT KING model, that model must be selected as your WARLORD. Otherwise, **if your army contains a PHAERON model, that model must be selected as your WARLORD**. Otherwise, if your army contains an OVERLORD model, that model must be selected as your WARLORD. Otherwise, if your army contains a LORD model, that model must be selected as your WARLORD. If your army contains none of the listed models, select your WARLORD as normal.
