### ISSUE TITLE
Aeldari - Craftworlds: Wraith Host WLT and Relic should only be available to Spiritseers

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9849]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Hi, a small error, but when making a wraith host detachment only wraith construct models and spiritseers should be able to gain the wraith host keyword, and thus have access to the associated warlord traits such as "Revered by the Dead". At the moment warlocks and farseers can also be given that keyword/warlord trait.

Thanks for the great data!

**Comment by Mad-Spy** [comment]
Also, the description text for the Specialist Detachment is incorrect, as it is missing "SPIRITSEERS and" from the 3rd sentence, and is also missing the changed text from the 1.2 Update in the second sentence (which blocks it from being used by Ynnari).

Wraithseers should also get access to Twilight Gloom when included in a Wraith Host, as they are WRAITH HOST PSYKERS.

I'd suggest actually applying the WRAITH HOST keyword to relevant models via a modifier and validating based on that.
