### ISSUE TITLE
Imperium - Adeptus Astartes - Dark Angels: Ravenwing Outrider Detachment entry is still always giving 3 CP

### ISSUE THREAD

**Issue by Citronnade** [BSData/wh40k-9e#9850]
**File/Catalogue:** Imperium - Adeptus Astartes - Dark Angels v208/v9.1.31

**BattleScribe version:** 2.03.21

**Platform:** Android 

**Dropbox:** Yes

**Description:** Exact same issue as #9613.  Reproduced using RW detachment of Cpt. on Bike with 3 ATVs, DW detachment of Azrael with 3 BGVs, using the same reproduction instructions in #9613.  The cost of the Ravenwing Outrider Detachment never changes no matter who the Warlord is, while the cost of the Deathwing Vanguard Detachment is properly No Cost or +3CP depending on who the Warlord is.

**Comment by Mad-Spy** [comment]
@Thairne this would be the problem.

![image](https://user-images.githubusercontent.com/29306451/118110656-9771eb80-b3da-11eb-9173-7039b4bfbc88.png)

I'm also not sure why the Ravenwing Detachment gets hidden when "Hide Primaris" is selected; there are definitely PRIMARIS models eligible to be in RAVENWING Detachments.

**Comment by Thairne** [comment]
well that would be a good question to whomever implemented the primaris selector :P
