### ISSUE TITLE
Imperium - Grey Knights: Brotherhood Ancient cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9858]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The brotherhood ancient is 100 pts. It should be 103 pts.

**Comment by tekton** [comment]
when the storm bolter got fixed, the ancient wasn't- and that was between QA passes, doh
