### ISSUE TITLE
Imperium - Dark Angels: Ravenwing Outrider selection doesn't refund CP

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9859]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Ravenwing outrider detachment no longer refunds the 3cp it should

**Comment by Mad-Spy** [comment]
@Thairne Frickin' "and child selections" checkbox.

**Comment by Thairne** [comment]
this is starting to get annoying :P
