### ISSUE TITLE
Grey Knights: Relics are visible even when a Warlord is not selected

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k-9e#9860]
The convention is that relic lists are hidden except when a Warlord is selected.

**Comment by tekton** [comment]
GK still have the old strat wording, so it's not entirely about the warlord. Oldest codex syndrome! Will address this with new codex once the wordings change.

**Comment by alphalas** [comment]
@tekton its more all the other files hide the relics unless there is a select of warlord or said strat in the roster; not that the WL has to be GK for the relics to show.
