### ISSUE TITLE
Drukhari - "Tolerated Ambition" roster validation error

### ISSUE THREAD

**Issue by CrumpetNinja** [BSData/wh40k-9e#9865]
**File/Catalogue:** Aeldari - Drukhari v118

**BattleScribe version:** 2.03.

**Platform:** Windows/Android

**Dropbox:** No

**Description:** Battlescribe gives a roster validation error when using the "tolerated ambition" stratagem more than once in a single detachment if that detachment is not the one with the "Battle Size" configuration option directly linked to it. 

Roster should look for Battle Size field even if it is linked to a different detachment, the same way it does for other similar stratagems, e.g. the "Prizes from the Dark City" strat.

Reproduced on Android, and Windows.

**Comment by Mad-Spy** [comment]
@WindstormSCR both the modifiers and conditions are per-Force when they should be per-Roster.
