### ISSUE TITLE
Imperium - White Scars - MCPS Relic not validating correctly

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9866]
**File:** Imperium - White Scars.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** White Scars chapter,
Primaris Lieutenant equipped with a master crafted power sword or the sword + storm shield is unable to take "Scimitar of the Great Khan" relic.

**Comment by Technoblazed** [comment]
Looks like there's 2 different instances of the MCPS being used, one from the BRB and one from the SM Codex.
