### ISSUE TITLE
Drukhari - Hekatrix Bloodbrides w/ special weapons issue

### ISSUE THREAD

**Issue by ItsmeHJB** [BSData/wh40k-9e#9867]
Catalogue: 40k

BattleScribe version: 2.03.21.166

Platform: Windows

Dropbox: Yes

Description: When building a Drukhari list using Aeldari - Drukhari v118, I encountered an issue with the Hekatrix Bloodbrides.
I had a unit with 3x standard Bloodbrides, 1x Hekatrix, and 1x Hekatrix Bloodbride w/ Shardnet and Impaler.

This was considered illegal, and I was forced to increase the size of the unit to 10 even though Wahapedia states: "If this unit contains fewer than 10 models, 1 Hekatrix Bloodbride can be equipped with one of the following instead of 1 splinter pistol and 1 hekatarii blade: 1 hydra gauntlets; 1 razorflails; 1 shardnet and impaler."

The rosz file is included via the dropbox link below:
https://www.dropbox.com/s/ytu8ykg0b2u567s/Drukhari1k.rosz?dl=0

Feel free to comment for further clarification.

**Comment by Mad-Spy** [comment]
Wahapedia is not the rules and should not be used as a primary rules source. 

Hekatrix Bloodbrides are no longer a separate unit (but are represented as such in the data for ease of use). They are an upgrade to the Wyches unit. Please refer to the Wyches datasheet in the latest Drukhari Codex for their rules. They can't take upgrades until there are 10 of them now.
