### ISSUE TITLE
Death Guard Terminus Est Assault Force Problem

### ISSUE THREAD

**Issue by Granmore** [BSData/wh40k-9e#9872]
If Terminus Est Assault Force is enabled, BattleScribe gives error when adding Fortification detachment.
Miasmic Malignifier isnt a vehicle and can be included in the Terminus Est Assault Force army in Fortification detachment if the Detachment is Harbingers plague company.

**Comment by Valorcalls** [comment]
The Maismic Malignifier is a vehicle, as such is not allowed in your army if using that AoR.
![Maismic](https://user-images.githubusercontent.com/68749775/119073976-30e16480-b9bc-11eb-95fd-664808baa905.png)
