### ISSUE TITLE
Sly Marbo is an Elite not an HQ

### ISSUE THREAD

**Issue by tekwerk** [BSData/wh40k-9e#9875]
Sly Marbo is an elite. I saw a closed ticket #9800 that claimed that Sly's current datasheet lists him as an HQ but that is false. My MTO Sly from about a month ago came with the datasheet in the picture attached, clearly listing him as an Elite, and this is backed up in changes to the Munitorum Field Manual, also attached. 
![sly marbo elite](https://user-images.githubusercontent.com/84628791/119228635-dc380980-bae1-11eb-9b4d-cd7c92b57f20.jpg)
[munitorum field manual 2021.pdf](https://github.com/BSData/wh40k/files/6526510/munitorum.field.manual.2021.pdf)

**Comment by AbonShell** [comment]
MFM doesn't doesn't have the authority to change datasheet organization, so unless it has been FAQ'd, he remains an HQ.

**Comment by Mad-Spy** [comment]
@AbonShell the OP posted the current datasheet, so those are the correct rules. One of the few times the MFM _is_ actually correct!

@tekwerk, thanks for posting the evidence; hadn't seen that before.
