### ISSUE TITLE
Space marine relic - Tome of Malcador bug

### ISSUE THREAD

**Issue by sevrilkestra** [BSData/wh40k-9e#9886]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS

**Dropbox:** No

**Description:** When equipping the space marine relic "Tome of Malcador", warnings are given when choosing a different psychic power from a different tree line although the relic allows it. 
![tome of malcador](https://user-images.githubusercontent.com/75389030/119744952-1fd0a180-be5b-11eb-8e18-7f1f44ae9c0e.png)

**Comment by acebaur** [comment]
No it doesn't. All you powers must come from one list per the supplements
