### ISSUE TITLE
Dark Angels Ravenwing Outrider CP refund bug

### ISSUE THREAD

**Issue by Granmore** [BSData/wh40k-9e#9887]
**File/Catalogue:** 

**BattleScribe version:** 2.03.15

**Platform:** Windows/iOS/

**Dropbox:** Yes

**Description:** 
Dark Angels Ravenwing Outrider Detachment dont give +3cp back even if there is warlord in the same detachment.

**Comment by Mad-Spy** [comment]
Fixed in next release.
