### ISSUE TITLE
Adeptus Mechanicus: Sterylizors Cost and Onager Wargear

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9890]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Pteraxii Sterylizors are 4PL, 85 pts in the new Codex, but they have their old cost in battlescribe. The Onager Dunecrawler is also missing the extra wargear options of smoke launchers and data tethers

**Comment by DedusJovus** [comment]
Sterylizors point cost is fine, they are 19pts per model (95 for unit of 5). Only the PL is wrong, it shoud be 4 as anon wrote.

**Comment by Thairne** [comment]
Onager has the Broad Data spectrum ability and the Smoke Screen keyword.
