### ISSUE TITLE
Datasmith Strategem and Holy Order problem

### ISSUE THREAD

**Issue by MarloBa** [BSData/wh40k-9e#9894]
**File/Catalogue:** WH40k 9th v185

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** Yes/No

**Description:** Datasmith seems not able to get mechanicus locum, a relic or an Holyorder, eventhough he is an Character and Tech-Priest

**Comment by DedusJovus** [comment]
You're correct about the Holy Orders, but for the relic and locum, you first have to select a warlord in the same detachment as datasmith.

**Comment by MarloBa** [comment]
![Datasmith](https://user-images.githubusercontent.com/72087343/120063659-97bfe700-c068-11eb-96a6-46cf935cb20a.PNG)
I did  that here and there was no option for mechanicus locum on the datasmith (right side)

**Comment by DedusJovus** [comment]
You're right. You can give him an extra relic if you activate Archeotech Specialist strat, but Muechanicum Locum doesn't show up for him. My bad.
