### ISSUE TITLE
AdMech - Datasmith has no Mechanicus Locum option

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9895]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Cybernetica Datasmith does not have Mechanicus Locum option.

**Comment by Thairne** [comment]
Fixed, will be released
