### ISSUE TITLE
Chaos Space Marines: Chosen

### ISSUE THREAD

**Issue by Wyvern350** [BSData/wh40k-9e#99]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** The entry for a squad of Chosen is all messed up.
The Chosen Champion is listed as an Aspiring Champion in the unit description
The entry in the Index is worded poorly.  The Chosen Champion should be able to replace his Boltgun for an item from the Champion Equipment List AND replace his bolt pistol for an item from the Champion Equipment List, or replace both with a Combi-weapon.  Currently, options are chosen under bolt pistol and boltgun, Battle Scribe returns a validation error that there are too many choices selected.
A squad of chosen should be able to make up to four replacements in the Weapon Replacements (up to 4) section.  Currently, the way the file is set up with radio buttons instead of quantity fields, you can only select one replacement.  This does not allow the unit to a) select different replacements for the four weapons and b) returns a validation error if more than one radio button is set to anything other than (none).

**Comment by cartag** [comment]
Chosen Champion should be able to replace bolt pistol and boltgun each with items from the Champions Equipment list, but not both for one combi weapon. You can replace one or the other for a combi-wepaon, but not both. You could bring a combi-melta and a chainaxe for instance.

The rest is being corrected.

**Comment by Wyvern350** [comment]
The way I was reading it was that he had to replace both his bolt pistol and boltgun with a single combi-weapon, but going back and reading it I think you're right.
