### ISSUE TITLE
AdMech - Cybernetica Datasmith PL wrong

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9900]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Cybernetica Datasmith is 2PL, not 3, as is listed.

**Comment by Thairne** [comment]
Fixed, will be released
