### ISSUE TITLE
Bug report: Imperium - Adeptus Mechanicus - Tech-Priest Enginsser "Brotherhood of the Cog" ability

### ISSUE THREAD

**Issue by krakjen** [BSData/wh40k-9e#9901]
File: Imperium - Adeptus Mechanicus.catz

BattleScribe version: 2.03.25

Platform: Android

Dropbox: No

Description: The Brotherhood of the Cog ability doesn't seem to apply. Even if the conditions are filled, the Enginseer stills takes up a HQ slot.

**Comment by AbonShell** [comment]
Look in to no force org, you'll see that there where you can then choose your tech priest

**Comment by krakjen** [comment]
Ho thanks, I missed that.
