### ISSUE TITLE
Adeptus Mechanicus Issues

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#9904]
**File/Catalogue:** Adeptus Mechanicus v151

**BattleScribe version:** 2.03.15

**Platform:** iOS

**Dropbox:** Yes

**Description:**
The Uncreator Gauntlet has a damage characteristic of 3D3 but should just be 3
There is also a typo in the Uncreator Gauntlet's ability. "Each time an attack made with this weapon its a VEHICLE unit" but it should be hits not its
The Fulgurite Electro-Priests electroleech stave still has the old ability of D3 mortal wounds instead of the normal damage and needs to be updated to the new one in the book
When I select the Mechanicus Defense Cohort, the Skitarii Marshal is not hidden

**Comment by TobiasOsterhaug** [comment]
Additional: Cybernetica Datasmith is currently unable to take a Holy Order. Cybernetica Datasmith also doesn't register as a valid target for Mechanicus Locum
