### ISSUE TITLE
Adeptus Mechanicus v151

### ISSUE THREAD

**Issue by TobiasOsterhaug** [BSData/wh40k-9e#9905]
File/Catalogue: Adeptus Mechanicus v151

BattleScribe version: 2.03.15

Platform: Android

Dropbox: Yes

Description:
Cybernetica Datasmith is unable to take Holy Orders (Datasmiths have the Tech Priest keyword and are therefore valid targets)
Cybernetica Datasmiths do not currently register as valid targets for the Mechanicus Locum strategem (they are characters)

**Comment by DedusJovus** [comment]
This has been fixed, just not published yet.
