### ISSUE TITLE
Aeldari - Craftworlds v133, Vampire Hunter [Legends] wrong number of attacks on Twin Vampire Pulsar

### ISSUE THREAD

**Issue by KalChoedan** [BSData/wh40k-9e#9913]
**File/Catalogue:** Aeldari - Craftworlds v133

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Vampire Hunter [Legends] weapon Twin Vampire Pulsar has weapon Type set incorrectly to Heavy 49. Should be Heavy 9, per most recent Forgeworld Legends pdf.

**Comment by WindstormSCR** [comment]
It's not a bug, it's a feature!
