### ISSUE TITLE
Imperium - Adeptus Mechanicus: Servitors appear in NFO after adding a Datasmith to NFO from having Kastelan robots

### ISSUE THREAD

**Issue by AbonShell** [BSData/wh40k-9e#9919]
**File/Catalogue:** admech 151

**BattleScribe version:** 2.03.25

**Platform:**/Android/

**Dropbox:** Yes

**Description:** Adding a Datasmith to no force org forces Servitors to appear in that category when I don't think there's any rule that allows Servitors to appear there.

**Comment by Thairne** [comment]
It's in the Servitors Mindlock Ability.
