### ISSUE TITLE
Deathwatch - Proteus Kill Team - Black shield Power Level cost. 

### ISSUE THREAD

**Issue by Anarchitect01** [BSData/wh40k-9e#9930]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** The Black shield entry in the Proteus Kill Team is missing it's power level cost. It should be 1 PL

**Comment by Technoblazed** [comment]
I can't seem to find any source that the black shield has a PL cost at all, do you have a written source for this that I've missed somewhere?

**Comment by Anarchitect01** [comment]
The ability to include one was added via the FAQ, so there's not complete
rules text, just a statement saying you can take one. But adding a
Deathwatch Veteran is 1PL, and the Black shield is a type of Deathwatch
Veteran.

**Comment by alphalas** [comment]
In this case, no it is not. A deathwatch veteran is a specific model; and the blackshield is not that specific model.
