### ISSUE TITLE
Tome Keepers successor chapter

### ISSUE THREAD

**Issue by Davios512** [BSData/wh40k-9e#9931]
Hello,

I noticed that the Ultramarines successor chapter "Tome Keepers" from White Dwarf Issue 458 is missing in battlescribe. They have 4 special characters with in build relics and special weapons so you can't build them as a custom chapter.

Thanks in advance!

**Comment by Mad-Spy** [comment]
At least the named Captain and Libby have weapon options not available to their standard versions (MC Power axe for the Primaris Captain and Force Stave for the Primaris Libby).

**Comment by acebaur** [comment]
On master
