### ISSUE TITLE
Eldar Wraithguard/blades 

### ISSUE THREAD

**Issue by Cyfighguy** [BSData/wh40k-9e#9934]
Warhammer 40,000 9.1.34

**BattleScribe version:** 2.03.21.166

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Eldar Wraithguard/blades had a point cost adjustment down to 37 points per model.

**Comment by alphalas** [comment]
you will not see CA point fixes until AFTER the CA book is officially released.
