### ISSUE TITLE
Imperium - Adeptus Mechanicus: Arc rifle profile not updated for new Codex

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9935]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Arc Rifle weapon profile in Skitarii Rangers and Skitarii Vanguards unit entries has incorrect range. Profile states its 24 inches which is the old value. The range  should be 30 inches as per new codex.

**Comment by Thairne** [comment]
![grafik](https://user-images.githubusercontent.com/8590840/120637801-a09d2800-c46f-11eb-8d9f-739ddbd01c31.png)
