### ISSUE TITLE
Space marines not selectable as top level force

### ISSUE THREAD

**Issue by Nebsie1** [BSData/wh40k-9e#9936]
**File/Cataloge   imperium space marine

**BattleScribe version:** 2.03.

**Platform:**Android

**Dropbox:** No

**Description:** when selecting a force for the roster, space marine does not appear as a selection, only supplement chapters are choosable
Space marines do not appear to be a selectable catalogue.

**Comment by acebaur** [comment]
Because you have to choose to be a sucesssor of someone.
