### ISSUE TITLE
Combat Doctrines are missing from Force Rules and Selection Rules for all Adeptus Astartes

### ISSUE THREAD

**Issue by voidstate** [BSData/wh40k-9e#9937]
**File/Catalogue:**
All Adeptus Astartes 

**BattleScribe version:** 
2.03.

**Description:** 
Combat Doctrines are missing from Force Rules and Selection Rules for all Adeptus Astartes.

They are listed by name under Angels of Death (which groups all the shared rules) but all the others have an additional entry showing the details for that particular rule. Basically, And They Shall Know No Fear, Bolter Discipline and Shock Assault  are all detailed. Combat Doctrines is not.

Example output: https://www.dropbox.com/s/wehea4eggngnz9c/image%2003-06-2021%20at%2008.56.jpeg?dl=0

From the rule book:

COMBAT DOCTRINES
If every unit from your army has the ADEPTUS ASTARTES keyword (excluding AGENT OF THE IMPERIUM and UNALIGNED units), this unit gains a bonus (see below) depending on which combat doctrine is active for your army, as follows:
During the first battle round, the Devastator Doctrine is active for your army.
During the second battle round, the Tactical Doctrine is active for your army.
At the start of the third battle round, select either the Tactical Doctrine or Assault Doctrine: until the end of that battle round, the doctrine you selected is active for your army.
During the fourth and subsequent battle rounds, the Assault Doctrine is active for your army.
Unless specified otherwise, this bonus is not cumulative with any other rules that improve the Armour Penetration characteristic of a weapon (e.g. the Storm of Fire Warlord Trait).

Devastator Doctrine
While this combat doctrine is active, improve the Armour Penetration characteristic of every Heavy and Grenade weapon that models in this unit are equipped with by 1.

Tactical Doctrine
While this combat doctrine is active, improve the Armour Penetration characteristic of every Rapid Fire and Assault weapon that models in this unit are equipped with by 1.

Assault Doctrine
While this combat doctrine is active, improve the Armour Penetration characteristic of every Pistol and Melee weapon that models in this unit are equipped with by 1.

**Comment by Mad-Spy** [comment]
It's a very long rule, which you can read out of your Codex. It doesn't need to be in the data, because the data is not a replacement for your Codex.

**Comment by voidstate** [comment]
Thanks for looking at this. I realise it’s long as-written but I’m happy to provide a shorter version to help players remember the rule. It could easily be condensed to a few sentences. 

If I condense it, would you consider including the rule. I ask specifically because I have had to look it up several times.
