### ISSUE TITLE
issue with archangels shard relic always being selectable

### ISSUE THREAD

**Issue by BAspector** [BSData/wh40k-9e#9942]
**File/Catalogue**: warhammer 40,000 v9.1.35 Imperium - Adeptus Astartes - Blood Angels.cat

**BattleScribe version**: 2.03.21

**Platform**: Windows/Android

**Dropbox**: No

Description: There is an issue with the special issue blood angels relic archangel's shard where it is useable by any character even though they do not have a power sword or master-crafted power sword equipped i.e. a lieutenant in reiver armor can be selected to use the shard even though he is only equipped with a combat blade.

Lastely, the stratagem angel ascendant (the give a Sargent a relic one) lets them also take the archangels shard even though the strat does not mention that relic being an option.

**Comment by alphalas** [comment]
Update your data making sure to check the delete data first checkbox - I cannot duplicate
