### ISSUE TITLE
Deathwatch Veteran wargear options

### ISSUE THREAD

**Issue by brianlaw033** [BSData/wh40k-9e#9948]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Description:** Deathwatch veterans shouldn’t be allowed to take combi-weapon with other weapons. Eg: combi-flamer with storm shield

**Comment by Technoblazed** [comment]
This isn't the case, you can pick 2 options from the deathwatch equipment list. When inside that, you can have the following:
- 2 of the "2 of these" items
- 1 of the "2 of these" items
- 1 of the "1 of these" items and 1 of the "2 of these" items
- 1 of the "1 of these" items.
