### ISSUE TITLE
Space Marines - Inceptor Points Error

### ISSUE THREAD

**Issue by Veles343** [BSData/wh40k-9e#9952]
**File/Catalogue:** Imperium - Imperial Fists.cat

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** Yes

**Description:** Points cost for plasma inceptors seems to be +20ppm instead of +10ppm per the 2021 MK II Chapter Approved

**Comment by Veles343** [comment]
Don't know if this effects other space marine files, I'm just using Imperial Fists

**Comment by acebaur** [comment]
The plasma exterminators are 10 points each, but the inceptors have two of them, so it's an extra 20ppm to add them. Points are correct.
