### ISSUE TITLE
Imperium - Dark Angels: Some models have incorrect points cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9966]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 9.01.36

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Dark Angels points not updated.

Chief Apothecary and Talonmaster still showing old points. Chief Apothecary has been updated for other SMfactions though.

**Comment by Thairne** [comment]
No idea why you think Chief Apothecary has wrong points.
Its the same 75 base, +35 as any other chapter.
