### ISSUE TITLE
Ork Nobz Kustom Shoota

### ISSUE THREAD

**Issue by mrgooby** [BSData/wh40k-9e#9973]
**File/Catalogue:** Warhammer 40.000 v9.1.36

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Ork Nobz cant equip Kustom Shoota

![ork nobz bug](https://user-images.githubusercontent.com/85652779/121443000-f8b2bd80-c98c-11eb-8197-da0df7f6cad8.jpg)

![ork nobz bug datasheet1](https://user-images.githubusercontent.com/85652779/121443016-ff413500-c98c-11eb-8ffb-ccda8259fb5c.jpg)

![ork nobz bug datasheet2](https://user-images.githubusercontent.com/85652779/121443023-023c2580-c98d-11eb-9a5b-d9f6f404eb4a.jpg)

**Comment by Technoblazed** [comment]
Wahapedia should not be used as a rules reference. Furthermore the screenshots you have provided apply to the 8th edition rules, not the 9th edition ones. They can no longer take a kustom shoota.

**Comment by mrgooby** [comment]
OK, i see what you mean! i still had the old wahapedia from 8th edition in my bookmarks! Sorry for the hastle!
