### ISSUE TITLE
Tyranids: Devourer has incorrect points cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9974]
**File:** Tyranids.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Points cost on tyranids devourer weapon no reduced .

**Comment by GenWilhelm** [comment]
As far as I am aware, devourers have not had any reductions recently.

According to the MFM 2021 Mk2, hive tyrants and carnifexes pay 10pts, warriors and primes pay 4, and termagants 2. This matches what the data file says, so please could you be more specific about where you're seeing the discrepancy?
