### ISSUE TITLE
NeonKatt- Techno pls this is the most important game breaking issue

### ISSUE THREAD

**Issue by NeonKatt** [BSData/wh40k-9e#9977]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

You spelled Halberd as "Halbred" either go all the way to Halbread or no, jk love you

**Comment by Thairne** [comment]
Jenius!

**Comment by Technoblazed** [comment]
Fixed in cd4e3cc0
