### ISSUE TITLE
Archaeopter

### ISSUE THREAD

**Issue by RespectableJack** [BSData/wh40k-9e#9984]
**File/Catalogue:** Adeptus Mechanicus

**BattleScribe version:** 2.03.15

**Platform:** iOS

**Dropbox:** Yes

**Description:** 
The Archaeopter's Command uplink is still the ild 8th ed codex version, needs to be updated to the 9th ed Admech codex version

**Comment by Technoblazed** [comment]
Fixed in 902333e3
