### ISSUE TITLE
Issues with allocations of special/heavy weapons on battltsisters troops

### ISSUE THREAD

**Issue by Muck1ng** [BSData/wh40k-9e#9986]
**File/Catalogue:** Adepta  sororitas

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux
iOS
**Dropbox:** Yes/No
Yes
**Description:** Detailed issue description.
A 10 person battle sister troop choice can have 2 special weapons at 10 models.  Currently this generates an error saying 1 too many. 

1-9 is 1 special or 1 heavy
10 is 1 heavy or special and + 1 special. 

Thanks for your work.

**Comment by Technoblazed** [comment]
The first point says 9 or fewer. If you have 10 models, you’re not 9 or fewer.

EDIT: You are limited to 1 of the battle sisters with special weapon (as intended), you need to add the "special or heavy weapon" if you want the "special or heavy weapon"

**Comment by Muck1ng** [comment]
Sorry. What I meant to say is the APP is letting me take 2 specials at 10 models with no errors.   I have a screenshot if I can send it on discord?

**Comment by Technoblazed** [comment]
Just attach the image to this issue thread

**Comment by Technoblazed** [comment]
From what I can tell, the app is correctly throwing errors if you take too many of the options.

![Image](https://i.tech-no.me/2021/06/12/210612124441.png)

**Comment by Muck1ng** [comment]
I realise what I’d done. Sorry. 

I just clicked + twice on special or heavy rather that selecting +special and +special and heavy.  

Nice work peeps
