### ISSUE TITLE
Imperium - Adeptus Mechanicus: Issue with Artefactotum stratagem

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9997]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The Artefactorum strategem doesn't require having an admech warlord, and should be available to any detachment regardless of whether or not you have an admech warlord.

**Comment by Technoblazed** [comment]
Artefactotum

> Select one SKITARII model in your army that has the word 'Alpha' or 'Princeps' in their profile and give them one of the following Arcana Mechanicum (this must be a Relic they could have)...

First line of the relics page

> If your army is led by an ADEPTUS MECHANICUS WARLORD, you can...
